osquery/osquery

- include/osquery/events.h
- osquery/events/events.cpp
- osquery/events/linux/audit.cpp
- osquery/events/linux/audit.h
- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/udev.cpp
- osquery/events/linux/udev.h
- osquery/events/tests/events_tests.cpp
- osquery/tables/utility/osquery.cpp
The UDEV tests for Linux call `osquery::attachEvents` several times. This causes event publishers to call their `::setUp` methods without a `::tearDown`, violating the events state guarantees. This will definitely lead to leaks.
> Fix UDEV publisher unit tests LSAN bug

- tools/make-win64-binaries.bat
The `/maxcpucount` causes Windows 2012R2 to run out of heap space. The MSBuild utility, when using `/MP` will spawn count(CPU) * 2 compiler processes.
Error encountered: `fatal error C1060: compiler is out of heap space`
Reference: https://msdn.microsoft.com/en-us/library/bb385193.aspx
Similar issue: https://github.com/appveyor/ci/issues/742
> Remove /maxcpucount from Windows build script

- osquery/dispatcher/scheduler.cpp
This implementation doesn't distinguish between different causes for the log path becoming invalid (e.g. directory removed vs log file assigned elevated permissions), which might be a worthwhile improvement(?) in the future.
> [Fix #2120] Request daemon shutdown when logger_path becomes invalid

- tools/provision.ps1
This should address #2466.
I need to test this on a few clean-slate hosts to ensure that this catches the pending reboots. There seems to be a few locations where one can find a Reboot Pending status for Windows, and I'm not sure I've caught them all.
> [Fix #2466] Reduced verbosity and added Pending Reboot Check

- osquery/tables/system/darwin/os_version.cpp
This adds the `version`, `platform`, and `platform_like` columns for OS X.
> Update os_version table on OS X

- Makefile
Now the builder may use `./build/darwin`, regardless of their minor version.
> [Fix #2698] Use build/darwin for all OS X builds

- osquery/extensions/extensions.cpp
There is a logic race when using `--extensions_require`. Currently the flag requires an extension's registry be broadcasted to the core, it does not require the extension's socket to be available for API access. If using:
```
osqueryi --extensions_require example -A example
```
The result is unpredictable without blocking until a valid `::ping` is returned.
> Require an extension socket with extensions_require

- include/osquery/database.h
- osquery/database/database.cpp
- osquery/database/plugins/ephemeral.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/sqlite.cpp
This `--database_in_memory` is an old flag that was never used.
> [Fix #2579] Remove database_in_memory flag

- osquery/tables/CMakeLists.txt
- osquery/tables/applications/darwin/browser_plugins.cpp
After lots of trials and tribulations, it seems `libarchive` cannot parse all of the Safari-supported XAR types. Moving our extraction and parsing to `libxar` works.
Tested that this does not leak. There are less-than-awesome APIs that do not allow us as much control over the content allocation, but it's no big deal in practice.
> [Fix #2702] Use libxar for safari_extensions parsing

- tools/deployment/make_osx_package.sh
RPMs are becoming more popular for package deployment on OS X.
> [Fix #2697] Create RPMs on OS X

- tools/deployment/make_osx_package.sh
This is a nitpick, to prevent confusion with CentOS-generated RPMs on OS X.
> packages: Add darwin to OS X RPM iteration

- docs/wiki/deployment/remote.md
- include/osquery/distributed.h
- osquery/dispatcher/distributed.cpp
- osquery/distributed/distributed.cpp
1. Some cleanups (visual/programmatic) to the Distributed code.
2. Appending a `statuses` top-level key to the distributed write API.
Failed distributed queries will now include an empty result set in their response. Additionally, a new key, `statuses` will include a key/value pair for each distributed query ID as the key. The value will be the SQLite response code from the query execution. Failed executions will include non-0 statuses.
> [Fix #2704] Various distributed code cleanups

- include/osquery/config.h
- osquery/dispatcher/scheduler.cpp
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
The `--events_optimize` flag was never intended to support multiple scheduled queries acting on the same events-based subscriber (the virtual table). This change allows optimization to occur on the query-level, not the subscriber.
> [Fix #2656] Refactor events_optimize to act per-query

- tools/provision/formula/cmake.rb
- tools/provision/formula/curl.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/python.rb
1. We bump the version of `curl` to force a rebuild and uninstall-before-reinstall-of-`openssl`. ;)
2. We bump the version of `openssl` from `1.0.2i` to `1.0.2j`.
3. We add a `version-script` to the linker to include the `1.0.0` ABI symbols (needed by the system `curl` on Ubuntu during the intermediate downloads before installing our local `curl`).
> [Fix #2726] Update OpenSSL to 1.0.2j and use linker versions

- Makefile
- mkdocs.yml
Strict-mode `mkdocs` requires us to list any additional CSS files staged in our `docs_dir`.
> mkdocs: Clean wiki during distclean and define extra_css

- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/aws_kinesis.h
- osquery/logger/plugins/tests/aws_kinesis_tests.cpp
@zwass could I get your opinion/assistance on this PR?  In short, there is an issue in the kinesis logger plugin where duplicate data gets sent to kinesis if there is an upload which partially fails.  
It may not seem too dire, but I have seen single endpoints send over 100k dup events over a 24h time period from just ~3k source events.  This typically happens in environments where kinesis is under heavy load and rate limit errors pop up.
With the current code path, when you receive errors like the following, osquery will resend all data (even the ones that successfully uploaded) until all data in the batch is successfully uploaded.
```
E1101 15:20:31.287334 4284416 aws_kinesis.cpp:111] Kinesis write for 5 of 140 records failed with error Rate exceeded for shard....REDACTED...
```
So in …
> Fix for sending only failed data to kinesis on full or partial failed uploads

- osquery/filesystem/fileops.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/windows/fileops.cpp
* Renamed `isNonWritable` to `isImmutable` to avoid confusion. `isImmutable` checks to see if the current file is impervious to changes with a check of its parent directory as well.
* Improvements on `platformChmod` to mimic POSIX behavior better
* Owner now always have the ability to delete the file and modify the file's DACL
* All users can at the minimum, read the file's DACL so `isExecutable` and `isImmutable` won't error out complaining about being unable to read the file's DACL
* `isImmutable` now works on files with the DACL modified by `platformChmod`
* Added new `platformChmod`, `isImmutable`, and `isExecutable` tests
> Improvements to platformChmod for closer POSIX behavior on Windows

- docs/wiki/deployment/file-integrity-monitoring.md
- osquery/tables/events/linux/file_events.cpp
If `file_accesses` is set in a config file, `osquery` doesn't collect stat-information of files.
```
$ cat /etc/osquery/osquery.conf
{
"schedule": {
"file_events": {
"query": "select * from file_events;",
"removed": false,
"interval": 3
}
},
"file_paths": {
"tmp": [
"/tmp/%%"
]
},
"file_accesses": ["tmp"]
}
$ sudo service osqueryd start
$ echo test >> /tmp/testfile
$ tail -n 3 /var/log/osquery/osqueryd.results.log
{"name":"file_events","hostIdentifier":"vagrant-centos65.vagrantup.com","calendarTime":"Thu Nov 10 08:04:54 2016 UTC","unixTime":"1478765094","columns":{"action":"OPENED","atime":"0","category":"tmp","ctime":"0","gid":"0","hashed":"0","inode":"0","md5":"","mode":"0","mtime":"0","sha1":"","sha256":"","size":"0","target_path":"\/tmp\/testfile","time":"1478765093","transaction_id":" …
```
> Do not calculate hash to avoid generating additional access events

- osquery/tables/system/posix/sudoers.cpp
- specs/posix/sudoers.table
I've done some profiling of this on my machine, and the statistics seem fine across the board. Please test on your machines as well.
Also, as per the original issue, there may be more useful things we can do with the different rule types/sections/etc, as opposed to the current implementation of two simple columns. Discussion of possible alternative implementations would be appreciated.
> [Fix #2396] New table: sudoers

- tools/provision.ps1
This looks for a special environment variable set on our build hosts: `OSQUERY_BUILD_HOST`. If this is found (with any value) the provisioning script will install the minimal build-tools from Visual Studio to save time.
> build: Install VS build tools on build hosts

- tools/provision/formula/augeas.rb
- tools/provision/formula/libxml2.rb
This adds hashes for `augeas` and `libxml2` for OS X 10.12.
> deps: Bottle updates for OS X: augeas, libxml2

- tools/provision/lib.sh
On OS X the `clang` compilers are installed to `/usr/bin/clang` and the `GCC` compilers are not present.
> deps: Only fallback to clang on Linux

- osquery/tables/system/darwin/tests/asl_tests.cpp
ASL is deprecated on OS X 10.12. The APIs are tested and pass but the actual query does not work. This inspects the `minor` version of the OS, if it matches `12` (macOS Sierra) the test is bypassed.
> OS X: bypass ASL tests on 10.12

- osquery/CMakeLists.txt
- tools/provision/formula/libaptpkg.rb
This updates `libaptpkg` to version 1.3.1. This is a significant change for the dependency as the build system moves from autotools to `cmake`. There are non-trivial changes required to (1) build without the documentation tools and (2) build a static library of just `apt-pkg`.
> deps: Linux: apt-pkg 1.3.1

- Makefile
Building dependencies on Apple OSs other than Sierra is very difficult and not supported. To help folks understand why there may be breakage, add a friendly reminder that we only test the build process on 10.12.
> [Fix #2748] Warn if building on OS X and not 10.12

- CMake/Packages.cmake
- tools/deployment/make_linux_package.sh
With the last several months of changes to the build system, every Linux binary can be transposed onto any other (as long as they are using a 2011+ `glibc` and running on `x86_64` hardware). Thus there is no need to isolate package building to the current-running-OS.
This commit changes `make packages` to build 4 packages:
* A DEB for upstart/initd hosts
* A DEB for systemd hosts
* A RPM for upstart/initd hosts
* A RPM for systemd hosts
We name the upstart package iterations: `14` and `el6` respectively for the last OS in the family to use upstart. The systemd packages are `16` and `el7` respectively.
> [Fix #2764] Attempt to build all packages on every Linux OS

- osquery/filesystem/fileops.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/windows/fileops.cpp
This commit fixes two bugs in the async PlatformFile read and write operations. If write successfully completed after one write operation, we return the number of bytes written as the operation completed successfully. When reading, we ensure to update the cursor position so subsequent reads read from the correct file offset.
> Updating bytes written and read cursor index

- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/tests/extensions_tests.cpp
- osquery/filesystem/fileops.h
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/windows/fileops.cpp
The goal is to remove as many `#ifdef`s for platform variance as possible.
This collapses `socketWritable` and the various checks for UNIX domain socket and Windows named pipe existence checks into a `socketExists`. There is a small complexity introduced in the form of a method overload using `remove_socket`.
If `remove_socket` is requested it is interpreted that the caller wants to know if the socket exists for removal with the intent of creating a new socket. This is used when an extension or extension manager (core) are first initializing.
> [Fix #2446] Consolidate namedPipe into socketExists

- tools/make-win64-binaries.bat
Previously, the `/maxcpucount` switch caused Heap exhaustion errors on the AWS Windows 2012R2 hosts. We should triage this more carefully and experiment with different machine types and `MSBuild` options.
> Restore the /maxcpucount switch for MSBuild

- osquery/filesystem/fileops.h
- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/windows/fileops.cpp
Improved `platformAccess` to use `AccessCheck` in lieu of `access`. Now, `platformAccess` and `PlatformFile::isExecutable` use a common utility function for its work.
> Improved platformAccess functionality and formatting in fileops

- packs/osx-attacks.conf
Our lazy-build release checks found errors in the packs: https://jenkins.osquery.io/job/osqueryMasterPosixPackages/13/TargetSystem=vm-osx12/console
The `file` table's `pattern` column was removed in version `1.7.1`. This cleans up the erroring queries and flattens the OceanLotus queries into 1.
> Remove pattern column from OceanLotus

- osquery/tables/networking/posix/interfaces.cpp
- specs/interface_details.table
We want to track drop packets.. 
osx doesn't have tx drops.. anyone knows why?
> add drop fields to interface details for linux/osx

- osquery/tables/system/linux/memory_map.cpp
This is the result of 1 round of `make fuzz`, the seed uses a basic PRNG, this just popped up. There's no existing risk as the input to `memory_map` is from `/proc`. But squashing this is good form and prevents future early-exits from `make fuzz`.
> Sanity check Linux memory_map offsets

- tools/deployment/make_osx_package.sh
The OS X launch daemon sets the `--flagfile` switch. If the value (path) does not exist, the daemon will error and quit. When the `-a` switch is given to `make_osx_package` the expectation is osquery will start upon package install.
> packages: Touch LaunchDaemon flagfile on OS X when autostarting

- tools/build.sh
To allow new jobs like `make fuzz` we want to build the `shell` target only.
We can achieve that with the CI build host entry point: `./tools/build.sh` if we allow it to skip building and running tests. The facility for building a single target exists using `RUN_TARGET`, but not skipping/running the tests. Other parts of the build system use `SKIP_TESTS`. This adds similar functionality.
> Allow tools/build.sh to SKIP_TESTS

- osquery/config/config.cpp
- packs/osx-attacks.conf
- tools/tests/test_release.py
To support "pretty" JSON in configuration and pack data, we support using `\\\\n` within the JSON content. Although JSON does not support this, we will replace the escape sequence when reading the content before applying parsers.
> Allow configuration JSON to include escaped newlines

- osquery/tables/system/posix/augeas.cpp
- osquery/tables/system/posix/tests/augeas_tests.cpp
- specs/posix/augeas.table
This renames the existing `augeas` table's `path` column to `node` and `filename` to `path`. This allows the table specification to mimic others such that `path` refers to a filesystem's path.
This diction is not "completely" perfect, but does a decent job: http://augeas.net/docs/api.html
We also allow the queryer to include `node =` and `path =` expressions in the predicate to better optimization the matching.
```
osquery> select count(1) from augeas;
+----------+
| count(1) |
+----------+
| 46131    |
+----------+
Run Time: real 2.434 user 2.408000 sys 0.024000
osquery> select count(1) from augeas where path = '/etc/hosts';
+----------+
| count(1) |
+----------+
| 27       |
+----------+
Run Time: real 0.830 user 0.820000 sys 0.008000
osquery> select count(1) from augeas where node = …
```
> Rename augeas path column to node

- docs/wiki/deployment/configuration.md
- include/osquery/config.h
- include/osquery/filesystem.h
- include/osquery/packs.h
- osquery/config/config.cpp
- osquery/config/plugins/filesystem.cpp
- osquery/config/tests/packs_tests.cpp
This introduces and documents a new syntax for `ConfigPlugin`s to retrieve pack content. Currently only the `filesystem` plugin supports the syntax (as it makes the most sense relatively). 
A config may specify a pack name `*` and filesystem globbing value. The `filesystem` plugin will read every file matching the value and assign a pack name as the path stem.
> [#1773] Introduce multi-pack configuration syntax

- osquery/events/linux/inotify.cpp
This fixes a crash in the file event processing path. It is possible that by the time a kernel file event is dequeued and the code hits createEventContextFrom() in inotify.cpp, the path from the descriptor_path_ map has been purged (say, by a remote config update from a TLS backend). This causes the code to crash when it dereferences the descriptor_path_ map in INotifyEventPublisher::createEventContextFrom.
The fix is to check for the existence of the descriptor_path_ after acquiring the path_mutex_. If not found the particular kernel event is effectively discarded.
> Fix crash in FIM processing

- osquery/events/linux/audit.cpp
- osquery/events/linux/audit.h
- osquery/events/linux/tests/audit_tests.cpp
- osquery/tables/events/linux/process_events.cpp
- osquery/tables/events/linux/socket_events.cpp
This adds 3 controls for Linux audit:
- The `backlog_wait_time`, the Hz to pause each enqueue within the kernel.
- The `blacklog_limit`, the size of the queue.
- The failure action.
When osquery terminates safely the default settings for audit are restored.
> Manage queue configuration for Linux audit

- tools/deployment/make_osx_package.sh
- tools/lib.sh
This fixes the aync tests in Jenkins that build `packages` and detect deterministic build failures.
> Fix deterministic and package build tests on OS X

- README.md
This updates the `README` to include references to Windows and to help clarify our perspective on the differences between **running** osquery and **building** osquery.
> Update build icons in README

- osquery/tables/networking/darwin/routes.cpp
Routes table doesn't show interfaces correctly. This is a small fix for that.
> [Fix #2731] Fix interface column in routes table on OS X

- tools/deployment/make_linux_package.sh
This PR contains a few minor bugfixes to the packaging script that I encountered while trying to get the osquery package to build on lucid. For reference, here is the [dockerfile](https://github.com/danielpops/osquery-lucid-build/blob/master/Dockerfile) I've been using to build on top of the ubuntu/lucid base image.
For the FPM thing, I originally was having difficulties getting FPM `gem install`ed with the apt-get installed version of ruby, so I decided to build the latest and greatest ruby from source. But then I observed the following failure when trying to build:
```
[+] creating deb package (for upstart)
/osquery/osquery/tools/deployment/make_linux_package.sh: line 220: /var/lib/gems/1.8/bin/fpm: No such file or directory
```
For the realpath thing, I'm actually not sure how it could …
> Lucid package build fixes

- include/osquery/system.h
- osquery/core/system.cpp
- osquery/filesystem/filesystem.cpp
`fseuid` management in OS X and Linux is not needed, `euid` and `egid` management is sufficient. 
See http://man7.org/linux/man-pages/man2/setfsgid.2.html for details.
> Remove fsuid permissions drop for OS X and Linux

- include/osquery/flags.h
- tools/provision/formula/gflags.rb
- tools/provision/formula/glog.rb
Thanks @ilovezfs for pointing out the breaking change. Unfortunately we "dip" into some opaque types in `gflags` making us a target for narrow API changes upstream.
There's not much to do here since one argument is now expressed as a template type (where `gflags` now explicitly generates the types, which is cool). We need to bump our internal `glog` to update linking expectations.
I expect this to break on Windows. A cursory look at `gflags`' headers did not show any version CPP macros unfortunately. This means we'll need to update the `glog` and `gflags` packages in Windows too. I know @PoppySeedPlehzr is in the process of updating several Windows dependencies already, what's 2 more?? ;)
> [Fix #2798] Update gflags on OS X/Linux to 2.2.0

- CMake/Packages.cmake
These are important, they add a safety check for older systems that may have installed newer C runtimes. That's ok, but we don't want to create a false sense of deployability.
> Keep Linux package dependencies for libc and zlib

- packs/osx-attacks.conf
Add xcode ghost iocs from:
http://researchcenter.paloaltonetworks.com/2015/09/novel-malware-xcodeghost-modifies-xcode-infects-apple-ios-apps-and-hits-app-store/
> add XcodeGhost dropped files

- Makefile
- docs/wiki/development/building.md
- tools/provision.sh
This breaks `make deps` into two commands:
```
make sysprep
make deps
```
When only the Vagrant targets and our CI provisioning should be running `make sysprep`.
Unfortunately, the `SKIP_DISTRO_MAIN` environment variable needs to mean the opposite, when you'll have to explicitly define it to `False` or `0` to prevent the skip. This is a legacy and opaque switch so it shouldn't be an issue.
> [#2816] Break make deps into sysprep and deps

- tools/provision/formula/rocksdb.rb
This bumps RocksDB on OS X and Linux to version 4.11.2. Windows is already using this version, also upgraded from 4.9.
> deps: rocksdb version 4.11.2 on POSIX

- osquery/extensions/tests/extensions_tests.cpp
Change argument name for function in order to remove warning about its declaration shadowing a member variable.
> Remove warning message during build

- tools/provision.ps1
We utilize a different chocolatey source internally, but we pull from chocolatey for numerous packages. This commit makes sure that we're explicit about which source we're pulling packages from.
> Explicitly set chocolatey source

- include/osquery/logger.h
- osquery/core/posix/process_ops.cpp
- osquery/core/process.h
- osquery/core/windows/process_ops.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/logger/logger.cpp
This fix resolves a deadlock condition as follows:
Thread calls a put operation in rocksdb
rocksdb acquires a mutex, mu_, in its write path.
rocksdb decides to flush, which has a LOG call in its path.
The LOG call calls GlogRocksDBLogger::Logv, which calls Google Log
Google Log decides to flush, which ends up making a call back to rocksdb put
The thread deadlocks on itself, since rocksdb's mutex is a fast (ie., non-recursive) mutex.
The recommended "thread safe" way for google logging is to use RAW_LOG_XXX method, which is what this PR does.
Unfortunately, the side effect of this is that rocksdb logs will not be sent to a TLS backend or to a File Logger. They will merely show up on stderr.
> Fix Deadlock in rocksdb log callback

- osquery/tables/system/linux/processes.cpp
This was reporting the offset from the documented `/proc/N/stat` field, we walk 3 items before splitting the `stat` details.
> Fix Linux processes table threads column

- osquery/tables/system/windows/patches.cpp
- specs/windows/patches.table
Ahoy friends! I will have a future need to have some reporting around what patches might be installed on a given windows computer. This thing you guys built just happens to have a nice way to do that, so I selfishly added this instead of filing an issue that @PoppySeedPlehzr may or may not have time to work on in the future 😆 
Kudos for making it easy, the docs were fairly easy to follow along although I find myself having to rebuild everything every time (though that is probably because I am OCD on arranging the schema 😉 )
Also not super sure how to test, but I made it pass the compiler, linker, tests, and got this lovely output on my computer:
```
PS C:\> C:\Users\svmastersamurai\github\osquery\build\windows10\osquery\Release\osqueryi.exe
Using a virtual database. Need help, type …
```
> [windows] add virtual table for patches

- osquery/config/plugins/tests/tls_config_tests.cpp
- osquery/config/plugins/tls.cpp
- osquery/config/plugins/tls.h
- osquery/remote/enroll/enroll.cpp
- tools/tests/test_http_server.py
This PR is the split from PR 2560, and covers:
1. A new option, --config_tls_enroll_on_startup, which forces osquery to do an enroll with a remote TLS server on startup.
2. A new option, --disable_host_id_cache, which ignores the host uuid cached in the rocksdb database, and instead gets it directly from the system. Useful when VM images (with existing rocksdb databases) are copied around.
For a longer discussion, please see PR 2560
> Enroll on startup and disable host uuid cache options

- osquery/database/plugins/rocksdb.cpp
This improves RocksDB's write times and overall exceptional impact on the system when using the `system_stress` and Audit benchmarks.
Average impact with `N=10` (before):
```
resident_size = 24404000
total_size = 783816000
user_time = 1077
system_time = 406
```
Average impact with `N=10` (after):
```
resident_size = 30244000
total_size = 581640000
user_time = 743
system_time = 235
```
Compared to using internal structures that bypass RocksDB:
```
resident_size = 27908000
total_size = 499476000
user_time = 647
system_time = 70
```
A subsequent read stress using several `group by` predicates uses high RSS. This is the same with RocksDB and using internal ephemeral structures (`--disable_database`) and is most likely related to the SQLite balloning issue we've created.
> Improve RocksDB thread usage and write stalls

- docs/wiki/installation/cli-flags.md
- osquery/logger/plugins/syslog.cpp
Several syslog parsers (e.g. rsyslog, syslog-ng) rely on the existence of a `@cee:` cookie prepended to the log message payload to indicate that the remainder of the message is a parseable JSON message. This PR is to add support for prepending the cookie by the flag `logger_syslog_prepend_cee`.
> Add a flag for prepending @cee: to json-logged messages to syslog

- docs/wiki/installation/cli-flags.md
- osquery/core/tests/watcher_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
This introduces `--watchdog_memory_limit` and `--watchdog_utilization_limit`, see the updates to the wiki (included) for a few more details.
> [#2736] Add memory and utilization limit override flags

- osquery/core/windows/wmi.cpp
- osquery/core/windows/wmi.h
- osquery/tables/networking/windows/win_sockets.h
- osquery/tables/system/windows/wmi_cli_event_consumers.cpp
- osquery/tables/system/windows/wmi_event_filters.cpp
- osquery/tables/system/windows/wmi_filter_consumer_binding.cpp
- osquery/tables/system/windows/wmi_script_event_consumers.cpp
We (the MSVC compiler team) use the OSQuery project as part of our
"Real world code" tests.  I noticed a few places in your windows
specific code where your build would fail if you used the
/permissive- switch because of language conformance issues.
for more information on /permissive- see our blogpost:
https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/
I have not added/modified any tests because this does not change
behavior.
There are two types of language conformance issues fixed in this:
1) Strict string conversion (this is also covered by the /Zc:strictStrings flag)
The 'const' is not implicitly dropped by string literals, which means the following is not allowed:
//BSTR is a wchar_t*
BSTR str = L"const string literal"; //error: cannot convert a 'const wchar_t*' to …
> C++ conformance fixes (MSVC /permissive-)

- osquery/filesystem/darwin/plist.mm
- osquery/tables/system/darwin/packages.cpp
`NSString` and `NSNumber` may return empty raw pointers. This fix checks the internal raw pointer (`[value UTF8String]`) before attempting a `std::string` conversion.
> [Fix #2862] Fix plist NSString raw pointer string conversion

- osquery/tables/system/linux/cpu_time.cpp
Fixes cpu_time table for redhat and centos 6.x. /proc/stat on those platforms is only guaranteed to have the first 8 fields.
> Fix cpu_time for centos 6.8

- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
Based on the recommendation of other osquery aws users, we feel it is best to remove the aws kinesis and firehose stream name checking.  The current method we use (describe stream) and the past method (list streams) have pretty nasty rate limits of around 5-10 RPS.  This can cause dos of osquery agents if you are doing a large rollout that is not staggered.
Docs for the rate limits can be found here:
http://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html
I have tested this check removal and all seems fine.  There is however some work that may need done on the logging for partial failed uploads as the info it logs may not be accurate.  Ill check that code path at a later time as it will be a bit more work.
Ultimately, this change seems safe and I have not seen any …
> Removed stream name checking for aws kinesis and firehose setup

- osquery/tables/system/darwin/smbios_tables.cpp
The `address` field in the `romN` IOKit property may not exist.
> Fix OS X platform_info address column

- Makefile
- requirements.txt
`make docs` should follow the existing make targets and use a dedicated directory within `./build`.
> make docs: Use build/docs folder

- tools/analysis/system_stress.py
This adds a utility function to stress the system. This can be used adhoc with testing several publishers, like `audit`. It's design to spawn lots of processes, with lots of network connections. It's currently missing large memory allocations and filesystem thrashing.
> Add system stress test

- packs/osx-attacks.conf
I went through the compilation of OSX malware for 2016 (https://objective-see.com/blog/blog_0x16.html) and reviewed the `osx-attacks.conf` pack, to make sure we have them all covered.
> Add launchd name for OSX_Keydnap

- include/osquery/config.h
- osquery/config/plugins/tests/tls_config_tests.cpp
- tools/tests/test_http_server.py
This adds a test to run the config updater (from the TLS plugin as an example) alongside the scheduler runner. If there is a critical section here, this and TSAN will find it.
> Add a TLS config plugin test that runs the scheduler

- osquery/tables/system/uptime.cpp
On my laptop:
```
C:\Users\marpaia\git\osquery [uptime ≡]> .\build\windows10\osquery\Release\osqueryi.exe
osquery> select * from uptime;
+------+-------+---------+---------+---------------+
| days | hours | minutes | seconds | total_seconds |
+------+-------+---------+---------+---------------+
| 0    | 8     | 29      | 51      | 30591         |
+------+-------+---------+---------+---------------+
osquery>
```
close #2905
> Uptime implementation on Windows

- osquery/core/init.cpp
- osquery/core/posix/process.cpp
- osquery/core/posix/process_ops.cpp
- osquery/core/process.h
- osquery/core/system.cpp
- osquery/core/watcher.cpp
- osquery/core/windows/process.cpp
- osquery/core/windows/process_ops.cpp
Assuming a child worker will exit within `--alarm_timeout` seconds, we at-most wait another second for the process to stop after a watcher signals.
> Allow watchdog watcher to wait for child exits

- tools/tests/test_additional.py
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/utils.py
The 0.10.0 Thrift Python module (auto-installed through pip updates) requires transport connections to be `.close`d before their `.open` will return success. In our tests we use an expect/assert model to apply timeouts and intervals for checking transport statuses; first expect with timeouts, then asset without. The initial expect, when true, blocks subsequent checks.
> [Fix #2912] Close initial Python thrift connections

- osquery/core/init.cpp
- osquery/core/posix/process.cpp
- osquery/core/process.h
- osquery/core/watcher.cpp
- osquery/core/windows/process.cpp
This adds a new method to the `PlatformProcess` API: `killGracefully` that should be implemented on each platform to ask an osquery worker process to stop. On POSIX this uses `SIGUSR2`, the worker process should catch this signal and shutdown cleanly.
> Allow POSIX to gracefully stop workers

- osquery/tests/test_additional_util.cpp
The `TLSServerRunner` class queries `listening_ports` every 100ms to check for the spawned server to have begun listening on the requested TCP port. Normal execution will apply caching of the results rendering them useless.
This commit reduces time-to-test for `osquery_additional_tests` from 42 to ~12.
> Disable query caching in TLSServerRunner

- include/osquery/core.h
- include/osquery/dispatcher.h
- include/osquery/events.h
- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/sqlite.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/tables/system/linux/groups.cpp
- osquery/tables/system/linux/user_groups.cpp
- osquery/tables/system/linux/users.cpp
This moves almost all use cases of `std::mutex` to `std::shared_timed_mutex` under the alias of `Mutex` for simplicity. We then add a unique/exclusive write lock as `std::unique_lock`, the companion `ReadLock` is a `std::shared_lock`.
This is run under `SANITIZE_THREAD=1 make sanitize; make test` on Linux.
> Move Mutex to shared_timed_mutex and add ReadLock

- include/osquery/database.h
Just a quick typo fix that I came across.
> Superfluous "d" in a doc block

- osquery/tables/system/darwin/process_open_descriptors.cpp
- osquery/tables/system/darwin/processes.cpp
Fixes #2849.
This is a small fix to Darwin's `processes` table, the `on_disk` column is now calculated correctly. For non-Zombie processes the first address in the process's memory map is used for the EXE program path.
The `threads` column is now casted correctly too.
> Fix Darwin processes on_disk and threads column

- osquery/config/parsers/decorators.cpp
Decoration population/execution will execute queries and store results in the decorator config parser plugin. Status logs may be generated while executing queries, these will query the current decorator content (at that point, the previously-existing results). The current implementation includes a dead lock.
1. Run decorators (write lock)
2. Query
3. Run tables
4. Log
5. Get decorators (write lock)
The new implementation avoids a dead lock
1. Run decorators
2. Query
3. Run tables
4. Log
5. Get old decorators (write lock)
6. (release lock)
7. Store new decorators (write lock)
The new implementation further improves the logic by changing the *Get decorators* step to use a read lock.
This should fix: #2910, it may also fix @morrigan's issue from #1277
> Fix deadlock in decorator execution

- osquery/core/init.cpp
- osquery/logger/CMakeLists.txt
- osquery/logger/logger.cpp
- osquery/logger/plugins/stdout.cpp
This allows the "tee" of LOG lines output to `stderr` to be controlled by CLI flags and configuration options.
We should follow up with a change to the systemd service and stop stderr output. This will isolate the location of osquery status log lines to the osquery logger pipeline.
> Do not control stderr teeing automatically

- tools/provision/formula/glibc-legacy.rb
- tools/provision/formula/glibc.rb
Update URLs in the "glibc" and "glibc-legacy" provision scripts to point at mirrors with higher reliability.
> [Fix #2881] Update glibc source URLs

- osquery/core/posix/process.cpp
- osquery/core/watcher.cpp
This fixes a bug introduced in 2.2.2 that will cause the watcher process to exit if an autoloaded extension fails.
> Do not exit watcher after failed autoloaded extensions

- packs/osx-attacks.conf
Add the IOCs (Launch Agent) for OSX Backdoor - https://blog.malwarebytes.com/threat-analysis/2017/01/new-mac-backdoor-using-antiquated-code/
Not sure if we would want to look for the ~/.client file but it should be located in the users home directory if we go off the plist file in the blog post:
com.client.client.plist:
`<string>/Users/xxxx/.client</string>`
possible query:
`"select * from file where path = '/Users/%/.client'"`
> Add Quimitchin backdoor IOCs to osx-attacks pack

- osquery/core/init.cpp
The daemon (and osquery in general) implements its own logging pipeline. For systems capturing service stderr output we have the potential to duplicate log content. The daemon should not output INFO and WARNING messages to stderr, these should go through the normal logger flow. The ERROR logs may be important to capture in os_log or syslog.
> Emit only ERROR logs to osqueryd stderr

- docs/wiki/installation/cli-flags.md
- docs/wiki/installation/install-osx.md
Adds `logtostderr` and `stderrthreshold` to the CLI docs page.
> Add stderr control to CLI docs

- include/osquery/database.h
- include/osquery/distributed.h
- include/osquery/sql.h
- osquery/database/benchmarks/database_benchmarks.cpp
- osquery/database/database.cpp
- osquery/database/tests/results_tests.cpp
- osquery/distributed/distributed.cpp
- osquery/sql/sql.cpp
- osquery/tests/test_util.cpp
- osquery/tests/test_util.h
For queries received via distributed_read, the returned columns are always in alphabetical order, instead of the order specified by the query. In addition, a column that is repeated - eg., select pid,name,pid,cmdline from processes - will only return one instance of the pid column. This is a great inconvenience to anyone issuing queries interactively over distributed_read.
The root cause is that the query results are stored in data structures of type Row (database.h), which is defined to be of type std::map. Maps will, by design, store things in order, and not allow duplicate keys.
This PR fixes this by keeping track of a new data structure of type ColumnNames, which is a vector of column names. When the query result is returned, the vector is used to serialize the result in the order …
> Fix column order and repeated columns in distributed query

- osquery/tables/system/windows/registry.cpp
We encountered a bug a while back with our internal deployment, where we were scheduling queries against the Windows HKEY_CURRENT_USER registry hive. This seemed like a perfectly valid thing to do, until you remember that HKEY_CURRENT_USER doesn't exist for a service running as `SYSTEM`. The fix was to query `HKEY_USERS`, and append the SID of the users of interest. A query might look something like:
```
> select username, uuid, hive || key, mtime, data from registry, users where hive='HKEY_USERS' and key=uuid || "\Environment";
```
Note: this query has a bug - will fix tomorrow when I have the working version in front of me -.-;
> Adding warning line for registry queries against HKCU

- tools/tests/test_http_server.py
Noticed that much of the output from test_http_server.py was getting lost from LastTest.log; similarly, running osquery_additional_tests from cmd line and redirecting the output to a file would lose the test_http_server.py output. This is because python script output is buffered, and on kill (which is how we terminate test_http_server.py from TlsServerRunner::stop), stdout/stderr is not flushed. 
Fixed by adding a flush call after every output. A bit expensive, but not that SIGKILL cannot be hooked.
With this PR, the output from test_http_server.py is available in LastTest.log whenever you run make test
> Fix test http server output getting lost

- osquery/tables/networking/darwin/wifi_status.mm
- osquery/tables/networking/darwin/wifi_survey.mm
- specs/darwin/wifi_scan.table
- specs/darwin/wifi_status.table
This returns the country code (ISO/IEC 3166-1:1997) for each network found.
> Add country_code to wifi_status and wifi_survey tables.

- osquery/logger/logger.cpp
- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
There's an untested regression from: https://github.com/facebook/osquery/commit/b2a90cd6e4b3b5813730a87fd5c5ce122c9cf289 that causes GLOG files to be created in `/tmp/` when the `filesystem` logger plugin is NOT used.
> Use logtostderr in initStatusLogger

- include/osquery/database.h
- include/osquery/logger.h
- osquery/core/posix/process_ops.cpp
- osquery/database/database.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/tests/rocksdb_tests.cpp
- osquery/database/plugins/tests/sqlite_tests.cpp
- osquery/database/tests/database_tests.cpp
- osquery/database/tests/plugin_tests.cpp
- osquery/database/tests/plugin_tests.h
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/tests/scheduler_tests.cpp
- osquery/logger/logger.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/sqlite_util_tests.cpp
This is a work-in-progress feature that allows the scheduler to reset the database plugin and SQL plugin arenas. The goal is to smooth persistent memory allocations over several-day windows.
> Introduce scheduler reload feature

- tools/codegen/templates/foreign.cpp.in
- tools/tests/test_osqueryi.py
The `--enable_foreign` flag is used for the shell and daemon to expose the schemas for all virtual tables. These tables are not attached to valid generate functions. Instead they use "blank" plugins that only describe the column and table attributes. They can be added to the registry.
This fixes a regression added with a refactor to the registry APIs. It also adds a test for the feature.
> registry: Fix enable_foreign and add test

- osquery/core/tests/watcher_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
If an extension fails to load during autoload it will not be retried (there is a bug in the retry logic). This fixes the bug and retries the failed extension (3 more times).
> Allow autoload extensions to retry loading

- include/osquery/extensions.h
- osquery/core/init.cpp
- osquery/extensions/extensions.cpp
If there are multiple shell's using `~/.osquery/shell.em` this will append a random word to the end.
> extensions: Select ephemeral path for shell socket

- docs/wiki/installation/cli-flags.md
- include/osquery/system.h
- osquery/core/system.cpp
- osquery/tables/utility/osquery.cpp
- specs/utility/osquery_info.table
As discussed in #2819, this PR introduces two new host identifier
options:
- instance: an instance-unique UUID generated at process start,
persisted in the backing store.
- ephemeral: an instance-unique UUID generated at process start, not
persisted.
This PR also adds the following columns to the `osquery_info` table:
- `uuid`
- `instance_id`
```
$ ./build/debug_darwin/osquery/osqueryi --database_path=/tmp/db
osquery> select uuid, instance_id from osquery_info;
uuid = B312055D-9209-5C89-9DDB-987299518FF7
instance_id = be85e03b-1ae9-473a-989e-666351030e30
$ ./build/debug_darwin/osquery/osqueryi --database_path=/tmp/db
osquery> select uuid, instance_id from osquery_info;
uuid = B312055D-9209-5C89-9DDB-987299518FF7
instance_id = be85e03b-1ae9-473a-989e-666351030e30
$ …
```
> Introduce two new host identifier options

- osquery/config/plugins/tls.cpp
- osquery/config/plugins/tls.h
If pulling down a configuration fails, it will changes the delay speed to the value set by `config_tls_accelerated_refresh` to allow smaller delays and thus less time with broken configurations.
> Adding success awareness to TLS config plugin

- osquery/core/system.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/events/darwin/kernel_util.cpp
- osquery/events/events.cpp
- osquery/extensions/extensions.cpp
Follow-up to PR #2823
Change the logging level used in a number of locations in the code base, to better capture priority of each message.
Primary changes are cases of LOG(INFO) to VLOG(1), with a few occurrences of LOG(INFO) to LOG(WARNING).
> Change logging level in certain cases

- CMakeLists.txt
Sanitize builds are failing since LTO was enabled.
> sanitize: Gate LTO to non-sanitize builds

- osquery/filesystem/windows/fileops.cpp
This makes the necessary changes to the osquery code base to support Windows 7 x64. To get the binaries running on Windows 7 x86 requires repackaging of all of our third party libs, which is do-able, but at the potential cost of stability.
Further, when I built this on Windows 7 x64 I was getting a single test fail with file perms, however this test fail didn't seem to exist on Windows 10 so there may have been an environment issue.
Lastly, I have not tested any of this on Server 2008. I'll get some VMs up and running and see if the changes apply, but I'm confident they will.
> Converting fileops to support Windows 7

- include/osquery/core.h
- osquery/remote/transports/tls.cpp
- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
Now, on macOS:
```
$ ./tools/deployment/make_osx_package.sh
[+] notice: no config source specified
[+] using /Users/marpaia/git/osquery/tools/deployment/com.facebook.osqueryd.plist as the launchd source
[+] copying osquery binaries
[+] copying osquery configurations
[+] finalizing preinstall and postinstall scripts
[+] creating package
[+] package created at /Users/marpaia/git/osquery/tools/deployment/../../build/darwin/osquery-2.2.3-15-g2f6c8f5.pkg
[+] Skipping OS X RPM package build: Cannot find fpm and rpmbuild
[+] skipping kernel package, no kext found
$ pkgutil --payload-files ./build/darwin/osquery-2.2.3-15-g2f6c8f5.pkg
.
./private
./private/var
./private/var/log
./private/var/log/osquery
./private/var/osquery
./private/var/osquery/com.facebook.osqueryd.conf …
```
> Bundle cURL PEM into packages

- docs/wiki/installation/install-windows.md
The Windows installation documentation was lacking in the clarity of what exactly was happening during the `choco install osquery` process, as well as what steps were required to get the daemon up and running with default configuration files. This diff attempts to improve that.
> Updating the windows installation docs

- Makefile
- osquery/sql/sqlite_util.cpp
- osquery/sql/tests/sqlite_util_tests.cpp
First this fixes a locking order in the SQLite connection manager's new `resetPrimary` method. This also enhances the `test_reset` test that had been comparing pointer values. This is undeterministic, the new test creates a view then tests to assure the view does not exist after resetting.
> sql: Reorder SQLite manager mutex locking

- osquery/core/init.cpp
On OS X, when replacing the worker's `argv`, spaces will continue to show in various process listings. This is odd for invocations of `osqueryd` with long argument lists. It will appear that the worker includes a newline.
> worker: Prefer null character over spaces when clearing argv

- osquery/filesystem/tests/fileops_tests.cpp
Several build hosts cannot allocate 200M * 2 of contiguous memory so this test becomes flaky. If we reduce to 20M we reduce the chance of failure-- and still pass normal 4k or 4m read chunking.
> tests: Reduce large file test to 20M

- requirements.txt
- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
This adds the `timeout_decorator` module to the local Python. The run loop for Python `unittests` is now wrapped with a 20minute timeout. Usually, builds will fail the 2-hour timeout because of a single long-running test. It's better to fail that test and reclaim some of the 2-hour window.
> tests: Add global 20min timeout for python tests

- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
The extensions API is very async, but there is an internal resource that is not protected. This adds locking around the internal extension state.
> extensions: Gate access to resource state within Handler

- include/osquery/core.h
- tools/deployment/make_osx_package.sh
This is a quick fix, supersedes: #2974.
> packages: Use /var/osquery on OS X for home

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
To bring our internal chocolatey package recipe up to speed with our external, we need to make some checks for an existing installation as we don't _currently_ make use of the `upgrade` functionality. This diff checks for an existing Chocolatey installation before proceeding to install a newer version, as we require removing the Deny-Write ACLs from the installation folder before dropping the new version.
> Add checks for existing installation to chocolatey installer

- tools/deployment/chocolatey/tools/chocolateyuninstall.ps1
By default, we install the osquery path to the `Machine` PATH variable. This was not being removed correctly on uninstall, and this PR fixes that.
> Chocolatey uninstall should remove path from Machine path

- osquery/tables/system/linux/memory_map.cpp
Fixed 1, but now the dynamic analysis breaks on the following line. We need to cover `b2` too.
> linux: memory_map additional out of range check

- docs/wiki/installation/cli-flags.md
- osquery/tables/events/windows/windows_events.cpp
This PR Address #2980 by changing the hard coded channels we automatically subscribed to into default flag values. This should allow folks to subscribe to as many _or as few_ channels as they'd like.
> Moving default channel list to default flag value

- tools/deployment/make_linux_package.sh
Check that the input source exists, not the destination.
> packages: Fix installing certs on Linux

- CONTRIBUTING.md
> This is what the new Code of Conduct section looks like in rendered markdown
In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.
Examples of behavior that contributes to creating a positive environment
include:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members …
> Updating to Code of Conduct to CC 1.4

- osquery/CMakeLists.txt
This adds the compiler and linker flags necessary to enable control flow guard on the Windows build of osquery.
> Enable Control Flow Guard on Windows

- CMake/Packages.cmake
- tools/deployment/make_linux_package.sh
This initial implementation installs all three files `/etc/init.d/osqueryd`, `/etc/{sysconfig | default}/osqueryd` & `/usr/lib/systemd/system/osqueryd.service` to the appropriate location (based on whether the system is Debian based or CentOS based), then runs a helper script to remove the extraneous files (based on the init system running on the target machine).
> [Fix #2816] Build single DEB/RPM package

- tools/docker/Dockerfile
I created this Dockerfile to be able to compile a linux version of the project source. After some discussion with @theopolis in Slack, I'm adding it here for review and to generate some discussion. 
There are a few reasons you might want to run osquery in a container. 
* Testing agents during development of a TLS server. @zwass created [CentOS and Ubuntu containers](https://github.com/kolide/docker-osquery) very early on in the development of the kolide TLS endpoints, which proved to be very useful. Eventually, I wanted to start testing not just the latest stable version of osquery, but to try catching any regressions that might come up, by creating a nightly build. The Dockerfile in this PR is one of my attempts. 
* It is possible to schedule osqueryd as a [kubernetes …
> add Ubuntu Dockerfile to build osquery

- packs/vuln-management.conf
Added `opera_extensions` table to the `vulnerability-management` pack and also updated some fields for other browser related tables, like the platform and the version when they join another table with a column introduced later.
> Update vulnerability-management pack

- packs/osx-attacks.conf
Adding detection for ProntoApp Launch Agents: 
https://malwarefixes.com/remove-pronto-video-converter/
> Update osx-attakcs pack: Adding ProntoApp

- include/osquery/core.h
- osquery/CMakeLists.txt
- osquery/sql/sqlite_util.cpp
- tools/provision/formula/boost.rb
With 2.3.2 OS X 10.10 will load not lazy-load shared libraries due to a missing `shared_mutex` implementation (C++14). We can use Boost's shared mutex timer code instead.
> darwin: Use boost shared_mutex for OS X

- tools/provision/formula/boost.rb
- tools/provision/formula/cpp-netlib.rb
This fixes an odd change in the `boost::optional` API with the upgrade from 1.60->1.63 (confirmed it is the 1.63 release over 1.62). The issue appears in our use of the `cpp-netlib` and oddly the boost xpressive library.
> deps: Upgrade boost to 1.63 and patch optional usage

- osquery/logger/plugins/aws_util.cpp
This supersedes #3004.
Add several 'missing' regions to the existing AWS Kinesis plugin.
> Add additional regions to AWS Kinesis

- osquery/core/windows/process_ops.cpp
- osquery/tables/system/windows/users.cpp
The users table will now first scan for any profiles existing on the local computer. This will give us all roaming profile users (AD accounts), as well as most local users. Lastly, we do a sweep for any accounts that have not yet established a profile on the machine, such as users _just_ made with `net add <user>`
> [Fix #2989] Updating users table to pickup users with no profile

- osquery/tables/system/linux/smbios_tables.cpp
I haven't been able to reproduce a crash here, but the code looks nasty. The VMs/AMIs do not boot EFI so they do not fuzz this code path. On a VMware EFI-booted Ubuntu 14.04 the previous implementation was not crashing (even after removing the early break from scans to `0xFFF0`).
> linux: Fix SMBIOS reading from EFI systab

- osquery/remote/transports/tests/tls_transports_tests.cpp
- tools/provision/formula/boost.rb
- tools/provision/formula/cpp-netlib.rb
This moves us to the `0.13.0` branch of `cpp-netlib` and that includes a patch for IPv6 with HTTPS.
> deps: Add patch to cpp-netlib for HTTPS IPv6

- osquery/remote/transports/tests/tls_transports_tests.cpp
Windows 2012R2 is failing the verify-peer test correctly, but with a different error message.
> remote: Edge case for Windows 2012 errors

- external/CMakeLists.txt
- osquery/devtools/printer.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
Several changes to enable building "external apps" using the `make external` make target. This target was originally scoped to only produce extensions and modules (C++), but some projects want to build another binary, similar to the shell or daemon. We handle this already with a 'catch-all' that runs your custom `CMakeLists.txt` in an `./external/project_name` subdirectory. However, to link surgically against what we consider the SDK and pull in some tables these reorganizations are needed.
> external: Enable external applications through make externals

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/plugins/filesystem.cpp
Adds a `--config_filesystem_refresh` option that does the same thing as `--config_tls_refresh`. If set, tells osquery to re-read the configuration on disk every <arg> seconds.
The code has been copied wholesale from the tls plugin. Thoughts on just having the base `Config` class expose an auto-refresh option instead?
> Allow reloading config from disk

- docs/wiki/deployment/configuration.md
Updated configuration documentation with instructions on how to configure prometheus targets to be queried when running queries against the ["prometheus_metrics"](https://github.com/facebook/osquery/pull/2925) table.
> prometheus_metrics: add wiki documentation for configuration

- osquery/tables/system/cpuid.cpp
This adds several additional CPUID feature flags to the `cpuid` table.
> Add SMEP/SMAP and other CPUID features

- osquery/tables/applications/browser_utils.cpp
An initial attempt at addressing #3011 
This is the first time I've written any C++, please make sure I didn't do anything stupid. I'm very open to feedback.
When `default_locale` is present in a `manifest.json`, genExtension now reads the contents of `path/_locales/<value of deafult_locale>/messages.json` into another propertytree. When populating row data, it looks for values prefixed with `__MSG_`, strips them, and then tries to match to a value in this messages.json-based propertytree. If there's no match, it falls back to supplying the raw value, which is how this function has worked thus far.
One limitation is that currently, the variable in manifest.json is case-sensitively checked against the key in messages.json. Most extensions in my testing match case, but one in particular …
> chrome_extensions table with basic localization support

- docs/wiki/development/windows-provisioning.md
Installing boost-msvc14 1.59.0 can result in a time-out error. This information is to prevent it from happening.
Cc: @mjpieters
> added a note for preventing time-out error

- packs/hardware-monitoring.conf
Some new tables were never added to the packs, in this case `hardware-monitoring.pack`. Also some intervals and platforms needed a bit of tweaking and newer tables were added too (ex: Windows)
This has been tested with the following configuration:
```
$ cat /tmp/osquery.conf
{
"options": {
"config_plugin": "filesystem",
"logger_plugin": "filesystem",
"logger_path": "/tmp/osquery",
"pidfile": "/tmp/osquery/osquery.pidfile",
"events_expiry": "3600",
"database_path": "/tmp/osquery/osquery.db"
},
// Define a schedule of queries:
"schedule": {
// This is a simple example query that outputs basic system information.
"system_info": {
// The exact query to run.
"query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
// The interval in seconds to run this query, not an exact …
```
> Updating hardware-monitoring pack with new intervals, platforms and queries

- tools/provision.ps1
The default value of execution-time is 2700 seconds. Increasing this value to 7200 seconds will prevent time-out error for most of the people.
> increased execution-time value

- packs/it-compliance.conf
New queries for the pack `it-compliance.pack` to cover the Windows platform and a couple of tweaks to more accurate platform selection.
> Updating it-compliance pack with windows queries

- tools/deployment/make_osx_package.sh
For some reason the package binaries end up being tagged `i386` for darwin RPMs. This is consistent with other deployments of RPM/yum on macOS.
> packages: Use i386 for the darwin RPM

- osquery/extensions/interface.cpp
Testing to see if this include is needed for any OS build.
> Remove include of thrift/TOutput

- osquery/database/plugins/rocksdb.cpp
For long running `osqueryd` processes that process lots of events within a 2-hour period, the `MANIFEST` transaction log may grow to 1G+ in size. We do not need to maintain replays beyond 500KB.
> rocksdb: Set a max size for RocksDB MANIFEST logs

- tools/analysis/profile.py
- tools/tests/utils.py
The newer version of `psutils` can throw a zombie exception, in most cases we are waiting for the process to become a zombie and must handle this. The tests should also be performed without extensions (when checking leads/etc) as the tooling does not handle profiling of child processes.
> profile: Fix Zombie check and disable extensions

- CMake/Packages.cmake
- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
This attempts to build a `pacman`-type packages on Linux with `make packages`. It will require a newer (1.6+) version of `fpm` and `bsdtar` installed.
> packages: Build ArchLinux package on Linux

- include/osquery/extensions.h
- include/osquery/sql.h
- osquery/sql/sql.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/sqlite_util_tests.cpp
This adds a new automation API method to the `SQL` implementation plugin. The only available built-in plugin, SQLite, is updated to include its implementation too.
`getQueryTables`: will return all of the _actual_ virtual tables scanned by a query.
This new API forces a unit test and has discovered a bug in the `QueryPlanner` abstraction, which is used to help identify the types of columns used in a query.
> Add getQueryTables to inspect tables scanned

- include/osquery/database.h
- include/osquery/events.h
- osquery/database/database.cpp
- osquery/database/plugins/ephemeral.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/sqlite.cpp
- osquery/database/tests/plugin_tests.cpp
- osquery/database/tests/plugin_tests.h
- osquery/events/benchmarks/events_benchmarks.cpp
- osquery/events/events.cpp
- tools/provision/formula/rocksdb.rb
This updates RocksDB to v5.1.4 on Linux/macOS and introduces `DeleteRange` for expirations in events. This allows us to bulk-remove event data when events are buffered beyond the configured max.
This also disables the WAL for writes to events and forces a flush when the database is closed.
> rocksdb: Update to 5.0 and use DeleteRange for expirations

- tools/provision.ps1
Since we've ported osquery to Windows, a large portion of our third party libraries have been pre-built and hosted externally for the sake of moving fast. I've begun building out a large amount of our auto-build system that will hopefully function in a Homebrew-esk manner, and this diff tests out some of this functionality. Before our boost libraries took quite a bit of time to install:
```
C:\Users\Nicholas\projects\repos\osquery [boost-source-built +0 ~1 -0 !]> .\tools\provision.ps1 -verbose
[+] Provisioning a Win64 build environment for osquery
=> Verifying script is running with Admin privileges
[+] Success!
...
[*] PSScriptAnalyzer already installed.
=> Retrieving third-party dependencies
=> Determining whether boost-msvc14 is already installed...
=> Did not find. Installing …
```
> Bumping boost to source built libs

- Vagrantfile
Add Ubuntu 16.10, FreeBSD 11, and ArchLinux vagrant targets.
> vagrant: Add Ubuntu16.04, FreeBSD 11, Arch Linux

- osquery/distributed/distributed.cpp
- tools/tests/test_http_server.py
Adding the ability to gate queries using discovery queries in ad hoc scheduling. This should not affect any system that relies on the format of distributed queries as they are now. The discovery query is achieved by adding an extra sub-dictionary to queries containing a map of names to discovery queries.
```json
EXAMPLE_DISTRIBUTED_DISCOVERY = {
"queries": {
"windows_info": "select * from system_info",
"darwin_chrome_ex": "select users.username, ce.* from users join chrome_extensions ce using (uid)",
},
"discovery": {
"windows_info": "select * from os_version where platform='windows'",
"darwin_chrome_ex": "select * from os_version where platform='darwin'"
}
}
```
This test block for distributed queries will return system_info only on Windows systems and chrome extensions only on OS X …
> Adding discovery query support to distributed queries

- include/osquery/events.h
- include/osquery/registry.h
- osquery/config/config.cpp
- osquery/config/parsers/events.cpp
- osquery/core/watcher.cpp
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/events/tests/events_tests.cpp
- osquery/main/tests.cpp
- osquery/registry/registry.cpp
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/sql.cpp
- osquery/tables/events/linux/syslog_events.cpp
- osquery/tests/test_util.cpp
- specs/linux/syslog_events.table
- tools/codegen/gentable.py
This commit aims to improve events in two ways:
- The events will inspect the schedule and inform each subscriber of the intervals and count.
- The tests for publishers and subscribers should be enhanced to follow the expected register and deregister expectations.
The assertion we make is that no subscriber should expire events before each query that uses the subscriber has a chance to run on the related events. This is achieved by enforcing a minimum expiration as the maximum interval * 3 to handle splay and a minor stretch in time as it applies to the counter and the time needed to run a complete schedule.
> events: Inspect schedule and improve tests

- docs/wiki/deployment/configuration.md
- osquery/config/packs.cpp
This expands `platform = ubuntu || centos` to apply to all Linux hosts, similarly to `platform = linux` in pack and query configuration.
> packs: Run centos and ubuntu platforms on all Linux

- include/osquery/events.h
- osquery/database/database.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/database/tests/plugin_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/events/tests/events_tests.cpp
- osquery/events/windows/windows_event_log.cpp
- osquery/events/windows/windows_event_log.h
- osquery/tables/CMakeLists.txt
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/darwin/process_file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/events/yara_events.cpp
This builds on the foundation from #3087.
With this we improve events in several ways:
- All queries that use a subscriber must execute once before events can be expired.
- Expiration happens on the index-level (`% 60`).
- Several bug fixes to RocksDB's `deleteRange` abstraction (newly introduced).
- Several performance improvements to expiration and event index recording.
> events: Execute schedule before expiring

- osquery/tables/system/tests/system_tables_tests.cpp
- osquery/tables/system/windows/users.cpp
This changes the functionality of the users virtual table to query the system registry for Roaming Profiles specifically, as opposed to the WMI database.
> [Fix #3079] Change users table to query from registry instead of WMI

- osquery/filesystem/filesystem.cpp
- osquery/tables/system/hash.cpp
Closes #3080
This adds a WARNING for all files that were not read due to file size limits (a configuration option). It also removes the CommonCrypto usage on OS X, all platforms are using OpenSSL.
> hash: Only return hashes for files hashed

- osquery/core/posix/process.cpp
- osquery/core/windows/process.cpp
At the expense of two `execle` calls, remove the need for extensions to implement `noverbose`.
> extensions: No not use noverbose in autoloading

- CMake/Packages.cmake
- tools/deployment/make_linux_package.sh
The previous `deb` and `rpm` packages included a `u16` for Ubuntu 16.04, and `el7` for Enterprise Linux (CentOS) 7-- but these packages can be installed to tons of flavors, so we should move the name to `linux`. If there's a Linux OS that uses either package manager, and the OS was constructed after 2011, targeting general purpose use, we should support it.
This also produces a `.tar.gz` with the install layout from `/` for OSes that do not use `dpkg` or `rpm`.
> packages: Use 'linux' for OS version and build .tar.gz

- osquery/extensions/extensions.cpp
This allows the `osqueryi` shell to pick a "random" socket path if the configured path cannot be removed. This may occur if another user chooses the same path and improperly stops the shell. Consider:
```
touch ~/.osquery/shell.em
chmod 000 ~/.osquery/shell.em
```
Currently this will prevent all `osqueryi` shells from starting their extension managers. The desired behavior is to select a new socket (append a short to the end of the path).
Daemons will fail if the path cannot be used.
> extensions: shell: Check for socket path ownership

- osquery/database/database.cpp
The `VLOG(1)` within `osquery::resetDatabase` is currently not protected under the `LoggerForwardingDisabler` scope. With `--verbose` flags, the `VLOG(1)` logging attempt will eventually hit `osquery::setDatabaseValue` with a `kDatabaseReset` lock already taken.
> Locking issue with osquery::resetDatabase

- docs/wiki/deployment/configuration.md
- osquery/tables/applications/posix/prometheus_metrics.cpp
- osquery/tables/applications/posix/prometheus_metrics.h
The prometheus_targets configuration now exposes a request timeout field (in seconds).  If there is no timeout explicitly set, then a default value of 1 second will be used.
> prometheus_metrics: exposed request timeout configuration

- osquery/events/linux/audit.cpp
- osquery/events/linux/audit.h
- osquery/events/linux/benchmarks/audit_benchmarks.cpp
- osquery/events/linux/tests/audit_tests.cpp
- osquery/tables/events/linux/process_events.cpp
- osquery/tables/events/linux/socket_events.cpp
- osquery/tables/events/linux/user_events.cpp
- specs/linux/socket_events.table
- specs/linux/user_events.table
- specs/posix/process_events.table
This fixes an oversight with the `user_events` table. The audit events are replayed about 5x and an event is recorded in the table for each. We add a small 10-sized audit ID cache to stem the number of events. From observation this dedups all user events.
We also add `auid` to `process_events`, `socket_events`, and `user_events`.
> audit: Optimize user_events and add auid

- osquery/dispatcher/scheduler.cpp
The `enable_monitor` flag has become integral to many parts of osquery. We need to remove the flag's capabilities.
> Remove enable_monitor functions

- tools/provision/formula/pcre.rb
The `pcre` package on Linux and Darwin is out of date, packages for 8.38 may not be available (from 2015).
> deps: Update pcre to 8.40

- include/osquery/tables.h
- osquery/tables/CMakeLists.txt
- tools/provision/freebsd.sh
- tools/provision/lib.sh
This is meant to improve the CI for FreeBSD11. The `lldpd` package is needed for linking the `lldp` table. `cpp-netlib` > 0.11 is needed for the TLS SNI functions.
> freebsd: Add lldpd to dependencies

- tools/provision/formula/augeas.rb
There are some performance improvements in Augeas we should pull in. This changes the build for `augeas` slightly in that we take the project-provided tarball instead of building from a Github checkout.
> deps: Update augeas to 1.8.0

- osquery/extensions/CMakeLists.txt
- tools/provision/formula/thrift.rb
Thrift 0.10.0 includes a fix for a memory leak in `gethostbyaddr`.
> deps: Update thrift to 0.10.0

- docs/wiki/installation/cli-flags.md
- osquery/logger/logger.cpp
- osquery/logger/plugins/stdout.cpp
- osquery/logger/tests/logger_tests.cpp
This closes #3041 by introducing a `--logger_min_status` that can be set to `=3` to disable status messages.
This also addresses a UX issue with `--logger_plugin=stdout` where the messages we also reported to stderr.
> logger: Add logger_min_status and disable stderr with stdout

- osquery/events/windows/windows_event_log.cpp
Add a check for the success of a malloc before continuing to parse the Windows Event Log in the case that the initial call to EvtRender returned with ERROR_INSUFFICIENT_BUFFER. 
nullptr can be provided to EvtRender to determine the needed buffer size, however there is no need to call this function if the malloc failed, and we also now have a safety issue with the code since we are assuming the malloc succeeded.
This fixes #3129.
> [Fix #3129] Check malloc result for WEL XML buffer before calling EvtRender

- osquery/tables/system/windows/tests/registry_tests.cpp
- specs/windows/registry.table
The way we were computing the registry table prevented an OR clause from working on the key column. 
This fixes it by forcing SQLite to not optimize away the OR clause.
```
osquery> select * from registry where key = 'HKEY_LOCAL_MACHINE\SAM' or key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Control Panel';
+----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+---------------------+--------+------+------------+
| key                                                                        | path
| name                | type   | data | mtime      |
+----------------------------------------------------------------------------+----------------------------- …
```
> [Fix #3135] Allowing OR clause in Windows Registry Table

- tools/provision.ps1
This commit will install aws-sdk-cpp libraries (core, kinesis, firehose, and sts) for windows on provisioning. Note that this does not bring full support to windows, it's simply making the port possible.  More PRs will follow with changes to our CMake logic to try and get aws functionality on Windows.
> Adding aws-sdk-cpp libraries to provisioning script

- osquery/remote/remote.cpp
Previously the output byte size was set to something of a no-op, the `sizeof` a `std::string` container.
> remote: Fix output size for TLS compression

- osquery/tables/system/windows/tests/registry_tests.cpp
- specs/windows/registry.table
The missing 'index' flag resulted in incomplete results from an OR operation on the windows registry key, adding it allows complete results to be returned.
```
osquery> select key from registry where  key like "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\%%" or key like "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\%%";
W0405 10:38:26.914213  5184 registry.cpp:424] CURRENT_USER hives are not queryable by osqueryd; query HKEY_USERS with the desired users SID instead
+-----------------------------------------------------------------------------------------------------+
| key                                                                                                 | …
```
> [Fix #3138] Adding index on 'key' column of Windows Registry table

- osquery/CMakeLists.txt
- osquery/database/database.cpp
- tools/provision/freebsd.sh
With: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=181519&action=diff we should use the `rocksdb-lite` port.
Closes #3111.
> freebsd: Link rocksdb-lite

- osquery/tables/system/windows/startup_items.cpp
Startup items can live in the WOW6432Node keys as well for 32-bit compatibility.
Note I had to change the SQL from 'OR' to 'UNION' to workaround a bug with how the 'OR' is being rendered.
> Adding 32-bit Items to Windows startup_info table

- include/osquery/logger.h
- include/osquery/system.h
- osquery/core/posix/utils.cpp
- osquery/core/system.cpp
- osquery/core/tests/time_tests.cpp
- osquery/core/utils.h
- osquery/core/windows/utils.cpp
- osquery/logger/logger.cpp
- osquery/logger/plugins/buffered.cpp
- osquery/logger/tests/logger_tests.cpp
Currently, logger plugins that use `BufferedLogForwarder` for status logging do not receive information about the `hostIdentifier`, `calendarTime`, and `unixTime`. This adds the following fields to a status log entry: `hostIdentifier`, `calendarTime`, and `unixTime`.
> Adding hostIdentifier, calendarTime, unixTime to status logging

- include/osquery/filesystem.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
This attempts to remove the PRE-PROCESSOR  based control flow for filesystem tests. It also adds `readFile` and `writeTextFile` basic tests. More are needed for directory/link-type checking.
> tests: Rewrite and add filesystem tests

- osquery/extensions/interface.h
The `TSocket` may throw in rare occasions (e.g., https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/transport/TSocket.cpp#L832) we should not allow this exception to escape the destructor. This bug will be seen in C++ extensions in rare situations after the core osquery process is stoped.
> extensions: Catch Thrift transport close exception

- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
This fixes a large issue with the use of `::select`, it does not expect a FD > 1024 and thus corrupts the stack when a target FD is passed to the `FD_` macros.
It also attempts to improve performance with the `inotify` publisher but move stack-local scratch buffers to an instance-life-long buffer. The chosen configuration had been allocing 2.7k bytes for every 400ms.
> inotify: Use poll over select in inotify publisher

- include/osquery/events.h
- include/osquery/tables.h
- osquery/events/benchmarks/events_benchmarks.cpp
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/tests/test_util.cpp
- osquery/tests/test_util.h
- tools/codegen/gentable.py
- tools/codegen/templates/default.cpp.in
After several days of tests with occasional runs of:
```
./tools/analysis/system_stress.py -n 10 -i lo0
```
This shows about a 20M RSS decrease (60M peak compared to a new 41M peak). With this implementation only 1 copy of the event set is in memory at any given moment, previously there were 2.
> events: Use generator-tables for event subscribers

- osquery/core/tables.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- specs/chrome_extensions.table
- specs/darwin/browser_plugins.table
- specs/darwin/crashes.table
- specs/darwin/keychain_items.table
- specs/darwin/package_receipts.table
- specs/darwin/safari_extensions.table
- specs/posix/augeas.table
- specs/posix/authorized_keys.table
- specs/posix/device_file.table
- specs/posix/firefox_addons.table
- specs/posix/known_hosts.table
- specs/posix/opera_extensions.table
- specs/posix/shell_history.table
- specs/posix/ssh_keys.table
- specs/posix/system_controls.table
- specs/posix/user_groups.table
- specs/posix/yara.table
- specs/users.table
- tools/codegen/gentable.py
Upon inspecting the virtual table implementations, several use `context.constraints` but do not indicate in the document + table `create` schema. This may lead to incorrect `rowid`s assigned to results in `OR` clauses.
> tables: Fix table metadata when constraints are used

- docs/wiki/deployment/debugging.md
- docs/wiki/deployment/file-integrity-monitoring.md
- osquery/events/events.cpp
- specs/darwin/disk_events.table
- specs/darwin/process_file_events.table
- specs/linux/socket_events.table
- specs/linux/syslog_events.table
- specs/linux/user_events.table
- specs/posix/file_events.table
- specs/posix/hardware_events.table
- specs/posix/process_events.table
- specs/posix/yara_events.table
- specs/windows/windows_events.table
- tools/codegen/gentable.py
This adds an `eid` column to all events tables. The column is marked `HIDDEN`, so it does not show up in results or with a `SELECT *`, this can be used to make sure all events are recorded, there should never be duplicates or skipped IDs when inspecting the entire table.
> events: Add hidden EID to all events tables

- docs/wiki/installation/cli-flags.md
The documentation for using the `windows_event_channels` contains quotes, however this wont work as the quotes are included in the channel name at subscription time.
> Updating windows_event_channels usage doc

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
We install a default service with chocolatey and point it at a flagsfile, however if the flagsfile doesn't exist the service start will fail. This touches a blank `osquery.flags` file if one doesn't already exist.
> Touching a blank osquery.flags file for win service

- osquery/core/windows/process_ops.cpp
- osquery/core/windows/wmi.cpp
If a `std::wstring` is passed to `stringToWstring` we are throwing a range exception. This wraps the converter call in a `try` clause, and returns an empty string on fail with a `WARNING` log line. I've also updated our helper functions which were causing this issue to use the wide string versions of the Windows API calls, as we're not making use of the user/group names in the helper functions.
> [Fix #3039] Fixing stringToWstring crashes with wide character strings

- osquery/core/system.cpp
Adds a new option for host identifier, which is to specify the value via the CLI. Also adds assigning the result status from each UUID generation function inside getHostIdentifier() so we can log any non-ok results. 
Built everything on windows via `.\tools\make-win64-binaries.bat`. This includes tests, which all passed. I tried running the osqueryi.exe shell with `--host_identifier specified --specified_identifier` and got an error from GFlags that I needed to set a value for `specified_identifier`. I also tried running the shell with both values set, and osqueryi ran fine (but wasn't sure how to select the host identifier).
I also ported this over to a local project where I'm including osquery as a library. Specifying host_identifier via `osquery::FLAGS_host_identifier = "specified";` …
> Add specified identifier via GFlags

- osquery/tables/events/windows/windows_events.cpp
This checks for, and removes, quotes wrapping the Windows event log channel subscriptions. Now one can pass a coma delimited list, where channel names contain spaces, and they'll correctly be subscribed to.  Example output follows:
```
C:\Users\thor\work\repos\osquery [win-events-channel-quotes]> .\build\windows10\osquery\Release\osqueryi.exe --disable_events=false --windows_event_channels="System,Security,Windows PowerShell" --verbose
I0418 15:10:02.155122  7256 process_ops.cpp:162] Unable to find environment variable (0): OSQUERY_WORKER
I0418 15:10:02.161072  7256 init.cpp:380] osquery initialized [version=2.4.0-15-gef1f3975]
I0418 15:10:02.161072  7256 process_ops.cpp:162] Unable to find environment variable (203): OSQUERY_WORKER
I0418 15:10:02.161072  7256 extensions.cpp:295] Could …
```
> Adding support for quote wrapped windows event channels

- osquery/tables/events/windows/windows_events.cpp
The Windows Event Log publisher was over-writing the EventData nodes with each iteration. This appends the additional data using a carriage-return+newline a la windows.
> [Fix #3180] Grabbing additional data fields for windows event logs

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
When doing an install with /InstallService using choco, let's start the service as well. IMO this is more intuitive behavior, and also ensures we restart the service after e.g an upgrade.
Note that on a fresh install, this doesn't make a ton of sense because there will be no osquery.flags file, however we decided this was worth it to prevent the unintuitive 'shutdown service after upgrade' behaviour.
> Start osqueryd on install with chocolatey

- docs/wiki/installation/cli-flags.md
- osquery/tables/events/linux/hardware_events.cpp
This is a small optimization for `hardware_events` on Linux. It allows hosts to be configured to skip reporting some types of UDEV events. This is helpful for flash-backed machines that experience lots of `disk` and `partition` events.
> Add hardware_disabled_types flag to control hardware_events

- osquery/tables/CMakeLists.txt
- osquery/tables/system/darwin/event_taps.mm
- specs/darwin/event_taps.table
Commit adds the event_taps table to Darwin. This will enumerate a list of processes that have a registered event tap. Useful in detecting userland keyloggers.
@evenfowler
> Fix #2838: Adds the event_taps table to Darwin

- tools/provision/formula/libarchive.rb
Add the bottle hashes for cached/binary versions of `libarchive`.
> deps: Add libarchive 3.2.2 bottles

- tools/provision/formula/libarchive.rb
An oversight in the `bottle` stanza for `libarchive` leads to a cache miss for binary packages and instead installs from source.
> deps: Fix libarchive bottle root URL

- include/osquery/core.h
- include/osquery/logger.h
- include/osquery/tables.h
- osquery/core/system.cpp
- osquery/logger/logger.cpp
- osquery/logger/plugins/filesystem.cpp
- osquery/logger/plugins/tests/buffered_tests.cpp
- osquery/logger/tests/logger_tests.cpp
This addresses: #3195 but other improvements to DB access could be implemented too.
This prevents the early-logging from generating host identifiers within the Glog callbacks.
> logger: Fixes to allow plugins access to hostIDs

- tools/provision/formula/boost.rb
Update the statically-build `boost` to version `1.64`.
> deps: Update boost to version 1.64

- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/formula/cpp-netlib.rb
- tools/provision/formula/openssl.rb
Update `openssl` and the cURL-provided certificate store.
> deps: Update openssl to version 1.0.2k

- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/formula/cpp-netlib.rb
1. Update `aws-ask-cpp` to version 1.0.107
2. Rebuild the bottles for `cpp-netlib` as this was also needed after rebuilding OpenSSL.
> deps: Update aws-sdk-cpp to version 1.0.107

- osquery/tables/system/linux/rpm_packages.cpp
- tools/provision/formula/librpm.rb
This attempts to improve `librpm` safety.
1. Upgrade to version `4.13.0`.
2. Add `isUserAdmin` checks to the privilege dropper check (do not allow `root` to query if privileges are not dropped).
3. Collect the `librpm` errors and send them to `VLOG(1)`.
> rpm: Improve librpm safety

- include/osquery/database.h
- osquery/database/database.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/sqlite.cpp
- osquery/logger/logger.cpp
- tools/tests/test_osqueryd.py
The `relayStatusLogs` function will access the DB for certain options of `--host_identifier`. This method may be called (thus requiring DB access), before the DB is initialized. The method is called periodically during the daemon's life, returning before the DB is initialized will only delay forwarding status logs to the logger plugin.
> logger: Require an open DB for status logs

- tools/provision/formula/boost.rb
Boost 1.64's coroutine2 project includes thread local storage. We're unsure if this will implicitly deprecate macOS 10.10 so to be safe, we'll stay at 1.63.
> revert: deps: Update boost to version 1.64

- tools/provision.ps1
This library package is still experimental, and this diff simply brings the libraries along with the development kit. The actual logic is still gated by CMake, and future diffs will work to ungate the logic.
> deps: Bumping windows aws-cpp-sdk to 1.0.107

- osquery/tables/system/windows/services.cpp
- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
I'm sick of Windows and it's raw pointers and C-style arrays. I also just read a book about c++11 and 14 at the recommendation of @poppyseedplehzr . So instead of simply adding some nullptr checks to the mallocs in this table I decided to un-C the code to satisfy my need to feel like a modern C++ programmer.
If the team is cool with this direction I'll continue to refactor other Windows tables in a similar manner.
> Refactor Windows Service Table to use std::unique_ptr

- tools/provision.ps1
This bundles the debug libs for aws-sdk-cpp, as well as the core lib which was left out of the previous version.
> deps: bumping aws-sdk-cpp to 1.0.17-r1

- osquery/tables/system/windows/startup_items.cpp
- specs/startup_items.table
One current issue with startup_items is that it contains both the path to the executable and also the args in one string, this makes it a pain to parse out the executable for e.g. hash analysis.
Right now this only will have results for windows. darwin will report empty columns.
```
osquery> select * from startup_items;                                                                                                                                                                                                                                                  
name = Dropbox                                                                   
path = C:\Program Files (x86)\Dropbox\Client\Dropbox.exe                         
args = /systemstartup …
```
> Split Startup items 'path' column into 'path' and 'args'

- tools/deployment/make_windows_package.ps1
With the updates to the osquery build system scripts for windows, I introduced a regression with how our deployment script builds our chocolatey package. This fixes that, as well as cleans up the script just a touch.
> deploy: fixing the windows osquery chocolatey packaging script

- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/database/database.cpp
- osquery/tables/CMakeLists.txt
Remove the ability to set `SKIP_ROCKSDB` in build.
> database: Remove SKIP_ROCKSDB build option

- tools/provision/freebsd.sh
For the FreeBSD CI/CB we need all features enabled (AWS, YARA, SleuthKit are optional in the port).
> freebsd: Add asio and aws-sdk-cpp dependencies

- CMakeLists.txt
On macOS there are several warnings with `gtest`. This updates `gmock` and `gtest` within the `third-party` submodule to version 1.8.0.
> test: Update gmock and gtest to 1.8.0

- CMakeLists.txt
Skip detecting and potentially using the C++ `std::tr1` and instead always use `gtest`'s.
> test: Always use gtest TR1 on FreeBSD

- osquery/config/parsers/tests/file_paths_tests.cpp
- osquery/core/posix/process.cpp
- osquery/core/tests/process_tests.cpp
- osquery/tables/system/freebsd/os_version.cpp
- tools/tests/test_parse_items.conf
The `osquery_tests` and `osquery_additional_tests` 'almost' run on FreeBSD. This PR adds the last few fixes to the tests themselves.
> freebsd: Fix process_tests and include wait

- packs/osx-attacks.conf
Adding signature, more specifically the LaunchAgent names for new OSX malware, DOK. More information here http://blog.checkpoint.com/2017/04/27/osx-malware-catching-wants-read-https-traffic/
> Adding signature for new OSX malware DOK

- packs/osx-attacks.conf
Adding File Artifact names for an OS X port of the Snake malware, as reported here: https://blog.fox-it.com/2017/05/03/snake-coming-soon-in-mac-os-x-flavour/ -- info taken from the IOCs section.
I didn't feel that the hashes or network indicators would work well in query pack (since we don't know what files the hashes correspond to), though we could do process open sockets to look for the IP. I just don't feel that is likely to have any value.
> Adding Fox-IT IOCs for OSX port of Snake malware

- tools/provision.ps1
This addresses #3248. The dev environment provisioning script was calling `git submodule update --init` in the `third-party` directory, however this needs to be run in the repo root.
> [Fix 3248] git submodule now inits new modules on windows

- tools/provision/chocolatey/osquery_utils.ps1
This ensures that installations on non-English systems with the chocolatey package should correctly set the Deny-Write ACL on the daemon folder. Received a verification that this fix works from @ogoudron that this is working on French systems, will test on a Japanese install and verify it's working there also.
> [Fix #3230] windows deploy: Changing the ACL group from Everyone to the world SID

- include/osquery/config.h
- include/osquery/extensions.h
- include/osquery/registry.h
- include/osquery/tables.h
- osquery/tables/applications/posix/docker.cpp
- specs/posix/docker_container_labels.table
- specs/posix/docker_container_mounts.table
- specs/posix/docker_container_networks.table
- specs/posix/docker_container_ports.table
- specs/posix/docker_container_processes.table
- specs/posix/docker_container_stats.table
- specs/posix/docker_containers.table
- specs/posix/docker_image_labels.table
- specs/posix/docker_images.table
- specs/posix/docker_info.table
- specs/posix/docker_network_labels.table
- specs/posix/docker_networks.table
- specs/posix/docker_version.table
- specs/posix/docker_volume_labels.table
- specs/posix/docker_volumes.table
UNIX domain socket provided by docker daemon is used to make API calls.
Docker Engine API (v1.27) is used as reference. No support is added for
docker swarm related APIs. This should work on all platforms where
docker UNIX domain socket is exposed.
Supports following top level tables:
- docker_containers
- docker_networks
- docker_volumes
- docker_images
- docker_info
- docker_version
[Examples](https://github.com/facebook/osquery/files/971156/examples.txt)
> Docker support in OSQuery.

- include/osquery/database.h
- include/osquery/distributed.h
- osquery/carver/carver.cpp
- osquery/carver/carver.h
- osquery/carver/tests/carver_tests.cpp
- osquery/database/database.cpp
- osquery/distributed/distributed.cpp
- osquery/tables/forensic/carves.cpp
This adds the distributed request ID to the file carver so requests made by a distributed TLS endpoint can be connected on the endpoints.
> carving: Adding distributed request_id to carver

- osquery/tables/system/windows/registry.cpp
- osquery/tables/system/windows/registry.h
- osquery/tables/system/windows/tests/registry_tests.cpp
All of those mallocs and delete[]s freak me out. Let's c++14ify them.
Also changing the registry function to return a status, so we can accurately know when a reg query failed vs. silently returning incomplete results.
> Refactor Windows Registry Code to use std::unique_ptr and Fail on Error

- packs/osx-attacks.conf
Adds detection for the malware that came packaged with the tampered version of Handbrake: https://objective-see.com/blog/blog_0x1D.html
• Check for file presence of the binary, plist
• Check for presence of running process named "activity_agent"
> Adding OSX/Proton to osx-attacks.conf

- Vagrantfile
- tools/provision/ubuntu.sh
* Ensures `git` is installed in the `ubuntu14` box before running `make sysprep; make deps`
* Installs additional necessary dependencies to run through [all build steps ](https://osquery.readthedocs.io/en/stable/development/building/#building-on-linux) including packaging
> deps: additional packages for building osquery on the ubuntu vagrant box

- docs/wiki/introduction/sql.md
- osquery/sql/CMakeLists.txt
- osquery/sql/sqlite_hashing.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
```
~/local/osquery(branch:master)  » ./build/linux/osquery/osqueryi "select sha1('');"
+------------------------------------------+
| sha1('')                                 |
+------------------------------------------+
| da39a3ee5e6b4b0d3255bfef95601890afd80709 |
+------------------------------------------+
------------------------------------------------------------
~/local/osquery(branch:master)  » echo -n '' | shasum
da39a3ee5e6b4b0d3255bfef95601890afd80709  -
```
> hashing: Add sha1, sha256, md5 functions

- osquery/tables/system/windows/registry.cpp
- osquery/tables/system/windows/tests/registry_tests.cpp
- specs/windows/registry.table
'path' is a standard column we use around the codebase, and up until now we could not query the registry using it. This adds support to query a registry value by a full path, not simply just a key. 
It does this somewhat naively, by stripping off the final token of a registry query (in case it's a value and not a subkey), querying the subkey in the registry, then letting SQL do the rest. It's a little inefficient but I couldn't think of a clean way to verify that the path refers to a value vs a subkey without actually querying the registry and checking, which I'm doing in this case anyway.
I've also made path the new primary key for the registry table, since it is actually a unique identifier for each result, and will fix some weirdness we were seeing with OR clauses on the table.
Fixes …
> Allow querying Windows Registry by 'path' column

- include/osquery/system.h
- osquery/core/watcher.cpp
- osquery/core/windows/process.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- osquery/filesystem/filesystem.cpp
- osquery/tables/system/windows/processes.cpp
This addresses #3268 by ensuring that the initial checks of `isChildSane` for launching extensions _fails_, which ensures that the extension processes are launched on the first iteration through our `WatcherRunner::start` loop.
> [Fix #3268] extensions autoload now correctly spawns extension processes

- osquery/tables/system/freebsd/os_version.cpp
- osquery/tables/system/freebsd/pkg_packages.cpp
- specs/freebsd/pkg_packages.table
* Basic os_version functionality using results read from system_controls.
* Table for installed pkgng packages, read from the SQLite database because libpkg isn't guaranteed to be available.
> FreeBSD: Fix os_version, add pkgng package table

- osquery/core/watcher.cpp
- osquery/tables/system/darwin/asl.cpp
- osquery/tables/system/darwin/asl_utils.cpp
- osquery/tables/system/darwin/tests/asl_tests.cpp
- tools/codegen/genapi.py
There are three things fixed here:
- There's a warning on Linux/Darwin about comparing signed/unsigned in `WatcherRunner::getProcessRow`.
- All of the macOS ASL APIs are deprecated.
- `freebsd` is not in the `genapi.py` list of platforms.
> darwin: Fix FreeBSD genapi, ASL warnings

- CMake/CMakeLibs.cmake
- Makefile
There was a bit of disorganization about providing linking arguments for shared objects. It looks odd by the safest way to assure the correct ABI linking with the embedded build is by providing the link search paths as compiler flags. This should only effect the output shared modules, which are tested with `./tools/tests/test_modules.py`.
> build: Improve SO linking on Linux

- osquery/database/database.cpp
Fixes #3294.
This attempts to solve a potential race-to-`std::runtime_error` within DB reset. The DB can be reset using a local method `resetDatabase`, but can also be reset using the generic `Registry` thrift-call APIs. Each contained a logical critical section and the method API would trampoline into the registry if the plugin was available locally.
> database: Simplify database reset logic and locking

- specs/darwin/temperature_sensors.table
Celcius and fahrenheit were TEXT types causing max to behave incorrectly. This changes the types to double so functions work right.
Fixes Issue #3292
> Fix temperature sorting

- osquery/filesystem/tests/fileops_tests.cpp
ASAN caught in a test we were reading past the end of buffer. Add the size to fix and make the tests happy when running through ASAN.
> Fix an reading past the end of buffer

- osquery/filesystem/filesystem.cpp
zwass caught that boost has a bug where it throws an exception when we aren't expecting it to. This catches that error and prevent osquery from crashing. It does not address what might be a logic bug in osquery dropping privileges before trying to read the plist. @theopolis can you weigh in on this?
Fix #3279
> Fix crash caused by boost's unhandled exception

- docs/wiki/deployment/debugging.md
- docs/wiki/deployment/extensions.md
- docs/wiki/development/osquery-sdk.md
- docs/wiki/installation/cli-flags.md
The 'modules' feature has been removed with LLVM 4.0, remove the documentation references.
> docs: Remove 'modules' from documentation

- osquery/tables/events/windows/windows_events.cpp
Windows event log data doesn't need to be 'pretty' formatted for results logging, and is causing a large amount of wasted data for tabs and carriage return+newline spacings.
> windows: Removing pretty printing from windows event log data

- docs/wiki/deployment/configuration.md
- include/osquery/config.h
- osquery/config/parsers/tests/views_tests.cpp
- osquery/config/parsers/views.cpp
- osquery/tests/test_util.cpp
- osquery/tests/test_util.h
- tools/tests/test_parse_items.conf
- tools/tests/view_test.conf
- tools/tests/view_test2.conf
Sometimes views can be useful to simplify queries that you use a lot. This lets you define views in the config file to be available for queries later.
> Adding a config block to create views

- osquery/tables/system/cpuid.cpp
- osquery/tables/system/uptime.cpp
- osquery/tables/system/windows/drivers.cpp
- osquery/tables/system/windows/kernel_info.cpp
- osquery/tables/system/windows/patches.cpp
- osquery/tables/system/windows/processes.cpp
- osquery/tables/system/windows/programs.cpp
- osquery/tables/system/windows/registry.cpp
- osquery/tables/system/windows/smbios_tables.cpp
- osquery/tables/system/windows/wmi_cli_event_consumers.cpp
- osquery/tables/system/windows/wmi_event_filters.cpp
- osquery/tables/system/windows/wmi_filter_consumer_binding.cpp
- osquery/tables/system/windows/wmi_script_event_consumers.cpp
This fixes numerous resharper lint issues, but most importantly the `drivers` table was spewing the following message on query due to an incorrect return value check:
```
...
I0524 21:48:42.050192  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.054209  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.058182  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.062187  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.066190  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.072209  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.079238  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 21:48:42.087190  4468 drivers.cpp:60] QueryServiceConfig failed (122)
I0524 …
```
> windows: Fixing INFO verbosity in drivers table and various resharper lints

- docs/wiki/deployment/configuration.md
- docs/wiki/installation/cli-flags.md
- include/osquery/config.h
- include/osquery/flags.h
- osquery/config/parsers/options.cpp
- osquery/config/parsers/tests/options_tests.cpp
- osquery/core/flags.cpp
This allows a configuration to set "custom" flags.
The `options` top-level JSON key sets a dictionary of key-value flags for osquery. If these contain `custom_` as the absolute prefix, they are stored as a flag accessible via `Flag::getValue("custom_NAME");` (see included unit tests). Unlike normal flags, they do not have to be created at compile time.
> flags: Allow custom flags in configuration

- osquery/sql/sqlite_encoding.cpp
- osquery/sql/tests/sql_tests.cpp
It would be good if the base64 functions in osquery had the same names as MySQL before they become widely adopted.
> Rename new base64 functions to be like MySQL

- docs/wiki/deployment/file-integrity-monitoring.md
The docs need to be updated to make it clear you cannot recursively wildcard in the middle of a string.
> Update docs about recursive wildcards in strings

- osquery/tables/yara/yara.cpp
- osquery/tables/yara/yara_utils.cpp
- osquery/tables/yara/yara_utils.h
YARA had it's osquery folder hardcoded, this makes it consistent with osquery home.
Fix #3229
> Address YARA hardcoded home folder issue

- osquery/config/config.cpp
If you try to load a pack that doesn't exist, osqueryctl (and config.cpp in general) throws a JSON error because parsing an empty string fails. This adds an extra check for that and throws a more verbose error letting them know that there was a problem getting file contents. Also make the JSON parsing error more verbose so if there is a parsing error they know where to look.
> Fix #3220 Error loading packs not verbose enough

- tools/provision.ps1
Bison installed via chocolatey on windows relies on a folder called `data` residing in the same path as the binary. This brings said path into the same location where we drop bison for usage.
> Adding bison data folder to system chocolatey path

- osquery/core/posix/process.cpp
Extensions may want to start and monitor subprocesses and their signals. If they do not define signal handlers we do not want the `SIGCHLD` notifications to be handled or ignored by osquery.
> extensions: Clear signals in autoload threads

- CMakeLists.txt
- osquery/tables/system/darwin/smbios_tables.cpp
- osquery/tables/system/darwin/smc_keys.cpp
I'd also like to add this as an error so that you cannot build when shadowing a local variable.
> Disallow the shadowing of local variables and fix existing shadows

- osquery/tables/networking/darwin/wifi.mm
osquery's build (especially tidy) was complainging the dynamically sized stack arrays are a C99 feature. This diff makes the compiler happy by moving them to heap with a malloc.
After they are used, the memory is freed. No exceptions should be raised or caught, and there are no other code paths so this memory should always be freed here. Also tested with ASAN and there were no memory errors announced.
> Fix C99 array errors by moving array to the heap

- docs/wiki/installation/cli-flags.md
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
The `--read_user_max` is confusing, let's remove it and only use the `--read_max` which is set to 50M by default.
> filesystem: Remove read_user_max flag

- docs/wiki/installation/cli-flags.md
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/virtual_table.cpp
This adds an optional flag `--table_delay` that will sleep the process for a number of microseconds between multi-table calls.
With a `1000` microsecond delay:
```
Profiling query: select count(1) from file join hash using(path) where path like '/Users/reed/Downloads/%'
D:3  C:2  M:0  F:0  U:3  manual (1/1): duration: 4.04213500023 cpu_time: 3.887093824 memory: 7528448 fds: 4 utilization: 85.8 
Profiling query: select count(1) from file join hash using(path) where path like '/Users/reed/Downloads/%'
D:3  C:2  M:0  F:0  U:3  manual (1/1): duration: 4.54719901085 cpu_time: 4.030604288 memory: 7553024 fds: 4 utilization: 80.09 
```
Time increases from `4.05s` to `4.54` and utilization drops `5%`.
> virtual tables: Add optional --table_delay between scans

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/parsers/file_paths.cpp
- osquery/config/parsers/tests/decorators_tests.cpp
- osquery/config/parsers/tests/events_tests.cpp
- osquery/config/parsers/tests/file_paths_tests.cpp
- osquery/config/plugins/tests/tls_config_tests.cpp
- osquery/config/plugins/tls_config.cpp
- osquery/config/tests/config_tests.cpp
- osquery/core/init.cpp
- osquery/devtools/shell.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/tests/scheduler_tests.cpp
- osquery/events/benchmarks/events_benchmarks.cpp
- osquery/events/events.cpp
- osquery/events/tests/events_tests.cpp
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/darwin/process_events.cpp
- osquery/tables/events/darwin/process_file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/events/tests/file_events_tests.cpp
- osquery/tables/utility/osquery.cpp
- osquery/tables/yara/yara_events.cpp
The `Registry` APIs use `get()` for their singleton access. This moves the `Config` singleton to the same name.
> config: Rename getInstance to get for consistency

- osquery/config/config.cpp
- osquery/events/linux/udev.cpp
- osquery/logger/plugins/aws_util.cpp
- osquery/logger/plugins/tests/aws_kinesis_tests.cpp
- osquery/tables/events/tests/file_events_tests.cpp
This attempts to fix TSAN internal errors:
```
FATAL: ThreadSanitizer CHECK failed
```
And new findings from LLVM 4.0 on Linux.
> tsan: Address failures and findings in LLVM 4.0

- osquery/tables/system/darwin/keychain_acl.cpp
Using a four character literal as an int causes clang to issue a warning. This replaces the string literal with a numerical hex representation and a comment noting what it was before.
> [Tidy] Fix four character literal warning

- docs/wiki/installation/cli-flags.md
- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/plugins/tests/tls_config_tests.cpp
- osquery/config/plugins/tls_config.cpp
- osquery/config/plugins/tls_config.h
- osquery/config/tests/config_tests.cpp
There are two config "refresh" concepts in the codebase right now. One only applies to the TLS configuration plugin, the other applies to any plugin; they use (respectively):
* `--config_tls_refresh`
* `--config_refresh`
This PR deprecates the `*_tls_*` flags related to refreshing by assigning them as aliases. It moves the "accelerated" refresh concept used by the TLS plugin to the general concept. It also adds a test for configuration refreshing. This test has not been applied end-to-end to the TLS plugin.
> config: Unify the config refresh logic

- docs/wiki/installation/cli-flags.md
- osquery/events/events.cpp
See https://community.uptycs.com/osquery-fim-reliability/ for more details.
Several folks have suggested that the `events_max` default should be near 50k. The expiration is suggested to be `1` for best performance, yet we set the default to "near 1 day". The safe default was suggested to be an hour.
> events: Sane defaults for expiration and max

- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/extensions/extensions.cpp
- osquery/main/shell.cpp
This is mostly code-cleanup: renaming singleton access method to `get()`. I say *mostly* because it allows us to correctly label member functions with `const` since they are no longer all static.
> watcher: Rename instance to get for consistency

- osquery/logger/logger.cpp
- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/buffered.cpp
- osquery/logger/plugins/tests/tls_logger_tests.cpp
- osquery/logger/plugins/tls_logger.cpp
- osquery/logger/plugins/tls_logger.h
This renames the `BufferedLogSink`'s `instance()` member to `get()` and removes the `static`/free method calling convention such that we can properly call some members `const`.
This applies some C++ modernization and potential performance improvements with moving rvalues (which seems to have been the intention).
> logger: Rename BufferedLogSink instance and other nits

- osquery/core/windows/process.cpp
- osquery/events/events.cpp
- osquery/filesystem/filesystem.cpp
- osquery/remote/enroll/plugins/tls_enroll.cpp
- osquery/remote/utility.h
- osquery/sql/sqlite_string.cpp
- osquery/tables/applications/posix/docker.cpp
- osquery/tables/events/darwin/process_file_events.cpp
- osquery/tables/system/darwin/kernel_info.cpp
- osquery/tables/system/darwin/preferences.cpp
- osquery/tables/system/windows/appcompat_shims.cpp
Use the single-character search overload of `std::string::find` as suggested via modernizers.
> nits: Use char-overload for find

- osquery/config/packs.cpp
- osquery/config/tests/packs_tests.cpp
- packs/it-compliance.conf
- packs/vuln-management.conf
Fixes: #3216
The `posix` query select should be valid. Any specific version of Linux does not make sense so remove them from the included packs.
> packs: Allow posix in pack platform selection

- osquery/tables/networking/darwin/tests/wifi_tests.mm
- osquery/tables/networking/darwin/wifi.mm
- osquery/tables/system/darwin/authorizations.mm
- osquery/tables/system/darwin/keychain_acl.cpp
- osquery/tables/system/darwin/process_open_descriptors.cpp
- osquery/tables/system/darwin/processes.cpp
In an effort to cleanup the osquery code base, warnings are being addressed. This diff fixes all C99 warnings about allocating dynamic arrays on the stack.
> [Tidy] Fix all C99 warnings

- include/osquery/logger.h
- osquery/logger/logger.cpp
- osquery/registry/registry.cpp
This moves several functions (`virtual`, oh-no!) into the `public` accessibility for `LoggerPlugin` allowing the `logString` and `logSnapshotQuery` methods to fast-track into the registry. Here "fast-track" means avoiding the `::call` API and serialization step. This should result in more performance for logger plugins available to the osquery daemon locally as opposed to externally in an extension.
> logger: Allow logString and logSnapshot to fast-track

- packs/osx-attacks.conf
Adds launchd detection for the default plist name. More here: https://github.com/EmpireProject/EmPyre/blob/master/lib/modules/persistence/osx/launchdaemonexecutable.py#L61
> Adding EmPyre agent to osx-attacks

- osquery/core/posix/process_ops.cpp
The syscall to get thread id is deprecated on macOS as of 10.12. This replaces the syscall with a std:: library call. I found this code mod in another project [here](https://github.com/gabime/spdlog/commit/b715378ff55eb40664d215e9264407b0310ec763#diff-075620b19501eee6536187116b2c8ff9R183) and discussion of it [here](https://github.com/gabime/spdlog/issues/74).
> [Tidy] Fix syscall deprecation on macOS

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/tests/config_tests.cpp
See https://community.uptycs.com/osquery-fim-reliability/ for more details on why this is an issue.
Overall it's silly to reconfigure (a somewhat intense process) osquery when the configuration has not changed.
> config: Only reconfigure if content changes

- osquery/remote/enroll/plugins/tls_enroll.cpp
Base10 encodes the integer representation of the platform type bitmask to enrollment requests. This will allow deployments to track what platform (windows/linux/mac os x/etc) each enrolled host is (or at least claims to be).
Tested this against modified and unmodified enrollment server and both worked fine.
> Adds platform to enrollment request

- docs/wiki/deployment/configuration.md
~~Currently the scheduler gets the time once during Initialization, and then executes scheduled queries based off of this initially obtained time. This diff updates that time if it ever happens to drift more than 60 seconds off of the real actual time, and further stores the last time of execution per scheduled query. This behavior should ensure that the sleeping/closing of laptops or system machines doesn't impeded the scheduler from executing queries as close to the time schedule as possible. Below is an example of the new behavior:~~
```
I0522 18:00:45.549796 262725632 scheduler.cpp:74] Executing scheduled query test_query_1: select * from processes;
I0522 18:00:45.549782 262189056 events.cpp:748] Starting event publisher run loop: iokit
I0522 18:00:45.653583 262725632 …
```
> docs: Adding a note regarding osquery scheduler behavior

- osquery/events/linux/audit.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/udev.cpp
The `::poll` calls in Linux event publishers may be interrupted by other threads. One example is when `rpm_packages` causes the process to drop privileges. The `errno` should be inspected in this case and the publisher thread be allowed to continue.
> fim: Allow Linux publishers to be interrupted

- docs/wiki/development/building.md
The developer should first change directory to the osquery project's directory and then run the make command
> Fixed the macOS build steps' order

- tools/provision/formula/libmagic.rb
As reported in https://github.com/facebook/osquery/issues/3373#issuecomment-305894590
the URL for libmagic formula's `file-5.29.tar.gz` is broken (404).
The version could be bumped to 5.31 (the version in the original URL). Instead, this PR changes the URL
to use a different mirror (macports.org instead of fossies.org).
> Change 'libmagic' bottle's URL to a different mirror

- CMake/CMakeLibs.cmake
- CMakeLists.txt
- docs/wiki/installation/cli-flags.md
- osquery/CMakeLists.txt
- osquery/config/config.cpp
- osquery/core/tests/watcher_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
This introduces a new flag `--watchdog_delay` with a safe default of `60s`. It is intended to allow a worker to perform an intense operation, like logging a significant amount of content, before the watchdog attempts a shutdown.
> watcher: Add initial watchdog delay

- osquery/core/watcher.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/extensions/interface.cpp
The `srand` function on Windows does not seed across multiple threads, and thus we make use of the Windows API `rand_s` function which leverages the native Windows OS crypto APIs to generate a cryptographically secure random number. This ensures that multiple extensions spawned have a unique uid value.
Furthermore, upon first launch of extensions an error occurs attempting to cast the Windows `ULONG_MAX` pid value to an integer due to `unsigned long` overflowing an `int` type. While this wasn't preventing extensions from spawning, it was causing errors on first launch. This diff also adds logic to finagle the pid value to a `-1` for "invalid" pids on Windows systems.
Some glorious testing follows:
```
C:\Users\thor\work\repos\osquery [win-extensions-triage-2]
λ …
```
> windows: Multiple extensions now auto-load without error

- osquery/tables/system/posix/load_average.cpp
- specs/posix/load_average.table
Load Averages on POSIX systems using the `getloadavg` function from `stdlib.h`. This PR is not tested on machines other than a mac, but it should work! 😄 
Docs to `getloadavg`
Linux - http://man7.org/linux/man-pages/man3/getloadavg.3.html
FreeBSD - https://www.freebsd.org/cgi/man.cgi?query=getloadavg
Example output:
```
osquery> select * from load_average;
+-----------------+-----------------+------------------+
| load_average_1m | load_average_5m | load_average_15m |
+-----------------+-----------------+------------------+
| 1.901855        | 2.080078        | 2.167480         |
+-----------------+-----------------+------------------+
```
> Load Averages on POSIX systems using getloadavg

- .watchmanconfig
- include/osquery/config.h
- include/osquery/system.h
- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/main/posix/daemon.cpp
- osquery/main/windows/daemon.cpp
- osquery/tables/utility/osquery.cpp
This should fix an error in the watchdog, where an exception is thrown when attempting to use the database. Previously we used the `Config`, and on initialization it constructed a `Schedule`, which attempted to look up the last-failed query from the database.
> watcher: Do not initialize the config in watcher

- osquery/core/init.cpp
Integration tests rely on a specific behavior. The initial verbosity log indicating the config file was unable to be found/read isn't honoring the `verbose` flag on Windows, so we make use of a macro that explicitly checks the `verbose` flag.
> Changing init verbosity to honor verbose flag

- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/sql/CMakeLists.txt
- osquery/sql/sqlite_util.cpp
- osquery/tables/CMakeLists.txt
In certain circumstances, one may wish to completely remove the carver code in it's entirety from the code base. To do so, one can use the `SKIP_CARVER=1` environment variable along with adding the `carves` table to the `specs/blacklist`.
> carver: gating carver code in CMake

- tools/analysis/profile.py
- tools/tests/utils.py
- Bugfix on tables path verification
- Search under <config file path>.d directory if exists in order to parse all sub configuration files
- In pack definition, check if it is an internal one and parse it
> Improve query profiler

- osquery/core/posix/process.cpp
- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
- tools/tests/test_base.py
Issue #3373 exposed a problem where the environment variable `OSQUERY_DEPS`, meant to control where to place osquery's build dependencies, is not always respected.
This makes using a non-default directory for the build dependencies (including a path which doesn't require root/sudo/admin access) unfeasible.
This pull request replaces the hard-coded path `/usr/local/osquery` with an attempt at accessing the `OSQUERY_DEPS` environment variable, defaulting to `/usr/local/osquery`. With these changes, it becomes possible to use `OSQUERY_DEPS` to place build dependencies in a user controlled directory.
The PR includes 6 commits (one per touched file) for easier review.
Note that this PR does not close #3373 completely since it doesn't fix:
1. Python needing to be recompiled when `OSQUERY_DEPS` …
> Replace hardcoded paths throughout code base

- tools/deployment/make_osx_package.sh
We need to customize a little bit the package created by `make_osx_package.sh` to include extra files. With the current structure of the script, it is not possible to inject those files into the package creation steps; the [temporary directory gets deleted](https://github.com/facebook/osquery/blob/e0a24fb0/tools/deployment/make_osx_package.sh#L181-L182) and nothing else can be copied to it before [`pkgbuild` gets called](https://github.com/facebook/osquery/blob/e0a24fb0/tools/deployment/make_osx_package.sh#L239).
This PR adds a mechanism to add extra files and directory to the built package. It does so through the `OSQUERY_PKG_INCLUDE_DIRS` environment variable (bash array). A loop will copy the content of every entries of the variable in `$INSTALL_PREFIX/`, overwriting any collision. So …
> make_osx_package.sh: Add a way to include extra files in the package

- docs/wiki/development/creating-tables.md
- specs/interface_details.table
- tools/codegen/gentable.py
This allows tables to extend their default schema with an `extended_schema`. The goal of the extended schema is to provide platform-specific columns without bloating the default-select case for the other platforms. The column types are still the same on all platforms, but marked `HIDDEN` for those not supported.
> virtual tables: Allow tables to use an 'extended' schema

- osquery/tables/system/darwin/cpu_time.cpp
- specs/posix/cpu_time.table
This PR adds support for the `cpu_time` table. It doesn't have all the information that is obtainable on ubuntu/centos but gets the basic user, idle and system time information that is found in `iostat`. This is done by a call to the `host_processor_info` function.
> cpu_time table on darwin

- Makefile
- osquery/tests/test_util.cpp
- tools/lib.sh
This will be a work-in-progress until it's tested on several platforms.
The goal is to implement #3414 and allow easy building within shared-folders like `vboxsf` and `nfs`.
> build: Major change to building within shared folders

- osquery/tables/utility/file.cpp
- specs/utility/file.table
The `file` table desperately needs a `symlink` field. This is different from the `type` field because you may still want to follow the link and know the type.
> tables: Add symlink column to file table

- osquery/tables/CMakeLists.txt
- osquery/tables/system/freenux/cpu_time.cpp
This introduces a new table category (implementation only for now) called `freenux`, an invented term for the repo meaning tables that build on both FreeBSD and Linux. Because "linbsd" didn't sound very nice.
The first table sharing an implementation is `cpu_time`, which already exists in the `posix` set of specfiles.
> virtual tables: Build Linux cpu_time on FreeBSD

- CMakeLists.txt
- Vagrantfile
- osquery/config/tests/config_tests.cpp
Fixes #3418.
It stinks we didn't catch the `-fvisibility=hidden` effecting FreeBSD earlier. I'm not sure why this causes the remote APIs to hang. FreeBSD is somewhat different that macOS/Linux in that most dependencies are available statically. If dynamic links, `asio`, `cpp-netlib` did not use these compile options, there will be undefined behavior.
> freebsd: Update Vagrantfile, config tests, and remove hidden visibility

- docs/wiki/deployment/extensions.md
Here are the os args my extension is seeing
```
[osquery extension: /usr/local/bin/osquery_extensions/my_config_and_logger.ext --verbose --socket /tmp/extensions.sock --timeout 3 --interval 3]
```
`--verbose` is there if passed to `osqueryd`
> document verbose flag passed to extensions.

- osquery/tables/applications/posix/docker.cpp
On OS X, ps_args are for some reason ignored.
> Check number of columns returned from 'docker top'.

- docs/wiki/installation/cli-flags.md
- docs/wiki/installation/install-linux.md
- docs/wiki/installation/install-osx.md
- osquery/tables/system/posix/augeas.cpp
This provides ability for users to specify their own augeas lenses directory.
On OS X, docker top API is not honoring 'ps_args'. Added check to make results
have correct number of columns.
On Ubuntu 16.04, I am unable to 'make deps' without libyaml. pip install of
requirements.txt is failing to link. Complaining about missing libyaml.
> Custom directory flag for augeas lenses.

- CMakeLists.txt
- tools/make-win64-binaries.bat
Windows by default builds all unit tests. This PR adds a check for the environment variable `SKIP_TESTS` to speed up development builds.
Further, CMake by default adds header include directories without the `SYSTEM` declaration, meaning that during builds the third party header includes will be processed and errors/warnings will be generated on this code. This sets said `SYSTEM` declaration for third party header includes on Windows.
> windows: Adding SKIP_TESTS check for windows

- osquery/core/init.cpp
This addresses the issue in #3445 where the `osqueryi` shell, and daemons using `--disable_watchdog` cannot use RocksDB or log.
> watchdog: Fix disabled database and logging when watchdog is not used

- osquery/tables/system/darwin/tests/asl_tests.cpp
The test only checked for macOS Sierra, make the test now whitelist on all versions post El Capitan.
> Fix test on High Sierra

- osquery/tables/system/windows/ie_extensions.cpp
Adding URL search hooks to the extensions table. Just a simple addition of a new key to query.
```
osquery> select * from ie_extensions;
+------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------+
| name                                           | registry_path
| version         | path                                                         |
+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Adding URL Search hooks to ie_extensions table

- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/ad_config.cpp
- osquery/tables/system/darwin/os_version.cpp
- osquery/tables/system/darwin/packages.cpp
- osquery/tables/system/darwin/preferences.cpp
- specs/darwin/plist.table
- specs/darwin/preferences.table
This separates the overloaded use of the `preferences` table.
`preferences` acts like `defaults` on macOS. It is limited in that it cannot join users or report the system's defaults. In the current form it can also take any `path` input and report the flattened plist items.
This separates the defaults, keeping the functionality in `preferences` from the `plist` (a new table) functions.
> Separate preferences from plist and add user-concept

- osquery/logger/plugins/aws_util.cpp
- tools/provision/formula/aws-sdk-cpp.rb
This restores the helpful error when connecting to AWS, which was removed in: #3343
The fix is upgrading the upstream AWS SDK to 1.1.5: https://github.com/aws/aws-sdk-cpp/releases/tag/1.1.5
Refer to #3437 on how not having this error printed causes issue for debugging.
> aws: Restore exception error printing and upgrade to 1.1.5

- tools/deployment/make_osx_package.sh
- tools/provision.sh
This builds debug versions of osquery (non-stripped) for darwin and installs the executables into `/var/osquery/debug`.
> packages: Build debug pkg and rpm on macOS

- docs/wiki/deployment/anomaly-detection.md
- docs/wiki/deployment/logging.md
- include/osquery/database.h
- osquery/config/config.cpp
- osquery/config/parsers/tests/decorators_tests.cpp
- osquery/database/benchmarks/database_benchmarks.cpp
- osquery/database/database.cpp
- osquery/database/query.cpp
- osquery/database/query.h
- osquery/database/tests/query_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/logger/plugins/tests/filesystem_logger_tests.cpp
- osquery/logger/tests/logger_tests.cpp
- osquery/tests/test_util.cpp
After initially returning all the results of a scheduled query, osquery subsequently returns incremental changes to the original result set on subsequent runs of the scheduled query.
It is useful for a backend to maintain a current full state of a machine based on the initial result set + incremental updates. 
However, because osquery can periodically delete its rocksdb local db (which is used to calculate the incrementals), or, in the face of backup/restores etc. on the host running osquery, the backend and osquery can fall out of sync on the current state.
This PR adds an epoch marker to scheduled queries. The marker provides a mechanism by which osquery and the backend can remain in sync wrt which "epoch" the scheduled query results belong to. If the backend falls out of sync for some …
> Add Epoch marker to scheduled query log results

- include/osquery/core.h
- osquery/core/system.cpp
- tools/deployment/osqueryd.initd
- tools/deployment/osqueryd.service
- tools/deployment/osqueryd.sysconfig
This updates the `--pidfile` location to be `/var/run` (like it should), for Linux and FreeBSD.
It adds logic to the SystemD service unit to "migrate" the pidfile from the old location to the new. This allows a `systemctl status osqueryd` to behave normally if:
- `osqueryd` was started before this commit
- `osqueryd` was started after this commit
...and checked after this commit.
It adds logic to the upstart initscript to report the correct status for `osqueryd` started with init or SystemD:
- `/etc/init.d/osqueryd status`
- `systemctl status osqueryd`
...will both report the correct status for `osqueryd` started with SystemD before and after this commit. `systemctl` will NOT report the correct status for `osqueryd` started with an initscript before or after this commit.
> pidfile: Update pidfile to /var/run on Linux and fbsd

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/plugins/tests/tls_config_tests.cpp
- osquery/config/tests/config_tests.cpp
This contains config testing and compiling improvements. The goal is to make implementation files that include `config.h` compile faster.
> General code cleanup for the config

- packs/incident-response.conf
- packs/osx-attacks.conf
- packs/vuln-management.conf
This updates several packs to use the new `plist` table. The `preferences` had overloaded capability to read a `.plist` but this feature has been removed from that table.
> packs: Update darwin's preferences table to plist

- osquery/tables/system/darwin/ad_config.cpp
Fixes the ad table bare map ats, and changes to plist/preferences tables.
> Fix ad_config table regression from splitting preferences and plist

- osquery/config/config.cpp
- osquery/config/plugins/tests/tls_config_tests.cpp
- osquery/config/tests/config_tests.cpp
If a TLS config check fails the first time, osquery will NOT start the config refresh runner thread. This puts osquery into a stale place.
> Set config refresh to 1 hour and fix retry

- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/core/tests/tables_tests.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- specs/processes.table
- tools/codegen/gentable.py
- tools/codegen/templates/default.cpp.in
This should improve the performance of "stacked" scheduled queries against the `processes` table. This technique (improvement) can be applied to other tables later too.
The caching feature landed a while ago, but was never applied to tables that reacted programmatically to predicate constraints.
> Allow caching for tables with indexes and additionals

- CMakeLists.txt
make format has been using the system installed clang-format, not the one installed by deps.
Adding the binary flag to point to our locally installed clang-format binary.
> Change make format to use dependency binary, not system

- osquery/filesystem/tests/fileops_tests.cpp
Globbing comes in a different order with APFS filesystems actually putting it in the same order as Windows NTFS filesystems. However we maintain two different lists of files in our testing, one for ext/HFS and one for APFS/NTFS. This creates a function which compares two lists of files ignoring their order.
> Ignore ordering in fileops tests

- osquery/events/darwin/fsevents.cpp
- osquery/tables/networking/windows/interfaces.cpp
When testing FIM on APFS I noticed that we aren't capturing mount alerts even though we're capturing unmount. I figure that this was just overlooked (unmount was added in pull request #1197 and it's not mentioned why mount wasn't added) so this just adds it in.
Also fixing a small nit that should've been addressed in a commit yesterday.
> Add mount to fsevents

- tools/deployment/make_windows_package.ps1
The chocolatey package deploy script constructs a chocolatey package for distribution, but doesn't restore the working directory upon completion. This is some-what undesirable from a UX perspective, so we restore the location upon completion.
> windows: Updating chocolatey deployment script to return to working dir

- osquery/core/watcher.cpp
- tools/tests/test_osqueryd.py
Currently if the osquery worker process dies on Windows, the exit code is stashed but the work process is never respawned, thus the watcher hangs indefinitely until the service restarts. This returns the correct code to re-spawn work processes.
> windows: Fixing watcher respawn logic for killed worker processes

- include/osquery/system.h
- osquery/core/system.cpp
- osquery/tables/system/windows/system_info.cpp
The `hostname` column in the `system_info` table is currently only the generic system name. This changes the value to be the FQDN in the event the system is joined to a domain, and the generic hostname otherwise.
> windows: Updating windows system_info to return fqdn for hostname

- tools/tests/test_osqueryd.py
For the integration test checking the existence of our info log, the file may not exist if the system is running sorta slow. This ensures that the info log file exists, before assigning it and checking it's presence.
> tests: Ensuring info log path exists before testing

- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/tests/aws_firehose_tests.cpp
- osquery/logger/plugins/tests/aws_kinesis_tests.cpp
The AWS plugins were correctly handling errors with individual records posting,
but did not handle an error for the overall request (such as an auth error). As
a result, when these errors occurred, osquery would print "Successfully sent 0
records to Kinesis." We now explicitly handle these errors.
Fixes #3310
> Fix error handling in AWS logger plugins

- osquery/events/linux/audit.cpp
- osquery/events/linux/audit.h
This "isolates" the audit consumer logic (well, most of) into a single consumer thread. It tries to be smart about the size of the queue used to buffer audit replies. If there are too many replies then it drops instead of consuming too much memory. If the queue size was ever > 100 then the queue container is replaced.
After several performance tests (system stress at 11), this will peak RSS at 50M. The success rate is poor, but comparable to previous implementations.
> audit: Isolate the audit consumer logic into a thread

- osquery/core/init.cpp
- osquery/core/posix/process.cpp
- osquery/core/watcher.cpp
On POSIX systems we are ignoring `SIGCHLD` and thus cannot inspect the exit-code for child worker processes. This is OK since we will never have an unreaped zombie child, but we cannot exit fast on 'catastrophic' errors like bad configuration or failure to log.
Following: https://stackoverflow.com/questions/7171722/how-can-i-handle-sigchld-in-c and the quoted:
> Explicitly setting the disposition of SIGCHLD to SIG_IGN causes any child process that subsequently terminates to be immediately removed from the system instead of being converted into a zombie.
We need to remove the ignore for `SIGCHLD` so our no-hang `waitpid` calls do not default return `-1`. This will move the ignoring into the default signal handler. So if the watcher receives any signal it will begin ignoring updates from …
> worker: Do not ignore SIGCHLD to exit faster

- osquery/tables/networking/posix/interfaces.cpp
- specs/interface_details.table
This data is available in both Linux and OSX from the [rtnl_link_stats](https://chromium.googlesource.com/native_client/linux-headers-for-nacl/+/2dc04f8190a54defc0d59e693fa6cff3e8a916a9/include/linux/if_link.h) and [if_data](https://developer.apple.com/documentation/kernel/if_data).
```
osquery> select interface, collisions from interface_details;
+-----------+------------+
| interface | collisions |
+-----------+------------+
| lo0       | 0          |
| gif0      | 0          |
| stf0      | 0          |
| en0       | 0          |
| en2       | 0          |
| en4       | 0          |
| en1       | 0          |
| en3       | 0          |
| bridge0   | 0          |
| p2p0      | 0          |
| awdl0     | 0          |
| utun0     | 0          |
| en6       | 0          |
| fw0       | 0 …
```
> Add collisions to the interface_details table

- tools/tests/test_osqueryd.py
As windows relies on the file system query to find the INFO logs, we need to wait for the log to actually exist. This entails re-querying inside of the `expectTrue` loop.
> windows: Waiting for info log in tests

- osquery/tables/system/darwin/gatekeeper.cpp
- specs/darwin/gatekeeper.table
- specs/darwin/gatekeeper_approved_apps.table
This pull request adds two tables to instrument Apples macOS' app security subsystem called Gatekeeper.
The first table is called `gatekeeper` it simply returns a single row with several columns that enumerate facts about the status of gatekeeper protection. This table can detect if gatekeeper is wholesale disabled or if it is enabled and if developer signed apps are allowed to run.
The second table is called `gatekeeper_approved_apps`. This table enumerates all of the unsigned apps that have been explicitly whitelisted by a user. This list is populated when you attempt to run an app that is unsigned (or signed by an unknown key) and you explicitly allow it to run by going into the Security & Privacy settings of the System Preferences app.
Ensuring Gatekeeper is enabled is an important …
> Darwin: Add gatekeeper tables

- tools/provision.sh
Brew updated and `make deps` and `make sysprep` are now broken. Pull the homebrew and homebrew-core taps forward to fix this.
> (Fix #3504) Pull taps forward to unbreak make deps

- include/osquery/status.h
- include/osquery/tables.h
- osquery/sql/sqlite_math.cpp
- osquery/tables/applications/posix/docker.cpp
- osquery/tables/system/linux/md_tables.cpp
- osquery/tables/system/linux/tests/md_tables_tests.cpp
- osquery/tables/system/windows/scheduled_tasks.cpp
Fixed some cppcheck warnings:
* Inefficient usage of string::find() in condition (docker.cpp etc)
* Function parameter 'm' should be passed by reference (status.h)
* Passing the result of c_str() to a function that takes std::string as argument no. 1 is slow and redundant (scheduled_tasks.cpp)
Fixed "make docs" on Ubuntu. Was failing with following error:
osquery/include/osquery/tables.h:788: error: The following parameters of osquery::TablePlugin::isCached(size_t interval, const QueryContext &ctx) const are not documented:
parameter 'ctx' (warning treated as error, aborting now)
> Some "make audit" output fixes.

- tools/provision/formula/zstd.rb
Update the bottles for `zstd`.
> deps: Add bottles for linux and macOS for zstd

- tools/provision/formula/bison.rb
Update the bottle hashes for `bison`, macOS is the only platform using a local-bison build.
> deps: Add bottle for macOS for bison

- osquery/tables/system/freebsd/processes.cpp
- osquery/tables/system/freebsd/procstat.cpp
- osquery/tables/system/freebsd/procstat.h
I find that some of the process structures on Linux and macOS are esoteric enough that in edge-cases return `nullptr`s for paths/directories/etc.
This attempts to add additional checking to these structures.
> freebsd: Some refactoring to processes table

- Vagrantfile
On Ubuntu14 make sysprep requires realpath to be isntalled to run.
> <Vagrant/ubuntu: Add a dep for running make sysprep>

- osquery/events/linux/audit.cpp
- osquery/filesystem/file_compression.cpp
- osquery/filesystem/linux/mem.cpp
- osquery/filesystem/linux/proc.cpp
- osquery/tables/applications/posix/prometheus_metrics.cpp
- osquery/tables/applications/posix/prometheus_metrics.h
- osquery/tables/sleuthkit/sleuthkit.cpp
- osquery/tables/system/hash.cpp
- osquery/tables/system/linux/md_tables.cpp
- osquery/tables/system/linux/processes.cpp
proc.cpp and processes.cpp, changed changed readlink() to realpath(). There was
no issue with the code, but it is easy to mis-use readlink. It can return
strings which are not null terminated in wrong arguments are passed.
Fixed 'meta' leak in sleuthkit.cpp#hashInode()
In sleuthkit.cpp, hash.cpp and md_tables.cpp structs were not properly
intialized. This can cause random values to be returned for primitive types
in the struct.
In audit.cpp initialize default value for max_size_.
In file_compression.cpp, handle -1 returned from read(). Also avoid divide
by zero if FLAGS_carver_block_size is accidentally set to 0.
while loop in mem.cpp#readMem never entered because bytes_read was initialized
to 0.
> Fixes from static code analysis

- osquery/tables/system/darwin/shared_folders.mm
- specs/darwin/shared_folders.table
This pull request resolves #3393 by implementing a `shared_folders` table. 
The shared table folder simply lists all folders marked as a "shared folder" via the properties GUI in Finder, the `dscl` binary, and the File sharing options under "Sharing" in System Preferences.
```
osquery> select * from shared_folders;
+------------------------------+-----------------------+
| name                         | path                  |
+------------------------------+-----------------------+
| Jason Meller’s Public Folder | /Users/jmeller/Public |
+------------------------------+-----------------------+
```
The table returns the folder's path and the name other users will see it when browsing it via SMB or AFP.
This table will return shared folders _regardless_ if file sharing is enabled or not. …
> tables: Implement shared folders table for Darwin

- osquery/tables/system/darwin/iokit_registry.cpp
- specs/darwin/device_firmware.table
This adds `device_firmware`, a general table for listing device firmware versions. Feel free to extend this and add platform firmware.
```
./build/darwin/osquery/osqueryi -A device_firmware            
+-------------+--------------------------------------+-----------------------------------------+
| type        | device                               | version                                 |
+-------------+--------------------------------------+-----------------------------------------+
| IOPCIDevice | AppleS3XController                   | 14.17.01                                |
| IOPCIDevice | AirPort_Brcm4360                     | Broadcom BCM43xx 1.0 (7.21.171.130.1a1) |
| IOResources | IOBluetoothHCIController             | v48 c4227                               |
|             | …
```
> tables: Add device_firmware to darwin

- .clang-format
If you try to run `make format_all` it will error on ObjC files on macOS. The clang-format documentation says that not including a `Language` stanza means the following rules are applied to all languages.
https://clang.llvm.org/docs/ClangFormatStyleOptions.html
> format: Remove Cpp restriction

- tools/provision/formula/aws-sdk-cpp.rb
This updates the bottle hashes for `aws-sdk-cpp` version `1.1.20`.
> deps: Update AWS-SDK 1.1.20 bottles

- osquery/devtools/shell.cpp
It doesn't make sense to call `SQL::SQL` and it breaks FreeBSD 12's build.
> Fix #3522: Do not call SQL ctor directly

- osquery/tables/networking/windows/arp_cache.cpp
- osquery/tables/networking/windows/interfaces.cpp
The `arp_cache` table wasn't grabbing indexes correctly, and thus we were hitting scenarios where attempts to get an interface at a predefined index wouldn't exist.
> [Fix #3527] Addressing interface indexing in arp_cache table

- docs/wiki/deployment/configuration.md
- osquery/tables/cloud/ec2_instance_metadata.cpp
- specs/linux/ec2_instance_metadata.table
This is based on https://github.com/facebook/osquery/pull/2853
I made some optimizations and cleanup.
When queried on non-EC2 instance, this table responds with no results
in 3 seconds. Subsequent queries are immediately returned.
On EC2 instance, each query makes 7 round trips to meta-data servers.
Original pull request had copyright claim by jfdive with BSD license.
I changed it to standard Facebook copyright.
> EC2 instance metadata implementation.

- osquery/tables/system/darwin/gatekeeper.cpp
Use `sqlite3_close` rather than `free` to properly release DB handle resources.
Fixes #3515
> Fix memory leaks in Gatekeeper table

- include/osquery/system.h
- osquery/carver/carver.cpp
- osquery/core/system.cpp
- osquery/events/linux/audit.h
- osquery/logger/logger.cpp
- osquery/tables/applications/posix/prometheus_metrics.cpp
- osquery/tables/networking/posix/utils.cpp
system.h: group_size_ can potentially be assigned negative value
carver.cpp: bytesRead can be negative. Check before calling write()
system.cpp: In rare cases (?) std::time can return -1. Fallback to 0 to avoid passing negative value to method that expect unsigned values
system.cpp: Check group_size_ before allocation memory
audit.h: Initialize status_ and reply_ fields
logger.cpp: Catch ptree error which can be thrown from put() and write_json
prometheus_metrics.cpp: Remove unnecessary default tree passed to get_child. count("urls") ensures that child tree exists
utils.cpp: Check addr->ifa_name for nullptr
> Minor static analysis fixes.

- tools/provision/formula/libdpkg.rb
A small fix to the URL for `dpkg`. The FTP on debian.org does not include patch 23 anymore.
> deps: Fix libdpkg download url

- osquery/tables/system/darwin/processes.cpp
This hopefully (works for me at least) fixes the issue presented in ticket #3495. Needs to be tested on older OSX builds.
> A fix for Mac OSX process start_time

- osquery/tables/system/linux/usb_devices.cpp
- specs/posix/usb_devices.table
This enables the `usb_devices` table to show as well the device class, device subclass and protocol as defined [there](http://www.usb.org/developers/defined_class) when the information is available.
```
osquery> select * from usb_devices;
+-------------+----------+------------------+-----------+--------------+----------+--------------+-----------+
| usb_address | usb_port | vendor           | vendor_id | model        | model_id | serial       | removable |
+-------------+----------+------------------+-----------+--------------+----------+--------------+-----------+
| 1           | 1        | Linux Foundation | 1d6b      | 1.1 root hub | 0001     | 0000:00:01.2 | -1        |
+-------------+----------+------------------+-----------+--------------+----------+--------------+-----------+
``` …
> linux usb_devices: add the class, subclass and protocol information

- packs/incident-response.conf
The current pack query throws the following error:
```
sudo su - root
Password:
~ root# osqueryi
I0809 12:09:06.350368 2952184640 options.cpp:63] Verbose logging enabled by config option
I0809 12:09:06.413350 2952184640 events.cpp:707] Subscriber expiration is too low: hardware_events
osquery> select * from shell_history;
W0809 12:09:11.895354 2952184640 virtual_table.cpp:516] The shell_history table returns data based on the current user by default, consider JOINing against the users table
W0809 12:09:11.895416 2952184640 virtual_table.cpp:531] Please see the table documentation: https://osquery.io/docs/#shell_history
```
This PR will grab shell_history for all users on the system.
Per conversation in osquery slack: …
> Updating shell_history in IR pack to include all users

- osquery/tables/system/freebsd/pkg_packages.cpp
This should fix #3440. The SQLite database was being freed, but not closed causing some allocated resources to go out of scope.
> Fix memory leak in FreeBSD pkg_packages

- osquery/tables/system/darwin/quicklook_cache.cpp
Fixes a small memory leak in quicklook_cache. The SQLite database was being freed, but not closed causing some allocated resources to go out of scope.
Before:
```
Analyzing leaks in query: select * from quicklook_cache
definitely:  63 leaks for 5984 total leaked bytes.
```
After:
```
Analyzing leaks in query: select * from quicklook_cache
definitely: 0 leaks for 0 total leaked bytes.
```
> Fix an sqlite3 memory leak in quicklook_cache

- osquery/tables/system/linux/md_tables.cpp
- osquery/tables/system/linux/md_tables.h
- osquery/tables/system/linux/tests/md_tables_tests.cpp
While testing another feature, discovered the following corner case while `osqueryd` was running packs:
```bash
Executing scheduled query pack_system-snapshot_md_drives_per_hour: select * from md_drives
terminate called after throwing an instance of 'std::out_of_range'
what(): basic_string::compare: __pos (which is 4) > this->size() (which is 3)
```
I managed to reproduce this one other time after hours running, but could not do so again.  Also did a query on kibana across the infra, and didn't get any hits.  Nevertheless I walked through the code paths of the `md_drives` query, and tightened up the areas that could have produced that issue, as well as adding a negative test.  Will update if I come across more information.
> md tables: additional bounds checking around substr calls

- tools/provision.sh
- tools/provision/formula/libcryptsetup.rb
This revers the `homebrew-core` tap back to `binutils` version 2.28, see #3533.
It also links `-lm` for `libcryptsetup`. It seems this is needed with the recent changes to devmapper.
> deps: Fix Linux build-world and link math for cryptsetup

- CMakeLists.txt
- osquery/CMakeLists.txt
- tools/tests/CMakeLists.txt
This PR makes me cry a little but IMO it is a good compensation for valuable sanitizer warning that are eaten by difficult-to-fix custom allocator problems. My suspicion is that static linking 20+ MB of content causes systemic issues. I've at least not been able to track down why random alignment problems occur with sanitizer tests.
> sanitizers: Skip several tests that fail custom alloc checks

- Makefile
The `PATH_SET` variable should be included in the `make` `DEFINES` as that list of environment variables is passed to whatever is called after `cmake`.
> build: Set PATH_SET in the make defines

- tools/provision.ps1
- tools/provision/chocolatey/llvm-clang.ps1
This brings the clang compiler and utility binaries to Windows. Initially this will just be for leveraging the `clang-format` binary, however we'll make use of this soon to perform osquery builds using clang.
This should also address #3561
> dependencies: Adding build script for llvm-clang package for windows

- osquery/tables/CMakeLists.txt
- osquery/tables/system/linux/block_devices.cpp
- osquery/tables/system/linux/disk_encryption.cpp
Filling in the parent field in the `block_devices` table with the containing LVM physical volume allows `disk_encryption` rows to inherit encryption status from parents.
My lsblk + device map:
```
$ lsblk
NAME                     MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
nvme0n1                  259:0    0   477G  0 disk  
├─nvme0n1p3              259:3    0   476G  0 part  
│ └─nvme0n1p3_crypt      253:0    0   476G  0 crypt 
│   ├─xubuntu--vg-root   253:1    0 456.2G  0 lvm   /
│   └─xubuntu--vg-swap_1 253:2    0  19.8G  0 lvm   [SWAP]
[snip]
$ ls -l /dev/mapper/
total 0
crw------- 1 root root 10, 236 Aug 10 09:08 control
lrwxrwxrwx 1 root root       7 Aug 10 09:08 nvme0n1p3_crypt -> ../dm-0
lrwxrwxrwx 1 root root       7 Aug 10 09:08 xubuntu--vg-root -> ../dm-1
lrwxrwxrwx 1 root root …
```
> add LVM and parental contexts to block_devices and disk_encryption on Linux

- tools/deployment/chocolatey/tools/chocolateyBeforeModify.ps1
- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
- tools/deployment/chocolatey/tools/chocolateyuninstall.ps1
This updates the Powershell chocolatey deployment scripts to ensure the environment is sane before attempting an install, which should result in more robust installations and uninstallation on Windows systems.
> deploy: adding sanity checks to deployment powershell scripts

- osquery/core/windows/process_ops.cpp
This addresses #3400 in which domain users uid value not showing up in either the users or processes table.
> bug: Processes name correctly displays uid for domain users

- Makefile
- Vagrantfile
- tools/deployment/make_linux_package.sh
- tools/provision/amazon.sh
- tools/provision/arch.sh
- tools/provision/centos.sh
- tools/provision/debian.sh
- tools/provision/fedora.sh
- tools/provision/freebsd.sh
- tools/provision/manjaro.sh
- tools/provision/oracle.sh
- tools/provision/rhel.sh
- tools/provision/scientific.sh
- tools/provision/ubuntu.sh
1. `realpath` is not needed when we can use `readlink --canonicalize`. This is more widely supported and allows use to use Vagrant out of the box on older RHEL and CentOS machines (if you're still custom-building on those).
2. The `make sysprep` command should install `doxygen` and `valgrind` for documentation generation and memory `--leaks` analysis.
> deps: Add doxygen and valgrind and remove realpath requirement

- tools/analysis/profile.py
The `./tools/analysis/profile.py` can use `--leaks` to auto-find an `osqueryi` shell from the build directory and begin running each table: `select * from TABLE`. If any leaks are detected it will complete the execution and return 1, otherwise 0.
> leaks: Return 1 if profile detects any leaks in tables

- osquery/utils/aws_util.cpp
This fixes a TSAN warning (see: #3555) with `cpp-netlib` and `aws-sdk-cpp`.
We had fixes this once before, but also had removed valuable debug information. We choose to re-enable but forgot to test if copying the exception would be thread-safe: #3456.
> aws: Fix TSAN warning in request exception

- osquery/tables/system/darwin/preferences.cpp
This addresses #3544
Some plists might have sublists, and it seemed that while we were processing these correctly it may be the case that the plist subitems don't have a label as it's enumerating list values. This makes an attempt to grab the `Name` field if it exists, and use this as the Label for list objects. This is particularly useful in the case of the MobileMeAccounts plist file.
> tables: Adding list indexing to darwin plist table

- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
This prevents LIKE and GLOB from being optimized into `> /EXPRESSION` and `<= /expression0`.
See #3579.
> sql: Handle potential LIKE and GLOB optimizations by increasing comparisons

- osquery/events/linux/audit.cpp
This was missed before, see #3584.
We need a CI test for this too.
> audit: Handle AUDIT_SOCKADDR messages

- osquery/logger/plugins/buffered.cpp
- osquery/logger/plugins/buffered.h
I tested this with `SANITIZE_THREAD=1` and `make sanitize` on Linux. The goal is to protect the internal memory for `buffer_count_` but also the logic that increments and decrements. It seems to be rolling over and to protect the check and edit we switch the atomic to a mutex over the critical section.
> logger: Use a mutex to protect buffered counts

- tools/deployment/osqueryd.initd
- tools/deployment/osqueryd.service
- tools/deployment/osqueryd.sysconfig
The `OLD_PIDFILE` defined in the sysconfig would override the `initd` `OLD_PIDFILE` default. These are two different settings so they should be named differently in their defaults.
> deploy: Change OLD_PIDFILE for systemd to be LOCAL_PIDFILE

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
- tools/deployment/chocolatey/tools/chocolateyuninstall.ps1
Some of our `Write-Output` messages during the chocolatey install are extraneous, or just flat out wrong. This removes those, and changes our `Write-Output`s to `Write-Debug` to ensure verbosity only shows up when needed/asked for.
> deploy: removing extraneous verbosity from windows deployment scripts

- tools/provision/formula/asio.rb
- tools/provision/formula/boost.rb
- tools/provision/formula/cpp-netlib.rb
macOS may have trouble with `boost` 1.65. Update to identify breakage.
The intention of this change is to break macOS's build, so we can fix it with a follow up change to compiler defines.
> deps: Update boost to 1.65

- CMakeLists.txt
This include #3600 as a required stacked-commit. Note that they will land independently.
Fixes #3598.
> Boost version 1.65 macOS fix

- tools/provision/formula/rapidjson.rb
The `rapidjson` bottle was trying to download it's bottle from Homebrew's binary storage. This would always fail due to (1) missing version and (2) a bad compile hash.
> deps: Fix rapidjson bottle root_url

- tools/provision.ps1
- tools/provision.sh
- tools/provision/formula/cmake.rb
This reduces the complexity of the `cmake` formula.
Version 3.9.1 will be needed for newer versions of xcode, see: https://gitlab.kitware.com/cmake/cmake/merge_requests/658
This tries to add a `-lto_library` as a link target, because of `-l...to...`.
Since `cmake` can bundle some of it's dependencies we can relax the requirements for our build list. The sooner we can build `cmake` the better.
The patch for `pthread` linking is applied because it's a "hidden" link dependency that the utility was expecting to get from `dl` or `rt`.
> deps: Update cmake to version 3.9.1

- osquery/tables/system/windows/chocolatey_packages.cpp
- specs/windows/chocolatey_packages.table
This brings a new virtual table to Windows, `chocolatey_packages`!  Similar to the python packages table, this lists out all packages which have been installed via chocolatey on a system. It relies on the chocolatey environment variable `ChocolateyInstall` to provide the table with the installation path, after which it pareses the packages `.nuspec`s for information.
```
osquery> select * from chocolatey_packages limit 10;
name = 7zip.commandline
version = 16.02.0.20170209
summary = 7-Zip is a file archiver with a high compression ratio.
author = Igor Pavlov
license = http://www.7-zip.org/license.txt
path = C:\ProgramData\chocolatey\lib\7zip.commandline\7zip.commandline.nuspec
name = 7zip.portable
version = 16.04
summary = 7-Zip is a file archiver with a high …
```
> tables: adding chocolatey packages virtual table

- include/osquery/system.h
- osquery/core/init.cpp
- osquery/main/windows/main.cpp
After merging the binaries together, the logic for handling shutdowns got a little muddled between the worker and the watcher. This adds an explicit clear on the pointer to the shutdown routine, as well as provides assurances that the watcher will be the only process to execute the shutdown logic. This partially addresses #3619 in that the service now correctly exits and does not emit any `ERROR` level logging, however the service still technically crashes as a dump is generated [at the destruction of the Dispatcher](https://github.com/facebook/osquery/blob/master/include/osquery/dispatcher.h#L205)
@theopolis hope you don't mind that I `cherry-picked` your commit <3
> worker: shutdown safely on Windows only if not worker

- docs/wiki/deployment/debugging.md
- include/osquery/database.h
- include/osquery/filesystem.h
- osquery/core/system.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/rocksdb.h
- osquery/database/plugins/tests/rocksdb_tests.cpp
- osquery/database/tests/plugin_tests.cpp
- osquery/database/tests/plugin_tests.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/tests/extensions_tests.cpp
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/tables/yara/tests/yara_tests.cpp
This tries to address: #3592.
First it renames: `osquery::remove` to `osquery::removePath` to differentiate from other similar method names (e.g., `std::remove`). `removePath` is then changed to use `boost::filesystem::remove_all`.
Second it adds a `movePath` that allows a file or directory to be moved to another location.
Use those two changes, this PR alters the behavior of the RocksDB database plugin's corruption and recovery behavior by first trying to move the existing corrupted database to `--database_path + ".backup"`. Then starting with a fresh DB at `--database_path`. The corruption detection logic is extended to include run-time detections. If a log-line is emitted indicating corruption then the next DB reset (default 5min) will perform the recovery.
There are several fixes …
> rocksdb: Implement a 'backup' and recover feature for RocksDB

- osquery/CMakeLists.txt
- tools/version.rc.in
As per the MSDN, Windows has the capability of bundling a versioning information resource with compiled binaries to offer publisher and version information to the operating system. This diff bundles said version resource so that we might gain additional information about the version of osquery running from various windows applications. In particular, the Windows Event Logs contain application logs about programs running on the system, and currently all of the values for osquery are blank and empty:
With this diff, we now have all of the fields filled out, so whenever the application crashes we'll be able to tell from Windows Event Logs the build version of the application:
This data acts as something of a redundancy to the information you can obtain from chocolatey data, however if …
> deploy: Adding binary version and publisher information

- osquery/database/plugins/rocksdb.cpp
- osquery/database/plugins/rocksdb.h
This addresses #3594.
We can try to force RocksDB to use a max of 256 files. We should also be `Flush`ing all of the column families on reset. This is a bug because we were not using the RocksDB API correctly.
> rocksdb: Flush all column families and set max files

- osquery/logger/CMakeLists.txt
- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/aws_log_forwarder.h
- osquery/utils/CMakeLists.txt
- osquery/utils/aws_util.cpp
- osquery/utils/tests/aws_util_tests.cpp
- tools/provision/chocolatey/aws-sdk-cpp.ps1
- Updated the PowerShell script that generates the aws-sdk-cpp nupkg file to support the latest version (1.1.44).
- Disabled support for AWS credential profiles when running under Windows.
- A couple of small fixes to the tests for the AWS utilities.
The Aws::Auth::InstanceProfileCredentialsProvider causes a crash when enabled on Windows. I have disabled it for now, and would like to have some feedback.
> Add Firehose/Kinesis support to Windows

- osquery/utils/aws_util.cpp
- tools/provision.ps1
- tools/provision/chocolatey/aws-sdk-cpp.ps1
This bumps the AWS SDK version in the provisioning scripts, as well as addresses a few small fixes in the choco build script.
> deps: fixing up aws-sdk-cpp choco build script

- osquery/tables/networking/freebsd/routes.cpp
Fix clashing definitions of Free() between rapidjson and the system networking includes on older versions of FreeBSD.
> FreeBSD: Avoid clash with rapidjson

- osquery/tables/cloud/ec2_instance_metadata.cpp
- osquery/utils/aws_util.cpp
- osquery/utils/aws_util.h
Moved isEc2Instance check to utility class.
Add faster check to see if instance is EC2 (using hypervisor UUID).
This avoids the 3 second initial timeout on non-EC2 instances.
Changed EC2 metadata URL to a constant.
> AWS code refactoring.

- docs/wiki/deployment/anomaly-detection.md
- docs/wiki/deployment/logging.md
- include/osquery/query.h
- osquery/config/parsers/tests/decorators_tests.cpp
- osquery/core/query.cpp
- osquery/core/tests/query_tests.cpp
- osquery/database/benchmarks/database_benchmarks.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/logger/plugins/tests/filesystem_logger_tests.cpp
- osquery/logger/tests/logger_tests.cpp
- osquery/tests/test_util.cpp
When setting up alerts for differential logs data you might want to skip the
initial added records. counter can be used to identify if the added records
are all records from initial query of if they are new records. For initial
query results that includes all records counter will be "0". For subsequent
query executions counter will be incremented by 1. When epoch changes, counter
will be reset back to "0".
> Query "counter" to differentiate initial results

- osquery/CMakeLists.txt
- osquery/filesystem/linux/proc.cpp
- osquery/tables/networking/tests/networking_tables_tests.cpp
This reverts a change added as the result of static analysis to replace `readlink` with `readpath`. From what I can tell, we're using `readlink` safely: https://www.securecoding.cert.org/confluence/display/c/POS30-C.+Use+the+readlink%28%29+function+properly
This adds a test for `listening_ports` using the internal `TLSServerRunner` so we do not regress again.
> [Fix #3625] Use readlink and add test for listening_ports

- tools/deployment/make_linux_package.sh
The binary unification (combine `osqueryi` and `osqueryd` into a single binary) created a regression in the package build script. This is identified by the periodic `make packages` build: https://jenkins.osquery.io/job/osqueryMasterPackagesPosix/TargetSystem=aws-ubuntu-16.04/771/console
> packages: Fix debug info break from binary unification

- osquery/main/windows/main.cpp
This addresses #3637
As we've merged the binaries into one, the shell is attempting to grab the stop event, which doesn't exist when running as the interactive shell. This checks to ensure we're only processing the stop event if we're the daemon.
> shell: ensuring shell does not access stop event

- osquery/database/plugins/rocksdb.cpp
We're using the RocksDB APIs incorrectly. We should not be calling `DB::Flush` manually (often).
> rocksdb: Remove manual flush

- osquery/remote/CMakeLists.txt
A refactor from far off lands had removed the enroll tests from the build.
> enroll: Fix bug in CMake that removed enroll tests

- osquery/CMakeLists.txt
The CMake line:
```cmake
get_property (DAEMON_EXECUTABLE TARGET daemon PROPERTY LOCATION)
```
Uses the deprecated `LOCATION` property. We are warned about setting the policy to `OLD`.
> cmake: Do not use target LOCATION property

- docs/wiki/deployment/remote.md
- include/osquery/enroll.h
- osquery/remote/enroll/enroll.cpp
- osquery/remote/enroll/plugins/tests/tls_enroll_tests.cpp
- osquery/remote/enroll/plugins/tls_enroll.cpp
- osquery/remote/enroll/plugins/tls_enroll.h
This closes #2560.
This pull request implements a simple `host_details` key addition to the `tls` enroll plugin.
The tables:
- `osquery_info`
- `platform_info`
- `system_info`
Populate the `host_details` key. The results of each table are included as keys themselves. These tables *should* only return a single row so that expectation is used to flatten the results into key->value. So expect: `{host_details.osquery_info.build_platform=ubuntu}` if building on a Ubuntu host.
> enroll: Add host_details to TLSEnrollPlugin

- osquery/config/parsers/options.cpp
A tiny change to handle setting `logger_min_level` within the `options` dictionary within configs.
> logger: Reconfigure verbosity with logger_min_level

- include/osquery/posix/system.h
- osquery/core/posix/process.cpp
- osquery/core/posix/process_ops.cpp
- osquery/core/process.h
- osquery/core/windows/process.cpp
- osquery/core/windows/process_ops.cpp
- osquery/tests/test_additional_util.cpp
This most important changes here:
- Do not emit a verbose log line in Windows when an environment variable cannot be found.
- Call the `launchPythonScript` `launchTestPythonScript`, there is no way to run a python script within osquery.
> process: Aesthetic changes to process and process_ops

- osquery/tables/system/posix/load_average.cpp
There's really no need to allocate a vector for periods.
Furthermore, since the number of results is known ahead of time we should reserve capacity.
> Load average table performance improvements

- osquery/tables/system/posix/known_hosts.cpp
Just some best practices.
Not sure what to do with kSSHKnownHostskeys vector yet.
In other tables we use a set for paths (See https://github.com/facebook/osquery/blob/master/osquery/tables/system/posix/python_packages.cpp#L30 for example).
> Known hosts table performance improvements

- tools/provision/chocolatey/osquery_utils.ps1
The `Osquery-StartProcess` cmdlet occasionally hangs based off of the behavior of the called subprocess. This fixes the cmdlet to ensure that we always return, as opposed to stalling.
> build: small fix to osquery utils Start-Process cmdlet

- tools/provision.ps1
- tools/provision/chocolatey/rocksdb.ps1
The previous upgrade of rocksdb for Windows was not built for portable, which was causing build fails on some platforms. This updates the libs builds to be portable.
> deps: building portable rocksdb libs

- osquery/tables/system/linux/usb_devices.cpp
Sometimes some devices are not in the host's database, in this case we should fallback to whatever is available, and it is in certain cases the raw ID_MODEL.
> [usb_devices] fallback to ID_MODEL if ID_MODEL_FROM_DATABASE is absent

- docs/wiki/installation/cli-flags.md
- include/osquery/core.h
- osquery/core/conversions.cpp
- osquery/core/tests/watcher_tests.cpp
- osquery/core/watcher.cpp
The documentation for `--watchdog_memory_limit` and `--watchdog_utilization_limit` are a little weak. Let's provide a tiny bit more information to make them helpful.
> watcher: Add more details to the utilization limits docs

- osquery/tables/system/darwin/system_info.cpp
I am not sure if this method is more reliable.
> [Fix #3140] Use IODeviceTree:/ for hardware fields

- osquery/tables/system/darwin/preferences.cpp
- specs/darwin/preferences.table
This implements #3501.
Instead of performing the 'override' detection, the table now includes a `host` column (similar to Apple's parameter name when using the preferences APIs). A user of the table must apply the knowledge of what host "type" overrides.
> preferences: Report both Current Host and Any Host

- osquery/tables/system/darwin/packages.mm
- specs/darwin/package_receipts.table
With this change:
```
osqueryi "select count(1) from package_receipts" --line        
count(1) = 198
```
Before:
```
osqueryi "select count(1) from package_receipts" --line        
count(1) = 90
```
> [Fix #2400] Use PackageKit to enumerate packages

- README.md
Several folks have been asking if the osquery team is hiring. Let's place a link in the README to direct them to the right place.
> readme: Add callout for osquery devteam recruiting

- osquery/core/conversions.h
- osquery/core/windows/wmi.cpp
- osquery/tables/networking/tests/networking_tables_tests.cpp
- osquery/tables/networking/windows/arp_cache.cpp
- osquery/tables/networking/windows/interfaces.cpp
- specs/interface_addresses.table
- specs/interface_details.table
This changes the value of the `Interface` column on Windows systems to be that of the interface index used by Windows. This change allows us to join the `interface_addresses` table with the `interface_details` table on this common index value to get extended interface information per interface address value. Further this PR gets data for interface packet sent/received, bytes sent/received and inbound/outbound errors as well as populates the `type`, `metric`, and `flags` columns thus addressing #2907
> [Fix #3683] Setting interface id for interface_addresses

- include/osquery/system.h
- osquery/core/init.cpp
- osquery/main/windows/main.cpp
This PR adds better logic to the Windows service shut down process which ensures both worker and watcher `WaitForSingleObject` until the `stopEvent` is signaled, only one time.  Further we move the `UpdateServiceStatus(0, SERVICE_STOPPED, 0, 4);` to the end of our service control handler thread, to ensure that the process does not terminate before the watcher and worker both have an opportunity to `stop` and `join` all relevant service threads. This addresses #3619
> [Fix #3619] Better shutdown logic for Windows service controller

- osquery/logger/plugins/aws_log_forwarder.h
- osquery/logger/plugins/tests/aws_logger_tests.cpp
This is a small change to make sure that the administrator is notified right away when the configuration of the Firehose and/or Kinesis plugins are not (or no longer) valid.
Without this patch, such errors are not shown until the retry count expires; this value is usually pretty high (100 by default on Firehose) and we must take into account that there's also a pause between each attempt.
> aws_kinesis/aws_firehose: Be more verbose when complete failures occur.

- Vagrantfile
Added official vagrant target for xenial64 and CentOS 6 and 7.
bento boxes are quite out of date.
> Add official vagrant targets for ubuntu/centos.

- osquery/tables/system/darwin/apps.mm
- specs/darwin/apps.table
This Pull Request adds a new column called `last_opened_time` to the Darwin apps table.
Users of Osquery may want to know when the last time an app was launched by a user. Examples of this need could be analyzing app useage for license recovery, or checking if an undesirable or malicious file was executed by a user.
Traditional methods of getting this data (atime) are usually inaccurate as the timestamp is updated when the app is accessed by a benign process (an indexer, or even Finder itself).
Spotlight's indexer maintains a special metadata attribute on files (and mach-o apps) called `kMDItemLastUsedDate`. Which Apple's docs define as...
> The date and time that the file was last used. This value is updated automatically by LaunchServices everytime a file is opened by double clicking, …
> Add last_opened_time to apps table

- Vagrantfile
- tools/get_platform.py
- tools/lib.sh
- tools/provision.sh
- tools/provision/amazon.sh
- tools/provision/arch.sh
- tools/provision/centos.sh
- tools/provision/debian.sh
- tools/provision/manjaro.sh
- tools/provision/oracle.sh
- tools/provision/rhel.sh
- tools/provision/scientific.sh
- tools/provision/suse.sh
- tools/provision/ubuntu.sh
Vagrant tweaks and SuSE support
Changed vagrant boxes:
* debian updated to target latest bento/debian boxes
* Removed centos6.5 (which was incorrectly pointing to centos-6.7 box)
* Removed centos7.1 (centos7 can be used instead)
* Changed centos boxes to use elastic. These seems to be actively updated
* Changed ubuntu17.04 to use bento/ubuntu17.04
* Updated freebsd to latest bento boxes
* Updated archlinux to official archlinux box
* Added suse11 and suse12 from elastic
* Install git, make and python on ubuntu boxes from Vagrantfile
Updated tools/get_platform.py and tools/lib.sh  to handle SuSE
Added tools/provision/suse.sh. It just invokes zypper update
pip installation on some Ubuntu16 and CentOS7 fails with compilation issues
(when setting up PyYAML). Added libyaml dependency.
Cleaned …
> Vagrant tweaks and SuSE support

- tools/deployment/make_windows_package.ps1
- tools/provision/chocolatey/osquery_utils.ps1
With a recent upgrade to how Chocolatey packages work, we're being required to add in the LICENSE file as well as a file detailing how to verify the package shipped is correct. This brings logic to our deployment script to copy the LICENSE file as well as generate a verification text file with instructions how to verify the binary obtained is the correct binary.
> deploy: Adding license and verification information to chocolatey package

- docs/404.html
- docs/_config.yml
- docs/_includes/header.html
- docs/_includes/primary-nav-items.html
- docs/_sass/_style.scss
This diff includes a few fixups for the new website.
- The `Home` button of the right-hand side top navbar is removed. This is a duplicated link, the logo, left-side also goes home.
- The schema is fetched and constructed at run-time from another "data" repo. Currently this is my local repo, we need to change this to the `osquery` organization's `osquery-site` repo.
- The logo is too large on mobile. This is fixed to remove the extra margins.
- The downloads and code-views overflow their windows now. This fixes them to use a hidden overflow and an ellipse indicating the content is clipped.
> website: Remove "home" change schema url to osquery/osquery-site

- osquery/events/linux/auditdnetlink.cpp
- osquery/events/linux/auditdnetlink.h
- osquery/events/linux/auditeventpublisher.cpp
- osquery/events/linux/auditeventpublisher.h
- osquery/events/linux/tests/audit_tests.cpp
- osquery/events/linux/tests/auditd_fim_tests.cpp
- osquery/tables/events/linux/auditd_fim_events.cpp
- osquery/tables/events/linux/auditd_fim_events.h
- osquery/tables/events/linux/process_events.cpp
- osquery/tables/events/linux/socket_events.cpp
- specs/posix/auditd_fim_events.table
- Added the process **uid** and **gid** columns.
- Renamed the **path1** column to **path**.
- Renamed the **path2** column to **dest_path**.
- Print the **saddr** event field contents when the parser fails. The original function parsing the field has not been changed (this is straight from master); this may still come in handy when debugging.
- Use DecodeAuditPathValues to read path fields from the event records.
- Add support for clearing Audit rules when osquery starts ( #3468 ).
> Update column names, add process uid/gid, add switch to clear Audit config on startup.

- docs/Gemfile
- docs/README.md
- docs/_config.yml
- docs/_includes/footer.html
- docs/downloads/downloads.html
This is a work in progress as I test the viability of `html-proofer`. Currently it finds quite a few errors. If it runs in the Jenkins job without too many dependencies then it will be enabled for all PRs.
> website: Add Jekyll CI checks using html-proofer

- osquery/logger/plugins/kafka_producer.cpp
- osquery/tables/applications/posix/prometheus_metrics.cpp
Use get_child_optional instead of get_child.
> Avoid unnecessary ptree allocation.

- osquery/carver/carver.cpp
- osquery/filesystem/file_compression.cpp
- osquery/filesystem/fileops.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/windows/fileops.cpp
This is a cleanup diff. The `PlatformFile` class is not trivially copyable, maybe it once was, but it's best to assume we shouldn't need to copy it. The constructor should take a `boost::filesystem::path` as most callsites are already operating on paths and on Windows a copy of a `boost::filesystem::path` was already stored though not really needed.
> filesystem: Use fs::path for PlatformFile ctor

- osquery/tables/system/darwin/firewall.cpp
- osquery/tables/system/darwin/tests/firewall_tests.cpp
This will generate all of the `alf_services`.
Working towards solving #2322.
> tables: alf_services should not be hardcoded

- packs/it-compliance.conf
Super minor diff, this is just to have querypacks automatically collect browser extension data for all users on a machine.
> Updated it-compliance query pack for browser extensions

- osquery/events/events.cpp
per the discussion here 
```
yanxin [10:24 AM] 
Hello, try to use osquery on Ubuntu laptop
[10:24] 
got the error after basic config
[10:24] 
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0928 09:51:42.747632 25866 events.cpp:824] Event publisher failed setup: audit: Publisher disabled via configuration
I0928 09:51:42.747768 25866 events.cpp:824] Event publisher failed setup: kernel: Cannot access /dev/osquery
I0928 09:51:42.747788 25866 events.cpp:824] Event publisher failed setup: syslog: Publisher disabled via configuration
yanxin [10:36 AM] 
anyone can help?
zwass [10:39 AM] 
Those are expected and don't indicate any problem unless you are explicitly trying to use those event publishers. (edited)
yanxin [10:51 AM] 
got it, thanks for explaining @zwass
[10:51] …
```
> soften language to not enabled rather than failed

- osquery/tables/system/linux/disk_encryption.cpp
Previously the `char *` values from `crypt_`* APIs were auto-constructed into `std::string`s. These must be checked for `nullptr` return values first.
> [Fix #3717] Check crypt API values before constructing strings

- docs/_layouts/schema.html
- docs/_schema/2.8.0.md
This renders the `2.8.0` schema (forget to include this redirect and render before). And adds some javascript that allows a `#table_name` focus request to scroll after the rendering.
> website: Render 2.8.0 schema and add schema scrollTo

- tools/manage-osqueryd.ps1
osquery version: 2.8.0
OS: Windows 10
**Problem:**
$args is a an automatically defined variable in Powershell (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-5.1)
Because of this, any parameter passed via the `-args` flag does not get parsed by `manage-osqueryd.ps1` and it will always contain a blank string. Simply add a `write-host "Arguments: $args"` anywhere in the script to verify this behavior.
By renaming `$args` to something different like `$startup_args`, we avoid this issue. This code has been tested and works on my Win10 host.
> manage-osqueryd.ps1: Fix for -args parameter

- docs/_config.yml
The current set of redirects are including `/osquery`. This is because GitHub pages is setting `site.baseurl` to the project name. The redirect-from plugin respects this. Reading though https://github.com/github/pages-gem/issues/350 it seems we can set the `baseurl` to an empty string to 'fix' this for our proxying scenario.
> website: Fix redirects with /osquery using empty baseurl

- osquery/tables/events/linux/socket_events.cpp
Hello,
The family of IPv6 sockets, in **osquery 2.7.0**, is converted from 'A' to '11'.
According to the mapping of protocol to integer values, the correct family identifier for IPv6 sockets is 10. Therefore, I am opening this PR to fix it.
https://github.com/torvalds/linux/blob/80cee03bf1d626db0278271b505d7f5febb37bba/include/linux/socket.h#L171
> socket_events: Fix IPv6 family

- osquery/tables/system/windows/system_info.cpp
Adding support for hardware_serial to system_info.cpp
Reads serial number from the BIOs and returns -1 if i cannot be found.
Note:
Submitting on behalf of Google which has signed a CLA for this project.
dyl@google.com
> Add support for hardware_serial

- tools/provision/formula/gflags.rb
This version includes various static analysis updates, nothing critical of note in the release notes though.
> deps: Update gflags formula to version 2.2.1

- tools/provision/formula/aws-sdk-cpp.rb
Periodic update of `aws-sdk-cpp` dependency for Linux and macOS.
> deps: Update aws-sdk-cpp formula to version 1.2.7

- tools/provision/formula/libgcrypt.rb
- tools/provision/formula/libgpg-error.rb
This updates both `libgcrypt` and `libgpg-error`.
> deps: Update libgcrypt to version 1.8.1

- tools/provision/formula/libxml2.rb
This updates `libxml2` to version 2.9.5, the version we had been statically linking, 2.9.4 has known weaknesses.
> deps: Update libxml2 to version 2.9.5

- README.md
- SECURITY.md
There is no existing resource mapping potential weaknesses in osquery to versions including mitigation/fixes.
This list should be iterated soon to include higher priority fixes from third-party dependencies. It's difficult to track these in general, so we'll ask for forgiveness initially if we do not retroactively populate a mapping of dependency vulnerabilities to osquery versions including fixes.
> Add SECURITY.md security issues tracker

- tools/provision/formula/librdkafka.rb
Updating librdkafka to version 0.11.0, 0.9.5 is not that far behind so this is low priority.
> deps: Update librdkafka to version 0.11.0

- tools/provision/formula/libcryptsetup.rb
This significantly improves `libcryptsetup`. It now uses a source-repo-provided package and includes a pinned `sha256`. Previously, the osquery team could have patched our provided `libcryptsetup` source tarball during source dependency builds.
> deps: Update libcryptsetup formula to version 1.7.5

- tools/provision/formula/augeas.rb
Bump `augeas` to version 1.8.1 for Linux and macOS. This will need to bump `SECURITY.md` to include CVE-2017-7555.
> deps: Update augeas formula to version 1.8.1

- tools/provision.sh
- tools/provision/lib.sh
This is a small update to the commands:
```
./tools/provision.sh install osquery/osquery-local/NAME
./tools/provision.sh bottle osquery/osquery-local/NAME
```
It makes installing/testing/bottling a single updated dependency much easier.
> deps: Improve provision bottling scripts

- tools/provision/formula/libarchive.rb
This pulls in various vulnerability/weakness fixes within `libarchive` from Oct 23, 2016 to July 9, 2017.
> deps: Update libarchive formula to version 3.3.2

- tools/provision.ps1
- tools/provision/chocolatey/glog.ps1
This bumps glog to 0.3.5 on Windows, as well as brings some of the aesthetic updates to the packaging we've got in other scripts.
> deps: Bumping windows glog to 0.3.5

- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/formula/gflags.rb
- tools/provision/formula/glog.rb
- tools/provision/formula/libmagic.rb
This is a roll-up of bottles for `libmagic`, `glog`, `gflags`, and `aws-sdk-cpp` for Linux and macOS.
> deps: Update bottles for glog gflags libmagic aws-sdk-cpp

- tools/provision.ps1
- tools/provision/chocolatey/gflags-dev.ps1
This bumps our version of gflags to 2.2.1
> deps: Bumping windows gflags to 2.2.1

- osquery/tables/system/posix/known_hosts.cpp
This is a little clunky because under the hood the `usersFromContext` is selecting from users and then casing the `gid_t` and `uid_t` types as strings, then we convert them back to literals for the input to `DropPrivileges::dropTo`.
> [Fix #3762] Use DropPrivileges helper within known_hosts table

- tools/provision.ps1
- tools/provision/chocolatey/aws-sdk-cpp.ps1
- tools/provision/chocolatey/osquery_utils.ps1
This bumps the AWS cpp SDK to 1.2.7
> deps: bumping aws-sdk-cpp to 1.2.7 on windows

- tools/provision/chocolatey/osquery_utils.ps1
This fixes an issue with our Start-OsqueryProcess where processes were failing as the working dir hadn't been set.
> build: fixing start-osqueryprocess cmdlet

- tools/provision/formula/librpm.rb
The `librpm` formula should be rebuilt with new versions of `libxml2`. While the library works, the binaries used in `make package` may not.
> deps: Bump librpm revision for new libxml2 version 2.9.5

- osquery/core/tables.cpp
- osquery/core/tests/tables_tests.cpp
This places a `try` `catch` block around the constraints matching. If a constraint fails to be casted to the target column type the result of the match will be `false`.
> tables: Add exception handling within constraints matching

- tools/provision.ps1
- tools/provision/chocolatey/osquery_utils.ps1
Having multiple installations of Python on Windows systems can occasionally happen. This removes our restriction to use an explicit python path, and allows for leveraging python installs already present on the system, to avoid potentially many python installs and conflicting system environments.
> build: adding logic to discern python path on windows

- specs/chrome_extensions.table
- specs/darwin/browser_plugins.table
- specs/darwin/crashes.table
- specs/darwin/preferences.table
- specs/posix/authorized_keys.table
- specs/posix/firefox_addons.table
- specs/posix/known_hosts.table
- specs/posix/opera_extensions.table
- specs/posix/shell_history.table
- specs/posix/user_ssh_keys.table
- tools/analysis/fuzz.py
The `make fuzz` zzuf usage may miss some table content because it does not use the example queries. This mostly applies to tables that need to be joined against `users` because they emit user-generated content.
> fuzz: Use example queries as input to make fuzz

- osquery/tables/system/hash.cpp
One windows systems, using the `readFile` without setting the `block` mode `true` results in the use of Windows Async file reads. These can be advantageous for incredibly large files, but in the situation of reading a file for hashing purposes we prefer blocking operations to ensure we get all of the data at once.
This addresses #3756 by ensuring that we have read all of the data before hashing.
> [Fix #3756] Fixing windows hashes table

- docs/README.md
- docs/downloads/downloads.html
I refactored the downloads page template to make it more readable, removed a style from the "debug" section, and then added the previous versions section.
This is for issue #3796
> Add previous version downloads

- docs/downloads/downloads.html
See issue #3806.
Corrected curl command so that the GPG key is properly downloaded.
> Document fix for yum download instructions.

- include/osquery/extensions.h
- include/osquery/sql.h
- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/core/tests/tables_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/sql/sql.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
Fixes #3733 
We implement a "warm" query cache for the scheduler. This allows queries in the schedule that use the same virtual table to access the values from the warm cache without running the query logic again. This unexpectedly effected "live" or "distributed" queries. Before this change a distributed query may also have used the warm cache.
The new experience is the expected one. Distributed queries act on live data, they do not use the query cache. This is now the default for the entire application. Only the scheduler overrides the default action and chooses to use a query cache.
> tables: Require explicit requests for query results caching

- tools/release/commit_schema.sh
This should be run after `./new_release.sh`:
```bash
./commit_schema.sh 2.8.1 ~/git/osquery-site
[+] Will commit the following schema files: 
schema/2.8.1.json
Are you sure? [y/N]: y
[master 8c3773b] Adding schema $VERSION
1 file changed, 4118 insertions(+)
create mode 100644 schema/2.8.1.json
[+] Finished
```
> release: Add commit schema script

- osquery/tables/events/linux/process_events.cpp
- specs/posix/process_events.table
Added a method to convert decimal to octal, and used it to convert the "mode" column to octal in the ProcessUpdate method.
> Convert Linux process_events mode column to octal

- osquery/devtools/shell.cpp
- osquery/tables/system/linux/tests/md_tables_tests.cpp
Get the following errors from the latest commit (702203086f88931e32a4a582edc79d4a33d44798):
```
[ 97%] Built target osquery_additional_tests
osquery-git/osquery/devtools/shell.cpp:1188:34: error: qualified reference to 'SQL' is a constructor name rather than a type in this context
auto results = osquery::SQL::SQL(
^
1 error generated.
```
```
[ 97%] Built target shell
osquery-git/osquery/tables/system/linux/tests/md_tables_tests.cpp:75:13: error: qualified reference to 'Sequence' is a constructor name rather than a type in this context
Sequence::Sequence s1;
^
1 error generated.
```
The attached PR fixes both of these.
> Fixes compilation issues with latest master branch

- Vagrantfile
- tools/provision/darwin.sh
- tools/release/build_release.sh
This adds a new script `./tools/release/build_release.sh` that builds a consistent set of osquery packages for Linux and macOS.
> release: Add build release script

- docs/404.html
- docs/_config.yml
- docs/_includes/primary-nav-items.html
- docs/_sass/_style.scss
Several folks have pinged about the `/docs` page linking to an example. This was intentional but it is not the best UX. Until there is documentation/content, let's redirect to ReadTheDocs.
> website: Point docs link to ReadTheDocs

- tools/provision.sh
- tools/provision/lib.sh
This side-steps using the `brew tap` command. Instead we choose to checkout the `homebrew-core` repo into `./Library/Taps/homebrew/homebrew-core` manually. This avoids checks that `brew tap` applies unfortunately, but does break-fix initial `make deps` builds.
This also handles several bugs with parsing `brew info` output for new build environment setups.
> deps: Tap homebrew-core manually and fix initial sysprep

- include/osquery/posix/system.h
- osquery/core/system.cpp
- osquery/core/tests/posix/permissions_tests.cpp
- osquery/tables/applications/darwin/browser_plugins.cpp
- osquery/tables/system/posix/authorized_keys.cpp
- osquery/tables/system/posix/known_hosts.cpp
- osquery/tables/system/posix/shell_history.cpp
- osquery/tables/system/posix/ssh_keys.cpp
The goal here is to (1) reduce code reuse, specifically casting UID and GIDs into `uid_t` and `gid_t`s within table implementations and (2) to adopt the priv-dropping on several additional Linux tables.
> tables: Add dropTo with string UID and GID params

- docs/_config.yml
This is a huge nitpick, but without the trailing slash ReadTheDocs will 301 the client to non-https version of the documentation.
> website: Prevent readthedocs from a 301 to http

- osquery/events/darwin/event_taps.cpp
- osquery/events/darwin/event_taps.h
- osquery/tables/events/darwin/key_events.cpp
- specs/darwin/key_events.table
This adds and event publisher and table consumer for keydown events. We consume these from the operating system by registering an event tap.
You can see the event tap created by osquery with the following query:
```SQL
select * from event_taps;
```
You can get times for keydown events with:
```SQL
select * from key_events;
```
To break the key events down by minute:
```SQL
select time/60*60 as minute_started, count(time/60) as number_of_events from key_events group by (time/60);
```
> Publisher and Table for Event Tap Capture (KeyDown)

- osquery/devtools/shell.cpp
- osquery/main/main.cpp
In one terminal run:
```
./build/linux/osquery/example_extension.ext --socket ~/.osquery/shell.em --timeout 1000
```
In another run:
```
./build/linux/osquery/osqueryi --extensions_require=example --verbose --nodisable_extensions "select * from complex_example"
```
You can run the shell with `SANITIZE_THREAD=1 make sanitize` and observe no deadlock/unprotected critical sections. If you run without this patch the shell will hang, with this patch the table will execute correctly.
> [Fix #3831] Do not lock kAttachMutex within shell callbacks

- osquery/tables/system/darwin/keychain_utils.cpp
Fix the memory leak in the certificates table on macOS
> Fix the memory leak in the macOS certificates table

- tools/provision.ps1
Provisioning on Windows was recently changed to attempt derivation of the path where Python was installed on the system. This didn't update the system path after deriving the path, and as such newly provisioned systems were failing builds due to the inability to find python. This should fix that.
> provision: Python path sometimes not getting set on Windows

- docs/wiki/installation/cli-flags.md
- osquery/core/query.cpp
- osquery/logger/logger.cpp
- osquery/logger/tests/logger_tests.cpp
This implements #3701.
```
» cat ./build/example.conf 
{
"options": {
"logger_snapshot_event_type": "true"
},
"schedule": {
"3groups": {
"query": "select * from groups limit 3",
"interval": 5,
"snapshot": "true"
}
}
}
» ./build/linux/osquery/osqueryd --ephemeral --disable_database --logger_plugin=stdout --config_path ./build/example.conf
{"name":"3groups","hostIdentifier":"maverics","calendarTime":"Mon Oct 16 05:50:00 2017 UTC","unixTime":"1508133000","epoch":"0","counter":"0","columns":{"gid":"0","gid_signed":"0","groupname":"root"},"action":"snapshot"}
{"name":"3groups","hostIdentifier":"maverics","calendarTime":"Mon Oct 16 05:50:00 2017 UTC","unixTime":"1508133000","epoch":"0","counter":"0","columns":{"gid":"1","gid_signed":"1","groupname":"daemon"},"action":"snapshot"} …
```
> Add logger_snapshot_event_type flag for snapshot events

- osquery/tables/system/darwin/preferences.cpp
This commit writes `CFDate` values in the preferences tables as unix-timestamps-as-strings, in the same way we handle dates in property list files through the `plist` table.
> Support date type in OS X Preferences table (#3585)

- osquery/core/system.cpp
- osquery/tables/system/darwin/system_info.cpp
- osquery/tables/system/linux/system_info.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
- osquery/tables/system/windows/system_info.cpp
This adopts the Windows `hostname` = `FQDN` for Linux and Darwin.
> tables: Use FQDN for POSIX system_info hostname

- osquery/tables/system/darwin/usb_devices.cpp
- osquery/tables/system/linux/usb_devices.cpp
- specs/posix/usb_devices.table
This adds device version to the usb_devices table.  It's a bit of a mess to deal with, because it comes back as an unsigned 16 bit integer of 4 bit binary coded decimals.  See from here http://www.beyondlogic.org/usbnutshell/usb5.shtml
```
The bcdUSB field reports the highest version of USB the device supports. The value is in binary coded decimal with a format of 0xJJMN where JJ is the major version number, M is the minor version number and N is the sub minor version number. e.g. USB 2.0 is reported as 0x0200, USB 1.1 as 0x0110 and USB 1.0 as 0x0100.
The bcdDevice has the same format than the bcdUSB and is used to provide a device version number. This value is assigned by the developer
```
> Add version to usb_devices table

- tools/build.ps1
- tools/make-win64-binaries.bat
- tools/provision/chocolatey/osquery_utils.ps1
Considering Visual Studio now allows for multiple installations of different versions, we need a more robust build system to derive which build utilities to use. This adds a new Windows build script to derive at runtime the visual studio toolset to invoke, and abstracts the build logic around our utility helper functions. This should allow for a more robust build experience on Windows, and give opportunities for extending and iterating on build logic.
> [Fix #3567] Powershell build script to handle multiple VS installs

- tools/build.ps1
Fixing some spacing and verbosity that was unintentionally landed.
> build: removing excess verbosity from powershell build script

- packs/osx-attacks.conf
Adding:
- Additional file paths
- Launchd detection query
- Additional process path
https://www.welivesecurity.com/2017/10/20/osx-proton-supply-chain-attack-elmedia/
> Detect Proton.C variant detection from Elmedia Player

- osquery/devtools/shell.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
Fix #3859 
Instead of removing the lock within `osqueryi` we apply per-DB instance attach locking. The previous approach was invalid. It used a single lock for all attach requests regardless of the DB parameter. If there are two DBs we do not need to guard against locking each. We only need to make sure a single DB is not attached and queried simultaneously.
> [Fix #3831] Apply per-DB instance attach locking

- tools/codegen/gentable.py
Python returns `win32` not `windows` for `sys.platform`.
> Fix extended_schema on Windows

- tools/provision.sh
- tools/provision/formula/beecrypt.rb
- tools/provision/formula/berkeley-db.rb
- tools/provision/formula/librpm.rb
- tools/provision/formula/popt.rb
This installs `librpm` on macOS hosts. The dependencies for `librpm`: `popt`, `berkeley-db`, and the externally-managed `beecrypt` are also installed.
We will need `rpm_packages` on macOS eventually.
> deps: Install librpm on macOS

- tools/provision/formula/libdevmapper.rb
The "from source" Jenkins job has been failing because the LVM source package was removed from `sources.redhat.com`. It seems that `mirrorservice.com` keeps all the versions in the `./old` directory.
> deps: Use persistent LVM source url

- tools/release/build_release.sh
I found it's hard to re-run the `./tools/release/build_release.sh` script if something breaks (like updating `brew`). So this adds two checks around the Linux and Darwin build to skip them if packages already exist from their outputs.
> release: Make build_release idempotent

- osquery/core/conversions.cpp
- osquery/core/json.h
- osquery/core/tests/conversions_tests.cpp
- osquery/logger/logger.cpp
This introduces a small wrapper around some `rapidjson` APIs, called `JSON` to protect us from making easy mistakes. We then port the logger's status logging serialization and deserialization to use `JSON` instead of Boost property trees.
> logger: Port status serialization to rapidjson

- osquery/tables/system/windows/physical_disk_performance.cpp
- specs/windows/physical_disk_performance.table
To test this out, I spun up another instance of osquery and hashed the entire fs, then queryed:
```
osquery> select * from physical_disk_perf;
name = _Total
avg_disk_bytes_per_read = 0
avg_disk_bytes_per_write = 13703
avg_disk_read_queue_length = 0
avg_disk_write_queue_length = 0
avg_disk_sec_per_read = 0
avg_disk_sec_per_write = 0
current_disk_queue_length = 0
percent_disk_read_time = 0
percent_disk_write_time = 1
percent_disk_time = 1
percent_idle_time = 98
name = 0 C:
avg_disk_bytes_per_read = 0
avg_disk_bytes_per_write = 13703
avg_disk_read_queue_length = 0
avg_disk_write_queue_length = 0
avg_disk_sec_per_read = 0
avg_disk_sec_per_write = 0
current_disk_queue_length = 0
percent_disk_read_time = 0
percent_disk_write_time = 6
percent_disk_time = 6
percent_idle_time = 91
name = 1 D: …
```
> tables: adding windows physical disk perfmon table

- tools/provision.ps1
This adds in the Windows 10 SDK to our provisioning, thus allowing more advanced virtual tables to be built using additional Windows libraries. There are a few packages hosted by Chocolatey already, and some [cursory glances at other Microsoft open source projects](https://github.com/PowerShell/PowerShell/blob/2cc091115b2279a2d5efa2e8ff67fea8185a0e17/build.psm1#L1500) shows that this SDK is likely maintained by MS.
> build: installing Windows 10 SDK during provisioning

- Vagrantfile
We had been using the "latest" repository of packages for FreeBSD so we could access newly-introduced packages like `rocksdb-lite`. These are now provided in the stable quarterly. The issue with "latest" is that a package build may fail, then the package is no longer available. This was the case with `aws-sdk-cpp`. 
We also set the hostname to `vagrant` because recent versions of `sudo` on FreeBSD we're sefaulting with an empty hostname.
> vagrant: Use quarterly packages on FreeBSD

- tools/provision.sh
DEPS_DIR is by default `/usr/local/osquery` and if that location exists before `make deps`, the provisioning will fail. Adding this message will at least provide some information why the provisioning has failed. Resolves #3860
> Exiting with a message if DEPS_DIR exists

- tools/provision.sh
Resolves regressions from #3877.
We normally expect the `DEPS_DIR` to exist after repeated runs of `make deps`.
> deps: If DEPS_DIR exists and is a git checkout assume Homebrew

- osquery/remote/http/http_client.cpp
- osquery/remote/http_client.h
- osquery/remote/transports/tls.cpp
- osquery/remote/transports/tls.h
- osquery/remote/utility.h
- osquery/tables/applications/posix/prometheus_metrics.cpp
- osquery/tables/cloud/ec2_instance_metadata.cpp
- osquery/tables/networking/posix/curl.cpp
- osquery/utils/aws_util.cpp
This fixes a bug with the new `http_client` implementation where the "path" component was not including the query string or URI fragment.
It also moves `http_client.h` out of the installed headers for osquery. This is a specialized utility.
It also fixes a retry-force-get problem with the TLS utilities class and addresses minor nits in places where `http_client.h` needed to be code-modded.
> remote: Various refactors for the http_client

- tools/release/sign_release.sh
This `sign_script` is used with a `package_publisher` script to produce the structure and results here: https://github.com/osquery/osquery-packages the use of a signing-host is still a black-box that I'm working to make repeatable and auditable. The host is not 'online' and the contents and keys are encrypted.
Eventually the `package_publisher` script will be kept side-by-side as well as a script on how to create protected keying material and a script to bootstrap a signing host.
> release: Add sign_release script

- include/osquery/core.h
- osquery/main/main.cpp
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/sqlite_util_tests.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
Some more refactors to `SQLiteDBInstance` to lock all intended uses of `::db()`. This deserves some profiling using `osquery_benchmarks` before and after this change.
> [Fix #3859] Lock every access to SQLiteDBInstance::db

- tools/release/build_release.sh
Installing `rpm` though `brew` is no longer needed on macOS. See https://github.com/facebook/osquery/pull/3863
> release: Do not install rpm for macOS release

- packs/unwanted-chrome-extensions.conf
The purpose of this pack would be to track a list of chrome extensions that:
- Have been hijacked
- Serve ads
- Exhibit sketchy behavior
- Can't be trusted for whatever reason
The most straightforward way to track extensions seems to be by identifier. Totally open to feedback on this concept.
> Adding a pack for unwanted chrome extensions

- osquery/tables/system/darwin/processes.cpp
Factoring in microseconds an well while calculating start_time since boot time.
> [Fix #3853]: fixing start-time flip-flop using higher precision arithmetic

- osquery/tables/system/windows/pipes.cpp
- specs/windows/pipes.table
This adds a table to query all named pipes on a system. Sample query follows:
```
osquery> select * from pipes;
+-------+------------------------------------------------------------------------------------------------------------------------+-----------+---------------+-----------------------------------+
| pid   | name                                                                                                                   | instances | max_instances | flags                             |
+-------+------------------------------------------------------------------------------------------------------------------------+-----------+---------------+-----------------------------------+
| 656   | InitShutdown …
```
> tables: Adding a Named Pipes table for Windows

- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
This fixes an issue brought up in Slack. If you use Vagrant and the `/vagrant` folder is mapped into the VM using NFS, the osquery build will place the build folder in `/tmp`. This accommodates issues with `ldd`. If you run `make packages` the CWD for the scripts on Linux and macOS will be outside of the git repo and the `git describe` commands will fail.
This PR also adds support for the documented `OSQUERY_BUILD_VERSION`. This environment variable is used by CMake and allows the builder/packager to override the version.
> packages: Use source repo git describe for packages

- osquery/devtools/shell.cpp
- osquery/events/darwin/event_taps.cpp
- osquery/events/darwin/event_taps.h
Tighten up the event tapping event publisher code. This should hopefully make the code more stable and better equip it to handle edge cases.
> Tightening up the eventing publisher

- osquery/tables/networking/linux/process_open_sockets.cpp
AF_UNIX is actually defined as 1 instead of 0.
$ cat /tmp/af-unix-print.c
#include <stdio.h>
#include <sys/socket.h>
#include <sys/un.h>
int main(void) {
printf("%d\n", AF_UNIX);
return 0;
}
$ gcc -o af-unix-print /tmp/af-unix-print.c
$ ./af-unix-print
1
> Print correct address family id for AF_UNIX sockets

- packs/windows-attacks.conf
- Adding multiple queries. Descriptions should be self-explanatory 
- Bumping the version to 2.2.1 because the oldest osquery Windows version in Chocolatey is 2.2.1
- Adding descriptions for weak crypto and openfont. `Artifact used by this malware` is not relevant to what these queries are checking for.
> Adding queries to windows-attacks, fix version, nits

- packs/windows-attacks.conf
- packs/windows-hardening.conf
As discussed in Slack, windows-attacks.conf should probably be limited to queries that represent actual compromise on a host, rather than security control settings. I've created windows-hardening.conf as a place to put queries related to Windows security settings.
> Creating a windows-hardening pack and moving queries there

- osquery/dispatcher/scheduler.cpp
Check if removed events should be removed before checking if there are any events at all.
> [Fix #3931] Remove removed results correctly

- docs/wiki/installation/cli-flags.md
Flags in a flagfile should not have quotes. Let's remove any temptation.
> docs: Remove quotes from flags documentation

- osquery/core/watcher.cpp
- osquery/extensions/interface.cpp
This also addresses some things in #3604.
Imagine adding
```diff
diff --git a/osquery/examples/example_extension.cpp b/osquery/examples/example_extension.cpp
index da556b4..769409b 100644
--- a/osquery/examples/example_extension.cpp
+++ b/osquery/examples/example_extension.cpp
@@ -86,6 +86,13 @@ class ComplexExampleTable : public TablePlugin {
r["database_test"] = content;
}
+    int x = 0;
+    while (1) {
+      x = x + 1;
+    }
+
+    r["x"] = std::to_string(x);
+
return {r};
}
};
```
Then selecting from that table. The extension would forever be DoSing the system. This diff does four things:
- Adds the reason why autoloaded extensions are reloaded.
- Applies the same initial startup delay for worker spawns to extensions (so extensions can do a lot of work initially).
- Actually kills …
> Stop latent autoloaded extensions and apply an initial delay

- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
This fixes #3764.
All extension clients will now set their receive and send timeouts to 5mins. The socket-alive function will set it to 2 seconds. So a hanging 'old' socket path will only rarely delay the shell by 2 seconds.
> extensions: Add 5min timeouts for read and send client calls

- osquery/core/init.cpp
- osquery/core/posix/process.cpp
- osquery/core/process.h
- osquery/core/tests/process_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/windows/process.cpp
- osquery/main/tests.cpp
It was fun while it lasted but renaming `argv[0]` from `/path/to/osqueryd` to `osqueryd: worker` had odd effects in practice. There are inconsistencies with libraries, such as syslog, and command line reporting in osquery's `processes` table on macOS.
Since this is not standard, and a little hacky, it feels like we should remove it altogether.
> [Fix #3941] Stop renaming worker and extension argv[0]

- osquery/tables/system/windows/users.cpp
- specs/users.table
This addresses #3929 by specifying a `type` for Windows users. The attempt is to differentiate roaming profiles from local users from system account profiles. To check for system account profiles, we match the SID of the user being processed against the set of well known SID values from MS. The only remaining type of user will be domain users, or users with a roaming profile that NetUserEnum doesn't process. Of note, I made some decisions here with the values of `type`. Currently they are `local`, `roaming` for domain users and roaming profiles, and `special` for any of the Windows well-known SIDs. I had thought about using `system` for the well-known sids, but figured that'd be confusing with the `SYSTEM` account. I'm definitely open to using different values though, let me know!
> tables: adding type column to users table to differentiate local users

- osquery/tables/system/windows/programs.cpp
- specs/windows/programs.table
This should address #3043 in entirety. The current method for parsing our program applications is to enumerate all of the `Uninstall` registry keys on the system, and parse out this data. This works out pretty well, however we're currently missing programs as we're looking for registry keys that leverage a GUID for the key path. This removes that restriction, and ensures we make a best effort to parse any registry keys we find under the uninstall path. I did some number checking against the programs generated by `Get-WmiObject -Query "Select * from Win32_Product"`, and it looks like we're getting all of the same stuff, plus more :3
The below series of python commands are checking that osquerys `programs` table captures all of the same installed programs as the WMI table by checking the …
> tables: expanding windows programs table to encompass apps without GUID

- packs/osx-attacks.conf
https://blog.malwarebytes.com/threat-analysis/mac-threat-analysis/2017/11/osx-proton-spreading-through-fake-symantec-blog/
> Adding detection for new "Symantec" Proton variant

- osquery/events/darwin/event_taps.cpp
- osquery/tables/events/darwin/user_interaction_events.cpp
- specs/darwin/key_events.table
- specs/darwin/user_interaction_events.table
Before we were only tapping key_down events. This modifies the concept to also tap mouse_down events and put the data into the same table.
Since the table no longer represents only key_events, it has been renamed user_interaction_events.
> Adding more functionality to macOS' event tapping

- osquery/tables/system/linux/intel_me.cpp
- specs/linux/intel_me_info.table
This is a very basic client for the Intel MEI driver on Linux. It requires that `mei` be loaded as a kernel module. It's possible to use PCI commands but it's far more complicated.
> tables: Add basic Intel ME table returning version

- osquery/remote/http/http_client.cpp
Host header takes part in the signature calculation.
The problem was aws was setting the host and calculating the signature and http_client was resetting the host header un-conditionally.
>  Fix for issue-3953

- osquery/tables/system/posix/augeas.cpp
- osquery/tables/system/posix/tests/augeas_tests.cpp
- tools/provision/formula/augeas.rb
Augeas 1.9 was released 5 days ago and contains the new API we needed to make this table return results faster.
Benchmark results:
```
/usr/local/osquery/bin/python tools/analysis/profile.py --compare old.json new.json
D:3  C:3  U:3  F:0  M:2  posix.augeas: duration: 12.5275700092 cpu_time: 12.09 utilization: 96.468 fds: 4.0 memory: 18239488.0 
D:3  C:2  U:3  F:0  M:2  posix.augeas: duration: 6.01688480377 cpu_time: 5.84 utilization: 97.0666666667 fds: 4.0 memory: 18624512.0
```
I think that 2X improvement is impressive.
I also made the augeas handle a singleton. If we really need a mutex around it's usage I'll add it.
> Augeas table performance imporvements

- osquery/remote/http_client.h
I'm guessing we don't need these defines anymore since we control the OpenSSL build.
> remote: Remove legacy OpenSSL SSL symbol defines

- osquery/core/windows/process.cpp
The breakage reported in `master` on Windows (#3964) was most likely caused by #3943. In that PR there is a deleted escaped-quote.
> extensions: Fix path quotes on Windows

- osquery/tables/system/posix/augeas.cpp
The trailing slash doesn't cause problems now but messes up further development.
If you specify a path query you get the following expression: `/files//etc/whatever|/files/etc/whatever//*` which wasn't intended.
The correct expression is `/files/etc/whatever|/files/etc/whatever//*`
> Fix typo in augeas table

- Makefile
- tools/provision.sh
This was my first time trying to build osquery on my mac and I hit a couple of problems:
1. Cloned osquery inside my personal dropbox directory, which is `~/Dropbox (Personal)/...` and due to the space on the directory name it failed to create a symlink - this one was fixed by adding double quotes in the Makefile in the `ln -s` command
2. During `make deps` it invoked pip, which wanted root to install stuff in the system's PYTHONPATH. I usually refuse to give root to build things, so I changed one of the provisioning scripts to make it call `pip install --user` instead; not sure you want this patch as-is because it may (will, likely) break other builds
Anyway, after these tweaks I was able to build it without root, like this:
```
mkdir -p ~/tmp/osquery_deps
export …
```
> Allow building as non-root on MacOS

- osquery/core/watcher.cpp
In #3944 an initial delay was added to autoloaded extensions. We also added a max-delay time for extension and worker process respawns. This should have been implemented as a `min`. Our tests for `test_osqueryd` started showing 10min+ wait times as this max was applied.
> watcher: Use min for delay max and delay current

- osquery/tables/system/linux/shadow.cpp
- specs/linux/shadow.table
Similar to the `users` table, but this uses `/etc/shadow` instead.
> tables: Add linux shadow table

- osquery/main/windows/main.cpp
This addresses #3950. In our current code flow, we register a service control handler, and on receiving a `SERVICE_CONTROL_STOP` signal we update the service to have a `SERVICE_STOP_PENDING` state while we shut down the osquery daemon. There is an expectation that the extent of our `ServiceMain` routine will be executed, but this does not happen via the service control manager. This ensures that we update the state of our service to be `SERVICE_STOPPED` in our SCM status handler.
> daemon: set service status to SERVICE_STOPPED on exit

- tools/deployment/linux_postinstall.sh
Without this, if you do `apt-get install osquery`, and systemd is *not*
running (for example, if you are trying to install osquery inside a
docker build, in which PID 1 is a bash script), it'll error out like
this:
```
Failed to connect to bus: No such file or directory
```
> only daemon-reload if systemd is running

- osquery/tables/events/windows/windows_events.cpp
This cleans up the trailing newline in the `windows_events` table to ensure sanity of data formatting.
> events: removing newline from windows event log lines

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
- tools/provision.ps1
- tools/provision/chocolatey/osquery_utils.ps1
This adds the WiX toolset binary path to the system `PATH` variable for CLI use. Also this adds a powershell helper for adding paths to the system-wide path
> build: adding helper function to add paths to system path

- osquery/core/system.cpp
I noticed the other day while troubleshooting with someone internally, that on Linux in particular we tend to hand back an ephemeral UUID as low priv users cannot read the system UUID. This is totally fine and makes sense, however it wasn't something I had thought of, and lead to a couple of lost hours due to realizing the uuid provided to me wouldn't exist in our backend. I'd prefer for this to actually be a `LOG(WARNING)`, however that might be a touch excessive? What do others think? Am I the only one who's fallen for this?
> ux: adding verbosity if osquery fails to read system uuid

- docs/wiki/deployment/debugging.md
I saw some recent questions related to events in the shell. I wanted a quick and simple persistent explanation that points folks to the related FIM and process-auditing documentation pages. The first step was saying how events should only be used in the shell for testing and prototyping.
> docs: Add short debugging note for events in osqueryi

- tools/provision/darwin.sh
- tools/release/build_release.sh
- tools/release/deps_release.sh
"Bottles" in Homebrew-terminology is the distributable version of a dependency. We build and store bottles from our dependencies to improve build time and to support more than just Ubuntu16.04 and MacOS10.12 for build systems.
Building these is difficult so we include a script to generate new bottles when a dependency formula is updated. Run `./tools/provision/deps_release.sh dependency1,dependency2` Where the comma-separated list is the set of dependencies changed. Each of these will be rebuilt. At the end the bottle `.tar.gz`s will be in the osquery repo root, ready to be uploaded to your hosting, and the formula will be updated to include the new bottle hashes.
> deps: Include script to auto-build bottles

- docs/wiki/installation/cli-flags.md
- osquery/core/watcher.cpp
We found that imposing watchdog limits on extensions is not a good default assumption.
There are many use cases for extensions and one include running high-computation workloads. Imposing these limits was a new feature added in 2.10. We'll keep the watchdog on the extensions to help restart if they inappropriately shutdown, but we wont by-default impose memory and CPU limits.
> extensions: watchdog: Opt-in to monitor extension performance

- docs/wiki/deployment/configuration.md
- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- packs/osquery-monitoring.conf
- packs/osx-attacks.conf
- tools/tests/test_inline_pack.conf
This adds a new feature to the configuration and extends the scheduled query schema by allowing a new (optional) key in the query details. If you set `blacklist: false` then a this scheduled query will never be blacklisted.
> config: Allow scheduled queries to set blacklist=false

- docs/wiki/installation/cli-flags.md
- osquery/core/init.cpp
- osquery/tables/system/hash.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
Turn the new hash-cache features on by default.
This adds documentation for the new hash-cache related flags. This cache uses inode and modification time reported by the OS and filesystems as "truth" for the content. If you are worried about out of band modifications or would generally like to skip this hash and recalculate hashes for each query use `--disable_hash_cache`.
This also introduces a on-by-default induced delay when using the `hash` table, with or without the cache features. This induced delay protects the OS from osquery trying to hash tons of files as fast as possible (in a single thread). Previously, hashing a download directory was a surefire 1-way ticket to being blacklisted.
> hash: Use the hash-cache by default and document flags

- docs/wiki/deployment/file-integrity-monitoring.md
This request is to add a note to the fim documentation as mentioned in issue #3991. Making sure people understand that if a file is monitored directly and replaced the service will need to be restarted to monitor the new file.
> docs: add note about fim file replacement

- tools/provision/formula/thrift.rb
- tools/provision/lib.sh
The thrift 0.11 dependency is not idempotent on Linux and Darwin.
> deps: Fix symlink check in thrift 0.11

- osquery/remote/http/http_client.cpp
- osquery/remote/http_client.h
This updates the beast checkout in our third-party repo to use version 124. These API changes should be compatible with boost version 1.66.
> deps: Use beast v124 APIs

- CMakeLists.txt
- tools/provision/formula/boost.rb
Our vendored-in version of Boost Beast (v124) is not compatible with Boost version 1.66.
For those platforms using Boost 1.66, the should use the included Beast. For those using Boost <= 1.65, they should use our version in `third-party`. We control this naively by platform.
> [#4009] deps: Update Linux and macOS boost to 1.66

- osquery/core/init.cpp
This addresses one of the potential causes of #3984. If the system has a restrictive max-open-files limit for the process, we attempt to increase to at least 1024.
> Set minimum NOFILE limit to 1024

- osquery/database/plugins/rocksdb.cpp
This is another attempt to mitigate #3984. When RocksDB's max open files is 256, and macOS's max per-process is at 256, a max + the FDs for stdin/etc will overflow.
> rocksdb: Decrease max open database files to 128 from 256

- include/osquery/filesystem.h
- osquery/filesystem/darwin/plist.mm
- osquery/tables/system/darwin/firewall.cpp
- osquery/tables/system/darwin/startup_items.cpp
- osquery/tables/system/darwin/tests/startup_items_tests.cpp
- tools/tests/test_startup_items.plist
This addresses #3994.
We unify the two locations where Alias data is parsed: Startup Items, and the ALF. Then that method is changed to fallback to parsing Alias structure, rather naively, looking for the POSIX path tag.
> tables: Fix Bookmark and Alias path extraction

- docs/wiki/installation/install-osx.md
In testing, the prior cmd line would create a symlink named `/var/osquery` that pointed to `/usr/local/share/osquery` (which was an empty folder) 
- this commit sets the symlink as (i presume) is intended
> 10.12.6 (16G1114)
> typo in mac setup instructions

- CMake/CMakeLibs.cmake
- Makefile
- tools/lib.sh
- tools/tests/test_base.py
- tools/tests/test_http_server.py
The goal is to allow `ctest` to output verbose messages when the environment variable `VERBOSE` is defined. We can define this in Jenkins to help debug problems with long-running tests, like `test_osqueryd`. This test is flaky on macOS and is not easily reproduced locally.
> tests: Allow VERBOSE_TEST=1 to run verbose ctest

- tools/provision.ps1
I removed `thrift` from the set of `requirements.txt` since the osquery-runtime's `thrift` package installs the module to the local site-packages.
This is not the case on Windows.
> windows: deps: Install thrift module on Windows only

- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
There are a lot of 2HR timeouts for macOS in Jenkins. I've noticed that sometimes an `osqueryd` subprocess is still running. I am assuming the test pauses waiting for all children to exit.
> tests: Interrupt subprocesses of osqueryd

- CMakeLists.txt
- docs/wiki/development/building.md
- osquery/CMakeLists.txt
Introduce a `SKIP_DEPS` environment variable. If you set this then osquery's CMake does not perform bit of magic that assume our dependency runtime installed at `/usr/local/osquery`.
This is helpful for OS package managers.
For example:
```
mkdir -p build/standalone
cd build/standalone
SKIP_DEPS=1 CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake ../..
```
If you do not want to build with `clang`.
> deps: Add SKIP_DEPS control to CMake

- Vagrantfile
This adds a Windows box to the vagrant set. There may be better box targets, please let me know!
> vagrant: Add win10 target for Vagrant

- osquery/tables/system/darwin/extended_attributes.cpp
The extended_attributes table can crash osquery if it cannot access a file
due to permissions.
> Fix a crash in the extended_attributes table

- osquery/tables/CMakeLists.txt
This is my error, I forgot to remove `libapt-pkg` from the required linking list.
> tables: Remove apt-pkg linking on Linux

- osquery/tables/system/linux/processes.cpp
Proposed changes to processes.cpp to fix error being returned by readProcLink when reporting on_disk status in Linux.  
When realpath is called with a null value for resolved_path the actual path will not be returned if the executable has been deleted.  The resolved_path variable must have a buffer to receive the path of the deleted executable.
Used this repo to test before and after changes: [https://github.com/exFill/onDisk-Tests](https://github.com/exFill/onDisk-Tests)
**Results at current base master:**
```
Checking /vagrant/build/xenial/osquery/osqueryi
Starting test ... 
osqueryi version 2.11.2-10-g099fb39
================================
Checking with executable PRESENT
attr_path=/proc/3267/exe
link_path=/home/ubuntu/onDisk-Tests/doThis
errno=Success (0) …
```
> Fix on_disk detection for Linux

- CMakeLists.txt
- docs/_docs/faq.md
- docs/wiki/development/building.md
- tools/provision/formula/Abstract/abstract-osquery-formula.rb
The default macOS SDK is set to the version of the build host. We are getting by with this in practice but it is dangerous. If we set the SDK to 10.11 then we will show compiler warnings for newer APIs.
In a follow-up commit we can enforce no weak linking. This will fail the build if any symbols were introduced after 10.11.
> build: Set default macOS SDK to 10.11

- tools/provision/formula/librdkafka.rb
- tools/provision/lib.sh
This updates the version of `librdkafka` to 0.11.3. It also includes a patch to make sure the Darwin/Apple version does not include `clock_gettime`. This API was introduced in 10.12 and would require a weak link (run-time resolved). If this was needed on 10.11 it would throw a SIGILL.
> deps: Build librdkafka 0.11.3 without clock_gettime

- packs/osx-attacks.conf
I updated the osx-attacks.conf to include detection for OSX/MaMi, as discussed in the #macos channel in slack today.
References:
Discussion in Slack:
https://osquery.slack.com/archives/C08VA8R6F/p1515784469000445
Patrick's original post:
https://objective-see.com/blog/blog_0x26.html
My blog post w/ queries:
https://medium.com/uptycs/finding-osx-mami-with-osquery-72960eee0190
> added IOCs to query for OSX_MaMi malware

- osquery/tables/system/cpuid.cpp
This adds a few more flags to the `cpuid` table, specifically it adds the relevant `pcid` flag.
> tables: Add pcid to cpuid table

- CMakeLists.txt
The `OSQUERY_BUILD_SHARED` flag will produce a `libosquery.so` and then link the executables against it. This is currently failing: https://jenkins.osquery.io/job/osqueryMasterBuildSharedLinux/ because of our forced visibility settings. This commit keeps default visibility when the flag is set.
> build: Fix OSQUERY_BUILD_SHARED visibility

- osquery/tables/networking/posix/interfaces.cpp
Fixes #4048.
It's not pretty, but it's more reliable. This will detect when `tcpdump` or otherwise sets an interface into PROMISC mode.
> tables: Parse interface flags from sysfs on Linux

- osquery/tables/system/linux/system_info.cpp
- osquery/tables/system/windows/system_info.cpp
- specs/system_info.table
This attempts to list the CPU microcode version on Windows and Linux, it's not clear how to find this on macOS.
> tables: Add cpu_microcode to system_info

- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/tables/events/linux/process_file_events.cpp
- osquery/tables/system/linux/intel_me.cpp
This ports the TablePlugin and constraints-related structures to use `JSON` and RapidJSON. We are attempting to remove all `ptree` usage from osquery.
> tables: Remove ptree from table plugins

- tools/codegen/genwebsitejson.py
- tools/codegen/genwebsitemetadata.py
- tools/release/new_release.sh
When cutting a release, use the `tools/release/new_release.sh` tool as usual, except point it at the new website instead of the `docs/` subdirectory:
```
$ ./tools/release/new_release.sh 3.0.0 ~/git/osquery-packaging ~/git/osquery-site
[+] Checking out version 3.0.0
HEAD is now at 597b60d5... website: Upload dark version of logo for README (#4065)
[+] Writing new table API
[+] Writing new version metadata
[+] Downloading and hashing packages...
[+] Downloading https://osquery-packages.s3.amazonaws.com/linux/osquery-3.0.0_1.linux_x86_64.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0   1054      0 --:--:-- --:--:-- --:--:--  1056
[+] Downloading …
```
> Tools to generate table and package JSON for the new website

- docs/_config.yml
This PR updates the current https://osquery.io to pull raw data files from the schema branch instead of master.
> Use schema branch of website instead of master for raw data

- osquery/tables/events/darwin/openbsm_events.cpp
Support capturing parent PID for the `process_events` when using openbsm. This is for feature parity with the kernel based version. Parent children relationship is maintained in a map by capturing fork events. This map is queried at the time of the exec call.
> Add parent PID on process_events from openbsm

- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
The osquery shell is just a copy of `osqueryd` within the build directory. We are currently installing this copied binary into packages then onto the target host. This results is large packages.
We can use a symlink instead on POSIX systems.
> packages: Install osqueryi as a symlink

- packs/hardware-monitoring.conf
Remove duplicate mode column in device_nodes query
> Remove duplicate mode column in device_nodes query

- osquery/tables/system/windows/tests/registry_tests.cpp
The system registry check on Windows for the username `LOCAL SERVICE` is a little redundant, and causes issues with international versions of Windows as the user account names will be different than the english spelling. This removes the string comparison, as it should be sufficient that the function `getUsernameFromKey` returned with a status of `OK`, and should fix test runs on international platforms.
> tests: removing registry username test in favor of status check

- osquery/carver/carver.cpp
When attempting to use the file carver with a remote server deployed as a Lambda function, but with a API Gateway in front of it handling TLS termination, after the enrollment has succeeded, the carver shows the following error, when starting and continuing a file carve:
```
osquery> select * from carves where carve=1 and path like '/tmp/testfile';
I0206 00:59:58.977370 19953 tls_enroll.cpp:63] TLSEnrollPlugin requesting a node enroll key from: https://XXXXXXXXXX.us-east-2.amazonaws.com/prod/enroll
I0206 00:59:58.978435 19953 smbios_tables.cpp:132] Could not read SMBIOS memory
I0206 00:59:58.979321 19953 tls.cpp:198] TLS/HTTPS POST request to URI: https://XXXXXXXXXX.us-east-2.amazonaws.com/prod/enroll
{"enroll_secret":"osquery_secret","host_identifier":"vagrant","platform_type":"9","host_d …
```
> Fix for sslv3 handshake failure in the file carver

- tools/deployment/make_windows_package.ps1
This address 4097 by leveraging WiX constructed groups for Windows as opposed to hard coded group names. We no longer should have issues for deployment on versions of Windows other than en-US
> [Fix 4097] Derive Windows groups for internationalization in MSI

- osquery/core/CMakeLists.txt
- osquery/core/darwin/iokit.cpp
- osquery/core/darwin/iokit.hpp
- osquery/events/darwin/iokit.cpp
- osquery/events/darwin/iokit.h
- osquery/tables/system/darwin/block_devices.cpp
- osquery/tables/system/darwin/disk_encryption.mm
- osquery/tables/system/darwin/iokit_registry.cpp
- osquery/tables/system/darwin/kernel_info.cpp
- osquery/tables/system/darwin/pci_devices.cpp
- osquery/tables/system/darwin/sip_config.cpp
- osquery/tables/system/darwin/smbios_tables.cpp
- osquery/tables/system/darwin/system_info.cpp
- osquery/tables/system/darwin/usb_devices.cpp
There are no functional changes here.  The basic iokit routines were intertwined with the iokit event support code.  This commit separates them into separate files, so that tables that don't require event support do not rely on such code.  The only reason I stumbled upon this, is that I have been looking at modularizing various components (events, database, etc.), and found that there are many hidden dependencies that make it difficult.
> darwin: separate iokit routines from iokit event support

- osquery/config/config.cpp
It was possible to call JSON::newFromValue with a null object causing an assert.
> Fix RapidJSON error asserting in configuration

- docs/wiki/development/building.md
The package instructions are located on the custom-packages page, but I think it's likely people will want to know how to do this while building from source
> Updating build docs to include make packages

- osquery/tables/system/windows/bitlocker_info.cpp
Our new bitlocker table created a regressions with the MSVC permissive flags. The easy fix is to cast the L string to a BSTR.
> Fix issue [#4123] MSVC Permissive Error

- osquery/core/conversions.cpp
- osquery/core/conversions.h
- osquery/core/windows/process.cpp
- osquery/extensions/extensions.cpp
This commit adds support for Windows autoloading Python extensions by adding a check on the file extension. If the file extension is `.ext`, as is the standard for posix platforms, then we attempt to launch this extension using Python. Otherwise the assumption is that the extension is a native Windows binary, and we launch as such. I tested this on a Windows VM, and we seem to launch and query from Python extensions correctly:
```
C:\Users\Nick\work\repos\osquery [win-python-auto-ext]
λ  C:\ProgramData\osquery\osqueryd\osqueryd.exe --flagfile=C:\Users\Nick\work\configs\osquery_extensions\osquery.flags --verbose
I0131 14:58:13.185580 15712 init.cpp:380] osquery initialized [version=3.0.0-17-g10c0c60b]
I0131 14:58:13.264608 15712 system.cpp:344] Found stale process for osqueryd (13792) …
```
> extensions: adding support for autoloading python extensions on Windows

- osquery/devtools/printer.cpp
- tools/tests/test_osqueryi.py
There is bug in the current implementation of the json printer. The old ptree representation meant we needed to pop the last character of the string to make the JSON valid but now that we have a proper JSON library, it's removing the final brace. 
This diff fixes that.
Existing output:
```
➜  osquery git:(fix_json) ✗ osqueryi --version
osqueryi version 3.1.0-22-ge421c398
➜  osquery git:(fix_json) ✗ osqueryi 'select 0' --json --disable_extensions
[
{"0":"0"
]
```
Fixed output:
```
➜  osquery git:(fix_json) ✗ ./build/darwin/osquery/osqueryi --version
osqueryi version 3.1.0-25-gd09c3eeb
➜  osquery git:(fix_json) ✗ ./build/darwin/osquery/osqueryi 'select 0' --disable_extensions --json
[
{"0":"0"}
]
```
> Fix JSON output from --json

- tools/deployment/make_windows_package.ps1
Updated the windows package build script to be clearer on help and us…age. Included the proper Get-Help function included in Windows to display help. Changed help from bool to switch where simply typing -h or -help will display the Get-Help information. Included aliases for the script parameters to help those who like to write options certain ways. Also included parameters names that were clearer to identify but the old parameter names are included as aliases. Both will work if identified so no workflow changes should occur. By default will still build chocolatey
> Updated Build Script for Windows with Help Documentation

- osquery/filesystem/linux/proc.cpp
- osquery/filesystem/linux/proc.h
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/tables/applications/posix/docker.cpp
- osquery/tables/networking/linux/process_open_sockets.cpp
- osquery/tables/networking/listening_ports.cpp
- osquery/tables/networking/tests/networking_tables_tests.cpp
- specs/listening_ports.table
- specs/posix/docker_containers.table
- specs/process_open_sockets.table
This PR modifies the process_open_sockets to actually show all sockets active inside all processes (both on the host and inside containers). A new column named "net_namespace" has been added, showing the network namespace that owns each socket.
I would like to make one last change: turn the protocol and family column types from integer to text, and use the actual protocol and family labels rather than numbers (which should make the table mor readable).
> List all sockets (host and containers) in process_open_sockets

- osquery/config/config.cpp
- osquery/core/flags.cpp
This extends the "config" plugin API to include an "option" call.
Calls to `Flag::getValue` within extensions will be forwarded to osquery core for lookup.
For example, imagine you have this within an extension's table:
```cpp
r["custom_ted_flag"] = Flag::getValue("custom_ted_flag");
```
And the config is:
```json
{
"options": {
"custom_ted_flag": "ted says hello"
}
}
```
This flag is now available.
Caveats:
- Flags in extensions must use the[ "custom_" prefix](https://osquery.readthedocs.io/en/stable/deployment/configuration/#options) (this differentiates them from gflags).
- There's no caching within extensions, so every flag request is a thrift call (+serialization).
- The value is only available as a string, please check and convert within your own code.
> extensions: Allow option accesses in extensions

- osquery/logger/logger.cpp
It is not our intention to allow extensions to use `LOG()` and other GLOG-related functions. These should be shuttled back to the core and logged through the appropriate logger plugin.
> logger: Add check to prevent C++ extensions from using glog

- osquery/events/linux/tests/inotify_tests.cpp
- osquery/filesystem/fileops.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/windows/fileops.cpp
This adds an extra check for symlink loops. We now keep track of all inodes of directory symlinks. If we ever encounter the same one, we may have found loop so stop globbing.
> Adding symlink loop detection to globbing

- tools/deployment/osquery.example.conf
This adds the Windows packs default path to the example osquery configuration.
> deployment: adding default path for Windows packs to example conf

- include/osquery/enroll.h
- osquery/carver/carver.cpp
- osquery/config/plugins/tests/tls_config_tests.cpp
- osquery/config/plugins/tls_config.cpp
- osquery/core/conversions.cpp
- osquery/core/json.h
- osquery/distributed/plugins/tls_distributed.cpp
- osquery/distributed/tests/distributed_tests.cpp
- osquery/logger/plugins/tls_logger.cpp
- osquery/remote/enroll/enroll.cpp
- osquery/remote/enroll/plugins/tests/tls_enroll_tests.cpp
- osquery/remote/enroll/plugins/tls_enroll.cpp
- osquery/remote/requests.h
- osquery/remote/serializers/json.cpp
- osquery/remote/serializers/json.h
- osquery/remote/serializers/tests/json_serializers_tests.cpp
- osquery/remote/tests/requests_tests.cpp
- osquery/remote/transports/tests/tls_transports_tests.cpp
- osquery/remote/transports/tls.cpp
- osquery/remote/utility.h
One more step towards getting rid of ptree. The usage of ptree for
serialization causes some problems by doing some invalid conversions
(e.g. deserializing {} as an empty string). This will hopefully fix some
of those problems by using rapidjson which should be more sane.
> Replace ptree with JSON on serialization code

- osquery/tables/applications/posix/docker.cpp
- specs/posix/docker_containers.table
Adding the following fields to the docker_container table to capture more context about a container:
Column("path", TEXT, "Container path"),
Column("config_entrypoint", TEXT, "Container entrypoint(s)"),
Column("started_at", TEXT, "Container start time as string"),
Column("finished_at", TEXT, "Container finish time as string"),
Column("privileged", INTEGER, "Is the container privileged"),
Column("security_options", TEXT, "List of container security options"),
Column("env_variables", TEXT, "Container environmental variables"),
Also ensured the "pid" field is populated for OS X.
> adding fields to docker_containers table

- tools/provision.ps1
Removes a line in the osquery/CMakeLists.txt that was setting a profile which was breaking the build on Windows.
I don't know why this wasn't caught in CI, but removing it also hasn't broken the build on macOS.
> Pin CMake version for build stability

- osquery/tables/system/windows/bitlocker_info.cpp
I realized it could be rather confusing having a variable sharing the name of one of the properties, so I changed it to something more generic and replaced all instances of the variable with the new name.
> Update confusing variable name and allow multiple row return in bitlocker_info.cpp

- CMakeLists.txt
- Makefile
- Vagrantfile
- osquery/CMakeLists.txt
- tools/provision/freebsd.sh
FreeBSD has thrift 11 and boost 1.66 so we can remove special handling (local include of beast).
> freebsd: Update CMake for thrift 11 and boost 1.66

- docs/wiki/deployment/configuration.md
Discovery queries in osquery short circuit and I didn't see this documented in our wiki. This just adds a small block, better defining how we evaluate discovery queries.
> Add block on short-circuiting discovery queries

- packs/windows-attacks.conf
Not sure if escape is supposed to work but it doesn't here
https://ci.appveyor.com/project/juju4/ansible-win-osquery/build/0.1.x.35/job/i8g2axx80emxwd28#L881
```
changed: [localhost] => {
"changed": true,
"cmd": "c:\\ProgramData\\osquery\\osqueryi.exe --config_path c:\\ProgramData\\osquery\\osquery.conf --config_check --verbose",
"delta": "0:00:01.281920",
"end": "2018-02-25 03:00:15.157841",
"rc": 0,
"start": "2018-02-25 03:00:13.875920",
"stderr": "I0225 15:00:14.079041  1840 init.cpp:380] osquery initialized [version=2.11.2]\r\nI0225 15:00:14.079041  1840 extensions.cpp:300] Could not autoload extensions: Failed reading: \\ProgramData\\osquery\\extensions.load\r\nI0225 15:00:14.079041  1840 init.cpp:609] Cannot start extension manager: Extensions disabled\r\nW0225 15:00:14.079041  1840 …
```
> Error parsing the "windows-attacks" pack JSON: <unspecified file>(47): invalid escape sequence

- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/authorizations.mm
- osquery/tables/system/darwin/disk_encryption.mm
- osquery/tables/system/darwin/packages.mm
- osquery/tables/system/darwin/shared_folders.mm
- osquery/tables/system/darwin/user_groups.mm
I've been investigating a crash in osqueryd and it seems to involve the use autoreleasepools in places they aren't needed. As a test I removed them from all the tables expecting to have a bunch of leaks but I didn't.
Thus I'm wondering if we can remove, reducing complexity and also hopefully fixing this crash in one fell swoop.
> Remove all table AutoReleasePool blocks

- osquery/distributed/distributed.cpp
This was a bug introduced in the port to RapidJSON. I noticed last night while debugging that we are doubling up on the data sent back and losing all the SQL status. This simply fixes that.
> Return SQL statuses in distributed response fix

- osquery/tables/system/darwin/disk_encryption.mm
Found this while looking at leaks.  Since issue #3121 is still open, can associate with that issue.
```
tools/analysis/profile.py --leaks --query "SELECT * FROM disk_encryption"
Analyzing leaks in query: SELECT * FROM disk_encryption
definitely:  28 leaks for 2080 total leaked bytes. 
```
> fix minor leak in darwin disk_encryption generate

- osquery/logger/plugins/aws_log_forwarder.h
* Fixing an issue that cause the logged errors to not have the proper record index by incrementing said index.
```
aws_kinesis logger: Failed to write the following records:
Record #0: {"name":"pack_foo","hostIdentifier":"foobar"...}
Record #0: {"name":"pack_bar","hostIdentifier":"foobar"...}
```
> [bug] aws_log_forwarder: incrementing index for batches of records that could not be sent

- osquery/extensions/CMakeLists.txt
- osquery/extensions/extensions.cpp
- osquery/extensions/impl_fbthrift.cpp
- osquery/extensions/impl_thrift.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
There's no real change here (unless I introduced a regression). This breaks out the FBThrift and Thrift implementations into two files. This way we can sync the FBThrift without references to the older Thrift headers/structures.
> thrift: Breakout thrift and fbthrift into implementations

- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/linux/processes.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
- specs/processes.table
Windows and FreeBSD fail to build for me, so I haven't been able to implement support for those platforms. My research indicates that it's possible, though.
Tested with new unit test on both platforms and profiling script on macOS:
```
% tools/analysis/profile.py --query 'select * from processes;' --leaks
Analyzing leaks in query: select * from processes;
definitely: 0 leaks for 0 total leaked bytes.
```
> mac/linux: add disk I/O columns to processes table

- docs/wiki/deployment/logging.md
- docs/wiki/installation/cli-flags.md
- osquery/logger/plugins/kafka_producer.cpp
librdkafka in osquery is already built with gzip support.
This change introduces logger kafka flag to specify compression codec.
Because librdkafka is not compiled with snappy and lz4 support
logger_kafka_compression flag only supports two values: "none" (default)
and "gzip".
> kafka: Support for kafka compression.codec

- tools/deployment/make_windows_package.ps1
Versioning on building a windows MSI was failing due to an extra carriage return making it's way into the `.wxs`.
> deploy: fixing version bug in windows msi build

- osquery/filesystem/linux/proc.cpp
On linux we're not guaranteed to have all namespaces available,
therefore listing namespaces shouldn't quit when one is not available or
fails to read.
This causes problems for instance on systems without cgroups.
> Don't bail out when querying one namespace fails

- osquery/tables/networking/linux/process_open_sockets.cpp
This fixes the case for when the user filters by pid = -1, i.e. sockets
without a pid associated.
> Properly filter process_open_sockets when pid=-1
