specs/linux/shadow.table

I was wondering for a 30 min if this is a bug or not, until I remembered, I was running `osqueryi` as my user not as root.

docs: shadow only works for root / sudo

---

osquery/tables/system/linux/processes.cpp

Addressing a late comment on #4204, fixing the data type while I'm at it.

Use safeStrtoll instead of strtol

---

osquery/tables/system/windows/video_info.cpp
specs/windows/video_info.table

I omitted the wmi property for AdapterRam, which should in theory return the video card memory (in bytes), but I am having some major type conversion and/or overflow issues when I approach it for devices that have over 4GB of memory on their card. Maybe someone else can add it in?

Add video_info table to collect video card information

---

packs/osx-attacks.conf

This is based off of the blog post here: https://clo.ng/blog/osquery_reverse_shell/
TL;DR - Reverse shells typically have:
- A process of Python, /bin/sh, or /bin/bash
- No associated open files (including TTYs)
- An open socket
It would be awesome if anyone with a fairly decent sized fleet of macs could test this out in their environment, but in my testing it was extremely high signal. 
Also, feel free to suggest improvements to the SQL if there are optimizations that can be made. I got the query to a working state, but I'm positive it's not in an optimal state.

Adding behavioral reverse shell detection to osx-attacks

---

osquery/distributed/distributed.cpp

The acceleration code was not updated to reflect the proper typing of RapidJSON deserialization, thus we were always failing the IsString() check and never running accelerated mode.
This is just a simple fix to use the API correctly. I'm marking it as `API Change` because in theory would have worked before if you made accelerate a string (even though it was supposed to be an int) and now it must be an int.

Fix acceleration code to use RapidJSON properly

---

osquery/tables/system/posix/tests/yum_sources_tests.cpp
osquery/tables/system/posix/yum_sources.cpp
specs/posix/yum_sources.table

Similar to the apt_sources table.
This assumes the configuration is at `/etc/yum.conf`. It will follow the `reposdir` option if it's set, but only does that once.
@fmanco

tables: Add yum_sources table

---

osquery/tables/system/uptime.cpp

It was fixed
```
osquery> select * from uptime;
+------+-------+---------+---------+---------------+
| days | hours | minutes | seconds | total_seconds |
+------+-------+---------+---------+---------------+
| 14   | 6     | 48      | 0       | 1234080       |
+------+-------+---------+---------+---------------+
```
```
PS C:\Users\karmazin>  $type = Add-Type -MemberDefinition $signature -Name SystemTime -Namespace GetTickCount64 -PassThru
PS C:\Users\karmazin>
PS C:\Users\karmazin> [System.TimeSpan]::FromMilliseconds($type::GetTickCount64())
Days              : 63
Hours             : 23
Minutes           : 53
Seconds           : 34
Milliseconds      : 843
Ticks             : 55292148430000
TotalDays         : 63,9955421643518
TotalHours        : 1535,89301194444
TotalMinutes      : …
```

fix incorrect uptime on windows

---

tools/codegen/genwebsitejson.py

Fixes https://github.com/osquery/osquery-site/issues/29
The root directory was only accounting for darwin and linux.

update specs at the root directory to include windows

---

osquery/tables/system/linux/os_version.cpp

Fixes #4071
In the presence of both `/etc/os-release` and `/etc/redhat-release`, os_version stops early after reading the first file, whereas it should continue because other files include more-specific data such as minor versions

tables: Use more specific release files on os_version

---

osquery/tables/applications/posix/docker.cpp

We shouldn't need the BOOST_FOREACH macro when we have C++11 range based loops. This removes that last instance of it.

Remove BOOST_FOREACH

---

packs/windows-hardening.conf

Replaced all occurrences of "Wether" with "Whether"

Fix typos in packs/windows-hardening.conf

---

include/osquery/database.h
osquery/database/database.cpp

This skips over domain prefixes of `.query`, as these values int he database do not require migration. Further this abstracts the database upgrade logic (#thanks @fmanco!) so that subsequent upgrades should be easier to pull off. Lastly this brings in a base case check for empty json objects being returned as empty RJ objects, as opposed to empty arrays.

database: updating migration logic from ptree to rapidjson

---

osquery/tables/system/linux/groups.cpp

Improve performance of the linux groups table by taking into
consideration the gid constraints.
This implementation returns results for non-existent groups passed as a
constraint for consistency with the darwin implementation. In fact the
code comes pretty much from the darwin table.

Filter by gid on Linux groups table

---

osquery/tables/system/darwin/certificates.mm
osquery/tables/system/darwin/keychain.h
osquery/tables/system/darwin/keychain_utils.cpp
osquery/tables/system/windows/certificates.cpp
specs/macwin/certificates.table

Adding a new column called "serial" to the certificates table, on Darwin and Windows. This is a hex-encoded string, e.g. `2E9EF8E848F2AAFC37C4A1E5A1B67C6`. 
osquery> select serial from certificates limit 1;
+----------+
| serial   |
+----------+
| 2ACEAE9A |
+----------+
I've tested the change on both Windows 10 and OSX 10.13.3.

Added certificate serial number column

---

tools/tests/test_windows_service.py

In my haste to fix the exit deadlock bug on Windows, I didn't remove the verbosity messages we had used for debugging the integration tests. These wont show up unless the test fails, and this PR cleans up said verbosity statements, as well as adds a clause to our teardown logic to ensure that all services are removed in the event one of the tests fails to complete.

tests: cleaning up windows service tests

---

osquery/tables/system/posix/yum_sources.cpp

Correct the file extension used to look for files under `/etc/yum.repos.d`.

bug: fix fail to read yum sources (#4284)

---

osquery/core/conversions.cpp
osquery/core/conversions.h
osquery/core/tests/conversions_tests.cpp

There was an error where having a query with a path like C:\users, osquery thought that was a unicode character `sers` after `\u`.
This adds a check for double backslashes and skips them if found.
What would happen before with the new testcase:
```
➜  osquery git:(master) ✗ ./build/darwin/osquery/osquery_tests --gtest_filter="ConversionsTests.test_unicode_unescape"
Note: Google Test filter = ConversionsTests.test_unicode_unescape
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ConversionsTests
[ RUN      ] ConversionsTests.test_unicode_unescape
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0421 11:44:52.044927 2431210368 conversions.h:212] Unescaping a string with length: 28 failed at: 3 …
```

Fix a unicode parsing error

---

include/osquery/extensions.h
osquery/extensions/extensions.cpp
osquery/extensions/impl_fbthrift.cpp
osquery/extensions/impl_thrift.cpp
osquery/extensions/interface.cpp
osquery/extensions/interface.h
osquery/extensions/tests/extensions_tests.cpp

The goal of this PR is to separate the server (API) and client implementations of Apache and FbThrift.
The current code should work with both (set the flag `FBTHRIFT=1`) to use the FbThrift implementation. This is not recommended for open source builds. Actually, it is only recommended if you are know you will need FbThrift.
The current code uses some pre-processor tricks that we would like to remove. This completes the isolation of the two implementations. There is a little more code this way, but there are several forcing functions to make sure the implementation code changes if the API does.
Note: this is not an API change, just a refactor.

fbthrift: Second set of Apache and FbThrift refactors

---

include/osquery/registry.h

Forgotten variable name. This was not locking anything.

Fix registry locking for plugin method

---

osquery/core/init.cpp

When using fbthrift we need to initialize folly which will eventually
initialize glog. Ensure we don't initialize twice in that situation.

Fix init when using fbthrift (and folly)

---

packs/osx-attacks.conf

In previous commit for this query I accidentally copy and pasted a previous iteration of the query that didn't include any socket-based filtering. I have also realized the `name='Python'` clause was redundant and has the potential to cause false positives. This version should be MUCH more high signal. My apologies for adding the wrong one initially!

Updating reverse shell query in osx-attacks

---

osquery/tables/events/windows/windows_events.cpp

Fix parsing of EventData block for Windows Events. Previously, parsed EventData blocks from the Windows EventLog would contain two additional "non-real" fields:
Old event example (4688 - process start), **note the properties`<xmlattr>` and `Name`**:
```
{
"EventData": {
"<xmlattr>": "",
"CommandLine": "osqueryi  --disable_events=false",
"MandatoryLabel": "S-1-16-12288",
"Name": "SubjectUserSid,SubjectUserName,SubjectDomainName,SubjectLogonId,NewProcessId,NewProcessName,TokenElevationType,ProcessId,CommandLine,TargetUserSid,TargetUserName,TargetDomainName,TargetLogonId,ParentProcessName,MandatoryLabel",
"NewProcessId": "0x1d88",
"NewProcessName": "C:\\ProgramData\\osquery\\osqueryi.exe",
"ParentProcessName": "C:\\Windows\\System32\\cmd.exe",
"ProcessId": "0x1e20",
"SubjectDomainName": …
```

Fix parsing of EventData block for Windows Events.

---

include/osquery/config.h
include/osquery/posix/system.h
include/osquery/registry.h
osquery/config/config.cpp
osquery/core/system.cpp
osquery/registry/registry.cpp

To be honest, I am not sure why this results in ODR violations but in practice, some methods of compiling will include multiple instances of the accessor methods (bad!). This does not occur with osquery's default compiler/linker configuration so this is hard to catch.

Move singleton accessors into implementations

---

include/osquery/tables.h

This is mostly a test, I am not sure if we still need this for windows and boost 1.66.

Remove clang pragmas from tables.h

---

osquery/config/parsers/options.cpp

Make options parser ignore invalid options

---

tools/get_platform.py

Detect `ID=nixos` from `/etc/os-release` in `_platform` method.
Parse `VERSION_ID` from that file in `_distro` method.
```
> python tools/get_platform.py --platform
nixos
> python tools/get_platform.py --distro
18.09.git.5a4a3a6
> python tools/get_platform.py --family
nixos
```

tools/get_platform.py: add support for nixos

---

include/osquery/dispatcher.h
include/osquery/flags.h
osquery/carver/carver.h
osquery/config/config.cpp
osquery/core/flags.cpp
osquery/core/watcher.h
osquery/dispatcher/dispatcher.cpp
osquery/dispatcher/distributed.h

This is a quick code review of the flags and dispatcher parts. I was casually browsing code changes via a proposed code-sync and saw some things I was unhappy with. Moving the singleton accessors into implementation files prevents odd ODR violations. The runner thread abstractions should `override` their start otherwise they will be spinning needless wheels (good practice).

Code audit for flags and dispatcher parts

---

osquery/tables/system/darwin/mdfind.mm
osquery/tables/system/darwin/tests/mdfind_tests.cpp
specs/darwin/mdfind.table

This adds a new mdfind table to darwin capable of searching the filesystem. A properly formatted mdfind query must be passed to the table for it to work ([here is the documentation](https://developer.apple.com/library/content/documentation/Carbon/Conceptual/SpotlightQuery/Concepts/QueryFormat.html))
Leaks tests:
```
➜  osquery git:(mdfind) ✗ ./tools/analysis/profile.py --leaks --query "select * from mdfind where query in ('kMDItemDisplayName == \"rook.stl\"', 'kMDItemDisplayName == \"Siroca.mp4\"');"
Analyzing leaks in query: select * from mdfind where query in ('kMDItemDisplayName == "rook.stl"', 'kMDItemDisplayName == "Siroca.mp4"');
definitely: 0 leaks for 0 total leaked bytes.
➜  osquery git:(mdfind) ✗ sudo ./tools/analysis/profile.py --leaks --query "select * from mdfind where query …
```

Add an mdfind table to macOS

---

tools/deployment/com.facebook.osqueryd.plist
tools/deployment/osqueryd.initd
tools/deployment/osqueryd.service

This should go into the flags file or configuration to avoid spreading
configs across multiple places.
The documentation also says by default osqueryd will log INFO messages
but a user installing our packages won't see that and reason might not
be obvious.

Remove --logger_min_stderr from service files

---

osquery/tables/networking/posix/interfaces.cpp

orred the value from sysfs and ifaddrs to both fix issue 4048 (flags not updated for promiscuous mode with `tcdump` for example) and maintain volatile flags mentioned issue 4272.

recover interface flags

---

osquery/tables/networking/windows/interfaces.cpp

Much of the error messaging in the `interface_details` table on Windows was quite confusing, and didn't provide any valuable information. This updates the table `INFO` messages to offer interface numbers.

tables: updating confusing info messages for interface details table

---

osquery/tables/system/darwin/usb_devices.cpp

Mirrors linux's class/subclass output now.

Fix USB class/subclass IDs on darwin

---

osquery/tables/system/darwin/usb_devices.cpp

A PR got merged before tests could complete, this will format the code and make sure tests pass before we land more stuff on top of it.

Format code in usb_devices

---

osquery/tables/system/windows/processes.cpp
specs/processes.table

Processes uid is now retrieved from TokenUser instead of TokenOwner. This allows for proper mapping of user names to processes. Ref #4360 
Added is_elevated_token to column to processes table which indicates if the process is using an elevated token.

Correct process uid for user name mapping and added is_elevated_token column

---

include/osquery/config.h
osquery/config/config.cpp

Add const qualifier to some Config methods
- `void scheduledQueries( std::function<void(std::string name, const ScheduledQuery& query)> predicate, bool blacklisted = false) const;`
- `void files(std::function<void(const std::string& category, const std::vector<std::string>& files)> predicate) const;`
- `void getPerformanceStats(const std::string& name, std::function<void(const QueryPerformance& query)> predicate) const;`
- `Status genHash(std::string& hash) const;`
Because they actually modify nothing during the call. So there is no excuse for them to be non-const.

Add const qualifier to some Config methods

---

include/osquery/system.h
osquery/core/system.cpp
osquery/core/tests/system_test.cpp

Some machines don't report proper UUIDs and placeholders are used
instead, namely the following:
00000000-0000-0000-0000-000000000000
03000200-0400-0500-0006-000700080009
03020100-0504-0706-0809-0A0B0C0D0E0F
10000000-0000-8000-0040-000000000000
Make sure we don't use these UUIDs as they're useless as an unique
identifier and use ephemeral UUIDs instead.

Handle placeholder hardware UUIDs

---

osquery/core/init.cpp
osquery/core/posix/process_ops.cpp
osquery/core/process.h
osquery/core/windows/process_ops.cpp
osquery/main/windows/main.cpp
tools/tests/test_windows_service.py

The logic that I had implemented around waiting for thread execution to complete before notifying the SCM of our service stopped state was incorrect. This updates the service thread wait logic to obtain a handle to the main execution thread which is used to wait before sending a `SERVICE_STOPPED` status to the SCM. This should prevent SCM returning error codes of 109, as well as prevent system crashes when the service shuts down. This also turns on tests to ensure that we don't see any exit error code aside from 0 when the service shuts down. Below is some contextual history that we found a way around.
Big shoutout to @ExceptionalHandler for helping me work through what this wait logic should look like, and reporting the issue to us in the first place!
~I messed around with the logic a …

bug: do not wait for main service thread before reporting stop to SCM

---

include/osquery/sql.h
include/osquery/tables.h
osquery/core/tables.cpp
osquery/core/watcher.cpp
osquery/dispatcher/scheduler.cpp
osquery/sql/sql.cpp
osquery/sql/sqlite_util.cpp
osquery/sql/virtual_table.cpp
osquery/tables/system/darwin/processes.cpp

The `processes` table on macOS makes a bunch of system calls and fills in a bunch of columns, both of which are relatively expensive operations. This PR enables the table to be smart about which system calls it makes and which columns it populates, based on what columns are actually used by the current query.
Note that the first few commits are from #4254 and #4262, which have not yet been merged. The new stuff for this PR starts with 4905d312c7628b9193e94c89037a92448accb8b2 Add used columns info and utilities to QueryContext

Plumb used columns into QueryContext; use that to make processes table more efficient on macOS

---

CMakeLists.txt
Makefile
docs/wiki/development/building.md
osquery/CMakeLists.txt
osquery/filesystem/linux/proc.cpp
osquery/main/fuzz.cpp
osquery/remote/uri.cpp
tools/provision/formula/Abstract/abstract-osquery-formula.rb
tools/provision/formula/libcpp.rb
tools/provision/formula/llvm.rb

This adds a new target (optional) `osqueryf`. This is built when using `make libfuzz`.
To use `libfuzzer` we need LLVM 6.0 so this also includes an update to the dependencies for `llvm` and `libcpp`. The `libcpp` dependency is what contains libFuzzer in this incarnation. This allows us to build libFuzzer with a clang that does not contain it, since libFuzzer needs a c++ runtime.
This is what found 6+ RapidJSON problems with config and config parsers. I am sure there are other fund parts you can fuzz by swapping out the content of `fuzz.cpp`.

llvm 6.0 and libFuzzer implementation

---

specs/darwin/alf.table

This PR adds documentation for "Block all incoming" connections mode in macOS.
When macOS application layer firewall is in "Block all incoming connections" mode, the `global_state` column of the `alf` table is `2`:
```
osquery> select global_state from alf;
+--------------+
| global_state |
+--------------+
| 2            |
+--------------+
```
I'm open to suggestions on wording, but want to fix this documentation because I ran into a problem where I thought ALF was not enabled on a bunch of devices when it actually was enabled in the strictest mode.  😄

Add documentation for Darwin ALF "Block all incoming connections" mode

---

osquery/tables/networking/posix/interfaces.cpp
specs/interface_details.table

- Add column for speed in Megabits per sec for interface details on Linux.

virtual_tables: add link_speed column to interface_details for linux

---

osquery/utils/aws_util.cpp

C5/M5 instances are missing /sys/hypervisor/uuid file. We used to use this
file to do a quick EC2/non-EC2 check. If UUID file is missing or UUID does not
start with string 'ec2', it was treated as non-EC2 instance.
Since C5/M5 instances are missing this file (?) we have to perform other
checks before deciding whether the instance is EC2 or not.
See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html
This fixes: https://github.com/facebook/osquery/issues/4378

aws: Deal with missing uuid file on C5/M5 instances.

---

osquery/remote/http/http_client.cpp
osquery/remote/transports/tls.cpp

Fixes #4398.
I noticed the TLS debugging should be moved to 'after all other OpenSSL options are set' because there's potential for the peer-verification setting to be flipped back on. I cannot reproduce this error without active termination of the socket.

http_client: Always close socket on exception

---

osquery/config/packs.cpp

This will handle string-type boolean values for `blacklist` in query definitions.

packs: Fix blacklist option bool assumption

---

tools/deployment/make_linux_package.sh

According to https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html
> For the “build ID” method, GDB looks in the .build-id subdirectory of each one of the global debug directories for a file named nn/nnnnnnnn.debug, where nn are the first 2 hex characters of the build
ID bit string, and nnnnnnnn are the rest of the bit string. (Real build ID strings are 32 or more hex characters, not 10.)
Test plan:
```
$ eu-readelf -n /usr/bin/osqueryd
...
Note section [ 5] '.note.gnu.build-id' of 24 bytes at offset 0x30f14c:
Owner          Data size  Type
GNU                    8  GNU_BUILD_ID
Build ID: cd23155a411c711a
$ strace -eaccess,readlink gdb /usr/bin/osqueryd
...
access("/usr/lib/debug/.build-id/cd/23155a411c711a.debug", F_OK) = 0 …
```

Fix debuginfo build-id subdirectory

---

osquery/tables/system/darwin/disk_encryption.mm

Fixed over release of object that was autoreleased and then picked up by ARC as retained. 
Use method implementaion instead of NSInvocation as much faster way to call as well as much safer  and understandable by compoiler.

Fixed over release of object on osx

---

tools/deployment/make_linux_package.sh

osqueryd and osqueryi build-ids are the same  (because this is the same binary) so the first ln wasn't doing much.

Remove useless links on debug package creation

---

osquery/tables/applications/posix/docker.cpp
specs/posix/docker_containers.table

Adding the readonly_rootfs field to the docker_container table. 
`Column("readonly_rootfs", INTEGER, "Is the root filesystem mounted as read only"),`

Adding readonly_rootfs field to docker_containers table.

---

osquery/tables/system/darwin/smbios_tables.cpp
osquery/tables/system/linux/smbios_tables.cpp
osquery/tables/system/posix/smbios_utils.cpp
osquery/tables/system/smbios_utils.h
specs/blacklist
specs/posix/memory_array_mapped_addresses.table
specs/posix/memory_arrays.table
specs/posix/memory_device_mapped_addresses.table
specs/posix/memory_error_info.table

Currently `memory_devices` exists as a virtual table.  This PR implements the remaining memory related tables of `SMBIOS`.
Tables are:
- `memory_arrays`
- `memory_array_mapped_addresses`
- `memory_error_info`
- `memory_device_mapped_addresses`
Note:  In `memory_device_mapped_addresses`, the `handle` column isn't really useful, meaning that it can't be used to join with any of the other tables.  It was left there for consistency with the other tables.   I will remove it if that's not what we want.

tables: memory related SMBIOS tables

---

osquery/dispatcher/scheduler.h

- Member [splay_] was removed because there is no use case for it.
- All members was hidden under private specifier.

Remove unused member from SchedulerRunner class

---

tools/provision/formula/glibc-legacy.rb

This allows `glibc-legacy` to build on Ubuntu-18.04', specifically with `gcc` version 7.

deps: Allow GCC 7 to build glibc-legacy 2.13

---

osquery/utils/tests/aws_util_tests.cpp
tools/provision/formula/aws-sdk-cpp.rb

Fixes #4158.
The `aws-sdk-cpp` version (1.2.x) does not build with `clang-6.0`.

deps: Update aws-sdk-cpp to version 1.4.55

---

tools/provision/formula/libdpkg.rb

The older `libdpkg` source tarball (1.18.23) was removed. This updates the dependency and includes a mirror to prevent this from happening again (at least reduce the chances).

deps: Update libdpkg to version 1.19.0.5

---

tools/provision/formula/sleuthkit.rb

This package version was old, and causing compiler errors with never versions of LLVM (6+).

deps: Update sleuthkit to version 4.6.1

---

tools/provision/formula/rapidjson.rb

I found that `rapidjson` is forcing `-march=native`. This is very bad for our portability guarantees.
This diff patches out the `march`, thus it will assume ours. This diff also ungates the compiler warning removals on MacOS, allowing it to build on newer LLVM installs, such as the install in Xcode 9.0.2.

deps: Patch RapidJSON to remove march native

---

osquery/dispatcher/scheduler.cpp
osquery/dispatcher/scheduler.h
osquery/dispatcher/tests/scheduler_tests.cpp

based on measuring time of loop step and reduce sleep time on it.
Issue: #4301

Simple solution to reduce drift time in loop of scheduled queries

---

docs/wiki/deployment/configuration.md

Updates the name of the view in the `views` example to be `kernel_hashes` instead of `kernel_hashses`.

Fix typo in views example

---

include/osquery/database.h
osquery/database/database.cpp
osquery/database/tests/database_tests.cpp

Added API and tests for int types in the database abstraction.
For now, it's just the  wrapper over the string type. In the following commits, will utilize specific database capabilites for additional performance.

Basic db int type support

---

README.md

As started in https://github.com/facebook/osquery/pull/4451, this fixes
links to schema on the new site. As Packs no longer are a tab on the
osquery.io site, pointing to the directory structure within the repo
for now to avoid the 404.

Fix older/broken links

---

osquery/tables/system/darwin/smbios_tables.cpp
osquery/tables/system/linux/smbios_tables.cpp
osquery/tables/system/linux/system_info.cpp
osquery/tables/system/posix/smbios_utils.cpp
osquery/tables/system/smbios_utils.h

Update `SMBIOSParser::tables` function parameter to include `textAddrs` so that the caller does not need to do pointer arithmetic to get to `DMI` text string location.

tables: text address arg for SMBIOSParser::tables predicate

---

osquery/tables/system/windows/os_version.cpp
tools/build.ps1

With newer SDKs, `PRODUCT_MOBILE_CORE` is being removed. As such having the symbol in our virtual table is causing builds to fail, and this value is likely not being used by anyone :) This PR additionally pins our toolkit version to the v140 compiler, which is visual studio 2015. Once @momopranto lands the VS 2017 conversion we'll be able to turn on `/permissive-`.

build: remove PRODUCT_MOBILE_CORE reference and pin v140 compiler

---

include/osquery/config.h
osquery/config/config.cpp

to avoid UB in non-const access from different threads. It is not a big deal for the interface and other code, because there is no use cases to shared this objects somewhere.

Rid off the shared_ptr using from config schedule

---

osquery/extensions/impl_fbthrift.cpp

`base` should be released after `e` and `em` members of `ImplExtensionClient`.

Fixed up resource releasing order UB in `ImplExtensionClient`

---

docs/wiki/deployment/process-auditing.md

The process auditing code in kernel/src/publishers/darwin/process_events.c uses the MAC framework to be notified about execve. The MAC framework is not a supported KPI, so fix the documentation to reflect that.

MAC framework is not a supported KPI

---

osquery/tables/networking/darwin/wifi_survey.mm

In Mojave, BSSIDs are not returned if location services are disabled.
This checks that there are returned before pulling a string out. It all removes
some extra string casts.

Fix Mojave BSSIDs

---

osquery/database/plugins/rocksdb.cpp
osquery/database/plugins/rocksdb.h

unnecessary private variables moved to functions.
Find method replaced by std::find

rocksDB simplify

---

include/osquery/database.h
osquery/config/config.cpp
osquery/core/conversions.h
osquery/database/database.cpp
osquery/database/plugins/ephemeral.cpp
osquery/database/plugins/ephemeral.h
osquery/database/plugins/rocksdb.cpp
osquery/database/plugins/rocksdb.h
osquery/database/plugins/sqlite.cpp
osquery/database/plugins/sqlite.h

Ephemeral supports int without serialization.
Dump get and put pushed from database.cpp to the database plugin.
Basic support for rocksDB and sqlite

Ephemeral native support for int

---

specs/posix/process_events.table

This is an openBSM specific event so it should be darwin only.

Move process_event's status to extended schema

---

tools/codegen/gentable.py

Considering all files might lead to confusion when temporary files are generate on the template directory, like when the files are open with vim for instance.

Make gentable.py ignore non *.in template files

---

osquery/tables/events/linux/process_events.cpp
specs/posix/process_events.table

parent is not provided on linux, but because it is a BIGINT it needs to exist or the casts are going to fail polluting the logs. Set it to -1.

Set parent to -1 on process_events

---

osquery/filesystem/tests/fileops_tests.cpp

Without ASSERT_* tests try to work with invalid file pointer - it doesn't make any sense and sometimes led to bizarre behaviour

Do not continue FileOpsTests.* after file opening failure

---

osquery/tables/events/linux/process_events.cpp

This got missed in the rewrite causing extra quotes around cmdline pieces along with hex encodings that are not decoded.

Add decode back to cmdline pieces

---

osquery/core/conversions.cpp
osquery/core/conversions.h
osquery/core/tests/conversions_tests.cpp
osquery/tables/system/linux/md_tables.cpp
osquery/tables/system/linux/os_version.cpp
osquery/tables/system/linux/processes.cpp

split contained bug, it was joining on every delimiter, which would result to unusual outcome. However, test could not detect this problem as delim.size() was 1.

bug split(string,string,size_t)

---

osquery/filesystem/tests/fileops_tests.cpp

There was used unsafe way to generate unique name for temporary file. It led for collisions sometimes, which make tests randomly failing. I have change mechanism of filename generating (used the one from the boost). And added check to make sure generated name is not exist.
```
$ ./build/darwin/osquery/osquery_tests --gtest_filter='FileOpsTests.*' 
...
[==========] 14 tests from 1 test case ran. (164 ms total)
[  PASSED  ] 13 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FileOpsTests.test_append
1 FAILED TEST
```

Fix up flaky fileops_tests

---

osquery/core/posix/process.cpp
osquery/core/watcher.cpp
osquery/core/watcher.h
osquery/main/main.cpp

Fix #4358
Added a custom stop function to WatcherRunner to stop all autoloaded extensions, before shutting down. Also, modified PlatformProcess for posix  to send SIGTERM, and not SIGINT (keyboard interrupt) when trying to nicely kill a process.
Run osqueryi locally and checked that after it completes no more Unix socket error messages appear.
Also,  runned an instance of osqueryd and running a simple query with osqueryi. Made sure that osqueryi doesn't kill any process that osqueryd has started.

Fix autoloaded extension processes outliving the main process

---

osquery/events/windows/windows_event_log.cpp
osquery/tables/events/windows/windows_events.cpp

This addresses #4538 by forcing all of our event channel subscriptions to lower case, to ensure our checks are case insensitive.

bug: correctly check windows event log channels for firing

---

tools/provision/formula/libxml2.rb

This updates `libxml2` to version 2.9.7 for Linux and MacOS.

deps: Update libxml2 to version 2.9.7

---

tools/tests/test_osqueryi.py

To prevent any affects from system env.

Force `osqueryi` to not use osquery extensions from system env in tests.

---

tools/provision/formula/yara.rb
tools/provision/ubuntu.sh

This updates yara on MacOS and Linux. It’s been a while since we updated.

deps: Update yara to version 3.7.1

---

CMakeLists.txt

When building with lto clang will not generate debug information for libstdc++ with the assumption we will have those symbols separately. Since we're statically linking the lib we need to tell clang to generate these to make debugging easier. One major advantage is to be able to look into std::string while debugging osquery.
This adds 23MB to the debug symbols on Linux, but obviously doesn't affect the binary.

Build posix with -fno-limit-debug-info

---

tools/provision/formula/openssl.rb

This updated OpenSSL for MacOS and Linux.

deps: Update openssl to version 1.0.2o

---

include/osquery/dispatcher.h
osquery/dispatcher/dispatcher.cpp
osquery/dispatcher/tests/dispatcher_tests.cpp
osquery/events/windows/windows_event_log.cpp
osquery/logger/plugins/tests/buffered_tests.cpp
osquery/logger/plugins/windows_event_log.cpp

There were several inefficiencies in the old version of RunnerInterruptPoint and InterruptableRunnable.
1) RunnerInterruptPoint was throwing the exception when interrupted, however, the exception was always ignored.
2) InterruptableRunnable used the read-write lock, however only write lock was used.
3) InterruptableRunnable InterruptableRunnable, stored almost similar variable stop_, interrupted_.
4) std::atomic<bool> interrupted_ was used with locks, even though it was accessed by default safest access mode memory_order_seq_cst. So no additional cache invalidation was needed.
5) InterruptableRunnable contained code(in method interrupted() and variables bypass_check_, checked) just for testing. Which was slowing down method interrupted().
6) Some more confusing things. notify_all was not …

InterruptableRunnable RunnerInterruptPoint redesign

---

include/osquery/dispatcher.h
osquery/dispatcher/dispatcher.cpp

the dispatcher had 2 race condition.
In joinServices it was accessing service_threads_ with different lock(join_lock). However, if by that time new service was added baad things would happen :) .
Also, the dispatcher was accessing services_.size() without the lock. ( If by that time service was removed or joined bad things would happen)

dispatcher race conditions

---

tools/provision/formula/ccache.rb
tools/provision/formula/fbthrift-mstch.rb
tools/provision/formula/gcc.rb
tools/provision/formula/openssl.rb
tools/provision/formula/python.rb
tools/provision/formula/zlib-legacy.rb

Removing the undents before only applied to macOS but the Linux taps were pulled forward as well and thus have the same errors. This removes the rest of the undents and should fix building on Linux.

Remove linux undents

---

osquery/tables/system/windows/ntfs_acl_permissions.cpp
specs/windows/ntfs_acl_permissions.table

First attempt at a table for fetching permission access control lists for files and directories on Windows. This table requires a path predicate.
Usage: `select * from ntfs_acl_permissions where path = "C:\Program Files\";`
Access permissions string is kinda gross at the moment 🙃 
Looking forward to feedback!

Added ntfs acl permissions virtual table

---

tools/provision.sh

Fixes: #4588
This restores the Linuxbrew commit pins.

deps: revert linuxbrew updates from #4561

---

Makefile
tools/audit.sh
tools/formatting/format-check.py

The tool tools/formatting/format-check.py is a wrapper around tools/formatting/git-clang-format.py which (1) caculates the merge-base between your current branch and master or the passed branch (2) runs git-clang-format.py with the result and (3) analyses the output and exits with an appropriate code, printing an message and if necessary the diff representing the changes required.
This will make code auditing performance code format checks only for the commits on your feature branch, so they won't be affected in case master advanced.

Implement make format_check

---

CMakeLists.txt
osquery/database/CMakeLists.txt
tools/sync.sh

When running make sync on centos7, when sync.sh runs, there is no default lib search directories for ld to search during linking. To fix, I added a second parameter to the sync.sh call with validation to allow the lib directories to be searched.

Fix make sync on centos7

---

include/osquery/config.h
osquery/config/parsers/options.cpp
osquery/config/parsers/tests/options_tests.cpp

If an option is not String/Number/Bool, parse it as string. Fix for #4566
This allows more complex option values that are valid json strings.

Parse structured options as string

---

include/osquery/dispatcher.h
osquery/dispatcher/dispatcher.cpp

Reverting back InternalThreadRef to shared_ptr. #4592
It's still weird. If it's a problem, it should be on other platforms too. It looks to be connected to the weird interaction between this InternalRunnableRef function binded to the InternalThreadRef. If anyone comes up to more constructive explanation, please let me know.

memory leak resolve for dispatcher

---

osquery/tables/system/cpuid.cpp

Information taken from https://www.lowlevel.eu/wiki/CPUID
Only added flags I actually have some interest in: long mode (64 bit support), NX , huge page support, ...
Some of these could probably be inferred from other flags (or their combination) but it seems cleaner to just pull them from the cpuid functions directly.

Add some more features to the cpuid table.

---

tools/deployment/make_linux_package.sh

Keep functions in build to be able to symbolicate crash logs wihtout full debug symbols

do not strip everything for release build

---

osquery/extensions/CMakeLists.txt

`osquery` itself does not care about unicode validity in table columns,
just takes it "as is". It definitely makes sense, because it could be broken.
But thrift extensions interface for python do decode/encode. Which doesn't look correct.
If, for instance, shell history contains broken unicode test `python_test_example_queries`
will fail.
```bash
% sed -n '5277p' < ~/.zsh_history | xxd -b                                                                                                                          [146]
00000000: 11000011 10000011 10111111 01101100 01110011 00001010  ...ls.
```

Do not try to decode/encode utf-8 in python extensions

---

osquery/events/linux/udev.cpp

It looks like udev is sometimes failing with message "udev monitor returned invalid device".
This happens when we receive NULL from udev_monitor_receive_device(monitor_).
I checked implementation, and one possible case of actually returning NULL is when the argument(monitor_) is NULL. https://github.com/systemd/systemd/blob/master/src/libudev/libudev-monitor.c#L591
Even though we are checking if monitor_ is NULL at the beginning of the run, lock is released afterward, so no assumption could be made during the udev_monitor_receive_device call.
Extending the locked area.

udev resource protection

---

tools/provision/formula/thrift.rb

This allows a build-from-source on Ubuntu 18.04. The build chooses a dynamic `libfl` by default, which results in a missing `yywrap` method. Later I'd like to supply a build of `libfl` (flex) ourselves.

deps: Use static libfl in thrift build

---

include/osquery/events.h
osquery/events/events.cpp

ec_id_lock_ was not needed, because next_ec_id_  is atomic.
numSubscriptions need to acquire read lock.
fire does not need write lock(read is enough)
replaced obfuscated code with boost::ends_with. ( Also this obfuscated code would generate wrong log if subscriber name contained _events in the middle and also in the end)

events proof read

---

osquery/tables/system/posix/ssh_configs.cpp
specs/posix/ssh_configs.table

This PR adds a new table, ssh_configs, which will parse out the systemwide default and per-user ssh_config files, and dump each configuration block therein.
I could be happier with the way that the systemwide config is pulled, so any feedback would be appreciated.
One possible area of contention is the default behavior when querying for the ssh_configs of a particular user.
```
select * from ssh_configs where uid=500;
```
does not return the blocks from the systemwide config.
From the ssh_config man page: 
```
ssh(1) obtains configuration data from the following sources in the following order:
1.   command-line options
2.   user's configuration file (~/.ssh/config)
3.   system-wide configuration file (/etc/ssh/ssh_config)
For each parameter, the first obtained value will be used.  The …
```

first pass at ssh_config table

---

osquery/tables/utility/file.cpp

Closes #4578 
Fixes logic according to https://www.gnu.org/software/libc/manual/html_node/Testing-File-Type.html

fix regular files being tagged as symlinks

---

docs/wiki/deployment/logging.md

Reading the [osquery docs](https://osquery.readthedocs.io/en/stable/deployment/logging/#logger-plugins) about logging plugins one would assume that in order to enable kafka logging the correct flag would be `--logger_plugin=kafka` (given that the other plugin names appear as their corresponding flags AFAIK).
Using `kafka` though will return the error
```
Cannot activate kafka logger plugin: Unknown registry plugin: kafka
```
This is caused by the fact that the plugin seems to be actually called `kafka_producer` (since setting this has osquery publishing data to kafka properly).

[Docs] Kafka logging plugin is called kafka_producer not kafka

---

osquery/tables/system/posix/shell_history.cpp
osquery/tables/system/posix/shell_history.h
osquery/tables/system/posix/tests/shell_history_tests.cpp
specs/posix/shell_history.table

If the shell history file does not contain the timestamps for the lines
osquery will miss the time in rows and will show an confusing error
about attempt to convert empty string to INTEGER.
```
% head -n 3 ~/.zsh_history
ls
cd source
ls
```
```
osquery> select * from shell_history limit 1;
I0621 11:56:37.804193 2629124992 virtual_table.cpp:292] Error casting time () to INTEGER
+------------+------+---------+-------------------------------+
| uid        | time | command | history_file                  |
+------------+------+---------+-------------------------------+
| 1868255265 |      | exit    | /home/akindyakov/.zsh_history |
+------------+------+---------+-------------------------------+
```
So, default value for the time in shell history can solve the problem.

The default timestamp was added for shell_history without timestamps

---

include/osquery/status.h
osquery/core/CMakeLists.txt
osquery/core/status.cpp
osquery/core/tests/status_tests.cpp

Consider this PR as a cosmetic one.
Creating Status class object in the code is not so clear. It is not so obvious that default constructed Status is success. Also it is not obvious that status with zero code is success and non-zero is failure.
I created 2 static methods to make construction of some particular status clear to reader.

Create a `success` and `failure` static factory for Status

---

osquery/core/CMakeLists.txt
osquery/core/tests/error_tests.cpp

```
% ./build/darwin/osquery/osquery_tests --gtest_filter='Expected*'
Note: Google Test filter = Expected*
[==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (0 ms total)
[  PASSED  ] 0 tests.
% ./build/darwin/osquery/osquery_tests --gtest_filter='Expected*'
Note: Google Test filter = Expected*
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from ExpectedValueTest
[ RUN      ] ExpectedValueTest.initialization
[       OK ] ExpectedValueTest.initialization (0 ms)
[----------] 1 test from ExpectedValueTest (0 ms total)
[----------] 1 test from ExpectedPointerTest
[ RUN      ] ExpectedPointerTest.initialization
[       OK ] ExpectedPointerTest.initialization (0 ms)
[----------] 1 test …
```

Connecte expected.h and error.h tests to build system

---

osquery/core/posix/utils.cpp
osquery/core/utils.h
osquery/core/windows/utils.cpp

On the one heand there is no place of use for it. And on the other, if code rely on all this checks it must be pretty unsafe and messy.

Remove platformStrncpy function from osquery/core/utils.h

---

osquery/tables/system/windows/processes.cpp

This is a follow-up to PR #4369.  The main change is on this line: https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/processes.cpp#L233
where TOKEN_OWNER is now TOKEN_USER.
Since in #4369 TokenOwner was corrected to TokenUser here: https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/processes.cpp#L237
we needed to update the vector size allocation. All the rest of the changes is just renaming tokOwner to tokUser to match the logic.

Using TOKEN_USER instead of TOKEN_OWNER struct

---

include/osquery/error.h
include/osquery/expected.h
osquery/core/tests/error_tests.cpp
osquery/core/tests/exptected_tests.cpp

- `Expected` is template from `ValueType` and `ErrorCodeEnumType`
- `Error` is stored by value in `Expected` object, not by pointer
- Changed storage mechanism for error and value - now it is a variant with both types
- Changed type of smart pointer for underlying error object - from shared to unique
- Added abstraction for new `Status` aka `Expected` with `boost::blank`
- Added more tests for `Expected`
- Added helper function to create `Error` object

Explicit use `ValueType` and `EnumErrorType` in `Expected` full type definition

---

osquery/core/conversions.cpp
osquery/core/conversions.h

Using templates generic version for any 'iterable' container could be done.
Also, definition for std::set were using a useless copy of data.

Remove container specific join implementation from conversions.h

---

osquery/tables/system/darwin/signature.mm
osquery/tables/system/darwin/tests/signature_tests.mm
specs/darwin/signature.table

This is an attempt at solving issue #2987 
The new column allows the user to disable resource hashing when querying the table.
```
osquery> SELECT *, hash_resources FROM signature WHERE path = '/Applications/Xcode.app' AND hash_resources = 0;
+-------------------------+--------+--------------------+------------------------------------------+-----------------+----------------------------------+----------------+
| path                    | signed | identifier         | cdhash                                   | team_identifier | authority                        | hash_resources |
+-------------------------+--------+--------------------+------------------------------------------+-----------------+----------------------------------+------------ …
```

Add a hash_resources parameter (column) to the macOS signature table

---

tools/build.ps1
tools/provision/chocolatey/openssl.ps1
tools/provision/chocolatey/osquery_utils.ps1

Minor fixes to provisioning script:
* moved `Invoke-VcVarsAll` to `osquery_utils.ps1` so all provisioning scripts can use it
* Force set TLS 1.2 in `osquery_utils.ps1`
* Explicitly check Perl install to make sure incompatible version is not used
* Clean up external executions for things like `.bat` scripts and 7z, nmake, etc

Update win64 openssl provisioning script

---

tools/deployment/make_linux_package.sh
tools/deployment/osqueryd.initd

The PR provides:
- SysV init script to honor EXEC env variable
- applicable "/etc/default/osqueryd" config path in initd script for deb

Initd script

---

osquery/core/conversions.h
osquery/core/tests/conversions_tests.cpp

Also created a template implementation of `tryTo<>` for the variables of the same type (moving without conversion in case of rvalue, copying in case of lvalue), as an simplest example of using  such errors.

Created an `enum ConversionError` for conversion errors

---

include/osquery/error.h
osquery/core/tests/error_tests.cpp

To create an error, human readable message should be provided among other arguments. The message is good to better understanding what happened by log records. To make it more informative user should put in those message some data (numbers, strings etc).
This operator will help us to avoid using verbose constructions like `boost::format` or `std::ostringstream` or something similar to format a proper error message. We will be able just to "stream" in a created error any "printable" variables from the context.
Additionaly we will be able to use "fancy" tools for streams like boost::io::quoted or std::hex to format messages.
Example:
```c++
createError(SystemErorr::NoSuchFile, "Could not read pidfile: ")
<< boost::io::quoted(pidfile_path)
<< " " << read_status.toString();
```

Output stream operator `<<` for `Error`

---

packs/osx-attacks.conf

Adding detection for the recently discovered`OSX Dummy` malware. More information can be found [here](https://isc.sans.edu/diary/23816) and [here](https://objective-see.com/blog/blog_0x32.html).
Basically the queries look for some files dropped by the malware, mostly to achieve some persistence in the targeted system. Here are the two added queries:
```
SELECT * FROM launchd WHERE name = 'com.startup.plist';
SELECT * FROM file \
WHERE path = '/Library/LaunchDaemons/com.startup.plist' OR \
path = '/var/root/script.sh' OR \
path = '/Users/Shared/dumpdummy' OR \
path = '/tmp/script.sh' OR \
path = '/tmp/com.startup.plist' OR \
path = '/tmp/dumpdummy';
```
Also added `interval` for the `MacSearch_Adware` detection, it appeared to be missing.

Adding OSX Dummy malware to osx-attacks query pack

---

docs/wiki/development/creating-tables.md

A while back I added the ability for table implementations to adapt their logic based on the columns used in the query. Now I'm updating the docs for adding new tables to use this approach.

Add documentation for conditional column gen

---

osquery/tables/events/linux/selinux_events.cpp

The recently merged: 9497df67cc31f7760a28c77215438b89deae2115 should have been tested after a rebase because of an includes path refactor.

bug: Fix SELinux events rebase

---

include/osquery/dispatcher.h
osquery/dispatcher/dispatcher.cpp

As far serviceCount is not a static function there is absolutely legal to use `this` in it

Remove using instance() from serviceCount()

---

docs/wiki/deployment/configuration.md

Was mistakenly referred to on the documentation as `decorators_top_level`.

Fix documentation for flag decorations_top_level

---

docs/wiki/deployment/file-integrity-monitoring.md
osquery/config/parsers/file_paths.cpp

This allows to use results of a query to add file event listeners to files.
Example config:
```
{
"file_paths_query": {
"category_name": [
"select distinct '/Users/' || username || '/.gitconfig' as path from last where username != '' and username != 'root';"
]
}
}
```

Add the ability to specify file_paths with sql queries

---

include/osquery/flags.h
osquery/config/config.cpp
osquery/core/flagalias.h
osquery/core/flags.cpp
osquery/core/tests/flags_tests.cpp
osquery/database/database.cpp
osquery/extensions/extensions.cpp
osquery/logger/logger.cpp
osquery/logger/plugins/filesystem_logger.cpp

The goal is to improve build times.
The boost lexical casting include requirement in `flags.h` is not needed in every implementation file that uses a google flag. Moving this to the several files that actually use it improves build times (+5% wall time). Measured with stopwatch and 2 builds (observational science).

flags: Separate flags and flagalias

---

osquery/core/conversions.cpp

After boostorg/uuid@33da3e2a5b87 (and boostorg/uuid@3d2f7758e9e1) build fails. See [error log](https://ptpb.pw/DwGV).
CC @ilovezfs

Unbreak build against Boost 1.68

---

osquery/logger/logger.cpp

This fixes #4459.
Previously if `--verbose` was used, the initial startup of osquery would write several log lines in `/tmp/`. This is because no logger is configured for a moment and glog freaks out and tries to write these logs to a temporary place "always be logging!"

logger: Fix logfile writes to /tmp with verbose flag

---

tools/tests/utils.py

- what?
- rounds up negative durations reported by `tools/analysis/profile.py`, to zero
- why?
- in #4657, i found that super fast queries were returning negative durations when profiled
- looking a bit further, i see that we are subtracting 2 seconds from the wall time reported, but i don't see why we would do that
- if that looks wrong to you folks as well, i'm happy to remove the subtraction by two
- if not, then i'm happy to add a comment as to why we're doing it there, and keep the line i added in this PR

round negative reported durations in query profiler to zero

---

osquery/sql/sqlite_filesystem.cpp

Before this PR getParentDirectory was using wrong separation symbol :(

fixed error when wrong directory separator was used for parent_directory function

---

osquery/tables/networking/etc_hosts.cpp
osquery/tables/networking/tests/networking_tables_tests.cpp
osquery/tests/test_util.cpp
osquery/tests/test_util.h
tools/tests/test_hosts_ics.txt

With this change, on Windows etc_hosts table will include data from etc/hosts.ics file in addition to etc/hosts.
Tested by querying the table manually:
Added a test for the new file as well.

Add etc/hosts.ics data to the etc_hosts table.

---

include/osquery/database.h
include/osquery/events.h
osquery/database/database.cpp
osquery/database/plugins/ephemeral.cpp
osquery/database/plugins/ephemeral.h
osquery/database/plugins/rocksdb.cpp
osquery/database/plugins/rocksdb.h
osquery/database/plugins/sqlite.cpp
osquery/database/plugins/sqlite.h
osquery/database/tests/database_tests.cpp
osquery/database/tests/plugin_tests.cpp
osquery/database/tests/plugin_tests.h
osquery/events/benchmarks/events_benchmarks.cpp
osquery/events/events.cpp
osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/auditdnetlink.h
osquery/events/linux/auditeventpublisher.cpp
osquery/events/tests/events_database_tests.cpp
osquery/tables/events/linux/process_events.cpp
osquery/tables/events/linux/process_file_events.cpp
osquery/tables/events/linux/socket_events.cpp
osquery/tables/events/linux/user_events.cpp

This PR adds support for write batching to the database plugins and the events framework. 
We spent some time profiling osqueryd with perf, and the patch should remove RocksDB from the hot path, making Audit-based tables (process_events/user_events/sockets_events/process_file_events) a lot more reliable and faster.
When using the `system_stress.py` script on my system with a factor of 9, CPU usage went down from 80~90% to 20% max. Another key difference is that the machine never feels unresponsive now.
I would really love to get some feedback on this patch, and hear what you think!

Improving audit-based table performances

---

osquery/tables/system/darwin/signature.mm
specs/darwin/signature.table

Osquery currently fails to extract the CDHash for signed binaries which use
a CDHash produced by a different algorithm than SHA-1.
CDHash is not guaranteed to be SHA-1.  In fact, the algorithm is being
changed to SHA-256. Therefore, this pull req removes the dependency on
SHA-1 from the code in order to support CDHashes produced with other
hash algorithms, but still relies on the OS to decide which CDHash to select
if there are multiple hashes produced using different hash algorithms.
An alternative approach to the one I've chosen would be to extract all of
the available CDHashes and make them all available in separate columns.
This pull request is the least intrusive improvement over failing to extract
the CDHash entirely where the OS decides to serve up SHA-256 instead
of SHA-1.

Support CDHash algorithms other than SHA-1 (Darwin)

---

include/osquery/tables.h
osquery/config/config.cpp
osquery/core/tables.cpp
osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp
osquery/remote/enroll/plugins/tls_enroll.cpp
osquery/sql/sqlite_util.cpp
osquery/sql/virtual_table.cpp
osquery/tables/events/darwin/disk_events.cpp
osquery/tables/system/cpuid.cpp
osquery/tables/system/darwin/preferences.cpp
osquery/tables/system/darwin/signature.mm
osquery/tables/system/freebsd/os_version.cpp
osquery/tables/system/linux/os_version.cpp
osquery/tables/system/linux/processes.cpp
osquery/tables/system/posix/shell_history.cpp
osquery/tables/system/posix/suid_bin.cpp
osquery/tables/system/windows/logged_in_users.cpp

The goal is to improve build times.
This removes `boost::lexical_cast` from `tables.h`.
This is a work in progress as there are plenty of things that relied on the implicit availability. And if someone has a better approach, please feel free to commandeer/close this.

tables: Remove lexical_cast include from tables

---

include/osquery/mutex.h
include/osquery/tables.h
osquery/core/tables.cpp
osquery/devtools/shell.cpp
osquery/examples/example_writable_table.cpp
osquery/registry/registry_interface.cpp
osquery/sql/benchmarks/sql_benchmarks.cpp
osquery/sql/sqlite_util.cpp
osquery/sql/tests/virtual_table_tests.cpp
osquery/sql/virtual_table.cpp
osquery/sql/virtual_table.h

This PR adds support for writable extension tables by providing an xUpdate sqlite3 implementation.
Write support for core/built-in tables is **NOT** implemented, and will not work.
This is a small demo for the following example: *osquery/examples/example_writable_table.cpp*
```
osquery> select * from WritableTable;
osquery> insert into WritableTable (text, integer) values ("1", 1);
osquery> insert into WritableTable (text, integer) values ("1", 1);
Error: constraint failed
osquery> insert into WritableTable (text, integer) values ("2", 2);
osquery> select * from WritableTable;
+------+---------+
| text | integer |
+------+---------+
| 2    | 2       |
| 1    | 1       |
+------+---------+
osquery> delete from WritableTable where text = "1";
osquery> select * from WritableTable; …
```

Write support for tables implemented from extensions

---

osquery/core/status.cpp

Dead code, let's get rid it off

Remove useless include of <iostream> from status.h

---

osquery/database/database.cpp
osquery/events/events.cpp
osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/tables/events/linux/process_events.cpp
osquery/tables/events/linux/process_file_events.cpp
osquery/tables/events/linux/socket_events.cpp
osquery/tables/events/linux/user_events.cpp

http://www.cplusplus.com/reference/vector/vector/reserve/
By documentation, vector can allocate more than requested by the reserve. If it can not allocate the minimum size bad_alloc is thrown.  ( This  kind of behavior actually makes sense, when reserve is optimized enough...)
Also, there is no point of checking if vector capacity is less then requested, as it's prohibited by the documentation.

incorrect assumption about reserve behavior

---

include/osquery/expected.h

Rvalue ref-qualified methods of unconditional access value or error are explicitly deleted. As far as `osquery` does not have an exceptions we definitely would like to avoid using unsafe way of getting either value or error without a proper check in advance.
So long story short, there is no legit scenario to use access rvalue ref-qualified access methods.
This is **wrong** to handle `Expected`:
```c++
auto getMeSomeText = []() -> Expected<std::string, SomeError> {
return createError(SomeError::SpecificError, "error message");
};
// ... many lines later ...
std::string text = getMeSomeText().get();  // UB
```
**The right way** is to check in advance:
```c++
auto expText = getMeSomeText();
if (expText) {
std::string text = getMeSomeText().get();
}
```

Explicitly delete rvalue ref-qualified unconditional access methods from Expected

---

osquery/core/conversions.h
osquery/core/tests/conversions_tests.cpp

- `boost_to_std_shared_ptr` and `std_to_boost_shared_ptr` as far as we don't use boost::shared_ptr in `osquery` anymore.
- `replaceAll`
- and remove useless includes

Remove dead code from conversions module

---

osquery/config/config.cpp
osquery/core/tables.cpp
osquery/core/watcher.cpp
osquery/sql/virtual_table.cpp
osquery/tables/system/darwin/signature.mm
osquery/tables/system/linux/processes.cpp

This applies @akindyakov's `tryTo` conversions to the refactor away from `lexical_cast` in #4683. This PR's scope is a little wider in that it replaces all `std::sto*`'s in the nearby code.
If fixes 1 bug AFAIK in the Linux `process_memory_map` table where `offset` conversions were failing for `00000` base16.

cleanup: Migrate calls to tryTo from 4683

---

include/osquery/status.h
osquery/core/tests/status_tests.cpp

To make transition from Status to Expected a bit easier.
For transition time there must be a lot of conversions from Expected to Status and back.
Conversion from Status to Expected is not simple, for many reasons.
Conversion from Expected to Status is trivial, but a bit verbose:
```c++
if (exp.isError()) {
return Status::failure(
exp.getError().getFullMessage()
);
} else {
return Status::success();
}
```
I'd suggest to use more laconic, clear and explicit way to convert.
```c++
return to<Status>(exp);
```

to<Status>(const Expected&) implementation

---

osquery/main/main.cpp

In the profile mode,  osquery was not shutting down normally.

profile implicit shutdown

---

osquery/carver/carver.cpp
osquery/config/config.cpp
osquery/core/watcher.cpp
osquery/dispatcher/dispatcher.cpp
osquery/dispatcher/distributed_runner.cpp
osquery/dispatcher/scheduler.cpp
osquery/events/darwin/diskarbitration.cpp
osquery/events/darwin/event_taps.cpp
osquery/events/darwin/fsevents.cpp
osquery/events/darwin/iokit.cpp
osquery/events/darwin/openbsm.cpp
osquery/events/darwin/scnetwork.cpp
osquery/events/events.cpp
osquery/extensions/extensions.cpp
osquery/extensions/interface.cpp
osquery/logger/plugins/buffered.cpp
osquery/sql/benchmarks/sql_benchmarks.cpp

setThreadName moved to thread entry points.
Also corrected our long-standing compilation warning
> /osquery/osquery/sql/benchmarks/sql_benchmarks.cpp:252:22: warning: 'range_y' is deprecated: use 'range(1)' instead [-Wdeprecated-declarations]
>   kWideCount = state.range_y();

setThreadName boilerplate removal

---

include/osquery/expected.h
osquery/core/conversions.cpp
osquery/core/tests/exptected_tests.cpp
osquery/core/watcher.cpp
osquery/devtools/shell.cpp
osquery/tables/networking/windows/interfaces.cpp
osquery/tables/system/darwin/signature.mm
osquery/tables/system/windows/physical_disk_performance.cpp

according to the osquery c++ style guide. Until it's not too late.

Fix up naming style for the Expected methods takeOr and getOr

---

osquery/dispatcher/scheduler.cpp

Use scheduled query name plus success/failure as a suffix of bumping path

Profile scheduled queries using numeric monitoring plugins

---

tools/get_platform.py

It is possible to identify Arch Linux without needing to install
`lsb-release` - we just use `/etc/os-release` which provides the same
level of information for what we need (and is available as part of the
base install).

Prefer /etc/os-release to identify Arch Linux

---

tools/build.ps1

This offers us a gate to prevent full 2017 builds until we can sort out the 3rd party dependency failures with the migration.

build: gating osquery build hosts to VS 2015 builds

---

osquery/config/config.cpp
osquery/core/conversions.h
osquery/events/events.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/sql/virtual_table.cpp
osquery/tables/system/linux/processes.cpp
osquery/tables/system/linux/smbios_tables.cpp
osquery/tables/system/tests/system_tables_tests.cpp

Also, I've used a throwing `std::stoll` in tests. Because the tests should not be exception safety and must fail if something goes wrong.

Remove `safeStrtoll` from conversions.h and change all use cases to `tryTo<>`

---

include/osquery/expected.h

To see something laconic and clear in case of incorrect usage in compiler error log. Like:
```
/Users/akindyakov/source/git.osquery/include/osquery/expected.h:86:3: error: static_assert failed "Expected does not support reference as a value type"
static_assert(
^
/Users/akindyakov/source/git.osquery/osquery/core/tests/exptected_tests.cpp:267:12: note: in instantiation of template class 'osquery::Expected<int &, osquery::TestError>' requested
here
auto e = Expected<int&, TestError>{i};
```
Instead of
```
/Users/akindyakov/source/git.osquery/include/osquery/expected.h:180:12: error: 'operator->' declared as a pointer to a reference of type 'osquery::Expected<int &, osquery::TestError>
::ValueType' (aka 'int &')
ValueType* operator->() && = delete;
^ …
```

Avoid verbosity of compiler complains in case of incorrect type for Expected value

---

include/osquery/expected.h
osquery/core/tests/exptected_tests.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/tables/applications/browser_utils.h

To make checks 'if expected is not an error then...' less verbose but more clear
Inspired by PR #4768

 `Expected::isValue` method, to make checks 'if expected is not an error then...'

---

osquery/tables/system/posix/load_average.cpp

This is a bug in llvm: https://bugs.llvm.org/show_bug.cgi?id=21629

Fix up warning about [missing-braces] in load_average.cpp

---

osquery/tables/system/windows/drivers.cpp

The windows drivers table has had some performance issues in the past, but these seem to have stuck around. I did some analysis with Visual Studio on "hot" paths in the table, and it seems like the worst offender is that we make a sql query against the registry table for every drivers Image path. For the most part, drivers image paths tend to be in the same place, so I replaced this logic with some simple caching to speed up the table a bit. I've left the manual derivation logic in the event the driver image is in a non-standard location. Below are the perf metrics, I'll update on a system at work that's experiencing substantially worse slow-downs tomorrow.
First with the new table:
```
C:\Users\Nick\work\repos\osquery [win-drivers-fix-take-2 ≡]
λ  Measure-Command …
```

performance: construct cache for windows drivers image path

---

osquery/killswitch/plugins/killswitch_tls.cpp

Killswitch content schema changed. Now killswitch map resides in "config"
In post request, killswitch plugin adds request=killswitch to make it more apparent what it's asking for and also to make it possible having same config and killswitch endpoint.
TLS plugin needed to call refreshable setup

Killswitch TLS plugin improved interface

---

include/osquery/config.h
include/osquery/dispatcher.h
osquery/config/config.cpp
osquery/config/tests/config_tests.cpp
osquery/core/watcher.cpp
osquery/dispatcher/dispatcher.cpp
osquery/dispatcher/distributed_runner.cpp
osquery/dispatcher/scheduler.cpp
osquery/dispatcher/tests/dispatcher_tests.cpp
osquery/events/events.cpp
osquery/events/kernel.cpp
osquery/events/linux/udev.cpp
osquery/events/windows/windows_event_log.cpp
osquery/extensions/extensions.cpp
osquery/killswitch/killswitch_refreshable_plugin.cpp
osquery/logger/plugins/aws_log_forwarder.h
osquery/logger/plugins/buffered.cpp
osquery/logger/plugins/kafka_producer.cpp
osquery/numeric_monitoring/numeric_monitoring.cpp

pauseMili renamed to pause. Removed pause without chrono time to get rid of the confusion. 
Improved use of pause by getting rid of multipliers.

pauseMili to pause transform

---

osquery/carver/carver.cpp
osquery/core/CMakeLists.txt
osquery/core/base64.cpp
osquery/core/base64.h
osquery/core/conversions.cpp
osquery/core/conversions.h
osquery/core/tests/base64_tests.cpp
osquery/core/tests/conversions_tests.cpp
osquery/filesystem/darwin/plist.mm
osquery/filesystem/darwin/tests/plist_tests.cpp
osquery/sql/sqlite_encoding.cpp
osquery/tables/system/darwin/extended_attributes.cpp
osquery/tables/system/darwin/tests/certificates_tests.cpp
osquery/tables/system/darwin/time_machine.cpp

It barely related to type conversion functions, so it is a good reason to live outside of it.
Just movement and small renaming. There is no changes in functional part.
(There is a bug in encoding implementation, but let me fix it after this PR)

Move out base64 decode/encode functions to separate file

---

osquery/events/events.cpp
osquery/events/linux/auditdnetlink.cpp
osquery/events/tests/events_database_tests.cpp

@clong is investing some time testing the patch to make sure that everything works as intended (thanks!).
Event records were not being saved correctly when writing batches, causing some events to get lost (how bad it was depended on how fast/slow the machine was).
A new test has been added to to prevent further regressions on this part of the code.
This only affected the Audit publishers.

Audit fixes

---

osquery/events/linux/auditdnetlink.cpp

Split of the PR @4714 
Thanks @alessandrogario 
@alessandrogario  text for this part of the PR
A 1-second timeout has been added to the wait call inside the  `AuditdNetlinkParser` service so that it now has a chance to check for the `interrupted()` status and correctly terminate even if the `AuditdNetlinkReader` service is no longer running and sending notifications.
The bug did not affect the osqueryd daemon because the signal sent on termination was able to wake up the service.

gracefully shutdown -  AuditdNetlinkParser will not wait indefinitely

---

osquery/tables/networking/windows/interfaces.cpp
osquery/tables/system/windows/drivers.cpp

We (the Visual C++ team) got feedback from a customer that they were surprised that converting a wstring to a string by passing the wstring iterators in through string's range ctor didn't emit narrowing conversion warnings. It turns out we were accidentally suppressing such warnings with a static_cast. Removing the static_cast exposes the warning is OSQuery, fixed here.
This change calls the wstringToString API already present, rather than leaving the wchar_t -> char narrowing in place.

Avoid warnings about implicit conversion from wchar_t -> char

---

osquery/database/database.cpp
osquery/database/tests/database_tests.cpp

`sendPutDatabaseRequest` grabbed the value from the wrong data point.
Changed to use the batch db processing only for >1 values in the list, instead of always.

Use putBatch only for multiple puts, fix bug in setDatabaseVal

---

osquery/devtools/shell.cpp

The OSQuery API provides a method (`getQueryColumns`) for getting
the column types of a query. It's far from perfect (there are
lots of cases where it can't tell, or even gets it wrong), so
it's sometimes useful to be able to see what it thinks about
a particular query.
This commit introduces a shell command `.types` that takes a query and
shows what the API would give for its column types.
```
osquery> .types SELECT name, celsius, celsius - 100 AS degrees_over_boiling FROM temperature_sensors;
+----------------------+--------+
| name                 | type   |
+----------------------+--------+
| name                 | TEXT   |
| celsius              | DOUBLE |
| degrees_over_boiling | BIGINT |
+----------------------+--------+
```

Introduce .types shell command

---

osquery/core/darwin/conversions.cpp
osquery/core/tests/conversions_tests.cpp

You could see it in `wifi_networks` table with Chinese network name for instance.
```
osquery> select network_name from wifi_networks;
[
{"network_name":""},
]
```
But is should be something like:
```
osquery> select network_name from wifi_networks;
[
{"network_name":"星期天"},
]
```
The problem was in function `stringFromCFString`. It was designed to work only with ASCII strings, which is wrong. So, I fixed it.

Fix up `stringFromCFString` bug related to non ascii strings

---

osquery/database/CMakeLists.txt
osquery/logger/CMakeLists.txt
osquery/sql/CMakeLists.txt

Recent CMakeLists changes missed necessary didn't account for `make sync`
support. Add a workaround here.

Fix make sync

---

tools/codegen/gentargets.py

osquery could not compile if we used different version of the rapidjson, which would have it's on typedef of the sizetype

support different version of the rapid json

---

osquery/tables/system/linux/smbios_tables.cpp
osquery/tables/system/linux/system_info.cpp
osquery/tables/system/posix/smbios_utils.cpp
osquery/tables/system/smbios_utils.h

Currently there is a function `std::string dmiString(uint8_t* data, uint8_t* address, size_t offset)` for extracting null terminated strings at the end of a [SMBIOS](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_2.7.1.pdf) structure.  The 3rd parameter takes the offset of the structure that points to the index of where the string resides.  This is problematic in that structures like `OEM string` (type 11), which merely contain a count of total number of strings stacked at the end, will not be able to use this function as is.  It also feels a bit semantically incorrect for the function to accept an offset of the structure to get an index from as parameter rather than just taking in the index of the string the caller wants directly.  This PR makes that minor change of …

tables: dmiString function param to use string index

---

osquery/database/database.cpp

std::regex is not safe https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61582 and also it errors linter.
Replaced it with the simpler mechanism.

get rid of std::regex

---

osquery/core/system.cpp
osquery/core/windows/wmi.h
osquery/tables/networking/windows/arp_cache.cpp
osquery/tables/networking/windows/interfaces.cpp
osquery/tables/system/windows/bitlocker_info.cpp
osquery/tables/system/windows/cpu_info.cpp
osquery/tables/system/windows/disk_info.cpp
osquery/tables/system/windows/drivers.cpp
osquery/tables/system/windows/logical_drives.cpp
osquery/tables/system/windows/os_version.cpp
osquery/tables/system/windows/patches.cpp
osquery/tables/system/windows/physical_disk_performance.cpp
osquery/tables/system/windows/processes.cpp
osquery/tables/system/windows/shared_resources.cpp
osquery/tables/system/windows/smbios_tables.cpp
osquery/tables/system/windows/system_info.cpp
osquery/tables/system/windows/video_info.cpp
osquery/tables/system/windows/wmi_bios_info.cpp
osquery/tables/system/windows/wmi_cli_event_consumers.cpp
osquery/tables/system/windows/wmi_event_filters.cpp
osquery/tables/system/windows/wmi_filter_consumer_binding.cpp
osquery/tables/system/windows/wmi_script_event_consumers.cpp

_There is a class WmiRequest in osquery/core/windows/wmi.h. It perform a WMI requests and do it during the construction. And it has only two methods, both to read the result of the query (results, getStatus). So, there are no reasons to be non-const for them. Let's mark them as const. And fix all the places which use them as non-const._
Added const keyword to functions and all the places which use them as non-const.
Issue:  #4731

Add constness for the methods of class `WmiRequest`

---

osquery/devtools/shell.cpp

Resolving writable-strings warning, which can be found in jenkins leaks build. This code could crash if shell_callback was really changing it, but it's not so made the argument const. Everything else, is just the chain reaction to this change :(

resolve -Wwritable-strings warning

---

tools/provision/formula/ssdeep-cpp.rb

Add hashes for `ssdeep-cpp` so everyone does not have to build when installing deps.

deps: Add bottle hashes for ssdeep-cpp

---

osquery/tables/system/darwin/packages.h

clang 1 out of 2 warning fixed.

clang flexible-array-extensions warnings fix

---

osquery/tables/system/darwin/gatekeeper.cpp

This PR fixes #4748. 
When I wrote the gatekeeper table, I did not correctly handle the case where `/var/db/SystemPolicy-prefs.plist` (the file that describes gatekeeper's settings) is missing.
When this file is missing (which is the default situation on macOS where the user has not modified gatekeeper's settings) macOS will fully enable Gatekeeper.
Before this commit, if the that file was missing, the gatekeeper table would incorrectly report the `assessments_enabled` column as `0` and `dev_id_enabled` as `NULL`. 
This change ensures the gatekeeper table reports `assessments_enabled` column as `1` and `dev_id_enabled` as `1`. This now correctly reports the state of the machine.

A missing Gatekeeper prefs file indicates it is on

---

include/osquery/expected.h

Expected was failing on debug mode for a while because of default move assignment operator did not update error_checked flag.
Use case is following:
Expected x = func1();
if (x) {
}
x = func2();
^======== failing here, code will assert on func2 result destructor

fixed move assignment operator for expected

---

CMakeLists.txt

Treating warnings as errors in posix
- makes osquery coding style better.
- In our current setup, it is hard to check if PR is causing additional warnings/problems and reviewer time was spent on pointing out pedantic things.
- makes review faster (Less rounds of the review)

posix treat warnings as errors

---

osquery/tables/networking/darwin/routes.cpp
osquery/tables/networking/freebsd/routes.cpp
osquery/tables/networking/linux/routes.cpp
osquery/tables/system/darwin/gatekeeper.cpp
specs/routes.table

Summary:
The 'hopcount' field exposes the TTL (or hop_limit in IPv6) associated to the route.
Tested on:
- Linux 4.17.13
- FreeBSD 11.2
- Darwin 17.7.0

Add hopcount entry to the 'routes' table

---

osquery/tables/networking/linux/routes.cpp

The routes table displays an IPv4 for the default IPv6 route:
`osquery> SELECT destination,gateway FROM routes WHERE gateway <> "";`
| destination | gateway               |
| ----------- | --------------------- |
| 0.0.0.0     | 172.17.208.1          |
| 0.0.0.0     | fe80::5:73ff:fea0:514 |
New output:
| destination | gateway               |
| ----------- | --------------------- |
| 0.0.0.0     | 172.17.208.1          |
| ::          | fe80::5:73ff:fea0:514 |
Note: it works as expected on Darwin and FreeBSD.

route table: properly display the default IPv6 route on Linux

---

osquery/tables/system/linux/pci_devices.cpp
osquery/tables/system/linux/pci_devices.h
osquery/tables/system/linux/tests/pci_devices_test.cpp
specs/posix/pci_devices.table

The current implementation linux's `pci_devices` table retrieves vendor and model information from sysFs attributes, which in turn utilizes systemd's hwdb to retrieve the information.  However hwdb utilizes a repo local copy of `pci.ids` to generate the `hwdb` rather than the system copy of `pci.ids` which usually far more updated.   This PR introduces retrieval of vendor and model information from the system copy of `pci.ids`.   New columns `subystem_vendor_id`, `subsystem_vendor`, `subsystem_model`, `subsystem_model_id` have also been added to enrich PCI device hardware information.

pci_devices: model and vendor information from system PCI db && add subsystem info

---

tools/provision/formula/ssdeep-cpp.rb

So that macOS doesn't pick the Linux one
Fixes #4855

Reorder hashes in the ssdeep-cpp formula

---

osquery/config/parsers/options.cpp
osquery/logger/logger.cpp

In the effort to make logger less confusing, removing aliased flag of the verbose which was verbose_debug.
#4608

get rid of alias verbose_debug and debug

---

osquery/tables/networking/linux/routes.cpp

Darwin, FreeBSD and Windows already supports this.
The value of the MTU is stored in an extended attribute of the netlink
message.
This field can be very useful to detect hosts that are using jumbo
frames.
Note that Linux has a different behaviour compared to the other OSs.
If the MTU was not configured, it will not display the default MTU value
(usually 1500), but 0, which means 'use the MTU of the interface'.
Test plan:
```
$ ip route add default via 172.17.208.1 dev wlp58s0 mtu 1492
$ osqueryi "select destination from routes where mtu=1492;"
```

route table: get the value of the MTU on Linux

---

osquery/logger/logger.cpp
osquery/logger/tests/logger_tests.cpp

Docs has never promised this kind of behavior currently implemented.
Even if we specify --logger_min_stderr=x and x matches with default value, logger_min_stderr could be overwritten.
#4608

Match how logger_min_stderr  works to doc

---

osquery/logger/logger.cpp

In the effort to make error filtering by the severity possible, we need to make several changes and less flag overwriting.
When plugin was not named filesystem osquery was just overwriting FLAGS_logtostderr to true. When FLAGS_logtostderr is true, it's impossible to filter logs written in GLOG by severity.
#4608

default logtostderr to true (remove logStderrOnly)

---

docs/wiki/installation/cli-flags.md
osquery/logger/logger.cpp
osquery/logger/tests/logger_tests.cpp

Split #4745 
Could not find any important use case for primary concept.
Noticed community about the PR mentioned(slack). Only thing which is still needed is logger logging events. No one has mentioned primary logger.

remove primary logger concept

---

docs/wiki/deployment/logging.md
osquery/logger/logger.cpp

In the effort to make logger less confusing, removing aliased flag of the logger_event_type which was log_result_events. 
In one doc https://osquery.readthedocs.io/en/2.4.5/deployment/logging/ - log_result_events is mentioned
In the other one https://osquery.readthedocs.io/en/2.4.5/installation/cli-flags/ - logger_event_type
To make things less confusing removing one of them.
#4608

get rid of aliased flag log_result_events

---

osquery/extensions/interface.cpp

This is useful information to have in the logs, not only verbose logs.

Log when an extension is registered or dies

---

include/osquery/filesystem.h
osquery/filesystem/filesystem.cpp
osquery/filesystem/tests/filesystem_tests.cpp
osquery/logger/plugins/filesystem_logger.cpp
osquery/remote/enroll/tests/enroll_tests.cpp

force_permissions argument is not used.  I checked the initial PR introducing this function and looks like was like that from the beginning.

remove unused force_permissions

---

osquery/logger/logger.cpp

While cleaning project from primary logger concept, some of the variables have been overlooked. #4969

cleanup after the primary logger concept removal

---

include/osquery/expected.h
osquery/core/tests/exptected_tests.cpp

Make error messages in Expected check different to know for sure which check is failed.

Make error messages in Expected check different to distinguish problems

---

include/osquery/expected.h

`debug_only::Var` debug version doesn't have assign operator. So, assigning couldn't be used to set up new value.

Fix up usage of debug_only::Var in expected assign operator

---

Vagrantfile
tools/provision/darwin.sh
tools/release/build_release.sh
tools/release/deps_release.sh

This is part of #5072.
The change from `head` to `tail` for selecting macOS command line tools may be concerning. This used to install 10.10 tools, which are still available on 10.13. This might include support for older SDKs to build against.
If this is a problem then it should be visible at compile time when we select the minimum-supported-build.

deps: Update Vagrant macOS target to 10.13

---

osquery/tables/system/darwin/smbios_tables.cpp
osquery/tables/system/linux/smbios_tables.cpp
osquery/tables/system/posix/smbios_utils.cpp
osquery/tables/system/smbios_utils.h
specs/blacklist
specs/posix/oem_strings.table

This is the initial implementation of [SMBIOS type 11 structure, OEM strings](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_2.7.1.pdf), which consists of free form strings defined by the OEM.
An real world example of the usefulness of this table could be when OEMs sell equipment to 3rd party suppliers, they sometimes do not fill out vendor and model information in the usual type 0 structure (retrieved in osquery table `system_info`) but include the data that reveals the original vendor and model in the type 11 structure.   This table will allow users to examine the true origin of the system.  In the case that information that can be missing altogether, an SQL statement like this can be made to fill in what should be there:
```sql
SELECT computer_name, 
cpu_brand, …
```

SMBIOS `oem_strings` table

---

osquery/core/init.cpp
osquery/logger/logger.cpp

In the effort to make logger less confusing,  initLogger would return immediately if FLAGS_disable_logging was true. However, this code could be pushed outside.
#4608 #4983

rearrange initLogger disable capabilities

---

tools/tests/test_http_server.py

Issue #4674 (https://github.com/facebook/osquery/issues/4674) details incorrect documentation for the persist argument in osquery/tools/tests/test_http_server.py
Updated description more accurately describes the persist argument.

Fix of issue #4674:  Updated Documentation

---

include/osquery/expected.h

to be sure that other expected remains with status 'error checked'

Add an rvalue constructor for Expected

---

osquery/core/system.cpp

FreeBSD supports renaming threads with `pthread_np`.
The difference with Linux or Darwin is that there's no error code:
>   Because of the debugging nature of this function, all errors that may
>    appear inside are silently ignored
This isn't really a problem because thread names are meant for debugging
and osquery does not check the retun value of `setThreadName()` anyway.
Test plan:
```
adrs@freebsd: procstat -t `pidof old_osqueryi`
PID    TID COMM                TDNAME              CPU  PRI STATE   WCHAN
7612 100059 osqueryi            -                    -1  152 sleep   ttyin
7612 100162 osqueryi            -                    -1  152 sleep   uwait
7612 100163 osqueryi            -                    -1  152 sleep   select
adrs@freebsd: procstat -t `pidof osqueryi`
PID    TID COMM …
```

Implement setThreadName() for FreeBSD

---

osquery/tables/system/darwin/sysctl_utils.cpp
specs/posix/system_controls.table

Task Description : On Posix systems (which includes macOS), the OSQuery system_controls table exposes various pieces of kernel state. It is the OSQuery equivalent of the sysctl command. Many of the state variables that can be read by sysctl are simple integers or strings. OSQuery handles these just fine. However, on macOS, some are so-called "opaque" values, typically structs that are specific to one or a few state variables. OSQuery does not know how to display these, and just shows them as null. This task is about teaching OSQuery to do something reasonable with these opaque values.
Changes : updated schema to include "field_name" column. This shows specific attribute of opaque struct.
systctl_utils.cpp logic now expands and pulls specific struct information similar to sysctl.c - …

Expand "opaque" values in system_controls table

---

tools/lib.sh

Run `make test_debug` in order to run the tests for the debug build. Because currently build.sh tries to run `make test` instead, which is wrong. Because it looks for the tests binary in wrong directory (e.g. in `build/darwin/` instead of `build/debug_darwin/` on masos).
That is only for posix builds, I'll do the same for windows later.

Run `make test_debug` in order to run the tests for debug build

---

osquery/tests/integration/tables/crontab.cpp
osquery/tests/integration/tables/helper.cpp
osquery/tests/integration/tables/helper.h
osquery/tests/integration/tables/uptime.cpp

It is a bit more clear to use just a functions without smartpointers

Use just std::function for custom validator in table integration tests

---

osquery/sql/sqlite_encoding.cpp
osquery/sql/virtual_table.cpp

Previously:
```
~/git/osquery(branch:blob*)0 » osqueryi                      
osquery> create table blobs (uid blob); insert into blobs values (x'0023456789abcdef0123456789abcdef42'); select length(uid), hex(uid), to_base64(uid), uid from blobs;
length(uid) = 17
hex(uid) = 0023456789ABCDEF0123456789ABCDEF42
to_base64(uid) = 
uid = 
```
With this change:
```
~/git/osquery(branch:blob*)0 » ./build/linux/osquery/osqueryi                               
osquery> create table blobs (uid blob); insert into blobs values (x'0023456789abcdef0123456789abcdef42'); select length(uid), hex(uid), to_base64(uid), uid from blobs;
length(uid) = 17
hex(uid) = …
```

virtual tables: Handle SQLite3 BLOB_TYPE

---

Vagrantfile

The Vagrantfile is missing a "-" in the name of the vagrant box for Ubuntu 17.04.
Typo'd vagrant box name causes vagrant up to fail.
```
osquery vagrant up ubuntu17.04
Bringing machine 'ubuntu17.04' up with 'virtualbox' provider...
==> ubuntu17.04: Box 'bento/ubuntu17.04' could not be found. Attempting to find and install...
ubuntu17.04: Box Provider: virtualbox
ubuntu17.04: Box Version: >= 0
The box 'bento/ubuntu17.04' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
URL: ["https://vagrantcloud.com/bento/ubuntu17.04"]
Error: The requested URL returned error: 404 Not Found
``` …

Typo on Ubuntu 17.04 bento box

---

tools/provision/darwin.sh

When running `make sysprep` on High Sierra with SIP enabled, this step will fail with the following due to SIP:
```
$ make sysprep
-- Warning! The only Apple OS supported for building is 10.12
-- Note: Installing and running osquery is supported on versions 10.9+
[+] found darwin provision script: ~/osquery/tools/provision/darwin.sh
[+] requesting sudo: /usr/bin/gem install --no-ri --no-rdoc fpm
Password:
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /usr/bin directory.
make: *** [sysprep] Error 1
```
This can be avoided by installing the fpm gem to `/usr/local/bin`. This issue is documented in #5116

Darwin provisioning script to use /usr/local/bin to avoid SIP violation

---

osquery/tests/integration/tables/helper.cpp

It makes error messages more readable in case of empty value or weird keys like `type`

Add quotes for the key and value in  assertion messages

---

osquery/tests/integration/tables/helper.cpp

It is exactly the same, to check the keys from both sets instead of checking the keys from one set and checking the size. But this way I must be more talkative what's wrong with a checking row.

Make  more talkative in terms of unexpected columns

---

include/osquery/numeric_monitoring.h
osquery/numeric_monitoring/numeric_monitoring.cpp
osquery/numeric_monitoring/tests/numeric_monitoring_tests.cpp

There was found non testing use case for numeric_monitoring flush. 
For example, when osquery receives termination signal and wants to store it, it needs to be flushed ASAP. 
Using flush is still not recommended when it's not necessary, as it might degrade performance or DDoS server.

allow numeric_monitoring flush for non testing purposes

---

Makefile
README.md

Following the order #5072.
macos10.13 should be ready for prime time.

build: Set 10.13 as default builder

---

include/osquery/killswitch.h
osquery/dispatcher/scheduler.cpp
osquery/killswitch/killswitch.cpp

Protect numeric_monitoring executing monitor with killswitch as it might misbehave and generate to much data for backend to handle.

executing query monitor under killswitch

---

include/osquery/numeric_monitoring.h
osquery/numeric_monitoring/numeric_monitoring.cpp
osquery/numeric_monitoring/pre_aggregation_cache.cpp
osquery/numeric_monitoring/tests/pre_aggregation_cache_tests.cpp

Additional aggregation types for numeric monitoring. Those aggregations can not be aggregated in buffer easily so pushing the logic to the backend.

numeric monitoring aggregation types

---

osquery/tables/system/intel_me.hpp
osquery/tables/system/windows/intel_me.cpp

This is a small fix for the `intel_me_info` table. The size of the response buffer should always match the size field found in the ioctl response.
I've tested this on Windows 10 with a Skylake processor. ~~Additional testing is welcome, as I'm only able to run it on one machine.~~
EDIT: We managed to test on different processors!
This will fix issue #4765
Processors we managed to test:
1. [i5-3320M - Ivy Bridge](https://github.com/facebook/osquery/pull/5111#issuecomment-416724062)
2. i5-6600K - Skylake
3. [i5-7200U - Kaby Lake](https://github.com/facebook/osquery/pull/5111#issuecomment-417642587)
4. [i7-7600U - Kaby Lake](https://github.com/facebook/osquery/pull/5111#issuecomment-416728451)
5. [i7-8650U - Kaby Lake](https://github.com/facebook/osquery/pull/5111#issuecomment-416628064)

intel_me_info/Windows: Fix the buffer size for the GetFirmwareVersion command

---

osquery/tables/system/linux/pci_devices.cpp
specs/posix/pci_devices.table

2nd PR of 3 described from [here](https://github.com/facebook/osquery/pull/5160).
The actual PCI class and subclass ID's were also missing from the table. Providing these columns brings value in that a user can now ask for information about PCI devices by their class and subclass attributes, and the queries will be less error prone because we can now select by their respective ID's rather than a textual description.
The next PR will contain a refactor for readability and easier unit testing of some of the subcomponents of `genPCIDevices` function, as well as some added unit tests.
@guliashvili let me know if there are updates to the integration tests.  I can add a test if it's ready to go.

tables: add pci_class_id and pci_subclass_id to pci_devices

---

tools/make-win64-binaries.bat

Windows 10 x64 Russian edition
Latest source code (bf95191)
Followed Windows 10 Development Environment Provisioning up to running `make-win64-binaries.bat`
Successful execution without errors
```
6/6 Test #6: python_test_windows_service ......***Failed    1.57 sec
test_1_install_run_stop_uninstall_windows_service (__main__.OsquerydTest) ... ERROR
test_2_thrash_windows_service (__main__.OsquerydTest) ... ERROR
======================================================================
ERROR: test_1_install_run_stop_uninstall_windows_service (__main__.OsquerydTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:/Users/dimas/Documents/Projects/osquery/osquery/tools/tests/test_windows_service.py", line 235, in setUp …
```

Changing the active code page to United States code

---

include/osquery/expected.h
osquery/core/conversions.cpp
osquery/core/tests/exptected_tests.cpp
osquery/devtools/shell.cpp
osquery/events/events.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/tables/networking/windows/arp_cache.cpp
osquery/tables/networking/windows/interfaces.cpp
osquery/tables/system/windows/physical_disk_performance.cpp

Too dangerous, because it is so easy to create a dangling reference (to local object for instance) with it.
It was discussed in terms of PR #4833
Explanation [ref](https://www.youtube.com/watch?v=lkgszkPnV8g&feature=youtu.be&t=769).

Removing potentially risky method `getOr(T const&)` from `Expected`

---

docs/wiki/deployment/process-auditing.md

Specify that you need to run _osqueryi_ as root to test audit framework. Usually you do not need to run _osqueryi_ as root, but in this case you need to. It may be obvious, but it wasn't for me!

osqueryi needs root to test auditing

---

osquery/core/windows/wmi.cpp
osquery/core/windows/wmi.h
osquery/tables/system/windows/smbios_tables.cpp

Previously, the `platform_info` table on Windows did not include the `ReleaseDate` field. This fix fills in the `date` column with an ISO8601 version of the `ReleaseDate`.
Closes #4771

Add ReleaseDate to table for platform_info queries on Windows

---

osquery/filesystem/windows/fileops.cpp

fixes #5194. osquery should not crash because of boost throwing. Reverting to non throwing api, as all other call to the is_directory in the fileops file

boost throwing is_directory bug

---

osquery/tables/applications/browser_utils.cpp
specs/chrome_extensions.table

This PR adds support for reading the permissions from the extension manifest file.
Here's a couple of examples:
```
osquery> SELECT uid, name, identifier, version, permission
...> FROM chrome_extensions
...> WHERE permission = "desktopCapture" OR
...>       permission = "clipboardRead";
+------+---------------------+----------------------------------+--------------+----------------+
| uid  | name                | identifier                       | version      | permission     |
+------+---------------------+----------------------------------+--------------+----------------+
| 1000 | Google Drive        | apdfllckaahabafndbhieahigkjlhalf | 14.1         | clipboardRead  |
| 1000 | Google Docs Offline | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1.4          | clipboardRead  |
| 1000 | Google Docs …
```

Add a 'permission' field to the chrome_extensions table

---

osquery/core/CMakeLists.txt
osquery/core/linux/cpu.cpp
osquery/core/linux/cpu.h
osquery/core/linux/tests/cpu_test.cpp

Helper functions to get CPU cores info exposed via sysfs on linux.
I need this information to use `kprobes` in osquery on linux.

Create helper functions to get CPU cores info on linux

---

include/osquery/numeric_monitoring.h
osquery/numeric_monitoring/numeric_monitoring.cpp
osquery/numeric_monitoring/plugin_interface.cpp
osquery/numeric_monitoring/plugin_interface.h
osquery/numeric_monitoring/plugins/filesystem.cpp
osquery/numeric_monitoring/plugins/tests/filesystem_tests.cpp
osquery/numeric_monitoring/tests/numeric_monitoring_tests.cpp

While program is terminating we need mechanism to make sure that plugin has really sent the data. sync monitor offers way to get rid of numeric_plugin buffer and also to let the plugin know that we need to send the record ASAP.

 numeric_monitoring recursive sync record

---

osquery/tables/applications/browser_utils.cpp

This PR fixes a translation issue in the `chrome_extensions` table, caused by how key names are handled in the translation dictionary.
The case of the string anchor (i.e.: `__MSG_APP_NAME__`, or `__MSG_appName__`) in the extension manifest does not always match the case used in the translation dictionary (`_locales/<locale_name>/messages.json`). This patch ensures that the translation dictionary is used with case insensitive keys. This fixes how the default `Chrome Web Store Payments` extension is shown to the user.

chrome_extensions: Use the translation dictionary with case insensitive keys

---

osquery/core/CMakeLists.txt
osquery/core/database/rocksdb_migration.cpp
osquery/core/database/rocksdb_migration.h

This PR adds new class that will handle all step by step db migrations in future. 
Implementation intentionally does not depends on actual rocksdb implementation, as well as on all existing constants to make each migration independent as much as possible.
Right now db migration is located in few places or non existent. It forces users to write logic that support old and new schema and provides no guarantees that other parts of the application will not access new data till it was actually migrated. Goal is to move all migration to single place and ensure that migration was performed before other parts of the app are inited.

added database migration class

---

include/osquery/core.h
osquery/core/init.cpp
osquery/database/database.cpp
osquery/extensions/extensions.cpp
osquery/main/windows/main.cpp
osquery/tables/yara/yara_utils.h

On Windows we have some queries for monitoring the size of the database path, however with the default values of the DB path these queries don't quite work. This modifies how we do default database paths just a bit so that slashes are specific to the platform on which the path is defined. A sample of the logic is below, as well as the sample query:
```
SELECT db.db_size_mb AS database_size FROM osquery_info i, processes p, time, (SELECT (sum(size) / 1024) / 1024.0 AS db_size_mb FROM (SELECT value FROM osquery_flags WHERE name = 'database_path' limit 1 ) AS flags, file WHERE path LIKE flags.value || '%%' AND type = 'regular' ) AS db WHERE p.pid = i.pid;
```
Before the database path was defaulted to an invalid directory
```
{"snapshot":[{"database_size":""}],"action":"snapshot","name":"datab …
```

database: changing default path of the database for pathing uniformity

---

osquery/database/plugins/rocksdb.cpp
osquery/database/plugins/sqlite.cpp
osquery/dispatcher/scheduler.cpp
osquery/filesystem/fileops.h
osquery/filesystem/posix/fileops.cpp
osquery/filesystem/tests/fileops_tests.cpp
osquery/filesystem/windows/fileops.cpp

The `paltformChmod` abstraction on Windows specifically leverages Deny ACE entries to attempt to prevent access to lower privileged users. The usage of Deny ACEs is pretty risky at best, and isn't something that's encouraged typically considering Windows DACLs will deny anyone who isn't explicitly granted an Allow ACE. This PR changes the permission management function we are using to manage our database permissions to simply set explicit allow entries for the Administrators and SYSTEM user accounts, our "equivalent" of root on Windows, as these are the only users that should have access to the osquery database. This addresses #5227, however this does not fix in entirety the issue that platformChmod shouldn't be leveraging Deny ACEs. That being said there are exceptionally few places in …

bug: explicitly set safe permissions on osquery dbs

---

tools/deployment/chocolatey/tools/chocolateyBeforeModify.ps1
tools/deployment/chocolatey/tools/chocolateyinstall.ps1
tools/deployment/chocolatey/tools/chocolateyuninstall.ps1
tools/provision/chocolatey/osquery_utils.ps1

CVE-2019-3567: This vulnerability affects osquery versions <= 3.3.2
osquery as it stands is vulnerable to a privilege escalation attack, if a malicious attacker is able to inject a new executable path into the extensions.load file, and hard link a parent folder of a malicious binary to a folder with known 'safe' permissions, osquery will load said malicious executable with SYSTEM permissions. This can be mitigated by migrating our installation to the 'Program Files' directory on windows which restricts unprivileged write access.
Test Plan: I built and installed this package locally
* Build the chocolatey package, we have to manually do this, but we can use our generation scripts :
```
PS C:\open\fbsource\xplat\osquery\oss\build\chocolatey\osquery> choco pack
Chocolatey v0.10.11
Attempting …
```

deployment: updating osquery installation path on Windows

---

tools/deployment/make_windows_package.ps1

This changes the deployment script to create an MSI binary which installs osquery to the Program Files folder, as per the latest security issues related to priv escalation in program data.

deploy: updating MSI package to install to Program Files

---

docs/wiki/deployment/configuration.md
docs/wiki/deployment/logging.md
osquery/utils/config/default_paths.h
tools/deployment/chocolatey/tools/chocolateyinstall.ps1
tools/deployment/osquery.example.conf
tools/wel/osquery.man

This fixes a few additional incorrect references to the old ProgramData installation path.

windows: updating more references to osquery installation path

---

docs/wiki/deployment/configuration.md
docs/wiki/deployment/logging.md
osquery/utils/config/default_paths.h
tools/deployment/chocolatey/tools/chocolateyinstall.ps1
tools/deployment/make_windows_package.ps1
tools/deployment/osquery.example.conf
tools/wel/osquery.man

This cherry-picks in some of the commits where we are migrating the ProgramData to Program Files installation directory.

deployment: updating additional installation paths to use Program Files

---

osquery/remote/http_client.cpp
osquery/remote/http_client.h
osquery/tables/applications/posix/docker.cpp

See issue #5591.
Boost ASIO does not detect the availability of `std::string_view` on newer LLVM/C++ installations. This is fixed in later versions of ASIO and #5591 should track the removal of this hack.

macos: Add hack for boost asio string_view detection

---

.travis.yml
tools/buckconfigs/freebsd-x86_64/type/debug.bcfg
tools/buckconfigs/freebsd-x86_64/type/release.bcfg
tools/buckconfigs/linux-x86_64/type/debug.bcfg
tools/buckconfigs/linux-x86_64/type/release.bcfg
tools/buckconfigs/macos-x86_64/type/debug.bcfg
tools/buckconfigs/macos-x86_64/type/release.bcfg
tools/buckconfigs/windows-x86_64/type/debug.bcfg
tools/buckconfigs/windows-x86_64/type/release.bcfg

It seems the base homebrew on TravisCI is not working (this may have started on June 11th). The error is `Error: Your Homebrew is outdated. Please run brew update.` 
This may add time to the build but should fix it.

travis: Add homebrew update true

---

CODEOWNERS

This adds a codeowners file. The intent here, is to provide a route to opening up more people to vet and approve commits. Committers should be added to the [osquery/osquery-committers](https://github.com/orgs/osquery/teams/osquery-committers) team. This will grant them write permissions, and cause them to be notified on PRs.
We will need to _additionally_ toggle the codeowners button in master branch protections.
This does _not_ provided a clearly visible audit trail for who has been added to `osquery-committers` or a process for doing that.
Fixes: https://github.com/osquery/foundation/issues/1

Initial codeowners

---

azure-pipelines.yml

Originally the separation existed because there were multiple branches,
and only one of them was protected by PRs.
So broken commits could land and differentiating from broken build
or tests was useful.
This is not true anymore and PRs checks are per pipeline, not per job,
so the separation wouldn't make a difference.

Merge Azure Pipelines build and test jobs

---

README.md

This PR adds CI status badges at the top of the README, separated between build and test statuses.
You can look at a preview here https://github.com/Smjert/osquery/blob/stefano/feature/ci-status-badges/README.md
Unfortunately right now there seems to be an issue, which I've reported to Azure DevOps, where the status badge for a job doesn't properly show its status, but it shows the result of the entire pipeline.
Meaning, if macOSBuild succeeded, but any other job failed, so the pipeline status is failed, also macOSBuild shows as failed.

Add Azure Pipelines status badges to the README

---

azure-pipelines.yml

Apparently there's a bug in the visualization of the logs,
where color codes eat characters.
So we disable tests colored output until a fix on Azure Pipelines appears.
Formatting a bit more consistently the yaml file.

Fix tests output and yaml formatting for Azure Pipelines

---

third-party/libudev/CMakeLists.txt

This is a hotfix to let the prepare_for_ide target work on Windows and
macOS, avoiding to download libudev that it's not needed and
doesn't exist for those platforms.
In theory for all the third-party libraries that do not exist for a
platform we should have an INTERFACE library as a substitute,
instead of avoiding to define any target.
We wait to do this change, because we are going to refactor how
dependencies are downloaded and imported.

Fix prepare_for_ide target on macOS and Windows

---

cmake/options.cmake
cmake/utilities.cmake

Some IDE require that the headers are assigned to a target, so they know
which TU uses them and also that they are part of the project.
The option ADD_HEADERS_AS_SOURCES has been added, if it's ON,
we assign those headers as INTERFACE sources of the target that publish
them.

Fix detection of some headers on some IDEs

---

osquery/tables/system/windows/registry.cpp
tests/unit/tables/system/windows/registry_tests.cpp

Calling GetLastError() will not return the error code for the Windows registry APIs,
since they return a LSTATUS value which already the error code.
This also fixes the RegistryTablesTest.test_registry_non_existing_key
test case which was incorrectly expecting success when querying
for a non-existent registry key.
Ported from https://github.com/osql/osql/pull/50

Fix wrong error code returned when querying the Windows registry

---

tools/generate_buck_config.ps1

The buck config generation script had a couple of small usage bugs.
This fixes it so it will properly generate a buck config on a new
Windows system
Start with no buck config on the system:
```
C:\Users\Nicholas\work\repos\osquery [win-buck-cfg-bug]> ls .\tools\buckconfigs\windows-x86_64\toolchain\vs2017_15.5.bcfg                                                    ls : Cannot find path 'C:\Users\Nicholas\work\repos\osquery\tools\buckconfigs\windows-x86_64\toolchain\vs2017_15.5.bcfg' because it does not exist.
At line:1 char:1
+ ls .\tools\buckconfigs\windows-x86_64\toolchain\vs2017_15.5.bcfg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\Nichol...s2017_15.5.bcfg:String) [Get-ChildItem], ItemNotFoundException
+ …
```

buck: fixing up buck config generation script for use on Windows

---

azure-pipelines.yml
cmake/options.cmake
cmake/utilities.cmake

Debug builds have been enabled on the CI, for macOS and Linux only, since Windows cannot build in Debug for now.
A new option has also been added to avoid generating debug symbols which are not useful on the CI and occupy too much disk space.

Enable Debug builds on the CI

---

cmake/options.cmake

This way is visible as a variable in the cache that can be set.

Explicitly add BUILD_TESTING CMake option

---

osquery/filesystem/fileops.h
osquery/filesystem/windows/fileops.cpp
osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/tests/BUCK
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/windows/certificates_tests.cpp
osquery/tables/system/windows/certificates.cpp
osquery/tables/system/windows/certificates.h
specs/macwin/certificates.table

This PR addresses a few bugs in the certificates table on Windows (which was somewhat broken), and also implements some additional functionality (new columns). This is the first of two PRs, the second of which improves the table's completeness with respect to the `Personal` certificate store.
Bugs Fixed
1. The store enumeration API (certEnumSystemStoreCallback) returned False during error handling, but this prematurely ends the enumeration of cert store locations and cert stores. The callback has been adjusted to always return true, which ensures complete enumeration. (https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nc-wincrypt-pfn_cert_enum_system_store#return-value)
2. The CertOpenSystemStore API (https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-cer …

windows/certificates: Fix enumeration bugs, add columns

---

osquery/sql/sqlite_util.h
osquery/sql/virtual_sqlite_table.cpp
plugins/config/parsers/auto_constructed_tables.cpp

This fix addresses issue https://github.com/osquery/osquery/issues/5225.
This idea came from reading the [SQLite WAL documentation](https://www.sqlite.org/wal.html) where it states:
> WAL normally requires that the VFS support shared-memory primitives...
It didn't clearly state that "shared-memory" requires the locking primitives to be enabled, but that's what I inferred since you usually don't want concurrent things to freely mess around with memory.
So I tried to load a WAL DB as ATC flipping the `respect_locking` parameter and it ended up working properly (hurray).
I'm sure the original reason why it was chosen to use the `*-none` (no-op locking primitives) VFSes by default is to avoid getting rejections from locked databases, but that's not the case with WAL since (again from the …

Fix ATC mounting of SQLite DBs using WAL journaling

---

tests/integration/tables/crontab.cpp

This test case failed for me. I believe range should be 0-7 not 0-6.
From man page of crontab
field allowed values
----- --------------
minute 0-59
hour 0-23
day of month 1-31
month 1-12 (or names, see below)
day of week 0-7 (0 or 7 is Sun, or use names)

crontab testcase fix

---

osquery/tables/system/windows/logged_in_users.cpp

Fixes https://github.com/osquery/osquery/issues/4655
I don't have much context here, other than the listed bug report. An internet search finds a slightly more in depth blog article http://redplait.blogspot.com/2018/06/interesting-case-of-memory-leak.html
As mentioned, the docs do reference using `WTSFreeMemory` to free.
Thanks for the bug report [redplait](https://github.com/redplait)

Update WTSFreeMemoryEx to WTSFreeMemory

---

osquery/tables/system/darwin/battery.mm

If there are no battery results, don't return a nil row. Return an empty set.
Fixes: https://github.com/osquery/osquery/issues/5649

Don't return a battery row, if there are no results

---

osquery/tables/system/linux/rpm_packages.cpp

The librpm dependency may be configured with a glibc version < 2.17. If
so then it will expect `__secure_getenv` to be available.

rpm: Check for glibc version and librpm secure_getenv

---

BUILD.md

Also add missing xcode-select --install in the CMake macOS guide
Fix osquery/osquery#5651

Specify compiler versions supported in BUILD.md

---

osquery/tables/CMakeLists.txt
osquery/tables/cloud/CMakeLists.txt

It does not look like the EC2 tables are available on Windows
(due to spec-file configuration).
Please see https://osquery.io/schema/3.3.2#ec2_instance_tags
This removes the EC2 library linking requirement until we revisit this
feature.

Remove cloud tables from windows

---

docs/wiki/development/creating-tables.md

update the hyperlink to tables.ht in the docs. It was broken in a previous refactoring

Fix tables.h hyperlink in docs

---

azure-pipelines.yml

A new Windows VM has been recently deployed that moves the
Python 2 installation, Windows Buck builds are now failing.
Support the old and new path for Python 2 and
support multiple minor versions of python instead of hardcoding one.

Fix python detection on Azure Pipelines

---

tests/integration/tables/running_apps.cpp

When run alone, using --gtest_filter to select the specific test,
it throws an exception because the tables are not registered.
It also wrongly checks for the query rows number to be >= 0 and then
proceeds to access the first one.

Fix runningApps.test_sanity

---

osquery/tables/system/darwin/user_groups.mm
osquery/tables/system/linux/groups.cpp
osquery/tables/system/tests/system_tables_tests.cpp
osquery/tables/system/user_groups.h

This PR supersedes #5669 with an alternate approach of moving forward
without a revert of #5368.
This includes a `cherry-pick`ed version of the code cleanup within #5669, thus needing a merge-with-rebase. 
- Lightly update the logic, to make the code paths similar between
no-constraint, and specified uid cases.
- Add tests to the group table.
@directionless I am interested if this PR's approach will cause missing data due to your code-comments here: https://github.com/osquery/osquery/pull/5669/commits/bb1e9b57af9cfd2b0ab28919ef81ccc01b0a7f40#r310408443

tables: Add optimization back to macOS users and groups

---

osquery/tables/system/linux/mounts.cpp

Hello osquery Devs!
**The issue:** 
Running statfs() on a /proc/mounts entry of type "autofs" will result in the mounting of that file system, changing the runtime state of the system.
**Why this is a problem:**
- The unintentional mounting of the file system changes the state of the machine, in violation of the first principle of contribution called out in the osquery/CONTRIBUTING.md guidelines: 
- "_1. osquery doesn’t change the state of the system_"
- In an environment with a large number of autofs direct maps, the query "select * from mounts;" will take down the host in a "mount storm". In a large environment, the traffic generated from pushing this request across the environment will result in the mount storm taking out the filers as well. 
**What solution is proposed by this pull …

Fix for mount table interacting with direct autofs.

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/windows/certificates.cpp
osquery/tables/system/windows/users.cpp
osquery/tables/system/windows/users.h

This is a follow up PR to #5631.
The winapis for certificate store enumeration generally do not show any certificates for other users' Personal stores, even when there are certificates there. Furthermore, whether the table shows information about other users' stores depends on whether the user has a registry hive mounted, which can be affected by events e.g. whether the user has logged in since boot. Personal certificates are actually stored on disk, rather than in the registry, which makes it possible to reliably read them (from an Admin process), regardless of whether they belong to a different user, and regardless of the state of the system's login history. This PR takes advantage of this to make the certificates table more complete wrt Personal certificates; Personal certificates are …

windows/certificates: Improve table's coverage of Personal certificates

---

osquery/tables/system/windows/certificates.cpp

Small follow up to #5640. 
When proactively searching disk for personal certificates, there is no
need to filter system accounts (SYSTEM, Local Service, etc) anymore
because `findUserPersonalCertsOnDisk` is now capable of handling those
accounts by dynamically finding a user's home dir (rather than by
constructing a hard coded path).
This now makes the table even more complete; any certificates found in
the system accounts directories will always be found. Previously they
could be found but only if there was a store location other than the
`Users` store location that had a system store string that looked like
`S-1-5-18\My` or `.DEFAULT\My`.
This is what it looked like previously. This is on a system where there are no store locations other than Users that have a system store string like …

windows/certificates: Improve table completeness for Personal certificates for system accounts

---

osquery/tables/system/windows/certificates.cpp

This is a followup to #5640. This should be the last one :)
This fixes a bug in environment variable expansion that occurs when paths to Personal certificate directories are constructed for system accounts.

windows/certificates: Fix bug in environment variable expansion

---

BUILD.md

java8 brew cask is deprecated due to a license change, adoptopenjdk8 is the recommended replacement.

Replace java8 with adoptopenjdk8 as the brew package name

---

osquery/carver/carver.cpp
osquery/filesystem/linux/proc.h
osquery/tables/networking/darwin/routes.cpp
osquery/tables/networking/posix/interfaces.cpp
osquery/tables/system/darwin/processes.cpp
osquery/tables/system/darwin/smc_keys.cpp
osquery/tables/system/efi_misc.h
osquery/utils/schemer/json/schemer_json.h
osquery/utils/schemer/json/schemer_json_impl.h
osquery/utils/schemer/json/tests/schemer_json.cpp
osquery/utils/system/linux/ebpf/perf_output.h
osquery/utils/system/linux/ebpf/perf_output_impl.h
plugins/logger/tests/tls_logger_tests.cpp

Work in progress to fix the bugs reported by Asan, as initially reported by #5628.
Some of them will probably require a refactor of the publisher/subscriber framework though, so we need to decide what to do with them and when to actually enable Asan in the CI builds.
This PR temporarily enable Asan which will be removed when before merging.

Fix bugs reported by asan

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/ibridge.cpp
specs/BUCK
specs/CMakeLists.txt
specs/darwin/ibridge.table
specs/darwin/ibridge_info.table
tests/integration/tables/BUCK
tests/integration/tables/CMakeLists.txt
tests/integration/tables/ibridge.cpp

Previous discussion in #5203 and #5166 
This add `ibridge` table in macOS to report on T1/T2 SOC (currently notebooks only).
Here is the output:
```
osquery> .all ibridge;
boot_uuid = B8EC353D-74E5-3437-B580-531F5D952DF3
coprocessor_version = Apple T1 Chip
firmware_version = 14Y904
unique_chip_id = 854183246450470
```
Tests pass:
```
90: [----------] 1 test from IBridgeTest
90: [ RUN      ] IBridgeTest.test_sanity
90: [       OK ] IBridgeTest.test_sanity (1 ms)
90: [----------] 1 test from IBridgeTest (1 ms total)
```
Tested with both CMake and Buck on macOS 10.13 and 10.14
Ideally we would want to report everything reported by `/usr/libexec/remotectl dumpstate`, but because of private APIs/frameworks and entitlements that is not going be possible/easy now.

tables: implement ibridge table to report on T1/T2 chip for mac notebooks

---

packs/osx-attacks.conf

Continuing https://github.com/osquery/osquery/pull/5407...
New OSX malware can be easily detected with osquery and it is consistent with other entries in the `osx-attacks` pack. More details can be found [here](https://blog.malwarebytes.com/threat-analysis/2018/10/mac-malware-intercepts-encrypted-web-traffic-for-ad-injection/).
File artifacts are:
* `/Applications/spi.app`
* `~/Library/LaunchAgents/spid-uninstall.plist`
* `~/Library/LaunchAgents/spid.plist`
* `~/Library/SPI`

Adding OSX Malware SearchAwesome to osx-attacks

---

docs/wiki/development/building.md

In response to @theopolis's invitation to contribute edits to the ReadTheDocs documentation, I've tested the build steps in the build guide by running CMake builds on macOS 10.14, Windows 10, and Ubuntu Linux 18.04. Then I made some minor improvements to the build instructions based on this. They are accurate to the `thirdparty-submodules` development branch, as well.
This is related to issue #5688.

Make improvements to the build guide

---

README.md
docs/wiki/index.md

The email in the wiki is no longer relevant. It does not make sense to have an email for a "more help" method either. Folks should be directed to Slack.
The build guide on the README is a broken link that should point to ReadTheDocs.

docs: Update README to correct email and build guide

---

osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/process_events.h
osquery/tables/events/linux/process_events.cpp
osquery/tables/events/linux/process_events.h
osquery/tables/events/tests/CMakeLists.txt
osquery/tables/events/tests/linux/process_events_tests.cpp
specs/posix/process_events.table

Audit: Implement support for fork/vfork/clone/execveat

---

osquery/tables/events/CMakeLists.txt

The test was built but wasn't running with the other tests.

Add audit processeventstests-test to the running tests

---

plugins/config/parsers/views.cpp

Added flag to check if the views config is updated the first time, and if query already exists in the local db store, then all we need to do is create the view.
I don't understand why the views are stored in the local db, but have left those as is, and remedied only the issue.
Issue: https://github.com/osquery/osquery/issues/5315
Previous pull request for same change, which was discarded - https://github.com/osquery/osquery/pull/5317

Fix for #5315. Ensure view recreated on startup.

---

tools/deployment/make_windows_package.ps1

Related to https://github.com/osquery/osquery/issues/5586 but I would appreciate @muffins review on my proposed fix. It builds the working MSI package for me now when run from the source directory and pointed at the build directory (CMake).

Fix bugs and update pathname variables in MSI package build script

---

osquery/tables/system/windows/certificates.cpp

This resolves #5104
The way I implemented this was to reverse the iterators that index the bytes, rather than reversing the resulting hexadecimal string. I believe this is a fast and correct way to do it, but let me know what you think.

Fix the reading of a certificate's serial

---

azure-pipelines.yml

Use the new CacheBeta task to cache and restore the ccache
directory, which greatly improves build times.
The cache is saved only if the job ends with success.
A pipeline variable CacheVersion present in the cache key
is used to invalidate all old caches if such a need arises.

Implement caching on the CI

---

osquery/tables/cloud/ec2_instance_tags.cpp
osquery/utils/aws/aws_util.h
plugins/logger/aws_log_forwarder.h

Attempting to include the ec2-instance-tags on windows will error out, apparently, this is due to a known issue https://github.com/aws/aws-sdk-cpp/issues/402 with the C++ AWS SDK, fix successfully compiles.

Fix optional AWS table compilation on Windows

---

cmake/flags.cmake

Full RELRO is a useful exploit mitigation which disables lazy
binding of functions, makes the GOT read-only and also reorders the ELF sections so
that a buffer overflow cannot easily overwrite the next ones, where
normally the GOT is.

Link binaries with Full RELRO on Linux

---

CMakeLists.txt
azure-pipelines.yml
cmake/flags.cmake
cmake/toolchain.cmake
docs/wiki/development/building.md
libraries/cmake/formula/modules/utils.cmake
libraries/cmake/formula/openssl/CMakeLists.txt
libraries/cmake/source/boost/CMakeLists.txt
libraries/cmake/source/librpm/config/config.h

- Always link to libc++abi.a, dl and rt
- Add OSQUERY_TOOLCHAIN_SYSROOT option which should contain
the path to the sysroot where the portable compiler and its libraries are in.
- Fix OpenSSL build with custom toolchain
- Always include the custom toolchain cmake.
Unfortunately system name detection is done when project() is called
which is also when compiler detection is done, and we need the compiler
to be set before that, so we always include the cmake file.
- Do not use getrandom syscall in Boost, for glibc < 2.25 support.
- Remove usage of secure_getenv and getauxval in librpm.
- Update CI to use the toolchain.
- Reflect changes in the docs.

Linux custom toolchain integration

---

osquery/tables/system/windows/programs.cpp

We see a lot of empty rows in the program table. Don't return an empty row.

Don't return nil rows for the programs table

---

cmake/packaging.cmake

We used to provide basic tarballs for Linux flavors that do not support DEB or RPMs.

cpack: Add TGZ optional generator for Linux

---

osquery/utils/aws/aws_util.h

The preprocessor logic here is incorrect and produces a warning for most builds.

aws: Fix preprocessor define check

---

cmake/packaging.cmake

This is the first part of checking package consistencies. The goal is to make upgrading from version 3.x to 4.x as simple as possible. I am trying to document the inconsistencies I found in https://github.com/osquery/osquery/issues/5769.

cpack: Apply existing Linux package conventions

---

osquery/tables/system/windows/intel_me.cpp

This PR implements a more correct query protocol for communicating with the driver. Due to this, the patch will also fix compatibility issues with older Windows versions (< 10).
EDIT: I made a lot of guessing and many tests to get this to work. It is working fine on my machines, but it would be nice if someone could compile this patch and test it. Thanks!
EDIT 2: This should fix issue #3247 
```
PS C:\Users\Claudio\Desktop> .\osqueryi.exe --verbose
I0227 19:31:33.643203  6752 init.cpp:416] osquery initialized [version=2.5.3-954-g3701ecae]
I0227 19:31:33.643203  6752 extensions.cpp:343] Could not autoload extensions: Failed reading: \ProgramData\osquery\extensions.load
I0227 19:31:33.653203  6752 database.cpp:563] Checking database version for migration
I0227 19:31:33.653203  6752 …
```

Intel ME table refactor

---

libraries/cmake/source/thrift/patches/src/ignore_eintr.patch

libraries: Add patch to thrift to ignore EINTR

---

azure-pipelines.yml
libraries/cmake/formula/openssl/CMakeLists.txt

OpenSSL should use the ar binary provided by the custom toolchain.
Also updated the docker image to avoid installing binutils
and hiding the issue.

Fix OpenSSL build when no system ar is installed

---

tools/release/new_release.sh

We use this tool to generate a PR to the website. However, the download links are broken. This is because they need `platform` and not `url`. The history behind this can be seen in https://github.com/osquery/osquery-site/pull/88
Relates to: https://github.com/osquery/osquery-site/pull/148

Fix the website download link schemas

---

cmake/flags.cmake

These warnings consumed a significant amount of the compilation output and did not serve a useful purpose.

Suppress Boost warnings about newer compiler

---

cmake/wix_patches/osquery_wix_patch.xml

When ErrorControl is set to `critical`, a failure to start osquery results in a system reboot. Instead, this should be set to `normal` where it is logged and the startup proceeds.
Upstream docs are Docs are http://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceinstall.html
This was fixed in https://github.com/osquery/osquery/pull/5467 and seems to have gotten lost.

Fix MSI Service Error handling

---

tools/deployment/make_osx_package.sh

Reverts osquery/osquery#5808
I'd prefer to keep this script around until we are confident that CPack is the way to go for macOS package building. I have concerns about https://github.com/osquery/osquery/pull/5777 and the inability to set the correct `package_id`.

Revert "Remove deprecated macOS package generator"

---

Vagrantfile
docs/wiki/development/building.md

- Remove Vagrant boxes provided by individual users and not well-known organizations.
- Use osquery/aws-dummy box for AWS support.
- Fix AWS startup when used without VPC and subnet.

Prune Vagrant boxes and fix AWS support

---

tools/formatting/format-check.py

I was curious why recent diffs were not causing a CI build failure when the code was not formatted.

format: Fix auto-formatting and format checking

---

osquery/main/main.cpp
osquery/main/windows/main.cpp

Build the binaries, run with `--install`, and verify that the paths are wrapped with quotes:
```
PS C:\Users\Nicholas\work\repos\osquery\build\windows10> .\osquery\Release\osqueryd.exe --install                                                        I0921 14:37:53.569830  7568 main.cpp:160] osqueryd service was installed successfully.
PS C:\Users\Nicholas\work\repos\osquery\build\windows10> sc.exe qc osqueryd                                                                              [SC] QueryServiceConfig SUCCESS
SERVICE_NAME: osqueryd
TYPE               : 10  WIN32_OWN_PROCESS
START_TYPE         : 2   AUTO_START
ERROR_CONTROL      : 1   NORMAL
BINARY_PATH_NAME   : "C:\Users\Nicholas\work\repos\osquery\build\windows10\osquery\Release\osqueryd.exe" --flagfile="\Program …
```

deploy: updating osquery --install to wrap binary path and flagfile

---

cmake/utilities.cmake

The script would not find clang-format or it would use the system one,
which it shouldn't.

Specify PATH when calling format_check if using the custom toolchain

---

cmake/flags.cmake

This is a nice-to-have and helps with building debug packages.

linux: Add --build-id linker option

---

tools/deployment/make_osx_package.sh

Example test plan:
```
$ ./tools/deployment/make_osx_package1.sh 
[+] using /vagrant/tools/deployment/com.facebook.osqueryd.plist as the launchd source
[+] copying osquery binaries into /vagrant/tools/deployment/../../build/_packaging/prefix
[+] copying osquery configurations
[+] finalizing preinstall and postinstall scripts
[+] creating package
[+] package created at /vagrant/tools/deployment/../../build/osquery-4.0.2-7-g33f7c6fc.pkg
[+] creating debug package
[+] package created at /vagrant/tools/deployment/../../build/osquery-debug-4.0.2-7-g33f7c6fc.pkg
```

packaging: Fix up make_osx_package to work for version 4+

---

azure-pipelines.yml
tools/formatting/format-test.sh

The test modifies the source code, appending "\n\n" at the end of each .cpp files.
Then runs the format_check target and verifies if the list of files to be formatted,
identified by the script, are the same ones previously modified.
Right now the test will fail because the PR depends on #5834 being merged.
I'll rebase the PR when that will happen.

Add a test for the format_check script

---

tools/deployment/getfiles.py
tools/deployment/make_linux_package.sh

This is a fix for #5779 
The python script `getfiles.py` is being used to collect the names of all source files which is passed back into `make_linux_package.sh` for collection. The python script removed the base of the path which was re-prepended in the bash script. This would be an issue for symlinks which would be evaluated in python.

Fix make rpm script to not break because of symlinks

---

plugins/database/CMakeLists.txt
plugins/database/tests/BUCK
plugins/database/tests/rocksdb.cpp
plugins/database/tests/utils.cpp
plugins/database/tests/utils.h

Not sure why this was disabled. If it was enabled we would have had less breakage in 4.0.1.

tests: Enable RocksDB plugin tests

---

azure-pipelines.yml

~~We'll want to revisit this in the near future, but for now the CI is broken due to `ant` and `bcel` being removed from Apache's mirrors.~~
Edit: This adds a `brew update` to the macOS Buck job.

azure/macos: Fix for brew/ant install failing

---

libraries/cmake/source/googletest/CMakeLists.txt
libraries/cmake/source/libudev/CMakeLists.txt
libraries/cmake/source/modules/Findgoogletest.cmake
libraries/cmake/source/modules/Findlibudev.cmake
libraries/cmake/source/modules/Findthrift.cmake
libraries/cmake/source/modules/Findutil-linux.cmake
libraries/cmake/source/modules/utils.cmake
libraries/cmake/source/thrift/CMakeLists.txt
libraries/cmake/source/util-linux/CMakeLists.txt

Keep patched source in the build directory instead of the source.
A new variable with the format OSQUERY_<submodule name>_ROOT_DIR
is set to the directory of where the submodule is, in case it's patched.
A new option PATCH has been added to importSourceModule
to let the patching system know that the submodule has to be patched
and which is the main submodule folder.

CMake: Improve submodule patching system

---

osquery/events/events.cpp
osquery/include/osquery/events.h

I noticed `osquery_events_tests_inotifytests-test` is a flaky test because of `getEventSubscriber`:
```cpp
if (!exists(name_id)) {
LOG(ERROR) << "Requested unknown event subscriber: " + name_id;
return nullptr;
}
return ef.event_subs_.at(name_id);
```
This is an unprotected race condition and one (of few) callsite is within `EventPublisher::fire`. This test exercises the race because it may remove the specific event subscriber before all inotify events have been serviced. Thus the `exists` works and the `at` throws.
There are two options IMO to address the issue:
- Add a lock (which means an embedded ReadLock within a same-thread's WriteLock)
- Refactor to include a `getEventSubscriberUnsafe` that does not lock and keep one that waterfalls, which does.
The first option requires a …

bug: Use RecursiveMutex and read locking on getEventSubscriber

---

azure-pipelines.yml

Buck compiles tests in Debug mode even if supposedly told otherwise,
this exhausts disk space available on the CI and makes the step always fail.

Temporarily disable Buck tests on Linux

---

osquery/tables/networking/BUCK
osquery/tables/networking/CMakeLists.txt
osquery/tables/networking/windows/connectivity.cpp
specs/BUCK
specs/CMakeLists.txt
specs/windows/connectivity.table
tests/integration/tables/BUCK
tests/integration/tables/CMakeLists.txt
tests/integration/tables/connectivity.cpp

Introduces the `connectivity` table, which contains the current system-wide (i.e., all interface) network state:
```
osquery> select * from connectivity;
+--------------+-----------------+-----------------+-------------+--------------------+---------------+-------------+--------------------+---------------+
| disconnected | ipv4_no_traffic | ipv6_no_traffic | ipv4_subnet | ipv4_local_network | ipv4_internet | ipv6_subnet | ipv6_local_network | ipv6_internet |
+--------------+-----------------+-----------------+-------------+--------------------+---------------+-------------+--------------------+---------------+
| 0            | 0               | 1               | 0           | 0                  | 1             | 0           | 0                  | 0             | …
```

(Windows) New table: connectivity

---

osquery/core/init.cpp
osquery/extensions/extensions.cpp
osquery/extensions/tests/extensions.cpp

Change the message that is logged when a required extension is not
loaded or found from "Extension not autoloaded: <extension id>" to
"Required extension not found or not loaded: <extension id>".
Change the message that is logged when the extension manager have an
error happening during startup from "Cannot start extension manager:
<error>" to "An error occured during extension manager startup: <error>"
Add the possibility of startExtensionManager returning with an error
if the Dispatcher failed to properly add the ExtensionManagerWatcher
or ExtensionManagerRunner.
Fallback to logging the startExtensionManager error message with a
serverity of INFO only if extensions are required to be disabled.
Add tests for starting the extension manager with a nonexistent
socket path and a nonexistent …

Improve error reporting from extension manager

---

tests/integration/tables/npm_packages.cpp

Creates sanity check for the table `npm_packages`.
#4942

[Table sanity check] npm_packages

---

libraries/CMakeLists.txt

- Reorder `add_library(osquery_thirdparty_extra_c_settings INTERFACE)`
for consistency
- Use correct target link library in osquery_thirdparty_extra_*_settings

Fix thirdparty_*_settings target_link_libraries

---

libraries/cmake/source/modules/utils.cmake

During the first configuration, the git command is searched
when submodules are initialized and it's then saved into a cache variable.
If though we delete the build folder and run configure again,
the submodules won't be initialized again, so the git command
won't be cached and visible to CMake.
Therefore we need to search for it each time.
Cleanup dead/deprecated code.

Fix git command not found after first configure

---

osquery/registry/registry_interface.cpp

PR osquery/osquery#5464 makes it impossible to call plugins
which are only registered in the core, as its happening with osquery/osquery#5839.
What happens when this is working is that the filesystem plugin is not present
in the extension registry, so when Registry::call tries to search for a plugin
that provides the "config" feature, it won't find one and the resulting plugin name,
and later item_name, will be empty.
This results in the RegistryInterface::call reroute the call to the core,
through Thrift, which will end up in the plugin correctly answering.
It's not clear though what issue exactly PR osquery/osquery#5464 was trying to solve (do we have any way to know more about it?).
At the same time it's indeed not clear why an empty item_name is accepted and why the extension registry …

Fix regression in calling core only plugins from extensions

---

osquery/utils/conversions/tryto.cpp

Previously the `osqueryi` shell supported `ON` or `OFF` as valid boolean toggles for various shell functions like `timer` or `echo`.
Currently trying to use these functions causes an error, even though the help message indicates that it is supported.
```
➜ ./osqueryd -S
osquery> .echo on
ERROR: Not a boolean value: "on". Assuming "no".
osquery> .timer on
ERROR: Not a boolean value: "on". Assuming "no".
osquery> .help
Welcome to the osquery shell. Please explore your OS!
You are connected to a transient 'in-memory' virtual database.
.bail ON|OFF     Stop after hitting an error
.echo ON|OFF     Turn command echo on or off
.timer ON|OFF    Turn the CPU timer measurement on or off
```
This small PR restores the original functionality.

[shell] support previously supported on|off toggle for osqueryi shell functions

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/windows/default_environment.cpp
specs/BUCK
specs/CMakeLists.txt
specs/windows/default_environment.table
tests/integration/tables/BUCK
tests/integration/tables/CMakeLists.txt
tests/integration/tables/default_environment.cpp

Adds the `default_environment` table, which contains rows of default environment variables added to each process on initialization by Windows.
This table proxies and extrapolates its contents from the `registry` table.

(Windows) New table: default_environment

---

osquery/tables/system/windows/os_version.cpp

Summary:
This addresses Issue #4080 by removing the `code_name` column on Windows whole-sale, and replacing it's contents with that of the `name` column. See the discussion in #4080 for additional details. 
Test Plan:
Ran on Windows 10:
```
PS C:\Users\Nicholas\work\repos\osquery\build\windows10> .\osquery\RelWithDebInfo\osqueryd.exe -S                                                                 Using a [1mvirtual database[0m. Need help, type '.help'
osquery> select * from os_version;
+--------------------------+------------+-------+-------+-------+-------+----------+---------------+--------------------------+---------------------------+
| name                     | version    | major | minor | patch | build | platform | platform_like | codename                 | install_date …
```

tables: update Windows codename column to be that of name

---

osquery/tables/system/darwin/keychain_items.cpp
tests/integration/tables/keychain_items.cpp

This adds a sanity test for the macOS keychain table. Running this test exposed an issue which was causing a number of blank rows to be returned at the end of the table. An additional patch avoids this issue by adding some more error checking to the keychain APIs used and allows the test to pass.
This PR is intended to close issue #5021

macOS keychain sanity test

---

azure-pipelines.yml
libraries/cmake/source/modules/Findlibcryptsetup.cmake
libraries/cmake/source/modules/Findlibgcrypt.cmake
libraries/cmake/source/modules/Findlibgpg-error.cmake
libraries/cmake/source/modules/utils.cmake

Enables the v2 protocol which allows the repositories to be shallow
cloned without error.

Fix shallow clone support for libraries in recent git versions

---

CMakeLists.txt
libraries/cmake/source/modules/utils.cmake

Instead of moving a patched submodule from source to build directory,
we copy it and then hard reset the submodule to its original HEAD.
Minor message change when a library fails to be imported.

Support source and build directory to be on different filesystems

---

.gitignore
CMakeLists.txt
external/CMakeLists.txt
external/cmake/cmakelibs.cmake
libraries/cmake/source/boost/CMakeLists.txt
libraries/cmake/source/modules/Findboost.cmake
tools/codegen/templates/osquery_extension_group_main.cpp.in

Restore the extension SDK support which was lost during refactoring. The changes include the CMake library functions and external directory for the extension source code.  
It also updates the library descriptor list for the boost. The changes follow the external extensions build process as documented.
https://osquery.readthedocs.io/en/stable/development/osquery-sdk/

Restore extension SDK support to osquery 4.x

---

osquery/utils/json/json.h
osquery/utils/json/tests/json.cpp

If osquery reads a user-controlled JSON it has the potential of overflowing the stack, exhausting stack memory due to recursing and allocating too many frames.

json: Configure rapidjson to use iterative parsing

---

tools/deployment/make_linux_package.sh

Example test plan:
```
» ./tools/deployment/make_linux_package.sh -b ./build -t rpm                                        
[+] copying osquery binaries to ./build/_packaging/prefix
[+] copying osquery configurations to ./build/_packaging/prefix
[+] copying built-in tls server certs file into ./build/_packaging/prefix/usr/share/osquery/certs/certs.pem
[+] copying osquery init scripts into ./build/_packaging/prefix
[+] creating rpm package
Created package {:path=>"/home/teddy/git/osquery-prod/build/osquery-4.0.2_7_gfadcfbca-1.linux.x86_64.rpm"}
[+] package created at /home/teddy/git/osquery-prod/build/osquery-4.0.2_7_gfadcfbca-1.linux.x86_64.rpm
Created package {:path=>"/home/teddy/git/osquery-prod/build/osquery-debuginfo-4.0.2_7_gfadcfbca-1.linux.x86_64.rpm"}
[+] debug created at …
```

packaging: Fix up make_linux_package to work for version 4+

---

osquery/sql/sqlite_util.cpp

There is a memory leak when a SQL statement is evaluated and returns an error while stepping. An example includes returning `sqlite3_result_error` from `regexStringMatchFunc`. The root cause is not finalizing a prepared statement.
This was found while testing #5910.

leak: Fix memory leak when SQL query fails

---

tests/integration/tables/nvram.cpp

Add a simple sanity test for macOS nvram.
Closes: #5019

tests: Add sanity test for nvram

---

CONTRIBUTING.md
docs/wiki/development/building.md

The goal of this PR is to improve the experience for new users. It assumes that `CONTRIBUTING.md` is the first document they read. This means it should link to documentation on how to build and test osquery as well as define terms as best as possible.

docs: Nitpicks to improve new-user experience

---

libraries/cmake/source/modules/Findrapidjson.cmake

With a small JSON input testcase, you can cause a wild read.
```json
0.0000074836628E-2147483636
```
```
./osquery/main/harnesses/osqueryfuzz-config /tmp/fuzz/clusterfuzz-testcase-minimized-osqueryfuzz-config-5751874325577728
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1020 15:48:17.027545  6973 database.cpp:77] Failed to activate database plugin "rocksdb": Cannot read RocksDB path: /var/osquery/osquery.db
INFO: Seed: 3643951471
INFO: Loaded 1 modules   (483657 inline 8-bit counters): 483657 [0x4953228, 0x49c9371), 
INFO: Loaded 1 PC tables (483657 PCs): 483657 [0x49c9378,0x512a808), 
./osquery/main/harnesses/osqueryfuzz-config: Running 1 inputs 1 time(s) each.
Running: /tmp/fuzz/clusterfuzz-testcase-minimized-osqueryfuzz-config-5751874325577728 …
```

libraries: Update RapidJSON to master 1a825d24

---

osquery/tables/utility/osquery.cpp
osquery/utils/info/platform_type.h
specs/utility/osquery_info.table

Right now, there is no way to tell what platform osquery is running on. We have `os_version.platform` and `os_version.platform_like`, but they are highly inconsistent, and require a lot of custom parsing to use. We should expose the underlying platform bitmask.
This adds the `platform_mask` to the `osquery_info` table.
This replaces https://github.com/osquery/osquery/pull/5488 Contrasting the approaches, I think the I like #5488 more. Exposing the booleans is a better API. This is useful, and better than status quo, but it means we're committing to not changing the bitmask fields

Add platform_mask

---

osquery/include/osquery/sql.h
osquery/sql/sql.cpp

The value_max flag is not needed, as described in #5705. @zwass @theopolis
Fixes https://github.com/osquery/osquery/issues/5705

remove the value_max flag

---

osquery/sql/tests/virtual_table.cpp
osquery/sql/virtual_table.cpp

Attempt to port fix for 5379 to new branch.  Some changes I noticed from v3.3.1 branch:
- now that there's a colsUsedBitset
- loop to fill colsUsed set<string> is considering aliases

Fix WHERE in(N items) results in table query running N times

---

osquery/include/osquery/registry_interface.h
osquery/registry/registry_interface.cpp

Several methods in the `RegistryInterface` class are reading and/or modifying member variables without locks. I've seen the `osqueryd --S` process terminate abnormally from this, and after debugging, the `RegistryInterface::remove` method was the culprit (more precisely `items_.erase(item_name)`).
This PR adds locks to the remaining methods in the class that read and/or modify member variables.

RegistryInterface: add locks to more methods

---

tests/integration/tables/interface_addresses.cpp

On macOS it is possible to have interfaces that have no netmask
set, for example:
| utun1 | 100.xx.xx.xx | | | 100.xx.xx.xx     | unknown |
This causes the interfaces test to fail. This change allows the
mask field to be blank and the test to pass on systems with this
type of interface configured.
The sockaddr for this interface has an ifa_netmask with sa_family
set to zero (AF_UNSPEC) which causes getnameinfo(3) to fail.
ifconfig does return a netmask for this interface but it's not
clear if the value is at all meaningful.

tests: Increase reliability of interfaces test

---

tools/harnesses/osqueryfuzz_config_corpus.sh
tools/harnesses/osqueryfuzz_config_dict.sh

This is partly a straw-man PR.  
The dictionary should list keywords for the config file. Rather than make a hard-coded list that will eventually get out of date, I grab them from the sample config files and from keywords inside HasMember() in the source code.
The seed corpus is a set of interesting config files for the fuzzer to start with. Again, I grab the sample config files.
I'd love more/better suggestions for how to identify config keywords in the codebase; or config files that are interesting but not represented in the existing test configs.
If these techniques are decent; but some hardcoded suggestions are also valuable, we can add them into the script (for the dict) or in a sub-directory of harnesses (for seed files).
Finally, if no one has any ideas, we can always add these to …

Add scripts to generate a dictionary and seed corpus for the config fuzzing

---

osquery/core/init.cpp
osquery/examples/example_extension.cpp
osquery/examples/example_writable_table.cpp
osquery/include/osquery/system.h
osquery/main/main.cpp

When a thread different from the main requests a shutdown
through Initializer::requestShutdown, it should not call
waitForShutdown; there's no reason to wait, moreover the function
doesn't only wait, but also actually stops other components and then
finally calls exit().
Since the main thread is already inside the waitForShutdown call
waiting on Dispatcher::joinServices or inside the shutdown() callable
on Windows, having a secondary thread do
the same work potentially at the same time is wrong.
Moreover calling exit() from a secondary thread is most of the time
incorrect.
The waitForShutdown function has been renamed to waitThenShutdown
to better represent what it's actually doing.

Fix a race condition during the shutdown of the worker process

---

tests/integration/tables/certificates.cpp

Summary:
We already have some tests for the `certificates` table on Windows, but this ungates the sanity tests for macos and Windows to ensure schema validation for this table.
Test Plan: run the tests:
```
PS C:\Users\Nicholas\work\repos\osquery\build\windows10> cmake --build . --config RelWithDebInfo -j10 --target run_tests         Microsoft (R) Build Engine version 16.3.1+1def00d3d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
Test project C:/Users/Nicholas/work/repos/osquery/build/windows10
Start  1: osquery_dispatcher_tests-test
1/69 Test  #1: osquery_dispatcher_tests-test .................................   Passed    0.03 sec
Start  2: osquery_dispatcher_tests_scheduler-test
2/69 Test  #2: osquery_dispatcher_tests_scheduler-test ....................... …
```

tests: enabling certificates table sanity checks

---

osquery/remote/http_client.cpp
osquery/remote/http_client.h
osquery/remote/transports/tls.cpp
osquery/remote/transports/tls.h

This is a quick review of the HTTP Client class. I noticed the Options
comparison does not include all members. The namespace alias seemed
unneeded so I removed boost_system and boost_asio.

http: Minor fixups to Client

---

docs/wiki/installation/cli-flags.md
plugins/logger/tls_logger.cpp

Multiple flags are moved from `FLAG` to `CLI_FLAG` due to the way they are implemented/used in code. If they were `FLAG`(s), meaning if they were also configurable via configuration at runtime, the new values would still be ignored.
These are:
- `logger_tls_endpoint`
- `logger_tls_period`
- `logger_tls_max`
The flag `logger_tls_max` has been renamed to `logger_tls_max_linesize` and an alias is added for compatibility.
A new flag is added, `logger_tls_max_lines`, to expose a previously hardcoded value of 1024 for the maximum number of log lines to send every period.

logger: Expose max_lines and correct flag types

---

osquery/utils/json/tests/json.cpp
third-party/rapidjson/BUCK
third-party/rapidjson/osquery.library

There is a bug in RapidJSON 1.1.0 that results in wild pointer reads when parsing exponents. We want to prevent regressing.
This requires updating the Buck/pre-built libraries.

tests: Add test for JSON exponent parsing

---

plugins/logger/tls_logger.cpp

This is a follow up to #5956, which reverts the CLI_FLAG changes.

logger: Restore TLS logger runtime flags

---

tools/harnesses/osqueryfuzz_config_dict.sh

Not the greatest look; I missed the companion script.

 Update osqueryfuzz_config_dict.sh to correct the paths to the tests and packs directories

---

tests/integration/tables/etc_protocols.cpp

In the etc_protocols test, the `alias` field in the etc_protocols table was not  allowed to be empty, this caused the test on some machine to fail as  described in #5805. Now it's allowed to be empty.

improve etc_protocols test

---

azure-pipelines.yml

Some Agents configuration is being updated and the default Xcode version is now 11.1 which we don't support yet.

Explicitly select Xcode version 10.3 in azure-pipelines.yml

---

osquery/tables/events/windows/powershell_events.cpp
plugins/config/parsers/feature_vectors.cpp

This fixes #5929.
I am not sure what this functionality provides and it is not tested. 
But this PR adds basic checks for the expectations for the format of the configuration JSON.

powershell/config: Add checks for character_frequencies

---

osquery/events/linux/auditdnetlink.cpp

Read the analysis within #5952.
There are multiple sources suggesting an optimal value is 0. Our implementation previously hardcoded the value to 1. It is now 0 and can be configured to a different value using the `audit_backlog_wait_time` option or command line flag.

audit: Allow configuring audit_backlog_wait_time

---

osquery/remote/http_client.cpp

Wait for https://github.com/osquery/osquery/pull/5946 to be reviewed and merged.
When testing on IPv6-only hosts, with an IPv4 lo stack, the resolver may not return an IPv4 address. This seems to be an issue with the deprecated overload of async_resolve. Upon inspection, the previous overload would only return 1 result_type.
Migrating to the recommended overload works as expected.
This was referenced in the issue #5883.

http: Move away from deprecated async_resolve overload

---

external/CMakeLists.txt
external/cmake/cmakelibs.cmake

- Link libraries and set compiler flags as PRIVATE on an executable.
- Define common extension options in the exernal/CMakeLists.txt,
using the external_options target.
- Uniform library linked by a single extension and an extension group.
- Remove thirdparty_boost since it's redundant and already brought in by thrift.
- Remove unused addOsqueryModule.

CMake: Improvements to extensions support

---

osquery/tables/networking/windows/process_open_sockets.cpp
specs/process_open_sockets.table

On Windows, the `process_open_sockets` table was missing the `state` column, so I added it for TCP connections.

process_open_sockets/windows: add state column

---

tests/integration/tables/deb_packages.cpp

@Smjert  The deb_packages test fails on some systems as described in #5917. This PR improves the reliability of this test.

improve deb_packages test

---

.github/ISSUE_TEMPLATE/New_Release.md

I find myself often wanting a documented TODO for release time.

Add New_Release GitHub issue template

---

osquery/events/linux/auditdnetlink.cpp

Fix for issue #5931 (--audit_force_reconfigure can stall linux system services.)

Prevent Audit from stalling Linux system services

---

docs/wiki/development/building.md

Passing the generator is needed because one can have
multiple installations of Visual Studio and Build Tools.
Moreover the documentation is written for Visual Studio 2019 and
the subsequent arguments passed to CMake are not fully valid for
earlier versions.

Restore specific Visual Studio generator selection in building.md

---

osquery/database/database.cpp

Migrating the database is a rare event. When it does happen it is important to know if there were errors. The successes are not informationally relevant.

database: Remove INFO logs for migration successes

---

cmake/flags.cmake
libraries/cmake/formula/openssl/CMakeLists.txt

- Remove the /EHsc compiler flag from the default flags
coming from CMake. Boost coroutine needs /EHs and
passing that after /EHsc does not override it.
- Remove other flags from the default ones,
to avoid the "overriding" warning.
- Give a suggested path to find Perl using CMAKE_PREFIX_PATH.
- openssl Makefile needs Perl to be passed explicitly through
the PERL variable, otherwise it won't properly find it.
Enables https://github.com/osquery/osquery/issues/5968

Fix build with Ninja on Windows

---

cmake/utilities.cmake
tools/osquery.manifest.in

This uniforms the manifest that gets embedded using msbuild
or Ninja, while also letting us customize it if necessary.
Depends on https://github.com/osquery/osquery/pull/6007 to test with Ninja.

Use a custom defined manifest for executables on Windows

---

docs/wiki/installation/cli-flags.md
osquery/dispatcher/scheduler.cpp

Just a nitpick on the length of the flag description.

docs: Move the schedule_max_drift description into docs

---

osquery/utils/conversions/BUCK
osquery/utils/conversions/CMakeLists.txt
osquery/utils/conversions/windows/strings.cpp

Reproduce what we already have in osquery/logger.h,
since we are compiling everything static.
Reduce warnings about locally defined and imported symbols.

Do not use dllimport in glog on Windows

---

tools/codegen/templates/osquery_extension_group_main.cpp.in

Use function `waitThenShutdown` to wait for the shutdown signal/interrupt before exiting. The function has been renamed after the 4.0.2 release.

Use function `waitThenShutdown` to wait for the shutdown signal

---

libraries/cmake/source_migration/modules/Findgflags.cmake
libraries/cmake/source_migration/modules/Findglog.cmake
osquery/logger/logger.h

Note that glog and gflags must be migrated at the same time, otherwise
linker errors are generated on macOS.

Migrate glog and gflags to source build on macOS and Windows

---

docs/wiki/deployment/logging.md
docs/wiki/deployment/process-auditing.md
osquery/core/query.cpp
osquery/core/tests/query_tests.cpp
osquery/logger/tests/logger.cpp
osquery/sql/tests/sql_test_utils.cpp
plugins/config/parsers/tests/decorators_tests.cpp
plugins/logger/tests/filesystem_logger.cpp

This is an API change for the format of logged events. The top-level log field "logNumericsAsNumbers" was introduced to help migrate from string-encoded numerics to JSON numbers.
This change updates the field to be "numerics", updates the flag to conform to flag naming conventions, and documents the expectation.

logging: Change logNumericsAsNumbers to numerics and add docs

---

osquery/tables/yara/yara.cpp

Watchdog will kill the osquery process if the memory usage is too high for too long.  Doing a decent size yara scan will likely trigger watchdog.  The yara library makes use of malloc(), and it has been observed that calling free() will not necessarily free that memory if the malloc subsystem thinks it will just need to reallocate that memory again soon.  The memory allocation increases more gradually, it's more likely that malloc will return free() memory back to the system.  This fix has two parts:
- a 50 microsecond delay after a file scan to make memory spike more gradual.  It accounted for about 30% less memory profile over a large scan.
- call to malloc_trim() on Linux to ask for malloc to cleanup and return freed memory.

yara memory management

---

libraries/cmake/source/aws-sdk-cpp/CMakeLists.txt
osquery/tables/cloud/CMakeLists.txt
osquery/utils/aws/CMakeLists.txt
plugins/logger/CMakeLists.txt

While in the end the osqueryd binary will require almost all libraries
built and linked, having each intermediate library depend on the whole
set of AWS libraries might result in higher compiling time.
Especially since on some platforms not all libraries are used.
This should speed up the compilation speed on Windows.

Don't always link to all AWS libraries

---

tools/ci/scripts/install_openssl_formula_dependencies.ps1

Use a faster method to download and a faster method to
extract zip archives, when available.

Prefer 7zip when installing Strawberry Perl

---

docs/wiki/installation/cli-flags.md
osquery/core/tables.cpp
osquery/sql/virtual_table.cpp

@directionless and @terracatta found this issue with go-sdk extension in response to the recent INDEX enforcements fix.
This fix adds a compatibility flag that defaults to the old behavior of INDEX on all columns.
This only affects extension virtual tables, all built in tables have index constraints enforced.
From Slack:
```
When run with 4.0.2:
dover:simple-osquery-test-extension seph$ ./osqueryd-4.0.2 -S --allow-unsafe --extension /tmp/simple.ext 
osquery> select * from test_table where input = "sdf";
generate called
Starting on constraint #0 -- sdf
Done. Processed 1 constraints
+-------+-----+--------+
| input | num | output |
+-------+-----+--------+
| sdf   | 0   | sdf    |
+-------+-----+--------+
When run with 4.1.0: …
```

extensions compatibility : default columns to INDEX

---

azure-pipelines.yml
docs/wiki/development/building.md

This is an attempt to maintain backwards compatibility for macOS. We should not add this directly to CMake due to recommendations in the CMake documentation, but we can test older deployment targets and recommend it in documentation.
The most significant effect this has for compatibility is on compile-time linking. 
This addresses #5993.

docs: Recommend macOS 10.11 deployment target

---

osquery/extensions/extensions.cpp

I noticed the extensions socket is checked even when extensions are disabled.

extensions: Skip shell socket when extensions are disabled

---

osquery/tables/yara/yara_events.cpp

Fix use after move in YARAEventSubscriber::configure

---

osquery/tables/system/darwin/nvram.cpp
osquery/utils/conversions/darwin/cfdata.cpp
specs/darwin/nvram.table

This improves the `nvram` table to use optional `name` constraints as lookups for non-advertised NVRAM variables.
An example includes:
```sql
select name, type, value from nvram where
name = '94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy';
```
The result on my laptop:
```
+------------------------------------------------------------+--------+-------+
| name                                                       | type   | value |
+------------------------------------------------------------+--------+-------+
| 94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy | CFData | %02   |
+------------------------------------------------------------+--------+-------+
```

tables: Improve nvram to use input variable names

---

osquery/tables/applications/atom_packages.cpp
specs/atom_packages.table

This addresses #5933. It changes the table API to use common user-based calling conventions. This avoids adding user-enumeration directly in the table implementation.
Fixes: #5933

tables: Change atom_packages to use user constraints

---

osquery/tables/system/linux/deb_packages.cpp
tests/integration/tables/deb_packages.cpp
tests/integration/tables/helper.cpp

This fixes the flaky `deb_packages` integration test by improving the `dep_packages` table to return a 0-size if a meta-package has no installed-sized.

tables: Improve integration test debugging and deb_packages

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/tests/windows/windows_optional_features_tests.cpp
osquery/tables/system/windows/windows_optional_features.cpp
specs/windows/windows_optional_features.table

This virtual table maps to Windows WMI class Win32_OptionalFeatures, and can be used to query which windows features are enabled or disabled. For example, is SMB v1 enabled?
Also came in useful when trying to determine whether osquery was running on a server with a specific role.  For example, `SELECT * FROM windows_optional_features WHERE name='Dns-Server-Full-Role' AND statename='Enabled'`.
(This is rebased from old 5257 PR)

new windows_optional_features table

---

osquery/remote/http_client.cpp
osquery/tables/networking/curl.cpp

This should fix #6043, where I think the root cause is the URI parsing. If there is no protocol/host/port then the URI is parsed incorrectly. We missed this due to the rarity of relative-redirects and due to the HTTP client being difficult to test.
This also adds a max of 10 redirects before the client gives up.

http_client: Handle relative redirects

---

osquery/config/config.cpp
osquery/config/config.h
plugins/config/parsers/decorators.cpp
plugins/config/parsers/tests/options_tests.cpp

Fixes #6041.
This could use a test. The parser plugins should not be linked with the core config target (ideally) and thus a test "options" plugin can be registered and tested to run first.

parsers: Always apply the options parser first

---

osquery/main/harnesses/CMakeLists.txt
osquery/main/harnesses/fuzz_config.cpp
osquery/main/harnesses/fuzz_sqlquery.cpp
osquery/main/harnesses/fuzz_utils.cpp
osquery/main/harnesses/fuzz_utils.h

I wanted to reduce code-reuse and make new harnesses easy to add. Now this should be a line in CMake and a new harness source file with only the harness logic.

fuzzing: Minify logic required for new harnesses

---

cmake/utilities.cmake

We are not currently ready for Python 3.8,
so we prefer either the newest 3.7 or 3.6.

CMake: Prefer Python 3.7 then 3.6

---

azure-pipelines.yml

git on Windows supports cloning a repository with symlinks
without actually creating them; it will substitute them
with text files containing the target path.
This can potentially break the build of some of osquery
third party libraries.
Moreover this is the default on the CI,
which is different compared to the setup on local machines,
which means that it can hide other kind of issues.

Force git to create symlinks on the CI

---

osquery/main/main.cpp

* When calling osquery in interactive mode with a single query as argument `(osqueryd -S  "SELECT * FROM bogus_table;")` would exit with a 0 return code when expectation is an exit with a 1 return code
* This change adds the return code back to the requestShutdown call in startShell, which will allow exiting with the proper return codes, this error was reported by and will fix #5853

Added return code to requestShutdown call

---

cmake/globals.cmake
libraries/cmake/source/boost/CMakeLists.txt

This is needed by some third party libraries and
when using Ninja on Windows.
CMake complains that it cannot find the internal variable
for CMAKE_ASM_MASM_COMPILE_OBJECT otherwise.

CMake: explicitly enable ASM_MASM language on Windows

---

cmake/utilities.cmake

Removed the restriction for the Python version to be >= 3.6 but < 3.8.
Now it has to be >=3.5, lower versions are EOL.
Removed the search for Python2 too since nothing uses it anymore.
Fixes osquery/osquery#6079

CMake: Change Python version required to be at least 3.5

---

tools/codegen/amalgamate.py
tools/codegen/genapi.py
tools/codegen/genwebsitejson.py

In python 3, open was changed to enable universal newlines by default, and 'U' mode was deprecated.
This PR replaces instances of `open(filename, 'rU')` with `open(filename, 'r')` to remove the DeprecationWarning.
Example:
```
[100%] Generating amalgamation file for the native tables...
/home/user/src/github.com/osquery/osquery/tools/codegen/amalgamate.py:53: DeprecationWarning: 'U' mode is deprecated
with open(template, "rU") as fh:
```

Fix python3 deprecation warning

---

docs/wiki/development/building.md

- Remove Python 2 as a prerequisite
- Add missing instructions when install Git for Windows
- Correct and move the paragraph about symbolic links permission earlier.
The "Enable symbolic link" check available during the Git for Windows
installing procedure doesn't enable the policy, but instead asks git
to create real symlinks when cloning, which is still something
we want.

Update steps to install prerequisites on all platforms

---

cmake/packaging.cmake

We should avoid renaming files unless we have a migration/cleanup plan. For existing installations this can lead to having two LaunchDaemons installed. Those with tooling to modify LaunchDaemons will need to be notified. We should save these changes until a 5.0 release that includes guidance.

cpack: Revert renaming com.facebook.plist to com.osquery.plist

---

tools/deployment/osqueryd.service

This updates the systemd service to use the default `KillMode`, `control-group`. This is needed due to removing the custom `signal` handlers within the osquery watchdog process -- the watchdog had been propagating signals to the worker processes.
Fixes #6092.

linux: Update systemd service to use KillMode=control-group

---

specs/darwin/mdfind.table
tests/integration/tables/mdfind.cpp

This also improves the integration test for `mdfind` by using a `query`. We only expect this to work if Spotlight is enabled and running.
Fixes #6099.

tables: Fix mdfind table by requiring query

---

libraries/cmake/source/librdkafka/CMakeLists.txt
libraries/cmake/source/zstd/CMakeLists.txt

Both libraries use the xxhash library,
compiling its source files directly.
The version they use though it's different so to avoid the linker
resolve the collision by removing one of the two implementations,
we prefix the functions with the respective library name.
Moreover we make the xxhash API private, by declaring the static
so that any unused function is not included anymore in the binary
and only the used one are present.
As additional info:
This was the old state of affairs
```
$ nm osquery/osqueryd| grep XXH
00000000017e85b9 t XXH32
00000000017e916b t XXH32_canonicalFromHash
00000000017e8555 t XXH32_copyState
00000000017e89c6 t XXH32_createState
00000000017e8cf3 t XXH32_digest
00000000017e89f2 t XXH32_freeState
00000000017e91bd t XXH32_hashFromCanonical
00000000017e8a74 t …
```

Fix possible xxhash collision between zstd and rdkafka

---

docs/wiki/development/building.md

@muffins pointed out the ReadTheDocs site has broken MarkDown. We should also reference building the `package` target without Make.

docs: Fix custom package markdown

---

osquery/core/tables.cpp
osquery/sql/tests/virtual_table.cpp
tools/codegen/gentable.py

We do not need an explicit INDEX column for ADDITIONAL to work. If the ADDITIONAL option is set the constraint should be passed into the virtual table context.

tables: Remove INDEX requirement for ADDITIONAL option

---

tools/deployment/make_windows_package.ps1

Instead of using the path to an openssl provided cert bundle (which no
longer exists in recent installs of openssl from Chocolatey), use the
cert bundle already stored in the repo.
Fixes #6109

Use cert bundle in repo for make_windows_package script

---

cmake/CPackConfig.cmake.in
cmake/packaging.cmake

This fixes a regression between `make_linux_package.sh` and `CPack`'s logic. The post-install script will restart `osqueryd` when the package is updated.

cpack: Add RPM and DEB postinstall script

---

cmake/utilities.cmake
libraries/cmake/facebook/modules/api.cmake
tools/codegen/CMakeLists.txt
tools/tests/CMakeLists.txt

CMake 3.16 doesn't set Python3_EXECUTABLE as cache variable anymore,
it has changed to _Python3_EXECUTABLE which is for internal use.
The module returns Python3_EXECUTABLE as a local variable,
so we share that value through a new custom cache variable,
OSQUERY_PYTHON_EXECUTABLE.

CMake: Future proof Python finding mechanism

---

azure-pipelines.yml

This helps debugging issues that may arise
between different Azure Pipelines instances.

Print CMake version in the CI

---

tools/harnesses/osqueryfuzz_config_corpus.sh
tools/harnesses/osqueryfuzz_config_dict.sh

For a possibly longer-term solution, please look at https://github.com/osquery/osquery/issues/6131

Fix regression in oss-fuzz after moving the test config files

---

osquery/config/tests/config_tests.cpp
osquery/dispatcher/dispatcher.cpp
osquery/extensions/tests/extensions.cpp
osquery/include/osquery/dispatcher.h

Fixes #6139.
We do not want to add any services after the dispatcher enters the stopping state. To accomplish this we first acquire a lock in both places then check or set the stopping state.

bug: Fix race in Dispatcher adding and stopping

---

osquery/tables/applications/browser_utils.cpp
specs/chrome_extensions.table

Chrome extensions have optional permissions which are defined in the extension manifest file along the required permissions. This PR will add an additional column to the chrome_extensions table to include optional_permissions.

Add optional_permissions column to chrome_extensions table

---

osquery/core/CMakeLists.txt
osquery/core/tests/BUCK
osquery/core/tests/CMakeLists.txt
osquery/core/tests/windows/wmi_tests.cpp
osquery/core/windows/wmi.cpp
osquery/core/windows/wmi.h

Hi, this PR adds the ability to execute methods on WMI results for Windows.
An example use case for this would be extending the `bitlocker_info` table to also include the Bitlocker version. This is done by executing the `GetVersion` method of the `Win32_EncryptableVolume` class, which this PR provides the foundation for doing.
At a high level, the main thing this PR does is add the `ExecMethod` method onto the `WmiResultItem` class. This is the interface for executing methods on WMI results. Adding this method required adding a secondary helper class: `WmiMethodArgs`. This helper class is used to hold the arguments to be provided to the result item method.
The `services_` member of `WmiRequest` has been converted to a shared pointer, since it is now being shared with `WmiResultItem`, …

core/windows/wmi: Add ability to exec methods on WMI results

---

specs/darwin/plist.table

Fixed typo in plist schema description

Update plist.table description

---

osquery/utils/azure/azure_util.cpp
osquery/utils/system/linux/ebpf/program.h

While there may be many implicit includes within the code base,
these specifically show up when trying to use different compilers.
These changes are a nice-to-have.

toolchain: Add required includes for azure and ebpf

---

cmake/flags.cmake
libraries/cmake/formula/openssl/CMakeLists.txt

This supersedes several of the changes included in #6112.
The goal is to pin Linux builds to libc++, which our toolchain does implicitly.

build: Pin Linux builds to use libc++

---

tools/formatting/format-test.sh

If we don't include them and if the commit we're on requires formatting
on a header file, the test will fail.
We don't want it to fail because it's not the job of this test
to verify that the commit is properly formatted.
Moreover, it just makes sense to test that the formatting script
can properly reach all files it has to.

Include header files in the test of format-check.py

---

osquery/tables/system/windows/bitlocker_info.cpp
specs/windows/bitlocker_info.table

Retrieves version, in-progress encryption status, and the lock
status for each BitLocker-encrypted volume via WMI methods.
Closes https://github.com/osql/osquery-pr/pull/9.

windows/bitlocker_info: Fetch WMI method results

---

libraries/cmake/source/boost/CMakeLists.txt
libraries/cmake/source/boost/patches/src/libs/process/ipstream_move_assignment.patch
libraries/cmake/source/modules/Findboost.cmake

The move assignment operator of boost::basic_ipstream is bugged.
It has been fixed on upstream in commit
https://github.com/boostorg/process/commit/ca994c1972d87939d60f5899e51bf3a43bc59cd8
which is not on any stable build, so we will patch boost with that commit.

Fix boost process basic_ipstream build

---

osquery/tables/applications/posix/docker.cpp
specs/CMakeLists.txt
specs/posix/docker_image_layers.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/docker_image_layers.cpp

This table lists constituent layers of a docker image.
Example output: 
```
osquery> select * from docker_image_layers where id = 'bcb0317';
+---------+------------------------------------------------------------------+-------------+
| id      | layer_id                                                         | layer_order |
+---------+------------------------------------------------------------------+-------------+
| bcb0317 | cc967c529ced563b7746b663d98248bc571afdb3c012019d7f54d6c092793b8b | 1           |
| bcb0317 | 2c6ac8e5063e35e91ab79dfb7330c6154b82f3a7e4724fb1b4475c0a95dfdd33 | 2           |
| bcb0317 | 6c01b5a53aac53c66f02ea711295c7586061cbe083b110d54dafbeb6cf7636bf | 3           |
| bcb0317 | e0b3afb09dc386786d49d6443bdfb20bc74d77dcf68e152db7e5bb36b1cca638 | 4           |
| …
```

adding docker image layers table

---

docs/wiki/deployment/debugging.md
docs/wiki/installation/cli-flags.md
osquery/config/config.cpp

* Add documentation and logging to show that config_dump flag will exit the
process after printing the config.

Add docs to show that config_dump flag exits

---

tools/codegen/genapi.py
tools/codegen/genwebsitejson.py

This script is used to generate JSON for the osquery website. We might be able to follow up and add a CMake target to run and test the code (we'll need the python testing PRs to land). For now let's update it to work with the recent `gentable` changes.

website: Update the website specs formatting code genapi

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/posix/last.cpp
osquery/tables/system/posix/last.h
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/posix/last_tests.cpp
tests/integration/tables/last.cpp

A validation was added to the `genLastAccess` function (https://github.com/osquery/osquery/pull/5274) which would filter for login events only (`USER_PROCESS`). This change breaks the intent of the `last` table, which should show logins and logouts.
This PR updates extracts the `last` implementation to its own function, which is OS independent, enabling tests to be made to the implementation, as well as adding a test for the content (if existing) of the `last` table.
The reasoning for the validation in the first place is to remove information unrelated to user login/logout (check `man wtmp` for more info).

Add missing validation to fix `last` table

---

osquery/logger/tests/logger.cpp

Logging happens after getting the current time,
so the time check should be inverted.
Example of a failure:
```
10: [ RUN      ] LoggerTests.test_logger_log_status
10: W0113 11:10:15.003626 58741 logger.cpp:186] Logger test is generating a warning status (2)
10: /__w/1/s/usr/src/debug/osquery/osquery/logger/tests/logger.cpp:194: Failure
10: Expected: (now) >= (LoggerTests::last_status.time), actual: 1578913814 vs 1578913815
10: [  FAILED  ] LoggerTests.test_logger_log_status (0 ms)
```

Fix flaky LoggerTests.test_logger_log_status

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/process_open_pipes.cpp
specs/CMakeLists.txt
specs/posix/process_open_pipes.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/process_open_pipes.cpp

This table lists a process' open named and anonymous pipes with endpoints resolved.
Example output:
```
osquery> select * from process_open_pipes limit 20;
+------+-----+------+-------+-----------+-------------+------------+--------------+
| pid  | fd  | mode | inode | type      | partner_pid | partner_fd | partner_mode |
+------+-----+------+-------+-----------+-------------+------------+--------------+
| 1    | 220 | rw   | 407   | named     |             |            |              |
| 1    | 221 | rw   | 408   | named     |             |            |              |
| 1    | 225 | rw   | 380   | named     |             |            |              |
| 1    | 250 | r    | 19564 | anonymous |             |            |              |
| 1057 | 21  | r    | 559   | named     | 1060        | …
```

Adding process_open_pipes table

---

osquery/core/windows/wmi.cpp
osquery/core/windows/wmi.h

This PR fixes https://github.com/osquery/osquery/issues/6173. Now, BSTRs are allocated from wstrings, and freed after use. Previously, wide-character strings were being C-casted as BSTR and then provided to WMI objects: Providing wide-character strings as BSTRs to functions and methods requiring BSTRs is undefined.
At the moment, there are other source files calling WmiRequest both with valid BSTRs and wstrings. Both cases will work without any side-effect.  I will make these cases consistent in a separate PR.

Fix Issue#6173: Update WmiRequest constructor to wstring from BSTR

---

docs/wiki/installation/cli-flags.md
osquery/sql/sqlite_util.cpp
osquery/sql/sqlite_util.h
osquery/sql/tests/sqlite_util_tests.cpp
osquery/sql/virtual_table.cpp
tools/deployment/osquery.example.conf

Adds an ``--enable_tables`` CLI flags to specify a limited set of
tables to expose. This is the contrary of ``--disable_tables``.
Ref https://github.com/osquery/osquery/issues/5513

flags: Implement enable_tables

---

osquery/devtools/shell.cpp
osquery/tables/system/windows/logged_in_users.cpp
osquery/utils/conversions/windows/strings.cpp
osquery/utils/conversions/windows/tests/strings.cpp

- Updates code to properly widen and narrow strings on Windows for tables.
- Fixes issue observed in issue https://github.com/osquery/osquery/issues/6160.
~- Does not solve the specific display issue where `fr°tz-jorn` is printed to the console instead of `frøtz-jorn`: This is another independent issue.~
- Now solves issue where `fr°tz-jorn` is printed to the console instead of `frøtz-jorn`.

fix: UTF-8<->UTF-16 conversion for windows; issue #6160

---

tools/formatting/format-check.py

- The output from the git subprocess has to be decoded from bytes
to str before passing it as an argument of a new subprocess.
- Use the python interpreter of the current script to run git-clang-format.py.
Closes https://github.com/osquery/osquery/issues/6089

Fix format_check.py failing on Windows with Python 3.7

---

osquery/filesystem/BUCK
osquery/filesystem/CMakeLists.txt
osquery/filesystem/linux/mounts.cpp
osquery/filesystem/linux/mounts.h
osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/mounts.cpp
osquery/tables/system/linux/selinux_settings.cpp
osquery/tables/system/tests/BUCK
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/linux/selinux_settings_tests.cpp
specs/CMakeLists.txt
specs/linux/selinux_settings.table

```
osquery> SELECT * FROM selinux_settings WHERE key = "enforce";
+-------+---------+-------+
| scope | key     | value |
+-------+---------+-------+
|       | enforce | 1     |
+-------+---------+-------+
```
```
osquery> SELECT value AS 'process_permissions' FROM selinux_settings WHERE key = "process/perms";
+---------------------+
| process_permissions |
+---------------------+
| dyntransition       |
| execheap            |
| execmem             |
| execstack           |
| fork                |
| getattr             |
| getcap              |
| getpgid             |
| getrlimit           |
| getsched            |
| getsession          |
| noatsecure          |
| ptrace              |
| rlimitinh           |
| setcap              |
| setcurrent          |
| setexec             |
| …
```

selinux_settings: New table that presents effective SELinux settings

---

cmake/utilities.cmake
tools/formatting/format-test.sh

- Exclude the whole "libraries" folder so that
we don't attempt formatting code from the other layers.
- Add .mm files to the format-check self test, otherwise
if one of those gets actually modified by a user
the test will fail.
Co-Authored-By: Alessandro Gario <alessandro.gario@gmail.com>

Fix format folder exclusion and format check self test

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/apparmor_profiles.cpp
specs/CMakeLists.txt
specs/linux/apparmor_profiles.table

This table provides output similar to the `apparmor_status` command
```
osquery> SELECT * FROM apparmor_profiles;
+----------------------------------------------------------------------------+-----------------------------------------------+-----------------------------------------------+----------+------------------------------------------+
| path                                                                       | name                                          | attach                                        | mode     | sha1                                     |
+----------------------------------------------------------------------------+-----------------------------------------------+-----------------------------------------------+----------+------------------------------------------+ …
```

apparmor_profiles: New table that presents active AppArmor profiles

---

libraries/cmake/source/boost/CMakeLists.txt

Also added a way to programmatically specify a non Boost third-party dependency
to Boost header only libraries.

thirdparty_boost_asio should depend on thirdparty_openssl

---

osquery/main/harnesses/fuzz_utils.cpp

This applies some query restrictions similar to the SQLite harnesses.
Examples include restricting the impact of ``randomblob(N)``.

fuzzing: Reduce sqlquery false positives

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/windows/services.cpp
osquery/tables/system/windows/startup_items.cpp
osquery/utils/BUCK
osquery/utils/CMakeLists.txt
osquery/utils/system/BUCK
osquery/utils/system/CMakeLists.txt
osquery/utils/system/env.h
osquery/utils/system/windows/env.cpp
osquery/utils/tests/windows/env.cpp

Adds support for expanding (`%`-style) environment variables in the paths of the `services` and `startup_items` tables.

services, startup_items: More intelligent expansion

---

specs/posix/prometheus_metrics.table

The existing description was copypasta from interface_addresses

Fix description for prometheus_metrics table

---

osquery/events/tests/windows/usn_journal_reader_tests.cpp
osquery/events/windows/ntfs_event_publisher.cpp
osquery/events/windows/usn_journal_reader.h
osquery/tables/events/windows/ntfs_journal_events.cpp

This fixes the verbosity observed in https://github.com/osquery/osquery/pull/5371#pullrequestreview-298697871:
A quick summary: `FileReferenceNumber` doesn't have an `operator==` for integers, but C++ gets clever and implicitly provides one because of the `FileReferenceNumber(DWORDLONG)` constructor. This ends up providing the wrong implicit comparison behavior, resulting in the branch below always being taken (and consequently erroring, since no old name record is actually present). This fix changes the comparison to `drive_letter`, which will always be compared correctly and will only be `0U` in the case we want to test.

events/windows: Prevent overly eager old name record handling

---

osquery/tables/system/tests/BUCK
osquery/tables/system/tests/CMakeLists.txt
specs/BUCK
specs/CMakeLists.txt
specs/windows/windows_optional_features.table

The table was added without the proper updates to the build files, so it is not built into the binary.

Update build files to include windows_optional_features table

---

docs/wiki/development/osquery-sdk.md

Updated url in documentation that was not found, and throwing a 404. 
Specifically, this was updated in `osquery-sdk.md`, line 11.
Summary of the change:
Old: https://github.com/osquery/osquery/blob/master/osquery.thrift
New: https://github.com/osquery/osquery/blob/master/osquery/extensions/thrift/osquery.thrift
Fix #6210

Fix 404 url in osquery-sdk.md

---

plugins/config/CMakeLists.txt

A regression from https://github.com/osquery/osquery/pull/6170 I didn't notice.

Fix build without tests enabled

---

libraries/cmake/source/boost/CMakeLists.txt

The`boost::iostreams` can be used to compress streams or single files. The changes add support for building zlib, gzip, lzma and bzip2 with the boost library.

Compiling boost iostream library with zlib

---

libraries/cmake/source/boost/CMakeLists.txt

When using Boost.Process on Windows with Boost.Asio for async_pipe,
the build fails because Asio requires BOOST_ASIO_WINDOWS define
to enable access to async_pipe.
This only partially solves the issue since it's necessary that
Asio users will also include the "sdkddkver.h" header
before the "boost/asio.hpp" header to properly define
_WIN32_WINNT_WIN7, used by osquery.

Fix boost process and asio build on Windows

---

docs/wiki/introduction/sql.md
osquery/sql/sqlite_string.cpp
osquery/sql/tests/sql.cpp
tools/buckconfigs/windows-x86_64/base.bcfg

replacing boost::regex with std::regex for SQL StringExtensions

---

osquery/sql/sqlite_math.cpp

sqlite3_result_error() third parameter is the length
of the string of the second parameter, not the error code.
We set that to -1, which means that the length of the string
will be taken using strlen().
Addresses https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18694

Fix heap buffer overflow in callDoubleFunc and powerFunc

---

osquery/remote/http_client.cpp
osquery/remote/http_client.h
osquery/remote/transports/tls.cpp
osquery/remote/transports/tls.h
osquery/tables/networking/curl.cpp
osquery/utils/aws/aws_util.cpp

This creates two sets of common TLS options. One is for osquery-internal infra, the other is for everything else. This updates the curl table implementation to use the generic TLS options. This prevents using outdated CA files on macOS/etc.
Fixes: #6034
Fixes: #6162

tables: Use basic TLS options within the curl table

---

libraries/cmake/source/boost/CMakeLists.txt
osquery/core/init.cpp
osquery/core/watcher.cpp
osquery/include/osquery/system.h
osquery/main/main.cpp
osquery/main/main.h
osquery/main/windows/main.cpp
osquery/process/posix/process_ops.cpp
osquery/process/process.h
osquery/process/windows/process_ops.cpp
tools/tests/test_osqueryd.py

The windows documentation mentions that ExitThread should not be used in C++ code. When debugging these exit flows I saw exceptions when running dtors.
> I think this is related to the `test_osqueryd.py`'s `test_3_daemon_lost_worker` hang. I have this test running in a loop now to verify.
As a follow up to the investigation referenced above, I reviewed how osquery shuts down gracefully and attempted to simplify the code.
There are essentially two entry points to osquery code, from `main` or as a Windows service `ServiceMain`. These should flow and spend all execution time in `osquery::startOsquery`.
The process then makes two decisions:
- If it is a daemon (using the CLI flag or named `osqueryd`) it becomes a daemon (execute a schedule) otherwise a shell (and execute a REPL).
- If the …

Refactor and simplify shutdown logic

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/mdls.mm
specs/CMakeLists.txt
specs/darwin/mdls.table

Created mdls table which mimics the functionality of the mdls command in macOS. Table allows osquery to retrieve key/value pairs from spotlight metadata.

mdls table implementation

---

CHANGELOG.md
SECURITY.md

This updates the `CHANGELOG.md` for the 4.2.0 release

release: updating changelog for 4.2.0 release

---

tools/codegen/templates/osquery_extension_group_main.cpp.in

Fix codegen template for extension group. The template has a reference
of `waitThenShutdown` which does not exist in the definitions. Instead
of that, a function, `waitForShutdown` is defined in the
`osquery/system.h` which should have been used. This causes compilation
to fail in case of building an extension. This commit fixes that
function call in the template.
if not move the committed files to the stage area,
build the `format` target to format, then re-commit.
More information is available on the wiki.

Fix codegen template for extension group

---

tools/tests/utils.py

psutil deprecated memory_info_ex in version 4.0.0 and suggests using memory_info() instead.See psutil documentation for more (https://psutil.readthedocs.io/en/latest/index.html#psutil.Process.memory_info_ex)

Updating memory_info_ex function call to non-deprecated function

---

osquery/tables/applications/browser_chrome.cpp
osquery/tables/applications/browser_utils.cpp
osquery/tables/applications/browser_utils.h
specs/BUCK
specs/CMakeLists.txt
specs/chrome_extension_content_scripts.table
specs/chrome_extensions.table
tests/integration/tables/chrome_extensions.cpp

Content scripts are able to pass information to the extensions from web pages that the browser visits. Matches specify which of these pages the content scripts will be allowed to access. This PR adds support for matches and scripts to the `chrome_extensions table`.
Example:
```
osquery> SELECT uid, name, identifier, version, script, match
...> FROM chrome_extensions
...> WHERE match = "http://*/" OR
...>       match = "https://*/";
+------+----------+----------------------------------+----------+------------+------------+
| uid  | name     | identifier                       | version  | script     | match      |
+------+----------+----------------------------------+----------+------------+------------+
| 1000 | JSONView | chklaanhfefbnpoihckbnefhakgolnmc | 0.0.32.3 | content.js | …
```

Support for "matches" and "js" keys from "content_scripts" in the chrome_extensions table

---

azure-pipelines.yml
osquery/tables/applications/posix/docker.cpp
specs/CMakeLists.txt
specs/posix/docker_container_fs_changes.table
tools/ci/osquery-ubuntu18.04-toolchain.dockerfile
tools/tests/CMakeLists.txt
tools/tests/test_docker_container_fs_changes_table.py

This table lists changes to a container's filesystem since it's creation.
Example query:
```
osquery> select * from docker_container_fs_changes where id = '6d4a0ff6d954';
+--------------+----------+-------------+
| id           | path     | change_type |
+--------------+----------+-------------+
| 6d4a0ff6d954 | /bin     | C           |
| 6d4a0ff6d954 | /bin/xxx | A           |
| 6d4a0ff6d954 | /bin/tar | D           |
| 6d4a0ff6d954 | /xxx     | A           |
+--------------+----------+-------------+
```
change_type legend: C:Modified, A:Added, D:Deleted

Adding docker_container_fs_changes table

---

osquery/dispatcher/scheduler.cpp

Non-error status messages should be verbose logs, not part of the standard log stream.

Non-error status messages should be verbose

---

osquery/sql/sqlite_string.cpp
osquery/sql/tests/sql.cpp

Add a new FLAG, regex_max_size, with a default of 4096 bytes,
which limits the size of the regex that can be used
with regex_match and regex_split SQL functions.
This is done since it's possible to create a regex
which makes the std::regex destruction go into a stack overflow,
due to too many alternate states (|).
Add a couple of tests to verify that the limit is correctly respected.
Restore the test for regex_split that was originally hanging when using
boost.

Limit regex_match and regex_split regex size

---

osquery/utils/conversions/darwin/cfnumber.cpp

As I began testing the newly merged `mdls` table, I came across some results that did not match my expectations (and also did not match the standard CLI mdls output).
For example:
```
➜  mdls /Users/fritz-imac/Pictures/summer-2019-onward-card/_DSC8054.JPG
kMDItemFocalLength                 = 28
kMDItemFocalLength35mm             = 28
kMDItemFNumber                     = 2.8
```
vs.
```shell
osquery> SELECT key, value, mdls.valuetype FROM mdfind, mdls USING(path) WHERE query = "kMDItemFSName == '_DSC8054.JPG'" AND key IN ('kMDItemFNumber', 'kMDItemFocalLength', 'kMDItemFocalLength35mm');
+------------------------+------------+-----------+
| key                    | value      | valuetype |
+------------------------+------------+-----------+
| kMDItemFocalLength     | 1105199104 | CFNumber …
```

Fix typing issue with CFNumber conversion

---

azure-pipelines.yml

When the batch script that implements the build step has been
changed to stop the sccache server as the last command,
all build failures started to be ignored because the last command,
always succeeding, was clearing out the exit status.
Batch scripts do not have a global "exit on error" option,
so manually checking the error level and exiting with such error is needed.

Azure Pipelines: Do not ignore a build failure on Windows

---

packs/unwanted-chrome-extensions.conf

Seems like a common pitfall/gotcha when running osquery as root is that queries are run against the root user. You'll see warning messages like 
```
W0221 13:48:37.001775 267830720 virtual_table.cpp:987] The chrome_extensions table returns data based on the current user by default, consider JOINing against the users table
W0221 13:48:37.001806 267830720 virtual_table.cpp:1002] Please see the table documentation: https://osquery.io/schema/#chrome_extensions
```
The fix is to join against `users` table (as noted in the warning messages). However, another thing to keep an eye out on is whether the query optimizer will affect query execution and cause osquery to continue using the root user context. An example of when this happens is:
```sql
SELECT * FROM users JOIN chrome_extensions USING …
```

Update unwanted-chrome-extensions.conf queries to include all users

---

osquery/extensions/impl_thrift.cpp
osquery/sql/virtual_table.cpp

[Issue 6107](https://github.com/osquery/osquery/issues/6107)

check for errors return status from extension table.

---

osquery/tables/applications/browser_utils.cpp

Move `profiles` initialization into `chromePaths`
This code uses a deep set of nested for loops to iterate over all possible extension directories. `profiles` was initialized _outside_ the `chromePaths` loop, which caused it to erroneously repeat. I'm unsure whether or not adding some kind of unique (or set) functionality here makes any sense.
I also converted an `if` to an early return.
Manually tested on macOS
Fixes: https://github.com/osquery/osquery/issues/6276

Fix initialization of profiles variable

---

osquery/sql/virtual_sqlite_table.cpp
plugins/config/parsers/auto_constructed_tables.cpp

Add the `path` column to the ATC generate specs. This matches the existing data, which already includes it here: https://github.com/osquery/osquery/blob/master/osquery/sql/virtual_sqlite_table.cpp#L64-L68
I'm assuming this wasn't intentionally omitted, since it is already in the underlying data.
tested manually on macOS

Add path to ATC generated specs

---

osquery/database/database.cpp
osquery/include/osquery/database.h
plugins/database/ephemeral.cpp
plugins/database/ephemeral.h
plugins/database/rocksdb.cpp
plugins/database/rocksdb.h
plugins/database/sqlite.cpp
plugins/database/sqlite.h

See #5296.
`--database_dump` flag does not output anything. I dug around and found that the functionality was added in https://github.com/osquery/osquery/commit/fef53fa0d0a30afc8cf08fa02e193723ee1e3097. But then, it seems that the functionality was accidentally removed in https://github.com/osquery/osquery/commit/521041ba86cd4f76a4272ec12ba5919d4af64b9a. (You can see that `dumpDatabase` method was moved to the specific db plugin and was implemented in `EphemeralDatabasePlugin` but NOT `RocksDBDatabasePlugin`.)
I copied the implementation over and built it locally and it seems to be working. But I'm a total newbie to osquery and c++ so my work may be incorrect (and perhaps an alternative approach is better). Or should I add tests? Let me know - just posting this PR for some discussion! ❤️

Fix database_dump for rocksdb

---

.gitmodules

The upstream repository (located on sourceware.com) has started causing connection issues when cloning with the HTTPS protocol.
This PR updates the remote of the submodule so that it uses our mirror inside the osquery organization (https://github.com/osquery/third-party-bzip2).

libs: Update the bzip2 remote URL

---

osquery/tables/system/windows/services.cpp

Osquery will discard all services if there's an error querying a specific service. This means if there is one service that errors osquery will never produce results. 
An example of this is an issue I've seen in the windows service manager:
```
Service name: NetTcpPortSharing
Description: <Failed to Read Description. Error Code: 15101 >
```
With the broken service on the machine querying the services table produced no results and logged a warning:
```
select * from services;
W0302 15:50:00.633996  7340 services.cpp:199] Failed to query service description
```
Osquery should skip over that service if it failed to query and continue. I have made two changes to overcome the issue:
1. If there's a failure to query a service log a warning and continue
2. If osquery cannot query the service …

Services query fails if osquery cannot get service description

---

osquery/tables/system/BUCK
osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/screenlock.mm
specs/BUCK
specs/CMakeLists.txt
specs/darwin/screenlock.table

This PR adds a new virtual table to the darwin platform called `screenlock`. This is a single row table that when queried with `SELECT * FROM screenlock` returns the following output...
```
+---------+--------------+
| enabled | grace_period |
+---------+--------------+
| 1       | 60           |
+---------+--------------+
```
An unattended Mac without the screenlock enabled is susceptible to an Evil Maid attack. This is one of the most requested checks by Kolide customers.
Previously, it was thought to be impossible to capture this data programmatically after Apple made significant changes the screenlock API in macOS 10.13 where instead of encoding the values in an easily accessible plist, they were instead stored in an encrypted keychain that requires the user's password to unlock.
More …

Add new macOS virtual table screenlock

---

plugins/logger/aws_kinesis.cpp
plugins/logger/aws_kinesis.h

The AWS kineis logger plugin is sent two types of log record: results logs which are produced by scheduled queries and status logs which are produced by glog. When the logger_min_status or verbose options are used the volume of status logs can cause undesirable bandwidth usage.
Logger plugins can opt out of being sent status logs by overriding the base LoggerPlugin usesLogStatus method. The AWS kinesis logger plugin currently opts in for status logs and this cannot be configured.
This PR adds a new configuration option aws_kinesis_disable_log_status that when set to true will prevent status logs being sent to kinesis. The default value of this option is false so when not specified the previous behaviour is retained. The options can be set either as a CLI flag or in the configuration.

Make AWS kinesis status logging configurable

---

azure-pipelines.yml

With the increasing size of the build and the respective ccache
and sccache caches, the disk space sometimes is not enough
and the build fails.
This deletes the build folder as the last step since it shouldn't
be necessary anymore.

Azure Pipelines: reclaim disk space after building

---

azure-pipelines.yml

In the past the Windows agent changed the path where Python2
was installed; a special logic was added which should've tested
if the path existed, though it wasn't correct in the case
the powershell script is configured to be aborted at the first error.
Since the old path should not be present anymore,
we simply remove the logic and use the path we expect to exist.

Azure Pipelines: Fix Python2 discovery in Buck builds

---

tools/tests/test_osqueryd.py

Partially addresses https://github.com/osquery/osquery/issues/6300

Fix assert used to check the retcode in test_5_daemon_sigint

---

plugins/config/parsers/decorators.cpp
plugins/config/parsers/tests/decorators_tests.cpp

The "decorators" configuration value must be a JSON object,
otherwise we try to search through its inexistent members
and dereference a null pointer.
Added also a regression test.
Addresses https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19274

Fix parsing an invalid decorators config

---

azure-pipelines.yml
docs/wiki/development/building.md
tools/ci/osquery-ubuntu18.04-toolchain.dockerfile

This new toolchain contains a newer LLVM version (9.0.1),
a fix for the scan-build scripts and it keeps the LLVM static libraries,
necessary to implement the new BPF framework and tables.

Update osquery-toolchain to the 1.1.0 version

---

tests/integration/tables/chrome_extension_content_scripts.cpp
tests/integration/tables/chrome_extensions.cpp

Removed the columns "script" and "match" from the test
since they do not belong to the chrome_extensions table,
they belong to chrome_extension_content_scripts.
Added the missing integration test for the table
chrome_extension_content_scripts.
Fixes https://github.com/osquery/osquery/issues/6306

Fix chromeExtensions.test_sanity failure

---

osquery/config/config.cpp
osquery/config/config.h
osquery/config/tests/config_tests.cpp
osquery/utils/json/json.cpp
osquery/utils/json/json.h

Parsing a configuration file as a JSON document
which contains deeply nested elements can lead to a stack overflow
when using the recursive parser of RapidJSON.
Since the configuration isn't changed or parsed frequently,
use the slower iterative parser instead.
Copying the configuration JSON document
that contains deeply nested elements, using the CopyFrom API,
can lead to a stack overflow, due to the recursive nature
of the RapidJSON GenericValue construction.
Detect the depth/nesting level of a config document
and limit it to 32 levels.
Using an iterative parser, while it avoids stack overflows,
can cause memory exhaustion if the config size is too big.
Limit the maximum config size, stripped from its comments, to 1MiB.
Addresses …

Fix stack overflow when parsing deeply nested configs

---

osquery/sql/dynamic_table_row.cpp

When a query triggers multiple xFilter calls
and there's an operation that has to work on the sum of rows
resulting from all those calls, we trigger a use-after-free
when such operation tries to access the rows data.
This happens because each xFilter call we clear the rows
resulting from the previous xFilter call, and because
when returning the values of a text column we don't copy it,
but return a pointer to it.
A contrived example of a query with the issue is:
SELECT path=count(*) FROM file WHERE path = '/' OR path = '1'
This changes the last sqlite3_result_text parameter
from SQLITE_STATIC to SQLITE_TRANSIENT.
Addresses https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20833

Hotfix a use-after-free accessing rows data

---

tools/tests/test_base.py

This is required for #6334.
I am unsure why the "runner"'s `proc` member was removed at the end of a successful `run()`?
But without this instance we cannot inspect the daemon's pid. In the follow up PR we confirm the daemon exits correctly.

tests: Keep proc instance for test_base and test_osqueryd

---

osquery/core/init.cpp
tools/tests/test_osqueryd.py

It is not enough to just `requestShutdown`, the `::start` logic should also return early. This allows the binary to exit from `main` normally.
Fixes #6290, #6329.

Return after check/dump requests in init

---

osquery/tables/system/darwin/processes.cpp
osquery/tables/system/tests/darwin/processes_tests.cpp

Fixes #6252.
This replaces the `cmdline` parsing logic in macos to be more C++, hopefully more efficient. It fixes a bug iterating through the argc/argv data and adds a test.

macos: Fix processes cmdline parsing

---

osquery/tables/system/linux/deb_packages.cpp
specs/linux/deb_packages.table
tests/integration/tables/deb_packages.cpp

Fixes #4740
The deb_packages table includes packages that are uninstalled but have config files left over.
This PR adds a `status` column to the table so a user can filter on packages with a specific status.
The most common statuses are
`install ok installed`
`deinstall ok config-files`

add status column to deb_packages table

---

libraries/cmake/formula/openssl/CMakeLists.txt
osquery/tables/networking/curl_certificate.cpp

- Add fallback url to download the openssl tar.gz from the "old" archives
- Add URL_HASH to the openssl external project,
to avoid to redownload the archive if it has been alredy downloaded
and the integrity is verified
- Update curl_certificate table to use the newer openssl API,
so that it builds.

Update OpenSSL to version 1.1.1f and fix build

---

osquery/tables/events/darwin/openbsm_events.cpp

macos: Use -1 for missing ppid in process_events

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/tests/filesystem.cpp

When a block size is passed to the readFile function
or a file has no size, the read is forced to be blocking,
even if the handle is opened as non-blocking.
The opposite can happen too, a blocking handle is opened
but since a block size of 0 is passed, and the file size is not 0,
the file is read with non-blocking I/O.
This change bases the decision of doing blocking
or non-blocking I/O mainly on the "blocking" parameter
of the readFile function and the file being a special file or not.
If a handle is opened in non-blocking mode but the file is special,
the handle is reopened as blocking.
Also give a different name to the overload that provides
a way to do a read file check via readFile.
This should address the most concerning issues found in https://github.com/osquery/osquery/issues/5661

Fix readFile API doing blocking I/O with a non-blocking handle

---

osquery/extensions/interface.cpp

If the extension uuid is 0 osquery will set the extension's socket to the same value as the main socket:
https://github.com/osquery/osquery/blob/master/osquery/include/osquery/extensions.h#L42
It will then fail to load.
Change the extension uuid so it can never be 0.

Ensure the extension uuid is never 0

---

osquery/process/windows/process_ops.cpp
osquery/tables/system/windows/processes.cpp

Change the logs in the processes table to be info to prevent constant errors caused by querying. Without SeDebugPriviledge https://support.microsoft.com/en-gb/help/131065/how-to-obtain-a-handle-to-any-process-with-sedebugprivilege you cannot access information about system processes. This means failing to get certain process information isn't really an error. To reduce the noise change the log level to information.
Run 
```
select cwd from processes
```
Without change:
```
C:\osquery_test\original>osquery.exe
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> select description from processes;
Error: no such column: description
osquery> select cwd from processes;
E0407 13:17:41.395509 31256 processes.cpp:312] Failed to lookup path information for process 4
E0407 …
```

Change process table log errors to info

---

osquery/core/init.cpp
osquery/include/osquery/system.h
osquery/process/windows/process.cpp

On Windows launching the worker took advantage of the fact a child process inherits from it's environment from the parent. You can see here when launching a worker osquery will change its own environment to set the worker variable for the child environment: https://github.com/osquery/osquery/blob/master/osquery/process/windows/process.cpp#L188
After the processes are launched the environment variables OSQUERY_WORKER and OSQUERY_LAUNCHER are then unset. This means the briefly the watcher can set itself as a worker. 
This then combine with the osquery checking if it's a worker by reading directly from the environment: https://github.com/osquery/osquery/blob/master/osquery/core/init.cpp#L143 causes a race condition where the watcher will begin behaving as the worker.
Copy the environment and …

Copy the parent environment when launching worker

---

osquery/core/plugins/sql.h
osquery/sql/sql.cpp
osquery/sql/sqlite_util.cpp

Osquery can fail to detach existing tables when an extension has gone away. This then causes issues re-registering the extension tables when the extension was added back. We can see here that the call to detach will always return success: https://github.com/osquery/osquery/blob/master/osquery/sql/sql.cpp#L162 instead this should return a status stating why it failed. 
The reason the detach fails is because it doesn't necessarily use the primary database when calling it. The fix has already been applied to attach function: https://github.com/osquery/osquery/blob/master/osquery/sql/sqlite_util.cpp#L247

Return error detaching table, only use primary database

---

osquery/extensions/extensions.cpp
osquery/include/osquery/extensions.h

When running the extension as a separate process if the extension goes away and is then added back within extensions_interval period the extension will remain connected but not registered with osquery. This is because the extension will successfully ping osquery core but won't actually be registered with it. This means the extension is a redundant process as it cannot receive any calls to it's tables. 
You can see that each extension is started with it's own unique route uuid https://github.com/osquery/osquery/blob/master/osquery/extensions/interface.cpp#L235 and osquery will keep a handle on this. 
You can then see in the ExtensionWatcher: https://github.com/osquery/osquery/blob/master/osquery/extensions/extensions.cpp#L240 that this will ping osquery core and if it gets a success will …

Check extensions are registered with osquery core

---

docs/wiki/development/building.md

Add git-lfs as dependency in documentation because without it the `cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 ..` fails
Here the output, (I kept the all output if needed:
```bash
❯ mkdir build; cd buildcd
❯ cd osquery
❯ mkdir build; cd build
❯ cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 ..
...
-- Importing: source/icu
Submodule 'libraries/cmake/source/icu/src' (https://github.com/unicode-org/icu) registered for path 'src'
Cloning into '/Users/gaetan.piquenot/Workspace/tools/osquery/libraries/cmake/source/icu/src'...
From https://github.com/unicode-org/icu
* branch            e2d85306162d3a0691b070b4f0a73e4012433444 -> FETCH_HEAD
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
Unable to checkout 'e2d85306162d3a0691b070b4f0a73e4012433444' in …
```

Add git-lfs as dep for macOS build in documentation

---

osquery/tables/system/windows/logged_in_users.cpp

On Windows the logged_in_users table accesses non-interactive sessions and returns them as logged on users. We can see from the Windows documentation: https://docs.microsoft.com/en-gb/windows/win32/api/wtsapi32/ne-wtsapi32-wts_connectstate_class that a user is only logged on if the state is WTSActive.
If the session is non-interactive or is session 0 it can't be a logged on user and should be ignored.
On Windows run:
```
select *from logged_in_users;
```
Without change:
```
C:\osquery_test\original>osquery.exe --verbose
I0408 11:40:21.701100 27116 init.cpp:340] osquery initialized [version=4.2.0]
I0408 11:40:21.701100 27116 extensions.cpp:349] Could not autoload extensions: Failed reading: \Program Files\osquery\extensions.load
I0408 11:40:21.701100 19312 interface.cpp:268] Extension …
```

Don't check logged in users in session 0 or non-active sessions

---

tests/integration/tables/userassist.cpp

The specific key the test checks for its existence,
which is Microsoft.Windows.Explorer,
might not be always present.
Use UEME_CTLSESSION key which should be always present since
it generically represents the start of a session.
Fixes https://github.com/osquery/osquery/issues/6360

Fix Userassist.test_sanity test sometimes failing

---

osquery/sql/virtual_sqlite_table.cpp
osquery/tables/system/darwin/quicklook_cache.cpp
osquery/tables/system/freebsd/pkg_packages.cpp

sqlite [defines](https://www.sqlite.org/c3ref/column_blob.html) `SQLITE_INTEGER` as 64bit, not 32bit. Most of our usage seems correct, but a couple did not. This updates them
Also include `SQLITE_BLOB` in ATC tables.
Fixes: #6391
Not sure how to add tests for this.
```
dover:build seph$ ./osquery/osqueryi  --config_path  /tmp/osq.conf "select * from url_timestamp limit 4;"
W0414 23:25:26.263969 284452288 auto_constructed_tables.cpp:178] ATC Table: url_timestamp is misconfigured. The configuration include `path`, which is a reserved column
+-------------------------------------------------------------------------+-------------------+---------------------+
| path                                                                    | time              | time_converted      | …
```

Update some sqlite types

---

osquery/distributed/distributed.cpp
osquery/include/osquery/distributed.h

Currently the distributed write API sends back status codes that indicate whether or not a particular query was successful. However, in the event that a query was not successful, we have no other information as to what the failure was. This PR solves the issue by adding a new top-level field to the distributed write results:
`messages`: A map of queryID -> error message for queries that fail. Successful queries will have an empty string for the message.
Also another top-level key was added for the original sql query statement corresponding to the distributed write request:
`statements`: A map of queryID -> sql statement.
Together, these fields help TLS distributed api implementors to inform clients about *why* an error happened - as opposed to just letting them know that *some* error …

Add messages to distributed query results

---

libraries/cmake/formula/openssl/CMakeLists.txt

Openssl was depending on zlib for SSL/TLS compression,
though it was trying to load it as a dynamic library.
On Windows especially this is an issue because the dll
could possibly be loaded from a insecure place,
so this can be exploited.
Moreover it's proven that compression can lead
to leaks of information; so we completely disable it
to resolve both issues.
First steps to mitigate https://github.com/osquery/osquery/issues/6426

Disable openssl compression support

---

README.md
SECURITY.md

Please see my note in Slack in the #foundation channel. The changes here are to be more concrete about how we handle advisories and reports; and to remove osquery from FB Whitehat scope.

docs: Update osquery security policy

---

.readthedocs.yml

Take a look at the latest build failure: https://readthedocs.org/projects/osquery/builds/11004002/

docs: Exclude all submodules for RTD builds

---

osquery/tables/system/windows/registry.cpp

**Description**
The windows registry table does not use recursive like correctly, if the '%%' is in the final part of the path it only gets the first set of subkeys.
**Testing**
Choose a registry key with multiple layers of subkey (I chose python) and query using recursive like:
Before
```
osquery> select path, name from registry where path like 'HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\%%';
+-----------------------------------------------------------+-------------+
| path                                                      | name        |
+-----------------------------------------------------------+-------------+
| HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7         | 2.7         |
| HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.6         | 3.6         |
| …
```

Change the registry LIKE path constraint to filter recursively

---

osquery/tables/system/darwin/os_version.cpp
osquery/tables/system/linux/os_version.cpp
osquery/tables/system/windows/os_version.cpp
specs/os_version.table
tests/integration/tables/os_version.cpp

To be able to quickly determine the architecture of the system osquery is running on, we add an `arch` column to all platform.
The architecture is shown in the system native format.
Linux and macOS basically use the same information available with `uname -m`, while on Windows we use the same WMI class used to get other information about the OS, but we also query `OSArchitecture`.

Add 'arch' column to os_version

---

osquery/tables/system/linux/rpm_packages.cpp
specs/linux/rpm_packages.table
tests/integration/tables/rpm_packages.cpp

As for the deb_packages table we expand the rpm_packages table, to add more information about the packages installed on the distribution and to better filter them. The two columns added are: vendor, group.
These are standard/official fields in the rpm database.
I've also enabled its respective integration test.

Add 'vendor', 'package_group' columns to rpm_packages

---

osquery/tables/system/linux/deb_packages.cpp
specs/linux/deb_packages.table
tests/integration/tables/deb_packages.cpp

To expand the information available about packages installed on a distro and also to be able to better filter them to find vulnerabilities, this commit adds 3 new columns: maintainer, section, priority.
They are standard/official fields available in the dpkg database.

Add 'maintainer', 'section', 'priority' columns to deb_packages

---

osquery/tables/system/hash.cpp

When a file on disk has been replaced and the cache is updated with the new hash value, it was not updating the inode number in the cache used for future lookups. This resulted in the cache being perpetually stale and recomputing the hash for every future lookup of the file.
One line fix to update the inode number in the cache entry along with updating the size and mtime.

Update hash cache inode number

---

libraries/cmake/formula/openssl/CMakeLists.txt

This is meant to reduce the noise in the installation output of openssl,
since docs would easily fill the scrollback of most terminals.
Since we don't care about the docs, only install binaries.

Do not install openssl docs

---

osquery/events/audit_flags.cpp
osquery/events/darwin/openbsm.cpp
osquery/events/darwin/openbsm.h
osquery/events/linux/auditdnetlink.cpp
osquery/tables/events/linux/process_events.cpp
osquery/tables/events/linux/process_file_events.cpp
osquery/tables/events/linux/user_events.cpp

No need to edit macos /etc/security/* files and reboot the machine  anymore.
if --disable_audit is false, rules are controlled by -
--audit_allow_sockets  default(false)
--audit_allow_process_events  default(true)
--audit_allow_user_events  default(true)
--audit_allow_fim_events  default(false)
With this implementation osquery can inform kernel in what events its interested.  That way it will not interfere with default audit trail mechanism of the system. Unlike linux kernel, OSX takes the responsibility of de-multiplexing the audit messages and apply the installed rules before delivering the messages to the userland.

macos: automating audit rules install

---

osquery/tables/system/windows/processes.cpp
osquery/utils/system/windows/env.cpp

Closes https://github.com/osquery/osquery/issues/6403
As seen in Windows' `startup_items`, if there's a startup item entry in the registry key which does not have an associated value, then an empty string is passed to a osquery helper function that tries to parse it into an `args` array. But it uses a Windows API that, if passed an empty string, fills in the command line args of the current osquery process, instead. This PR catches the empty string before that happens.

Fix the handling of empty args strings, on Windows

---

specs/darwin/account_policy_data.table

https://github.com/osquery/osquery/issues/6345
if not move the committed files to the stage area,
build the `format` target to format, then re-commit.
More information is available on the wiki.

Fixing the description of failed_login_count from account_policy_data

---

osquery/tables/system/darwin/packages.mm

After fixing #6457 I wanted to write a fuzzer for this data structure. It was time well spent as it found another bug in the BOM parsing. This prevents a crash in the case of parsing a malformed package BOM.

Fix potential overread bug in package_bom

---

osquery/process/windows/process_ops.cpp
osquery/tables/system/windows/windows_security_center.cpp
osquery/tables/system/windows/windows_security_products.cpp

This hardens our runtime DLL loading a bit more. I am assuming we only ever want to load system DLLs and wont be packaging libraries with osquery. See #6426.

Use LOAD_LIBRARY_SEARCH_SYSTEM32 for LoadLibrary

---

osquery/core/init.cpp
osquery/core/watcher.cpp
osquery/dispatcher/scheduler.cpp

requestShutdown(int retcode, const std::string& system_log) only logs to the syslog which is not available on Windows. 
When the watcher exits log the error in the standard log saying why it's exiting.

Add additional logging in the watcher for windows

---

osquery/tables/system/windows/processes.cpp

Closes https://github.com/osquery/osquery/issues/4384 by pulling the correct Current Working Directory from the process's PEB, which is an approach that —although not a supported API— was already being taken in this table for other fields. Tested on Windows 10 x64.

Correct the 'cwd' and 'root' columns of processes table on Windows

---

docs/wiki/deployment/process-auditing.md
osquery/events/darwin/openbsm.cpp
osquery/events/darwin/openbsm.h
osquery/events/events.cpp
osquery/include/osquery/events.h

I don't think this is the root cause of #6431, but while reviewing the OpenBSM publisher I noticed it can hang osquery if there are no events in the audit queue.
This change applies the same polling interval and error handling as Linux.

macos: Add polling to OpenBSM publisher

---

libraries/cmake/formula/openssl/CMakeLists.txt

If CMAKE_OSX_DEPLOYMENT_TARGET is not explicitly set, CMake will leave it empty and leave the sdk version choice to the compiler used.
Therefore we have to avoid to pass the minimum sdk flag to openssl if the deployment target is not explicitly set.
This is a follow up to https://github.com/osquery/osquery/pull/6469

Pass the minimum macOS SDK version to openssl only if explicitly set

---

libraries/cmake/source/libelfin/patches/src/incorrect_const_set_binding.patch
libraries/cmake/source/modules/Findlibelfin.cmake

The set_binding function is incorrectly marked as const,
since it actually modifies one of the struct members.
This was somehow not caught by older compilers,
but is failing on LLVM/Clang 10, so we create a patch to fix this.

Fix libelfin build on ossfuzz and LLVM/Clang 10

---

osquery/tables/system/windows/registry.cpp

Running "SELECT * FROM registry WHERE (path like ' ')" causes osquery to crash. This is due to the explodeRegistryKey function assuming that whatever string is passed into it is prepended with the registry hive.
Before:
```
C:\test>osqueryd.exe --allow_unsafe --S
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> SELECT * FROM registry WHERE (path like ' ');
C:\test>
```
After:
```
C:\test>osqueryd.exe --allow_unsafe --S
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> SELECT * FROM registry WHERE (path like ' ');
osquery>
```

Only explode registry key if it can be tokenized

---

libraries/cmake/source/librdkafka/CMakeLists.txt
plugins/logger/CMakeLists.txt
plugins/logger/tests/CMakeLists.txt

I fixed the issues left open in (https://github.com/osquery/osquery/pull/6095)
- CMake now also links librdkafka on windows
- Fixed the usage of the LIBRDKAFKA_STATICLIB macro

Link librdkafka on windows

---

libraries/cmake/source/libelfin/CMakeLists.txt

This is a followup of PR osquery/osquery#6472,
while the code was patched we were still using the unpatched version.
This should finally fix ossfuzz build failure.

Actually use the patched libelfin version

---

osquery/utils/error/error.h

Fix a build error with newer LLVM/Clang (11), as found on
oss-fuzz.
The member function returns a member variable via std::move,
but the member function is marked as const.
Since that variable to be actually moved would require
the class instance to be non const, a copy is used instead;
the return type has its copy constructor deleted though,
so this is always incorrect and removing the const qualifier
is the solution.

Change ErrorBase::takeUnderlyingError to non const

---

docs/wiki/deployment/configuration.md

Thanks to @FritzX6 for helping me with this. I'd prefer the example be cross platform or use GNU/Linux, but I couldn't think of any non-creepy databases. Does Firefox use SQLite for anything benign?

Add Auto Table Construction to docs

---

tests/integration/tables/deb_packages.cpp
tests/integration/tables/helper.cpp
tests/integration/tables/helper.h
tests/integration/tables/npm_packages.cpp
tests/integration/tables/os_version.cpp
tests/integration/tables/rpm_packages.cpp

This simple helper takes a table name and
an already prepared rows map to add the container
columns, which are normally hidden, and call validate_rows on it.
We use this function in deb_packages, rpm_packages, npm_packages,
os_version integration tests.
Follow up to #6413 and #6414

Add validate_container_rows helper for integration tests

---

specs/hash.table
specs/utility/file.table
tests/integration/tables/file.cpp
tests/integration/tables/hash.cpp
tests/integration/tables/helper.cpp
tests/integration/tables/helper.h

This is for consistency with the decisions taken
for PR osquery/osquery#6413 and osquery/osquery#6414.
We also update the integration test helper to accept custom constraints,
in the case the table has required columns.
Depends on #6485

Make file and hash container columns hidden

---

osquery/config/packs.cpp

If you have a lot of queries and use a low `--config_refresh` you may "spam" your logs with update notices. Let's instead only emit this warning once.

Only emit 'denylist' warning once

---

tools/codegen/templates/typed_row.h.in

There was an issue found in #6450.
This serialize method is not working correctly, the columns should be added to the object passed to serialize, which is then added to the array-type document.

bug: Fix typed_row table caching

---

docs/wiki/development/building.md

This updates the docs around using `cpack` to build packages for
Windows, Linux, and macos.
See pictures of updated docs in markdown:

packaging: updating docs on cpack usage to include Chocolatey

---

tests/integration/tables/atom_packages.cpp
tests/integration/tables/processes.cpp
tests/integration/tables/rpm_packages.cpp

tests: Fix atom_packages, processes, rpm_packages flakiness

---

cmake/flags.cmake
osquery/sdk/CMakeLists.txt

Add a description to the function preparing the targets carrying the
main compiler and linker flags.
Convert CMake default flags to the ones we use, instead of overriding
them later via targets.
This can also avoid having us use the wrong CRT on Windows if we forget to link
against osquery_cxx_settings.
Reduce the "overriding <flagX> with <flagY>" messages on Windows by
removing the warning level from the default flags, and adding that
to the specific osquery_<c|cxx>_settings target, so that non internal
targets can choose their own level.
Minor cleanups
Fix osquery/osquery#6509

CMake: Fix and cleanup compile flags

---

osquery/core/tables.cpp
osquery/include/osquery/tables.h
osquery/sql/tests/virtual_table.cpp

This is a prototype fix for #6510. ~~I wrote the test code without running it.~~
This has one limitation in that if you were to populate the table cache with:
```sql
select * from some_table;
```
You would expect a cache-hit with:
```sql
select some_col from some_table;
```
But cache-hits are only allowed with star (or similar) selects.

tables: Only populate table cache with star-like selects

---

cmake/flags.cmake

target_link_libraries correctly consider "-framework \<library\>"
as a library, instead of a flag; let's use that instead of
target_link_options.

CMake: Correct macOS framework linking

---

azure-pipelines.yml
docs/wiki/development/building.md

Also update the Windows Server version used from 2016 to 2019,
update Ninja to the latest stable and update the docs.
Note: the dependency on the VS2017 compiler was due to build errors we had when rewriting CMake for experimental, which was itself using VS2017; the build error were most likely caused by boost old version.
The new compiler builds and works fine now, so lets update!

Azure Pipelines: Update compiler version used to v142

---

cmake/flags.cmake
libraries/cmake/source/boost/CMakeLists.txt

```
./osquery/sql/tests/osquery_sql_tests_virtualtabletests-test
Running main() from /home/teddy/git/osquery-prod/build/libs/src/patched-source/googletest/src/googletest/src/gtest_main.cc
[==========] Running 23 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 23 tests from VirtualTableTests
[ RUN      ] VirtualTableTests.test_tableplugin_columndefinition
[       OK ] VirtualTableTests.test_tableplugin_columndefinition (3 ms)
[ RUN      ] VirtualTableTests.test_extension_tableplugin_columndefinition
[       OK ] VirtualTableTests.test_extension_tableplugin_columndefinition (0 ms)
[ RUN      ] VirtualTableTests.test_tableplugin_options
[       OK ] VirtualTableTests.test_tableplugin_options (0 ms)
[ RUN      ] VirtualTableTests.test_tableplugin_moreoptions …
```

build: Support ASAN for boost coroutine2 using ucontext

---

osquery/worker/logging/glog/glog_logger.cpp

Add missing GLOG_WARNING type
In #6209 a logging abstraction was added. However, it omitted the
GLOG_WARNING this caused some logs to be dropped, with the severity not
supported.

Fix logging of `GLOG_WARNING`

---

osquery/filesystem/filesystem.cpp

Symlink loops seem quite common on macOS. And, the occasionally crop up on other platforms. As we seem to handle this fine, change from a warning to a verbose.
(there may be disagreement here, feel free to speak up.)
Fixes: #6462

Change "Symlink loop" message from warning to  verbose

---

osquery/events/windows/usn_journal_reader.cpp
osquery/filesystem/fileops.h
osquery/filesystem/filesystem.cpp
osquery/filesystem/windows/fileops.cpp
osquery/tables/system/windows/certificates.cpp
osquery/tables/system/windows/drivers.cpp
osquery/tables/system/windows/logged_in_users.cpp
osquery/tables/system/windows/logon_sessions.cpp
osquery/tables/system/windows/os_version.cpp
osquery/tables/system/windows/processes.cpp
osquery/tables/system/windows/registry.cpp
osquery/tables/system/windows/scheduled_tasks.cpp
osquery/tables/system/windows/userassist.cpp
osquery/tables/system/windows/video_info.cpp
osquery/utils/conversions/CMakeLists.txt
osquery/utils/conversions/windows/strings.cpp
osquery/utils/conversions/windows/strings.h
osquery/utils/conversions/windows/tests/strings.cpp
osquery/utils/conversions/windows/tests/windows_time.cpp
osquery/utils/conversions/windows/windows_time.cpp
osquery/utils/conversions/windows/windows_time.h
specs/os_version.table
specs/windows/video_info.table

Summary: 
See #5746 for more details. This PR adds a helper function to
convert datetime BSTRs passed back from WMI queries into FILETIME
structs, which we can convert using our existing utility into a Unix
Epoch time.
Test Plan:
Sample queries against `video_info`:
```
osquery> select driver_date from video_info;
+-------------+
| driver_date |
+-------------+
| 1563926400  |
+-------------+
```
Checking that time:
```
In [2]: datetime.datetime.fromtimestamp(1563926400  )
Out[2]: datetime.datetime(2019, 7, 23, 17, 0)
```
And `os_version`:
```
osquery> select install_date from os_version;
+--------------+
| install_date |
+--------------+
| 1558581844   |
+--------------+
```
And that time in a datetime:
```
In [3]: datetime.datetime.fromtimestamp(1558581844)
Out[3]: …
```

wmi: adding utility function to convert datetime to FILETIME

---

osquery/tables/system/linux/rpm_packages.cpp

There are two leaky situations in the `rpm_package_files` table. One almost always occurs, the failure to free the `malloc`ed `digest` and the other in rare situations where we continue early without freeing `td`.
See https://github.com/osquery/osquery/issues/6532.

rpm: Fix memory leaks in rpm_package_files

---

osquery/process/windows/process_ops.cpp

psidToString calls ConvertSidToStringSidA but never calls LocalFree on the allocated LPTSTR . #6536

Fix #6536 Leak in psidToString 

---

osquery/events/darwin/fsevents.cpp
osquery/events/tests/darwin/fsevents_tests.cpp

This attempts to fix https://github.com/osquery/osquery/issues/6024.
The issue in this flaky test is that an FSEvents callback may be invoked late in the process teardown when we cannot make assumptions about what memory is still allocated. This PR adds `FSEventStreamFlushSync`, which blocks until all existing callbacks are flushed.

fsevents: Improve testing assumptions and flush fsevents when stopping

---

osquery/events/tests/events_tests.cpp
osquery/include/osquery/events.h

This guards against a rare situation where an OS callback, such as `FSEvents` is fired very late in process execution. If this happens, the osquery process is already terminating and deallocating structures. Practically, we see these errors in CI. 
See the instances in #6024, where a log "cannot find publisher" is created.

events: Only fire if publisher exists

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/windows/shimcache.cpp
osquery/tables/system/windows/userassist.cpp
osquery/tables/system/windows/userassist.h
specs/CMakeLists.txt
specs/windows/shimcache.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/shimcache.cpp

This PR adds a shimcache table to osquery for Windows systems.  
Shimcache (Application Compatibility Cache, also sometimes called "AppcompatCache") contains entries of executed applications on Windows systems (it may also contain a list of executable's enumerated by Explorer when browsing the file system). Shimcache entries contain:
- Path of file executed
- Last modified time of the file
- An execution flag on the file (this flag does not exist on Windows 10 systems)
Additional info can be found here: https://medium.com/@bromiley/windows-wednesday-shim-cache-1997ba8b13e7
This PR enumerates all the ControlSets on a Windows system and parses the Shimcache entries.
Its been tested on Windows 8.1 and Windows 10 (Creators update)
It should also work on Windows 10 (Pre-Creators) but I do not …

Shimcache Table

---

osquery/events/linux/syslog.cpp
osquery/events/linux/syslog.h
osquery/events/tests/linux/syslog_tests.cpp

This is an initial attempt to take the awesome work from #5969 and #5232, and minify it. The original bug report is #4810.
The goal is to have a non-blocking, mostly accurate, fast enough, minimalistic `std::getline`.
There may be areas for improvement from a performance and accuracy point of view. Areas to consider, copying data from the internal buffer out to the caller, line 106; the rare/exceptional case of shifting any left over data, line 110; giving up trying to handle a line larger than 2048 bytes, line 96; others?

syslog: Replace fstream with custom non-blocking getline

---

osquery/sql/dynamic_table_row.h
osquery/tables/system/posix/shell_history.cpp
osquery/tables/system/posix/shell_history.h
osquery/tables/system/tests/posix/shell_history_tests.cpp
specs/posix/shell_history.table

This is an effort to improve the CPU and memory requirements for the `shell_history` table.
There are several changes involved:
- The table now reads files 4k at a time.
- The table processes / parses lines `std::getline` style, one at a time.
- The table uses the "yield" generation feature.
The following observations were made with `./osquery/osqueryd -S "select count(1) from shell_history where uid = 1000"`
My shell history is 500Kb.
- with no changes: `1.83s user 0.01s system 89% cpu 2.062 total`
- with chunked reading and using chunked parse: `1.82s user 0.01s system 89% cpu 2.053 total`
- with yield: `1.80s user 0.01s system 89% cpu 2.029 total`
The same observations were made:
I imagine the positive impact on memory performance will be more substantial for larger history files.

tables: Refactor shell_history to use generators

---

osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/events/linux/process_events.h
osquery/tables/events/linux/process_events.cpp
osquery/tables/events/tests/linux/process_events_tests.cpp

Add support for processing KILL, TKILL and TGKILL syscalls. The first
message of the SYSCALL message type is handled in a similar way as
EXECVE as the structure is more or less the same.
Three additional fields are parsed from the message which are "ses"
(session of the process), "comm" (the command that was executed, eg: the
script name in case of a /bin/bash invoke) and "tty" (the controlling
terminal for the process). These fields will not be published though
since the table schema doesn't support it at the moment.
The above feature is activated using the
```
--audit_allow_kill_process_events=true
```
Sample columns:
```
"columns": {
"atime": "1589007635",
"auid": "4294967295",
"btime": "0",
"cmdline": "",
"ctime": "1587237608",
"cwd": "",
"egid": "1000",
"euid": "1000",
"fsgid": …
```

Add support for processing KILL syscall

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/windows/dns_cache.cpp
specs/CMakeLists.txt
specs/windows/dns_cache.table

This PR adds a new table named `dns_cache` for Windows that utilizes the undocumented `DnsGetCacheDataTable` call in `dnsapi.dll` that will return a list of currently cached DNS names and record types. There is also a `flags` column included from the results returned by `DnsGetCacheDataTable` for which I can't say I understand the exact usage of, but it is included in case it may be of use to someone who understands the meaning of this field.

Add dns_cache table for Windows

---

osquery/tables/system/darwin/user_groups.mm
tests/integration/tables/groups.cpp
tests/integration/tables/users.cpp

This does a little refactoring on the users and groups tables. It pulls update from https://github.com/osquery/osquery/pull/5669 into the fixes on the users table
* Create a `genGroupRow` to normalize the path with and without constraints.
* Start populating results from open directory, and then fill in with getpwnam.
* Add integrations tests to check that is_hidden is populated for with and without constraints

Light refactor on users & groups

---

CMakeLists.txt
libraries/cmake/source/yara/CMakeLists.txt
osquery/tables/CMakeLists.txt
osquery/tables/yara/CMakeLists.txt
osquery/tables/yara/tests/CMakeLists.txt
specs/CMakeLists.txt
tests/integration/tables/CMakeLists.txt

The PR enables the on-demand Yara table on Windows. Currently, it is only supported on macOS and Linux.

Enable YARA table on Windows

---

cmake/flags.cmake
osquery/config/tests/config_tests.cpp
osquery/config/tests/test_utils.cpp
osquery/core/windows/wmi.cpp
osquery/core/windows/wmi.h
osquery/filesystem/windows/fileops.cpp
osquery/process/windows/process.cpp
osquery/tables/cloud/aws/ec2_instance_tags.cpp
osquery/tables/events/windows/ntfs_journal_events.cpp
osquery/tables/events/windows/powershell_events.cpp
osquery/tables/events/windows/windows_events.cpp
osquery/tables/networking/etc_services.cpp
osquery/tables/sleuthkit/sleuthkit.cpp
osquery/tables/system/tests/system_tables_tests.cpp
osquery/tables/system/windows/certificates.cpp
osquery/tables/system/windows/dns_cache.cpp
osquery/tables/system/windows/drivers.cpp
osquery/tables/system/windows/intel_me.cpp
osquery/tables/system/windows/kernel_info.cpp
osquery/tables/system/windows/logon_sessions.cpp
osquery/tables/system/windows/registry.cpp
osquery/tables/system/windows/scheduled_tasks.cpp
osquery/tables/system/windows/services.cpp
osquery/tables/system/windows/shimcache.cpp
osquery/tables/system/windows/windows_security_center.cpp
osquery/tables/system/windows/windows_security_products.cpp
osquery/tables/utility/file.cpp
osquery/utils/system/windows/env.cpp

Define UNICODE and _UNICODE preprocessors. This will result in Windows API function macros defaulting to the wide implementation instead of the ANSI (local) implementations. This PR ought to be the final PR in the line of PRs that aim to resolve internationalization/localization issues observed in osquery on Windows.
This should resolve #2569 from 2016. :-)
Please encourage future PR submitters to not call the *A functions but the *W functions instead.

Define UNICODE and _UNICODE preprocessors for windows

---

docs/wiki/deployment/logging.md
osquery/core/query.cpp

The schedule counter increments every query execution. This is true even when a query has no new results to log. The Current behavior, which increments the query counter every execution, makes it difficult to determine whether or not a differential result was missed. 
Change the counter behavior so only when a differential results is calculated the counter increments. With this change the counter represents the order in which differential results should be replayed to recreate the point in time state.
Looking for initial thoughts on this change. The documentation and original PR #3651 suggest the counter is only ever useful to detect the initial results. Changing the counter behavior this way doesn't break this use case.

Update schedule counter behavior

---

osquery/filesystem/fileops.h
osquery/filesystem/windows/fileops.cpp
osquery/tables/system/windows/ie_extensions.cpp
osquery/tables/utility/file.cpp
specs/utility/file.table
tests/integration/tables/file.cpp

I have added the file_version column to the file table for windows. I have used the approach of adding a new parameter to the windowsGetFileVersion(). I have refactored the name of the method as well as the parameters. Here is a blueprint of the same:
/*
* @brief Get the product and file version associated with a file
*
* @param path: Full path to the file
* @param product_version: String representing the product version, e.g. "16.0.8201.0"
* @param file_version: String representing the file version
* @return Success if the version could be retrieved, otherwise failure
*/
Status windowsGetVersionInfo(const std::string& path, std::string& product_version, std::string& file_version);
I have added the additional field for the fileVersion in the row structure as well as have placed a …

Fix #5737: Add FileVersionRaw column to file table for windows

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/tests/filesystem.cpp

The readFile function in the filesystem package takes a size param, however this size param is ignored unless the file is a "special" file (I suppose a device file). This change fixes the readFile function to observe the requested read size.

Fix readFile to observe requested read size

---

osquery/events/tests/events_tests.cpp
osquery/include/osquery/events.h

Some event publishers use `EventFactory::fire` to queue events from a callback back into their publisher instances. In these cases, and perhaps others, the `::getType` function is hot. We want to speed this up by preventing allocations.
This strategy improves the performance by nearly 43% on optimized builds.

events: Memoize EventFactory::getType

---

libraries/cmake/source/librpm/CMakeLists.txt

Starting in glibc 2.25, the macros `major` and `minor` were moved
from `<sys/types.h>` to `<sys/sysmacros.h>`, to stop leaking these
common words into the global namespace of those including <stdlib.h>
https://sourceware.org/bugzilla/show_bug.cgi?format=multiple&id=19239
The macros MAJOR_IN_MKDEV and MAJOR_IN_SYSMACROS would be defined if
necessary by autoconfig, and put in `config.h`. But osquery build
uses CMake instead of autotools, with a git-committed `config.h`.
This generally is all right across Ubuntu variations, as an automake
for one will likely make a config.h that works on others. However
the glibc change makes a "one-size-fits-all-Ubuntu" config impossible.
This mirrors detection done by autoconf/headers.m4 as CMake code.
It is a relatively simple patch, which unblocks …

CMake detect MAJOR_IN_SYSMACROS/MKDEV for librpm

---

CMakeLists.txt
azure-pipelines.yml

Pip is warning us that a newer version is available.
```
Installing collected packages: psutil, timeout-decorator, six, thrift, argparse, future, osquery, pywin32
Running setup.py install for timeout-decorator: started
Running setup.py install for timeout-decorator: finished with status 'done'
Running setup.py install for thrift: started
Running setup.py install for thrift: finished with status 'done'
Running setup.py install for future: started
Running setup.py install for future: finished with status 'done'
Successfully installed argparse-1.4.0 future-0.18.2 osquery-3.0.6 psutil-5.7.2 pywin32-228 six-1.15.0 thrift-0.11.0 timeout-decorator-0.4.1
python.exe : WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
At …
```

ci: Fix pip upgrade warning

---

osquery/process/windows/process_ops.cpp

On my windows test host I was encountering falling calls to ConvertSidToStringSidA() inside getUidFromSid(). Following a failed call we call LocalFree() on a potentially uninitialized pointer sidString. This was resulting in a segfault. Initializing the pointer to null fixes the crash.

Fix call to LocalFree() on uninit ptr inside getUidFromSid()

---

osquery/core/system.cpp

Fixes #6581. In PR #6569 I fixed the readFile function to respect the requested read size. This tickled a bug in the createPidFile function which was incorrectly using the readFile API. The original intent of the call to readFile was to pass dry_run = true meaning "don't actually read file contents." This stopped working when there was a size param inserted in the API and the 'true' became a requested read size of 1. Now that we respect the size in readFile, createPidFile was getting a short read. In this PR I remove the 'true' entirely because there was also a different change that uses the data from pidfile made later so it actually depends on dry_run being false. Gotta love it when bugs are stacked 3 deep.

Fix incorrect readFile params in createPidFile

---

osquery/tables/events/windows/powershell_events.cpp

This should fix #6583, caused by the recent Windows Event Log refactor. The malformed_field variable was originally a counter, which was then turned into a boolean flag. When this change happened, two of the original lines that incremented the value survived, causing the bool++ issue.

powershell_events: Fix bool type usage

---

README.md
cmake/packaging.cmake
docs/README.md
docs/doxygen/mainpage.md
docs/wiki/development/creating-tables.md
osquery/core/plugins/sql.cpp
osquery/core/plugins/sql.h
osquery/devtools/devtools.h
osquery/devtools/shell.cpp
osquery/extensions/thrift/osquery.thrift
osquery/tables/system/efi_misc.h
osquery/tables/system/linux/portage.cpp
osquery/tables/system/windows/kva_speculative_info.cpp
specs/curl.table
tools/ci/scripts/install_openssl_formula_dependencies.ps1
tools/codegen/genwebsitejson.py
tools/codegen/genwebsitemetadata.py
tools/deployment/copyright.debian
tools/deployment/make_windows_package.ps1
tools/deployment/osqueryctl
tools/windows_resources.rc.in

Update the remaining copyright notices that were unscripted oddballs, and missed in #6589
These are predominately ones that feature additional additional authors. I kept them, but I don't know if we can include them in the broader "osquery authors" flag.
This also adjusts several of the oneline copyright blocks.
And updates a several old github URLs.

Manual copyright changes

---

osquery/extensions/impl_thrift.cpp

The PR sets the global output function for the Thrift server. This prevents throwing up the error log on `stderr` while testing the Thrift socket. It also enables the error logging in the verbose mode as suggested by @Smjert.
Related to #6152

Set global output function for Thrift 

---

tools/deployment/osqueryd.service

osquery can start without a configuration file and will start even if the specified config file does not exist, so there is no need to create an empty config before starting the service. This PR addresses https://github.com/osquery/osquery/issues/6381.
Presumably this `ExecStartPre` command was added to suppress the warning that osquery logs if it cannot open the config file specified with the `--config_path` flag. If that is true, a better way to handle that may be to create a small shell script that only starts `osqueryd` with either/both of the `--flagfile` and `--config_path` flags if the corresponding files exist.
Fixes: #6381

Remove ExecStartPre from systemd service unit -- do not create empty config file

---

osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp
osquery/core/watcher.h

This fixes an unintended effect of the `--watchdog_delay` only being applied to the first worker start. This delay was intended to be applied to each restart of the worker. The goal is to allow a worker to do process and memory intensive work during start up.

bug: Apply watcher delay each time the worker is started

---

osquery/core/shutdown.cpp
osquery/core/shutdown.h
osquery/main/main.cpp

It's sort of annoying for `--database_dump`, `--config_check`, etc to only return with an exit code in `osqueryd`. The shell should mimic this behavior.

shell: Return early if relative flags are used

---

libraries/cmake/source/rocksdb/CMakeLists.txt
plugins/database/rocksdb.cpp
plugins/database/rocksdb.h
plugins/database/tests/utils.cpp

This changes how we build RocksDB such that the entire library is built (not just the "lite" version), which includes important SST file management utilities. One of these utils allows us to compact a range of smaller SST files.
*Why does our usage create small SST files?*
When we restart the database to flush large allocations, we flush or sync the data into an immutable SST. This happens behind the scenes as part of RocksDB's normal operating procedure. There's really no problem with this other than esthetics and occasionally lots of file IO if you build up a lot of buffered logs and then need to flush them quickly.
*What does this change 'cost'?*
Expect longer startup times and more initial I/O when starting as the immutable files will be scanned and checked. With multi-100MB files …

bug: Fix buildup of RocksDB SST files

---

CONTRIBUTING.md
README.md
SECURITY.md
SUPPORT.md
docs/wiki/index.md
tools/deployment/make_windows_package.ps1

The old slackin Heroku app is no longer supported, but we now have an official way to allow public invites.

docs: Replace slackin with Slack shared invite

---

osquery/tables/yara/tests/yara_tests.cpp
osquery/tables/yara/yara.cpp
osquery/tables/yara/yara_utils.cpp
osquery/tables/yara/yara_utils.h
specs/yara/yara.table
tests/integration/tables/yara.cpp

The PR adds a new column `sigrules` that can be used to pass a small set of YARA signature with the query. 
```
osquery> select * from yara where path = '/etc/passwd' and sigrules = 'rule always_true { condition: true }';
+-------------+-------------+-------+-----------+---------+--------------------------------------+---------+------+
| path        | matches     | count | sig_group | sigfile | sigrules                             | strings | tags |
+-------------+-------------+-------+-----------+---------+--------------------------------------+---------+------+
| /etc/passwd | always_true | 1     |           |         | rule always_true { condition: true } |         |      |
+-------------+-------------+-------+-----------+---------+--------------------------------------+---------+------ …
```

Add `sigrules` to pass YARA signature with query

---

osquery/dispatcher/scheduler.cpp

One of the reasons osquery creates small SSTs is because write buffers are flushed to immutable tables every 5 minutes. We are addressing this by compacting the SSTs but a side effect is more CPU time spent when databases are opened. We mitigate that with longer reset periods. We still want a reset until we can more deeply understand the effect of very-long persistent handles.

database: Change reset interval from 5m to 1hr

---

osquery/config/config.h
osquery/core/plugins/CMakeLists.txt
osquery/core/plugins/logger.h
osquery/core/plugins/sql.h
osquery/core/tables.h
osquery/database/database.h
osquery/distributed/distributed.cpp
osquery/distributed/distributed.h
osquery/experimental/events_stream/events_stream_registry.h
osquery/extensions/extensions.h
osquery/logger/data_logger.h
osquery/logger/logger.cpp
osquery/logger/tests/logger.cpp
osquery/numeric_monitoring/plugin_interface.cpp
osquery/numeric_monitoring/plugin_interface.h
osquery/registry/registry.h
osquery/registry/registry_interface.h
osquery/remote/enroll/enroll.h
osquery/sql/sql.cpp
osquery/sql/sqlite_util.cpp
plugins/logger/aws_firehose.h
plugins/logger/aws_kinesis.h
plugins/logger/aws_log_forwarder.h
plugins/logger/buffered.h
plugins/logger/filesystem_logger.h
plugins/logger/kafka_producer.h
plugins/logger/stdout.h
plugins/logger/syslog_logger.h
plugins/logger/tls_logger.h
plugins/logger/windows_event_log.h

The previous include path for `osquery/core/plugins` was `osquery/plugins`. We want this to instead match the layout on disk to assist with IDEs and other tools.

refactor: Change the include path for osquery/core/plugins

---

osquery/core/init.cpp

Fixes #6613.
There should be a test for this but `test_osqueryi` is not working right now. I will try to address this in a follow up.

bug: Force shell to disable watchdog and logger

---

specs/processes.table

The cpu_type and cpu_subtype description in the processes table is a duplicate of upid and uppid. Kindly review.
This PR fixes #6351

Improve descriptions for table: processes

---

cmake/flags.cmake

thirdparty_librdkafka_c was failing to compile
due to the C11 keyword _Thread_local not being recognized.
Note: This began failing recently due to a CMake update in the Windows agent which "respects" our request to use C11.

Fix Windows build removing non existing C11 conformance

---

docs/wiki/installation/cli-flags.md
osquery/dispatcher/scheduler.cpp
osquery/dispatcher/scheduler.h
osquery/dispatcher/tests/scheduler.cpp
plugins/config/tests/tls_config_tests.cpp

Previously, we were not applying `--scheduler_timeout` correctly. This should be the number of seconds for the scheduler to run. After the schedule is completed the daemon should stop.

Apply scheduler_timeout correctly

---

osquery/core/system.cpp
osquery/events/events.cpp

Thread names are limited to 16 characters include the ending `\0`.

bug: Set thread names correctly on macOS and Linux

---

osquery/core/init.cpp
osquery/database/database.cpp
osquery/database/database.h

The "initializer" includes helpful database open retry logic. We should move this into the database APIs such that every usage of `initializeDatabase` benefits from the retry.

database: Move initialization retry logic into DB API

---

osquery/remote/tests/test_utils.cpp
osquery/remote/tests/test_utils.h

The goal is to address #6630. I do not think we can remove the non-determinism of starting the TLS server. But we can adapt where the delay/waiting occurs to match where the OS might lag. We should wait longer between starting the Python script and expecting a listening server.

tests: Improve the reliability of TLSServerRunner

---

tools/tests/test_base.py
tools/tests/test_osqueryd.py

I see that `test_2_daemon_with_option` tends to be flaky, for example https://github.com/osquery/osquery/runs/1050124927
I think it is because we are over-complicating the search for `osqueryd.INFO`. We do not need to use `osqueryi` to enumerate these files, instead we can look for the well known symlink. This puts the search for the file existence under the retry logic. It will not remove the non-determinism but it should help protect from false positive errors.

tests: Fix flaky test_2_daemon_with_option

---

libraries/cmake/source/gflags/CMakeLists.txt
libraries/cmake/source/glog/CMakeLists.txt

I am looking through `compile_commands.json` for third party library headers included with `-I`. I would like for them all to be `-isystem`.
This is a stepping stone towards adding `-Wconversion` to our code.

libs: Set glog and gflags includes as SYSTEM

---

osquery/core/init.cpp
osquery/database/database.cpp
osquery/database/database.h
plugins/database/rocksdb.cpp
plugins/database/sqlite.cpp

This removes a confusing feature of "falling back" to a read only version of the backing persistent storage/database. In the cases where someone requests persistent storage (aka default usage of `osqueryd`, or `osqueryi` with an explicit `nodisable_database` or `database_path` set) we should not 'behind the scenes' fall back to an in-memory version if an error occurs. Additionally, the read only support for RocksDB has not been well tested by our project.

database: Remove read only concept

---

osquery/tables/yara/yara.cpp
osquery/tables/yara/yara_utils.cpp
osquery/tables/yara/yara_utils.h
specs/yara/yara.table

The PR adds a new column `sigurl` that can be used to pass the url from where the YARA signature can be downloaded for the scan. The signature urls need to be pre-registered with the configuration file. 
```
// Configuration file for registering the URL's 
"yara": { 
"signature_urls": { 
"sig_url_1": "https://raw.githubusercontent.com/Yara-Rules/rules/master/cve_rules/CVE-2010-0805.yar", 
"sig_url_2": "https://raw.githubusercontent.com/Yara-Rules/rules/master/crypto/crypto_signatures.yar", 
"sig_url_3": "https://raw.githubusercontent.com/Yara-Rules/rules/master/malware/APT_APT3102.yar"
}
}
```
The feature will be disabled by default and can be enabled with a hidden flag `enable_yara_sigurl`. It also forces all the strings to be private, if the rules are downloaded from url unless . The …

Add `sigurl` to get the YARA signature from https server for scan 

---

osquery/tables/system/windows/wmi_bios_info.cpp

https://github.com/facebook/osquery/issues/5244
Fixes blank results for wmi_bios_info table. In looking at other examples in the code base, you must use (BTSR)L"wmi\\namespace" instead of (BTSR) "wmi\\namespace", otherwise you get blank results.

Fix BIOS Info table searching.

---

tools/deployment/osqueryd.service

With newer versions of systemd, this will prevent `osqueryd` from using more than 20% of a single CPU.
I tested this at 10% with audit enabled and with pegging the CPU with process creations (200/s) and audit does lose more data (about 9-10% data loss actually). I tested at 20% and there is no data loss.

systemd: Limit osqueryd CPU usage to 20%

---

osquery/tables/system/tests/windows/registry_tests.cpp
osquery/tables/system/windows/ie_extensions.cpp
osquery/tables/system/windows/registry.cpp
osquery/tables/system/windows/registry.h

This improves the performance of querying the Windows registry when using `queryMultipleRegistryKeys`. It also improves the accuracy for when SQL statements merge their LIKE operators into a single call of `genRegistry`. It looks like there was a bug in the registry globbing that assumed the result parameter would be fresh/empty.

Improve performance and accuracy of Windows registry querying

---

tools/tests/test_base.py

I notice that some python tests are flaky and that we try to handle this by running them multiple times, expecting a single success. This flaky test handler does not reset the state of the test so tests that fail once are prone to fail again.
This aims to reset some of the state by running the `setUp` method again.

tests: Improve flaky python test handling

---

osquery/tables/system/tests/windows/registry_tests.cpp
osquery/tables/system/windows/drivers.cpp
osquery/tables/system/windows/registry.cpp
osquery/tables/system/windows/registry.h

This supersedes https://github.com/osquery/osquery/pull/6059.
There is a bug in the `drivers` table that prevents `image` from being populated. A value is mistakenly used as a key.
This PR also improves the accuracy of the table by fixing an error in SQL. And the PR improves the table performance by bypassing the SQL/SQLite abstractions.
The user and system time end up at about 50% of the previous implementation.

Fix image column within drivers table on Windows

---

specs/carves.table

There are some small bugs in the `carves` specs:
- This does not require a join to `users`
- `path` is only required when `carve=1`, otherwise the table is designed to full-scan without needing `path` populated.

carver: Update carves specs to allow full scan

---

osquery/sql/sqlite_operations.cpp

This is a small change to make carving requests that use `carve(PATH)` clearer. If the function-based carving is disabled the result should be an error statement.

carver: Emit an error if the carve function is disabled

---

osquery/carver/carver.cpp
osquery/carver/carver.h
osquery/carver/tests/carver_tests.cpp

I plan to refactor some of Carver. Before I start I wanted to improve the test coverage slightly by testing `::start`.

carver: Improve tests by faking postCarve

---

cmake/flags.cmake
osquery/tables/networking/curl_certificate.cpp
specs/curl_certificate.table

to Fix #6615 i've updated curl_certificates to have a timeout so it doesn't hang forever. It works by setting up the socket, setting a recv timeout, connecting, and then passing the socket into BIO to complete the TLS handshake.
I've tested this on Mac, Windows, and Linux and should provide feature parity with the old BIO-based implementation (supports ipv6 and ipv4).  I've added an optional timeout parameter to the table that allows the user to set a timeout in seconds for their query.  It defaults to 3s.
@theopolis this is ready for review now.

curl_certificate: Implement configurable timeout through WHERE clause

---

osquery/utils/aws/aws_util.cpp

Support additional AWS regions.

Add AWS regions

---

osquery/tables/system/windows/windows_eventlog.cpp

While reading the event log records in batches the windows function `EvtNext` returns with invalid array bound error (`RPC_S_INVALID_BOUND`). This is unusual behavior and causes inconsistency in the results of `windows_eventlog` table. 
The fix handles the error by reseting the query handler at the previous best position and retrying the `EvtNext` with reduced batch size. 
Related to #6650 
Query result with the fixes:
```
osquery> select eventid,count(*) from windows_eventlog where channel="Security" group by eventid;
+---------+----------+
| eventid | count(*) |
+---------+----------+
| 1100    | 1        |
| 4608    | 1        |
| 4616    | 2        |
| 4624    | 26       |
| 4625    | 36198    |
| 4634    | 4        |
| 4647    | 1        |
| 4648    | 4        |
| 4672    | 24 …
```

Fixed handling of invalid array bound error with EvtNext function

---

osquery/tables/networking/curl_certificate.cpp

This fixes undefined behavior where `temp_c` has the allocated space to hold content but the internal state is confused. The `.clear()` resets the size to be 0, where the code's intention is to reset the default values.

Fix container overflow in curl_certificate

---

osquery/tables/system/windows/authenticode.cpp

Fix for #6401. Authenticode table will now show signature information for files, which themselves are not signed, but whose hashes are in a signed system catalog file.

feature 6401: authenticode table with catalog file info

---

docs/wiki/deployment/debugging.md
osquery/sql/tests/virtual_table.cpp
osquery/sql/virtual_table.cpp

This implements #6684.
If someone is interested in debugging these logs you can use `--table_exceptions` and the binary with rethrow the exception.

Add broad exception catching for table execution

---

cmake/modules/Findcppcheck.cmake

This PR adds a clause to the CMake that finds the `cppcheck` executable, that also finds it on macOS. Tested with `brew install cppcheck` which is the instruction step that I recently added to the build documentation.
To test:
```
cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 ..
cmake --build . --target cppcheck
```

Add cppcheck support to macOS

---

osquery/core/init.cpp

I found that `stdout` is not always flushed with `--help`. For example, `osqueryi --help | grep 'osquery.io'` may not find the epilog.

Flush stdout with --help

---

tools/tests/test_base.py
tools/tests/test_osqueryd.py
tools/tests/test_osqueryi.py
tools/tests/utils.py

This PR aims to reduce the flakiness of `test_osqueryi` by reducing the complexity of flag usage. It also adds the 'default flags' to `TimeoutRunner`, preventing local state from impacting the tests.

tests: Reduce flakiness of test_osqueryi

---

osquery/tables/events/linux/process_events.cpp

`stat` returns `0` on success.

Fix incorrect stat return checking within process_events

---

osquery/core/init.cpp
osquery/filesystem/darwin/bsd_file_flags.cpp
osquery/filesystem/tests/darwin/bsd_file_flags_tests.cpp

On macOS, there are several additional bsd_flags that may be set. These are not documented in the man page, but are documented in the header file.
(plus a tiny unrelated spelling fix)
```
osqueryd --verbose -S "select bsd_flags from file where path = '/private/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordFound'"
I1006 12:09:15.603936 82957760 init.cpp:343] osquery initialized [version=4.4.0]
I1006 12:09:15.627223 82957760 file.cpp:107] The following file had undocumented BSD file flags (chflags) set: "/private/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordFound"
+------------+
| bsd_flags  |
+------------+
| 0x00080000 |
+------------+
```
After patch:
```
dover:build seph$ ./osquery/osqueryd --verbose -S "select bsd_flags from file where path = …
```

Add additional file stat flags to darwin (bsd_flags)

---

osquery/tables/system/tests/darwin/startup_items_tests.cpp
tests/integration/tables/apps.cpp

Fixes couple of unit tests that are failing on Catalina because of minor differences between Mojave and Catalina. 
Uncovered these when I moved the Azure worker to Catalina for EndpointSecurity related PR.

[macOS][Tests] Fix tests on Catalina

---

packs/ossec-rootkit.conf

This PR adds Reptile rootkit inline with ossec: https://github.com/ossec/ossec-hids/blob/master/src/rootcheck/db/rootkit_files.txt#L409
Reptile rootkit files mentioned in their wiki: https://github.com/f0rb1dd3n/Reptile/wiki/Install#uninstalling

Add Reptile rootkit to ossec-rootkit pack

---

osquery/tables/system/linux/shadow.cpp

Add branch to if statement to detect empty, but not null, passwords.
I don't see how to easily add test cases here, and can't readily test this
Fixes: #5465

Fix shadow table to detect empty passwords
