- include/osquery/config.h
- include/osquery/events.h
- osquery/config/config.cpp
- osquery/config/config_tests.cpp
- osquery/core/CMakeLists.txt
- osquery/core/init.cpp
- osquery/events/events.cpp
- osquery/scheduler/scheduler.cpp
- tools/tests/test.config
While catching the expected runtime_error when accessing the DB late during run within an event emit/yield I found that config testing needed some help. To make the config tests more "unit"-y: the ctor is now an explicitly called member function `load`. The config test now forces filesystem as the retriever and uses a known-test config instead of a variable runtime/production config from whatever plugin was used as default.
> [Fix #560] Improve config tests

- CMake/FindGlog.cmake
- include/osquery/events.h
- osquery/events/events.cpp
This moves the ending decision/boolean into the publisher but also fixes a bug that caused inotify to log more often than. 
The inotify publisher shouldFire method should be the cause of https://github.com/facebook/osquery/issues/559
> Fix shouldFire pubsub virtual

- tools/provision.sh
gems is not installed in Ubuntu 12 and it does not install with the ruby-dev package, installing it to avoid the build to break
> Installing gems in Ubuntu 12 to avoid error

- tools/provision.sh
@marpaia I was trying to build from a base CentOS (vagrant) and noticed that the makeinfo bin was missing, thus this adding texinfo. I think you're build problem in: https://github.com/facebook/osquery/issues/611 is from left-over build targets. Maybe `make distclean` (which will delete third-party package sources in .source) then destroy your centos and try again. 
Can you try without this PR and let me know if makeinfo was installed?
> Add texinfo to CentOS provision

- include/osquery/config.h
- include/osquery/scheduler.h
- include/osquery/tables.h
- osquery/config/config.cpp
- osquery/config/config_tests.cpp
- osquery/config/plugins/filesystem.cpp
- osquery/core/CMakeLists.txt
- osquery/core/init.cpp
- osquery/core/tables.cpp
- osquery/core/tables_tests.cpp
- osquery/core/virtual_table.cpp
- osquery/core/virtual_table.h
- osquery/scheduler/scheduler.cpp
- osquery/scheduler/scheduler_tests.cpp
This adds basic testing of virtual_table/tables `QueryContext` and constraints usage.
This includes:
1. Moving `TablePlugin` from the internal `virtual_tables.h` to the public `tables.h` such that modules may subclass this directly instead of a forced spec/genapi.py pattern.
There are some addons here:
1. Move the splay operations to scheduler.
2. Announce the osquery version in verbose log during init.
3. Filesystem ConfigPlugin retriever should verbose announce the config path.
> QueryContext unit tests and splay/config updates

- osquery/events/darwin/iokit_hid.cpp
See: #617 for the inline reference with "slightly more" context on the issue.
> Treat IOKit HID failures as warnings

- osquery/core/virtual_table.h
If xBestIndex is called multiple times during query planning: to determine the best/lowest query cost the intermediate query constraints must be cleared.
> [Fix #630] Clear stacking index plans

- osquery/core/darwin/conversions.cpp
- osquery/tables/system/darwin/nvram.cpp
1. Remove CFData -> std::string parsing within the NVRAM virtual table.
2. Move LOG(ERROR) -> VLOG(1) for in-table handled error states.
3. Organize logic to discourage goto.
> Remove goto/sprintf from NVRAM parsing

- include/osquery/hash.h
- osquery/config/config.cpp
- osquery/core/CMakeLists.txt
- osquery/core/hash.cpp
- osquery/tables/specs/x/hash.table
- osquery/tables/utility/hash.cpp
I have added in SHA1 and SHA256 into the hash table so they can be easily checked against other services.
There is darwin specific code in this which is organized with pre-processor macros. darwin systems use 
`#import <CommonCrypto/CommonDigest.h>`
where as all other systems use 
```
#include <openssl/sha.h>
#include <openssl/md5.h>
```
> Added SHA1 and SHA256 in Hash Table

- osquery/tables/specs/darwin/iokit_devicetree.table
- osquery/tables/system/darwin/iokit_registry.cpp
To address #640, this removes `location` and `service` (a boolean to mean the device provides an IOService) from `iokit_registry` and removes the device tree constraint from the IOKit query. Then `iokit_registry` becomes a more-latent query and is not device-centric. Since a non-plane-specific request to IOKit does NOT mean a result superset of all planes we include a `iokit_devicetree`. This device tree is only IOKit plane represented as a table in osquery as it is quite important and other plane (ACPI/PCI/USB) information is surfaced in more-agnostic forms.
The `iokit_devicetree` has a bit of overlap with `iokit_registry`. However, the `name` will differ since the IOKit entry was queried using the DeviceTree plane (odd, but OK). The most important addition to the new table is the …
> Separate IOKit devicetree from registry

- tools/provision.sh
Provision fails in Ubuntu systems because doxygen and gflags missing, this PR updates the provision.sh script to fix that
> Provision fails in Ubuntu systems because doxygen and gflags missing

- tools/provision.sh
If gflags is installed before cmake, make deps will fail
> gflags should install after cmake

- osquery/tables/networking/utils.cpp
Fixing a bad coding practice of using strcpy. Changed to strncpy with the appropriate length.
> Fixing the last strcpy

- include/osquery/status.h
- osquery/core/test_util.cpp
Adds useful operators to the `Status` class. Enables niceties such as:
```c++
Status s = doSomething();
ASSERT_EQ(Status(), s);
```
And when the assertion fails, the expected and actual statuses will be pretty-printed.
> Add useful operator implementations to Status

- Makefile
- osquery/CMakeLists.txt
Different packages for different Ubuntu distros, directories created both precise and trusty, and the changes keep the support forward
> Different packages for different ubuntu distros

- include/osquery/sql.h
- osquery/CMakeLists.txt
- osquery/core/sql.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/filesystem_tests.cpp
- osquery/main/daemon.cpp
This adds a watcher/worker model for osqueryd: on load the process will continue to fork and monitor the child for (1) exceptions/aborts, (2) process utilization violations, (3) memory consumption violations. It can also take action if (4) the worker exits, or is killed, too frequently. 
Immediate observations:
* Because of the fork there is a duplication of phys memory on load. 
** In practice on Ubuntu 14.04 this is 800kB of memory.
* The performance limits are defines in worker.cpp and could be part of a configurable profile.
* Rewriting the process name only affects ps/libproc tools.
* tables.h is now an include dependency in sql.h.
> Adding a watcher/worker model for osqueryd

- include/osquery/core.h
- include/osquery/tables.h
- osquery/core/sqlite_util.cpp
- osquery/core/sqlite_util_tests.cpp
- osquery/core/tables.cpp
- osquery/core/tables_tests.cpp
- osquery/core/virtual_table.cpp
- osquery/database/db_handle.cpp
- osquery/tables/templates/default.cpp.in
This new getQueryColumns function allows us to determine what columns
will be returned by executing a given query. It is intended to be used
with the distributed query system, to determine a schema for the
results before sending the query.
Tested by unit tests. Also used valgrind and did not find errors that
looked related to this change (though there appear to be many errors
related to glog logging).
> Add getQueryColumns function to core

- osquery/filesystem/filesystem.cpp
Support paths like this:
```
/b%/b%
```
To get:
```
/bin/bash
```
> First iteration to support letter wilds in file paths

- osquery/tables/system/darwin/process_open_descriptors.cpp
We were allocating space for the data but left out a system call to actually acquire it. The system call has now been added.
> Fixed open sockets on OS X

- include/osquery/core.h
- include/osquery/database/db_handle.h
- include/osquery/dispatcher.h
- include/osquery/filesystem.h
- include/osquery/tables.h
- osquery/CMakeLists.txt
- osquery/core/CMakeLists.txt
- osquery/core/init.cpp
- osquery/core/system.cpp
- osquery/core/tables.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/database/db_handle.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/extensions/extensions.cpp
- osquery/filesystem/filesystem.cpp
- osquery/main/daemon.cpp
- osquery/main/shell.cpp
- osquery/sql/sql.cpp
- osquery/sql/sql_tests.cpp
- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/darwin/startup_items.cpp
- osquery/tables/system/darwin/xattr.cpp
- osquery/tables/system/linux/acpi_tables.cpp
- osquery/tables/system/linux/processes.cpp
* The watcher/worker model on OSX was flawed in that it forked without execing itself. 
* The worker now execs after setting an environment variable indicating the daemon should skip startup checks.
* `OSQUERYD_WORKER` indicates a worker should skip setting pid, checking DBInstance, and some logging.
* The performance monitoring of the worker was latent in most cases because of the implicit requirement to start an in-memory SQL database.
* This now skips the SQL and emits data directly from the processes table plugin using `Registry::call`. 
* On OSX CPU time is measured with different precision that Linux, the watcher now monitors utilization accordingly.
* The precision on OSX would cause an integer overflow in abort the watch (thus worker) within a reasonable amount of time.
* The …
> Harden watcher for more perf, use exec and watch from worker

- osquery/extensions/extensions.cpp
Extensions will fail (SIGABRT) since they ONLY expose a thrift service. osqueryd/osqueryi, the extension manager, is optional.
> [Fix #713] Do not abort if EM fails

- osquery/tables/system/darwin/apps_tests.cpp
This is a quick test add to make sure that the apps table returns data that we were expecting. It fails if /Applications does not return Safari
> Adding test to make sure Apps table returns real data

- include/osquery/tables.h
- osquery/tables/CMakeLists.txt
- osquery/tables/specs/darwin/preferences.table
- osquery/tables/system/darwin/nvram.cpp
- osquery/tables/system/darwin/preferences.cpp
`select * from preferences` is the equivalent to OS X `defaults` without setting a domain (application ID) or plist path to infer a domain from. There's quite a bit of data and running it as a user may expose potentially sensitive data. Schedule this as ROOT only!
> Added 'defaults' table called 'preferences'

- osquery/tables/system/darwin/process_open_descriptors.cpp
- osquery/tables/system/darwin/processes.cpp
1. Every process-related table should use PID as a constraint.
> [#721] Add pid constraint checking to darwin procs

- CMake/Packages.cmake
- CMakeLists.txt
- include/osquery/registry.h
- osquery/CMakeLists.txt
- osquery/filesystem/linux/proc.cpp
- osquery/tables/networking/linux/process_open_sockets.cpp
- osquery/tables/system/linux/processes.cpp
- tools/provision.sh
A working test of CentOS7 without fortify, which causes NL socket reads to hang.
> Testing CentOS7 clang 3.5 without fortify

- include/osquery/extensions.h
- osquery.thrift
- osquery/extensions/extensions.cpp
- osquery/extensions/extensions_tests.cpp
This allows extensions to execute SQL through the extensions API.
> Add thrift 'query' endpoint

- include/osquery/extensions.h
Fixing a silly inconsistency with reporting socket locations for the core extension manager.
> Fix osquery_extensions listing .0 for the core

- Makefile
```
[root@localhost vagrant]# make sync
mkdir -p build/sync
rm -rf build/sync/osquery*
cp -R osquery build/sync
cp -R include/osquery build/sync
cp -R build/centos6/sdk/generated/ build/sync/osquery
cp osquery.thrift build/sync/osquery/extensions
find build/sync -type f -name "CMakeLists.txt" -exec rm -f {} \;
mkdir -p build/sync/code-analysis
cd build/sync/code-analysis && SDK=True cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../../../
CMake Warning at CMakeLists.txt:95 (message):
Requested dependencies may have changed, run: make deps
-- Building for CentOS
-- Found components for DL
-- Found readline library
-- Looking for include files libunwind.h, unwind.h
-- Looking for include files libunwind.h, unwind.h - not found
-- Found RocksDB
-- Thrift version 0.9.1
-- Found library dependency …
```
> add version of osquery to sync tarball

- Makefile
- include/osquery/core.h
- include/osquery/dispatcher.h
- include/osquery/extensions.h
- include/osquery/registry.h
- include/osquery/sdk.h
- osquery.thrift
- osquery/core/init.cpp
- osquery/core/test_util.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/distributed/distributed_tests.cpp
- osquery/examples/example_extension.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/extensions_tests.cpp
- osquery/filesystem/darwin/plist_tests.cpp
- osquery/main/lib.cpp
- osquery/registry/registry.cpp
- osquery/sql/sql_tests.cpp
- osquery/tables/specs/x/file.table
- osquery/tables/specs/x/hash.table
- osquery/tables/specs/x/osquery_extensions.table
- osquery/tables/specs/x/osquery_flags.table
- osquery/tables/specs/x/osquery_info.table
- osquery/tables/specs/x/time.table
- osquery/tables/templates/default.cpp.in
- tools/codegen/gentable.py
Many things extensions-related.
An extension is made with the `sdk` make target. By default the example_extension is built that registers an example table. Running example_extension will check for an active osquery process, attempt to register, and on success enter a Thrift blocking server join. It will not end until the osquery core process is shutdown or something interrupts the process.
There's one removed unit test that only existed because extensions would broadcast the duplicate "utility" tables includes in libosquery. We've added a "internal" flag to registry items (plugins), which are not broadcasted. The "utility" tables are marked as such and the table generation code flags these tables as internal registry items.
There are a couple final SQL implementation abstractions brought …
> Building example extension with SDK

- osquery/filesystem/linux/proc.cpp
- osquery/tables/networking/linux/process_open_sockets.cpp
> [Fix #792] Replace std::regex with string parsing gcc below 4.9

- include/osquery/flags.h
- include/osquery/registry.h
- osquery/core/flags.cpp
- osquery/core/init.cpp
- osquery/extensions/extensions.cpp
- osquery/registry/registry.cpp
- osquery/tables/specs/x/osquery_registry.table
- osquery/tables/utility/osquery.cpp
#797 Use --socket for extensions, limit help
#796 Add an 'active' concept to registries, support a blank item call
#798 Add osquery_registry to list the internal/external plugin details
> Extensions helpers, API additions

- CMakeLists.txt
- osquery/extensions/CMakeLists.txt
- requirements.txt
- tools/provision.sh
- tools/tests/test_extensions.py
Use osquery-C flags for every object compile.
Add CXX flags without conditional logic.
Move the `python-thrift` target into the CPP generation command.
Remove verbose option for extensions python unittest.
Add thrift as a pip install requirement (for unittests).
This will *hopefully* fix #806, it's very loosely tested with cmake CLI Cflags overrides.
> Respect external CMake C/CXX flags

- tools/provision.sh
We should install CMake on both CentOS 6.5/7, since we install boost on both, let's move both CMake & boost after clang.
> [Fix #823] Install cmake/boost after clang on centos

- osquery/core/conversions.h
- osquery/core/darwin/conversions.cpp
- osquery/tables/specs/darwin/kernel_extensions.table
- osquery/tables/system/darwin/kernel_extensions.cpp
- tools/tests/test_modules.py
- tools/tests/test_watchdog.py
Need to grab the "path" estimate from the loaded extension, then cross-check against all of the extension auto-load search paths for the signature/executable.
> Organize kernel_extensions to add signatures

- osquery/tables/CMakeLists.txt
- osquery/tables/specs/darwin/keychain_items.table
- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/certificates_tests.cpp
- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/darwin/keychain_items.cpp
- osquery/tables/system/darwin/keychain_utils.cpp
The final part of #786, simple data about all keychain items for system-keychains or a keychain of your choosing via `WHERE path = '/path/to/non-system/keychain.keychain'`.
> Add keychain_items to include basic item details

- tools/deployment/osqueryd.initd
Read an optional GFlags flag file from /etc/osquery/osquery.flags.
This allows the daemon to start with a non-default `--config_plugin` or `--logger_plugin`. This is the only way to control active plugins and extensions options. All of the extensions flags are read and acted on before a config plugin starts and a config is loaded.
> [Fix #861] Allow initscript to read gflags flagfile

- include/osquery/extensions.h
- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/extensions/extensions.cpp
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/test_modules.py
Instead of using a parameter filled with delimited paths, use a .load.
> Use a .load file instead of delimited dirs

- tools/provision.sh
rpmbuild was missing in the provision script and was making centos7 targets to fail
> Fix for centos7 targets

- osquery/sql/sqlite_util.cpp
This check fixes a crash in the "run" testing and profiling binary when tables returns blank columns.
> Fix error in run when tables emit blank columns

- osquery/tables/specs/linux/process_memory_map.table
- osquery/tables/system/linux/processes.cpp
Save for 'file', it's nicer to remove 'is_' for boolean fields. When selecting you would write "SELECT * FROM xyz WHERE condition is expression", not "true condition is true".
> Nit, prefer boolean columns to not use 'is_'

- include/osquery/core.h
- include/osquery/filesystem.h
- osquery/core/init.cpp
- osquery/devtools/shell.cpp
- osquery/extensions/extensions.cpp
- osquery/filesystem/filesystem.cpp
- osquery/tables/system/linux/block_devices.cpp
- tools/codegen/gentable.py
This removes a lot of the SQLite's shell. It enables a persistent DB connection such that extensions can attach new table plugins.
> Remove unused shell functions

- osquery/database/query.cpp
- osquery/database/results.cpp
- osquery/database/results_tests.cpp
I believe the cause of the problem was that an extraneous escape was happening
in the `addNewResults` function in query.cpp.
I believe this can be safely removed because it's purpose is only to make things
JSON safe. However, I don't think this function is ever called with out a JSON
serialization later, making this unnecessary.
> [Fix #877] Removing an extra escape

- osquery/config/config.cpp
ConfigPlugin items can use action='update' along with a single
source, data to add to the config structure. If multiple external
sources update at the same time, multiple 'update' actions are needed.
> Add 'update' action to ConfigPlugin call

- osquery/tables/system/darwin/keychain_items.cpp
There was a bug where when passing a path to a file that doesn't exist to keychain_items causes a crash because a check for null was not present.
> [Fix #919] Fixing segfault for non-existent path in keychain_items

- tools/deployment/make_osx_package.sh
- tools/deployment/osqueryctl
* Added a `--clean` option to make_osx_package.sh and `osqueryctl` that will nuke the database, removing the stored query results. This could be useful if you want to have the daemon reemit all the query results in the database.
* Changed how osqueryctl starts and stops the osx daemon. It now uses launchctl load and unload
* Validating the json config file before making the packages.
* Few other small clean-ups
> Added clean options, general osqueryctl cleanups

- osquery/tables/CMakeLists.txt
- osquery/tables/specs/x/disk_encryption.table
- osquery/tables/system/darwin/disk_encryption.cpp
(These are now tracked in #933)
* ~~Linux implementation~~
* ~~Add/update Tests~~
* ~~Documentation~~
Hey @theopolis,
This change adds `encrypted` column to the `block_devices` table.
Turns out `CoreStorage` is sub-class of  `IOMedia` (not a surprise), so this is a straightforward change, since there is already a `DASession`.
```bash
❯ echo "select name, uuid, encrypted from block_devices where encrypted == 1;"  \
| ./osqueryi
+------------+--------------------------------------+-----------+
| name       | uuid                                 | encrypted |
+------------+--------------------------------------+-----------+
| /dev/disk1 | ABCF88F5-629A-4DE9-9D30-91EFA68149E8 | 1         |
+------------+--------------------------------------+-----------+
```
```bash
❯ echo "select name, uuid, …
```
> [#911] Implement FDE status

- osquery/filesystem/filesystem.cpp
- osquery/filesystem/filesystem_tests.cpp
There was a bug in the logic that prevented absolute paths from being passed through the wildcard resolution function unscathed. It should be fixed now.
> [Fix #948] Absolute paths in wildcard resolution

- osquery/config/config.cpp
- osquery/config/plugins/filesystem.cpp
- tools/tests/test_osqueryi.py
There are a couple places where this was an issue.
The first place was in the filesystem plugin where it was only checked that it
existed, and not that it was an actual file.
The second was a lack of try and catch on the parse call in config.cpp.
Both of those issues are addressed in this diff.
> [Fix #945] Fix crashes from bad JSON

- osquery/core/test_util.cpp
- osquery/tables/networking/etc_hosts.cpp
- tools/tests/test_hosts.txt
This fixes #955.
Inline comments are now ignored. Updated tests.
Now querying doesn't output inline comments:
```
+-------------------------------------------------------+
| hostnames                                             |
+-------------------------------------------------------+
| localhost                                             |
| localhost.localdomain                                 |
| broadcasthost                                         |
| localhost                                             |
| local                                                 |
| bad_domain.com                                        |
+-------------------------------------------------------+
```
Ran the Intruments wrapper script:
```
❯ echo "select count(*) from etc_hosts;" | …
```
> [Fix #955] Fix etc_hosts hostname parsing so that inline comments are now ignored

- osquery/sql/virtual_table.cpp
A subquery may optionally include a where clause (predicate) constraint expression when an operator+constraint is specified.
The best value optimization phase will increase the count for a missing expression and include an `argv` item to filter, however this value will return null when fetching the string value.
> [Fix #953] Check sqlite predicate expression passing

- osquery/tables/specs/x/os_version.table
- osquery/tables/system/darwin/ad_config.cpp
- osquery/tables/system/darwin/os_version.cpp
- osquery/tables/system/linux/os_version.cpp
Instead of returning the kernel version for OS X, we should return the 10.VERSION string.
> [Fix #962] Add OS name and friendly version

- tools/provision/lib.sh
The only thrift bindings we need for osquery are cpp/python.
Python is used for the integration tests.
> Remove php from thrift provision

- include/osquery/filesystem.h
- osquery/filesystem/CMakeLists.txt
- osquery/filesystem/darwin/plist.mm
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/globbing.cpp
- osquery/tables/applications/browser_firefox.cpp
- osquery/tables/system/darwin/launchd.cpp
- osquery/tables/system/darwin/tests/launchd_tests.cpp
1. Move filesystem globbing code into globbing.cpp
2. Add some JSON-parsing utils to filesystem, similar to Plist parsing.
3. Improve launchd plist discovery and fix missing launch agents regression.
> [Fix #968] Refactor launchd

- CMake/FindCppNetlib.cmake
- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/remote/CMakeLists.txt
- osquery/remote/requests.h
- osquery/remote/requests_tests.cpp
- osquery/remote/serializers/json.cpp
- osquery/remote/serializers/json.h
- osquery/remote/serializers/json_tests.cpp
- osquery/remote/transports/http.cpp
- osquery/remote/transports/http.h
- osquery/remote/transports/http_tests.cpp
As discussed in the comments of #961. Included is an HTTP transport
(which works for HTTPS also) and a JSON serializer.
I've already updated `third-party`, this PR will update the pinned hash.
> Request template classes

- CMake/FindGlog.cmake
- CMakeLists.txt
- tools/analysis/clang-analyze.sh
- tools/provision/rhel.sh
The clang in yum is built with gcc 4.4 and the standard loader. We need to compile our dependencies with the devtoolkit3 version of gcc (4.9) as well as our source. The only way to use clang is to build LLVM/clang ourselves since it is not included alongside the updated gcc in devtoolkit.
Reference: #926
Update (4/13): Instead of building another LLVM/clang using the updated gcc toolchain we can use the existing compiler and set the new gcc toolchain for the osquery build. The downside is the static analyzer may not work as intended.
> Cross compile with LLVM 3.4 using gcc 4.9 on RHEL6.5

- osquery/tables/system/linux/os_version.cpp
@marpaia I think this should do it. The "LTS" string wasn't set in the version I tested with. :(
> Fix Ubuntu os_version regex

- osquery/tables/specs/utility/osquery_schedule.table
- osquery/tables/specs/utility/osquery_scheduled.table
- osquery/tables/utility/osquery.cpp
Code for the table and specs to add the new table osquery_scheduled that will track all the current scheduled queries
> Adding osquery_scheduled table

- README.md
I figured this was using the shortened URL because it was shorter / looked better, so I threw it up on my fork (https://github.com/marpaia/osquery/tree/readme) and I think it looks pretty good. Plus, it looks awesome when our README has all TLS links.
> Changing read the docs URL to be https

- mkdocs.yml
mkdocs v0.12.2 fails to build and serve without this page attribute.  Adding a "Welcome to osquery" title to fix the build and for the navigation object to render correctly.
Before:
```
$ mkdocs serve
Traceback (most recent call last):
File "/usr/local/bin/mkdocs", line 9, in <module>
load_entry_point('mkdocs==0.12.2', 'console_scripts', 'mkdocs')()
File "/usr/local/lib/python2.7/site-packages/mkdocs/main.py", line 77, in run_main
main(cmd, args=sys.argv[2:], options=dict(opts))
File "/usr/local/lib/python2.7/site-packages/mkdocs/main.py", line 49, in main
serve(config, options=options)
File "/usr/local/lib/python2.7/site-packages/mkdocs/serve.py", line 22, in serve
builder()
File "/usr/local/lib/python2.7/site-packages/mkdocs/serve.py", line 19, in builder
build(config, live_server=True) …
```
> Add a missing Page attribute to fix broken mkdocs build

- tools/provision/centos.sh
- tools/provision/lib.sh
See #1025, this should build on a clean (unprovisioned) centos7 vagrant.
> Build cmake with gcc to avoid gnu++1y

- Vagrantfile
- docs/wiki/development/building.md
As much of a fan I am of sword-fighting, I would still like my code to be compiled faster.
> Use all available CPUs when provisioning a Vagrant box

- osquery/devtools/shell.cpp
The `--csv` flag was broken in https://github.com/facebook/osquery/commit/79ddc5b, this pull request restores its previous functionality.
> Fix --csv flag in osqueryi shell

- osquery/config/config.cpp
- osquery/config/config_tests.cpp
- osquery/core/flags.cpp
- osquery/core/init.cpp
- osquery/core/watcher.h
- tools/tests/test.config
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/test_modules.py
- tools/tests/test_watchdog.py
- tools/tests/utils.py
Flags loaded from options was removed during a refactor of config merging. This fixes the ignored options regression.
> Fix dameon flags loading from options

- .gitignore
- osquery/tables/CMakeLists.txt
- osquery/tables/specs/disk_encryption.table
- osquery/tables/system/linux/block_devices.cpp
- osquery/tables/system/linux/disk_encryption.cpp
- tools/provision/centos.sh
- tools/provision/rhel.sh
- tools/provision/ubuntu.sh
This implements #933
This change implements `disk_encryption` table for Linux. 
Note that this query has to be run as root since this reads headers on block devices.
```
+------------+----------------------------------------+-----------+-----------------------+
| name       | uuid                                   | encrypted | type                  |
+------------+----------------------------------------+-----------+-----------------------+
| /dev/sr0   |                                        | 0         |                       |
| /dev/sda   |                                        | 0         |                       |
| /dev/sda1  | 15d95ae5-5dee-4283-a49d-463188b4f7f9   | 0         |                       |
| /dev/sda2  |                                        | 0         | …
```
> [Implement #933] Add LUKS/dm-crypt disk_encryption support for Linux

- docs/wiki/index.md
Just removing an extra `-` in the link.
> Fix a broken link to the OS X install docs.

- osquery/tables/specs/utility/file.table
- osquery/tables/utility/file.cpp
Now you can run a query like:
```
osquery> select path from file where pattern = "/home/%/git/osquery/%";
+--------------------------------------------+
| path                                       |
+--------------------------------------------+
| /home/marpaia/git/osquery/.clang-format    |
| /home/marpaia/git/osquery/osquery.thrift   |
| /home/marpaia/git/osquery/PATENTS          |
| /home/marpaia/git/osquery/README.md        |
| /home/marpaia/git/osquery/Vagrantfile      |
| /home/marpaia/git/osquery/CONTRIBUTING.md  |
| /home/marpaia/git/osquery/mkdocs.yml       |
| /home/marpaia/git/osquery/Doxyfile         |
| /home/marpaia/git/osquery/.gitmodules      |
| /home/marpaia/git/osquery/requirements.txt |
| /home/marpaia/git/osquery/Makefile         |
| /home/marpaia/git/osquery/LICENSE …
```
> [Fix #1013] wildcard support in file table

- osquery/tables/applications/browser_chrome.cpp
- osquery/tables/applications/browser_utils.cpp
Chrome (non-Opera) may use multiple profiles before the
extensions dir. Use a glob before searching for extensions/versions.
> [Fix #1017] Use a fs glob in chrome-extensions searching

- include/osquery/config.h
- osquery/tables/events/yara_events.cpp
- osquery/tables/utils/yara_utils.cpp
- osquery/tables/utils/yara_utils.h
This was causing a crash when executing a query using the yara table
from the command line, because YARA was never initialized properly, so
the thread index was whatever was left on the stack. Eventually YARA
would attempt to set a rule that matches using this thread index and
would explode in flames.
Fix it by moving the initialization to a place that is always called.
> Move YARA initialization to setUp().

- osquery/config/tests/config_tests.cpp
- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/extensions/tests/extensions_tests.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/logger/tests/logger_tests.cpp
- osquery/main/tests.cpp
- tools/tests/test_base.py
Jenkins recently broke all unittests because of false assumptions about filesystem state. We did some patching and left files on disk, subsequently the unittests assumed a blank state.
> Towards safer and shuffled unittests

- osquery/tables/utils/yara.cpp
- osquery/tables/utils/yara_utils.cpp
Previously this only existed in the yara table, but it now exists in the
yara config parser land, which will compile signature groups upon
update. Now your signature groups can reference signature files using
paths relative to /var/osquery.
> Make YARA rule compiling handle relative paths.

- README.md
The current links result in errors because they don't include
"/en/latest" in the URL paths.  This also upgrades the links to https.
> Fix build/osqueryi/osqueryd doc links in readme

- docs/wiki/installation/cli-flags.md
- osquery/core/init.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/virtual_table.cpp
- tools/deployment/osquery.example.conf
This implements #1016.
Here's how it looks:
```bash
❯ ./build/darwin/osquery/osqueryi --verbose --disable_tables=time,foo_bar
I0430 01:07:36.459516 2054472448 init.cpp:148] osquery initialized [version=1.4.4-181-g4fa7083]
I0430 01:07:36.459674 2054472448 extensions.cpp:163] Modules autoload contains invalid paths: /etc/osquery/modules.load
I0430 01:07:36.459961 212852736 interface.cpp:249] Extension manager service starting: /Users/sbs/.osquery/shell.em
I0430 01:07:36.466197 217632768 events.cpp:422] Starting event publisher runloop: fsevents
I0430 01:07:36.466231 218169344 events.cpp:422] Starting event publisher runloop: iokit_hid
I0430 01:07:36.466241 218705920 events.cpp:422] Starting event publisher runloop: scnetwork
I0430 01:07:36.476591 2054472448 virtual_table.cpp:243] Table time …
```
> [Implements #1016] Disable tables runtime flag

- docs/wiki/deployment/anomaly-detection.md
- docs/wiki/deployment/configuration.md
- docs/wiki/deployment/file-integrity-monitoring.md
- docs/wiki/deployment/log-aggregation.md
- docs/wiki/deployment/logging.md
- docs/wiki/deployment/yara.md
- docs/wiki/development/building.md
- docs/wiki/development/config-plugins.md
- docs/wiki/development/creating-tables.md
- docs/wiki/development/logger-plugins.md
- docs/wiki/development/pubsub-framework.md
- docs/wiki/development/unit-tests.md
- docs/wiki/index.md
- docs/wiki/installation/cli-flags.md
- docs/wiki/installation/custom-packages.md
- docs/wiki/installation/install-linux.md
- docs/wiki/installation/install-osx.md
- docs/wiki/introduction/using-osqueryd.md
- docs/wiki/introduction/using-osqueryi.md
Noticed that the linked screenshot images were loaded over http resulting in mixed content warning. This updates links to https.
Also noticed that most of the internal hyperlinks were broken. According to [Mkdocs RTD](https://mkdocs.readthedocs.org/en/latest/user-guide/writing-your-docs/#linking-documents) these require the `.md` extension.
I think I got most of those, but my grep/regex could have certainly missed some.
> [Docs] Fix 404s and https mixed content warning

- osquery/tables/networking/linux/process_open_sockets.cpp
- tools/provision/centos.sh
See the reference-tagged issue #1094 about removing netlink for the time being.
This adds the common, proc-accessible protocol lists to processes_open_sockets aside from just TCP/UDP.
> [Fix #1080] Remove netlink, support raw sockets

- CMake/Packages.cmake
- CMakeLists.txt
- Makefile
- osquery/config/CMakeLists.txt
- osquery/core/init.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/remote/CMakeLists.txt
- tools/codegen/genapi.py
While cutting 1.4.5 I noticed enrollment and http-based config retrieval plugins were included. Instead of a note to not use these features I'd rather support a release-package boolean to remove in-progress features.
> Add a CMake variable for packages

- osquery/database/db_handle.cpp
Previously the RocksDB instance was allowed to write 1000 log files. This can take on the order of 4-5GB of debug info. We must restrict this to at max 10M and only WARNING+ERROR logs.
> Limit the number of RocksDB log files

- osquery/CMakeLists.txt
`make install` should:
```
cd build/darwin && cmake ../../ && \
CTEST_OUTPUT_ON_FAILURE=1 make --no-print-directory install
-- Requested dependencies may have changed, run: make deps
-- Building for OS X
-- Found components for DL
-- Found readline library
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   regex
--   date_time
--   thread
--   filesystem
--   program_options
--   chrono
--   atomic
-- Found RocksDB
-- Thrift version 0.9.2
-- Found library dependency /usr/local/lib/libboost_thread-mt.a
-- Found library dependency /usr/local/lib/liblz4.a
-- Found library dependency /usr/local/lib/libboost_system.a
-- Found library dependency /usr/local/lib/libboost_filesystem.a
-- Found library dependency …
```
> Remove cpp-netlib from make install

- CMake/CMakeLibs.cmake
- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/tables/networking/interfaces.cpp
- tools/codegen/gentable.py
1. Require a python2 interpreter for thrift:py generation.
2. Move ifaddrs after net/if include: https://www.freebsd.org/cgi/man.cgi?query=getifaddrs
> Use CMake find_package for python, fix ifaddrs on FreeBSD

- CMakeLists.txt
- osquery/tables/CMakeLists.txt
- osquery/tables/networking/linux/iptables.cpp
- osquery/tables/networking/linux/tests/iptables_tests.cpp
- osquery/tables/specs/linux/iptables.table
- sysroots/linux/linux/netfilter_ipv4/ip_tables.h
- tools/provision/centos.sh
- tools/provision/lib.sh
- tools/provision/rhel.sh
- tools/provision/ubuntu.sh
This code gives osquery visibility over iptables filter, chains and rules. Also the headers that are patched to make osquery to compile with a C++ compiler but the returns has a void pointer. More info: https://bugzilla.netfilter.org/show_bug.cgi?id=536
> Adding new table to display iptables filters, chains and rules

- osquery/devtools/shell.cpp
- tools/tests/test_base.py
- tools/tests/test_osqueryi.py
1. Fix an array-out-of bounds error in .show (regression from removing mode names).
2. Use the registry for table names and schema
3. Add meta command integration tests for the shell to prevent #1121-style regressions.
> [Fix #1121] Minify shell table/schema, add meta tests

- CMake/Packages.cmake
- osquery/tables/networking/linux/iptables.cpp
- osquery/tables/networking/utils.cpp
- osquery/tables/networking/utils.h
- tools/lib.sh
- tools/provision.sh
- tools/provision/centos.sh
- tools/provision/lib.sh
- tools/provision/rhel.sh
- tools/provision/ubuntu.sh
1. Remove epel-release and systemd-devel from EL-based distro package requirements.
2. Build the libip4tc iptables-table requirement inline and install the static lib.
3. Add some helpful provision lib macros
4. Remove the remove-package of unwind, since we've removed the checking from glog.
5. Speed up deps/provisioning installs.
> Relaxing iptables, EL-deps

- tools/deployment/com.facebook.osqueryd.conf
- tools/deployment/make_osx_package.sh
The old issue: #302 was left a bit dangling in suggestions for log rotation. We should do a little better and include an example newsyslog config in our deployment directory.
We also mention how this is installed with Chef here: http://osquery.readthedocs.org/en/latest/deployment/configuration/
> Add example newsyslog conf for OS X

- tools/provision/lib.sh
Looks like a simple typo: `automake` for `libtool`
Before this commit, this is the error you'd get when you ran `make deps`:
```
[+] libtool is not installed/provisioned. installing...
[+] libtool has not been downloaded. downloading...
--2015-05-11 06:01:38--  https://osquery-packages.s3.amazonaws.com/deps/automake-2.4.5.tar.gz
Resolving osquery-packages.s3.amazonaws.com... failed: Temporary failure in name resolution.
wget: unable to resolve host address “osquery-packages.s3.amazonaws.com”
[+] libtool has not been extracted. extracting...
tar (child): libtool-2.4.5.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/vagrant/tools/provision/lib.sh: line 196: pushd: …
```
> Fix URL for libtool

- tools/provision/lib.sh
Prior to this commit, you'd get this error when running `make deps` with a version of autoconf that belongs in a museum (e.g. the one that's in CentOS 6 Base):
```
[+] autoconf is already installed. skipping provision.
/home/brandt/osquery/tools/provision/lib.sh: line 163: force_provision: command not found
make: *** [deps] Error 127
```
I couldn't find a `force_provision` in the codebase. Plain old `provision` should do the job.
> Fix missing command: force_provision

- include/osquery/config.h
- include/osquery/extensions.h
- osquery/config/config.cpp
- osquery/core/flags.cpp
- osquery/core/init.cpp
- osquery/main/shell.cpp
- tools/tests/test.badconfig
- tools/tests/test_base.py
- tools/tests/test_osqueryi.py
1. Make the flag help padding checks more robust. Also use only the flag values from osquery, not gflags.
2. Fix `--config_check` always returning (0, OK).
3. Add `--config_check` tests to osqueryi's integration testing.
> [Fix #1125 #1126] Flag padding checks, config_check tests

- osquery/CMakeLists.txt
Missing an argument to OSQUERY_ADD_LINK here, which was causing the build to fail on FreeBSD.
> Fix build on FreeBSD.

- CMake/Packages.cmake
`libcryptsetup` is a required runtime dependency.
Corresponding sections of provision files:
- [CentOS provision file](https://github.com/facebook/osquery/blob/8235fd155f25334e8edf21218491cc511853c17e/tools/provision/centos.sh#L73-L78)
- [RHEL provision file](https://github.com/facebook/osquery/blob/8235fd155f25334e8edf21218491cc511853c17e/tools/provision/rhel.sh#L94-L99)
CentOS 6
--------
[Demonstration of problem and work around.](https://gist.github.com/brandt/e32af345b63c339ddbdb#file-centos-6-log-L81)
Error message:
```
[root@b1a7318dbf3c /]# osqueryi
osqueryi: error while loading shared libraries: libcryptsetup.so.1: cannot open shared object file: No such file or directory
```
CentOS 7
--------
[Demonstration of problem and work …
> Specify dependency on libcryptsetup in CentOS/RHEL

- osquery/tables/specs/blacklist
- osquery/tables/system/freebsd/mounts.cpp
Cleanup blacklist entries for FreeBSD (mounts/users/groups)
> Add mounts table support under FreeBSD

- osquery/tables/CMakeLists.txt
- osquery/tables/system/darwin/extended_attributes.cpp
Currently where_from parsing in extended_attributes is too browser centric and misses other information for files sent through airdrop/bluetooth/etc.
```
❯ echo "select key,value,base64 from extended_attributes where path = \"/Users/sbs/Downloads/foobar.jpg\";" | osqueryi
+--------------------------------------------------------+------------------------------------------------------------------------------+--------+
| key                                                    | value                                                                        | base64 |
+--------------------------------------------------------+------------------------------------------------------------------------------+--------+
| where_from_download_url                                | …
```
> More thorough where_from parsing in extended_attributes

- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/core/watcher.cpp
- osquery/main/tests.cpp
Some simple logic to "test" variations of the `kTestWorkingDirectory` variable. Normally unit test executables run with a cwd=./build/PLATFORM/osquery/. They discover file-based assets from ../../../tools/tests. We add some "search" steps to discover this asset folder if cwd=./
> Allow unit tests execs from project root

- osquery/tables/specs/user_groups.table
- osquery/tables/system/darwin/user_groups.mm
- osquery/tables/system/linux/user_groups.cpp
- osquery/tables/system/user_groups.h
The user_groups table represents the association between user ids and group ids.
Darwin Issue:
Issues arise in darwin systems with users that are members of many groups due
to a bug in Apple's implementation of [getgrouplist](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/getgrouplist.3.html).  If the number of groups a
user is a member of is greater than 64 a truncated association table may
be returned.
> Wrote a user_groups table for darwin and linux based system.

- osquery/core/conversions.h
- osquery/core/darwin/conversions.cpp
- osquery/tables/system/darwin/certificates.mm
Adds an offset to the CFAbsoluteTime in `not_valid_before` and `not_valid_before` to convert both to UNIX time.
I also suggest changing the [documentation on the certificates table](https://osquery.io/docs/tables/#certificates) to reflect this change.
> Converted CFAbsoluteTime in X509 certificates to UNIX time

- include/osquery/tables.h
- osquery/core/tests/tables_tests.cpp
- osquery/tables/networking/linux/process_open_sockets.cpp
- osquery/tables/system/centos/rpm_packages.cpp
- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/keychain_items.cpp
- osquery/tables/system/darwin/packages.cpp
- osquery/tables/system/darwin/preferences.cpp
- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/darwin/user_groups.mm
- osquery/tables/system/linux/process_open_files.cpp
- osquery/tables/system/linux/processes.cpp
- osquery/tables/system/linux/user_groups.cpp
- osquery/tables/system/system_controls.cpp
Fixes issue #1160
This change allows QueryContext constraints to be checked for based on
operator type.  This makes checks for the existence of an equality
operator allow enumeration.
Example:
```
if (context.constraints["pid"].exists(EQUALS)) {
pids = context.constraints["pid"].getAll(EQUALS);
} else {
osquery::procProcesses(pids);
}
```
> Constraint existence now check for constraints using specific operator types.

- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/database/db_handle.cpp
- osquery/extensions/extensions.cpp
- tools/tests/test_http_server.py
- tools/tests/test_osqueryi.py
`make tests` fails with another osquery process running.
The backing-store check happens after a config plugin is setUp and the initial load occures. This may involve calls to cached keys, the check should occur pre-config initialize.
Let's see if this fixes the errors in recent PRs, such as #1177.
> Fix DBHandle checking with concurrent processes.

- osquery/config/parsers/query_packs.cpp
With the old code, strings with only the platform string, would not satisfy this check
> Fix that checks the right platform to schedule packs

- osquery/tables/system/user_groups.h
OS X build errors on current master 7d4142b28cb8dd7e3bc8f29553b422a65e61b1a9: 
```bash
In file included from ./osquery/osquery/tables/system/darwin/user_groups.mm:13:
./osquery/osquery/tables/system/user_groups.h:72:7: warning: Memory allocated by 'new[]' should be deallocated by 'delete[]', not 'delete'
delete groups;
^~~~~~~~~~~~~
./osquery/osquery/tables/system/user_groups.h:78:5: warning: Memory allocated by 'new[]' should be deallocated by 'delete[]', not 'delete'
delete groups;
^~~~~~~~~~~~~
2 warnings generated.
make[3]: *** [osquery/tables/CMakeFiles/TARGET.dir/system/darwin/user_groups.mm.o] Error 1
make[2]: *** [osquery/tables/CMakeFiles/TARGET.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```
(Not sure why Jenkins didn't catch it)
This fixes it.
> Fix OS X build: Deallocate array with delete[] instead of delete

- CMake/Packages.cmake
We were missing a dependency on RHEL6.5 because the devmapper package was only added to CentOS6.5. This treats the EL mostly equivalent from a dependency perspective.
> [Fix #1176] Merge Redhat-based package dependencies

- osquery/tables/system/linux/model_specific_register.cpp
- specs/linux/model_specific_register.table
This table contains information is primarily related to the performance of processor
cores.  The information given constitutes only a small portion of
the information in the model specific register, but this table
has been designed so that more information may easily be added.
The table requires osquery be run as the root, and that the msr
kernel module is loaded.  The table reads the msr data from /dev
> Created a table for information in the model specific register.

- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/core/system.cpp
- osquery/main/tests.cpp
- osquery/tables/system/linux/disk_encryption.cpp
- tools/profile.py
- tools/tests/utils.py
1. The release tooling had regressions from recent refactors such as new paths for specs and platform detections.
2. License/copyright missing from disk_encryption.
3. Initializer's random number generator was seeded using second-precision and the splay calculation was not seeded.
> Update tooling/profiling paths and use a better random seed

- osquery/tables/system/darwin/extended_attributes.cpp
- osquery/tables/system/darwin/tests/extended_attributes_tests.cpp
- tools/tests/test_xattrs.txt
Now uses LaunchServices API to grab quarantine data.
* No more manual parsing (often prone to breaking on updates)
* More insight into quarantine events: timestamp, type (webdownload, mail.app attachment, ical attachment, airdrop), etc 
* Added tests
```
osquery> select key,value,base64 from extended_attributes where path = "/Users/sbs/Downloads/foo_bar/googlechrome.dmg";
+----------------------------------+------------------------------------------------------------------+--------+
| key                              | value                                                            | base64 |
+----------------------------------+------------------------------------------------------------------+--------+
| com.apple.diskimages.fsck        | OP++fu++J8B7AGyIsqFQTRZwbHo= …
```
> Extended Attributes: Use LaunchServices API for quarantine data 

- osquery/tables/system/linux/model_specific_register.cpp
- specs/linux/msr.table
`int osquery::filter(const struct dirent*)` seemed like a pretty generic
symbol to have in our symbol table, so I changed it to
`int osquery::msrScandirFilter(const struct dirent*)`
> Formatting the callback function in the model_specific_register table

- tools/provision/darwin.sh
We were building RocksDB from source hosted on S3, we should have been using Homebrew but there was a problem building portable code (non-CPU optimized).
> [Fix #1185, #1183] Use RocksDB from Homebrew on OS X

- osquery/config/config.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/dispatcher/scheduler.cpp
- tools/codegen/genapi.py
- tools/provision/lib.sh
1. Add `"removed":false` to a scheduled queries to only emit `"action":"added"` results.
2. Workers now abort with an exponential backoff.
> [#1190] Schedule queries without logging removed results

- osquery/core/watcher.cpp
The watchdog process was useless without monitoring states between polling intervals.
> Fix the watchdog/scheduler limit tracking

- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/tests/fsevents_tests.cpp
The FSEvent action mask was overwriting multiplexed actions. We should fire an event for each action applied to a path during a transaction. For example: if a file was created, an FSEvents transaction may buffer the open and write events into a single transaction. Our publisher's callback would overwrite each action with the last in the mask-walk.
> Fix FSEvents multiplexing actions

- osquery/tables/networking/linux/process_open_sockets.cpp
- osquery/tables/system/darwin/process_open_descriptors.cpp
- specs/process_open_sockets.table
Again, this is only network/raw sockets. The format for UNIX sockets is a bit different and might be able to be merged into the `process_open_sockets` table with an optional `path` column.
> Process open sockets on Linux needs '['

- osquery/core/init.cpp
If the original string size of argv[0] was less than the size of the overwriting (helpful) worker name replacement, the argv[*] memory would remain = NULL.
> [Fix #1202] Replace argv[*] with spaces, fallback to path in [0]

- docs/doxygen/DOXYGEN-LICENSE.txt
- docs/wiki/deployment/configuration.md
- docs/wiki/development/osquery-sdk.md
1. Doxygen license was missing a few bytes.
2. RTD wiki pages have some grammar issues.
> Various quality control fixes

- osquery/logger/CMakeLists.txt
- osquery/logger/plugins/syslog.cpp
How to use: `--logger_plugin=syslog`.
You *should* set up a facility sink for `LOG_LOCAL3` and expect the following:
1. Results go to `LOG_INFO`, this is typically dropped from the normal system log because it is verbose.
2. If using debug/verbose mode (`--verbose`) you will get `LOG_NOTICE` status lines.
3. Warning and osquery error logs go to `LOG_WARNING` and `LOG_ERR` respectively.
The result JSON in syslog format, note the `result=` followed by JSON:
```
Jun 12 18:12:24 reed-mbp.local osqueryd[86786]: result={"name":"info","hostIdentifier":"reed-mbp.local","calendarTime":"Sat Jun 13 01:12:24 2015 UTC","unixTime":"1434157944","columns":{"build_distro":"10.10","build_platform":"darwin","config_md5":"d3690eac60986d212fe52a687aed3431","config_path":"\/Users\/reed\/osquery-custom.conf","ex …
```
> [#1207] Add syslog plugin

- include/osquery/tables.h
- osquery/core/init.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/apps.cpp
- osquery/tables/system/darwin/extended_attributes.cpp
- osquery/tables/system/darwin/keychain_acl.cpp
- specs/darwin/app_schemes.table
- specs/darwin/package_receipts.table
- tools/codegen/gentable.py
This virtual table adds information about common OS X application schemes. A scheme, or protocol (e.g., `https://`, `tel://`, `ssh://`), may be used for IPC between applications by constructing URI definitions. Because of this, applications may define somewhat-arbitrary scheme names. We say "common" because automatic enumeration of schemes is handled by private OS X APIs in Core and Launch Services. However, we know the scheme name a-priori we can query for information.
There are several well-known schemes that are handled by the OS. This means the application handler is determined by a preference or ACL/enable controlled by the user/OS. Launch Services/Inter-App Communication [documentation](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/I …
> OS X application duti/scheme listing table

- tools/tests/test_base.py
This change updates tests to use psutil's `Process.children()` instead of `Process.get_children()` as the latter has been deprecated.
`Process.get_children()` had been deprecated in psutil 2.x and is compeletely removed in 3.x versions
in favor of `Process.children()`.
[Here is the list](https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#200---2014-03-10) of replacement API for all `Process.get` functions.
This fixes #1220. I am not so sure that this is related to #1198, but I have yet to encounter it.
> [Fix #1220] osqueryd watchdog tests

- osquery/tables/system/darwin/extended_attributes.cpp
Just noticed osquery 1.4.7 land in brew, and that it removes Mavericks supports.
This change removes 10.9 code path since we no longer support it. 
This is the only instance of it that I found, which I had added in `extended_attributes` to support Mavericks.
Context: File Manager, `FSRef` (carbon era) APIs have been deprecated in favor of CoreFoundation ones.
> Remove OS X 10.9 code path

- include/osquery/extensions.h
- osquery/core/init.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.h
- osquery/extensions/tests/extensions_tests.cpp
- tools/tests/test_base.py
Mostly try to be clear about time and units in death and socket timeout checks. Allow unit tests to be more aggressive in delay/latency.
> [Fix #1198] Faster death/timeout checks in extensions tests

- kernel/include/feeds.h
- kernel/src/circular_queue_kern.c
- kernel/src/circular_queue_kern.h
- kernel/src/osquery.cpp
- osquery/events/kernel/circular_queue_user.cpp
This makes the daemon disconnect process safe.  The kernel extension will now wait for pending events before freeing the buffer up.  One race is still possible: daemon disconnects followed by an extension unload before all pending events have gone through.  The risk of this is reduced by a 1 second delay that is enforced from the time the buffer is freed up to the time the extension may be unloaded.  During this period the kernel extension will refuse to be unloaded.
> Kernel extension fixes for daemon shutdown process.

- osquery/database/db_handle.cpp
- osquery/database/query.cpp
- osquery/database/tests/query_tests.cpp
- tools/provision/lib.sh
We found that not installing the headers for snappy caused RocksDB's
snappy detection to not find that snappy was installed:
https://goo.gl/YOWJl0
The snippet there requires that the headers are installed, not just the
library. By installing the headers, we can ensure that snappy is linked.
OR, alternatively, we could just leave it and not link snappy. It's
uncertain what the specific benefits of including snappy are for our
use-case. (CC @igorcanadi)
> Install snappy headers instead of just the library

- include/osquery/core.h
- include/osquery/logger.h
- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/dispatcher/dispatcher.h
- osquery/logger/logger.cpp
If watcher processes generate warning or error status logs they will "relay" to the worker processes upon successful sanity check.
> [#1277] Forward status logs to osqueryd workers

- CMake/Packages.cmake
Missing the epoch number prevents the package from updating the device-mapper dependency if the existing package has the same epoch number
https://bugzilla.redhat.com/show_bug.cgi?id=1207839
> add epoch number to device-mapper version

- tools/tests/test_extensions.py
- tools/tests/test_osqueryi.py
Bring extension and shell IPC timeouts up to 10 seconds.
> Relax extensions and shell timeouts

- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/tests/fsevents_tests.cpp
When osqueryd loads it can use symlinks to subscribe for `file_events` assuming those symlinks are constant. Here "configure time" means the initialization of the daemon after it reads a config and knows about the set of paths it should watch. This helps for the `/etc` -> `/private/etc` case.
> [Fix #1063] Allow configure-time symlink resolution in FSEvents

- docs/wiki/installation/cli-flags.md
- include/osquery/flags.h
- osquery/core/flags.cpp
- osquery/core/test_util.cpp
- osquery/extensions/tests/extensions_tests.cpp
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/registry/registry.cpp
There are 3 new options that control how files are read:
- `--read_max` that controls the maximum size, in bytes, for file reads. If a file is larger than `read_max` the read will fail.
- `--read_user_max`, similar to `read_max` but applies additional limitations to user-controlled files.
- `--read_user_links`, a boolean control to enable/disable following symlinks for user-controlled files.
Important highlights:
- If files exceed the configured max, those reads will fail.
- The `read_max` will override `read_user_max` if it is set lower.
- A default integer value of `0` will disable the limitations. 
The default `read_max` is set to 50M and the default `read_user_max` is 10M.
> [Fix #1171, #1089] Add configurable max reads

- osquery/remote/transports/tls.cpp
Before, osqueryd would send `osquery/OSQUERY_BUILD_VERSION` as the user agent and appeared broken.  I copied the logic from the osquery version table and used that var here also so the user agent now reads `osquery/1.4.7`
> Fix version string for TLS plugins

- tools/provision/lib.sh
- tools/provision/ubuntu.sh
This a PR for supporting Ubuntu 10 builds. It was tested on a fresh VM.
Note: On Ubuntu 10, linking the executables produces the following errors/warnings:
```
/usr/bin/ld: Dwarf Error: found dwarf version '4', this reader only handles version 2 and 3 information.
/usr/local/lib/libapt-pkg.a(fileutl.o): In function `FileFd::Open(std::string, unsigned int, APT::Configuration::Compressor const&, unsigned long)':
fileutl.cc:(.text+0x2b3c): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
```
The warning about `mktemp` is obviously due to using an old `libapt-pkg` version. The dwarf messages I believe stem from building `libapt-pkg` with a newer `gcc`, but linking uses an older version of `ld`. This does not appear to affect the binaries, however the version of GDB …
> Minor fixes to support building on Ubuntu 10.04

- osquery/tables/utility/time.cpp
- specs/utility/time.table
Add information about the date as well as unix_time and an ISO 8601-formatted string to the table.
See #1297.
> Add date information to time table

- osquery/main/run.cpp
The `run` binary target is a simple tool for executing a query and monitoring performance/overhead. It should also be used to find exceptions in tables by preventing them from the normal "catch and log" safety net.
> Enable registry exceptions for benchmarking/testing

- CMake/CMakeLibs.cmake
- CMakeLists.txt
- kernel/CMakeLists.txt
- kernel/include/feeds.h
- kernel/src/circular_queue_kern.c
- kernel/src/circular_queue_kern.h
- kernel/src/osquery.cpp
- osquery/CMakeLists.txt
- osquery/core/test_util.h
- osquery/events/CMakeLists.txt
- osquery/events/kernel.cpp
- osquery/events/kernel.h
- osquery/events/kernel/circular_queue_user.cpp
- osquery/events/kernel/circular_queue_user.h
- osquery/events/kernel/tests/kernel_communication_tests.cpp
- osquery/main/tests.cpp
- osquery/tables/events/process_events.cpp
- specs/darwin/process_events.table
Creates `process_events` table which contains exec event information.
#1287 Tracks information we are interested in exposing.
> Adding process events table.

- docs/wiki/index.md
Let's start using our google group for long-form questions so that we can leave issues for implementation tasks.
> Add google group email to the wiki

- osquery/sql/virtual_table.cpp
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/networking/darwin/routes.cpp
- osquery/tables/networking/interfaces.cpp
- osquery/tables/networking/linux/routes.cpp
- osquery/tables/networking/utils.cpp
- osquery/tables/utility/hash.cpp
1. There are observed cases where `getifaddrs` will return a success response but leave its output parameter set to `nullptr`. Our raw pointers were not initialized and were evading static analysis.
2. Attempt to reduce memory requirements for SQLite virtual table modules.
3. Avoid trying to hash files if file eventing does not indicate content changes.
> Fix getifaddrs result / data checking

- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/darwin/keychain_utils.cpp
- osquery/tables/system/darwin/tests/certificates_tests.cpp
X509 parsing is now handled by OpenSSL as there does seem to be a
memory leak in SecCertificateCopyValues of Security framework which resulted
performance hit when querying certificates. This fixes #1032.
Quick and dirty benchmark:
```bash
❯ time ./build/darwin/osquery/run --query "select * from certificates" --iterations 10
0.60s user
0.08s system 
87% cpu 
0.785 total
```
And here's the same run on master build:
```bash
❯ time ./build/darwin/osquery/run --query "select * from certificates" --iterations 10
7.30s user
0.10s system 
98% cpu 
7.534 total
```
`key_usage` and `key_algorithm` columns now display human readable strings
(e.g. Digital Signature, CRL Sign rsaEncryption) than the raw flags and OIDs (e.g 0x86, 1.2.840.1).
Here's how it looks:
```
key_algorithm = rsaEncryption …
```
> [Fix #1032] Better/faster performance when querying certificates on OS X

- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/darwin/keychain_utils.cpp
- osquery/tables/system/darwin/tests/certificates_tests.cpp
This adds a macro to `keychain.h` on OS X that silences OpenSSL deprecation warnings when using the Apple-system provided OpenSSL by detecting if `SSL_TXT_TLSV1_2` is defined. This TLS1.2 macro only exists on newer OpenSSL distributions.
> Silence OS X OpenSSL-related deprecations

- tools/provision/lib.sh
As of [homebrew #41151](https://github.com/Homebrew/homebrew/pull/41151) gflags is not installed with a static library. Our build hosts must have static versions of gflags.
> Build/install gflags' static library on build hosts.

- include/osquery/filesystem.h
- osquery/core/hash.cpp
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
1. "really" check for links in readFile
2. Apply the same restrictions and flag ACLs to file hashing.
> [Fix #1332] Check mode for links in readFile

- osquery/CMakeLists.txt
`osqueryctl` was previously missing from the `make install` target in CMake.
> [Fix #1341] Add osqueryctl to make install target

- include/osquery/filesystem.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
Fix to the `osquery::readFile` function (#1344).
> Updated the readFile function to correctly handle symbolic links

- osquery/config/config.cpp
- osquery/config/plugins/tls.cpp
- osquery/core/tables.cpp
- osquery/database/database.cpp
- osquery/distributed/distributed.cpp
- osquery/logger/plugins/tls.cpp
- osquery/registry/registry.cpp
- osquery/remote/serializers/json.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
When filling in column data, do not clear intermediate `QueryData` and `Row` data. Instead, tell SQLite that the text content will be statically accessible until the callback is complete. In this case the callback is the iteration as rows are returned.
This also includes wrapping some `write_json` calls with exception handling "pretty close" to the problematic/encoding sites. Parsing a property tree into JSON may fail if the content contains binary or otherwise null information.
> Fix broken JOIN predicate passing

- tools/codegen/genapi.py
JSON table file was missing the rest of versioning after X.Y.Z, now it is generated with whatever is tagged
> Fix tables JSON file name

- CONTRIBUTING.md
- docs/wiki/deployment/logging.md
- docs/wiki/deployment/yara.md
Fixed some typos and two links to the documentation in the [CONTRIBUTING.md](https://github.com/facebook/osquery/blob/master/CONTRIBUTING.md) file.
> Fixed URLs and some typos in the documentation

- CMakeLists.txt
- osquery/filesystem/filesystem.cpp
- osquery/tables/system/linux/os_version.cpp
1. Redhat-based distributions were not reporting their version correct.
2. The file read API assumed stat would return an accurate file size. This has been replaced with an attempt to seek to the end of the file.
> [Fix #1319] CentOS version reporting and file read error

- osquery/CMakeLists.txt
- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
- tools/deployment/osquery.example.conf
For Homebrew (HB) and `make install` targets, all configuration files are installed into the CMake install target. This is `/usr/local/` and then we use `./share` from that base. For package builds on OS X this is modified to `/var/osquery/`. This allows dual Homebrew + enterprise/site deployments. On Linux based platforms the package installs target `/usr/share/osquery`. 
Ideally site deployments on OS X could mirror Linux but with 10.11 and SIP we are limited to potential collisions with Homebrew in local.
> Install additional configs for HB/packages

- include/osquery/events.h
- include/osquery/registry.h
- osquery/events/darwin/iokit_hid.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/events/tests/events_tests.cpp
Previously, event publishers used a canonicalized 'type' name for async callbacks.
This type was used to lookup the publisher plugin in the registry as well as for backing store namespacing. The type is still used but subscribers, which made heavy used of the lookup, store the value locally. This prevents unneeded publisher plugin allocation when adding events.
> Optimize event publisher database namespace lookups.

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/tests/config_tests.cpp
- osquery/logger/logger.cpp
Previously, `ConfigParserPlugin`s could only maintain an internal derived object called `data_`.
Then parts of the code that knew to use the plugin's data would call `getParsedData` and provide the name of the plugin.
Parser plugins can now request a mutable version of the `ConfigData` using `::mutableConfigData`.
This requires a lock on the `ConfigDataInstance` and must be provided to their mutable accessor.
Acess to a mutable config enables parsers to make modifications to internal config structures like options and the query schedule.
> Allow ConfigParserPlugins to update the ConfigData.

- osquery/filesystem/darwin/plist.mm
- osquery/filesystem/darwin/tests/plist_tests.cpp
- tools/tests/test.plist
Boost property trees are level delimited using '.' characters.
An Apple property list may contain keys with '.' characters, so the plist conversion must use iterators and raw node appends.
> [Fix #1355] Allow plist keys with '.'

- osquery/filesystem/filesystem.cpp
- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/darwin/user_groups.mm
- osquery/tables/system/linux/processes.cpp
I tried my hand at fixing #1303: I don't think optimizing around pid lists > than the number of running pids is worthwhile. Unless I am overlooking something obvious the number of individual `=` operands in a predicate should be 1, else they are superfluous. In the case of a join, there is a separate query for each match.
On OS X the pid existence determination can be quickly resolved using the already-needed sysctl for parent pid checking. On Linux this is a directory check within proc. On both platforms pids must be greater than 0.
> [Fix #1303] Only emit rows when appropriate for processes/users.

- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/tests/apps_tests.cpp
Attempt to use OS X's LaunchServices to get a list of applications.
Fall back to basic directory traversal of well-known application paths.
Note: this may put more stress on existing application listing.
> [Fix #1357] Use OS X LS API for app listing

- README.md
Small fix to remove duplicated "the" - just annoying, nothing else :)
> Remove duplicated "the" in README

- tools/deployment/make_osx_package.sh
This is fixing a regression with the `make_osx_package.sh` deployment script. The autostart postinstall commands had been removed.
> [Fix #1368] Restore autostart post-install scripts

- osquery/config/parsers/query_packs.cpp
- osquery/config/parsers/tests/query_packs_tests.cpp
Comparing 1.4.5 with 1.5.0 was not considered in the tests and it was making the versionChecker to fail. This fixes it.
> Fixing problem with versionChecker and adding usecase to tests

- osquery/filesystem/filesystem.cpp
- osquery/tables/utility/file.cpp
1. Do not allow reads from user-owned FIFOs.
2. Allow users to stat non-readable files.
> [Fix #1367] Disable user-controlled FIFO reads

- osquery/events/darwin/iokit_hid.cpp
- packs/incident-response.conf
1. Only emit results that contain an `location` or `model_id`.
2. Add limits to various incident response pack queries.
> [Fix #1369] Limit IOKit HID events

- osquery/tables/networking/etc_hosts.cpp
- osquery/tables/networking/etc_services.cpp
- osquery/tables/system/darwin/firewall.cpp
- osquery/tables/system/darwin/preferences.cpp
- osquery/tables/system/linux/model_specific_register.cpp
This is an attempt to clean up spurious log lines from table implementations. Table code should emit verbose logs at best.
> Remove some non-warning/error log lines from tables

- CMake/FindBenchmark.cmake
- CMakeLists.txt
- kernel/CMakeLists.txt
- osquery/CMakeLists.txt
Do not build google benchmark tests during default make/build. Also, gate the benchmarking and testing to test-inclusionary build requests.
> Silence google benchmark CMake output, remove benchmark tests

- include/osquery/events.h
- include/osquery/registry.h
- osquery/events/events.cpp
- osquery/events/tests/events_tests.cpp
- osquery/tables/events/linux/passwd_changes.cpp
- osquery/tables/events/yara_events.cpp
1. Allow multiple namespaces using the same publisher and event subscriber combination. The "multiple" means a unique/different namespace for potential subclassing subscribers.
2. Limit YARA results adding to events with matches.
> [Fix #1374] Allow subscription subclassing

- osquery/tables/events/yara_events.cpp
- osquery/tables/other/yara.cpp
- osquery/tables/other/yara_utils.cpp
- specs/yara.table
- specs/yara_events.table
When strings match they will be populated into the "strings" column of the table. The format is identifier:offset.
When a matching rule has tags defined the tags will be put into the "tags" column of the table in a comma separated list.
Also, only operate on CREATED or UPDATED events in the yara_events table.
> Add tags and strings columns to YARA tables.

- osquery/tables/system/linux/users.cpp
See Github issue #1301. FreeBSD (which also uses this table) by default has two
users which are UID 0 -- both `toor` and `root`. 19a2d64959 made it so that we
would only get the first one from `getpwent`, but this feature is undesirable
in cases where two different users share the same UID.
> linux users table: Do not drop users with duplicate UIDs

- include/osquery/events.h
- osquery/events/benchmarks/events_benchmarks.cpp
- tools/benchmark.sh
Benchmarks will be more stable with an average across 5 benchmark runs.
> Benchmark using mean across 5 runs.

- osquery/core/system.cpp
`SIGQUIT` on OS X causes a crash dump.
> Use SIGKILL on OS X

- osquery/events/CMakeLists.txt
- osquery/events/darwin/kernel_util.cpp
- osquery/events/freebsd/kernel_util.cpp
- osquery/events/kernel.cpp
- osquery/events/kernel.h
- osquery/events/linux/kernel_util.cpp
Checks for panics we are involved in and does not load kernel extension.  Otherwise looks for `/var/osquery/.gtfo` with `0660` permissions or a `disable_kernel` flag in the config options.
> Added loading of kernel.

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/parsers/query_packs.cpp
Having the ability to NOT emit "removed" events from queries in packs is essential!
> Apply query options to pack queries

- osquery/dispatcher/CMakeLists.txt
- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/dispatcher.h
- osquery/dispatcher/scheduler.cpp
- osquery/main/run.cpp
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/virtual_table.cpp
- tools/codegen/templates/default.cpp.in
Small tweaks to use less data structures and registry calls when making internal SQL queries. Internal applies to the core components directly using the SQLite implementation.
> Several small optimizations around internal SQL queries

- CMakeLists.txt
- tools/provision.sh
Having `-mtune=i386` is causing compilation failure for gflags on ubuntu. This change removes the `mtune` compile flag.
`-march` flag is already set to `x86-64` and according to gcc docs:
specifying `-march=cpu-type` implies `-mtune=cpu-type.`
Fixes #1428
The `python_test_release` passes:
```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ export RUN_RELEASE_TESTS=1
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make test
cd build/trusty && cmake ../../ && \
CTEST_OUTPUT_ON_FAILURE=1 make --no-print-directory test
-- Building for platform Ubuntu (ubuntu, trusty)
-- Building osquery version  1.4.5-401-g1eea02e sdk 1.4.5
-- Configuring done
-- Generating done
-- Build files have been written to: /vagrant/build/trusty
Running tests...
Test project /vagrant/build/trusty
Start  1: osquery_tests …
```
> [Fix #1428] Remove `-mtune` compile flag

- osquery/tables/system/darwin/keychain_acl.cpp
- osquery/tables/system/darwin/keychain_items.cpp
enum `SecItemClass` changed in 10.11 headers, so don't instantiate with rvalue of int.
Update `SecKeychainSearchCreateFromAttributes` to match the stricter definition.
After we figure out a way forward with OpenSSL, this should be good.
Fixes #1423
> Fix build on OS X 10.11

- osquery/tables/system/darwin/os_version.cpp
#1433 
```
osquery> .all os_version;
+----------+-------+-------+-------+---------+
| name     | major | minor | patch | build   |
+----------+-------+-------+-------+---------+
| Mac OS X | 10    | 11    | -1    | 15A244d |
+----------+-------+-------+-------+---------+
```
```
osquery> .all os_version;
+----------+-------+-------+-------+-------+
| name     | major | minor | patch | build |
+----------+-------+-------+-------+-------+
| Mac OS X | 10    | 10    | 4     | 14E46 |
+----------+-------+-------+-------+-------+
```
> [Fix #1433] Correct os_version reporting on 10.11

- Makefile
When building for OSX 10.9, we need to use a different build directory. This can be used forward when 10.11 comes along.
> Different build directory for darwin != 10.10

- tools/build.sh
OS X 10.9 should not build/test a kernel extension yet. The MAC policy framework is slightly different and the APIs/version dependencies need to be tested.
> Update build/test for 10.9 (do not test extension)

- osquery/tables/system/darwin/homebrew_packages.cpp
#1434
```
osquery> select * from homebrew_packages where name = "osquery";
+---------+----------------------------+---------+
| name    | path                       | version |
+---------+----------------------------+---------+
| osquery | /usr/local/Cellar/osquery/ | 1.5.0_1 |
+---------+----------------------------+---------+
osquery> select * from homebrew_packages where name = "valgrind";
+----------+-----------------------------+---------+
| name     | path                        | version |
+----------+-----------------------------+---------+
| valgrind | /usr/local/Cellar/valgrind/ | HEAD    |
+----------+-----------------------------+---------+
osquery> select * from homebrew_packages where name = "clang-format";
+--------------+---------------------------------+------------+
| …
```
> [Fix #1434] version reporting for homewbrew_packages

- docs/wiki/deployment/kernel-linux.md
- docs/wiki/development/kernel.md
- docs/wiki/installation/install-linux.md
- docs/wiki/installation/install-osx.md
- docs/wiki/introduction/using-osqueryd.md
- kernel/CMakeLists.txt
- mkdocs.yml
- tools/deployment/osquery.example.conf
Add notes for the default packs location based on the method of osquery install.
> [#1402] Add notes around pack paths in example.conf

- tools/deployment/make_osx_package.sh
Using the wrong variable name for the build version was making creating OSX packages in 10.9 to define the wrong build directory.
> Fix for the version variable

- include/osquery/tables.h
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/other/yara.cpp
- osquery/tables/other/yara_utils.cpp
- osquery/tables/other/yara_utils.h
- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/extended_attributes.cpp
1. This commandeers @mofarrell's improvements to SQLite data casting within virtual tables. This will yield about a 10~ improvement for INT, BIGINT, DOUBLE affinite types.
2. A cache of signature compiles for YARA is used when issuing ad-hoc `sigfile` JOINs or SELECTs. The content of the signature file is cached for the life of the `osqueryi` or `osqueryd` process. Changing the underlying signature file will NOT affect the process. This will make pattern-based matching a lot faster. We need benchmarking around this style of scanning.
3. The 10.9 `ifndef/ifdef`s are removed in favor of runtime capability checking.
> Speedup type conversions, yara, and 10.10 symbols at runtime

- osquery/sql/virtual_table.cpp
This should be faster than a boost lexical cast.
http://tinodidriksen.com/2010/02/16/cpp-convert-string-to-int-speed/
> Switch boost lexical casts to strtol

- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- osquery/events/benchmarks/events_benchmarks.cpp
- osquery/events/events.cpp
- osquery/tables/networking/interfaces.cpp
- tools/analysis/clang-analyze.sh
Focusing on reducing the system/user time in the events-based benchmarking: `make run-benchmarks`.
My current results (after change):
```
Benchmark                      Time(ns)    CPU(ns) Iterations
-------------------------------------------------------------
EVENTS_add_events_mean                       246374     137434      10000                                 
EVENTS_retrieve_events/0/100_mean              2463       2330     248993                                 
EVENTS_retrieve_events/0/500_mean              2393       2226     242145                                 
EVENTS_retrieve_events/0/1000_mean             2203       2084     310875                                 
EVENTS_retrieve_events/0/9.76562k_mean         2780       2639     221248 
```
> RocksDB usage speedups

- CMake/Packages.cmake
- tools/deployment/make_linux_package.sh
- tools/provision/lib.sh
- tools/provision/ubuntu.sh
Had some troubles getting the package to install on lucid. It looks like there are some dependencies specified by the package that are not actually required.
```
vagrant@vagrant:~/osquery_official/osquery/build/lucid$ sudo dpkg -i osquery-1.5.1-59-g43cf5f1.deb
(Reading database ... 56769 files and directories currently installed.)
Preparing to replace osquery 1.5.1-1-g7a72534-1.ubuntu (using osquery-1.5.1-59-g43cf5f1.deb) ...
Unpacking replacement osquery ...
dpkg: dependency problems prevent configuration of osquery:
osquery depends on libc6 (>= 2.15); however:
Version of libc6 on system is 2.11.1-0ubuntu7.21.
osquery depends on libapt-pkg4.12; however:
Package libapt-pkg4.12 is not installed.
dpkg: error processing osquery (--install):
dependency problems - leaving unconfigured …
```
> Fix lucid package building

- CMakeLists.txt
- tools/provision/darwin.sh
- tools/provision/lib.sh
Recapping from #1425:
* It wasn't straightforward to get OpenSSL building without avx/vxorps optimizations on 10.10
* After chatting with @theopolis, we decided libressl was the way to go. It is essentially a modern/lean-ish drop-in replacement for OpenSSL and we can build without avx optimizations to support older Macs.
This change:
* Installs libressl (builds a bottle) using homebrew
* And statically links `libcrypto.a` and `libssl.a`
| binary | libressl static link size | size after striping symbols | difference |
| -------- | ----------------------------: | ----------------------------------: | ------------: |
| osqueryd |  9232344 | 7841472 | 1390872 (~1.32MiB) |
| osqueryi |  9261632 | 7866872 | 1394760 (~1.33MiB)|
Thanks again for all the help on this @theopolis
Fixes #1329
> [#1329] Statically link against brew bottled libressl on OS X

- CMakeLists.txt
Only statically link brew's LibreSSL if building on 10.11 (where no OpenSSL is provided) or when explicitly asked.
> Optionally use LibreSSl

- osquery/filesystem/darwin/plist.mm
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/launchd.cpp
- osquery/tables/system/darwin/packages.cpp
- osquery/tables/system/darwin/preferences.cpp
Instead of rotating the generated data from row to columns, access each row/column directly. Although there were optimizations around space within the rotation, this improves query performance by a factor of `1.25`.
Before:
```
Benchmark                         Time(ns)    CPU(ns) Iterations
----------------------------------------------------------------
SQL_virtual_table_registry            2134       2128     311644                                 
SQL_virtual_table_internal          113019     112584       6089                                 
SQL_virtual_table_internal_long    1971752    1964762        340                                 
SQL_virtual_table_internal_wide    2192625    2185087        310                                 
SQL_select_metadata                  40653 …
```
> Remove VirtualTable matrix rotation

- docs/wiki/deployment/configuration.md
Yes the tool immediately told me the correct subcommand, just a docs tweak to reflect the proper order. 😅
> osqueryctl subcommand reversed in doc

- CMakeLists.txt
A build will fail if you install libraries (like gflags) that only include a static version and include the `BUILD_LINK_SHARED` environment flag. Practically, this will fail when installing from brew.
> Allow static linking when BUILD_LINK_SHARED is used

- Vagrantfile
- osquery/tables/networking/linux/tests/iptables_tests.cpp
- tools/lib.sh
- tools/provision.sh
- tools/provision/debian.sh
- tools/provision/files/debian/condition_variable.patch
Refs https://github.com/facebook/osquery/issues/320
Add provisioning scripts to build osquery on Debian Wheezy and Debian Jessie.
The build for Debian Wheezy isn't pretty: it downloads Clang 3.4 (not 3.5, because it has some issues with some specific code. That's fixable, but wasn't sure it was needed. It also patches a header file in /usr/include/ to be able to build. The result is that osquery can run without anything special on a clean wheezy system.
> Build on Debian Wheezy and Debian Jessie

- docs/wiki/deployment/remote.md
- osquery/remote/enroll/enroll.cpp
In response to #1460 this pull request attempts (and fails) to create a flag `--enroll_secret_env` which would provide an environment variable. The code in this PR compiles and runs but creates segfaults.
```
Aug 21 18:27:20 ip-172-31-28-89 kernel: [788874.184360] osqueryd[13990]: segfault at 0 ip 00007f4bbf668aea sp 00007fff1dda1308 error 4 in libc-2.19.so[7f4bbf5e0000+1bb000]
```
This PR is intended to get the conversation going so we can decide how to implement this (if at all).
> Attempts to add a cli flag --enroll_secret_env

- Makefile
I occasionally rely on doxygen generated wiki, and `make docs` is currently broken with `no such directory/file error`
`genapi.py` (and hence `make docs`) [expects `build/docs` directory to exist.](https://github.com/facebook/osquery/blob/master/CMakeLists.txt#L359)
However this directory wouldn't exist if `make distclean` is run or `build` directory is nuked.
This change creates the docs directory if it doesn't exist.
> Fix doxygen docs generation

- CMake/Packages.cmake
Fun fact, this wont build on Debian stable, since Jesse only includes libgcrypt20. For our purposes, and from our build/package host's perspective, `debian-based` means Ubuntu.
> [#1455] Add libgcrypt11 as a package dependency for debian builds

- docs/wiki/deployment/remote.md
- include/osquery/core.h
- include/osquery/enroll.h
- osquery/config/plugins/tls.cpp
- osquery/core/system.cpp
- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/dispatcher/scheduler.cpp
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/extensions/tests/extensions_tests.cpp
- osquery/logger/plugins/tls.cpp
- osquery/remote/enroll/enroll.cpp
- osquery/remote/enroll/plugins/tls.cpp
- osquery/remote/enroll/tests/enroll_tests.cpp
- osquery/remote/requests.h
- osquery/remote/transports/tls.cpp
- osquery/remote/transports/tls.h
This extends the TLS-based plugin configuration options by allowing the configuration/flags to set the name of the enrollment/access key as well as a boolean to toggle "always on" enrollment authentication in the case where a shared deployment secret must be included with every request.
> Add 'hidden' flags to customize TLS plugins

- osquery/filesystem/darwin/plist.mm
Removing the ptvalue typedef in favor of just using `pt::ptree::value_type`
> Removing the ptvalue typedef

- include/osquery/config.h
- include/osquery/core.h
- include/osquery/events.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- osquery/config/tests/packs_tests.cpp
- osquery/core/darwin/conversions.cpp
- osquery/core/watcher.cpp
- osquery/events/kernel/circular_queue_user.h
- osquery/extensions/interface.h
- osquery/registry/registry.cpp
- osquery/remote/requests.h
- osquery/tables/CMakeLists.txt
- osquery/tables/networking/linux/iptables.cpp
- osquery/tables/system/linux/mounts.cpp
1. Apply performance and style cleanups from `cppcheck`.
2. Prefer dynamic/dependent linking of `libmagic` on Linux.
3. Use the boost package alias on Ubuntu to avoid deep dependency error for `make deps`.
> Static analysis cleanups, static libmagic

- osquery/tables/applications/browser_firefox.cpp
- osquery/tables/applications/browser_utils.h
- osquery/tables/applications/darwin/browser_plugins.cpp
- specs/firefox_addons.table
Plist `.count` does not evaluate embedded keys. We can skip the existence checking and supply a default value = `""` when the key or embedded key does not exist in the input JSON.
> [Fix #1492] Fix firefox key counting and spec typo

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/tables/utility/osquery.cpp
- specs/utility/osquery_info.table
```
$ ./build/darwin/osquery/osqueryi --config_path=/asdfasdfadfs
E0903 11:45:02.050308 1990836992 init.cpp:370] Error reading config: config file does not exist
osquery> .all osquery_info
pid = 33700
version = 1.5.2-43-gb06fa92
config_md5 =
config_valid = 0
config_path = /asdfasdfadfs
extensions = active
build_platform = darwin
build_distro = 10.10
osquery> .exit
$ ./build/darwin/osquery/osqueryi
osquery> .all osquery_info
pid = 33781
version = 1.5.2-43-gb06fa92
config_md5 = 8a432ac93d3de080c62d77ba99b89783
config_valid = 1
config_path = /var/osquery/osquery.conf
extensions = active
build_platform = darwin
build_distro = 10.10
osquery> .exit
```
#1486
> Config MD5 a bit more deterministic

- osquery/tables/events/linux/process_events.cpp
Apparently GCC prior to version 5.0 (we're using 4.8.4 on Lucid) uses the C89 semantics for dealing with "inline" functions, and it appears the linker is removing this "unused" function from the static library. The easiest fix is to simply remove the "inline" from the definition. This *should* be ok because based on my understanding, the compiler needs the source code to be able to optimize an inline function, and that isn't available when linking a static library.
As always, please let me know if you have any concerns or questions. Thanks!
> Fix build for Ubuntu Lucid

- include/osquery/events.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/main/tests.cpp
- osquery/tables/utility/osquery.cpp
- specs/utility/osquery_events.table
- tools/tests/stress.py
This adds tracking data to subscribers and publishers. A scheduled query to `osquery_events` allows one to determine if any publishers are trashing or if their subscriptions are generating too many uncaught events.
> [#1487] Add osquery_events table to track pubsub stats

- osquery/tables/system/darwin/sysctl_utils.cpp
- osquery/tables/system/darwin/system_info.cpp
- specs/darwin/system_info.table
This change adds:
* `cpu_type` 
* `cpu_subtype`
* `cpu_brand`
* `cpu_physical_cores`
* `cpu_logical_cores`
* `physical_memory`
* `hardware_model` 
columns to `system_info` table.
Here's how it looks:
```
osquery> .all system_info;
hostname = <redacted>
uuid = <redacted>
cpu_serial = <redacted>
cpu_type = x86_64h
cpu_subtype = Intel x86-64h Haswell
cpu_brand = Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
cpu_physical_cores = 4
cpu_logical_cores = 8
physical_memory = 17179869184
hardware_model = MacBookPro11,3
```
I don't think there is a (public) IOKit API to get human readable strings for cpu info, so this relies on two mach calls: `host_info` and `sysctlbyname`.
I also briefly looked at `ioreg`, but didn't find a way (yet) to get IO/PCH chipset model/version. Maybe …
> Update system_info table to include CPU type, CPU cores and total memory

- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
Catch normal tear-down related signals and allow the event factory's publisher threads time to run their `tearDown` methods. If threads are not joined within a timeout (10s) the process exits with `SIGSTOP`.
`SIGHUP` is also caught and does nothing.
> [#1488] Use signal handlers for teardown and reloading

- include/osquery/enroll.h
- osquery/distributed/distributed.cpp
- osquery/distributed/tests/distributed_tests.cpp
- osquery/remote/enroll/enroll.cpp
- osquery/remote/enroll/tests/enroll_tests.cpp
Distributed tests were failing every now and then because the test
plugin didn't implement retry's and the test server wasn't always
starting up fast enough. I fixed this by refactoring the tests to use
the real TLS plugin, which has retry logic. This required some mangling
of the configuration options, which should serve as a good reference as
well.
> Making distributed tests more awesome and less flaky

- kernel/src/osquery.cpp
- osquery/events/darwin/kernel_util.cpp
- osquery/events/kernel.cpp
- osquery/tables/system/darwin/packages.cpp
1. Clean up kernel extension build compile warnings.
2. Only try to load an OS X kernel extension if the `com.facebook.osquery.kernel` package is installed by searching for the package receipt on daemon start.
3. Emit a more appropriate verbose INFO log if the kernel extension's device node does not exist or is not readable.
> [#1506] Silent kext loading messages from syslog

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/dispatcher/scheduler.cpp
If a scheduled query fails to complete it will be recorded within the backing store (RockDB). On the next daemon, or worker, load: a `WARNING` log message will be generated. This can be used to monitor failing queries across a fleet but aggregating status logs.
> Scheduled query success tracking

- Vagrantfile
- osquery/tables/system/linux/os_version.cpp
* There is an issue with the regex for os_version in the `/etc/redhat-release` file, this change properly 
parses version on RHEL6/RHEL7.  
* I also included a new Vagrant box link as chef/centos-6.5 doesn't show up anymore as a valid remote box. 
```
osquery> SELECT * FROM os_version;
+---------------------------------+-------+-------+-------+-------+
| name                            | major | minor | patch | build |
+---------------------------------+-------+-------+-------+-------+
| Red Hat Enterprise Linux Server | 7     | 1     | -1    |       |
+---------------------------------+-------+-------+-------+-------+
```
> RHEL os_version fix

- osquery/core/init.cpp
- osquery/events/darwin/diskarbitration.cpp
- osquery/events/darwin/diskarbitration.h
- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/iokit_hid.h
- osquery/events/darwin/scnetwork.h
When CTRL+C, SIGINT, SIGTERM, or SIGABRT is sent to osqueryd, the event publishers should stop gracefully within 4 seconds. A secondary signal will cause the application to stop immediately.
> [#1488] Stop OS X event publishers with SIGINT

- osquery/events/linux/audit.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/udev.cpp
- tools/deployment/osqueryd.initd
Each linux publisher should shutdown within a second when the service is turned down or a terminate signal is received. 
1. Enforce a max of 1-second blocking periods for each Linux publisher.
2. Make the Linux init script smarter, it should wait for workers and worker threads to stop.
> [#1488] Shutdown Linux event publishers responsibly

- osquery/database/database.cpp
- osquery/database/db_handle.cpp
- osquery/events/events.cpp
- osquery/tables/system/linux/processes.cpp
1. Allow osqueryi to run without a RocksDB when using RocksDB LITE.
2. Protect against malformed /proc data when processing on Linux.
> [#1529] Allow DB Readonly with RocksDB lite

- osquery/tables/applications/darwin/browser_plugins.cpp
The libarchive API seems to still leak with XAR header entry parsing, be careful!
> [Fix #1531] Use libarchive finish for safari_extension parsing

- osquery/filesystem/filesystem.cpp
Previously, if there is a symlink loop and a complete-recursive glob (`**` or `%%`) is used the offending query will hang the process.
> Fix potential hang with recursive globbing

- osquery/config/config.cpp
This fixes a bug that was incorrectly checking the `valid_` flag, causing the `getMD5` function to return a bad status and not compute a hash, which would in turn cause `genOsqueryInfo` to set the hash to an empty string.
https://github.com/facebook/osquery/blob/master/osquery/config/config.cpp#L302
https://github.com/facebook/osquery/blob/64c18a70a9eb6030405bb0253ed0ee8ee9928d82/osquery/tables/utility/osquery.cpp#L193
> Fixed bug when checking if config is valid

- include/osquery/config.h
- include/osquery/packs.h
- osquery/config/packs.cpp
- osquery/config/tests/packs_tests.cpp
- tools/tests/test_inline_pack.conf
There was a bug in the `osquery::Schedule` container object such that,
when the iteration through the schedule occured, pack objects were being
passed by value (copied) instead of passed by reference. Thus, the
discovery query would be executed, the object's cache would be updated,
and then the object would go out of scope and be destructed, thus
leaving the original object without ever having ran the discovery query.
This caused discovery queries to thrash. Bad times.
I added a new test so that we don't regress here as well as const'd a
few functions that should have been const in `osquery::Pack`.
> [fix #1536] Schedule iteration pass-by-reference

- docs/wiki/installation/install-linux.md
Added the character "d" to two lines to fix a typo.
From:
sudo service osquery start
sudo service osquery status
To:
sudo service osqueryd start
sudo service osqueryd status
> Typo in linux installation docs

- docs/wiki/installation/cli-flags.md
- osquery/core/init.cpp
- osquery/dispatcher/distributed.cpp
- osquery/distributed/distributed.cpp
Use the `--disable_{feature}` "style". We could also support both, at the cost of a few additional strings if we used `FlagAlias`s.
> Minor nits around distributed CLIs

- tools/deployment/osquery.example.conf
This trailing comma was making the default config to fail since the last one is commented.
> Fixing default configuration syntax, trailing comma

- CMakeLists.txt
- osquery/config/CMakeLists.txt
- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- osquery/database/tests/db_handle_tests.cpp
- osquery/extensions/CMakeLists.txt
- osquery/remote/transports/tls.cpp
- osquery/tables/system/darwin/kernel_info.cpp
- osquery/tables/system/linux/kernel_info.cpp
- specs/kernel_info.table
1. RocksDB LITE is writing DB SUMMARY logs to WARN, bump the error logging to ERROR.
2. Silence OS X 10.11 compile warnings for Thrift/Boost.
3. Fix the `path` column in the `kernel_info` table on OS X, and remove `md5` from the spec, prefer a JOIN to `hash.
> Bumb RocksDB to ERROR, fix OS X kernel_info, silence compile warnings

- osquery/tables/networking/interfaces.cpp
This PR fixes an issue we saw on our machines where the osquery process would eventually exhaust the number of allowed open file descriptors on the machine. Root cause appears to be when generating the `interface_details`, the socket created for use with `ioctl` calls is not closed.
EDIT: Clearified that we saw the number of lingering file descriptors increasing on all machines, this was \*not\* an intermittent issue.
> Close socket fds when finished with them

- CMake/FindGlog.cmake
- CMakeLists.txt
- docs/README.md
- kernel/CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/logger/logger.cpp
1. Use the OS X ABI compile flag in the Glog external project.
2. Add `SKIP_BENCHMARK` to skip building benchmark binaries.
> Build Glog with OS X ABI, add SKIP_BENCHMARK

- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
If you try really hard you could mess up and delete ".*" files you do not intend. Under normal runs the extension manager path will not be changed. However, if you change the path to an existing file it will be overwritten (this artifact has existed for a while), but now that `path + ".*` will be overwritten by both extension sockets and the clean up routines.
> Extension managers should clean extension sockets when starting

- osquery/core/init.cpp
Reset `LC_ALL` to "C" if `boost::filesystem` cannot handle the system/user-configured `LC_CTYPE`
> [Fix #1559] Allow boost.filesystem incorrect LC_CTYPE

- docs/wiki/installation/install-osx.md
Even though I’m unsure myself, since I noticed there’s no mention of 10.11 support or really any sysReqs, I added it to the docs. (May want to bump the readme with that info as well, didn’t feel like I should be making that call.) 
Pardon the presumption of accuracy 😅
> explicitly call out OS and requirements at top of OS X install doc

- osquery/events/linux/inotify.cpp
- osquery/tables/system/ubuntu/apt_sources.cpp
- osquery/tables/system/ubuntu/deb_packages.cpp
This fixes a crash identified by @endrazine. When apt sources data in `/etc/apt/sources.list` or `/etc/apt/sources.list.d/{*}.list` contain invalid data/lines the `cache_file.GetPkgCache();` call will fail and `cache` will be `nullptr`. Subsequent usage results in a `SIGSEV`.
To reproduce the fault try:
```
$ zzuf -I /etc/ -r 0.01:0.1 -s 0:1000 -v \
./build/trusty/osquery/osqueryi --registry_exceptions=true --verbose \
"select count(*) from apt_sources"
```
Signed-off-by: Jonathan Brossard
> [Fix #1570] Check for invalid apt sources

- osquery/tables/networking/interfaces.cpp
getifaddrs(3) states that ifa_addr can be null. Check to make sure they are not null before accessing them
> Fix segfault on interfaces tables

- osquery/tables/utility/file.cpp
- specs/utility/file.table
To support <i>many-more</i> file types we should deprecate the `is_type`-style columns in the `file` table and use a somewhat catchall-style `type` that reports the textual file type.
> Remove boolean type-columns from file in favor of 'type'

- CMake/FindLibdpkg.cmake
- Vagrantfile
- osquery/tables/CMakeLists.txt
- osquery/tables/system/ubuntu/deb_packages.cpp
Libdpkg has some breaking changes in newer versions which prevented
compiling the deb_packages table on Ubuntu 15.04.  This change looks for
the libpkg version user pkg-config and adds some preprocessor magic to
support the newer versions.
> Support for newer versions of libdpkg

- kernel/CMakeLists.txt
`kernel-make-target` cmake target fails due to a syntax error because of the parentheses.
> Fixing kernel-configure-target syntax error

- osquery/config/config.cpp
- osquery/core/conversions.cpp
- osquery/distributed/distributed.cpp
- osquery/events/events.cpp
- osquery/filesystem/filesystem.cpp
- osquery/remote/utility.h
- osquery/tables/applications/browser_utils.cpp
- osquery/tables/events/yara_events.cpp
- osquery/tables/networking/interfaces.cpp
- osquery/tables/networking/linux/iptables.cpp
- osquery/tables/networking/linux/routes.cpp
- osquery/tables/networking/linux/tests/iptables_tests.cpp
- osquery/tables/other/yara.cpp
- osquery/tables/system/linux/mounts.cpp
- tools/codegen/templates/default.cpp.in
Removed calls to std::move (mostly in return statements) that would prevent copy elision.
> eliminated some warnings from Clang 3.7 analyze mode

- CMakeLists.txt
- include/osquery/filesystem.h
- osquery/core/hash.cpp
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
A TOCTOU flaw exists in the `readFile` method, which allows any user to possibly cause `osqueryd` to open arbitrary files. The opened file streams are then checked for size limits and types (more so just for FIFOs owned by users). This may lead to undefined behavior and certainly unwanted behavior.
This diff changes the `readFile` implementation to remove symlink checking and prefer checking ownership/access via the opened file descriptor. If osquery is running as a privileged user, credentials are set to the non-root user that owns the target file's directory.
> Fix readFile TOCTOU error

- include/osquery/config.h
- include/osquery/events.h
- include/osquery/packs.h
- kernel/CMakeLists.txt
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/parsers/events.cpp
- osquery/config/parsers/tests/events_tests.cpp
- osquery/config/tests/config_tests.cpp
- osquery/config/tests/packs_tests.cpp
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/events/tests/events_tests.cpp
- osquery/tables/events/darwin/process_events.cpp
- osquery/tables/events/linux/socket_events.cpp
- osquery/tables/events/yara_events.cpp
- osquery/tables/networking/linux/process_open_sockets.cpp
- osquery/tables/system/darwin/process_open_descriptors.cpp
- specs/linux/socket_events.table
- specs/process_open_sockets.table
The refactor of config/packs was initiated because event subscribers needed a method for toggling `::init` based on some configurable option. In the case of auditd, turning on the support with `--disable_audit=false` used to start auditing the EXECVE syscall. It was understandable that this would cause latency based on the number of processes executing per measure of time.
A new `socket_events` table will do the same but for `bind` and `connect`. These are less-obvious and for now, require a scan of /proc for socket tuples. In the future this file descriptor to socket tuple will be faster.
A config may now contain:
```json
{
"events": {
"enabled_subscribers": [ "socket_events" ],
"disabled_subscribers": [ "process_events" ]
}
}
```
By default the `socket_events` table is disabled. This …
> Refactor a bit of config and add socket_events table to Linux

- osquery/core/init.cpp
- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- tools/provision/lib.sh
This extends the `DBHandle` interface to include a concept of "required R/W" and then sets that requirement for both checking DB sanity and opening a process-global RocksDB handle for only the daemon process.
> [Fix #1583] Require osqueryd to have R/W access to RocksDB

- docs/wiki/deployment/file-integrity-monitoring.md
- osquery/events/linux/inotify.cpp
- osquery/events/linux/tests/inotify_tests.cpp
This reduces inotify's (our Linux FIM implementation) scope to file modifications. The file access table on Linux will become more-or-less useless for the time being.
> [#1600] Put inotify into a mod-only watch mode

- osquery/config/tests/config_tests.cpp
- osquery/events/linux/audit.cpp
- osquery/events/linux/tests/audit_tests.cpp
This fixes a problem in my assumption about audit message being either (a) base64 encoded or (b) a single string not containing spaces, `"`, or `=`. It's possible for each key=value to contain integer values, non-`"` encapsulated string values, base64 encoded strings, or `"` encapsulated strings that contain spaces and `=`.
> Fix auditd message parsing

- requirements.txt
- tools/tests/test_extensions.py
Reviewing a few of the annoying failed integrations tests, I find that a few (extensions) are always the culprits. It doesn't make sense to remove, skip, or retry tests if these fail so we end up merging anyway. Hopefully marking these as [flaky](http://opensource.box.com/flaky/) will help!
One way to find out!!!!
> Mark flaky integration tests

- osquery/tables/events/linux/process_events.cpp
The `exec` family may emit non-0 return statuses, opaque to the caller, we do _not_ want to audit these.
> Only emit process events for 0-status execve

- include/osquery/filesystem.h
- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/filesystem/filesystem.cpp
Based on the implementation example from #1612.
> [Fix #1611] Prevent fs links in inotify path search

- include/osquery/core.h
- osquery/CMakeLists.txt
- osquery/core/hash.cpp
- osquery/core/system.cpp
- osquery/core/tests/permissions_tests.cpp
- osquery/filesystem/darwin/plist.mm
- osquery/filesystem/filesystem.cpp
- osquery/tables/applications/darwin/browser_plugins.cpp
Move the `DropPrivileges` helper class into `core.h` so it can be used throughout the code base. There are several locations where the `readFile` abstraction cannot be used: plist stream parsing, archive parsing, and hashing (for some examples). It is mostly important to drop privileges before (1) operating on someone else's data, and (2) using that data within library/odd structure parsing implementations. In the case of a crash, it would be ideal if the application's effective user was non-super.
> Expand the scope of permissions dropping

- osquery/database/db_handle.cpp
- osquery/events/events.cpp
The list and ID for events errors do not matter much. The specific filenames in RocksDB IOErrors are equally noisy and require specific backend aggregation logic. It's best to have repeatable errors.
> Remove specific filenames from RocksDB IOErrors

- include/osquery/config.h
- include/osquery/core.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- osquery/core/init.cpp
- osquery/core/system.cpp
- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/tables/utility/osquery.cpp
1. Add a blacklist for failed queries.
2. Add some warnings around `DBHandle` creation if it is not expected.
The blacklist works a follows:
- If a query is executing and the watchdog process stops the worker the next start will emit a warning about the offending query. That query will be added to the blacklist with an eviction/expiration time of 24h.
- The blacklist is saved every time a dirty query is found or expiration for a query occurs.
- An expiration time is absolute, if the process stops completely, time still counts.
- At expiration time the blacklist is saved and the query may again execute.
> [Fix #1626] Add schedule blacklist and protect DBHandle

- docs/wiki/deployment/configuration.md
- docs/wiki/installation/cli-flags.md
- osquery/config/config.cpp
- osquery/config/packs.cpp
Allow configurations to override the pack query name limiter. It makes sense to eventually make the default delimiter "/" since "_" is often used within query names.
> Add pack_delimiter option

- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
This removes the check for user controlled FIFOs and instead allows reads of pseudo files up until a configuration-defined max limit. There may be ways to improve the read performance, this could use some integration tests and benchmarking.
> Allow user-controlled FIFOs

- osquery/CMakeLists.txt
- osquery/core/system.cpp
- osquery/main/run.cpp
- osquery/tables/system/cpuid.cpp
- osquery/tables/system/darwin/system_info.cpp
- osquery/tables/system/linux/system_info.cpp
- specs/system_info.table
- tools/tests/utils.py
As of now, this is a WIP since the Linux version of `system_info` is fairly incomplete. I'm debating parsing structures in /proc.
> [#1546] Add computer_name to system_info and extend to Linux

- include/osquery/filesystem.h
- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/filesystem/filesystem.cpp
The inotify event publisher needed some more tests, and was not handling `/etc` as a directory to monitor.
> Linux inotify should accept non-glob dirs

- include/osquery/core.h
- osquery/core/hash.cpp
- osquery/core/system.cpp
- osquery/database/db_handle.cpp
- requirements.txt
- tools/tests/test_additional.py
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/test_osqueryd.py
- tools/tests/test_release.py
The previous privilege dropping logic was incorrect w.r.t to dropping group privilege. This switches the order and drops the effective group before the user.
> Add GID to PrivilegeDropper

- osquery/config/parsers/file_paths.cpp
- osquery/tables/networking/darwin/wifi.mm
The `file_paths` config parser may act on POD and the Wifi table may attempt to release data it has not allocated.
> Fix missed nullptr checks in wifi

- osquery/tables/CMakeLists.txt
- osquery/tables/system/darwin/signature.mm
- osquery/tables/system/darwin/tests/signature_tests.mm
- specs/darwin/signature.table
This table allows verifying the signature of files (or bundles) on
Darwin.  It also provides the signing identifier that is a part of the
signature.
I've made a couple of possibly-controversial changes here, most important of which is adding a dependency on the Cocoa framework in order to get access to NSAppKitVersionNumber.  If this is something you'd rather not support, let me know and I'd be happy to strip that portion out.
> Add a `signature` table on Darwin

- osquery/tables/utility/time.cpp
- specs/utility/time.table
So, this is the minimum version of what is necessary.  In an ideal world, we could pull in [ICU](http://site.icu-project.org/) and use that [to get the Olson timezone](http://userguide.icu-project.org/datetime/timezone).  That does pull in another dependency, so I'm not going to do that for now.
However, for future reference, this does more-or-less the right thing:
```
#include <unicode/timezone.h>
#include <iostream>
using namespace U_ICU_NAMESPACE;
std::string getTimezone() {
TimeZone* tz = TimeZone::createDefault();
UnicodeString us;
tz->getID(us);
std::string s;
us.toUTF8String(s);
delete tz;
return s;
}
int main() {
auto tz = getTimezone();
std::cout << "Current timezone ID: " << tz << std::endl;
return 0;
}
```
> Add timezone field to time table

- docs/wiki/installation/cli-flags.md
- osquery/logger/plugins/filesystem.cpp
- tools/tests/test_osqueryd.py
This is useful in cases where you want an external process (e.g. a log forwarder running with dropped privs) to be able to read the log files, but still want to run `osqueryd` as root in order to gather information.
Quick note: I'm not sure why, but the test isn't working as expected.  Any idea why that might be?  This is the only actual mode I was able to find in the codebase.
> Allow setting the mode of log files

- osquery/tables/CMakeLists.txt
- osquery/tables/system/darwin/signature.mm
I wasn't super happy with the new dependency on Cocoa, so I took another look at how other parts of `osquery` determined the system version and copied them.  Upside: less dependencies!  Downside: slightly more code :disappointed: 
P.S. Sorry for all the PRs today :smile:
> Refactor how we determine the OS version in the signature table

- osquery/filesystem/filesystem.cpp
- osquery/tables/utility/hash.cpp
1. Update the directory enumeration functions to use the osquery filesystem APIs.
2. Use `noexcept` methods of evaluating filesystem properties in the `hash` table.
> Use a noexcept method of directory checking for hash

- osquery/tables/system/freebsd/processes.cpp
It's not totally clear why saved IDs were used here. There is some precident in
sigar (https://github.com/hyperic/sigar), where they also use the saved UID,
but me and @wxsBSD are not really sure why. Maybe it's because kinfo_proc feels
different than similar structs on other Unices.
Fixes #1662.
> freebsd process table: Fix EUID/EGID to not use saved IDs

- osquery/events/linux/audit.cpp
- osquery/events/linux/audit.h
- osquery/tables/events/linux/user_events.cpp
- specs/linux/user_events.table
This captures the USER* related audit messages in a `user_events` table. This table is *for now* Linux only.
> [#1497] Add user_events table based on audit user-type messages

- osquery/config/packs.cpp
Kept running into this clang analyzer warning with Xcode 7.1.1 and clang-700.1.76 on OS X 10.10.5
```
[ 11%] Building CXX object osquery/config/CMakeFiles/osquery_config.dir/packs.cpp.o
In file included from /Users/sbs/projects/osquery/osquery/config/packs.cpp:11:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2920:52: 
warning: The result of the '>>' expression is undefined
__mask0_ = __w0_ > 0 ? _Engine_result_type(~0) >> (_EDt - __w0_) :
~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
1 warning generated.
```
Traced it to `std::uniform_int_distribution` which takes `IntType` as the template parameter, and is undefined if it's not one of the `IntType`. Switched it to using `uint32_t` instead of `size_t` and clang-analyzer is …
> Fix clang-analyzer warning

- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/tables/applications/browser_firefox.cpp
- osquery/tables/applications/browser_utils.cpp
- osquery/tables/applications/browser_utils.h
- osquery/tables/applications/darwin/browser_plugins.cpp
- osquery/tables/system/authorized_keys.cpp
- osquery/tables/system/known_hosts.cpp
- osquery/tables/system/shell_history.cpp
- osquery/tables/system/system_utils.cpp
- osquery/tables/system/system_utils.h
- specs/authorized_keys.table
- specs/chrome_extensions.table
- specs/darwin/browser_plugins.table
- specs/darwin/safari_extensions.table
- specs/firefox_addons.table
- specs/known_hosts.table
- specs/opera_extensions.table
- specs/shell_history.table
The default expectation/policy for tables based primarily on user data is to generate content for the user running osquery only. To support listing content from all users the user data-based table must support an `additional` key and be marked with the attribute `user_data=True`. The additional key **SHOULD** be `uid` such that:
```sql
SELECT * from users join USER_DATA_TABLE using (uid)
```
Is performant.
> [#1665, #1615] Refactor user-based tables to act uniformly

- packs/hardware-monitoring.conf
- packs/incident-response.conf
- packs/osquery-monitoring.conf
- packs/osx-attacks.conf
- packs/vuln-management.conf
- tools/deployment/osquery.example.conf
- tools/tests/test_additional.py
1. Recent changes to user-data-based tables will only return data for the current user unless you set a value for the `additional` field (`uid`). These scheduled queries need to join against `users`.
2. Add helpful internal monitoring queries.
3. Add potentially noisy inventory-based device and hardware monitoring packs.
> Add hardware/internal (monitoring) packs and reduce FPs, duplicates

- osquery/core/init.cpp
OS X's launch daemon's `ProgramArguments` may over write `argv[0]` for the osqueryd process. This will unintentionally set Glog's log prefix (filename) to what should be the first argument to the process.
> Use a static 'binary' name for Glog

- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/darwin/keychain_utils.cpp
- osquery/tables/system/darwin/tests/certificates_tests.cpp
- specs/darwin/certificates.table
- Some authority certificates are missing a CN so include the complete `subject` distinguished name.
- The algorithm used to sign the certificate (`signing_algorithm`) is now includes.
> [Fix #1686] Add 'subject' and 'signing_algorithm' to certificates

- tools/provision/lib.sh
- tools/provision/ubuntu.sh
The build was failing at 2 points:
1) Building Thrift:
- required newer OpenSSL 1.0.0+. The latest available in lucid repositories is OpenSSL 0.9.8
- required Bison >=2.5. The latest available in lucid repositories is Bison 2.4.8
2) Python packages were failing to install with pip, because they required python >=2.7, but the latest python for lucid is python 2.6. These packages are - argparse, jinja2, psutil.
After fixing these two points the build became successful. 
For testing if build is working I was using Docker with this Dockerfile:
```
FROM ubuntu:lucid
RUN apt-get update
RUN apt-get -y install git-core
RUN git clone https://github.com/jajce/osquery.git
RUN cd osquery/ && make deps
RUN cd osquery/ && make
RUN cd osquery/ && make packages
```
> Fixing build for Ubuntu 10.04 Lucid

- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
- osquery/tables/CMakeLists.txt
- tools/codegen/gentargets.py
1. This fixes a constraint stacking regression that prevented UNIONS with embedded constraints from working as expected. The bug introduced would stomp constraints on subsequent selects operating on the same virtual table.
2. This adds a small "runtime" query planner that prints to `stderr` *some* actions taken by the constraint parser and filter.
> [Fix #1693, #1527] Add osquery-specific query planner output

- osquery/tables/networking/linux/routes.cpp
- tools/provision.sh
- tools/provision/centos.sh
The NETLINK read logic seemed incorrect. Previously this would exhaust the read latency as there are usually several `recvfrom` calls needed to read the entire NETLINK message.
> [Fix #1660] Prevent spurious NETLINK recv retries

- osquery/tables/applications/browser_utils.cpp
Previously the ID was embedded into the path. The `identifier` column was added for this ID, not the path-encoded version.
> Fix chrome-based extension virtual table ID extraction

- osquery/logger/logger.cpp
- osquery/logger/plugins/syslog.cpp
- osquery/logger/tests/logger_tests.cpp
- osquery/registry/registry.cpp
- tools/tests/test_extensions.py
This is mostly a PoC for multiple "active" plugins. Setting a comma-separated list of loggers on start should turn them both on and send all messages to both simultaneously, serially.
> [#1648] Support multiple loggers

- docs/wiki/development/building.md
- include/osquery/config.h
- include/osquery/database.h
- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/database/database.cpp
- tools/tests/test_osqueryi.py
From #1702:
This provides (1) and (3). The second bullet is skipped since it takes a bit more work and is not straight forward that it should even exist beyond a method for debugging. If a config fetch fails the daemon stops.
> [#1702] Add config and database dumping to stdout

- osquery/core/hash.cpp
- osquery/tables/forensic/sleuthkit.cpp
- specs/device_hash.table
- tools/profile.py
1. Clean up sleuthkit tables.
2. Add `device_hash` table that takes a `device`, `partition`, and `inode` tuple to calculate hashes.
> Additional TSK table: device_hash

- include/osquery/config.h
- include/osquery/packs.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/core/system.cpp
- osquery/dispatcher/CMakeLists.txt
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/tests/scheduler_tests.cpp
- osquery/remote/enroll/enroll.cpp
1. Change interval restrictions to include a max of 1 week. Anything over a week will not be added to the schedule and will emit a log.
2. Every time the configuration content is updated check for results/intervals that have not been used/updated for a week. Expire results older than a week if the related scheduled query no longer exists in the schedule.
> [Fix #1694] Expire results for 'old' scheduled queries

- osquery/events/darwin/fsevents.cpp
If an osquery process starts and enables the FSEvents event publisher there should be at least 1 watched path. The alternative involves wait queues waiting for configuration updates. A single path will implement this exact queueing within the run loop for 0 extra code or CPU cost.
We call the `/var/osquery` path an FSEvents canary as it almost always exists, but that is not a requirement. Events occurring within the canary will be silently dropped since there are no matching extensions.
> Add canary path on empty FSEvents subscription set

- osquery/sql/virtual_table.cpp
Conditional logic error was restricting types to TEXT, INTEGERs, and BIGINTs.
> [Fix #1714] Restore balance to the DOUBLE force

- docs/wiki/deployment/configuration.md
- include/osquery/config.h
- include/osquery/packs.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- osquery/config/tests/packs_tests.cpp
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/tables/utility/osquery.cpp
- specs/utility/osquery_packs.table
- tools/tests/test_inline_pack.conf
1. Packs can now include a `"shard"` key that applies Chef-style machine sharding. If a machine's shard (first character of hostname MD5 / 255) is below the required shard, the logic applies. These shards can be applied to the embedded queries within a pack too.
2. Pack discovery checking for version/platform now occurs once. If the platform/version does not apply at a pack level the query addition is skipped.
> [#1636] Add simple sharding to packs and pack queries

- docs/wiki/deployment/file-integrity-monitoring.md
- osquery/config/parsers/file_paths.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/events/process_file_events.cpp
- specs/darwin/process_file_events.table
This extends the config to add `file_accesses`. Adding a list of `file_paths` categories will enable access monitoring for those directories on Linux.
> Reorganize file_events into process_file_events

- include/osquery/hash.h
- osquery/core/hash.cpp
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/forensic/sleuthkit.cpp
- osquery/tables/utility/hash.cpp
This extends the hashing capabilities to add a "multi" file hash. This implementation is the default and accepts a mask of hash types. The speed up reference is opening each file once and performing each requested hashing function on the file contents by block. Previously each file was hashed completely, serially.
> Speed up file hashing

- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/event_utils.cpp
- osquery/tables/events/event_utils.h
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/system/darwin/apps.mm
- osquery/tables/utility/file.cpp
- specs/file_events.table
This adds helpful fields to the `file_events` table that are nice to query at the time of event, rather than a subsequent JOIN at query time.
> Extend fields of file_events

- osquery/tables/system/linux/smbios_tables.cpp
- osquery/tables/system/smbios_utils.cpp
Previously the only SMBIOS/DMI parsing support includes raw (pre/non-EFI). With an EFI boot the DMI structures are moved and the physical address is stored in the firmware sysfs.
> Add support for Linux SMBIOS/DMI EFI structure parsing

- osquery/tables/system/darwin/iokit_registry.cpp
- osquery/tables/system/darwin/smbios_tables.cpp
- osquery/tables/system/linux/smbios_tables.cpp
- osquery/tables/system/smbios_utils.cpp
- osquery/tables/system/smbios_utils.h
- specs/platform_info.table
This is a WIP implementation of the `platform_info` table that reports DMI BIOS information about the platform on Linux and (will) IOKit's platform-related ROM information on Darwin.
> Add platform_info table for UEFI/ROM details

- CMake/FindRocksDB.cmake
- osquery/events/darwin/fsevents.cpp
- osquery/events/events.cpp
- osquery/filesystem/filesystem.cpp
- osquery/tables/events/process_file_events.cpp
- osquery/tables/forensic/sleuthkit.cpp
- osquery/tables/system/linux/os_version.cpp
- osquery/tables/system/linux/processes.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
- tools/provision/fedora.sh
- tools/provision/lib.sh
- tools/tests/asan.supp
- tools/tests/sanitize_blacklist.txt
1. Bump RocksDB to 4.1 for Linux, `brew` will reflect the update too for OS X.
2. Fix an allocation error for sleuthkit-based tables.
3. Update provision for Fedora.
4. The `process_file_events` subscriber would fail without the `kernel` publisher and say "OK".
> Fixes for various build/sanitize/deps nice-to-haves

- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/tests/fsevents_tests.cpp
Reporting FS events from osquery causes duplicate `ATTRIBUTES_MODIFIED` lines when the event handler `stat`s and reads the content for hashing.
Also, removing the defer option increases performance at the cost of lagging events slightly. In our cases this lag will not be noticed as in almost all cases the query schedule is much more request-latent.
> Do not add (self) events for FSEvents

- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/tables/events/linux/file_events.cpp
Using `IN_ALL_EVENTS` and restricting `IN_ACCESS` was a bad plan. Let's explicitly use event type masks for non-access categories.
> [Fix #1735] Limit OPENED and access-related events

- osquery/remote/enroll/enroll.cpp
- osquery/remote/enroll/plugins/tls.cpp
- osquery/remote/utility.h
- tools/tests/test_http_server.py
Using the following flags:
```
--config_plugin=tls
--config_tls_endpoint=/config
--tls_hostname=localhost:9090
--verbose
--disable_logging
--config_tls_refresh=3
--tls_allow_unsafe
--enroll_tls_endpoint=/enroll
--enroll_secret_path=./tools/tests/test_enroll_secret.txt
```
The `test_http_server.py` API strawman will return an "invalid" every 3 requests.
> [Fix #1736] Do not cache TLS node key within enroll plugin

- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/darwin/keychain_utils.cpp
- osquery/tables/system/darwin/tests/certificates_tests.cpp
- specs/darwin/certificates.table
Add `issuer` and `self_signed` columns to OS X's `certificates` table.
> Add certificate issuer and self_signed columns

- include/osquery/events.h
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
When using the shell, multiple selects against an event subscriber that resulted in expired events would result in the second not returning any rows. This happened because post-expiration and event data deletion the first database get for data would fail and incorrectly fail the entire record select.
> Fix double event subscriber select

- include/osquery/database.h
- osquery/database/database.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/scheduler.h
- osquery/logger/logger.cpp
- osquery/logger/plugins/filesystem.cpp
- osquery/logger/plugins/syslog.cpp
- osquery/logger/plugins/tls.cpp
- osquery/logger/tests/logger_tests.cpp
Hopefully this improves logger plugin performance by not requiring another JSON encode within the TLS logger. It should also make the API a bit clearer, `logString` logs a single line of string data, this is an event in most cases. Previously the logger plugin would have to deduce how to split and emit multiple events.
> [#1518] Only emit a single line for each logString

- osquery/filesystem/linux/mem.cpp
- osquery/tables/system/linux/smbios_tables.cpp
- osquery/tables/system/smbios_utils.cpp
When reading from the SMBIOS offset from the systab hint, only discover the tables (ala "_DMI_") once if the memory read succeeds.
> Only discovery SMBIOS tables once on Linux

- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/darwin/keychain_utils.cpp
- specs/darwin/certificates.table
Aside: hopefully the last addition to the certificates table.
The key_size of the public key for RSA, DSA, and EC keys can be listed using the EVP APIs. This is useful for auditing potentially weak key pairs.
> Add key_size to certificates table

- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/keychain_utils.cpp
- specs/darwin/certificates.table
Call `key_size` `key_strength` to support labels for curves for ECC as well as key sizes for RSA/DSA.
> Use key_strength to support ECC

- osquery/tables/system/darwin/signature.mm
Hi,
Simple change - replaced kSecCSStrictValidate vs kSecCSDefaultFlags.
Reason is that strict code signing checks insure that no data is being hidden on a macho/fat file. No increased performance overhead from my testing.
This coincides with my ShmooCon talk next Friday.
http://shmoocon.org/speakers/#hidedata
Let me know if you have any questions.
Thanks!
> Adding strict codesigning checks

- CMake/Packages.cmake
- CMakeLists.txt
- osquery/database/db_handle.h
- tools/provision/debian.sh
1. Add relevant macros to CMake for Debian 7 and 8.
2. Install fpm within the Debian provisioning scripts.
3. Silence intentional override of overloaded method (RocksDB logger facility).
> [Fix #1749] Add support for make packages on Debian

- osquery/CMakeLists.txt
I don't believe there is a hard-and-fast need for cpp-netlib to be linked statically. If the build environment only contains a shared netlib library, then we should use it.
> Require either static/dynamic link of cpp-netlib

- osquery/tables/system/darwin/smc_keys.cpp
- specs/darwin/smc_keys.table
A very similar enumeration and display of Apple's SMC key storage. This data can be used to troubleshoot hardware issues. Anecdotally, I've needed to inspect SMC reporting to track down an infrequent instant-halt caused by applications trying to 'optimize' fan and power settings.
This can also be used to detect SMC 'unlocking' which may be cause for security concerns. An unlocked SMC has had the `KPPW` set to an Apple-hidden secret value, shared among all SMCs. This value has been reverse engineered several times and is more-or-less public. If this value is input then the SMC will allow RAM inspection.
> Add an smc_keys table for OS X

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/parsers/file_paths.cpp
- osquery/config/parsers/tests/file_paths_tests.cpp
- osquery/config/tests/config_tests.cpp
- osquery/config/tests/packs_tests.cpp
- tools/tests/test_inline_pack.conf
- tools/tests/test_parse_items.conf
From some testing I saw that `file_paths` was not recognized when within paths. This was an original design decision that doesn't have to be as limiting now that we manage config state from multiple sources.
The concept is simple! Paths and other things from packs are tracked by their source. For things in the config that do not recognize indexing by an additional pack name, or where something would be over-complicated by an additional 'name' the source becomes the source + DELIMITER + name. When a config source is updated the packs from that source are removed. This triggers a removal of the file paths originally added by the pack.
> Allow packs to add file_path categories

- Makefile
- osquery/events/benchmarks/events_benchmarks.cpp
- osquery/events/kernel/benchmarks/kernel_communication_benchmarks.cpp
- tools/benchmark.sh
- tools/build.sh
- tools/lib.sh
1. Detecting git/bash in the `Makefile` will help identify CMake problems where the version/build info is not formatted well.
2. Unifying the build logic for build/test and benchmarking should help preventing breakage of less-watched build paths. Previously the nightly benchmark generation was failing due to exceptions in the benchmark code and regressions in the build flow.
> Unify build script and fix EVENTS benchmarks

- CMakeLists.txt
- README.md
- osquery/CMakeLists.txt
- tools/deployment/make_linux_package.sh
- tools/deployment/osqueryd.service
- tools/deployment/osqueryd.sysconfig
1. We do not produce packages for RHEL and our subscriptions are expiring. Unless someone shows renewed interest, let's punt on restarting those since they are a royal PITA.
2. The SQLite code has annoying uninitialized constants. A part of me dies when I see these warnings, so I'm squashing them and limiting `-Wall -Wextra` to only osquery code.
3. CentOS7 users have asked for a systemd service. CentOS 7 package builds will now include such a service and it will up to the administrator to enable/start the service.
> Remove RHEL builds, silence SQLite warnings, add systemd

- osquery/database/db_handle.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/logger/plugins/tls.cpp
- tools/profile.py
This minimizes the max memory needed for TLS loggers. When the logger thread wake up it will discover the log items in RocksDB. Those will be constructed into a property tree and passed to the remote API's serializer/deserializer. This adds a spurious JSON encode/decode step. We should try to avoid keeping multiple copies of this content in memory simultaneously.
> Improve TLS logging memory

- Makefile
- osquery/sql/virtual_table.cpp
- tools/tests/test_osqueryd.py
- tools/tests/test_osqueryi.py
This will effect those to develop or perform custom builds for OS X on 10.10 and 10.11!
| Version | Current Target  | New Target | 
| --- | --- | --- |
| 10.10 | `./build/darwin/osquery` | `./build/darwin10.10/osquery` |
| 10.11 | `./build/darwin10.11/osquery` | `./build/darwin/osquery` |
This change will cause the package-related jobs to use the 10.11 build as the distribution build.
> Promote 10.11 to default darwin package builder

- osquery/tables/system/darwin/disk_encryption.cpp
- specs/disk_encryption.table
From the discussion in #1752, this adds currently authenticated FileVault user to `disk_encryption` table on Darwin.
```
osquery> select de.name, de.encrypted, de.type, de.uid, users.shell
...> from disk_encryption as de join users
...> where de.uid == users.uid;
+------------+-----------+---------+-----+--------------------+
| name       | encrypted | type    | uid | shell              |
+------------+-----------+---------+-----+--------------------+
| /dev/disk1 | 1         | AES-XTS | 501 | /usr/local/bin/zsh |
+------------+-----------+---------+-----+--------------------+
```
> Add currently authenticated FileVault user

- osquery/logger/plugins/tls.cpp
- tools/tests/test_osqueryd.py
- tools/tests/test_osqueryi.py
The previous change in https://github.com/facebook/osquery/pull/1771 introduced a regression by not deserializing the string JSON into a property tree.
> [Fix #1788] Use an array for the 'data' key in TLS logs

- CONTRIBUTING.md
- docs/wiki/installation/cli-flags.md
- kernel/CMakeLists.txt
- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
- tools/deployment/osqueryd.service
1. Update contributing with examples on rebasing/squashing.
2. Add some missing CLI flags to the wiki.
3. Add the OS X version to the kernel extension package. To be safe from a feature-enablement perspective, encourage folks to use the package version corresponding to their OS. In practice the worst that has been observed is losing feature capability (e.g., no more MAC auth).
4. Include the systemd service for RHEL7 systems too.
> Rollup of several docs and build fixes.

- osquery/tables/system/darwin/smbios_tables.cpp
- osquery/tables/system/darwin/smbios_utils.h
- osquery/tables/system/darwin/system_info.cpp
- osquery/tables/system/linux/smbios_tables.cpp
- osquery/tables/system/linux/smbios_utils.h
- osquery/tables/system/linux/system_info.cpp
- osquery/tables/system/smbios_utils.cpp
- osquery/tables/system/smbios_utils.h
- specs/system_info.table
This fills in the missing `hardware_` fields in `system_info` on Linux and adds two additional fields for both Linux and Darwin: `hardware_vendor` and `hardware_version`. These are backed by the SMBIOS/DMI System Info type (pretty appropriate).
> [#1778] Add hardware/board info for Linux

- docs/wiki/development/building.md
- tools/build.sh
- tools/lib.sh
- tools/provision.sh
This implements part 1 of #1742.
The package and release checks are mostly dependent on the build environment. The relative environments are hosted in an isolated infrastructure that is not subject to PR trashing. It is fine if these checks are run 'nightly' or out of band with PRs, which often benefit from synchronous responses. As we grow the build and the number of platforms each PR runs on we must balance the runtime for each and the global strain each build has on the MacMini cluster.
This also removes `make deps` from the build. If developers are adding to the provision script we will need another method of triggering a specialized build that exports the associated variable to install the dependencies alongside the PR. This will be done within Jenkins and a development team member …
> [#1742] Remove deps and release from PR builds

- include/osquery/database.h
- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/database/database.cpp
- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- osquery/database/tests/database_tests.cpp
- osquery/database/tests/db_handle_tests.cpp
- osquery/distributed/tests/distributed_tests.cpp
- osquery/logger/CMakeLists.txt
- osquery/logger/plugins/tests/tls_logger_tests.cpp
- osquery/logger/plugins/tls.cpp
- osquery/logger/plugins/tls.h
This is a rather large update to the performance improvements needed for TLS logging. This also adds the much-needed set of tested for the logger plugins and TLS log forwarder. 
There are some additional tests for the database APIs as the `Scan` methods were extended to include an optional `max` argument to allow the caller an incremental scan. In the case of log buffering, a noisy set of queries may emit "too many" logs in the sense that when they are drained or forwarded, they overflow the downstream byte limit. With TLS logging this is a very practical possibility where HTTPS servers implement a max request size.
> Improve TLS logger performance

- osquery/tables/system/darwin/disk_encryption.cpp
1. Create a copy of UUID data so that we have the value instead of its reference before we release the properties.
> Fix potential crash in disk_encryption

- docs/wiki/deployment/remote.md
- docs/wiki/installation/cli-flags.md
- osquery/logger/plugins/tls.cpp
- osquery/remote/CMakeLists.txt
- osquery/remote/remote.cpp
- osquery/remote/requests.h
- osquery/remote/tests/requests_tests.cpp
- osquery/remote/transports/tls.cpp
1. Document the 10.11 limitation/requirement for `--tls_server_certs` when using packages built using the static LibreSSL.
2. Document the optional `--logger_tls_max` for limited the max size of each transmitted log line [#1793].
3. Add helpful remote status messages to the TLSLogger verbose message logs. This helps when debugging TLS/server failures.
4. Add optional support for compression (GZIP) of POST request content.
> Add and document TLS debug features

- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
Remove the silly heuristic-based attempt to determine what constraint set would be used. Instead us the deterministic approach of correlating `idx`.
> Reduce complexity of SQLite constraints tracking

- Makefile
- docs/wiki/development/building.md
For Vagrant targets, the `make deps` provisioning scripts will install `git`. A check for `git` is only needed when executing CMake proxy targets.
> [1576] Gate Makefile check for git to non-deps targets

- docs/wiki/installation/cli-flags.md
- include/osquery/events.h
- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/sql/virtual_table.cpp
This adds a new CLI flag: `--events_max` that assists subscriber tables from buffering an excess number of events in RocksDB. The max value will be applied regularly when events are added to the backing store, while they wait for a query to select results. If the maximum number of events occurs within a scheduled period, events will drop.
In practice, dropped events never occur. This assist is focused on draining buffers that have no scheduled query.
> Add an events_max limit for event buffering

- docs/wiki/deployment/remote.md
- docs/wiki/development/pubsub-framework.md
- osquery/logger/plugins/filesystem.cpp
1. Remove references to the `passwd_changes` table.
2. Add a reference to the expected enrollment experience when using TLS client-auth.
> Documentation updates for TLS client-auth and FIM

- packs/vuln-management.conf
See https://vulnsec.com/2016/osx-apps-vulnerabilities/ for context. This will return all non-`https` update feed endpoints.
> Add unauthenticated sparkle feeds query to vuln-mgmt pack

- Makefile
- osquery/events/events.cpp
- osquery/main/lib.cpp
- tools/deployment/make_osx_package.sh
Publishers/subscriptions failing their initialization is normal for kernel-based publishers. This is also assumed normal if there are no subscriptions needed. Later during runtime, after a reconfiguration, the publishers/subscribers *could* be started/stopped.
This also adds helpful macros for building debug packages on OS X.
> Minor de-prioritization of failed publisher logging

- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/filesystem/filesystem.cpp
1. The `forensic`  capability on Linux to preserve `atime` between hashing has an adverse effect of causing additional inotify events. We should opt for variable `atimes` over variable `ctimes` as the access event for hashing is gated to an explicit opt-in.
2. The daemon will create duplicate `file_events` if it is torn-down before an expiration event occurs. This adds a persistent `optimize` key to RocksDB to restore optimization times, which is the default.
> [Fix #1814] Various fixes for Linux inotify

- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/tables/events/event_utils.cpp
- osquery/tables/events/event_utils.h
- osquery/tables/events/linux/file_events.cpp
If you stat an access-based event you will generate a secondary access event. This is bad. ;)
> [#1814] Do not stat inotify access subscriptions

- osquery/tables/system/darwin/smc_keys.cpp
- specs/darwin/temperatures.table
A few OCD changes to the `temps` table to make it JOINable with `smc_keys`. The first change is a conditional allowing constraint searching instead of needing a full scan for each join. The second is a few renames within the spec:
`temps` -> `temperatures`
`smc_key` -> `key`
The rename of `smc_key` should help to make the table spec platform agnostic.
> Rename 'temps' temperatures, add constraints

- osquery/tables/applications/darwin/browser_plugins.cpp
- specs/darwin/safari_extensions.table
This was missed from the original `safari_extensions` refactor since it is an optional key.
> [Fix #1418] Add developer_id to safari_extensions

- osquery/tables/system/darwin/smc_keys.cpp
Restrict getTemperatures() to smc temperature keys.
I might be overlooking something. Right now it's functionally equivalent since there's a one to one mapping between kSMCKeyDescriptions.keys() and kSMCTemperatureKeys, but shouldn't it be restricted to kSMCTemperatureKeys?
> restrict getTemperatures to smc temp keys

- osquery/core/init.cpp
If you're running as a user without a home, or with a restricted home (one you cannot create a `.osquery` within) osquery will exit. It does not need to stop, a user should be able to run most queries in a restricted setup.
> Handle restricted home directories

- include/osquery/core.h
- include/osquery/events.h
- osquery/config/config.cpp
- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/devtools/shell.cpp
- osquery/dispatcher/dispatcher.h
- osquery/events/events.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
- osquery/main/shell.cpp
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/sqlite_util_tests.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- tools/tests/sanitize_blacklist.txt
- tools/tests/test_base.py
- tools/tests/test_osqueryi.py
This is a refactor of shutdown, dispatcher, and event factory concurrency logic. The results here are an attempt to minimize the number of critical sections identified by LLVM's thread sanitization.
> Refactor dispatcher shutdown logic

- CMake/FindThrift.cmake
- CMakeLists.txt
It is no longer feasible to run with thrift versions less than 0.9.3, see #1830. Let's stop people from building if CMake can detect the thrift version.
> Require Thrift 0.9.3

- osquery/tables/system/darwin/smc_keys.cpp
Lumping parsing of smc fpe2 values in with the else case, which is also
used for parsing sp78 values, seems to have it show correct values that
match those outputted by `./smc -l | grep -i fpe2` via the smc-fuzzer
tool.
resolves #1822
> [Fix #1822] adjust smc parsing fpe2 values

- osquery/devtools/shell.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/virtual_table.cpp
- tools/tests/test_osqueryi.py
A recent regression prevented transient connections to the DB. This fixes the bug, allowing multiple DB connections (using distinct DBs/virtual table modules) and improves the speed of `-A` or `.all` shell meta commands. The `do_meta_command` command switch does not need to hold a lock for the database. It does so to help future commands, assuming they'll want to change options/modes for the database. There is one custom-command that trampolines into `shell_exec` (the all command) and this should run before the secondary lock is needed.
> Fix -A/.all contention via do_meta_command

- include/osquery/config.h
- include/osquery/packs.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- osquery/config/tests/packs_tests.cpp
- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/tables/utility/osquery.cpp
- tools/tests/test_inline_pack.conf
1. Record the success of pack instantiation. Validity means acceptable shard, version, and platform. If a pack is valid then discovery queries will determine appropriateness. Previously, packs did not record valid state but would fail to append to the schedule. For other (non-schedule) uses of packs this leads to undefined behavior and confusion.
2. Packs should be treated as non-copyable. There is a simple refactor here that moves pack storage into shared pointers. Pack use/scoping should still be confined to the `Config` and subsequent `Schedule` instance.
> Valid bool in packs for shard/plaform/version checking

- include/osquery/core.h
- include/osquery/registry.h
- include/osquery/tables.h
- osquery/core/flags.cpp
- osquery/core/init.cpp
- osquery/extensions/extensions.cpp
- osquery/main/shell.cpp
- osquery/registry/registry.cpp
- osquery/tables/utility/osquery.cpp
The osquery shell can autoload extensions. The only difference between the daemon and the shell, with respect to extensions autoloading, is the daemon expects to fork a worker process and continue only as a watch dog (a loop to check sanity of a single worker). If the shell implicitly disable watchdog features it can offer the same extension loading and monitoring as the daemon.
> [#1810] Allow extensions autoloading in osqueryi

- osquery/tables/system/darwin/disk_encryption.cpp
- osquery/tables/system/darwin/user_groups.mm
- specs/block_devices.table
- specs/disk_encryption.table
- specs/users.table
This change adds:
* `uuid` column to `users` table:
According to Apple's docs: the UUID may be a synthesized UUID (i.e. system accounts) with the prefix `FFFFEEEE-DDDD-CCCC-BBBB-AAAAxxxxxxxx`, where `xxxxxxxx` is a hex conversion of the UID
I did not notice a change in query times, but if we want to optimize further we can restrict user's UUID reporting to non-system accounts in the future.
* `user_uuid` column to `disk_encryption` table
```
osquery> select de.name, de.encrypted, de.uid, de.user_uuid, users.shell
...> from disk_encryption as de join users
...> where de.uid == users.uid and de.user_uuid == users.uuid;
+------------+-----------+-----+--------------------------------------+--------------------+
| name       | encrypted | uid | user_uuid                            | shell …
```
> [#1800] Add UUID to users and disk_encryption on Darwin

- include/osquery/config.h
- include/osquery/events.h
- include/osquery/registry.h
- osquery/config/config.cpp
- osquery/config/tests/config_tests.cpp
- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/events/tests/events_tests.cpp
- osquery/registry/registry.cpp
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/events/process_file_events.cpp
- osquery/tables/events/tests/file_events_tests.cpp
- osquery/tables/events/yara_events.cpp
- tools/tests/test_noninline_packs.conf
This is a bit of clean and some additional testing around the `file_events` lifecycle. This goes from configuration to registry to event factory to the related publishers and finally adds a new small set of tests around the "user"-facing `file_events` API (so to speak).
We make sure of a meta-table that reports details about the pubsub system. While this does not report on the publisher internal details, it reports on the data that publishers use during `configure`.
> Cleanup/stabilize file_events-related APIs

- osquery/devtools/shell.cpp
Pretty simple, CTRL+C should exit the shell immediately #1783.
> Exit shell with CTRL+C

- include/osquery/distributed.h
- osquery/dispatcher/distributed.cpp
A small refactor to prevent the publish SDK from depending on inline-included headers.
> [Fix #1828] Remove inline include from distributed

- CMakeLists.txt
1. Correctly set the CMake variables, so that it gets evaluated to the environment variable and not the literal `ENV{VAR}`
> Fix setting CMake variables to the environment variables.

- osquery/tables/system/darwin/smc_keys.cpp
- osquery/tables/system/darwin/tests/smc_tests.cpp
- specs/darwin/fan_speed_sensors.table
- specs/darwin/power_sensors.table
- specs/darwin/sensor_currents.table
- specs/darwin/sensor_powers.table
- specs/darwin/sensor_voltages.table
- specs/darwin/signature.table
- specs/darwin/temperature_sensors.table
1. Rename `sensor_temperatures` -> `temperature_sensors`, `sensor_powers` -> `power_sensors`, and `sensor_fan_speeds` -> `fan_speed_sensors`.
2. Remove `sensor_currents` and `sensor_voltages`, and replicate their data within `sensor_powers`.
3. Add a `category` to `power_sensors` (the new mega-power-related sensors table) indicating what "type" of sensor this key/value reports.
4. Create some inline predicate parsing to minimize duplicate code.
> [Fix #1854] Unify power sensor tables

- osquery/logger/logger.cpp
- osquery/logger/plugins/filesystem.cpp
Add a newline to snapshot and health filesystem writes.
Previously, **only** the `logString` interface for the Filesystem logger plugin was "re" appending a newline. This is a bug, writes to files should always include a newline.
> [Fix #1861] Add newline to all filesystem logger writes

- include/osquery/logger.h
- osquery/logger/CMakeLists.txt
- osquery/logger/logger.cpp
- osquery/logger/plugins/filesystem.cpp
- osquery/logger/plugins/syslog.cpp
- osquery/logger/plugins/tests/filesystem_logger_tests.cpp
- osquery/logger/plugins/tls.h
- osquery/logger/tests/logger_tests.cpp
As a follow up to #1861, let's add some tests specific to the Filesystem logger plugin. These tests make sure the log lines emitted to disk are sane: for the string/result logs we expect 1 per line; for the snapshot queries, which are essentially only a different file sink, we expect the same.
> Improve logging tests, add filesystem logger tests

- osquery/config/parsers/options.cpp
Check if a provided config options has a defined type. If no type has been recorded then this option is considered unknown.
> [Fix #1866] Emit warning log with unknown options

- tools/deployment/osqueryd.initd
The LSB init syntax is different than chkconfig, this was breaking Debian installation.
> Update initd script to respect LSB values

- include/osquery/tables.h
- osquery/devtools/shell.cpp
- osquery/main/shell.cpp
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/sql.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/sql_tests.cpp
- osquery/sql/tests/sqlite_util_tests.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
This begins to refactor the use of a `DBInstance` management/contention checking abstraction into something that can communicate from within the SQLite table implementations back to the callsite. As long as the callsite does not "lose control" [1] of the database, it is possible to receive information back from the execution and decisions made within the SQLite module/virtual table code.
[1] The shell does this, but it's somewhat outside of the control of the osquery codebase.
> [#1816] Refactor DB instance management

- packs/osx-attacks.conf
Detect persistency binary from hacking team (ref: https://reverse.put.as/2016/02/29/the-italian-morons-are-back-what-are-they-up-to-this-time/)
> Added new detection for hacking team

- osquery/sql/virtual_table.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
Prevent regressions with SQLite optimizer output.
> Add high level join tests for processes, file, and hash

- CMake/Packages.cmake
- osquery/tables/CMakeLists.txt
- tools/provision.sh
- tools/provision/centos.sh
- tools/provision/fedora.sh
- tools/provision/lib.sh
- tools/provision/oracle.sh
- tools/provision/rhel.sh
libdevmapper's ABI changes too rapidly, and the updates repo is not maintaining older packages. CentOS / RHEL / and other RH-based systems will now build and link devmapper statically.
> [Fix #1892] Build devmapper statically

- CMakeLists.txt
- Makefile
- docs/wiki/development/building.md
- osquery/devtools/shell.cpp
This is handy when debugging complex SQL queries when results are unexpected.
To build with the two SQLite-specific defines the entire project will be recompiled/relinked. There is a better way to stack these defines, but since we build SQLite as a third-party isolated CMake project, the defines should be at the top-level. Since this type of debugging is very rare it's not worth the reorganization effort.
> Add define to enable SQLite WHERETRACE

- packs/osx-attacks.conf
Adding detection for OSX malware/ransomware Keranger. Related: https://forum.transmissionbt.com/viewtopic.php?f=4&t=17834
http://researchcenter.paloaltonetworks.com/2016/03/new-os-x-ransomware-keranger-infected-transmission-bittorrent-client-installer/
> Adding detectiong for OSX Keranger

- packs/osx-attacks.conf
Query uses `OR` and this will be supported in the next release (with SQLite 3.12.0). For reference:
#1898 and https://github.com/facebook/osquery/commit/6afd1a29cf849e4e2d91831dcb3af5beea5dce29
> OSX Keranger detection fix

- osquery/tables/system/linux/cpu_time.cpp
- specs/linux/cpu_time.table
Implemented table for seeing where every cpu core spent time since the system was started. Information is taken from /proc/stat . Adapted the original spec file from @xavinux a little to arrive at the the current spec file.
> Cpu time table implementation (solves #1889)

- osquery/examples/example_extension.cpp
- osquery/extensions/interface.cpp
- tools/tests/test_extensions.py
This added test ensures extension processes can set/get database values.
> Allow extensions to use the backing store

- osquery/devtools/printer.cpp
- osquery/devtools/shell.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/processes.cpp
There is somewhat of a breaking change here:
- Previously `INTEGER`, `BIGINT`, and `DOUBLE` typed columns would emit a `-1` if the content could not be safely parsed into the corresponding literal type. This was bad form as some column use `-1` as an expected result-- and all of the literal types are signed.
- There are several conversions / helper methods like `--json` that assume a value for each column.
- `NULL` values within the shell's default output mode: `pretty` will respect the `--nullvalue` SQLite shell CLI switch.
- `--nullvalue` is NOT available for the `osqueryd` so expect null content to result in missing column fields. **This will result in errant/spurious differential results as we are implicitly changing expectations of output fields.**
> Allow NULL values, stop using -1 as int/double invalid values

- osquery/tables/system/darwin/processes.cpp
Process states in `processes` table now use mnemonics instead of the integer code. They follow closely to the states defined `sys/proc.h`, which means processes with state as:
```
state    value   meaning                           mnemonic
-------- ------- --------------------------------- ----------
SIDL     1       process being created by fork     'I'
SRUN     2       currently runnable                'R'
SSLEEP   3       sleeping on an address            'S'
SSTOP    4       process debugging or suspension   'T'
SZOMB    5       awaiting collection by parent     'Z'
```
Note: The mnemonics here will not match up with what `ps` or `top` reports.
`ps` and `top` queries run state of all Mach Threads (by grabbing a Mach Task)<sup>1</sup> of a process, and then coalesces it to represent …
> [#1886] Use mnemonics for process states on Darwin

- osquery/tables/CMakeLists.txt
- tools/provision/amazon.sh
- tools/provision/centos.sh
- tools/provision/darwin.sh
- tools/provision/debian.sh
- tools/provision/fedora.sh
- tools/provision/lib.sh
- tools/provision/oracle.sh
- tools/provision/rhel.sh
- tools/provision/ubuntu.sh
1. Update boost to 1.60 from 1.55 on Linux platforms
2. Add asio (1.11.0) to the deps set
3. Update snappy to 1.1.3 on Linux platforms
4. Update cpp-netlib to 0.12.0-rc1 from 0.11 on Linux platforms
- OS X and brew also include 0.12.0-rc1 as a devel option
5. Update libapt to 1.2.6 from 0.8.6 on Ubuntu/Debian
- This adds lzma as a dependent link
6. Upgrade RocksDB to 4.4 from 4.1
> Several package updates within provision code

- include/osquery/events.h
- osquery/config/plugins/tls.cpp
- osquery/core/watcher.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/dispatcher.h
- osquery/dispatcher/distributed.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/scheduler.h
- osquery/dispatcher/tests/dispatcher_tests.cpp
- osquery/events/darwin/diskarbitration.cpp
- osquery/events/darwin/diskarbitration.h
- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/iokit.cpp
- osquery/events/darwin/iokit.h
- osquery/events/darwin/scnetwork.cpp
- osquery/events/darwin/scnetwork.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/events/kernel/tests/kernel_communication_tests.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.h
- osquery/logger/plugins/tls.cpp
- osquery/registry/registry.cpp
- tools/tests/sanitize_blacklist.txt
Prevent `std::~thread` from calling `::terminate` on the thread context after we cancel and join using the native handle.
> [Fix #1920] Detach thread before joining/clearing (terminate)

- osquery/tables/system/darwin/asl.cpp
- osquery/tables/system/darwin/asl_utils.cpp
- osquery/tables/system/darwin/asl_utils.h
- osquery/tables/system/darwin/tests/asl_tests.cpp
- specs/darwin/asl.table
This table allows querying agains the Apple System Log (ASL) data store.
It can efficiently query on exact matches, but using `like` can be pretty slow. I am including results of perf testing below. For reference, my 2 month old machine had only about 18,000 logs in the store. A different test machine had about 500,000 lines of log spam. The following results are with ~350,000 logs inserted into the store on my machine.
```
$ python ./tools/profile.py --leaks --config osquery.conf
Analyzing leaks in query: select count(*) from asl;
definitely: 0 leaks for 0 total leaked bytes.
Analyzing leaks in query: select * from asl where Facility = 'com.apple.console';
definitely: 0 leaks for 0 total leaked bytes.
Analyzing leaks in query: select * from asl where Facility = 'com.apple.console' and …
```
> Apple System Log Virtual Table Implementation

- osquery/tables/system/darwin/signature.mm
- specs/darwin/signature.table
I am adding three new fields to the signature table so we can have more info. Here is the breakdown:
- `cdhash` - code directory hash
(Ref: [Code Signing Requirement Language](https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/RequirementLang/RequirementLang.html))
- `team_identifier` - an unique id of the app developer (osx 10.10 or later) 
- `authority` - the common name of the signed certificate
> Upgrade signature table

- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/events/CMakeLists.txt
- tools/deployment/getfiles.py
- tools/deployment/make_linux_package.sh
- tools/provision/centos.sh
- tools/provision/lib.sh
- tools/provision/rhel.sh
This fixes a build issue for CentOS7 where devmapper's pkgconfig was not installed. This would fail the cryptsetup build during `make deps`. This also attempts a poor man's `-debuginfo` package build for CentOS7/Ubuntu.
> Build debug packages

- osquery/events/darwin/iokit.h
As with all other appearances of IOKitLib.h in the osquery sources, use
the capitalization "IOKitLib.h" not "IOKitlib.h" to avoid build failure
on case-sensitive file systems.
> IOKitLib.h not IOKitlib.h

- .clang-format
This fixes issue #1934, and potentially other C++11 compatibility.
On a couple of test files, this change did not seem to change the formatting (besides fixing the problem of #1934).
Files tested:
```
include/osquery/events.h
osquery/events/linux/inotify.cpp
osquery/events/linux/inotify.h
osquery/events/linux/tests/audit_tests.cpp
```
> Change .clang-format standard from Cpp03 to Cpp11

- include/osquery/events.h
- osquery/CMakeLists.txt
- osquery/core/watcher.cpp
- osquery/events/events.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- tools/deployment/make_linux_package.sh
1. Add a catch-all cleanup for events expiration when the daemon/shell starts. This should only affect processes that stop with too many buffered events.
2. Add a friendly note in the CMake output indicating the expected directory of the output shell/daemon binary.
3. Add appropriate warning logs when extensions/modules cannot load.
4. Fix CentOS 6.5 debuginfo package building.
5. Remove "unneeded" Thrift transport interruptions (for the extensions server/clients).
> Various cleanups

- osquery/config/plugins/tls.cpp
This might be related to #1941, but in all cases an interrupt should not allow logic within a service thread to continue.
> Check for interrupt requests in TLS config refresher

- osquery/events/darwin/diskarbitration.cpp
- osquery/events/darwin/diskarbitration.h
- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/iokit.cpp
- osquery/events/darwin/iokit.h
- osquery/events/darwin/scnetwork.cpp
- osquery/events/darwin/scnetwork.h
- osquery/events/darwin/tests/fsevents_tests.cpp
Add some consistency to the resource locking and start/configure/restart workflow in OS X's event publishers. We should create a RunLoop-based publisher wrapper the abstracts some of the actions to protect against critical sections with respect to starting the publisher and arbitrarily requesting stoppage or reconfigurations (caused by configuration updates).
> Enhance publisher resource locking on OS X

- README.md
It doesn't make sense to assume someone new to the project is going to click the Slack badge. Let's add the auto-invite Heroku app link as the 'Slack' link.
> Update Slack link in README

- osquery/tables/system/darwin/signature.mm
- osquery/tables/system/darwin/tests/signature_tests.mm
1. Before we cannot query multiple rows. We cannot use `LIKE` statement. This commit adds the ability to query multiple signatures, like:
`osquery> select * from signature where path like "/Applications/G%";`
NOTE: Query all applications at once, e.g. `/Applications/%`, is a little slow. 
2. Before if an app is not validated, it doesn't extract extra info (cdhash, team id, etc), Now, we will try to extract those fields even if the app is not validated as long as it has a signature.
> add feature to select multiple rows to signature table

- include/osquery/registry.h
- osquery/core/init.cpp
- osquery/devtools/shell.cpp
- osquery/dispatcher/dispatcher.cpp
- osquery/extensions/extensions.cpp
- osquery/main/shell.cpp
- osquery/registry/registry.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
A few of the refactors around database access have left the shell's `--profile` features in a bad state. Current `--profile` on any table implementation requiring database access will SIGSEG the shell.
This PR also fixes some TSAN issues with the shell and the managed/concurrent DB access. When the shell is used with extensions, some of the more-or-less opaque implementation borrowed from the SQLite shell remained unprotected.
> Fix shell's --profile switch

- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/dispatcher.h
- osquery/events/linux/udev.cpp
- osquery/events/linux/udev.h
This actually hardens both the platform and specifically the UDEV publisher from fast terminations. There are several tests that stress the speed at which osquery may be interrupted. If interrupted too quickly the `Dispatcher` facilities may cause an ABRT hang (for several additional seconds) as services can be added to the monitor AFTER a stop/interruption event is requested. This causes the main thread to join services that will never be interrupted.
> Protect udev publisher from fast interrupts

- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/linux/processes.cpp
- specs/processes.table
`group` is a reserved term in SQLite, explicitly selecting or including this column in a predicate has confusing usage requirements. If we use `pgroup` then there's no need to name-escape the column.
> [Fix #1878] Rename processes 'group' to 'pgroup'

- include/osquery/dispatcher.h
- include/osquery/events.h
- osquery/config/plugins/tls.cpp
- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/distributed.h
- osquery/dispatcher/scheduler.h
- osquery/dispatcher/tests/dispatcher_tests.cpp
- osquery/events/events.cpp
- osquery/events/kernel/benchmarks/kernel_communication_benchmarks.cpp
- osquery/events/kernel/tests/kernel_communication_tests.cpp
- osquery/events/linux/audit.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/udev.cpp
- osquery/extensions/interface.h
- osquery/logger/plugins/tls.h
By breaking the "interruptable" portion of internal runnables into its own set of traits, we can reuse the fast-interruption within event publishers. This results in faster tear down for the publishers on Linux. There is repeated code within the event publisher implementation and internal runnables w.r.t. start and stop state which can be removed (or unified) later.
> Move dispatcher to public API

- osquery/tables/events/yara_events.cpp
On OS X and Linux, moving a file monitored by FIM (non-accesses) will potentially trigger a YARA scan if the category applies.
> Add move events to yara_events

- tools/deployment/com.facebook.osqueryd.plist
When I added the flag file switch it was aimed at `/var/osquery`, but the package is built such that everything exists in `/private/var/osquery`. This simply makes this more consistent.
> Inconsistant Pathing for Flags File

- tools/deployment/osqueryd.service
Basically you're not supposed to daemonize with systemd, ever. Type=forking is meant as a backwards compatibility thing for services that can't not daemonize, but it's unreliable and you end up not supervising the process correctly, which leads to issues like systemd thinking you're dead when you're not and restarting, or osquery dying and systemd not noticing and not restarting it.
> systemd properly supervised

- osquery/config/config.cpp
Configuration data is accessed via several `Config::` methods that apply a lambda to the private data, typically by iterating and applying each item in the container to the lambda. These operations could be chained within the schedule executor. We must use a recursive lock guard to avoid a dead lock.
> [Fix #1971] Use recursive locks for config data predicates

- osquery/core/watcher.cpp
- osquery/logger/logger.cpp
- osquery/logger/tests/logger_tests.cpp
1. Only attempt to relay status logs if the process is a watcher. The responsible thread is overloaded to also monitor autoloaded extensions.
2. Only re-enable buffering of status logs if the sink was enabled before the disabler (odd-style of log lock) was requested.
3. Fail fast for the logging methods if logging is disabled. This will prevent weird error messages when a plugin cannot be found, as in most cases the logging disabling is *very* much related.
> [Fix #1973] Improve logging/extensions relays

- osquery/distributed/distributed.cpp
- osquery/distributed/tests/distributed_tests.cpp
If the distributed plugin's `writeResults` method can be successfully
called, we must clear the local vector of results so that we're not
constantly growing it over time.
> [Fix #1962] Clear cache of distributed query results after flush

- osquery/tables/applications/darwin/browser_plugins.cpp
- specs/darwin/browser_plugins.table
Changed the browser_plugins table to iterate through the Disabled folder, so that the disabled folder is no longer treated like a plugin.  Additionally added a 'disabled' flag to the table which correlates with plugins living in the disabled folder.
> Treating the disabled plugins as a folder

- CONTRIBUTING.md
The Open Code of Conduct is no longer maintained or supported. Many
other projects have found success with Contributor Covenant and it's
quickly becoming a standard. This PR migrates osquery's code of conduct
to use Contributor Covenant.
> Migrate from Open Code of Conduct to Contributor Covenant

- CMake/Packages.cmake
- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/tables/system/centos/rpm_packages.cpp
- osquery/tables/system/linux/disk_encryption.cpp
- tools/lib.sh
- tools/provision.sh
- tools/provision/files/scientific6.devtoolset.repo
- tools/provision/scientific.sh
Scientific Linux is a derivative of RHEL, and is very similar to CentOS. I added the appropriate provision script, based on the CentOS provision script, to allow for building on Scientific Linux. The main difference between the two is that it uses SL's devtools repository instead of the CentOS one, primarily so that the package signature verification works properly.
> Add build support for Scientific Linux

- docs/wiki/deployment/configuration.md
- include/osquery/config.h
- include/osquery/database.h
- osquery/config/parsers/decorators.cpp
- osquery/config/parsers/decorators.h
- osquery/config/parsers/tests/decorators_tests.cpp
- osquery/database/database.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/logger/plugins/tls.cpp
- tools/tests/test_parse_items.conf
New feature! `decorator` queries: a way to enhance result logs with data from queries.
If you want to add things like: 
- the osquery version
- the last logged in user
- the last executed process
- the hostname (if you're using `--host_identifier=uuid`)
- the hostuuid (if you're NOT using `--host_identifier=uuid`)
You can define decorators according to the new "config specification" guide in the wiki.
> Introduce decorator queries

- include/osquery/dispatcher.h
- osquery/dispatcher/dispatcher.cpp
These APIs using std::chrono::duration allow us to take advantage of
automatic time conversion and type safety among different units of time.
No changes were made to existing call sites.
> Add type safe dispatcher pause APIs

- osquery/tables/system/shell_history.cpp
- specs/shell_history.table
Bash can be configured to include timestamps in the bash_history file. If enabled, the resulting history file would look something like this:
```
#1459654091
ls
#1459654139
pwd
#1459654234
echo "hello world"
```
The timestamp, if present, would be in Unix time format preceded by a # character on the line above the command that it applies to. A simple way to enable this is to run `export HISTTIMEFORMAT="%F %T"`.
If available, this information is very useful to have. The shell_history table currently considers these timestamp lines to be commands, which gets annoying with this configured across a large fleet. This change checks for this timestamp and adds it to a new "time" column if present.
```
osquery> select time, command from shell_history;
+------------+--------------------+
| time …
```
> Add time column to shell_history table

- packs/osx-attacks.conf
See: https://threatpost.com/mac-adware-osx-pirrit-unleashes-ad-overload-for-now/117273/
Someone also wrote a removal script for it:
https://github.com/aserper/osx.pirrit_removal/blob/master/remove_pirrit.sh
> Add detection for OSX Pirrit

- CMake/CMakeLibs.cmake
- osquery/CMakeLists.txt
- osquery/sql/virtual_table.cpp
- tools/codegen/amalgamate.py
- tools/codegen/gentable.py
- tools/codegen/templates/amalgamation.cpp.in
- tools/codegen/templates/foreign.cpp.in
This adds all table specs to all osquery binaries, regardless of platform. This allows for an opaque `--enable_foriegn` switch to start the binary with the foreign specs, which have no backing implementation. These tables will appear as virtual tables but will never return row data.
> [Fix #2030] Add generate_foreign and --enable_foreign

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/parsers/decorators.cpp
- osquery/config/parsers/tests/decorators_tests.cpp
- osquery/config/parsers/tests/events_tests.cpp
- osquery/config/parsers/tests/file_paths_tests.cpp
- osquery/config/parsers/tests/options_tests.cpp
- osquery/config/tests/packs_tests.cpp
- osquery/dispatcher/tests/scheduler_tests.cpp
There are several tests that introduce confounds because they do not clear configuration state.
These changes mostly affect tests since the `Config::reset` method is not used during normal flow. This method was intended to restore a blank configuration state before/after a series of tests. It had two problems:
- It wasn't used in several test sets that explicitly changed configuration data.
- The reset did not extend into configuration parser state.
> Reset configuration state in relative tests

- osquery/tables/system/darwin/crash_logs.cpp
- specs/darwin/crash_logs.table
Added a table that parses out some of the informaiton in the OS X logs
stored in /Library/Logs/DiagnosticReports as well as
/Users/<user>/Library/Logs/DiagnosticReports
> Adding Crash Logs table for OS X

- osquery/tables/system/linux/cpu_time.cpp
We assume the first word starts with 'cpu' and we split the string and get the cpu id. 
This should address #2025
> fix the cpu id displayed in core column

- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/launchd.cpp
- osquery/tables/system/darwin/preferences.cpp
- osquery/tables/system/darwin/xprotect.cpp
Fixes warnings generated by Clang when `std::move` is used in a `return`
statement. Verified by `make clean`, saw no warnings, `make test` passes.
> Fix pessimizing move warnings

- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
- tools/lib.sh
There seems to have been a regression in package building. The `./tools/lib.sh` script now overloads the `SCRIPT_DIR` variable, which is also used in the package build scripts.
This changes the file-local variable in `./tools/lib.sh`.
> Fix make_package build for OS X/Linux

- osquery/remote/remote.cpp
- osquery/remote/requests.h
- osquery/remote/tests/requests_tests.cpp
- osquery/remote/transports/tls.cpp
- osquery/remote/transports/tls.h
When the configuration flag: --logger_tls_compress is used the client should
send a "Content-Encoding: gzip".
> [Fix #2058] Send Content-Encoding when using TLS compression

- docs/wiki/installation/cli-flags.md
- include/osquery/core.h
- osquery/core/system.cpp
- osquery/core/tests/conversions_tests.cpp
- osquery/tables/utility/time.cpp
- specs/utility/time.table
Beginning in version 1.8.0 all time uses will converge on an osquery-provided
getUnixTime() API call that returns, by default, UNIX time integers converted
to UTC/GMT. The 'time' table will respond with the parsed time for the
configuration. If the timezone is not UTC then osquery is using localtime.
This configuration option will affect the 'unix_time' response in the 'time'
table. Because of this configurable-effect the table is extended to include
'local_time' which is always the system local UNIX time.
> Introduce --utc flag to convert all calendar UNIX times to UTC

- osquery/config/parsers/tests/decorators_tests.cpp
- osquery/database/database.cpp
Currently, the decorations are applied to statuses and results in batch format.
This seems like an oversight, decorations should be on all results.
> Include decorations within results events

- osquery/tables/utility/time.cpp
- specs/utility/time.table
It is often helpful to know the local timezone of the machine. For this use
local_timezone, as the base timezone will use local or UTC depending on the
--utc flag. This will be default=UTC in osquery 1.8.0.
The datetime field is added to mimic ISO 8601, along with iso_8601.
The timestamp field remains as the time stamp used for logging (within osquery)
and commonly outside of osquery. The goal for adding multiple representations
is to allow joining/augmenting of other tables.
Cc: @PoppySeedPlehzr
> Add local_timezone and datetime (ISO) to time table

- osquery/tables/system/darwin/crashes.cpp
- specs/darwin/crashes.table
Renamed the crash_log table to crashes for future abstraction to other
operating systems. Also fixed how the table was parsing the most recent
stack trace and the registers.  Register values are now all parsed into
one column 'registers', which will be a space delimited string of the
form:
`register:value register:value ... register:value`
in order to best allow for OS abstraction.
> Renamed crash_log table to crashes and small fixes to parsing behavior

- osquery/tables/system/darwin/crashes.cpp
- specs/darwin/crashes.table
This commit adds mobile device crashes to the list of crash logs parsed
by the Crashes table as well as adding a lamdba to improve code reuse.
> Adding mobile device crash parsing to Crashes table

- include/osquery/registry.h
- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/registry/registry.cpp
- osquery/sql/sql.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/utility/hash.cpp
- tools/codegen/templates/default.cpp.in
This adds a new optimization feature that allows expensive tables to cache their results between JOINs. Consider JOINing a list of open sockets, for each process, then requesting to hash each process path. This query may hash the same path multiple times.
Within-query caching allows the hash table to respond with the previous result of the hash request as long as the requested computation was the result of a single query. Subsequent queries will perform subsequent hashing.
> Introduce within-query caching

- osquery/tables/system/darwin/crashes.cpp
The mobile 'LowBattery' crash logs provide little if any data of value,
and seem to be nothing more than notification events.  We're filtering
these out of the crashes table.
> Filtering out LowBattery crash logs

- osquery/config/parsers/decorators.h
- osquery/logger/logger.cpp
- osquery/logger/plugins/filesystem.cpp
- osquery/logger/tests/logger_tests.cpp
These APIs are not used within the logger plugins or the osquery codebase.
> Remove the logHealth method from logger plugins

- docs/wiki/deployment/configuration.md
- tools/deployment/osquery.example.conf
Having `host_uuid`, regardless of the `--host_identifier` flag, is useful for every query differential result. This adds an example set of decorator queries that log both the suspected username and actual host UUID.
> Add decorators to example config

- kernel/include/feeds.h
- kernel/src/osquery.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/events/kernel.cpp
- osquery/events/kernel.h
- osquery/events/kernel/benchmarks/kernel_communication_benchmarks.cpp
- osquery/events/kernel/circular_queue_user.cpp
- osquery/events/kernel/circular_queue_user.h
- osquery/events/kernel/tests/kernel_communication_tests.cpp
- osquery/tables/events/darwin/process_events.cpp
- osquery/tables/events/process_file_events.cpp
The OS X kernel subscribers have not been starting because they expect the publisher thread to run before they begin configuration. Due to some recent refactors the publisher thread creation now occurs after configuration.
The subscriber logic to check for a valid kernel connection is still valid.
> Revive the OS X kernel-based publishers

- include/osquery/logger.h
- osquery/logger/logger.cpp
- osquery/logger/plugins/aws_firehose.h
- osquery/logger/plugins/aws_kinesis.h
- osquery/logger/plugins/aws_util.h
- osquery/logger/plugins/filesystem.cpp
- osquery/logger/plugins/syslog.cpp
- osquery/logger/plugins/tests/filesystem_logger_tests.cpp
- osquery/logger/plugins/tls.cpp
- osquery/logger/plugins/tls.h
- osquery/logger/tests/logger_tests.cpp
The initialization of a logger plugin was confusing. The 'init' step was introduced to allow a daemon to buffer status events before a logger plugin is determined by external/remote configuration. The buffered statuses could then be transferred via a medium other than Glog (the default). To determine if Glog should continue to write statuses to the filesystem the 'init' method returned a Status.
Logger plugins should now use a feature method override to select how status logs should be handled.
> Refactor logStatus and logger initialization

- CMake/FindThrift.cmake
- osquery/CMakeLists.txt
The Thrift library should be discovered simiarly to all others. When using the build-macros for library discovery the caller can choose how to discover static or dynamic links.
> [Fix #2032] Remove manual Thrift library discovery

- osquery/core/system.cpp
When selecting UUID as the host identifier the client follows:
- If host_identifier is set to hostname, return the hostname.
- If UUID check a static UUID container
- If empty request the UUID from the backing storage, RocksDB
- If empty use the Apple hardware UUID or generate a UUID
- If the Apple UUID request fails generate a UUID
When no UUID is available in the backing store save the new UUID.
> Clean up host identifier UUID access

- tools/provision/debian.sh
Fixes #2055. Compared to from #2091, also moves the not in jessie ruby1.8-dev package to wheezy
> Allow building on Debian Jessie

- osquery/devtools/devtools.h
- osquery/devtools/shell.cpp
- osquery/main/shell.cpp
This introduces a new testing-related flag to the osqueryi shell.
The `--pack` flag takes a single argument, the name of a configured pack.
To list the configured packs try:
```
$ osqueryi -A osquery_packs
```
To run all queries, immediately and serially, try:
```
$ osqueryi --pack NAME_OF_PACK
```
Cc: @arubdesu
> Add --pack flag to the shell

- osquery/core/init.cpp
- osquery/core/posix/process.cpp
- osquery/core/process.h
- osquery/core/testing.h
- osquery/core/tests/process_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/core/windows/process.cpp
- osquery/main/tests.cpp
Replaced most instances of `pid_t` with `PlatformProcess` as necessary. 
Replaced platform-specific functions such as `getpid`, `getppid`, etc. with our equivalent process abstraction operations.
> Process Operations - osquery/core Integration

- tools/deployment/osqueryctl
Some Linux distros use SystemD instead of upstart/SysV, include a check for the SystemD service unit too.
> Check for systemd service in osqueryctl

- include/osquery/events.h
- include/osquery/logger.h
- osquery/events/events.cpp
- osquery/logger/logger.cpp
- osquery/logger/tests/logger_tests.cpp
This adds an additional API to logger plugins that requests `EventSubscriber`-based tables to send their events directly to logger plugins.
To have events forwarded to a `LoggerPluggin` that is registered as active via `--logger_plugin=YourPlugin` you must implement the following methods:
```cpp
bool usesLogEvent() override { return true; }
Status logEvent(const std::string& event) override { return Status(0); }
```
The event `std::string` will be the JSON-encoded event that is normally stored in RocksDB. If a `LoggerPlugin` requests forwarding of events, the event data is still stored in RocksDB to support the subscriber table abstraction.
> Add logEvent API to logger plugins

- osquery/tables/system/darwin/quicklook_cache.cpp
- specs/darwin/quicklock_cache.table
The `path` column should be JOINable to `file` and `hash`. The parsed `mtime` should be matchable to the `mtime` in `file` too.
See issue #2097 for details about Quick Look.
> Add quicklook_cache to Darwin

- osquery/distributed/plugins/tls.cpp
- osquery/remote/utility.h
What I've called the "node" API for TLS-based plugins abstracts the TLS endpoints around a item/node. The distributed actions act on the node by checking out/in work on the queue. Thus they should be POSTs.
> Use POST for distributed queries within the node API

- docs/wiki/deployment/aws-logging.md
The example aws config had some errors.
> fixed issue with aws logger example for kinesis and firehose

- tools/provision/ubuntu.sh
`fpm`'s dependency `ruby-xz` wants ruby version 1.9.3, this is an alias to the ABI equivalent 1.9.1 and seems to work fine on Precise.
> Use ruby/gem ABI version 1.9.1 on 12.04

- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/devtools/shell.cpp
- osquery/examples/example_extension.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- specs/etc_hosts.table
- specs/utility/time.table
- tools/codegen/gentable.py
- tools/codegen/templates/default.cpp.in
- tools/codegen/templates/foreign.cpp.in
Aliases (both column and table) allows us to change table and column names, then explicitly choose to support the old (deprecated) names.
> Introduce table aliases

- osquery/main/benchmarks.cpp
- tools/provision/lib.sh
google-benchmark jumped from 0.1.0 to 1.0.0 on homebrew and had minor API change which caused compilation failures. The release is here: https://github.com/google/benchmark/releases/tag/v1.0.0
Manually pulled in 1.0.0 and tested on vagrant boxes and via brew on OS X.
But prior to testing on build hosts, the updated sources will need to be pushed to s3/deps.
> Fix benchmark target and bump version of google-benchmark to 1.0.0

- include/osquery/core.h
- include/osquery/events.h
- osquery/core/init.cpp
- osquery/core/test_util.cpp
- osquery/database/database.cpp
- osquery/tables/utility/osquery.cpp
This changes several initialization steps:
- The daemon (and shell, though not needed) have a new `--ephemeral` flag.
- Events are now disabled in the shell by default, use `--nodisable_events` to re-enable.
- RocksDB-based backing storage is now disabled in the shell by default.
The `--ephemeral` flag for the daemon is disabled by default and will allow skipping configuration and database path sanity, and skipping `--pidfile` checks. This is intended to be used when debugging or monitoring the daemon process.
To make the RocksDB backing storage feature usage very clear we introduce a new flag: `--disable_database`. The shell sets this to true unless overridden in a `--flagfile` or via command line arguments.
Closes: #2109, #2110
> Add --ephemeral for daemons and disable shell events

- include/osquery/dispatcher.h
- osquery/dispatcher/dispatcher.cpp
- tools/deployment/make_osx_package.sh
- tools/lib.sh
With a `::removeService` method, combined with the abstracted thread start in the Dispatcher API, services auto-remove when finished.
This will un-break the kernel communication tests. These tests only stop when all their producer threads/services have ended.
> Add removeService to Dispatcher API

- osquery/tables/system/linux/os_version.cpp
Xenial changed the format of the `VERSION` string in `/etc/os-version`.
> Fix os_version detection for Ubuntu 16.04

- osquery/sql/CMakeLists.txt
- osquery/sql/sqlite_string.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
The three new SQLite functions:
- split: Splits a column using a set of tokens and a selected index.
- regex_split: Similar to split but with a regex instead of tokens.
- inet_aton: Returns the IPv4 decimal value for a string-formatted address.
> Add basic string split and inet_aton functions

- packs/it-compliance.conf
Getting the current status of System Integrity Protection in the it-compliance pack. The table was added in version 1.7.0
> Adding sip_config table to it-compliance pack

- tools/provision.sh
- tools/provision/darwin.sh
- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/lib.sh
Thus begins our need to include local (modified) brew formulas. This commit adds a new provision library method: local_brew. Use this function within provision scripts to install packages that are not appropriate for homebrew-core.
/cc @zwass
> Use local AWS-SDK formula for OS X

- osquery/filesystem/tests/fileops_tests.cpp
Some of the types in fileops tests were causing warnings to be thrown
during build, due to type mismatch. I've added a few local variables to
quiet these warnings.
Also note, a lot of clang formatting got applied as this was run through 
our formmater.
> Fixed typing warnings in FileOps tests

- tools/provision/lib.sh
The `linked_keg` key may exist but set to `null`, indicating no package version is installed.
> Check for none in linked_keg

- CMake/Packages.cmake
- tools/deployment/make_linux_package.sh
- tools/provision/centos.sh
Opt in the Ubuntu 16.04 `make_linux_package`, wrapped by `make packages` into including a systemd service unit. This is the same unit as CentOS 7.
> Add systemd service to Xenial

- osquery/core/tables.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
- specs/darwin/iokit_registry.table
- specs/darwin/kernel_extensions.table
- specs/darwin/keychain_items.table
- specs/darwin/launchd.table
- specs/darwin/smc_keys.table
- specs/groups.table
- specs/users.table
- specs/utility/file.table
- tools/codegen/gentable.py
This commit bumps the third-party SQLite to the 3.14.0 pre-release (18:59). With 3.14.0 the `LIKE` and `EQUALS` constraint operators may be mixed within a query. Previously these would fail to produce a valid set.
As part of the support, each virtual table should choose to bypass rowid-based deduplication using the new "`WITHOUT ROWID`" create table epilog. This will be appended to the schema if the table defines a `PRIMARY KEY` using `index=True`.
> Use SQLite 3.14.0 to support LIKE and EQUALS

- osquery/tables/system/tests/system_tables_tests.cpp
Using the first process that contains a non-empty path for `JOIN` tests is flaky. Instead the test should use its own PID.
> Use self-process for query join tests

- osquery/logger/CMakeLists.txt
- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/aws_util.cpp
- osquery/logger/plugins/aws_util.h
- osquery/logger/plugins/tests/aws_firehose_tests.cpp
- osquery/logger/plugins/tests/aws_kinesis_tests.cpp
- osquery/logger/plugins/tests/aws_util_tests.cpp
The AWS SDK changed how custom HTTP clients are used, and this commit brings
compatibility with the new initialization style.
> Update AWS logger code for AWS SDK 0.12.4

- tools/deployment/make_linux_package.sh
Added changes to package creation for linux for custom configs and post install scripts to optionally be included in base deb/rpm via env vars.  To build a package with a default osquery config and postinst script (to make osquery autostart after install), do the following:
````
cat << EOF >> postinst.sh
#!/bin/bash
update-rc.d osqueryd defaults
service osqueryd start
EOF
OSQUERY_CONFIG_SRC=/some/directory/osquery.example.conf OSQUERY_POSTINSTALL=./postinst.sh make package
````
> Ability to add default configs and postinstall scripts to deb/rpm packages

- osquery/core/tables.cpp
- osquery/sql/virtual_table.cpp
- specs/system_controls.table
This does not yet make multi-column primary keys. That will take some reading and re-parsing and is generally not helpful right now.
> Allow table specs to use multiple row indexes

- osquery/events/darwin/kernel_util.cpp
- specs/darwin/package_receipts.table
- tools/deployment/make_osx_package.sh
1. Use `path` within `package_receipts` to determine if the OS X kernel extension is installed.
2. Do not include the OS version within the package version.
> Fix OS X kernel extension autoload

- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/tests/aws_firehose_tests.cpp
Because of the way Firehouse aggregates records, we need to add newlines in
order to separate records in the resultant files.
> Add newlines in Firehose records

- docs/wiki/deployment/aws-logging.md
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/aws_kinesis.h
- osquery/logger/plugins/tests/aws_kinesis_tests.cpp
The AWS logging plugin sends shard_id_ as a partition key to AWS kinesis when pushing data.  The current implementation uses a static string as the shard id.  Kinesis uses these partition keys (i.e. shard ids) to load balance between shards in a stream.  By randomizing this value, you will get better performance on larger deployments using many shards in a Kinesis stream.  For more background on this, please read the following:
http://sdk.amazonaws.com/cpp/api/0.11.0-7-g6be9f8d/d5/d84/class_aws_1_1_kinesis_1_1_model_1_1_put_record_request.html#a1f230751b741869bb8a3d0618d055cb6
This feature can be enabled by setting the following config variable otherwise the functionality will remain the same:
````
"aws_kinesis_random_shardid": "true",
````
> Optional randomization of shard ids for AWS Kinesis load balancing.

- CMakeLists.txt
- tools/provision.ps1
Update the Windows provision script to install new required packages on Windows (cpp-netlib and linenoise-ng), and update CMakeLists to link to them ( #2007 ).
> Windows Daemon/Shell: Install and link to new prerequisites

- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
Added a check for nullptr before de-reference, which was causing segfaults when running as root.  This commit also bundles in formatting fixes from clang.
> Adding check for nullptr before dereferencing.  This fixes #2185

- CMake/Packages.cmake
This handles non-exec bits for both the embedded script calls for `make packages`.
> Add bash and python to make packages calls

- include/osquery/tables.h
- osquery/tables/system/system_utils.cpp
- osquery/tables/system/windows/processes.cpp
- osquery/tables/system/windows/system_util.cpp
- osquery/tables/system/windows/system_util.h
- osquery/tables/utility/file.cpp
- osquery/tables/utility/time.cpp
This PR includes the code for a Windows processes table and changes to other tables we need for daemon and shell to run. The Windows processes table uses WMI as a backend to gather process information. This commit does not include the CMake changes to build these tables, that is coming in a future PR.
> Windows Daemon/Shell: Windows Processes Table

- CMakeLists.txt
While hacking on osquery I found that the build does not use ccache if it's available.
This was a quick win to me. After a few compilations I got a clean build done in one minute (including dependencies).
Using ccache in the CI environment can also speed up the build.
> Use ccache when available to speed up compilation

- CMakeLists.txt
- osquery/filesystem/fileops.h
Previous error:
```
In file included from osquery/filesystem/filesystem.cpp:32:0:
osquery/filesystem/fileops.h:186:8: error: 'bool osquery::PlatformFile::getFileTimes(osquery::PlatformTime&)', declared using anonymous type, is used but never defined [-fpermissive]
In file included from osquery/filesystem/filesystem.cpp:32:0:
```
> Add -fpermissive and fixes using for anon struct

- tools/tests/utils.py
The move of `./specs` files from the specs root to `./posix` for POSIX-based implementations needs to make several other components aware of the refactor.
> Run profile on all POSIX tables

- osquery/core/windows/process.cpp
- osquery/core/windows/process_ops.cpp
- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/windows/fileops.cpp
This pull request should resolve #2201. This PR changes use of `&vector[0]` to `vector.data()`, which is more clear about the intent to access the underlying vector buffer.
> Use vector.data() verus &vector[0] to get underlying vector buffers

- osquery/core/init.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
This removes the ability for Watcher and Initialization code to explicitly override watchdog limits.
> [Fix #2203] Restore extension respawn limits to 20s

- CMakeLists.txt
This also cleans up some of `./CMakeList.txt`'s formatting issues.
> Silence ccache and clang warnings

- osquery/sql/virtual_table.cpp
Clang's static analysis will complain and error about this.
> Remove unused variable in virtual_table

- include/osquery/tables.h
- osquery/tables/system/darwin/tests/signature_tests.mm
The boost API: `boost::conversion::try_lexical_convert` is a `noexcept` alternative to `boost::lexical_cast`.  It should be used, and allowed to return a `null` type, within table implementations. Otherwise innocuous SQLite type conversions could throw exceptions and prevent all table data from returning.
> Use a noexcept lexical_cast for SQL type conversions

- osquery/tables/system/darwin/quicklook_cache.cpp
Using the boost ASIO libraries before calling SQLite open causes the "file://" protocol to be rewritten with a prepended CWD.
> Fix SQLite access after ASIO usage

- osquery.thrift
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
This alters the osquery.thrift spec to add a `::shutdown` method to the `Extension` class. The `ExtensionManager` inherits from this but includes a no-op shutdown method.
When an `ExtensionManager` (osquery core) stops, it optionally requests all `Extension`s to shutdown immediately. This helps quit extensions processes faster. The `osquery-python` extension will need to be rebuilt with the updated spec methods.
> Add shutdown method to extensions

- osquery/logger/plugins/tests/buffered_tests.cpp
This test was intermittently failing because it relies on the actual thread
scheduling. Our discussion in issue #2218 decided that it was worth keeping the
test around, while trying to mitigate the flakiness. The longer sleeps in this
test ran successfully hundreds of times in local testing.
> Increase block period in flaky BufferedForwarder test

- tools/get_platform.py
- tools/provision.sh
- tools/provision/arch.sh
- tools/provision/lib.sh
This will install the necessary packages. I had issues compiling which I was able to get around with the following diff (not included in the pull request):
```
00:20:17 tenforward (arch-linux-provisioner) ~/Documents/Git/osquery $ git diff
diff --git a/osquery/remote/transports/tls.cpp b/osquery/remote/transports/tls.cpp
index 4273293..f181af9 100644
--- a/osquery/remote/transports/tls.cpp
+++ b/osquery/remote/transports/tls.cpp
@@ -30,12 +30,12 @@ SSL_CTX* TLSv1_2_method(void) { return nullptr; }
SSL_CTX* TLSv1_2_server_method(void) { return nullptr; }
#endif
#if defined(NO_SSL_TXT_SSLV3)
-SSL_METHOD* SSLv3_server_method(void) { return nullptr; }
-SSL_METHOD* SSLv3_client_method(void) { return nullptr; }
-SSL_METHOD* SSLv3_method(void) { return nullptr; }
-SSL_METHOD* …
```
> Add ability to provision Arch Linux

- packs/osx-attacks.conf
Adding detection for the following malware:
Aobo: http://aobo.cc/aobo-mac-os-x-keylogger.html
Keydnap: http://www.welivesecurity.com/2016/07/06/new-osxkeydnap-malware-hungry-credentials)
> Adding Aobo Keylogger and OSX_Keydnap to osx-attacks

- include/osquery/database.h
- osquery/database/plugins/rocksdb.cpp
RocksDB is the default "database" plugin. Writes are normally kept in an in-memory memtable. Writes that are not part of the event pubsub system can be forced to sync to disk.
> Force RocksDB to sync writes for non-event domains

- tools/provision/arch.sh
- Removed make from provisioning since it is assumed to be installed on Arch systems
- Added wget to provisioning since it is required for install_aws_sdk further in the provisioning script
- Extended AUR dependencies text. Only one of rocksdb and rocksdb-static is required and when using rocksdb BUILD_LINK_SHARED should be set to True before building
> Arch provisioning cleanup

- osquery/distributed/distributed.cpp
Meets the minimum requirements asked of #2164, by logging execution of distributed queries.
> Log execution of a distributed query

- osquery/main/shell.cpp
Tab completion in osqueryi now attempts to use table names first,
falling back to normal filename completion when there are no
matches.
> Add autocompletion of table names in osqueryi

- tools/deployment/osqueryd.service
When using the default osqueryd.service file I am unable to restart the osqueryd service without it failing on me:
```
19:47:54 tenforward (master) ~/Documents/Git/osquery-git $ sudo systemctl restart osqueryd
19:48:00 tenforward (master) ~/Documents/Git/osquery-git $ sudo systemctl status osqueryd
● osqueryd.service - The osquery Daemon
Loaded: loaded (/etc/systemd/system/osqueryd.service; disabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Sun 2016-07-17 19:48:02 EDT; 640ms ago
Process: 12147 ExecStart=/usr/bin/osqueryd --config_path /etc/osquery/osquery.conf (code=exited, status=78)
Main PID: 12147 (code=exited, status=78)
Jul 17 19:47:56 tenforward systemd[1]: Stopped The osquery Daemon.
Jul 17 19:47:56 tenforward systemd[1]: Started The osquery Daemon.
Jul 17 …
```
> Better fault-tolerant defaults for systemd service

- include/osquery/tables.h
The `QueryContext` dtor is not calling the dtor for `VirtualTableContent`, which is a fairly large structure.
> Fix mismatched free/delete in QueryContext dtor

- osquery/database/database.cpp
- osquery/logger/tests/logger_tests.cpp
- osquery/tests/test_util.cpp
A swapped order of "added" and "removed" for log events makes sense. It does not change the API but allows for easier parsing of chunked logs.
> Swap removed and added for logs

- docs/wiki/deployment/file-integrity-monitoring.md
- osquery/tables/events/darwin/process_file_events.cpp
The `process_file_events` subscriber was included on Darwin and Linux, but it is only used (combined with a table) on Darwin. This moves the subscriber implementation into Darwin-only build folders from CMake's point of view.
> Remove process_file_events subscriber from Linux

- osquery/core/init.cpp
Prior to this change, both `--disable_database=false` and `--database_path` had to
be specified together. Now, if the user specifies `--database_path` the database
is enabled automatically.
> Enable DB in osqueryi when --database_path specified

- docs/wiki/deployment/process-auditing.md
- osquery/tables/events/linux/socket_events.cpp
1. Enable the `socket_events` table in Linux if `--audit_allow_sockets` is enabled.
2. Fix a path parsing error within the existing/disabled `socket_events` table.
> Introduce --audit_allow_sockets for Linux socket_events

- osquery/CMakeLists.txt
- osquery/core/posix/process.cpp
- osquery/core/posix/process_ops.cpp
- osquery/core/process.h
- osquery/core/tests/watcher_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/core/windows/process.cpp
- osquery/core/windows/process_ops.cpp
- osquery/extensions/tests/extensions_tests.cpp
There is a slight refactor of the watcher logic such that it can be applied to either a worker process and worker state OR a watcher process and state.
For the watcher we only apply a basic memory/RSS check.
> The watcher process should apply memory limits to itself

- osquery/tables/utility/osquery.cpp
- specs/utility/osquery_info.table
Knowing the watcher process when the daemon is using the watchdog is important.
> Add watcher column to osquery_info

- Doxyfile
- include/osquery/config.h
- include/osquery/database.h
- include/osquery/dispatcher.h
- include/osquery/enroll.h
- include/osquery/events.h
- include/osquery/extensions.h
- include/osquery/filesystem.h
- include/osquery/logger.h
- include/osquery/registry.h
- include/osquery/sql.h
- include/osquery/system.h
- include/osquery/tables.h
This change causes Doxygen to error if there are unrecognized commands, or
undocumented/incorrect parameters in documented functions. It does not require
that every function be fully documented, just that those that are do not have
errors.
Old documentation with problems was fixed to comply.
> Fix up doxygen docs and require correct docs in CI

- osquery/tables/utility/time.cpp
On the Windows 10 test build environment the time was set to UTC, which resulted in a blank timezone. This is fine, but it should mimic the results/style for POSIX. A simple hack is applied to check for blank timezones, where the assumption is no timezone = Z.
> Print UTC for blank timezones in utilities/time

- osquery/tables/system/linux/memory_info.cpp
- specs/linux/memory_info.table
Added a memory_info table for Linux machines based on [this issue](https://github.com/facebook/osquery/issues/2028).  The `/proc/meminfo` file is read and a single row containing memory information is stored in the table.
I kept the memory in units of kilobytes just like the `meminfo` file uses.
I was wondering if it's fine to keep the data type as INTEGER or if I should use BIGINT. It looks like the INTEGER type is 64 bits for sqlite so I don't think this is an issue.
> Added memory_info table for Linux

- osquery/logger/plugins/aws_util.cpp
- osquery/remote/transports/tls.h
This allows aws_util to support the various flags and special configurations
that TLSTransport implements.
> Use TLSTransport HTTP client in aws_util

- Makefile
- docs/wiki/development/building.md
- include/osquery/filesystem.h
- tools/provision/formula/libaudit.rb
1. Fix `make docs` regression from build system redesign.
2. Fix filesystem documentation.
3. Add documentation to the wiki about the build system redesign.
> Build documentation for brew-based build

- tools/provision.sh
- tools/provision/formula/llvm.rb
- tools/provision/lib.sh
This closes: #2308.
The sanitization frameworks are built and installed alongside LLVM and clang. The options osquery uses, and this new inclusion, are now opt-out within the LLVM formula.
> Bump LLVM to revision 1 and build with clang-rt

- tools/provision/arch.sh
As per you changes in tools/provision.sh line 83-85
```
if [[ -z "$SKIP_DISTRO_MAIN" ]]; then
distro_main
fi
```
the name of function in tools/provision/arch.sh should be distro_main()
> Rename the function main_arch() to distro_main()

- tools/provision/arch.sh
Running `make deps` fails due to function name, also ruby-irb doesn't exist as
a package on Arch Linux and appears to compile fine with it removed.
> Rename main function, remove ruby-irb

- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/lib.sh
When a `make deps` dependency encounters a cache miss, the from-source build is triggered. This must mimic the from-source CLI arguments to brew.
This commit also improves the `aws-sdk-cpp` formula.
> Fix dependency building for bottle cache misses

- packs/osx-attacks.conf
Malwarebytes recently did a writeup of a crossplatform Java based trojan: https://blog.malwarebytes.com/threat-analysis/2016/07/cross-platform-malware-adwind-infects-mac/
Unfortunately the trojan seems to use randomly generated strings for filenames and plist names so the detection rule is a bit long, but I've tested it on an actual infected VM and it works as advertised :)
> Adding detection query for Java_Adwind Trojan

- osquery/logger/plugins/tls.cpp
Missing initialization of the BufferedLogForwarder was causing an underflow in
the count of buffered logs, and error messages as described in #2324. This
commit brings the initialization of the forwarder for TLS in line with
aws_kinesis and aws_firehose, removing that error.
Fixes #2324.
> Properly intialize BufferedLogForwarder for TLS output plugin

- osquery/events/kernel/tests/kernel_communication_tests.cpp
> Allow the non-blocking kernel-test publisher to drop 5%

- docs/wiki/development/windows-provisioning.md
- osquery/CMakeLists.txt
- tools/make-win64-binaries.bat
* Copy DLLs into shell and daemon build directories
* Update batch files to use `cmake --build` instead of msbuild
* Remove copy files commands from batch file
* Update readme to reflect new changes
This closes #2296.
> Windows: Copy required DLLs into the build directory

- include/osquery/tables.h
I am not sure if this fixes "all" of the OSX 10.9 build problems. But from a quick search for ctor ambiguity, this seemed like the only instance, aside from `std::vector<...>`.
> [Fix #2281] Avoid ctor ambiguity in table header

- osquery/main/shell.cpp
This fixes a regression introduced by the platform-agnostic refactors for Windows.
> [Fix #2342] Use seconds for --profile_delay precision

- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
This also adds more debugging information to the test failure outputs.
> [Fix #2274] Relax return code checks for osqueryd tests

- osquery/tables/system/posix/logged_in_users.cpp
- specs/posix/logged_in_users.table
To differentiate between a user-temp log line and logged-in-user we add `type`. To find the users set:
```sql
WHERE type = 'user'
```
> Add 'type' to logged_in_users

- CMakeLists.txt
- osquery/CMakeLists.txt
Google benchmark 1.0.0 is included with the 1.8.0 build redesign.
> [Fix #2112] Remove forced benchmark skip

- include/osquery/dispatcher.h
- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/tests/dispatcher_tests.cpp
- osquery/logger/plugins/buffered.cpp
- osquery/logger/plugins/buffered.h
- osquery/logger/plugins/tests/buffered_tests.cpp
This improves dispatcher tests by allowing units to act like component tests and use embedded `std::thread`-based osquery APIs. A unit may force a 'service' to run by joining the `Dispatcher` before deconstructing.
> Improve dispatcher tests

- .clang-format
- CMakeLists.txt
- Doxyfile
- Makefile
- docs/wiki/development/building.md
- osquery/dispatcher/scheduler.cpp
- osquery/remote/transports/tls.h
- osquery/sql/sql.cpp
- osquery/sql/sqlite_math.cpp
- osquery/tables/system/darwin/kernel_info.cpp
- tools/audit.sh
- tools/lib.sh
- tools/provision.sh
This updates the `.clang-format` to the Google style from LLVM 3.6. Where our style differs, we add a `# differs` to the rule.
This also updates the `make format` rule to force-format everything different than the current `master` branch. If you haven't updated master in a while then there will be quite a few changes proposed. This allows our CI (code audit) to detect unformatted changes in the current PR. Updating the `.clang-format` to version 3.6 should help with "seesawing" from one recommendation to another. If we notice this we will more carefully inspect the rules and version of LLVM our developers are using.
There are several instances where a `// clang-format off` is added. I've added those to this PR.
> Add clang-format rules from 3.6

- tools/provision/lib.sh
There's weird behavior when maintaining multiple osquery checkouts and modifying the dependency formulas because the "local" tap is nothing but an installed symlink to the formulas within our `./tools` directory.
> Always update the local tap symlink for make deps

- osquery/logger/plugins/aws_util.cpp
- osquery/logger/plugins/aws_util.h
- osquery/logger/plugins/tests/aws_util_tests.cpp
- tools/provision.sh
- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/lib.sh
1. Remove `AWS::Region` enum for version 0.14.x
2. Fix re-install of deps symlink.
3. Add helper `bottle` and `install` macros to the provision script.
> Update to AWS-SDK-CPP version 0.14.x

- .gitignore
- CMakeLists.txt
- docs/wiki/development/osquery-sdk.md
- external/CMakeLists.txt
Folks maintaining osquery extensions have asked for a simpler way of building and testing. This allows external extensions/modules to use the same build system reducing potential for runtime-linking crashes and simplifying extension/module development.
Closes #2084
> Introduce 'external' project builds: make externals

- .clang-format
- Makefile
- osquery/filesystem/filesystem.cpp
- tools/provision/lib.sh
Hopefully, this allows clang 3.6-3.9 to use our input `.clang-format` configuration.
There is a minor artifact around testing the code audit, a OS X clang-format version 3.9 is run against `./osquery/filesystem/filesystem.cpp` to assure no seesawing for Ubuntu's version 3.6.
This also adds "now-required" Homebrew auto-update disabling configuration to the `make deps` provisioning. Auto updating our Taps introduces scenarios which are difficult to test.
> Fix code auditing job and disable homebrew auto-update

- tools/provision/formula/rocksdb.rb
There are some API changes in 4.8 & 4.9.
I'm not sure if we're using those APIs yet. Let's see if the tests pass first.
> Bump rocksdb to 4.9

- tools/make-win64-binaries.bat
This will load VS build variables for a native amd64 build prior to launching CMake. This should close #2354.
> Load VS variables for amd64 native build prior to launching cmake

- osquery/tables/system/linux/users.cpp
Some `pwd` members (`char*`) may be uninitialized pointers. This occurs very rarely due to odd configurations with `/etc/passwd`.
> Handle empty Linux pwd members

- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/linux/processes.cpp
- specs/processes.table
1. Add a `threads` column to the `processes` table that returns the number of threads for that process.
2. Rename `phys_footprint` to `total_size` and attempt to support a column-alias as to not break existing queries where this column was explicitly `SELECT`ed.
> Rename phys_footprint to total_size and add threads

- osquery/events/events.cpp
- osquery/tables/utility/osquery.cpp
- specs/utility/osquery_events.table
There are two significant changes here:
1. This moves the location of `event_count_++` from within the publisher's `::fire` call to the subscriber's `::add` call. All subscriptions will be fired, but a subscriber may not "add" an event every time. Now the `events` count in the `osquery_events` meta table better reflects a subscriber's state.
2. The `restarts` column was confusing, it really counts an opaque concept of "refreshing" the publisher's runloop. It's still not the best verb.
> Count subscriber events correctly in osquery_events

- Makefile
- osquery/devtools/shell.cpp
There are a lot of formatting changes here due to the recently updated `.clang-format`.
The significant changes include:
1. Adding a `.list` meta command to the shell that mimics `.tables`.
2. Adding a `.socket` meta command, which is also included in the `.help` documentation. This will quickly show the tool's Thrift socket path.
> Add .list and .socket to shell meta command set

- osquery/core/init.cpp
- osquery/core/system.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/logger/logger.cpp
- osquery/tables/utility/osquery.cpp
This is fairly important, it changes the default mode for what status events are logged to `INFO`. It had been set to `WARNING` and `INFO` was relatively unused.
This also removes expected support for RocksDB 'in-memory' databases. If a shell-user requests a database via CLI flags it will now work.
> Use LOG(INFO) and set INFO as default logging mode

- include/osquery/database.h
- include/osquery/extensions.h
- include/osquery/sql.h
- include/osquery/tables.h
- osquery/core/tables.cpp
- osquery/database/query.h
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/scheduler.h
- osquery/dispatcher/tests/scheduler_tests.cpp
- osquery/examples/example_extension.cpp
- osquery/examples/example_module.cpp
- osquery/extensions/extensions.cpp
- osquery/sql/benchmarks/sql_benchmarks.cpp
- osquery/sql/sql.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/tests/sql_tests.cpp
- osquery/sql/tests/sqlite_util_tests.cpp
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- specs/darwin/quicklock_cache.table
- tools/codegen/gentable.py
- tools/codegen/templates/default.cpp.in
- tools/codegen/templates/foreign.cpp.in
Table attributes allow virtual tables to make decisions about how their data should be used. With attributes, the table may alert call-sites that the query logic does not make sense.
More importantly, some of the attributes may be made available to the higher-level call-sites external from the virtual table implementations. For this we amend `SQLInternal` to expose an `::eventBased` check. When used in the context of the scheduler, the results can skip the intermediate differential DB store and differential set difference operations. This should lead to enhanced performance and save some hosts from stopping their workers when the "re-insert" into RocksDB causes several compactions to occur.
> Introduce table 'attributes'

- .gitignore
- tools/provision/formula/llvm.rb
This will use about 300M additional space within the Cellar and about 100M additional space in the download cache. It will upgrade the `clang-format` to that available in Homebrew and in choco.
> Upgrade LLVM to 3.8.1 on Linux

- include/osquery/system.h
- osquery/logger/logger.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
This attempts to make the shell and osquery schedule a bit more helpful when queries act on 'weird' tables. We still should investigate ways to make osquery "do the right thing", but in the mean time let's be helpful.
```
~/git/github/osquery (branch:usage_warnings) » ./build/darwin/osquery/osqueryi 
osquery> select * from file;
W0831 17:28:53.894932 1969598464 virtual_table.cpp:495] Table file was queried without a required column in the WHERE clause
W0831 17:28:53.894984 1969598464 virtual_table.cpp:503] Please see the table documentation: https://osquery.io/docs/#file
osquery> select count(*) from chrome_extensions;
+----------+
| count(*) |
+----------+
| 20       |
+----------+
osquery> ^D
~/git/github/osquery (branch:usage_warnings) …
```
> Emit warnings for improper 'osquery' table usage

- tools/deployment/make_linux_package.sh
This functionality mirrors the OSX build flag `-t` to include a server cert chain file in package builds for tls connections.  This feature is added as an env variable to make it possible to build with the standard `make package` command.  An example use case is as follows:
`OSQUERY_TLS_CERT_CHAIN_SRC=/path/to/ca_certs.pem make package`
> Added *nix package build env flag to include a tls server certs file

- osquery/dispatcher/scheduler.cpp
- osquery/distributed/distributed.cpp
This is a significant change:
1. It promotes log lines from the distributed and schedule executor from verbose to `INFO`.
2. It includes slight modifications to the log line, so any parsing or counting will need to be revisited.
> Change schedule and distributed log execution status text

- tools/provision/formula/cmake.rb
- tools/provision/formula/gcc.rb
CMake 3.6.0 no longer builds because the patch (https://gitlab.kitware.com/cmake/cmake/merge_requests/34.patch) was updated and the `sha256` no longer matches. This updates the deps to install 3.6.1, which does not need a patch.
> deps: CMake 3.6.1

- packs/osx-attacks.conf
ref https://securelist.com/blog/research/75990/the-missing-piece-sophisticated-os-x-backdoor-discovered/
> add query to detect Backdoor.OSX.Mokes.a

- include/osquery/distributed.h
- osquery/distributed/distributed.cpp
We would like the queries buffered to RocksDB because if the system is killed before they've run but after they've been received, currently they will just be lost.
> Buffer the distributed queries to RocksDB for greater reliability

- osquery/filesystem/darwin/plist.mm
- osquery/tables/system/darwin/sandboxes.cpp
It's possible to create ill-formatted plist content that crashes osquery worker processes. This can lead to "blinding" of table content if a table never finishes executing because of an unhandled exception.
> Fix minor sandboxes performance issues and plist parsing exceptions

- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/launchd.cpp
When parsing plists for `launchd`, `apps` and other OS X tables, the existence of a `*.app` does not mean an "application" still exists. The current `osquery::readPlist` and other methods will return nasty messages event if the `Info.plist` does not exists or happens to be a broken symlink. In these cases no row is returned.
This PR cleans up the potential verbose messages by not emitting false-positive plist-parsing errors.
> Check for plist existance before attempting parsing

- osquery/tables/CMakeLists.txt
- osquery/tables/system/linux/rpm_packages.cpp
- specs/blacklist
- tools/provision.sh
- tools/provision/amazon.sh
- tools/provision/centos.sh
- tools/provision/fedora.sh
- tools/provision/formula/Abstract/abstract-osquery-formula.rb
- tools/provision/formula/beecrypt.rb
- tools/provision/formula/berkeley-db.rb
- tools/provision/formula/librpm.rb
- tools/provision/formula/popt.rb
- tools/provision/oracle.sh
- tools/provision/rhel.sh
- tools/provision/scientific.sh
This restores the RPM tables to the Linux build.
1. Add `popt`, `berkeley-db`, `beecrypt`, and `librpm` to the Linux dependency list.
2. Link the resultant dependencies into `libosquery_additional`.
3. Remove the blacklist for `rpm_packages` and `rpm_package_files`.
4. Add the RPM table implementation to all Linux builds, ungated from CentOS/RHEL-based systems.
5. Add a new class to help discovery the RPM database. Like everything else librpm-based, this may be changed with environment variables.
For this build extension, `popt` and `libdb` were already part of the build, now they are tightly controlled and linked. Beecrypt is added as a possible RPM digest implementation over the default NSPR/NSS. It may be possible to replace this with the already-included gcrypt in the future.
> Add librpm build and RPM tables

- osquery/tables/system/windows/registry.cpp
When we allocate an array using the new …[…] syntax, we should deallocate it using delete[]. In these cases, we needed to change delete to delete[]. If we use the wrong form of delete to match our allocation with new, we have undefined behavior.
> [windows] fix deallocation mismatches

- tools/provision.sh
- tools/provision/formula/Abstract/abstract-osquery-formula.rb
- tools/provision/formula/gcc.rb
- tools/provision/formula/glibc-legacy.rb
- tools/provision/formula/glibc.rb
- tools/provision/formula/libgpg-error.rb
- tools/provision/formula/xz.rb
- tools/provision/formula/zlib-legacy.rb
- tools/provision/lib.sh
This added zlib-legacy and reorganizes the legacy runtime directory to handle any formula install. As part of this we move xz and libgpg-error after the GCC install.
> Refactor legacy runtime

- osquery/database/query.cpp
- osquery/database/query.h
- osquery/database/tests/query_tests.cpp
- osquery/dispatcher/scheduler.cpp
This PR includes a reorganization of `Query` and the internal database storage of query results and their change/differential calculation.
First, the class now includes detection of when a query with the same name changes. If you alter a query by including new columns or restricting the predicate, the results may change. It is possible to invalidate all results since differential calculation is "dumb" and does not understand column/key alterations.
A log line is also generated when query results are saved for the first time. This is helpful in debugging and altering on situations where the internal database becomes unavailable. The observed result will be a "fresh" select of the entire table.
Second, there is a small memory optimization for new table scans. Previously, new scans would …
> Improve scheduled/differential query performance and logging

- CMakeLists.txt
Simple, save some build resources in the case of a stuck test.
> Limit CTest runs to 600 seconds

- tools/deployment/make_linux_package.sh
I changed the underbars to dashes in the tls server file which gets baked into packages.  This change was to make it match the naming standard used in the current osx package creation script.  
I also changed the storage location to be in var instead of etc since it is also stored there in osx.  
This should make configs a bit more cross platform.
> Changed the naming convention of the tls server file to match osx

- Makefile
- tools/provision/formula/asio.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/thrift.rb
- tools/provision/lib.sh
To support machines without AVX2 features we need to avoid compiling and linking the dependent instructions found the ASM implementations of some OpenSSL crypto algorithms.
Additionally, we are removing the SSL3 methods from our OpenSSL build. The osquery TLS plugins explicitly define a cipher list that excludes SSL3, but as an extra measure (for plugins not using our transports) we remove it from ASIO and Thrift too.
> Build OpenSSL with no-asm to remove AVX2 dependency

- CMakeLists.txt
- osquery/config/config.cpp
- osquery/core/tests/process_tests.cpp
- osquery/dispatcher/tests/dispatcher_tests.cpp
- tools/tests/sanitize_blacklist.txt
This fixes the `Dispatcher` and `Process` tests so they pass `make sanitize` with TSAN.
> [Fix #2482] Use atomic member in Dispatcher tests

- tools/tests/test_base.py
While `make test` should have set the `PYTHONPATH`, tooling calling the tests directly should always prefer the dependencies static path.
> Prefer the osquery dependencies root for Python tests

- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/extensions/extensions.cpp
There is a bit of a "logic race" in the `Watcher` and `ExtensionManagerWatcher`.
When using an `extensions_autoload` the `Watcher` (watchdog) will start extensions automatically. It will also monitor these processes such that they don't run away with CPU/memory. If these processes are killed with/without the control of the `Watcher` it will try to "restart" the process by fork/execing again.
If the `ExtensionManagerWatcher` has not yet recognized the extension as "missing" there will be an extension registry collision. The two data sets involved are rather unique: the watcher knows what paths you want to load, the extension manager knows a name and assigned UUID. Without significant refactoring/redesign there's no realistic way to merge these sets. In this case a collision will cause the …
> Remove extensions retry and introduce watcher retry

- tools/provision/formula/Abstract/abstract-osquery-formula.rb
When running the `python` `postinstall`, having `PYTHONPATH` set to the local `site-packages` fixes an initial install bug for OS X.
> Add PYTHONPATH to brew environment for Python postinstall

- osquery/registry/registry.cpp
I'm hesitant to consider #2483 a true positive. However, this lock does not introduce circular locking and seems reasonable.
The high-level case:
1. Config Extension starts, responds to `ping`, is assigned a `uuid` and the `Initializer` flow continues.
2. (race) The extension dies and is deregistered immediately. 
3. (race) `Initializer` attempts to `setUp` and `setActive` the config plugin.
> [Fix #2483] Lock registry manipulation while setting active plugins

- osquery/sql/virtual_table.cpp
Use special base value of '0' that can handle values starting with 0x
process_memory_map on Ubuntu 16 LTS return offset in hex
> Properly handle hex bigint values.

- osquery/core/conversions.h
- osquery/core/system.cpp
- osquery/core/tests/conversions_tests.cpp
- osquery/tables/utility/time.cpp
As promised for 1.8.3, `--utc` will now be default. And `time.local_time` should become hidden.
> Toggle --utc to true

- CMake/CMakeLibs.cmake
Previously the dependencies' library path was added to `LINK_PATHS_SYSTEM` meaning dynamically-linked libraries could prefer our installed dependencies over those libraries available on the system. This was added to accommodate `libgcc_s` on Linux, which maintains an acceptable ABI.
On OS X the `liblzma` was included in our install path and linked as a mistake. This PR almost mitigates the issue. Eventually a refactor is needed to allow call sites to determine how they want to link: dynamic, dynamic system, or static.
> Gate the default dependency path to Linux

- include/osquery/events.h
- osquery/dispatcher/scheduler.cpp
- osquery/events/events.cpp
- osquery/events/linux/syslog.cpp
- osquery/events/linux/syslog.h
- osquery/events/linux/tests/syslog_tests.cpp
- osquery/events/tests/events_database_tests.cpp
- osquery/extensions/interface.cpp
- osquery/tables/events/darwin/disk_events.cpp
- osquery/tables/events/darwin/file_events.cpp
- osquery/tables/events/darwin/hardware_events.cpp
- osquery/tables/events/darwin/process_events.cpp
- osquery/tables/events/darwin/process_file_events.cpp
- osquery/tables/events/linux/file_events.cpp
- osquery/tables/events/linux/hardware_events.cpp
- osquery/tables/events/linux/process_events.cpp
- osquery/tables/events/linux/socket_events.cpp
- osquery/tables/events/linux/syslog_events.cpp
- osquery/tables/events/linux/user_events.cpp
- osquery/tables/events/yara_events.cpp
- specs/linux/syslog.table
This will remove the use of current time for `syslog.time` and introduce a new column called `datetime`.
Events now uses an `optimize_id` alongside `optimize` to prevent returning colliding events added within the same second as the previous `genTable` call.
> Remove time-override for events add API

- tools/provision.sh
- tools/provision/formula/ccache.rb
We plan to use `ccache` on the AWS build hosts. The easiest way to configure these are through the existing provision script.
> deps: Add ccache to provision

- osquery/config/config.cpp
…artup time. The use-case is a TLS back-end server that cannot provide a configuration before an enrollment, or after an enrollment has expired. Because of the sequence in which modules are initialized, config request goes first, which fails. Since Config::loaded_ is only ever set to true if the Config::load succeeds, it remains set to false because of the config request failure. On subsequent successful config requests, the event monitoring publishers/subscribers are never updated. Thus, event monitoring cannot be enabled at all.
The fix is to set the Config::loaded_ variable to true after a subsequent config::update call succeeds.
> Fix update of event pub/sub plugins when config fails to load

- tools/provision/formula/asio.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/thrift.rb
Update the bottle hashes for ASIO, OpenSSL, and Thrift on 10.11.
> deps: Update OS X asio, openssl, thrift

- osquery/main/windows/daemon.cpp
Stopping **osquery daemon service** on Windows will succeed but result in "Terminated unexpectedly" error. This is because prior to requesting shutdown, we do not signal to the service control manager that the service has stopped.
To fix this, we update the service status both for the watcher and the worker (only if `--disable-watchdog` is triggered).
> Fixing "Terminated unexpectedly" whilst shutting service down issue

- osquery/remote/transports/tls.cpp
On OS X and Linux, we can use a directory for server certificate pinning. A restriction of regular files was added for Windows but did not include a platform check.
> Restrict regular file checking of TLS pinned cert to Windows

- osquery/core/system.cpp
Linux hosts should act like OS X and attempt to return the platform/motherboard UUID before generating an ephemeral.
> Attempt to query platform UUID on Linux

- include/osquery/events.h
- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
Closes #2513.
This removes the 10s and 3600s indexes for events. The result is a simpler indexing algorithm at similar cost/time.
> Refactor events and remove 10/3600 indexes

- include/osquery/core.h
- include/osquery/extensions.h
- osquery/config/packs.cpp
- osquery/core/init.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/tests/extensions_tests.cpp
- osquery/main/lib.cpp
This is not an API change, but does begin to enforce API change incompatibility checks for extensions. The first may be 1.8.2 and 1.8.2+ unless we revert a number container size for `RouteUUID`.
> Add extensions SDK incompatibility checking

- osquery/config/config.cpp
The `loaded_` member of configuration acts as a "has-run-load" check. This exists because `Config::update` may be called multiple times before the `Initializer` has completed a configuration load.
> Correct config-loaded meaning to be has-run-load

- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
Two fixes to home directory assumptions:
1. If you have `HOME` set by `sudo` and it cannot be accessed, fall back to using effective user's home directory.
2. If a temporary directory is used it should be created before returning and caching.
> Create temp directory and fail over to user home

- include/osquery/tables.h
I found that an uninitialized `TableAttributes` may lead to undefined behavior while testing with older extensions that append to the schema. Pre-1.8.0 routes are equivalent to `::NONE`.
> Initialize VirtualTableContent attributes

- README.md
- docs/wiki/installation/cli-flags.md
- docs/wiki/installation/install-linux.md
- docs/wiki/installation/install-osx.md
- docs/wiki/installation/install-windows.md
- mkdocs.yml
1. Add a `Windows 10` badge to the README.
2. Add Windows-related osquery flags to the wiki.
3. Add a basic Windows-install guide to the wiki.
4. Document the **syslog** logger plugin and the **syslog** event publisher flags.
5. Remove references to **brew** as a recommended method of install for OS X.
> docs: Windows 10 badge/install/flags

- osquery/remote/transports/tests/tls_transports_tests.cpp
This is not a solution for #2532 (which is meant to bring attention to the problem), but a work-around while the issue is addressed.
> [#2532] Handle potential test errors 'Address family not supported'

- osquery/logger/logger.cpp
- osquery/logger/tests/logger_tests.cpp
- tools/tests/test_osqueryd.py
This adds an esoteric option `--logger_secondary_status_only` that will only be used/needed when using multiple logger plugins. Some configurations may only warn WARNING/ERROR logs to be forwarded to the secondary plugin.
> Add option for status-only secondary logger plugins

- osquery/main/windows/daemon.cpp
Previously, arguments can only be parsed in `osqueryd.exe` in manual start mode (either started via properties page in `services.msc` or `sc.exe start`). Now, we can parse arguments for automated starts by manually decomposing `GetCommandLine`.
> Ability to parse arguments for Windows Services

- docs/wiki/deployment/remote.md
Make the documentation consistent with [the code](https://github.com/facebook/osquery/blob/master/osquery/remote/enroll/plugins/tls.cpp#L88).
> Add missing host_identifier in TLS enrollment request documentation

- osquery/registry/tests/registry_tests.cpp
> [#2544] Fix sign-compare warnings in tests

- tools/provision/formula/sleuthkit.rb
I've updated the dependency `sleuthkit` to v4.3.0 - fix #2545
Happy Hacktoberfest!
> Update sleuthkit to v4.3.0 (#2545)

- tools/lib.sh
Directories may have spaces and in bash such correspondent dir variables should be properly quoted.
upd: Signed CLA
> fix for directories with spaces in path

- osquery/events/events.cpp
- osquery/extensions/interface.cpp
- osquery/tables/system/darwin/processes.cpp
- specs/darwin/disk_events.table
- specs/darwin/package_bom.table
- specs/darwin/quicklock_cache.table
The goal here is to reduce several log messages that are difficult to aggregate and make use of. `LOG(INFO)` logs should be countable/reportable. That means in normal/non-exceptional cases they should not include variant information.
> Reduce several INFO logs to VLOGs and increase size-INTEGERs to BIGINT

- packs/osx-attacks.conf
> The “_main” function writes the data within ‘_Payload_1’, ‘_Payload_2’, and ‘_Payload_3’ variables to the following files, respectively:
/Users/Shared/.local/kextd (SHA256:
227b7fe495ad9951aebf0aae3c317c1ac526cdd255953f111341b0b11be3bbc5)
/Users/Shared/com.apple.updates.plist (SHA256:
1f22e8f489abff004a3c47210a9642798e1c53efc9d6f333a1072af4b11d71ef)
/Users/Shared/start.sh (SHA256:
d494e9f885ad2d6a2686424843142ddc680bb5485414023976b4d15e3b6be800)
> add osx komplex query

- tools/provision/arch.sh
Building osquery fails if the [multilib] repository is enabled resulting
in a conflict between gcc and gcc-multilib:
```
$ pacman -S gcc
resolving dependencies...
looking for conflicting packages...
:: gcc and gcc-multilib are in conflict. Remove gcc-multilib? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gcc and gcc-multilib are in conflict
```
> Remove package gcc from arch linux provisioner

- include/osquery/core.h
This typo was causing `make docs` to error out.
> Fix doxygen string in core.h causing `make docs` to fail

- osquery/tables/system/linux/memory_info.cpp
- specs/linux/memory_info.table
memory_info table on most systems had several blank fields. This is because sizeof(int) often maps to 4-bytes, and many systems have memory figures in excess of 4G. Switched the type of all fields in memory_info to BIGINT to fix the issue.
> Change memory_info fields to BIGINT to handle 4G and larger sizes

- tools/make-win64-binaries.bat
This will make the Windows build host use all CPUs and suppress most of the useless stdout.
> [Fix #2549] Windows: use all CPUs with minimal verbosity

- osquery/tables/system/windows/processes.cpp
Removed the need for a WMI query for _every_ captured process ID.
<pre>
PS > measure-command { & .\osqueryi.exe 'select * from processes;' --json }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 178
Ticks             : 1788286
TotalDays         : 2.06977546296296E-06
TotalHours        : 4.96746111111111E-05
TotalMinutes      : 0.00298047666666667
TotalSeconds      : 0.1788286
TotalMilliseconds : 178.8286
</pre>
Closes #2574
> Efficiency improvements to processes table on Windows

- include/osquery/registry.h
- include/osquery/tables.h
- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
Previously, scans of tables with columns marked `index=True` were assumed the same cost as all tables. This is not true, scanning tables with an index, using that index in the predicate, should yield lower costs.
> [Fix #1690] Use INDEX options in constraint cost evaluation

- osquery/tables/networking/etc_hosts.cpp
- osquery/tables/networking/etc_protocols.cpp
- osquery/tables/networking/etc_services.cpp
- osquery/tables/system/windows/registry.cpp
As per the feedback on my last pull request #2595, I've switched `#define fs boost::filesystem` to `namespace fs = boost::filesystem;` as directed on mine and similar files within the project.
> Use 'namespace' instead of '#define' for boost::filesystem

- osquery/logger/plugins/aws_util.cpp
When osquery flipped over to cpp-netlib for aws http connections, a hidden bug occurred which did not pop up until recently.  This bug caused aws ami role authentication via the auth provider `InstanceProfileCredentialsProvider` to stop working.  Here is a short description of the bug.
1. Osquery switched to using cpp-netlib instead of the aws core http lib (libcurl)
2. Aws changed their ami role credentials endpoint from http://blablabla/security-credentials to http://blablabla/security-credentials/ (notice the trailing slash).  
3. Aws sdk uses the non slash version and now gets a 301 redirect for the new url.
4. cpp-netlib has a redirect issue when run in asyc mode.  This issues causes netlib to not follow redirects even when its set to. Info can be found in this issue …
> Fix for AWS ami role auth with cpp-netlib custom redirect condition

- tools/provision/formula/xz.rb
Seems like the Linux xz revision was bumped and we forgot to update a bottle.
> deps: Bump xz revision and bottle hash on Linux

- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
- osquery/tables/system/linux/smbios_tables.cpp
- osquery/tables/system/linux/smbios_utils.h
- osquery/tables/system/posix/smbios_utils.cpp
This also fixes odd behavior in Linux when reading a 'regular' file from /sys that only returns a max of a page-read in bytes.
> [Fix #2599] Read from Linux SMI sysfs node for SMBIOS

- osquery/core/system.cpp
If the response from Linux's sysfs node contains trailing NULLs, a short string construction will erase them from the result.
> [Fix #2601] Return hardware UUIDs without potential trailing NULL bytes

- osquery/tables/system/windows/services.cpp
- specs/windows/services.table
**New Virtual table for Windows (issue #2540)**
**Process Info:**
**Service Config Info:**
PS C:\Users\ExtremeGTX>Measure-Command {osqueryi.exe "select * from services;"}
Seconds           : 0
Milliseconds      : 238
Ticks             : 2384709
TotalDays         : 2.76007986111111E-06
TotalHours        : 6.62419166666667E-05
TotalMinutes      : 0.003974515
TotalSeconds      : 0.2384709
TotalMilliseconds : 238.4709
> Add virtual table: Windows services

- osquery/tables/system/windows/appcompat_shims.cpp
- specs/windows/appcompat_shims.table
This adds a table that does some processing of the application compatibility shim information in the registry and presents it in a nice way. To get this same info without a table it would require two queries, and even then it would not be displayed in the best way.
http://files.brucon.org/2015/Tomczak_and_Ballenthin_Shims_for_the_Win.pdf
> add table for appcompat shims

- osquery/tables/system/windows/wmi_event_filters.cpp
- specs/windows/wmi_event_filters.table
The "query" column was missing from the cpp file and the the "query_language" column was missing from the table spec. This fixes both issues.
> Fix missing columns in wmi_event_filters table

- include/osquery/system.h
- osquery/core/system.cpp
- osquery/tables/system/linux/apt_sources.cpp
- osquery/tables/system/linux/deb_packages.cpp
- osquery/tables/system/linux/rpm_packages.cpp
- osquery/tables/system/linux/tests/users_tests.cpp
- osquery/tables/system/linux/users.cpp
1. Introduce a new `dropTo` call that allows tables to drop the processes effective privileges to a `username`.
2. Allow `users` on Linux to optimize based on the `username` column.
3. For APT/DEB/RPM tables, drop privileges to `nobody` before accessing any database content.
> Add dropToUser method to privileges dropper interface

- osquery/distributed/plugins/tls.cpp
- osquery/logger/plugins/tests/tls_logger_tests.cpp
- osquery/logger/plugins/tls.cpp
- osquery/logger/plugins/tls.h
Two bugs in the TLS logger re-enrollment handling are fixed by this commit:
1. A fixed node key is used, so a new node key acquired through re-enrollment
is ignored.
2. The body is not checked for node_invalid, so no re-enrollment is triggered
when necessary.
Each of these bugs is fixed by the following:
1. Call `getNodeKey("tls")` instead of using a fixed stored node key.
2. Use TLSRequestHelper::go which already includes handling for node_invalid
(this makes these TLS calls consistent with other TLS methods).
> Fix TLS logger plugin handling of re-enrollment

- osquery/remote/utility.h
A TLS server might like to return `"node_invalid": true` and an error string
indicating why the node was invalid. The old behavior caused `node_invalid` to
be ignored if `error` was specified, therefore making it impossible for
osqueryd to resolve the error.
With the new behavior, osqueryd can now re-enroll when a reason is provided.
> Prioritize reading node_invalid over error for host re-enrollment

- osquery/core/tables.cpp
- osquery/devtools/shell.cpp
The `definition` action is fairly legacy. Move to the new `columns` action that handles a few additional error cases such as missing column "options".
> [Fix #2630] Remove 'definition' TablePlugin action

- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/windows/fileops.cpp
`PlatformFile` does not like sharing the file for reading. This created issues with Filebeat.
Closes #2639
> Fixes PlatformFile issue with sharing

- tools/provision.sh
- tools/provision/formula/asio.rb
- tools/provision/formula/aws-sdk-cpp.rb
- tools/provision/formula/boost.rb
- tools/provision/formula/ccache.rb
- tools/provision/formula/cmake.rb
- tools/provision/formula/cpp-netlib.rb
- tools/provision/formula/cppcheck.rb
- tools/provision/formula/gflags.rb
- tools/provision/formula/glog.rb
- tools/provision/formula/google-benchmark.rb
- tools/provision/formula/libmagic.rb
- tools/provision/formula/linenoise-ng.rb
- tools/provision/formula/lz4.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/pcre.rb
- tools/provision/formula/python.rb
- tools/provision/formula/rocksdb.rb
- tools/provision/formula/sleuthkit.rb
- tools/provision/formula/snappy.rb
- tools/provision/formula/thrift.rb
- tools/provision/formula/yara.rb
- tools/provision/formula/zzuf.rb
- tools/provision/lib.sh
This updates the commit hashes for `Homebrew` core and dupes to support building on OS X 10.12. That allows binary (bottle) installs for some of our tools. The local builds for library dependencies have been uploaded to S3.
> [Fix #2641] Update OS X build and add Sierra hashes

- tools/deployment/make_linux_package.sh
RPMs should convert their "long" version strings to use underscores: `2.0.0-1-g12345` becomes `2.0.0_1_g12345`.
> Use underscores for long RPM package versions

- osquery/sql/virtual_table.cpp
This moves the `satisfied` warning checks outside of the check for `argc`. A constraint set may be selected that includes a column that was marked required. But there may not be expression content from the `JOIN`.
> [Fix #2644] Check constraint requiremens regardless of expression

- osquery/distributed/plugins/tls.cpp
- osquery/logger/plugins/tls.cpp
- osquery/remote/transports/tls.cpp
- osquery/remote/utility.h
The `Request` API uses a "waterfall" calling pattern resulting in all logic handled in a method responsible for `POST`ing content to an endpoint. A recent change to the logger `tls` plugin migrated transport calls to the `Request` API but did not handle this under-the-hood logic error (as well as a lack of compression support within the `Request` API).
This change introduces `_verb` as a potential parameter and `_get` to force a GET request via the waterfall calling. Requesting compression is the responsibility of the caller via a new `_compress` parameter.
> Fix regression in Requests/TLS APIs related to verb detection

- osquery/main/windows/daemon.cpp
- tools/analysis/analyze.bat
- tools/provision.ps1
This PR adds in a cppcheck that will be run against new PRs for Windows going forward. Alongside this new static analysis script, I'm fixing a few issues it found including a leaking resource handle in the deamon's `installService` code.
Currently our static analysis will only fail on errors found, as opposed to warnings and style issues.
Lastly, I'm bumping up our Powershell gate to be 5.0 and greater, as currently our provisioning script fails on Powershell 3.0 due to our use of newer cmdlets. I'm currently working on making our provisioning 3.0 friendly, but this will come later.
> Adding cppcheck analysis script

- docs/wiki/installation/cli-flags.md
This fixes an errenous error referring to the "logger_mode" argument
as an octal string instead of as a decimal string.
Fixes #2609
> [Fix #2609] Fix error in "CLI Flags" documentation

- osquery/logger/plugins/aws_kinesis.cpp
Random partition keys should be assigned per batch rather than per event.  This avoids nasty kinesis rate limiting errors.  It also avoids various issues with resending failed data.
> Random partition keys should be assigned per batch

- osquery/logger/plugins/filesystem.cpp
- osquery/main/lib.cpp
- osquery/remote/transports/tls.h
Used clang-format to shorten lines greater than 80 characters wide.
Exceptional case occured for "tls.h", in which the offending lines were
located in between the "clang-format (off/on)" comments.
> [Fix #2652] Shorten long lines

- osquery/core/init.cpp
- osquery/dispatcher/distributed.cpp
- osquery/extensions/extensions.cpp
While visiting the `init.cpp` `Initializer` implementation, I found some instances where runtime platform checks could be used over preprocessor logic.
The primary goal is to allow `--distributed_plugin` modifications, and allow the configured plugin to exist as an autoloaded extension.
> Allow distributed plugin changes and reduce ifdefs

- docs/wiki/development/osquery-sdk.md
- docs/wiki/index.md
- docs/wiki/introduction/overview.md
- osquery/extensions/extensions.cpp
This adds a new shell-only flag `--extension` that "autoloads" a single extension. This is helpful for testing/developing extensions.
> Add --extension to osqueryi for quick autoloading

- tools/provision/lib.sh
Over the course of dependency updating we will occasionally change the Homebrew pinned revisions. This assumes the install has the up2date references, meaning we need to continually fetch from each repository.
Since we continually `pull` then `reset`, `make deps` will have a tendency to output repeated stdout. Let's silence it!
> Silence several git messages when running make deps

- docs/wiki/installation/cli-flags.md
- osquery/core/init.cpp
This optional "default" `flagfile` is used in the shell and daemon ONLY if the file exists. This is helpful when using a default set of extensions/additional tables. The default `flagfile` can set `--extensions_require` after having autoloaded from `/etc/osquery/extensions.autoload`.
> Add optional default flagfile /etc/osquery/osquery.flags.default

- osquery/tables/system/linux/os_version.cpp
- osquery/tables/system/tests/system_tables_tests.cpp
- specs/os_version.table
This removes the precompiler logic in Linux's `os_version` table. The bias is towards newer distributions using a `/etc/os-version`, but we include logic for `redhat-release` too. The only noticeable change is the `name` on older distributions will now be blank.
> Prefer /etc/os-release for Linux os_version

- CMakeLists.txt
- Makefile
- tools/analysis/lsan.supp
The LLVM sanitize framework environment variables are cleared from `cmake` to `ctest`. To enable suppression and options during `make test` we need to break out the `test` target and set the variables for the `ctest` call.
> Refactor test/ctest and suppressions

- include/osquery/core.h
- osquery/config/config.cpp
- osquery/devtools/shell.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
#2674 demonstrates a leak and race between the shell's `shell_exec` and extension's use of the `Registry`. Internals may assume a valid SQLite DB handle for running internal queries. If there is no resource contention the handle used by the shell is the same as internal queries. Unfortunately the shell makes use of the handle directly and MUST lock access.
> [Fix #2674] Add SQLite prepare lock to shell_exec

- Makefile
- tools/provision.sh
- tools/provision/formula/curl.rb
- tools/provision/formula/openssl.rb
- tools/provision/lib.sh
This tries to handle all potential setups:
* Someone has OpenSSL installed without `certs.pem`: uninstall `curl`, reinstall `openssl` with `certs.pem`, reinstall `curl`.
* Someone with neither will install `openssl` then `curl`.
> [Fix #2678] Run postinstall for OpenSSL to install certs.pem

- include/osquery/extensions.h
- osquery/core/init.cpp
- osquery/extensions/extensions.cpp
This introduces a new feature `--extensions_require` that allows a `flagfile` to set a comma-separated set of extension names. osquery will apply the existing `--extensions_timeout` while waiting for the set of extensions to be registered.
The shell or daemon will emit a warning message if a required extension is not found within the timeout.
This is helpful for `osqueryi` when the tool does not need to depend on active config or logger plugins. Before, when using one of the query-and-exit workflows, extensions were useless.
> Add --extensions_require feature

- osquery/events/events.cpp
- osquery/tables/events/linux/socket_events.cpp
It is important to run subscriber `setUp` methods and use the result to potentially disable subscribers.
When a subscriber is disabled, the `init` method to add subscriptions will not be called. This fixes an oversight with the Linux `audit` publisher. Currently enabling audit will always enable `bind` and `connect` auditing, along with process auditing.
> [Fix #2681] Use subscriber setUp result to enable/disable

- osquery/tables/networking/linux/routes.cpp
When requesting routes from Linux netlink, the NL header is followed by a route-details structure that allows the caller to limit/customize the response. This area of the buffer was not sanitized leading to inconsistent responses between calls to the `routes` virtual table.
> [Fix #2591] Fix Linux routes table inconsistencies

- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/preferences.cpp
Some columns include the `ColumnOptions::ADDITIONAL` option, indicating a predicate will alter the results and possibly return additional content. The best index cost calculation should bias towards a lower cost when these columns are included.
The OS X `preferences` table should also use `LIKE` for `path` constraints operators.
> Allow TableOptions::Additional to influence cost
