osquery/osquery

- osquery/main/daemon.cpp
> Add --daemonize option to osqueryd

- osquery/events/events.cpp
- osquery/tables/system/darwin/process_open_files.cpp
If thread contexts go out of scope of the stack then the dtor/terminate does as well. Detach these publisher threads before they go out of scope.
> [Fix #559] Detach event publisher threads when ending

- osquery/core/system.cpp
- osquery/main/daemon.cpp
- osquery/tables/system/darwin/processes.cpp
- tools/deployment/osquery.example.conf
Working towards better install/package experience on OSX. Also removing gotos for #579 and improving pid checking by including the basename in OSX processes table when a `proc_name` isn't available.
> Provide example config, improve pid check

- osquery/core/md5.h
- osquery/tables/CMakeLists.txt
- osquery/tables/specs/darwin/acpi_tables.table
- osquery/tables/specs/darwin/iokit_registry.table
- osquery/tables/system/darwin/acpi_tables.cpp
- osquery/tables/system/darwin/iokit_registry.cpp
- osquery/tables/system/darwin/pci_devices.cpp
Working towards a complete OSX boot status table/set of tables. We'll need multiple tables and a combination of data to determine boot state.
> OSX IOKit registry and ACPI table data

- osquery/tables/networking/linux/routes.cpp
There's no RAII for the socket or a unique pointer structure for the netlink message, but the goto usage is nasty and can be removed while maintaining readability and safety.
> Remove gotos from linux routes

- osquery/core/system.cpp
- osquery/tables/system/darwin/nvram.cpp
- osquery/tables/system/linux/processes.cpp
> Use sizeof with memcpy and memset

- include/osquery/hash.h
- osquery/core/hash.cpp
- osquery/tables/system/darwin/acpi_tables.cpp
- osquery/tables/system/linux/acpi_tables.cpp
- osquery/tables/utility/hash.cpp
1. A few hash style nits.
2. Use const content passing.
3. Update table implementation callsites into hashing.
> Update the md5 hashing callsites

- include/osquery/hash.h
- osquery/core/hash.cpp
I added some doxygen docs for hash.h
> hash.h documentation

- tools/codegen/genapi.py
> Ignore ',' add support Linux-only categories in genapi.py

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/main/daemon.cpp
> config-check command in osqueryd

- tools/codegen/genapi.py
- tools/profile.py
1. Fix the --output for performance profiling and add support for --output and --leaks to profile.py
2. Add --diff to pretty-print API changes to genapi.py
> Add table API changes to genapi, leaks summary view

- osquery/tables/networking/linux/process_open_sockets.cpp
In CentOS netlink may send failure messages (#671). It's unclear why the netlink requests fail, but it's possible to scan /proc/net/<protocol><family> for the same information.
> Fallback to /proc/net/ for open sockets in Linux

- osquery/core/system.cpp
Sometimes launchd will NOT unlock the daemon when asked. If so when the LD is restarted, osqueryd will stop previous instances.
> [FIx #676] Add --force option to osqueryd

- include/osquery/filesystem.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/filesystem_tests.cpp
Working pull request for adding the ability to specify queries with wildcards in them for recursive traversal and wildcard matching.
> Adding recursive directory traversal functionality

- tools/deployment/make_linux_package.sh
- tools/deployment/make_osx_package.sh
Adding latest to package names
> Adding latest to package names

- tools/codegen/gentable.py
> ignore ds_store on table generation

- tools/deployment/make_osx_package.sh
Super small fix. The plist file was getting put in /var/osquery, when it should be put in /Library/LaunchDaemons, so the daemon was not being started when the package was installed.
I assume this was not intentional, because the postinstall script still tries to load the plist from the LaunchDaemons folder. If we don't want to the daemon to autostart, we should remove the postinstall script.
> --autostart option for make_osx_package.sh

- osquery/tables/specs/x/file.table
- osquery/tables/utility/file.cpp
> Add stat details to file table

- osquery/tables/specs/x/hash.table
- osquery/tables/specs/x/interface_addresses.table
- osquery/tables/specs/x/last.table
- osquery/tables/specs/x/logged_in_users.table
- osquery/tables/specs/x/osquery_info.table
- osquery/tables/specs/x/passwd_changes.table
- osquery/tables/specs/x/process_envs.table
- osquery/tables/specs/x/process_open_sockets.table
- osquery/tables/specs/x/processes.table
> Adding description to columns

- osquery/main/run.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
- osquery/sql/sqlite_util_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table_tests.cpp
This is an attempt to make `sqlite3` safer. Access is now arbitrated and applies an RAII model.
> Add a SQLiteDBManager

- Makefile
- README.md
- Vagrantfile
- tools/lib.sh
- tools/provision.sh
Now we can build in CentOS 7, rejoice!
> Adding support for CentOS 7

- osquery/extensions/extensions.cpp
- tools/provision.sh
> Fix for the CentOS 7 support

- tools/provision.sh
> Adding rpm-build to provision

- CMake/Packages.cmake
- tools/provision.sh
Adding needed dependencies for packages in CentOS 7
> Adding needed dependencies for packages in CentOS 7

- CMake/Packages.cmake
- tools/provision.sh
Provision script had a bug and some of the packages were not installed. Also some dependencies were missing when creating the RPM package
> Bug in provision when checking for packages

- tools/provision.sh
All packages were presumed to be installed when they were not. Oops :)
> Logic to check packages was wrong

- include/osquery/sql.h
- osquery/CMakeLists.txt
- osquery/core/system.cpp
- osquery/distributed/CMakeLists.txt
- osquery/distributed/distributed.cpp
- osquery/distributed/distributed.h
- osquery/distributed/distributed_tests.cpp
- osquery/sql/sql.cpp
This introduces the notion of a DistributedQueryHandler that uses a "provider" to read/write requests and results to and from the master. The full flow is exercised via integration tests, and unit tests for each component.
It is intended to foster discussion around this client side interface, as well as provide a base to build from.
> POC for client side of distributed queries.

- tools/provision.sh
Using gcc 4.8 and fix on the provision script
> Using gcc 4.8 and fix on the provision script

- tools/provision.sh
Dependencies needed for building osquery now are stored in our S3 bucket
> Downloading dependencies from S3

- Makefile
- include/osquery/extensions.h
- osquery/extensions/extensions.cpp
- osquery/extensions/extensions_tests.cpp
- requirements.txt
- tools/codegen/gentargets.py
> syncing sdk with codemod and targets

- include/osquery/config.h
- include/osquery/events.h
- osquery/config/config.cpp
- osquery/config/config_tests.cpp
- osquery/events/darwin/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/events/events_tests.cpp
- osquery/events/linux/inotify_tests.cpp
- osquery/tables/CMakeLists.txt
- osquery/tables/events/darwin/file_changes.cpp
- osquery/tables/events/darwin/hardware_events.cpp
- osquery/tables/events/linux/file_changes.cpp
- osquery/tables/events/linux/hardware_events.cpp
- osquery/tables/specs/x/file_changes.table
You can now specify directories with wild cards in them to generate events when any of them change
> Added ability to specify files to watch with wildcards

- CMakeLists.txt
- Makefile
- tools/sync.sh
Fix https://github.com/facebook/osquery/issues/773
> Move sync to CMake and remove generated mkdir

- include/osquery/events.h
- osquery/events/events.cpp
Allow overloaded virtual warnings.
> Removed reinterpret plugin casts

- tools/deployment/make_linux_package.sh
- tools/deployment/osqueryctl
- tools/deployment/osqueryd.initd
> osqueryctl tool

- osquery/core/init.cpp
See #785 for context. If you don't have a properly configured system,
osqueryd will print a convenient warning with instructions.
> Adding warning text if the system is not configured

- osquery/tables/system/darwin/processes.cpp
Allow constraints to emit a parent pid.
> [Fix #788] Lookup ppids on OS X using CTL_KERN

- tools/provision.sh
> [Fix #805] Add symlink to gmake for gflags

- osquery/filesystem/filesystem.cpp
- osquery/filesystem/filesystem_tests.cpp
Supporting relative paths and added extra tests for .. in file paths
> Filesystem dotdot

- osquery/tables/utility/file.cpp
Added a condition so the files table will also return folders
> Files now returns directories as well

- osquery/tables/utility/time.cpp
> Cleaned Up Time Table

- include/osquery/filesystem.h
- osquery/filesystem/filesystem.cpp
- osquery/tables/system/darwin/certificates.mm
This is pretty slow and take a bit more memory than I'd like.
> Add more keychain search paths for certificates

- README.md
> updating readme to include another query

- osquery/filesystem/darwin/plist.mm
> [For #579] Remove gotos from auto-release plist parsing

- include/osquery/logger.h
- include/osquery/registry.h
- osquery/config/config.cpp
- osquery/config/config_tests.cpp
- osquery/core/init.cpp
- osquery/logger/logger.cpp
- osquery/logger/logger_tests.cpp
- osquery/registry/registry.cpp
Implement the basic requirement from #796, although that issue/request is deprecated.
> Move logger/config to use Registry getActive

- osquery/core/watcher.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.h
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/test_watchdog.py
> Improve extensions integration testing

- osquery/filesystem/filesystem.cpp
> Fixing UBN by adding extra trys to uncaught throws

- include/osquery/filesystem.h
- osquery/events/events.cpp
- osquery/events/linux/inotify.cpp
- osquery/events/linux/udev.cpp
- osquery/extensions/extensions.cpp
This will greatly improve osqueryd's performance! The select timeouts were very low.
> Reduce restart times for event runloops

- osquery/logger/logger.cpp
- osquery/logger/plugins/filesystem.cpp
Updates third-party to master too.
> [Fix #907] Use glog to log to data-identified files

- Vagrantfile
> Cleaned up Vagrantfile

- Makefile
- include/osquery/events.h
- include/osquery/registry.h
- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/events/events_database_tests.cpp
- osquery/events/events_tests.cpp
- osquery/events/linux/inotify.h
- osquery/events/linux/inotify_tests.cpp
- osquery/tables/events/darwin/file_changes.cpp
- osquery/tables/events/darwin/hardware_events.cpp
- osquery/tables/events/darwin/passwd_changes.cpp
- osquery/tables/events/linux/file_changes.cpp
- osquery/tables/events/linux/hardware_events.cpp
- osquery/tables/events/linux/passwd_changes.cpp
- osquery/tables/events/yara_matches.cpp
Event time was not initialized, leading to arbitrary time reporting.
> Fix event subscriber time

- Makefile
- tools/lib.sh
- tools/provision.sh
- tools/provision/centos.sh
- tools/provision/lib.sh
- tools/provision/ubuntu.sh
Remove some repeated or unused conditionals.
Make sure autoconf is at least version 2.69: #926
> Update provision.sh and os-specific deps

- docs/wiki/development/creating-tables.md
MATCHES is not a valid ConstraintOperator, and a quick look at the history and I can't find a time when it ever was.
> Remove MATCHES from docs.

- README.md
Adding some links to the build table.
> Update readme table

- docs/wiki/installation/install-linux.md
- tools/deployment/make_linux_package.sh
osquery-site will land after this.
> [Fix #964] Restrict apt-sources to arch=amd64

- CMake/FindGlog.cmake
- CMakeLists.txt
- osquery/dispatcher/dispatcher.h
- osquery/extensions/interface.h
- osquery/filesystem/CMakeLists.txt
- tools/provision/lib.sh
- tools/provision/rhel.sh
Working towards building our dependencies using GCC 4.9 on RHEL 6.5.
> [Implement #926] RHEL6 provisioning

- osquery/core/init.cpp
It doesn't make sense to start publisher threads when a single query will be executed.
> Skip event publishers when a single query is used

- CONTRIBUTING.md
- README.md
Minor doc changes:
* update links to the new wiki
* and use https
* formatting to not have long scrollbars.
> Minor doc updates

- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/tables/CMakeLists.txt
- osquery/tables/networking/etc_protocols.cpp
- osquery/tables/networking/tests/etc_protocols_tests.cpp
- osquery/tables/specs/etc_protocols.table
- tools/tests/test_protocols.txt
This adds a new table to display the file /etc/protocols, which will be handle for the iptables table
> Adding new table for /etc/protocols

- CMakeLists.txt
- Makefile
- tools/provision/rhel.sh
> Simpler RHEL6 provision

- Makefile
- osquery/CMakeLists.txt
- osquery/tables/specs/centos/rpm_package_files.table
- osquery/tables/specs/centos/rpm_packages.table
- osquery/tables/system/centos/rpm_packages.cpp
Add files/RPM info DB metadata
> Add rpm_package_files table

- osquery/devtools/shell.cpp
Remove modes: HTML, Tabs, Explain.
Remove stats (meaningless for virtual tables).
Use the osquery SQLite DB manager within meta and shell SQL
execution to allow registry/extensions non-locking access.
This allows existing runtime DB manipulators to prefer a locking
modifier. Currently these manipulators will fallback to a more
transient db instance. The effect was, no shell-accessible runtime
created virtual tables.
> Remove unpopular features from shell

- docs/wiki/deployment/yara.md
- mkdocs.yml
This is in need of some work, but might as well toss it up and get more eyes on it.
> First cut at YARA docs.

- include/osquery/database/db_handle.h
- include/osquery/database/query.h
- include/osquery/database/results.h
- include/osquery/logger.h
- osquery/config/config.cpp
- osquery/core/test_util.cpp
- osquery/core/test_util.h
- osquery/database/query.cpp
- osquery/database/results.cpp
- osquery/database/tests/query_tests.cpp
- osquery/database/tests/results_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/logger/logger.cpp
- osquery/logger/tests/logger_tests.cpp
Scaffolding for snapshot queries and schedule+worker health reporting.
> [#966] Allow snapshot scheduled items

- osquery/config/config.cpp
- osquery/config/tests/config_tests.cpp
- osquery/core/darwin/conversions.cpp
- osquery/core/tables.cpp
- osquery/database/results.cpp
- osquery/distributed/distributed.cpp
- osquery/filesystem/filesystem.cpp
- osquery/logger/logger.cpp
- osquery/remote/serializers/json.cpp
- osquery/tables/system/darwin/extended_attributes.cpp
- tools/tests/utils.py
Mostly applying the correct exception handling to JSON reading. And removing lax exception catching from JSON writing (where a parse error is not thrown). 
This also includes some reported nullptr catching from malloc, and fixes a profiling/leak detection regression from reorganization of spec files.
> Various exception hardening

- tools/provision/lib.sh
Tested on a clean ubuntu14 vagrant box.
> [Fix #1099] Build RocksDB 3.10.2 on linux

- include/osquery/events.h
- osquery/config/config.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/dispatcher.h
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/scheduler.h
- osquery/dispatcher/tests/dispatcher_tests.cpp
- osquery/events/darwin/fsevents.cpp
- osquery/events/darwin/fsevents.h
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/extensions/extensions.cpp
- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
- osquery/extensions/tests/extensions_tests.cpp
- osquery/remote/enrollment/plugins/tests/http_enrollment_tests.cpp
Better control over extension thread managers and dispatcher service lifetimes.
> Harden extensions/dispatcher tests

- osquery/core/watcher.cpp
Apply the same permissions checking from the extensions loader to the worker/watcher fork and exec.
> Apply a safe permissions check to worker

- osquery/tables/system/crontab.cpp
Mostly a crontab catch-all for RHEL, CentOS, and Ubuntu.
> Include several search paths for user contabs

- CMake/FindGlog.cmake
- CMakeLists.txt
- Vagrantfile
- docs/wiki/development/building.md
- tools/lib.sh
- tools/provision/rhel.sh
Using the discussion and work from @blakefrantz in: https://github.com/facebook/osquery/pull/1145
This fixes a build issue, adds us-west-2 region and VPC support.
> Amazon AWS/EC2 Vagrant support for RHEL/Amazon Linux

- osquery/tables/networking/freebsd/routes.cpp
- osquery/tables/specs/blacklist
- osquery/tables/system/freebsd/procstat.cpp
Missing osquery/tables.h include in routes.cpp and need to add gen_users
to blacklist on FreeBSD.
> Fix build on FreeBSD.

- osquery/tables/system/darwin/sandboxes.cpp
- specs/darwin/sandboxes.table
List simple application sandbox container details.
> Add application sandbox container metadata

- CONTRIBUTING.md
The git workflow has been severely out of date for a long time. I made a
few updates to reflect the current state of affairs.
> Update the contributing docs git workflow

- .idea/.name
- .idea/encodings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/osquery.iml
- .idea/scopes/scope_settings.xml
- .idea/vcs.xml
These files are ten months old, nobody uses CLion on the team to verify
that these still work properly, etc. If someone uses CLion and default
project settings would be useful, please add and maintain new project
files.
> Remove CLion files

- tools/provision/lib.sh
> updating yara to 3.4.0

- osquery/CMakeLists.txt
- osquery/core/darwin/conversions.cpp
- osquery/events/CMakeLists.txt
- osquery/events/darwin/diskarbitration.cpp
- osquery/events/darwin/diskarbitration.h
- osquery/tables/events/darwin/disk_events.cpp
- specs/darwin/disk_events.table
- specs/hardware_events.table
This implements #1103.
The `publisher` reports on disk events and its metadata, using the DiskArbitration framework on OS X. Currently disk appearance and disappearance events are published for both physical and virtual disks (DMG files). On an event trigger, disk properties are parsed and that metadata is reported along with the action.
The `subscriber` subscribes to virtual disk events currently.
```
osquery> select * from disk_events;
action = add
path = /Users/sbs/Downloads/googlechrome.dmg
name = Apple
bsd_name = /dev/disk2s1
uuid =
size = 32256
time = 1434779637
ejectable = 1
mountable = 0
writable = 0
content = Apple_partition_map
media_name = Apple
vendor = Apple
filesystem =
checksum = 7AC543FC
action = add
path = /Users/sbs/Downloads/googlechrome.dmg
name = …
```
> [Implement #1103] DMG Mount Events

- osquery/tables/system/darwin/keychain_utils.cpp
> Check for nullptr in CreatePropertyFromCertificate

- kernel/user/test/consumer.cpp
- kernel/user/test/producer.cpp
- osquery/events/kernel/circular_queue_user.cpp
- osquery/events/kernel/circular_queue_user.h
The makefile will no longer effectively build the test system.
The kernel/user directory is on its way out.
> Moved kernel userland code into the osquery directory structure.

- tools/provision/lib.sh
- tools/provision/ubuntu.sh
Towards "loosely" supporting 10.04 builds.
> Loose support for building on Ubuntu 10.04

- osquery/extensions/extensions.cpp
- osquery/extensions/interface.h
- osquery/remote/transports/tests/tls_transports_tests.cpp
- osquery/remote/transports/tls.cpp
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/test_osqueryi.py
This adds a small retry (3 times) to the core's extension watcher thread.
> [Fix #1198] Add a small retry to ext watcher

- CMakeLists.txt
- docs/wiki/development/kernel.md
- kernel/CMakeLists.txt
- kernel/Makefile
- kernel/src/osquery.cpp
- kernel/tools/darwin.sh
- kernel/tools/deployment/Info.plist
- tools/deployment/make_osx_package.sh
- tools/provision/lib.sh
This PR includes a rebase on facebook/master, so it includes the previous 2 kernel-feature commits.
> Towards CMake-based OS X kernel extension building

- kernel/include/feeds.h
- osquery/events/CMakeLists.txt
- osquery/events/kernel.cpp
- osquery/events/kernel.h
> Kernel event publisher

- README.md
- docs/wiki/installation/install-freebsd.md
- mkdocs.yml
Moving platform specific build instructions to the wiki, to keep the
README brief.
> README updates

- osquery/tables/system/darwin/processes.cpp
> [Fix #1295] `processes` table to report gid correctly.

- CMake/Packages.cmake
- kernel/CMakeLists.txt
- kernel/tools/deployment/Info.plist
- kernel/tools/unload_with_retry.sh
- tools/build.sh
- tools/deployment/make_osx_package.sh
OS X jenkins machines will now build and test the kernel extension as well.  It will also be included in the package produced for OS X.
> Build system changes for kernel extension testing and deployment.

- kernel/CMakeLists.txt
- kernel/include/feeds.h
- kernel/src/osquery.cpp
- kernel/src/publishers.h
- kernel/src/publishers/darwin/process_events.c
- osquery/events/kernel.cpp
- osquery/events/kernel.h
- osquery/events/kernel/circular_queue_user.cpp
- osquery/events/kernel/circular_queue_user.h
- osquery/tables/events/process_events.cpp
Created a more generic way to add kernel events.
> Publisher system for kernel events in the kernel extension.

- tools/codegen/genapi.py
Generation of json file with tables now can be done to an external directory
> Adding support to generate documentation to external files

- osquery/tables/system/darwin/authorization_mechanisms.mm
- osquery/tables/system/darwin/authorizations.mm
- specs/darwin/authorization_mechanisms.table
- specs/darwin/authorizations.table
Adding an `authdb` table. This utilizes the `AuthorizationRightGet` function from the Security Framework.
> Added authdb table

- CMake/Packages.cmake
- CMakeLists.txt
- tools/codegen/genapi.py
The tables doc in JSON format will be generated now on packages and doc targets
> Generation of table docs with packages and docs targets

- packs/incident-response.conf
- packs/it-compliance.conf
- packs/osx-attacks.conf
- packs/vuln-management.conf
Adding all the query packs files:
* incident-response
* it-compliance
* vuln-management
* osx-attacks
These files provide all the queries, description, interval and required version and platform, to have a comprehensive number of queries, aggregated per topic.
> Query packs files

- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/preferences.cpp
- tools/tests/utils.py
The profile tool had a bug where it was not including platform tables during leaks checking. This re-enables and fixes a memory leak it found.
> Fix profile platform bug in leaks checking

- osquery/remote/transports/tls.cpp
This is a fix to support the compiler used on Ubuntu 10.
> Support for older GCC compiler

- osquery/CMakeLists.txt
- osquery/core/watcher.cpp
- osquery/filesystem/filesystem.cpp
> [Fix #1381] Add documentation/install for daemon+Homebrew

- packs/incident-response.conf
> Update an error in the incident response pack

- tools/deployment/make_osx_package.sh
Make sure the directory for creating packages is correct.
> Updating the script to create packages for 10.9 building

- README.md
We are building now for OSX 10.9
> Adding OSX 10.9 build badge

- tools/lib.sh
- tools/provision.sh
- tools/provision/fedora.sh
Adds support for compiling on Fedora 21 by enabling the `make deps` target to build successfully.
> Support for Building on Fedora 21

- README.md
Hat tip to @theopolis https://github.com/facebook/osquery/issues/1465#issuecomment-134835685
Did a quick cursory scan in README and docs/wiki, didn't find any other problematic queries.
> [Doc Update] Fix example query in README

- osquery/tables/system/darwin/usb_devices.cpp
1. Report OS X USB `vendor_id` and `model_id` as hex-encoded numbers.
2. Whitelist the PCI simulation HUBs in OS X 10.11 from generating empty USB device rows.
3. Use device-reported serial numbers on OS X if available.
4. Use the IOKit node/item label if the `model` string is missing.
> [Fix #1432] Improve OS X USB device reporting

- osquery/tables/CMakeLists.txt
- osquery/tables/system/magic.cpp
- specs/magic.table
- tools/provision/amazon.sh
- tools/provision/centos.sh
- tools/provision/darwin.sh
- tools/provision/freebsd.sh
- tools/provision/oracle.sh
- tools/provision/rhel.sh
- tools/provision/ubuntu.sh
> Adding magic table to check for libmagic data

- CMakeLists.txt
- osquery/events/darwin/kernel_util.cpp
- osquery/events/kernel.cpp
- osquery/events/linux/udev.cpp
- osquery/examples/example_extension.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/remote/transports/tests/tls_transports_tests.cpp
- osquery/tables/networking/linux/arp_cache.cpp
- osquery/tables/system/darwin/extended_attributes.cpp
- osquery/tables/system/linux/disk_encryption.cpp
- osquery/tables/system/linux/pci_devices.cpp
- osquery/tables/system/linux/usb_devices.cpp
All the log entries won't have a dot at the end.
> Removing dots at the end of log entries

- osquery/devtools/shell.cpp
* Mostly formatting fixes -- slightly more inline with the rest of the codebase
* Removed unused variables/macros/fields
* Remove Oracle/MS style SQL command terminator -- only support `;` as the command terminator.
> Shell Cleanups

- osquery/core/init.cpp
> Only log to warning if the config can't be read by the daemon

- osquery/tables/other/yara.cpp
This fixes a bug with the `yara` table and using `sigfile` to load a signature file within query (not using a configuration binding signature groups to file event groups).
> Fix YARA sigfile caching

- osquery/database/db_handle.cpp
This is an attempt to make database reads and locks easier to debug with `--verbose`.
> Write helpful DB access/open error to verbose log

- osquery/tables/system/darwin/startup_items.cpp
We were not parsing system startup items.
> Include system startup items

- tools/provision/debian.sh
- tools/provision/files/debian/benchmark_traits_fix.patch
As above, just updating the scripts so that things build again with the recent changes in osquery.
> Build on debian wheezy with recent changes

- docs/wiki/installation/install-linux.md
> Use full key for apt

- docs/wiki/development/building.md
- tools/provision.sh
sudo is needed in order to do `make deps`.
> sudo added as requeriment

- tools/tests/utils.py
Replace comments inside of config file before execution to allow people to use profile.py without editing conf file.
> added comment parsing for profile.py

- README.md
Master builds have different jobs in Jenkins
> Updating status icons for master builds

- osquery/tables/system/linux/processes.cpp
Linux's `process_memory_map` needs some sanitization. Although these variances in procfs are not expected, we should handle unexpected data correctly.
> [Fix #1580] Handle exceptions in linux process_memory_map

- tools/deployment/com.facebook.osqueryd.plist
I haven't tested this yet, but it should work correctly. LaunchDaemons are weird.
> OSX Default Flags

- README.md
Stil a couple of references to the Package job in CI
> Removing link to Package CI job

- osquery/tables/system/shell_history.cpp
2nd time is the charm. I added the sh_histroy file to shell history.
> added sh_history

- include/osquery/events.h
- osquery/CMakeLists.txt
- osquery/core/hash.cpp
- osquery/core/system.cpp
- osquery/core/watcher.cpp
- osquery/database/tests/query_tests.cpp
- osquery/devtools/shell.cpp
- osquery/events/darwin/diskarbitration.cpp
- osquery/events/darwin/tests/fsevents_tests.cpp
- osquery/events/events.cpp
- osquery/events/linux/tests/inotify_tests.cpp
- osquery/filesystem/darwin/tests/plist_tests.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/kernel_info.cpp
- osquery/tables/system/darwin/keychain_acl.cpp
- osquery/tables/system/darwin/keychain_items.cpp
- osquery/tables/system/darwin/sysctl_utils.cpp
- osquery/tables/system/darwin/tests/apps_tests.cpp
- osquery/tables/system/darwin/tests/launchd_tests.cpp
> Fix clang warnings, promote warnings to errors

- osquery/extensions/interface.cpp
- osquery/extensions/interface.h
- osquery/remote/requests.h
- osquery/sql/sqlite_util.cpp
- tools/provision/lib.sh
A bit more ASAN on Linux, after this the entire test suite passes ASAN/LSAN without complaints for 3.7.
> Passing clang Address/Leak Sanitize version 3.7

- osquery/filesystem/filesystem.cpp
> [Fix #1634] Add sys/stat to filesystem

- osquery/logger/plugins/syslog.cpp
As discussed in https://github.com/facebook/osquery/pull/1212#issuecomment-155575626
> Removed result= in the Syslog plugin

- osquery/tables/system/authorized_keys.cpp
- specs/authorized_keys.table
2nd attempt at authorized keys table. Added comment ignoring and algorithm checking. Future work to be done is adding authorized_keys2 file and support for commands after successful login.
> added authorized_keys table

- osquery/tables/system/known_hosts.cpp
- specs/known_hosts.table
> Added known_hosts table

- osquery/tables/system/darwin/processes.cpp
- osquery/tables/system/linux/processes.cpp
- specs/processes.table
Not tested locally since I have no Mac machine, I put my faith in Jenkins.
> Add saved UIDs and GIDs to process table

- osquery/tables/system/darwin/homebrew_packages.cpp
> Determine Homebrew Cellar from binary

- osquery/tables/system/darwin/signature.mm
Clang analyze `make analyze` fired on an uninitialized value `staticCode` being passed to `SecStaticCodeCheckValidityWithErrors`. There are a few other OCD changes here and a `make format`.
> Fix clang analyze failures in signature table

- README.md
Add notes about the FIM/eventing capabilities and add a slack badge to the top.
> Update README with Slack badge

- packs/osx-attacks.conf
Added a new genieo query to the osx_attacks pack.
> adding genieo query

- osquery/sql/tests/virtual_table_tests.cpp
- osquery/sql/virtual_table.cpp
- osquery/sql/virtual_table.h
- tools/tests/test_additional.py
- tools/tests/test_base.py
This is part of a larger effort to fix the SQLite usage limitations identified in #1651.
> Fix constraints stacking

- tools/codegen/amalgamate.py
- tools/codegen/genapi.py
- tools/codegen/gentable.py
- tools/codegen/gentargets.py
- tools/formatting/git-clang-format.py
- tools/profile.py
- tools/tests/stress.py
- tools/tests/test_additional.py
- tools/tests/test_base.py
- tools/tests/test_example_queries.py
- tools/tests/test_extensions.py
- tools/tests/test_http_server.py
- tools/tests/test_modules.py
- tools/tests/test_osqueryd.py
- tools/tests/test_osqueryi.py
- tools/tests/test_release.py
- tools/tests/utils.py
Signed-off-by: Teddy Reed
Merge-conflicts-by: Teddy Reed
Closes: #1586
> PEP8 Compliance && Python 3.X compatibility

- osquery/config/plugins/tls.cpp
Passing a `shared_from_this` results in storage of a weak pointer.
> Fix quick regression with config refresh runner

- osquery/tables/events/linux/file_events.cpp
fixes #1720 and potentially future bugs of its sort
> DRY for inotify event mask (we missed IN_MOVE)

- include/osquery/core.h
- osquery/core/system.cpp
- osquery/core/watcher.cpp
- osquery/database/db_handle.cpp
- osquery/database/db_handle.h
- osquery/database/tests/db_handle_tests.cpp
- osquery/devtools/shell.cpp
- osquery/tables/forensic/sleuthkit.cpp
- tools/provision/fedora.sh
- tools/provision/lib.sh
1. Dumping config may rely on an extension, allow a worker to dump config and exit.
2. Although `dropTo` is not used consecutively, it should be safe from leaking if it ever is.
3. TSK partition iteration was not freeing the partition meta data.
> Various results from ASAN and LSAN

- README.md
> Fix osquery Slack invite link

- README.md
Updating README for OSX 10.11 and fixing build badge
> Updating README for OSX 10.11 and fixing build badge

- tools/deployment/osqueryctl
Honestly I got so frustrated with trying to squash #1754 that I decided to cut a new PR.
> As someone working on osquery with remote configuration I've been trying to use osqueryctl and hit a number of snags. This adds the ability to use osqueryctl if a valid osquery.flags file is found.
All in one commit even!
> modified osqueryctl for flags based deploys

- docs/wiki/deployment/debugging.md
- mkdocs.yml
In response to some of the common deployment gotchas, let's keep a curated list of debugging recommendations. This document intends to be a 'self-help' or first level of debugging todos and an outlet for describing common problems.
> Add deployment debugging wiki

- osquery/tables/system/darwin/sip_config.cpp
- specs/darwin/sip_config.table
This is still a work in progress, but I wanted to open it up for review, especially regarding the nomenclature and the table schema.
I would also like to report on SIP exceptions defined, but that probably is another table `sip_exceptions` perhaps?
> Report on System Integrity Protection

- osquery/tables/system/darwin/sip_config.cpp
1. If `csr-active-config` IOKit key is not found (or cleared by `csrutil clear`), it is the default case (i.e SIP is enabled) and should not be considered an error.
2. `efi` -> `nvram` variable name update
> SIP config: handle default case when IOKit key is not set

- osquery/sql/virtual_table.cpp
On OS X, when using an invalid column name in a query predicate the `xBestIndex` API is provided a `sqlite3_index_info` structure with an `nConstraint = 0`:
```cpp
(sqlite3_index_info) $0 = {
nConstraint = 0
aConstraint = 0x00000001038571e0
nOrderBy = 0
aOrderBy = 0x00000001038571e0
aConstraintUsage = 0x00000001038571e0
idxNum = 0
idxStr = 0x0000000000000000
needToFreeIdxStr = 0
orderByConsumed = 0
estimatedCost = 4.9999999999999998E+98
estimatedRows = 25
idxFlags = 0
colUsed = 131071
}
```
On Linux (tested with Ubuntu 14.04) `nConstraint = 1` and the first `sqlite3_index_constraint` structure has an `iColumn = -1`.
> Fix constraint index checking on Linux

- osquery/tables/system/darwin/smbios_tables.cpp
The IOKit name for OS X's platform info "rom@0" is not consistent across models. The registry's ID seems at least more stable.
> Use ROM iokit ID instead of name

- osquery/tables/system/darwin/smc_keys.cpp
- specs/darwin/temps.table
Extract temperature-related data from smc_keys table for table dedicated
to temperature sensors.
Resolves #1807
> add temperature sensors table

- osquery/tables/system/darwin/smbios_tables.cpp
Simplify the `platform_info` table on OS X again. The `/rom` path within `IODeviceTree` should catch all platforms.
> Use '/rom' path for OS X platform_info

- osquery/tables/system/darwin/smc_keys.cpp
Remove a few unnecessary temperature-related comments.
> remove some temp-related comments

- osquery/tables/system/darwin/smc_keys.cpp
- specs/darwin/fan_speeds.table
Add a fan_speeds table with each row containing attributes for a given
fan such as min, max, actual speed.
> add fan speeds table

- docs/wiki/deployment/extensions.md
- docs/wiki/development/osquery-sdk.md
Add an example use of extensions within the shell to complete #1810.
> [#1810] Minor changes to extensions-use docs

- osquery/tables/events/tests/file_events_tests.cpp
Fix for issue https://github.com/facebook/osquery/issues/1845
> Build fix for file_events_tests

- osquery/tables/system/darwin/smc_keys.cpp
Consolidate logic for returning a float given a smc type and value.
> consolidate smc hex val -> float conversion

- osquery/logger/plugins/tls.cpp
- osquery/remote/enroll/plugins/tls.cpp
- osquery/remote/transports/tls.cpp
- osquery/remote/utility.h
- tools/provision/lib.sh
This requires non-merged changes to cpp-netlib. This will fail to build.
> [Fix #1746] Add SNI options for TLS plugins

- tools/deployment/osquery.example.conf
> fix typo in config example

- osquery/tables/system/darwin/disk_encryption.cpp
1. Fix potential leak in `disk_encryption` when grabbing user UUID.
> Fix potential leak

- osquery/tables/system/user_groups.h
This fixes group lookups on OS X when a user is in more than 64 groups.
While the getgroupcount function is undocumented and not included in any headers, it has been exported from libSystem.B (via libsystem_info) since 10.6 and is used by the getgroups function, so it's very unlikely to disappear anytime soon.
> Darwin: Use undocumented getgroupcount() before getgrouplist

- include/osquery/hash.h
- include/osquery/status.h
- osquery/filesystem/filesystem.cpp
- osquery/sql/sqlite_util.h
- osquery/tables/applications/browser_utils.h
- osquery/tables/events/event_utils.h
- osquery/tables/forensic/sleuthkit.cpp
- osquery/tables/networking/utils.cpp
- osquery/tables/system/darwin/iokit_utils.h
- osquery/tables/system/darwin/keychain.h
- osquery/tables/system/efi_misc.h
- osquery/tables/system/smbios_utils.h
- osquery/tables/system/sysctl_utils.h
- osquery/tables/system/system_utils.h
- osquery/tables/system/user_groups.h
Minor code cleanups. Expect no functional changes.
> Fix various lint issues

- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/database/plugins/rocksdb.cpp
- osquery/tables/CMakeLists.txt
- tools/deployment/make_linux_package.sh
- tools/provision.sh
- tools/provision/amazon.sh
- tools/provision/debian.sh
- tools/provision/lib.sh
- tools/provision/ubuntu.sh
Gate "additional" (non-core) tests and all benchmarks from the `make sdk` target.
> [Fix #1896] Gate additional and kernel tests/benchmarks

- osquery/events/events.cpp
- osquery/events/tests/events_database_tests.cpp
Records that should be expired "within" a binning were not being removed.
> Expire data when record is before expire time

- docs/wiki/deployment/configuration.md
- docs/wiki/development/creating-tables.md
- docs/wiki/development/pubsub-framework.md
- osquery/core/conversions.h
- Minor fix in creating tables documentation
- Fix docs for join
- Add note about config paths
- Update events docs
- Fix link to query packs
> Collection of doc fixes

- packs/osx-attacks.conf
• Added additional checks for Vsearch
• Added detection for PremiereOpinion, Bundlore, Spigot, and SearchInstUpdater
> Adding detection for new adware variants to osx-attacks

- osquery/tables/system/darwin/tests/asl_tests.cpp
Previously, this test relied on there being console messages available
to query for. Now, it actually writes a message to ASL, then verifies
that the message can be found. It also exercises a more complicated
query than previously.
Fixes issue #1975
> Update flaky test for ASL table

- tools/provision/debian.sh
> Merge missing package dependencies for Debian wheezy

- osquery/dispatcher/tests/scheduler_tests.cpp
Enhance the safety of the scheduler and config interaction. This test will run several queries with a second interval for a second, using the `SchedulerRunner` facility.
> Add test for SchedulerRunner

- kernel/src/osquery.cpp
> Corrected typo in OS X kernel extension debug output

- packs/osx-attacks.conf
Common off-the-shelf keylogger popular on OSX
> Adding Elite Keylogger Detection to osx-attacks

- include/osquery/dispatcher.h
- osquery/logger/plugins/buffered.cpp
- osquery/logger/plugins/buffered.h
- osquery/logger/plugins/tests/buffered_tests.cpp
- osquery/logger/plugins/tests/tls_logger_tests.cpp
- osquery/logger/plugins/tls.cpp
- osquery/logger/plugins/tls.h
`BufferedLogForwarder` is a base class for external log forwarding schemes
that require buffering and retries. It generalizes the logic from the
existing `TLSLogForwarderRunner`.
The existing `TLSLoggerPlugin` and `TLSLogForwarderRunner` are refactored to
demonstrate the use of this new base class.
> Introduce BufferedLogForwarder

- CMake/CMakeLibs.cmake
- CMake/FindGtest.cmake
- CMakeLists.txt
- osquery/CMakeLists.txt
- osquery/core/CMakeLists.txt
- osquery/core/posix/process.cpp
- osquery/core/posix/process_ops.cpp
- osquery/core/process.h
- osquery/core/process_shared.cpp
- osquery/core/test_util.h
- osquery/core/testing.h
- osquery/core/tests/process_tests.cpp
- osquery/core/windows/process.cpp
- osquery/core/windows/process_ops.cpp
- osquery/main/tests.cpp
This is the first in a series of pull requests for process abstraction.
This pull request commits all of the process abstraction code with no integration with the current osquery build system.
> Process Operations - Pure Process Abstraction

- Vagrantfile
- tools/provision/ubuntu.sh
Small additions to support building on Ubuntu 14.04
> Add Ubuntu Xenial 16.04 build support

- docs/wiki/deployment/remote.md
This PR provides a blurb about [Doorman](https://github.com/mwielgoszewski/doorman), a project I started to help manage my own osquery fleet.
> Update to TLS remote settings example projects

- tools/provision/ubuntu.sh
> Fix Ubuntu 15.04 build

- CMakeLists.txt
- osquery/logger/CMakeLists.txt
> Disable Google Benchmark and AWS SDK from build

- osquery/sql/CMakeLists.txt
- osquery/sql/sqlite_math.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
Add:
```
pow(2, 16);
ceil(9.8);
floor(9.8);
degrees(3.4);
radians(180);
pi();
sqrt(10);
exp(2);
log(90);
log10(90);
```
And a suite of additional trig functions: `sin`, `cos`, `tan`, `cot`, `asin`, `acos`, `atan`.
> Add basic math extension functions

- README.md
- docs/wiki/installation/install-linux.md
- Add a build badge for Ubuntu16.
- Update the wiki to include Ubuntu 16.04 LTS references.
> [#2086] Update README/wiki for Ubuntu 16.04

- tools/get_platform.py
Imported `__future__` libraries and changed the print's to contain parens. Also removed some spacing.
> Updated the get_platform.py script to be Python 3 compatible

- tools/get_platform.py
- tools/provision/scientific.sh
This fixes SL build support after a recent build tooling update.
> Fix Scientific Linux build process

- tools/get_platform.py
Adding an except clause for when lsb_release is not present.  Addresses #2136
> Added except for lsb_release not existing on system

- osquery/CMakeLists.txt
- osquery/filesystem/fileops.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
- osquery/filesystem/windows/fileops.cpp
- Integrated filesystem operation abstraction code into filesystem.cpp
- Modified filesystem unit tests to be more platform agnostic
Closes #2002 
Closes #2000 
Closes #1999 
Closes #1997 
Closes #1996
> Filesystem Abstractions - Integrations

- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
Changed AWS logger stream validation from list streams to describe streams as resticted aws roles are likely to have describe permissions instead of list permissions
> Changed stream validation from list streams to describe streams

- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/windows/fileops.cpp
This PR is intended to fix issues in #2165
Closes #2165
> Bugfix for #2165

- docs/wiki/development/building.md
remove a duplicate word "take".
take take a look at -> take a look at
> fix a typo error on the doc for building

- tools/provision/formula/aws-sdk-cpp.rb
> Bump AWS SDK to 0.12.17

- packs/osx-attacks.conf
Infection by iWorm can also be detected by the directory it creates. More info here https://www.virusbulletin.com/virusbulletin/2014/10/invading-core-iworm-s-infection-vector-and-persistence-mechanism
> Adding folder signature for iWorm OSX malware

- packs/osx-attacks.conf
update based on this blog post:
https://blog.malwarebytes.com/cybercrime/2016/07/new-mac-backdoor-malware-eleanor/
> update osx_attacks with Backdoor.MAC.Eleanor with fixes

- osquery/filesystem/filesystem.cpp
The conditional:
```
if (home_directory.is_initialized() && isWritable(*home_directory).ok())
```
Was checking the writability of the user's home directory, not the permissions of the "osquery" home directory.
This also allows multiple shells to use temp-home-directories concurrently.
> [Fix #2196] Fix osquery home directory checking

- osquery/tables/system/linux/processes.cpp
This commit fixes two issues with `path` in the linux processes table:
(1) Fixes a bug in which `on_disk` is set to `NULL` instead of `0` when the
binary is not on disk.
(2) Fixes a bug in which a filename ending in ` (deleted)` could cause osquery
to return an incorrect value for `on_disk`. See
https://github.com/facebook/osquery/issues/1607
> Fix process path parsing

- osquery/config/parsers/decorators.cpp
- osquery/config/parsers/decorators.h
- osquery/core/hash.cpp
- osquery/core/posix/process.cpp
- osquery/core/posix/process_ops.cpp
- osquery/core/process.h
- osquery/core/system.cpp
- osquery/events/linux/syslog.cpp
- osquery/events/linux/syslog.h
- osquery/filesystem/fileops.h
- osquery/filesystem/posix/fileops.cpp
- osquery/filesystem/windows/fileops.cpp
- osquery/logger/plugins/aws_util.h
- osquery/logger/plugins/buffered.h
- osquery/tables/system/centos/rpm_packages.cpp
- osquery/tables/system/darwin/tests/signature_tests.mm
- osquery/tables/system/linux/disk_encryption.cpp
- osquery/tables/utility/time.cpp
Several fixups, applying code lints and C++ best practices.
- Include guards
- Header non-POD moves
- `std::` suggested API usages
- Linting and grammar fixes
- Thread safe time functions
> Various fixups and best practices

- .gitignore
Minor updates to help the Window10 build.
> Update third-party for Win10 building and add .patch to gitignore

- osquery/tables/system/ssh_keys.cpp
- specs/posix/ssh_keys.table
Added a new table for tracking id_rsa file. I'm new to contributing to open source software and I tried to follow the contribution guide as closely as possible. So let me know if there is anything I need to add or change.
> added ssh_keys table for id_rsa files.

- tools/deployment/make_linux_package.sh
- tools/provision.sh
- tools/provision/debian.sh
- tools/provision/lib.sh
- tools/provision/ubuntu.sh
Fixes Debian naming convention compliance and a number of failures during package building process.
> Ubuntu + Debian build fixes (#2247)

- CMake/Packages.cmake
- CMakeLists.txt
- docs/wiki/development/kernel.md
- kernel/CMakeLists.txt
- tools/lib.sh
> Fix debug-kernel build and deploy dependencies

- docs/wiki/introduction/using-osqueryi.md
> Clarify events and database flags in osqueryi docs

- include/osquery/core.h
- osquery/config/plugins/filesystem.cpp
- osquery/core/init.cpp
> Move OSQUERY_HOME into core and use as filesystem config default

- include/osquery/core.h
- include/osquery/system.h
- osquery/core/init.cpp
- osquery/core/process.h
- osquery/core/system.cpp
- osquery/core/windows/process.cpp
- osquery/database/database.cpp
- osquery/extensions/extensions.cpp
- osquery/logger/plugins/filesystem.cpp
- osquery/main/windows/daemon.cpp
- osquery/tables/system/windows/processes.cpp
- osquery/tables/system/windows/system_util.cpp
- tools/manage-osqueryd.ps1
This PR contains numerous changes to osquery to begin support for building `osqueryd.exe` as a Windows service.
> Changes to support building a osquery Windows service.

- osquery/tables/utility/file.cpp
1. Skip `lstat` checking on Windows.
2. Set `btime` (birth) to 0 for now on Windows.
3. Skip `block_size` and `hard_links` on Windows.
> Port utilities/file to Windows

- CMakeLists.txt
- requirements.txt
- tools/lib.sh
> Add wiki build to `make docs` and verify in CI

- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/buffered.cpp
- osquery/logger/plugins/buffered.h
- osquery/logger/plugins/tests/buffered_tests.cpp
- osquery/logger/plugins/tests/tls_logger_tests.cpp
> Add release valve for purging buffered logs in BufferedLogForwarder

- include/osquery/filesystem.h
- include/osquery/system.h
- osquery/core/init.cpp
- osquery/core/process.h
- osquery/core/system.cpp
- osquery/core/windows/process.cpp
- osquery/extensions/extensions.cpp
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/windows/fileops.cpp
> Changes to make pidfile work on Windows

- tools/tests/test_osqueryd_win.py
Windows specific tests for `osqueryd`
Closes #1993 
Closes #2008
> Test for Windows osquery daemon

- tools/provision/debian.sh
> Fixed typo in debian provision script

- tools/deployment/osqueryctl
A small refactor for `osqueryctl`.
> Enforce config-check for start command

- tools/deployment/osqueryctl
Quick fix for Issue 2262 under OS X, please bear with me, it's my first time using git and GitHub (and I'm not even a devel).
> Fix for Issue #2262

- tools/make-win64-dev-env.bat
Check return code from the provision script and error if it errored.
Should close #2292
> Windows: Error if provisioning fails

- CMakeLists.txt
- tools/provision.ps1
This PR will contain changes needed to make provisioning script work better on Jenkins
> Changes to support new boost-msvc14 package

- CMakeLists.txt
- Doxyfile
- Makefile
- tools/profile.py
- tools/tests/test_base.py
- tools/tests/test_extensions.py
- tools/tests/utils.py
Simple fixups, attempting to stabilize flaky tests.
> Ignore errors within testing for rmtree

- osquery/main/shell.cpp
https://github.com/facebook/osquery/issues/2351
> Change second FLAGS_pofile_delay to seconds

- osquery/events/linux/tests/syslog_tests.cpp
> Remove several raw strings that confuse static analysis

- docs/wiki/deployment/aws-logging.md
- osquery/logger/CMakeLists.txt
- osquery/logger/plugins/aws_util.cpp
- osquery/logger/plugins/aws_util.h
- osquery/logger/plugins/tests/aws_util_tests.cpp
- tools/provision/formula/aws-sdk-cpp.rb
> Add AWS STS assume role authentication capability

- include/osquery/filesystem.h
- osquery/filesystem/filesystem.cpp
- tools/audit.sh
Add getSystemRoot fn to filesystem. Also ran clang format on filesystem.
> Adding getSystemRoot function and FS Formatting

- osquery/tables/applications/posix/carbon_black.cpp
- osquery/tables/applications/windows/carbon_black.cpp
- specs/cb_info.table
* use getSystemRoot to get windows dir
* fix compile warnings
* update documentation
* replace %20 with space in sensor group
> minor fixes to cb_info table

- osquery/core/flags.cpp
> Display flags in alphabetical order

- include/osquery/distributed.h
- osquery/distributed/distributed.cpp
- osquery/distributed/plugins/tls.cpp
- osquery/remote/enroll/plugins/tls.cpp
- osquery/remote/transports/tls.cpp
- osquery/remote/utility.h
> Increase TLS client timeout from 4s to 16s

- osquery/remote/transports/tls.cpp
We're no longer supporting multiple OpenSSL and cpp-netlib versions. Let's remove the preprocessor defines.
> Remove OpenSSL and cpp-netlib old version exceptions

- tools/deployment/make_linux_package.sh
Corrects reference to example config in Linux package script.
> Corrects Linux package script reference

- osquery/tables/system/windows/registry.cpp
> Fixed bug in MULTI_SZ processing

- osquery/sql/virtual_table.cpp
Addresses #2402, if `*_events` tables are used and events are not enabled the shell will receive a notice to read the relative table specification. Both the shell and the daemon will receive a note that events are not enabled.
> Add warning for event-based table without events

- osquery/core/conversions.h
- osquery/dispatcher/distributed.cpp
- osquery/distributed/distributed.cpp
- tools/tests/test_http_server.py
Added a setting allowing the server to request that osquery checkin every 5 seconds for a length of time that it specifies.
> Accelerated checkins

- CMake/Packages.cmake
- osquery/CMakeLists.txt
- tools/deployment/make_linux_package.sh
This removes all of the dependencies we now package/build statically... from the package definition.
> [#2462] Limit Linux package dependencies

- docs/wiki/deployment/configuration.md
> Remove errant comma in example config JSON

- osquery/main/windows/daemon.cpp
The `--install` flag will now only create the service in the Windows Service Manager. Should users so desire they can start the service using the windows `net` or `sc` command, but starting the service alongside the install seemed excessive.
> Removing service start functionality

- tools/provision.ps1
> Fixing powershell linting warnings

- tools/deployment/make_linux_package.sh
Similar to post-install scripts, these scripts will let use add `service
stop` and remove stuff from autostart before removing files.
> Add support for pre-uninstall scripts at package creation

- tools/provision/formula/asio.rb
- tools/provision/formula/libgpg-error.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/thrift.rb
- tools/provision/formula/zlib-legacy.rb
Update bottles for several Linux dependencies.
> Update bottles: asio, libgpg-error, openssl, thrift, zlib

- osquery/tables/system/posix/crontab.cpp
> Extended crontab table to support files in /etc/cron.d/

- osquery/core/system.cpp
We are now preferring the hardware UUID within `getHostUUID`. The next version intends to invalidate the UUID generation cache for all Linux hosts. OS X will continue to use the hardware UUID or generate a new ephemeral UUID if it was unavailable.
Here are the scenarios/expectations:
1. OS X will experience no change in almost all cases.
2. OS X in the exceptional case will generate a new UUID.
3. Linux will generate a new UUID.
> Promote host UUID to version 2

- specs/windows/programs.table
This fixes incorrect file naming for the programs table.
> Rename programs table to correct file name

- docs/wiki/deployment/syslog.md
- docs/wiki/installation/cli-flags.md
- osquery/events/events.cpp
- osquery/events/linux/syslog.cpp
See issue #2542 for the 'problem' statement. This should provide slight performance improvements for default Linux deployments.
> [#2542] Introduce --enable_syslog to explicit enable syslog ingestion

- tools/provision/formula/yara.rb
I had to add new pull patch because they the yara guys introduced another redeclaration bug. I have already filed a PR for this but until the next release comes out, I will have to leave it there. This PR addresses issue #2546.
> Update yara to version 3.5.0 (#2546)

- osquery/devtools/shell.cpp
> Fix memory leak at osquery/devtools/shell.cpp

- osquery/tables/system/tests/system_tables_tests.cpp
Assure new platforms include a `total_size` and `resident_size` for memory reporting in bytes units. Assure new platforms include a `user_time` and `system_time` to report CPU cycles uses in seconds units.
> Add test for processes table to verify mem/cpu units

- tools/deployment/make_linux_package.sh
Fixes #2547 
Example package names:
osquery-1.8.2-166-gb895c6a-1.el7.x86_64.rpm  
osquery-debuginfo-1.8.2-166-gb895c6a-1.el7.x86_64.rpm
osquery_1.8.2-166-gb895c6a_amd64.deb  
osquery-dbg_1.8.2-166-gb895c6a_amd64.deb
> RPM packages now follow the form name-version-rev.platform.arch.rpm

- specs/windows/wmi_cli_event_consumers.table
- specs/windows/wmi_script_event_consumers.table
Update example queries with correct columns
> Update example queries with correct columns

- osquery/extensions/extensions.cpp
Adding a small line to fix an issues with a distributed query plugin
> Set active distributed plugin within extensions

- osquery/devtools/shell.cpp
This adds `.features` and `.summary` to the shell to help folks with state debugging.
> Add .features and .summary meta commands

- osquery/tables/system/windows/drivers.cpp
- specs/windows/drivers.table
- Name
- Display Name
- Status
- Start type
- path
- Driver type
- inf file
> Add virtual table: Windows Drivers

- kernel/CMakeLists.txt
Added a check and information about Kext Dev Mode and SIP to the Kernel CMake
> [Fix #2696] Kext Dev Mode Check

- osquery/tables/system/cpuid.cpp
This fixes the `hypervisor_id` value by emitting a hex value string instead of attempting to convert to ASCII. it also adds the `sgx` available bit and two "most popular" leaf-feature bits. The `sgx0`'s `eax` output determines if SGX is currently enabled.
> Add SGX CPU feature and availability detection to cpuid

- osquery/tables/CMakeLists.txt
- osquery/tables/system/posix/augeas.cpp
- osquery/tables/system/posix/tests/augeas_tests.cpp
- specs/posix/augeas.table
- tools/provision.sh
- tools/provision/amazon.sh
- tools/provision/formula/augeas.rb
- tools/provision/formula/libxml2.rb
This is not ready yet but I'd like to see where it doesn't build yet.
What's still missing:
> Added the Augeas table

- tools/provision.ps1
The difference between a normal "Windows dev-kit" and the osquery build host intensifies.
> deps: windows: Skip clang-format on build hosts

- osquery/filesystem/tests/fileops_tests.cpp
Currently, the last two tests (platformAccess() & platformFopen()) fail if the test is run as root. I'm looking into this at the moment, but the rest functions as expected.
On a related note, running "make test" as root causes approx. half of the test suites to fail (on Ubuntu 16.04). Are the tests supposed to pass when run as root (in which case I'll file an Issue for it)? Or are they only intended for regular users (in which case I'll leave this Commit as is)?
> [Fix #2175] New test: zero permission file operations

- packs/osx-attacks.conf
Some ocean lotus sigs from alien vault
https://www.alienvault.com/blogs/labs-research/oceanlotus-for-os-x-an-application-bundle-pretending-to-be-an-adobe-flash-update
> Add ocean lotus

- tools/lib.sh
This is a very simple addition to `./tools/build.sh`, which is the entry point for several CI tests.
The goal is to provide a:
```
RUN_DETERMINISTIC=1 RUN_TARGET=daemon ./tools/build.sh
```
The `daemon` CMake target will be built twice and the SHA256 of the binary post-`strip` will be compared. If the hashes vary the script will exit non-0.
> Add RUN_DETERMINISTIC test to build.sh

- osquery/events/linux/audit.cpp
This "imports" the `audit_get_reply` library logic as `safe_audit_get_reply` that implements a `select` instead of a block/non-block choice. The existing method does not reveal details about the state of the Netlink queue. When using a read-select we can choose to pause the thread if the queue was empty. If the queue is filled the thread will dequeue as fast as possible.
It is also safe to implement audit rate limits at the consequence of losing data, but maintaining queue performance.
Consider the follow test program:
```python
#!/usr/bin/env python
import subprocess
import sys
NUM = 8
P = 3298723423324
def largest_prime_factor(n):
i = 2
while i * i <= n:
if n % i:
i += 1
else:
n //= i
return n
j = 0
if len(sys.argv) != 1:
j = int(sys.argv[1])
if j > NUM:
largest_prime_factor(P)
exit(0) …
```
> Improve process_events on Linux

- osquery/tables/CMakeLists.txt
- osquery/tables/networking/darwin/wifi.mm
- osquery/tables/networking/darwin/wifi_status.mm
- osquery/tables/networking/darwin/wifi_utils.h
- osquery/tables/networking/darwin/wifi_utils.mm
- specs/darwin/wifi_status.table
A simple table using CoreWLAN to get the status of all wifi interfaces. Also refactored out extractSsid because both wifi_networks and wifi_status need it.
> Adding a table for currently connected WiFi information

- osquery/core/system.cpp
- osquery/core/tests/posix/permissions_tests.cpp
When we use `seteuid` and `setegid` it sets the effective credentials for all threads. We are using this temporary credential drop for safety and not trying to protect against exploitation to increase privilege.
> Use syscalls for dropping effective gid/uid on POSIX

- osquery/sql/sqlite_util.cpp
This also added the `--nullvalue` content to the result of internal / non-shell query outputs.
> [#2809] Emit verbose warning on column collisions

- README.md
> clearer statement about getting started when building from source

- osquery/devtools/shell.cpp
We've been ignoring this for a while with suppressions. Since we're no longer merging in changes from the SQLite shell, we should port pointer comparisons and reduce the number of compile/run ASAN, LSAN, TSAN suppressions for the shell.
> Fix innocuous memory leak when exiting osqueryi

- packs/osx-attacks.conf
> fix comma in osx attack pack

- tools/provision.ps1
I'm currently YOLO testing this <3
> Adding helpers to add/remove to/from Windows PATH

- tools/provision/formula/gflags.rb
- tools/provision/formula/glog.rb
- tools/provision/formula/libaptpkg.rb
- tools/provision/formula/libmagic.rb
- tools/provision/formula/rocksdb.rb
- tools/provision/formula/zzuf.rb
Regularly scheduled bottle builds.
> Update bottles: gflags, glog, libmagic, libaptpkg, rocksdb, zzuf

- osquery/extensions/extensions.cpp
- tools/tests/test_extensions.py
We now support directories in `--extensions_autoload`.
> Allow autoload paths to include directories

- osquery/tables/system/linux/processes.cpp
There are no changes or fixes here, this is intended as a code-cleanup to make the `processes` table a bit easier to read. It uses an early-return flow for determining the `on_disk` state now. There may be some performance improvement over time as a potentially large `SimpleProcStat` will never be copied now, AFAIK this would be optimized out by the compiler anyhow.
> [#2849] Linux processes table cleanup

- osquery/tables/system/linux/apt_sources.cpp
The `_system` global is not initialized on non-APT systems.
> [Fix #2874] Check apt_sources resource initialization

- osquery/logger/plugins/aws_kinesis.cpp
New information from AWS indicates that throughput will be maximized if each
record in a batch request has a different partition key. Previously we were
generating one random key for each batch.
> Generate random Kinesis partition keys per-record

- docs/wiki/development/building.md
- tools/provision.sh
This is a small change to documentation. It provides a small outline for dependency updates and bottle builds.
> Documentation and steps for dependency bottles

- osquery/tables/system/darwin/homebrew_packages.cpp
> homebrew_packages: Search above Homebrew for Cellars

- osquery/config/config.cpp
While the TSAN Linux job is NOT flagging this as a critical section, it seems likely.
> config: Add schedule lock during source update

- tools/provision/formula/llvm.rb
> Add bottle for Linux LLVM 3.8 revision 2

- packs/osx-attacks.conf
Figured folks might want to know about malware on their macs within the hour instead of within the day :)
> Updating the interval on osx-attacks to check hourly instead of daily

- osquery/database/plugins/rocksdb.cpp
This PR adds code to repair (or, in the case of ROCKSDB_LITE, delete) a corrupted db if one is encountered on startup.
On some testing we have done with OSX, we see regular occurrence of rocksdb database getting corrupted. The problem is, at that point, osquery itself is hosed - it won't restart until someone manually deletes the rocksdb database. 
While it's hard to generalize what's causing the corruption, in a few instances, we did catch this error:
I1214 10:05:25.787860 1064960 rocksdb.cpp:133] RocksDB: [ERROR] [events] [JOB 84] OpenCompactionOutputFiles for table #36365 fails at NewWritableFile with status IO error: /var/osquery/osquery.db/036365.sst: Permission denied
I1214 10:05:25.788249 1064960 rocksdb.cpp:133] RocksDB: [WARN] Compaction error: IO error: …
> Handle corrupted rocksdb database

- CMakeLists.txt
- osquery/CMakeLists.txt
> Add externals subdirectory within osquery subdirectory

- osquery/tables/system/linux/processes.cpp
This is a minor step in addressing #2873. If the osquery process cannot read a process's `/proc/N/stat` or `/proc/N/status` then the details from a partial scan are mostly useless.
> Address the invalid uid for Linux processes

- docs/wiki/deployment/log-aggregation.md
The plugin has changed its name and settings
> Update of elasticsearch output plugin

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
- tools/deployment/make_windows_package.ps1
> Bundling example conf, packs, and certs.pem in choco package

- osquery/events/darwin/fsevents.cpp
The `FSEvents` publisher includes some unprotected uses of the run loop.
> events: Fix locking around FSEvents

- osquery/events/events.cpp
The sanitize-thread builds detect critical sections when running Python's `example_queries`. These additional locks protect the names and publisher/subscriber members.
> events: Add locks around publisher and subscriber name accesses

- osquery/tables/applications/posix/carbon_black.cpp
There was no exception catching/handling on parsing the carbon black settings file (ini file). So a malformed file was crashing osquery with the following message:
```
$ sudo ./build/darwin/osquery/osqueryi --verbose "select * from carbon_black_info"
I0206 14:33:15.299680 2749072320 init.cpp:364] osquery initialized [version=2.1.0-2-ged13157]
I0206 14:33:15.300122 2749072320 extensions.cpp:351] Could not autoload extensions: Failed reading: /var/osquery/extensions.load
I0206 14:33:15.300148 2749072320 extensions.cpp:364] Could not autoload modules: Failed reading: /var/osquery/modules.load
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::ini_parser::ini_parser_error> >: …
```
> Catch exception when parsing POSIX carbon black ini/settings file

- docs/wiki/installation/install-osx.md
There are known issues with symbol resolution for 10.10 (https://github.com/facebook/osquery/issues/2988).
> docs: Only support OS X 10.11 and 10.12

- docs/wiki/development/windows-provisioning.md
Documentation Improvement for windows
> [Fix #3028] Updated windows provisioning doc to clarify build location 

- tools/tests/test_http_server.py
For the upcoming file carving functionality of osquery, the test server needed to be updated to handle receiving files from the client.
> Adding support to the test server to receive carved files

- docs/wiki/deployment/file-integrity-monitoring.md
I personally had a lot of confusion while reading this page when it came to understanding how FIM gets enabled and how to enable access monitoring in the config. I think these edits help clear some of that up.
> Updating FIM docs page

- osquery/tables/system/linux/os_version.cpp
> Fix platform detection in os_version table on CentOS6

- tools/provision.sh
- tools/provision/formula/lldpd.rb
Build and install LLDPD using the osquery-provided formula.
> deps: Use local LLDPD formula

- docs/wiki/installation/cli-flags.md
- osquery/core/watcher.cpp
> watcher: Set default memory limit to 200M

- osquery/tables/system/hash.cpp
Really unsure why this PR closed on my push, but this should be good now.
> [Fix #3080] Adding a warning when read surpasses limits in hash table

- specs/windows/windows_events.table
"registry hives" was probably copied from different section of this project
> Minor description correction

- osquery/tables/system/linux/pci_devices.cpp
Working something that utilizes pci_devices, I noticed that the pointers from libudev were not wrapped in smart pointers so I added that.  From my previous PRs, I got the impression that we should check do an explicit check for `nullptr` for validation so I did not utilize `std::unique_ptr::operator bool`.
> pci_devices: unique_ptr wrapper for udev pointers

- tools/provision.sh
- tools/provision/formula/boost.rb
- tools/provision/formula/lldpd.rb
- tools/provision/formula/rocksdb.rb
Update deps on Linux and Darwin to new bottles.
> bottles: RocksDB 5, Boost 1.63r7, LLDPD

- osquery/tables/system/posix/python_packages.cpp
This builds on to the `python_packages` virtual table to scan macOS Python Framework directories for additional packages.
> tables: Add macOS python2.7 frameworks

- tools/provision/lib.sh
This resolves https://github.com/Linuxbrew/brew/issues/315
> deps: Patch to resolve rack aliases on Linux

- osquery/logger/plugins/aws_firehose.cpp
- osquery/logger/plugins/aws_firehose.h
- osquery/logger/plugins/aws_kinesis.cpp
- osquery/logger/plugins/aws_kinesis.h
- osquery/logger/plugins/aws_util.cpp
- osquery/logger/plugins/aws_util.h
- osquery/logger/plugins/tests/aws_firehose_tests.cpp
- osquery/logger/plugins/tests/aws_kinesis_tests.cpp
- osquery/logger/plugins/tests/aws_util_tests.cpp
The Kinesis/Firehose logger plugin can now send status logs.
Closes #3077
> Adding Status Logging to AWS Kinesis/Firehose Logger Plugins

- include/osquery/logger.h
- osquery/database/database.cpp
- osquery/database/plugins/rocksdb.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/logger/logger.cpp
- osquery/logger/tests/logger_tests.cpp
This is an attempt to fix https://github.com/facebook/osquery/issues/3119
> logging: Allow Glog reentrancy

- osquery/extensions/extensions.cpp
- osquery/extensions/interface.h
Minor clean ups for the extensions code to protect against mistakes going forward.
> extensions: Improve extensions and interface headers

- osquery/events/linux/audit.cpp
- osquery/events/linux/udev.cpp
This fixes a bug we introduced with `::select` without checking the value of the FD. If the value is over 1024 then we will corrupt the stack of the run loops for `udev` and `audit`.
> events: Use poll instead of select for audit and udev

- osquery/tables/system/windows/appcompat_shims.cpp
This adds checks for keys as well as bounds checks for substr usage. I'll add a test plan after creating some garbage registry values and ensuring this table handles them appropriately.
> Adding bounds checks and key checks for appcompat shims table

- include/osquery/database.h
- include/osquery/system.h
- osquery/core/init.cpp
- osquery/database/database.cpp
Hello guys!
bumped into #3114 issue.
Made a fix as described in the ticket.
Not sure about the right strategy for the # of retries and delay between them. Set to 3 retries with 5 seconds delay in-between.
If that should be resolved in a different way or needs any other changes, let me know.
Please review!
Thank you,
Grigoriy
> Add database init retry

- osquery/database/database.cpp
Avoid holding the database reset mutex while setting an active database plugin.
> database: Fix TSAN-detected reset lock inversion

- osquery/database/database.cpp
- osquery/database/tests/plugin_tests.cpp
The DB reset locking does not protect the database plugin from extensions requesting a reset.
> database: Move r/w reset lock for extensions

- docs/wiki/deployment/syslog.md
Update syslog.md with syslog-ng information based on my blog:
https://www.balabit.com/blog/endpoint-visibility-and-monitoring-using-osquery-and-syslog-ng/
> Update syslog.md with syslog-ng information

- osquery/tables/system/windows/registry.cpp
> [Fix 3249] Addressing permissive build fail

- osquery/tables/networking/windows/routes.cpp
This should fix #3257 by using the interface's reported gateway if it is available:
```shell
osquery> select * from routes;
+---------------------------+---------+-----------------+--------+-------+---------------+------+--------+--------+
| destination               | netmask | gateway         | source | flags | interface     | mtu  | metric | type   |
+---------------------------+---------+-----------------+--------+-------+---------------+------+--------+--------+
| 0.0.0.0                   | 0       | 192.168.1.1     |        | -1    | 192.168.1.4   | 1500 | 35     | remote |
| 0.0.0.0                   | 0       | 172.30.0.1      |        | -1    | 172.30.102.83 | 1350 | 2      | remote |
| 127.0.0.0                 | 8       | 127.0.0.0       |        | -1    | 127.0.0.1     | …
```
> [fix #3257] report proper routes for 0.0.0.0

- osquery/tables/system/windows/services.cpp
The original commit did not specify custom deleters for these std::unique_ptrs, which means the default deleter will be called (i.e. delete or delete[]). This is bad, since I'm creating these pointers with a malloc() and not a new(), which means the reuslt of a delete on the pointer is undefined.
Fixing this up to use a custom deleter that calls free() instead of delete.
> Fix undefined deleters with unique_ptrs in Windows Services table

- osquery/CMakeLists.txt
Removing permissive builds for posix, I misunderstood how builds work :P
> Removing permissive builds on posix

- osquery/logger/logger.cpp
- osquery/logger/plugins/tests/filesystem_logger_tests.cpp
- osquery/logger/tests/logger_tests.cpp
> logger: Relay status logs to the enabled log sinks

- osquery/database/database.cpp
@theopolis There is still one more issue that is causing crashes. Thanks for your earlier fix.
> kDBInitialized should be checked after acquiring lock.

- osquery/core/conversions.cpp
- osquery/sql/CMakeLists.txt
- osquery/sql/sqlite_encoding.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
Also make decodeBase64 safe from an unhandled exception
> Add base64 encode and decoding functions

- osquery/tables/networking/windows/routes.cpp
The IPv6 `metric`s weren't displaying properly with what is in `route print -6`
```shell
PS C:\Users\svmastersamurai> C:\programdata\osquery\osqueryi.exe "select * from routes where gateway = '::';"
+---------------------------+---------+---------+--------+-------+-----------+------+--------+-------+
| destination               | netmask | gateway | source | flags | interface | mtu  | metric | type  |
+---------------------------+---------+---------+--------+-------+-----------+------+--------+-------+
| ::                        | 0       | ::      |        | -1    |           | 1400 | 2      | local |
| ::1                       | 128     | ::      |        | -1    |           |      | 331    | local |
| 2620:10d:c081:1110::      | 64      | ::      |        | -1    |           | 1400 | …
```
> [windows] refactor routes to properly display metrics and mtus

- specs/carbon_black_info.table
- specs/carves.table
- specs/darwin/app_schemes.table
- specs/darwin/asl.table
- specs/darwin/crashes.table
- specs/darwin/event_taps.table
- specs/darwin/extended_attributes.table
- specs/darwin/kernel_panics.table
- specs/darwin/keychain_items.table
- specs/darwin/quicklook_cache.table
- specs/darwin/sip_config.table
- specs/darwin/time_machine_backups.table
- specs/darwin/time_machine_destinations.table
- specs/darwin/wifi_scan.table
- specs/darwin/wifi_status.table
- specs/linux/memory_info.table
- specs/linux/portage_packages.table
- specs/posix/disk_encryption.table
- specs/posix/dns_resolvers.table
- specs/posix/user_ssh_keys.table
- specs/windows/appcompat_shims.table
- specs/windows/drivers.table
- specs/windows/scheduled_tasks.table
- specs/windows/services.table
- specs/windows/shared_resources.table
- specs/windows/wmi_cli_event_consumers.table
- specs/windows/wmi_event_filters.table
- specs/windows/wmi_script_event_consumers.table
- tools/codegen/gentable.py
There are also a couple mistakes in the descriptions or example queries that were fixed.
> Make all descriptions use periods consistently.

- tools/provision.ps1
- tools/provision/chocolatey/thrift-dev.ps1
Bumping thrift-dev to contain package which has Thrift compiler, and provisioning on windows now installs flex and bison.
> deps: Adding thrift compiler build and deploy logic

- include/osquery/core.h
Necessary to chase the yara path change.
> Set some paths for FreeBSD.

- osquery/carver/carver.cpp
- osquery/core/system.cpp
- osquery/sql/sqlite_operations.cpp
Carver as a function had a few cleanups that didn't make it in
> Addressing a few nits that didn't make it in

- packs/osx-attacks.conf
- packs/vuln-management.conf
- tools/tests/utils.py
Addressing: #2892 
This fixes a lot of the issues but still doesn't address // when it's in a query because we can't just ignore it (which is what we now do with URLs in descriptions.
@poppyseedplehzr Any regex fu ideas?
> Fix profile.py

- osquery/remote/utility.h
Fixing a docs copy pasta error
> [Fix #3161] Small TLS docs change

- osquery/tables/system/darwin/system_info.cpp
- osquery/tables/system/linux/system_info.cpp
- osquery/tables/system/windows/system_info.cpp
- specs/system_info.table
Adding local host name which was referenced in an issue a while back.
> Fix #1546 Add local host name

- packs/ossec-rootkit.conf
- tools/deployment/osquery.example.conf
Querypack generated with tool at https://github.com/Uptycs/ossec-to-osquery
> Querypack equivalent of ossec rootkit db

- osquery/logger/CMakeLists.txt
- osquery/logger/plugins/syslog_logger.cpp
- osquery/logger/plugins/tests/syslog_logger_tests.cpp
> logger: Re-add syslog logger plugin

- osquery/tables/system/linux/rpm_packages.cpp
- specs/linux/rpm_package_files.table
> Allow up to 64k rpm_package_files

- osquery/sql/sqlite_operations.cpp
FreeBSD 10.2 cannot compile with an `std::set`'s `= {};`.
> sqlite: Remove the explicit copy and add mutex to function carve

- Makefile
- tools/analysis/fuzz.py
> build: Run setup target with .DEFAULT

- osquery/tables/networking/posix/interfaces.cpp
- osquery/tables/networking/windows/interfaces.cpp
- specs/interface_details.table
This includes a small refactor to the Windows implementation. I think the WMI calls can be reduced with: https://msdn.microsoft.com/en-us/library/aa394218(v=vs.85).aspx to get both the adapter information and configuration.
> tables: Add flags to interface_details

- osquery/carver/carver.cpp
This brings a "streaming" file IO to the carver for the tar archive creation to ensure that large carves do not bump up against our file read limits, as well as adds a few small checks to enhance the user experience of the carver.
> carver: tar creation is now streamed

- tools/provision.sh
- tools/provision/formula/bison.rb
These are all the changes that I had to make to the osquery build system to get make deps and make working on High Sierra. I had to build bison myself to apply a patch addressing a change in macOS' printf stack. Other than that I had to add ninja and reorder a couple dependencies.
> [RFC] Building on High Sierra

- tools/provision.sh
> linux: updating linuxbrew pins

- osquery/registry/registry.cpp
I think this is causing the odd errors observed in #3199.
> logger: Fail all plugins if any fail

- osquery/core/init.cpp
- osquery/core/posix/utils.cpp
- osquery/core/watcher.h
This fixes several findings from Linux's TSAN.
> tsan: Fix watcher and posix utils tsan findings

- osquery/tables/system/windows/programs.cpp
We currently only grab a limited set of the Windows programs installed on a system. This expands the list to include all GUID product IDs found in the system registry, as well as user specific applications.
> windows: Adding in additional program installation locations

- packs/osx-attacks.conf
Add detection capabilities for newly discovered mac malware
> Adding osx_fruitfly to osx-attacks

- packs/osx-attacks.conf
Fixed version of this commit: https://github.com/facebook/osquery/pull/3496#issuecomment-317951767
> Add Check for Additional Leverage Variant (redo)

- tools/provision.sh
Make deps is currently broken on Linux systems for a clean build
> Fix linuxbrew

- osquery/core/watcher.cpp
- osquery/core/watcher.h
Move the extensions checking code into a method and add a wait for each.
Fixes #3513
> extensions: Call wait on all extensions before respawning

- osquery/tables/system/windows/processes.cpp
This fixes/introduces a few broken/missing fields in the Windows processes table.
> tables: Adding threads and start_time fields to windows processes table

- osquery/tables/system/darwin/extended_attributes.cpp
> implement LIKEs for extended attributes table

- tools/provision/formula/libdevmapper.rb
Install `liblvm2app` alongside of `libdevmapper`.
> deps: Update LVM2/devmapper to r173 and install lvm2app

- osquery/tables/system/windows/scheduled_tasks.cpp
- specs/windows/scheduled_tasks.table
> tables: adding scheduled action to windows scheduled tasks table

- packs/osx-attacks.conf
https://objective-see.com/blog/blog_0x20.html
> Adding detection for OSX_Mughthesec

- include/osquery/distributed.h
fixes the failure in jenkins code audit
> fix c++ doc for rapidjson arguments

- tools/provision/formula/libcryptsetup.rb
- tools/provision/formula/libdevmapper.rb
- tools/provision/formula/libdpkg.rb
- tools/provision/formula/rapidjson.rb
> deps: Update Linux bottles libcryptsetup libdevmapper libdpkg rapidjson

- specs/windows/registry.table
Hi, this is an offer of some examples that I hope can address [issue 3218](https://github.com/facebook/osquery/issues/3218 ).
> Add examples of Windows registry virtual table

- tools/provision.ps1
- tools/provision/chocolatey/boost-msvc14.ps1
Bumping boost to 1.65 for windows.
> deps: bumping boost for Windows to 1.65.0

- tools/tests/test_http_server.py
Updating carver test endpoints with additional documentation.
> docs: updating comment documentation on carver endpoints

- osquery/tables/networking/posix/curl.cpp
- specs/posix/curl.table
This PR adds a curl table that allows users to make GET requests and get basic stats about the request back. Here's example usage of webpages with status 200, 301, 404, followed by one that contains the response column.
```
osquery> select url, method, user_agent, response_code, round_trip_time, bytes  from curl where url = 'https://github.com/facebook/osquery';
+-------------------------------------+--------+------------+---------------+-----------------+--------+
| url                                 | method | user_agent | response_code | round_trip_time | bytes  |
+-------------------------------------+--------+------------+---------------+-----------------+--------+
| https://github.com/facebook/osquery | GET    | osquery    | 200           | 112             | 150047 | …
```
> tables: Adding posix curl virtual table

- README.md
Just an update to put build status in the Readme.
> Add Jenkins status for FreeBSD

- include/osquery/filesystem.h
- osquery/core/tests/posix/permissions_tests.cpp
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/fileops_tests.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
> tests: Improve permissions tests as root

- osquery/tables/system/darwin/authorizations.mm
> Refactor authorizations tables

- packs/vuln-management.conf
Adds a query to search for the backdoored Python packages detailed here: http://www.nbu.gov.sk/skcsirt-sa-20170909-pypi/index.html
> packs: adding checks for known bad python packages

- packs/vuln-management.conf
> packs: fixing backdoored python pack

- tools/provision/formula/librdkafka.rb
Adding bottles for macOS for `librdkafka`.
> deps: Add bottles for librdkafka

- docs/_config.yml
- docs/_data/packs.yml
- docs/_layouts/packs.html
- docs/_layouts/schema.html
- docs/_sass/_style.scss
- docs/schema/packs.html
This will fetch the JSON pack content from the repo's: `/packs` directory and render a view like the table schema.
> website: Add the packs view

- docs/_layouts/schema.html
This seems to work. May be there is better way to do it!
> Split example SQL

- docs/_includes/top.html
- docs/schema/packs.html
- docs/schema/schema.html
> website: Fix missing redirects for tables and packs

- include/osquery/flags.h
- osquery/core/flags.cpp
- osquery/logger/logger.cpp
> flags: Add helper method to get an Int32 flag value

- packs/windows-attacks.conf
Created the windows-attacks.conf file, and included queries for windows attacks.
> Windows attacks query pack

- tools/provision/formula/glog.rb
Periodic update of dependencies for Linux and macOS.
> deps: Update glog formula to version 0.3.5

- tools/provision/formula/libmagic.rb
This updates the `libmagic`, the `file` project to version 5.32
> deps: Update libmagic to version 5.32

- osquery/tables/applications/darwin/browser_plugins.cpp
The `safari_extensions` table used to use `dropToParent`. This doesn't make a lot of sense when the table is already acting on user search paths. A more responsible approach uses the user.
NB: We provide `GLOB_NO_CANON` to the search in case we wanted to use the improved `dropToParent`. If we had canonicalized the path then the symlinks would be resolved within the filesystem APIs.
> [Fix #3765] Drop privileges to the user in the safari_extensions search

- SECURITY.md
Start using the `SECURITY.md` for relevant changes. We just fixed several issues reported by Ruslan Habalov and Felix Wilhelm of the Google Security Team.
> security: Update SECURITY.md with recent merges

- tools/provision/lib.sh
Update the python call to print all required attributes by using a straightforward bash loop. The bash function now takes in an array of object paths and returns a space-separated list of attributes. The caller uses `read` to usher the results into an array. Fixes #3803
> Get all required attributes in one shot during brew install. Addresses #3803.

- docs/_data/resources.yml
If you like, we've posted a blog about the usefulness of osquery and tracking code-signing issues on Windows.
> Add new blog post about osquery's use for examining Authenticode

- docs/_data/resources.yml
> Add more to resources.yml

- osquery/tables/system/windows/logical_drives.cpp
- specs/windows/logical_drives.table
This adds support for issue #3152
Back and with slightly more functionality!
> Implement a logical_drives table for windows

- osquery/registry/registry.cpp
The `mutex_` in the `Registry` methods should only protect the `extensions_` container. The `addExternal` method may contain anything. In the case of `TablePlugin` this may include locking SQLite.
> [Fix #3824] Do not lock registry addExternal calls

- osquery/filesystem/windows/fileops.cpp
The check for `isUserCurrentUser` on Windows has been failing since the recent overhaul of the relaxation of Safe perms. This fixes an issue I introduced where there was no buffer being passed when we get the current users token to check if they own the file.
> filesystem: allowing currently executing user to own binary

- osquery/events/darwin/diskarbitration.cpp
This also makes the code more similar to the new event_taps publisher. Testing showed no differences in rows returned.
> Fixes a small data race in disk arbitration

- osquery/tables/system/linux/os_version.cpp
This sets sane defaults for the `os_version` table on POSIX.
Fixes #3753.
> tables: Add default values for POSIX os_version

- tools/make-win64-binaries.bat
> Add guard around call to Visual C env bat files

- tools/build.ps1
This addresses #3861 by 1.) ensuring that we enumerate the `-legacy` versions of VS, which should ensure we correctly build for VS 2015, and 2.) we fail back to searching the environment for the VS 2015 directories where the `vcvarsall.bat` script is located in the fashion we were previously building.
> [Fix #3861] build: adding checks to vswhere usage to find msbuild tools

- docs/wiki/installation/install-osx.md
As per https://github.com/facebook/osquery/issues/3548#issuecomment-338358744. 
I'm also thinking of writing uninstall.sh. Where in the project directories should I put such a script?
> removal instructions for osquery on macOS

- include/osquery/dispatcher.h
- osquery/carver/carver.cpp
- osquery/config/config.cpp
- osquery/core/tests/posix/permissions_tests.cpp
- osquery/core/watcher.cpp
- osquery/core/watcher.h
- osquery/dispatcher/dispatcher.cpp
- osquery/dispatcher/distributed.h
- osquery/dispatcher/scheduler.h
- osquery/dispatcher/tests/dispatcher_tests.cpp
- osquery/events/kernel/tests/kernel_communication_tests.cpp
- osquery/events/linux/audit.cpp
- osquery/extensions/interface.h
- osquery/logger/plugins/aws_log_forwarder.h
- osquery/logger/plugins/buffered.h
- osquery/logger/plugins/kafka_producer.h
- osquery/logger/plugins/tests/buffered_tests.cpp
- osquery/logger/plugins/tls_logger.cpp
EDIT: This PR has been split into two; this is the first part, and Windows Event log has been moved to a dedicated branch.
This is a contribution to improve the status of issue #3604
I've given a name to all services; this should make it easier to understand what is going on when browsing the logs. 
Any feedback is really appreciated!
> Verbose logging when spawning services

- osquery/remote/http/http_client.cpp
> Conditionally adding port along with host name as host header value

- osquery/tables/networking/linux/iptables.cpp
- specs/linux/iptables.table
> Virtual table: Iptables port feature #3621

- packs/windows-attacks.conf
fixing missing coma in query pack.
> packs: fixing malformed win attack pack

- tools/deployment/make_windows_package.ps1
Updating our MSI generation logic to allow for upgrades
> deploy: allowing for MSI packages to upgrade previous installers

- tools/deployment/make_windows_package.ps1
This adds a couple of fields to our MSI building tooling, to allow for folks to bundle up additional files and customize their MSI deployment package.
> deployment: allowing for extra files to be bundled

- osquery/tables/system/windows/certificates.cpp
This addresses #3934 by adding the certificate store location to the certificates `path` column on Windows. @cryps1s let me know if you have something else in mind for the certificate store location. If we prepend the value to the cert path, we can avoid having a schema that varies from the MacOS certificates table. The current layout of the certs table now looks like the following, where the certificate store is prepened to the path to allow for cert differentiation:
```
osquery> select common_name,path from certificates;
+------------------------------------------------------------------+----------------------------------------------------+
| common_name                                                      | path …
```
> tables: Adding certificate store location to Windows certificates table

- tools/build.ps1
This ensures that the powershell build scripts return an exit code so our build CI will properly report the status of tests and builds.
> [Fix #3964] Returning exit code in Powershell build script

- tools/provision/formula/berkeley-db.rb
- tools/provision/formula/librpm.rb
- tools/provision/formula/zstd.rb
Update and patch some dependencies, and rebuild forward dependency bottles.
> deps: Update db, librpm, and zstd libs for Linux and Darwin

- docs/wiki/deployment/remote.md
- osquery/remote/transports/tls.cpp
- osquery/utils/aws_util.cpp
- osquery/utils/aws_util.h
Removing cpp-netlib name references from source code and docs.
> Removing cpp-netlib name references

- packs/osx-attacks.conf
More info on this threat:
https://digitasecurity.com/xplorer/xprotect_osx_hiddenlotus_a/
https://twitter.com/noarfromspace/status/936386961480306688
> Adding OSX detection for HiddenLotus

- docs/wiki/installation/cli-flags.md
This feature was added in #3165 but was never documented.
> Document --host_identifier=specified CLI option

- tools/provision/formula/librdkafka.rb
Update hashes for macOS and Linux for `librdkafka`.
> deps: Update librdkafka 0.11.1 bottle hashes

- tools/provision/formula/openssl.rb
Upgrade OpenSSL to 1.0.2m and cacert PEM file to latest
> Upgrade OpenSSL to 1.0.2m and cacert PEM file to latest

- osquery/core/init.cpp
The `--ephemeral` flags is designed for testing. It should allow the daemon to start without many configuration options. Previously the database also needed configuration, this does not make sense. 
Now, if someone uses `--ephemeral` then no on-disk database is used or needed.
While investigating I found that the older "config error warning", used when no config path/pidfile/database was configured, is no longer appropriate. These configuration items are taken care of automatically.
> ux: The ephemeral flag should disable the database

- CMake/Thrift.cmake
- osquery/extensions/interface.h
- requirements.txt
- tools/provision.ps1
- tools/provision.sh
- tools/provision/chocolatey/thrift-dev.ps1
- tools/provision/formula/thrift.rb
- tools/provision/lib.sh
- tools/release/deps_release.sh
This will need a Windows package built too since 0.11.0 is changing the pointer implementation.
> deps: Build for thrift 0.11.0

- include/osquery/core.h
- include/osquery/query.h
- include/osquery/sql.h
- osquery/core/query.cpp
- osquery/core/tests/query_tests.cpp
- osquery/database/benchmarks/database_benchmarks.cpp
- osquery/database/tests/results_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/sql/sql.cpp
Proposing these changes to enforce move semantic.
> Reducing memory footprint of osquery by achieving zero-copy.

- tools/deployment/make_osx_package.sh
Added a sign and keychain flag to the make_osx_package script. When provided
it will sign osqueryi and osqueryd with the certificate, package them up then
sign the package.
> Add signing functionality to make_osx_package

- osquery/tables/system/windows/kva_speculative_info.cpp
- specs/windows/kva_speculative_info.table
This adds in updates to the descriptions for the `kva_speculative_info` table.
> tables: updating row description for kva_speculative_info

- include/osquery/query.h
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- osquery/core/query.cpp
- osquery/core/tests/query_tests.cpp
- osquery/database/benchmarks/database_benchmarks.cpp
- osquery/database/tests/results_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/tests/test_util.cpp
Towards ordered scheduled query results.
> Ordered query results

- tools/deployment/make_windows_package.ps1
This fixes a small bug with the windows MSI packaging script.
> deploy: fixing error and warning with windows msi package

- README.md
Updating the link to the README image.
> readme: fixing link to logo image

- packs/incident-response.conf
missing platform else can have strange situation like trying to collect crontab on windows...
> adding platform tag incident-response pack

- osquery/registry/registry.cpp
> look up the external plugin by the correct name

- osquery/tables/applications/posix/docker.cpp
It looks like some docker daemon proxies return HTTP/1.1 response.
This change gracefully accepts 1.0 and 1.1 responses.
> docker: Deal with HTTP/1.1 response.

- osquery/remote/tests/requests_tests.cpp
> tests: Fix compression test failing for Sierra

- .github/ISSUE_TEMPLATE.md
- SUPPORT.md
This is a first draft to get us going. Looking for feedback!
> create a github issue template

- include/osquery/config.h
- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/parsers/file_paths.cpp
- osquery/config/parsers/views.cpp
- osquery/tables/yara/yara_events.cpp
- osquery/tables/yara/yara_utils.cpp
I found this with our `libfuzzer` integration :)
> config: Parser keys should be objects or arrays

- .github/ISSUE_TEMPLATE.md
- SUPPORT.md
Also repoint stackoverflow to the existing tag
> Update docs to encourage community resources

- osquery/tables/system/darwin/processes.cpp
PID 0 is actually legal; it's `kernel_task`. Allowing it through.
```
osquery> select * from processes where pid = 0;
+-----+-------------+------+---------+-------+-----+------+-----+-----+------+------+------+------+---------+------------+---------------+------------+-----------+-------------+-----------------+--------------------+------------+--------+--------+---------+------+
| pid | name        | path | cmdline | state | cwd | root | uid | gid | euid | egid | suid | sgid | on_disk | wired_size | resident_size | total_size | user_time | system_time | disk_bytes_read | disk_bytes_written | start_time | parent | pgroup | threads | nice |
+-----+-------------+------+---------+-------+-----+------+-----+-----+------+------+------+------+---------+------------+---------------+------------+- …
```
> [darwin][processes] Show kernel_task

- osquery/tables/system/darwin/sip_config.cpp
There was an intermittent leak in the SIP config table. It seems to only affect when osquery is running as root (because only root can get the IOMasterPortDefault I believe).
There were two missing release cases which I've fixed as well as a manual definition of "ok" in a status 0.
This is marked as API Change because if `genCsrConfigFromNvram` fails, we will now return `-1` and not `0`. This allows us to distinguish between unset csr values, and a failure to retrieve them.
> [Fix #4304] Fix a memory leak in the sip_config table

- osquery/core/posix/process.cpp
- osquery/core/process.h
- osquery/core/system.cpp
- osquery/core/watcher.cpp
- osquery/core/windows/process.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/tables/system/windows/processes.cpp
- osquery/tables/utility/osquery.cpp
This addresses #4322 and #4317, as well as adds a getter for the current process pid.
> bug: fix handle leaks in Windows process functions

- osquery/extensions/impl_fbthrift.cpp
- osquery/logger/logger.cpp
- tools/codegen/gentargets.py
- tools/sync.sh
This updates the codegen for buck's `TARGET` file.
> sync: Fix sync to handle new fbthrift refactor

- osquery/main/main.cpp
- osquery/main/main.h
- osquery/main/posix/main.cpp
- osquery/main/windows/main.cpp
This address #3949 by deriving the full path to the executable during service install.
> service: add full path for service binary

- tools/release/new_release.sh
This adds windows to our release tooling.
> release: adding Windows links to release script

- osquery/tables/networking/darwin/wifi.mm
- osquery/tables/networking/darwin/wifi_status.mm
- osquery/tables/networking/darwin/wifi_survey.mm
- osquery/tables/system/darwin/account_policy_data.mm
- osquery/tables/system/darwin/apps.mm
- osquery/tables/system/darwin/authorizations.mm
- osquery/tables/system/darwin/certificates.mm
- osquery/tables/system/darwin/disk_encryption.mm
- osquery/tables/system/darwin/event_taps.mm
- osquery/tables/system/darwin/mdfind.mm
- osquery/tables/system/darwin/packages.mm
- osquery/tables/system/darwin/shared_folders.mm
- osquery/tables/system/darwin/signature.mm
- osquery/tables/system/darwin/user_groups.mm
Added autorelease pool to fix long term memory usage. 
Default autorelease pool is drained on thread exit, so we need to use nested pools to avoid memory leaks, since our query execution thread is long running.
> [osx] added autorelease pools

- osquery/tables/system/darwin/mdfind.mm
CFObjects were created but never released.
> Fixing memory leak in mdfind table

- tools/provision/formula/Abstract/abstract-osquery-formula.rb
- tools/provision/formula/libcpp.rb
- tools/provision/formula/llvm.rb
Simplifying the include paths required for our custom C++ install.
> deps: Simplify LLVM includes

- osquery/config/config.cpp
- osquery/config/parsers/logger.cpp
- osquery/config/parsers/logger.h
Enable configure() calls on logger plugins.
> Logger config

- osquery/tables/system/linux/system_info.cpp
now cpu_type is extracted  using uname syscall
> cpu_type fixed for linux

- osquery/database/CMakeLists.txt
- osquery/database/plugins/ephemeral.cpp
- osquery/database/plugins/ephemeral.h
- osquery/database/plugins/sqlite.cpp
- osquery/database/plugins/sqlite.h
- osquery/registry/CMakeLists.txt
Reworked cmake file list
Split database plugins into cpp & h files to imrpove code structure
> reworked cmake file split database plugins files

- docs/wiki/development/osquery-sdk.md
> docs: adding note about extensions using RJ

- osquery/config/config.cpp
There are some reason to prefer vector and not the list:
1. Vector in most cases is noticeably faster. Because of memory locality, low memory overhead and so on.
2. Vector is much more convenient in terms of debuggability.
> Use std::vector instead of std::list for PackRef in Config

- specs/users.table
#4421 looking for initial review from @zacbrown 
Particularly looking for input on the description.
> Update docs around the users table to account for Windows

- Makefile
- tools/hooks/pre-commit.py
Added new clang format git hook that will abort commit if clang format should be executed
Added new make file target: git_hooks that will symlink clang format pre-commit hook
> added git clang format pre-commit hook

- osquery/tables/system/darwin/signature.mm
- specs/darwin/signature.table
This addresses CVE-2018-6336.
I am just the messenger opening the PR here, @obelisk is the author of the fix and the one who found the way to implement the correct checking.
> tables: Fix macOS signature table reporting

- osquery/registry/registry_interface.cpp
Do not hold a lock while calling the external callback during
addExternal or removeExternal.
External code might call the Registry causing a deadlock.
The code could be simplified and lock less, however this PR should not
change the logic.
Fixes #4527.
> Registry: don't call external code holding lock

- osquery/core/conversions.cpp
- osquery/core/conversions.h
base64Encode no additional string copy needed.
base64Decode code simplified.
> base64 encoding and decoding optimized

- osquery/tables/system/windows/processes.cpp
> bug: ensure correct checks on OpenProcess handles

- osquery/tables/system/linux/processes.cpp
- specs/linux/process_namespaces.table
- specs/processes.table
> Move process namespaces to separate table

- osquery/events/linux/auditdnetlink.cpp
- osquery/events/linux/auditdnetlink.h
- osquery/events/linux/auditeventpublisher.cpp
> AuditdNetlink: Only start the netlink services once

- osquery/config/additional_parsers/auto_constructed_tables.h
Comply with cpp member initialization order.
> ATCPlugin fix ctor initialization order

- osquery/events/darwin/fsevents.cpp
> Remove /dev/null monitoring from fsevents

- osquery/events/windows/windows_event_log.cpp
This is blocking other pulls. Not sure how this happened.
> WEL format change

- docs/wiki/introduction/sql.md
> actualized names for *base64* family functions

- tools/deployment/make_windows_package.ps1
> deploy: set default flagfile to utf-8 for MSI package

- tools/provision.sh
- tools/provision/formula/bzip2.rb
- tools/provision/formula/ccache.rb
- tools/provision/formula/libmagic.rb
- tools/provision/formula/ncurses.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/python.rb
Brew needs to be updated for Mojave then some features are deprecated in favour of new ones. This should fix the system for 10.14.
> Update brew and formulae for Mojave

- tools/tests/test_windows_service.py
Our windows service thrashing tests have been pretty flaky. This changes our logic to assert the service has been installed, and correctly started, before we begin testing more components.
> tests: ensure service has been installed before starting

- tools/provision.ps1
- tools/provision/chocolatey/openssl.ps1
Uploaded openssl-1.0.2o private deps in S3 and updated certs.
#4556
> update win64 openssl to 1.0.2o

- tools/provision.sh
- tools/provision/formula/bzip2.rb
- tools/provision/formula/ccache.rb
- tools/provision/formula/fbthrift-mstch.rb
- tools/provision/formula/gcc.rb
- tools/provision/formula/libmagic.rb
- tools/provision/formula/ncurses.rb
- tools/provision/formula/openssl.rb
- tools/provision/formula/python.rb
- tools/provision/formula/zlib-legacy.rb
This reverts commits 19c0bedf194d19a4a3d6c561a774709bcab41847 and c8133b2810e1501e6641ea78c274bcf071380d24.
> Revert homebrew changes introduced for Mojave

- osquery/main/windows/main.cpp
Addresses #4200
After `osqueryd --install` the results look as expected: https://i.imgur.com/Q8TAo0D.png
> add recovery behavior to osqueryd Windows service

- osquery/events/events.cpp
No need for additional loop to determine length of the integer in decimal representation.
> toIndex simplification

- include/osquery/registry_factory.h
- include/osquery/sdk.h
Just to make it clear for easier reading
> Used proper names in registry macro instead of obfuscated names

- osquery/distributed/CMakeLists.txt
- osquery/events/CMakeLists.txt
- osquery/filesystem/CMakeLists.txt
- osquery/logger/CMakeLists.txt
- osquery/remote/CMakeLists.txt
another set of removed file(GLOB) and adding CMAKE_CURRENT_LIST_DIR
> updated another set of cmake files

- tools/tests/test_windows_service.py
This should continue to address #4601. I'll continue trying to repro this, but the best remediation I could find from jumping on the CI host was clearing out all of the residual services, as some of them didn't seem to finish or clear out correctly, and then re-run the tests. As such, this isn't a fix so much as diagnosing the symptoms, but we're getting closer!
> tests: ensure services have been cleared before testing

- osquery/tables/system/posix/shell_history.cpp
This adds logging of history files in the bash_sessions directory on MacOS.
> refactor before adding bash_sessions history files to shell_history

- osquery/sql/CMakeLists.txt
- osquery/tables/CMakeLists.txt
- osquery/utils/CMakeLists.txt
One more part of reworked CMakeFiles with support of include command and removing file(GLOB)
> reworked part of cmake files

- tools/provision/formula/libgcrypt.rb
- tools/provision/formula/popt.rb
- tools/provision/ubuntu.sh
I was trying to build clean on Ubuntu 18.04 and here are some nitpicks needed.
> deps: Small changes for Ubuntu18 build

- osquery/numeric_monitoring/pre_aggregation_cache.cpp
- osquery/numeric_monitoring/pre_aggregation_cache.h
> Fixed up misspells in variable name and docstrings

- osquery/core/conversions.cpp
- osquery/core/conversions.h
- osquery/core/tests/conversions_tests.cpp
- osquery/devtools/shell.cpp
- osquery/tables/applications/browser_utils.h
Also use it in some obvious placed in codebase. Cosmetic change.
> Implement generic `tryTo` for string to boolean converions

- osquery/tables/system/darwin/sharing_preferences.cpp
- specs/darwin/sharing_preferences.table
> Adding content_caching to sharing_preferences

- osquery/core/conversions.cpp
- osquery/core/conversions.h
- osquery/tables/networking/windows/interfaces.cpp
- osquery/tables/system/windows/physical_disk_performance.cpp
and remove `safeStrtoull` from the `conversions.h`
> Use `tryTo` instead of `safeStrtoull` in the code

- osquery/tables/utility/file.cpp
PR #4613 reverted #4579 by mistake.
> Revert regression on symlink detection

- osquery/core/posix/utils.cpp
> Add missed include <climits> for PATH_MAX

- osquery/tables/networking/posix/utils.cpp
`inet_ntop` does not support IPv6 scopes, which results in some addresses being formatted incorrectly. I noticed this in the Darwin `interface_addresses` table (as compared to the output of `ifconfig`), but it no doubt applies elsewhere as well.
Before:
```
osquery> select interface, address from interface_addresses where interface = 'awdl0';
interface = awdl0
address = fe80::2460:63ff:fe22:226b
```
After:
```
osquery> select interface, address from interface_addresses where interface = 'awdl0';
interface = awdl0
address = fe80::2460:63ff:fe22:226b%awdl0
```
> [posix] Properly format IPv6 addresses with scopes

- osquery/events/linux/udev.cpp
We've been missing information about the udev fd problems. It might be the cause of the udev errors so adding additional error message.
> udev fd check

- osquery/filesystem/darwin/plist.mm
- osquery/tables/system/darwin/packages.mm
Autorelease added to the leaking NSNumber allocs.
Thanks for help @mkareta
> objective c leak

- CMakeLists.txt
- osquery/core/json.h
- osquery/examples/example_writable_table.cpp
- osquery/killswitch/killswitch_refreshable_plugin.h
- osquery/killswitch/plugins/killswitch_filesystem.h
- osquery/tables/system/darwin/crashes.cpp
- osquery/tables/system/darwin/kernel_panics.cpp
- osquery/tables/yara/yara_utils.h
I was playing with CMake builds, trying to optimize compile time. Here are a few non-intrusive fixes.
> review: Small code review fixes related to CMake

- osquery/core/system.cpp
- osquery/filesystem/filesystem.cpp
- osquery/sql/sqlite_util.cpp
- osquery/sql/virtual_table.cpp
- osquery/tables/system/darwin/authorizations.mm
- osquery/tables/system/darwin/smc_keys.cpp
- osquery/utils/aws_util.cpp
Using pvs-studio, I detected various issues in osquery.
integer overflow
inserting the same key several times
Dead code.
> pvs-studio errors and warnings fix

- osquery/events/linux/auditdnetlink.cpp
- osquery/tables/system/windows/authenticode.cpp
No need to check if resize works.
> Resize size check dead code

- include/osquery/expected.h
- osquery/core/tests/exptected_tests.cpp
Also restructed the code around this sort of checks to beter readability
> Add debug checks for wrong access of error in Expected

- CMakeLists.txt
- tools/provision.ps1
- tools/provision/chocolatey/boost-msvc14.ps1
This updates our boost build using MSVC 14.1
> deps: boost updates for windows vs 2017

- include/osquery/killswitch.h
- osquery/killswitch/killswitch_plugin.cpp
- osquery/killswitch/killswitch_plugin.h
- osquery/killswitch/plugins/killswitch_filesystem.cpp
- osquery/killswitch/plugins/killswitch_filesystem.h
- osquery/killswitch/plugins/killswitch_tls.cpp
- osquery/killswitch/plugins/tests/killswitch_filesystem_tests.cpp
- tools/tests/test_killswitch.conf
- tools/tests/test_killswitch_incorrect_key.conf
- tools/tests/test_killswitch_incorrect_value.conf
- tools/tests/test_killswitch_no_table.conf
Killswitch map of the enabled/disabled switches will be under tables name.
> killswitch extendable config format

- README.md
Update license text according to the text in CONTRIBUTING.md. Remove old
recruitment text. Update Slack registering link.
> Cleanup old text from README

- osquery/core/database/database.h
> spelling errors

- include/osquery/killswitch.h
- osquery/core/database/database.h
- osquery/core/tables.cpp
- osquery/killswitch/killswitch.cpp
- osquery/killswitch/killswitch_refreshable_plugin.cpp
Various minor linter warnings correction
> linter warnings

- osquery/config/packs.cpp
- osquery/core/conversions.h
- osquery/core/darwin/iokit.hpp
- osquery/core/flags.cpp
- osquery/core/system.cpp
- osquery/tables/events/linux/socket_events.cpp
- osquery/tables/networking/windows/arp_cache.cpp
- osquery/tables/sleuthkit/sleuthkit.cpp
- osquery/tables/system/linux/md_tables.cpp
- osquery/tables/system/linux/memory_info.cpp
- osquery/tables/system/linux/user_groups.cpp
- osquery/tables/system/linux/users.cpp
- osquery/tables/system/windows/os_version.cpp
One more step to use `tryTo<long>` instead of `safeStrto*`
Based on PR #4767
>  Remove `safeStrtol` from conversion.h (use `tryTo<long>` instead)

- docs/wiki/deployment/extensions.md
- docs/wiki/development/osquery-sdk.md
Hi, I'd like to contribute some small edits and additions to the documentation on osquery extensions.
Addresses #4465
> Improve extensions documentation

- docs/wiki/deployment/configuration.md
> docs: fix the definition of 'posix' for the platform key

- osquery/core/system.cpp
Reduced warnings in set thread name.
> fix set thread warnings

- osquery/main/fuzz.cpp
I did not like some of the assumptions in `smbios_utils` so I wrote a small fuzzer harness.
This found several issues but they are best-practice / coding practice issues, not vulnerabilities as SMBIOS data cannot be controlled by the user. It is possible that this data is corrupted since some device vendors choose to ignore fields / etc.
> libfuzz: Add SMBIOS table fuzzing

- docs/wiki/installation/install-linux.md
> Update linux installation guide

- osquery/config/config.cpp
- osquery/config/packs.cpp
- osquery/config/tests/config_tests.cpp
- osquery/core/conversions.cpp
- osquery/core/conversions.h
- osquery/core/tests/conversions_tests.cpp
> Remove boost SHA1 UUID dependency

- osquery/logger/logger.cpp
unused code left out while refactoring the code.
> unused code logger

- include/osquery/killswitch.h
- osquery/config/config.cpp
- osquery/killswitch/killswitch.cpp
Protecting new config backup feature with the killswitch.
> put config backup feature behind killswitch

- osquery/tables/events/linux/socket_events.cpp
This is a small fix for the bind() event handling in the socket_events table. This has been backported from the following PR: https://github.com/facebook/osquery/pull/5084 (which includes tests for each supported syscall type).
```
osquery> SELECT action, pid, path, local_address,
...>        local_port, remote_address, remote_port
...> 
...> FROM socket_events;
+---------+-------+-----------------+---------------+------------+----------------+-------------+
| action  | pid   | path            | local_address | local_port | remote_address | remote_port |
+---------+-------+-----------------+---------------+------------+----------------+-------------+
| bind    | 20806 | /bin/nc.openbsd | 127.0.0.1     | 8080       | 0              | 0           |
| connect | 20884 | /bin/nc.openbsd | 0 …
```
> socket_events: Use local_port/local_address for bind()

- osquery/tests/integration/tables/hash.cpp
> [Table sanity check] hash

- osquery/tests/integration/tables/helper.cpp
- osquery/tests/integration/tables/system_info.cpp
- Sanity check test for system info table
- Fixed Int type check when number is bigger than int
> [Table sanity check] system info

- osquery/tests/integration/tables/kernel_modules.cpp
> [Table sanity check] Integration test for the linux kernel modules table

- osquery/tests/integration/tables/crontab.cpp
- osquery/tests/integration/tables/helper.cpp
- osquery/tests/integration/tables/helper.h
- osquery/tests/integration/tables/system_info.cpp
added sanity check for crontab and validation for cron tab time format
> [Table sanity check] crontab

- osquery/tests/integration/tables/deb_packages.cpp
> [Table sanity check] Integration tests for deb_packages

- include/osquery/error.h
@akindyakov ErrorBase fix for wdeprecated flag warning.
> errorbase wdeprecated warning fix

- osquery/tests/integration/tables/process_envs.cpp
> [Table sanity check] process_envs

- osquery/tests/integration/tables/helper.cpp
- osquery/tests/integration/tables/helper.h
> Fix up wrong integer types from validating values from the tables

- docs/wiki/installation/cli-flags.md
- osquery/numeric_monitoring/numeric_monitoring.cpp
This is a trivial fix, I think you'll agree no changes to the tests are needed :)
> Fix typo. It's Comma, not Coma :-)

- osquery/tests/integration/tables/sandboxes.cpp
> [Table sanity check] sanboxes

- osquery/tests/integration/tables/programs.cpp
> [Table sanity check] programs

- osquery/tests/integration/tables/memory_map.cpp
> [Table sanity check] memory_map

- osquery/tables/networking/posix/interfaces.cpp
- osquery/tests/integration/tables/helper.cpp
- osquery/tests/integration/tables/helper.h
- osquery/tests/integration/tables/interface_addresses.cpp
- specs/interface_addresses.table
> [Table sanity check] sanity check for the table interface_addresses

- osquery/tests/integration/tables/logged_in_users.cpp
> [Table sanity check] sanity check for the table logged_in_users

- osquery/tests/integration/tables/system_controls.cpp
> [Table sanity check] Integration test for the table system_controls

- osquery/tables/system/posix/known_hosts.cpp
- osquery/tables/system/posix/known_hosts.h
- osquery/tables/system/posix/tests/known_hosts_tests.cpp
- osquery/tests/integration/tables/known_hosts.cpp
> [Table sanity check] Integration test for the `known_hosts` table

- osquery/tests/integration/tables/apt_sources.cpp
> [Table sanity check] Integration test for the 'apt_sources' table

- osquery/tests/integration/tables/process_open_files.cpp
> [Table sanity check] process_open_files

- osquery/tests/integration/tables/registry.cpp
> [Table sanity check] Integration test for the `registry` table

- include/osquery/killswitch.h
- osquery/core/init.cpp
- osquery/killswitch/killswitch.cpp
monitor how many times is osquery started.
> monitor number of times osquery starts

- include/osquery/killswitch.h
- osquery/killswitch/killswitch.cpp
- osquery/logger/logger.cpp
monitor how many query result was sent from osquery
> total number of queries sent numeric_monitor

- Vagrantfile
We will be able to set memory capacity for the vagrant as the env variable.
> vagrant check memory env variable

- tools/deployment/make_windows_package.ps1
This is a very quick attempt to address https://github.com/facebook/osquery/issues/5067
testing needed
> add osquery.man to wix config for New-MsiPackage - #5067

- docs/wiki/deployment/process-auditing.md
- docs/wiki/development/building.md
Removed weird character after --disable-audit=false (i.e. code example in point no. 5 of Troubleshooting)
> Small doc fixes

- include/osquery/dispatcher.h
- osquery/dispatcher/dispatcher.cpp
dispatcher destructor causes problems in your debug build.
> dispatcher static destructor fiasco

- include/osquery/expected.h
- osquery/core/tests/exptected_tests.cpp
Fix up checking the type for argument in template definition.
Related PR #5190
> Expected::takeOr have to accept rvalue as an argument

- Vagrantfile
vagrant configure vmware_desktop same as the virtualbox
> vagrant configure vmware_desktop

- osquery/core/conversions.h
- osquery/core/windows/process_ops.cpp
- osquery/dispatcher/distributed_runner.cpp
- osquery/events/events.cpp
- osquery/events/linux/auditdnetlink.cpp
- osquery/examples/example_writable_table.cpp
- osquery/tables/networking/posix/interfaces.cpp
- osquery/tables/system/darwin/tests/asl_tests.cpp
- osquery/tables/system/windows/objects.cpp
- osquery/tables/system/windows/system_info.cpp
Used `tryTo<>` from #4676 instead
> Remove the rest of the safeStrto* function from conversion.h

- osquery/tests/integration/tables/arp_cache.cpp
- osquery/tests/integration/tables/helper.cpp
- osquery/tests/integration/tables/helper.h
- osquery/tests/integration/tables/interface_addresses.cpp
- osquery/tests/integration/tables/routes.cpp
Fixes:  #5022
Test Plan:
```
./osquery_integration_tests --gtest_filter="routes.*"
./osquery_integration_tests --gtest_filter="arpCache.*"
```
> [Table sanity check] routes & arp_cache

- include/osquery/filesystem.h
- osquery/filesystem/filesystem.cpp
- osquery/filesystem/tests/filesystem_tests.cpp
Non throwing  directory creation function.
`Status` was used as a return value, as far as all function in this file operate with `Status` not `Expected`. Let's move from `Status` to `Expected` in another PR.
> Non throwing directory creation function.

- osquery/core/init.cpp
Prepare the filesystem directories in initialisation routine when osquery get started as a daemon.
Depends on: #5206
> Prepare the filesystem directories in initialisation routine

- osquery/tables/networking/windows/routes.cpp
- osquery/tests/integration/tables/routes.cpp
- specs/routes.table
> tables: netmask should be an integer

- osquery/tables/system/windows/os_version.cpp
- osquery/tests/integration/tables/os_version.cpp
- specs/os_version.table
Continuation of https://github.com/facebook/osquery/pull/5205
I bricked the branch I was on pretty hard so I decided to move what I need to a new branch off of an up to date pull from master.
> Add InstallDate to os_version for Windows

- tools/cmake/downloader.py
This will allow to automatically handle URL re-directions (e.g. 302)
> Improve the downloader.py script to use urllib2

- osquery/utils/base64.cpp
(it is probably a copy and paste error)
> Fix small typo in the base64 log message

- azure-pipelines.yml
- osquery/core/init.cpp
- osquery/filesystem/windows/fileops.cpp
- osquery/process/posix/process_ops.cpp
- osquery/process/process.h
- osquery/process/windows/process_ops.cpp
- osquery/process/windows/process_ops.h
- osquery/tables/system/tests/system_tables_tests.cpp
- osquery/tables/system/windows/groups.cpp
- osquery/tables/system/windows/processes.cpp
- osquery/tables/system/windows/user_groups.cpp
- osquery/tables/system/windows/users.cpp
- tests/integration/tables/interface_details.cpp
Start working toward getting the Azure Pipelines CI all green.
#5608
> Fix or disable failing tests

- osquery/remote/http_client.cpp
- osquery/remote/http_client.h
- tests/integration/tables/crontab.cpp
1. Putting all the networking calls under timeout.
2. Remove some obsolete code.
3. Some error handling changes.
4. Calling set_terminate_threads once
> Replacing sync calls by async ones and some cleanup

- docs/wiki/introduction/sql.md
- osquery/sql/sqlite_string.cpp
- osquery/sql/tests/sql.cpp
This creates a `regexp_match` sql function, tests, and associated docs.
Add tests for more of the string sql functions
> sql function regex_match (and some tests for other sql functions)

- tools/deployment/make_windows_package.ps1
With the introduction and support of the Buck build system, we should start adding support to our various build|provision|deployment scripts for the Buck components. This adds in checks for the buck binaries as a secondary option to the CMake binary output to make generation of osquery packages easy for either build platform.
- Build the binaries:
```
PS C:\Users\Nicholas\work\repos\osquery> cmake --build .\build\windows10\ --config Release -j10                                                                                                     Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
osquery_utils_config.vcxproj -> C:\Users\Nicholas\work\repos\osquery\build\windows10\osquery\utils\config\Release\osqu …
```
> packaging: updating packaging script to support Buck binary output

- tests/integration/tables/etc_protocols.cpp
> [Table sanity check] etc_protocols

- docs/wiki/development/building.md
... and complete the list of prerequisites on Ubuntu 18.10.
Related to / resolves #5692
> Clarify permissions required for Windows build

- README.md
We've registered with the best practices part of the core infrastructure project. May as well add the badge to the readme.
> Add CII badge to the readme

- docs/wiki/deployment/extensions.md
> Add more complete docs on extension file permissions

- azure-pipelines.yml
All the tests under tests/ and plugins/from the root of the project were not run.
> Add missing tests not run in Buck

- README.md
This is a small refactor within the README.md
> readme: Replace information and build status table with lists

- CONTRIBUTING.md
Very light edits to CONTRIBUTING to remove Facebook URLs, TravisCI, and
Phabricator
> Light edits on CONTRIBUTING

- CHANGELOG.md
Update the CHANGELOG with recent updates.
> changelog: Update 4.0.1 changes

- tools/deployment/chocolatey/tools/chocolateyinstall.ps1
Summary: This updates the chocolatey deployment scripts to ensure that
if the current installation is using the ProgramData path in the system
service, this is removed and subsequently updated to the new Program
Files location.
Test Plan: Force installed osquery 3.3.2:
```
C:\Users\Nick\Desktop> choco install -yf osquery --params='/InstallService' --version 3.3.2
Chocolatey v0.10.7
Installing the following packages:
osquery
By installing you accept licenses for the packages.
Progress: Downloading osquery 3.3.2... 100%
osquery v3.3.2 (forced) [Approved]
osquery package files install completed. Performing other installation steps.
True
True
C:\ProgramData\osquery\osqueryd
C:\ProgramData\osquery\log
Extracting C:\ProgramData\chocolatey\lib\osquery\tools\\bin\\osquery.zip to …
```
> deploy: update windows choco scripts to migrate service to Program Files

- tests/integration/tables/startup_items.cpp
Creates sanity check for the table `startup_items`.
#5058
> [Table sanity check] startup_items

- cmake/packaging.cmake
This enables a component install for DEB (only). This is required in
CMake version 3.17.0 (planned) and lower to produce a debuginfo version.
One side-effect is we have to gate the stripping for DEB.
I've checked RPM and TGZ and there should be no side effects but I will double-check again on a clean environment later.
> cpack: Update package logic to build DEB debuginfo

- tests/integration/tables/sudoers.cpp
Creates sanity check for the table startup_items.
#4889
> [Table sanity check] sudoers

- tests/integration/tables/chocolatey_packages.cpp
Creates sanity check for the table `chocolatey_packages`.
#5037
> [Table sanity check] chocolatey_packages

- osquery/tables/system/windows/processes.cpp
The windows processes table is missing the implementation of it's pid INDEX filtering.
Without this, the windows processes table will do a full table scan for every element in a JOIN or IN() list.
> windows processes: Implement missing pid index

- azure-pipelines.yml
- docs/wiki/development/building.md
- libraries/cmake/formula/modules/utils.cmake
- libraries/cmake/formula/openssl/CMakeLists.txt
- libraries/cmake/source_migration/modules/Findopenssl.cmake
- tools/ci/scripts/install_openssl_formula_dependencies.ps1
- tools/ci/scripts/install_strawberry_perl.ps1
~~The formula should work, but I still have to add a script to install Perl on the Windows CI machine~~
Ready for review!
> CMake: Migrate macOS and Windows to the OpenSSL formula

- osquery/remote/http_client.cpp
- osquery/remote/http_client.h
Addressing some of the issues raised at #5883
> Removing code repetition and fixing timer bug

- osquery/config/config.cpp
- osquery/config/tests/packs.cpp
- osquery/utils/json/tests/json.cpp
> config: Add check for non-object multi-packs

- azure-pipelines.yml
- tools/ci/osquery-ubuntu18.04-toolchain.dockerfile
Needed to create RPM debuginfo packages.
Also update the azure-pipelines.yml to use the new Docker image.
Needed by https://github.com/osquery/osquery/pull/5936
> Add elfutils to the CI Dockerfile

- osquery/utils/info/BUCK
- tools/buckconfigs/base.bcfg
- tools/build_defs/oss/osquery/native.bzl
I am not sure of another way to do this with `PYTHON_DSL`. Switching to Skylark may provide the `execute` function, but I have not tested this.
Fixes #5739.
> buck: Detect git version

- docs/wiki/installation/cli-flags.md
> docs: Add reference to buffered_log_max option

- tools/harnesses/osqueryfuzz_config_corpus.sh
> Update osqueryfuzz_config_corpus.sh to correct the path to the tests directory

- specs/chrome_extensions.table
- specs/curl.table
- specs/darwin/browser_plugins.table
- specs/darwin/crashes.table
- specs/darwin/event_taps.table
- specs/darwin/kernel_extensions.table
- specs/darwin/keychain_items.table
- specs/darwin/package_receipts.table
- specs/darwin/preferences.table
- specs/darwin/safari_extensions.table
- specs/darwin/signature.table
- specs/linux/ec2_instance_metadata.table
- specs/linux/npm_packages.table
- specs/linux/rpm_packages.table
- specs/posix/authorized_keys.table
- specs/posix/known_hosts.table
- specs/posix/opera_extensions.table
- specs/posix/ssh_configs.table
- specs/posix/system_controls.table
- specs/python_packages.table
- specs/smart/smart_drive_info.table
- specs/windows/drivers.table
- specs/windows/ie_extensions.table
- specs/windows/logon_sessions.table
- specs/windows/winbaseobj.table
- specs/yara/yara.table
This addresses #5675 .  (As well as the old osql #53 )
Now that #5919 has been merged, we need to fix the spec files to match table implementations.
> 5675 advert index not implemented

- cmake/packaging.cmake
- tools/deployment/copyright.debian
> cpack: Add Debian copyright file and Augeas license

- osquery/extensions/impl_thrift.cpp
If a Thrift server is requested to stop before everything is
properly initialized a race condition could happen.
Specifically if stopping during a listen() a race condition will happen
accessing childInterruptSockWriter_, which is a socket initialized by listen(),
in a non thread-safe way, and used by stop() to notify other threads
that they should shutdown.
> Fix a race condition between Thrift server stop() and listen()

- CHANGELOG.md
This takes advantage of GitHub's display of PRs/issues using hashtag-shorthand.
> Update changelog for 4.1.0

- CHANGELOG.md
- Tables and a column have been added, not removed.
- Fixed MSI ErrorControl bugfix PR link.
> Some corrections to the 4.1.0 Changelog

- CHANGELOG.md
Correct a few typos in the v4.1.0 changelog
> Typo fixes in v4.1.0 CHANGELOG

- azure-pipelines.yml
- cmake/utilities.cmake
- tools/ci/osquery-ubuntu18.04-toolchain.dockerfile
- tools/formatting/format-check.py
- tools/formatting/git-clang-format.py
py2->3 update for format checkers
Fixes https://github.com/osquery/osquery/issues/5762
Needs utf8 locale set; missing in dockerfile; changes made
> formatting functions py2->3

- plugins/config/parsers/auto_constructed_tables.cpp
This is a short code-review for the ATC config parser. It adds checks for the JSON format assumptions. It also returns a success when there is no ATC configuration (this is the normal behavior for parsers).
> config: Code review for ATC parser

- .github/PULL_REQUEST_TEMPLATE.md
Adding some common high-level "checks" we perform when coding-reviewing.
> docs: Add common code-review checks to PR template

- osquery/sql/tests/sqlite_util_tests.cpp
- osquery/sql/virtual_table.cpp
This is an alternative to #6014.
Instead of returning an error from xBestIndex we return an impossible cost.
> tables: Re-enable required-column warning message

- libraries/cmake/source/modules/utils.cmake
CMake doesn't support reading and therefore copying Windows symlinks.
A recent update to Thrift creates a symlink in its tutorial folder,
which makes the copy after patch process fail.
As a workaround we remove the tutorial folder,
since we don't care about it anyway.
> CMake: Workaround Thrift symlink issue on Windows

- osquery/config/packs.cpp
- tools/tests/test_inline_pack.conf
Additional JSON type checks for configuration parsers (I am almost finished reviewing them all).
> config: Add more checks for pack JSON

- osquery/tables/applications/browser_chrome.cpp
- osquery/tables/applications/browser_utils.cpp
- osquery/tables/applications/browser_utils.h
- osquery/tables/applications/posix/browser_opera.cpp
- tests/integration/tables/chrome_extensions.cpp
Added support to the chrome_extensions table for Brave and Chromium browsers.
This PR addresses #5800 and closes #3912.
> Added Brave/Chromium support for chrome_extensions

- osquery/CMakeLists.txt
- tools/tests/CMakeLists.txt
- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
- tools/tests/winexpect.py
Co-Authored-By: SS <sahil.suneja@trailofbits.com>
> Restore test_osqueryd.py test

- tests/integration/tables/chrome_extensions.cpp
Created tests for chrome_extensions table.
Addresses #4926
> [Table sanity check] chrome_extensions

- osquery/tables/system/windows/ntfs_acl_permissions.cpp
Fixes https://github.com/osquery/osquery/issues/6123
> tables: Fix ntfs_acl_permissions

- CHANGELOG.md
Adding changelog for the new bug-fix version 4.1.2
> changelog: Add CHANGELOG for 4.1.2

- libraries/cmake/source/boost/CMakeLists.txt
> Make Boost winapi available to all platforms

- tests/integration/tables/hash.cpp
Co-Authored-By: Ryan Wilson <ryantimwilson@fb.com>
> tests: Improve hash table integration tests

- osquery/tables/system/tests/system_tables_tests.cpp
Co-Authored-By: Marek Cirkos <marekc@fb.com>
> tests: Reduce flakyness of test_processes_memory_cpu

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- docs/wiki/development/building.md
Make the formatting step and documentation more prominent,
also add what's needed to be able to format on macOS and Windows.
> Add some more information about formatting

- packs/osquery-monitoring.conf
As added in #4004, this column is very valuable and should be surfaced here.
> Add blacklisted column to osquery_schedule query

- docs/wiki/deployment/performance-safety.md
Updated performance-safety.md to include details about profile.py and it's output. The changes also include information about how profile.py sets the thresholds that appear in the script output.
> Updated documentation for profile.py in performance-safety.md

- osquery/carver/carver.cpp
- osquery/carver/carver.h
- osquery/carver/tests/carver_tests.cpp
Co-Authored-By: Ryan Wilson <ryantimwilson@fb.com>
> carver: Fix bug where carve returns empty files for hidden files

- osquery/tables/system/darwin/crashes.cpp
- osquery/tables/system/freebsd/os_version.cpp
- osquery/tables/system/linux/os_version.cpp
- osquery/tables/system/linux/processes.cpp
- osquery/tables/system/linux/shadow.cpp
- osquery/tables/system/posix/shell_history.cpp
- osquery/tables/system/windows/programs.cpp
- osquery/tables/system/windows/wmi_bios_info.cpp
> regex engine replacement: boost -> std

- CONTRIBUTING.md
This adds a section on the TSC to the contributing file.
It also reflows things.
> Add the TSC to the contributing file

- osquery/events/linux/udev.cpp
Co-Authored-By: Ryan Wilson <ryantimwilson@fb.com>
> udev: Log errno for udev ERROR messages

- README.md
Add a link to the README to the older documentation. (Also reflow the docs)
> Add link to older releases

- CMakeLists.txt
- libraries/cmake/source/librdkafka/CMakeLists.txt
- libraries/cmake/source/zstd/CMakeLists.txt
- libraries/cmake/source_migration/modules/Findlibrdkafka.cmake
- osquery/main/CMakeLists.txt
- plugins/logger/CMakeLists.txt
- plugins/logger/kafka_producer.cpp
The PR will be reviewed by an osquery committer.
Here are some common things we look for:
- The code is formatted correctly, considering using `make format_check`.
- Common utilities within `./osquery/utils` are used where appropriate (avoid reinventions).
- Modern C++ structures and patterns are used whenever possible.
- No memory or file descriptor leaks, please check all early-return and destructors.
- No explicit casting, such as `return (int)my_var`, instead use `static_cast`.
- The minimal amount of includes are used, only include what you use.
- Comments for methods, structures, and classes follow our common patterns.
- `Status` and `LOG(N)` messages do not use punctuation or contractions.
- Support for both CMake and BUCK (we are happy to help).
- The code mostly looks and feels …
> Build librdkafka on Windows

- osquery/tables/system/linux/pci_devices.cpp
Test pull request to ensure that the CLA is cleared.
Reference pull request : https://github.com/osquery/osquery/pull/6206
> Fix 5569 pci ids on redhat like v2 

- tools/tests/test_http_server.py
Do not close the http server after 10s if there are requests coming,
since some tests may take more than 10s to run.
Reset the timer each time a request is received by the server instead.
> Fix TLSConfigTests.test_runner_and_scheduler failing

- tests/integration/tables/disk_info.cpp
Fixes #5036
All tests from tests_integration_tables-test passes (except one - chromeExtensions.test_sanity, problem reported in #6306).
> [Table sanity check] disk_info

- osquery/tables/system/posix/magic.cpp
> magic: Check return from magic_file

- osquery/sql/dynamic_table_row.cpp
Osquery converts numbers in table rows without checking if the values are empty and then errors trying to convert an empty string to a numeric type. 
If the row value is numeric and empty return a null value.
On Windows run
```
select * from process_open_sockets;
```
Without change:
```
C:\osquery_test\original>osquery.exe --verbose
I0407 13:35:27.066941 20636 init.cpp:340] osquery initialized [version=4.2.0]
I0407 13:35:27.066941 20636 extensions.cpp:349] Could not autoload extensions: Failed reading: \Program Files\osquery\extensions.load
I0407 13:35:27.066941 20636 auto_constructed_tables.cpp:93] Removing stale ATC entries
I0407 13:35:27.066941 32048 interface.cpp:268] Extension manager service starting: \\.\pipe\shell.em
Using a [1mvirtual database[0m. Need help, type '.help' …
```
> Remove errors when converting empty numeric rows

- osquery/events/darwin/iokit.cpp
> iokit: Fix race when accessing port_

- osquery/dispatcher/dispatcher.cpp
The Windows build of osquery does not support a debug build. Change debug logs in the dispatcher to be verbose.
Run osquery with the verbose flag:
```
C:\>osquery.exe --D --allow_unsafe --verbose
I0407 12:54:16.810698 16600 init.cpp:345] osquery initialized [version=4.2.0]
I0407 12:54:16.857560 16600 system.cpp:335] Found stale process for osqueryd (29216)
I0407 12:54:16.857560 16600 system.cpp:367] Writing osqueryd pid (21244) to \Program Files\osquery\osqueryd.pidfile
I0407 12:54:16.873204 16600 extensions.cpp:376] Could not autoload extensions: Failed reading: \Program Files\osquery\extensions.load
I0407 12:54:16.873204 16600 dispatcher.cpp:78] Adding new service: WatcherRunner (0000028172CE6B60) to thread: 17544 (0000028172CF3030) in process 21244
```
> Change calls to debug log to be verbose

- osquery/tables/system/CMakeLists.txt
- osquery/tables/system/windows/hvci_status.cpp
- specs/CMakeLists.txt
- tests/integration/tables/CMakeLists.txt
- tests/integration/tables/hvci_status.cpp
> Build hvci_status table with CMake

- docs/wiki/deployment/process-auditing.md
> Add documentation for enabling socket_events on macOS

- libraries/cmake/source_migration/modules/Findlinenoise-ng.cmake
> Build linenoise-ng from source on macOS and Windows

- libraries/cmake/formula/openssl/CMakeLists.txt
Fixes https://github.com/osquery/osquery/issues/6430
> Update openssl from 1.1.1f to 1.1.1g

- osquery/tables/system/linux/deb_packages.cpp
- osquery/tables/system/linux/npm_packages.cpp
- osquery/tables/system/linux/rpm_packages.cpp
- specs/linux/deb_packages.table
- specs/linux/npm_packages.table
- specs/linux/rpm_packages.table
- tests/integration/tables/deb_packages.cpp
- tests/integration/tables/npm_packages.cpp
- tests/integration/tables/rpm_packages.cpp
These are other 3 tables that use what has been implemented in PR #6209.
> Add container access to DEB, RPM, NPM packages tables

- osquery/tables/system/linux/os_version.cpp
- specs/os_version.table
- tests/integration/tables/os_version.cpp
This is another table that uses what has been implemented in PR osquery/osquery#6209.
> Add container access to the os_version table

- docs/wiki/development/creating-tables.md
I noticed the new table tutorial was not working correctly. Some of the guidance needed a refresh given build and test changes.
> docs: Improve the new table tutorial

- docs/wiki/deployment/performance-safety.md
- specs/denylist
- tools/codegen/genapi.py
- tools/codegen/gentable.py
- tools/codegen/templates/denylist.cpp.in
- tools/tests/utils.py
- Remove racialized language.
This is an internal concept, so should not really effect users.
Part of #6475
> Change compile time 'blacklist' to 'denylist'

- docs/wiki/installation/cli-flags.md
- osquery/include/osquery/registry_interface.h
- packs/windows-hardening.conf
I checked the TechNet documentation to make sure we are using consistent terminology: https://docs.microsoft.com/en-us/windows-server/identity/software-restriction-policies/software-restriction-policies-technical-overview
> Update documentation to use 'allow list' and 'deny list' diction

- docs/wiki/installation/install-macos.md
Supersedes https://github.com/osquery/osquery/pull/6420
> docs: Remove references to brew in macOS install

- osquery/remote/http_client.cpp
It seems the Windows version of `async_resolve`, combined with other osquery pluming will leak handles. This moves the HTTP client implementation back to using a sync resolve. 
Fixes #6125.
> http: Use sync resolve

- osquery/remote/http_client.cpp
- osquery/remote/http_client.h
- osquery/tables/cloud/aws/ec2_instance_metadata.cpp
- osquery/utils/aws/aws_util.cpp
- osquery/utils/aws/aws_util.h
- osquery/utils/azure/azure_util.cpp
> bug: Do not use system proxy for AWS local authority

- .github/ISSUE_TEMPLATE/New_Release.md
See https://github.com/osquery/osquery-site/issues/172
> docs: Add note to bump the Homebrew cask

- osquery/tables/CMakeLists.txt
- osquery/tables/cloud/CMakeLists.txt
- osquery/utils/azure/azure_util.cpp
- specs/CMakeLists.txt
- tests/integration/tables/azure_instance_metadata.cpp
- tests/integration/tables/azure_instance_tags.cpp
> build: Add Azure tables to specs CMakeLists

- CHANGELOG.md
Add additional changelog items
> Add additional changelog items

- docs/wiki/development/building.md
Depends on: https://github.com/osquery/osquery/pull/6528
> CPack: Update and uniform instructions to build a package

- tools/tests/utils.py
The python test utilities package now catches NoSuchProcess exceptions correctly and no longer attempts to collect the number of file descriptors on windows platforms (where the data are unavailable from the psutil package).
This fixes issue #5560
> fix the test utility to allow windows profiling

- osquery/core/sql/diff_results.h
- osquery/core/sql/scheduled_query.h
- osquery/core/tests/query_tests.cpp
- osquery/dispatcher/scheduler.cpp
- osquery/dispatcher/scheduler.h
Just a lot of code cleanups.
I do hope this file is a bit easier on the eyes than before.
> Scheduler refactor

- osquery/tables/networking/curl_certificate.cpp
- specs/curl_certificate.table
- tests/integration/tables/curl_certificate.cpp
tests for the table `curl_certificate` - Fix #5061
> curl_certificate test

- osquery/registry/registry_interface.cpp
> bug: Fix race in removing external TablePlugins

- osquery/events/windows/windowseventlogpublisher.cpp
It seems like we are reading configuration without checking the max size.
> Add check for character_frequencies size

- osquery/tables/events/linux/process_events.cpp
By looking at a graph of CPU usage for the Linux audit event publishers, it seems like we can save some CPU usage on this hot path. The `selectAllFrom` is a convenience function to abstract what `file` returns. We do not need the x-platform feature from this, nor most of the returned results. So we can call `stat` directly in the callback.
> events: Remove selectAllFrom from linux process events callback

- docs/wiki/deployment/process-auditing.md
Super small docs typo which I noticed linking to a schema version.
> Update process auditing docs schema link.

- tools/tests/CMakeLists.txt
- tools/tests/test_base.py
- tools/tests/test_osqueryd.py
- tools/tests/test_osqueryi.py
I plan to make improvements to these tests but the first step is re-enabling them as they worked before.
> tests: Restore test_osqueryi

- osquery/tables/forensic/CMakeLists.txt
- osquery/tables/forensic/carves.cpp
This is a small change to port `select * from carves` to use JSON instead of ptree parsing.
> carver: Update table to use JSON

- docs/wiki/development/config-plugins.md
- docs/wiki/development/creating-tables.md
- docs/wiki/development/logger-plugins.md
- docs/wiki/development/options-arguments.md
- docs/wiki/development/osquery-sdk.md
- docs/wiki/development/pubsub-framework.md
- docs/wiki/development/unit-tests.md
- docs/wiki/installation/cli-flags.md
- docs/wiki/installation/custom-packages.md
- docs/wiki/installation/install-linux.md
- docs/wiki/installation/install-macos.md
- docs/wiki/installation/install-windows.md
Another documentation PR of manageable size, a follow-on to #6662
> Documentation copy edit pt 2

- docs/wiki/development/building.md
- docs/wiki/installation/install-macos.md
I've gone through our build steps documentation and discovered some minor things to update. See commit messages.
> Update documentation around build steps

- docs/wiki/deployment/configuration.md
> Document max interval

- osquery/filesystem/windows/fileops.cpp
Fix for #6204. Documented way to check if two file paths refer to the same underlying file is documented in `BY_HANDLE_FILE_INFORMATION` structure in [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information) under nFileIndexLow.
Test which validates this is: FilesystemTests.test_safe_permissions*
> bugfix-6204: fix dirPathsAreEqual the documented way

- osquery/tables/system/windows/certificates.cpp
- tests/integration/tables/certificates.cpp
Fix for bug #6719. Not sure how or why had I added PUNYCODE flag to these calls before....
Fixes #6719
> bugfix-6719: removing PUNYCODE flag

- osquery/events/linux/bpf/bpfeventpublisher.cpp
- osquery/events/linux/bpf/bpfeventpublisher.h
- osquery/events/linux/bpf/isystemstatetracker.h
- osquery/events/linux/bpf/systemstatetracker.cpp
- osquery/events/linux/bpf/systemstatetracker.h
- osquery/events/tests/linux/bpf/bpfeventpublisher.cpp
- osquery/events/tests/linux/bpf/systemstatetracker.cpp
Requires: https://github.com/osquery/osquery/pull/6721
> BPF: Implement additional syscalls to track fd usage

- osquery/registry/registry_interface.cpp
- osquery/registry/registry_interface.h
> Fix deadlock when registering two extensions

- cmake/flags.cmake
> Remove unused LTCG flag

- .buckconfig
> Remove a Buck leftover

- CHANGELOG.md
> CHANGELOG 4.6.0

- osquery/sql/sqlite_util.cpp
- osquery/sql/sqlite_util.h
Set up an allowlist for PRAGMA commands in the authorizer. Allow the
PRAGMAs for listing table schema and available functions.
Closes #6813
> Allow table info PRAGMAs

- libraries/cmake/formula/openssl/CMakeLists.txt
> Update openssl to version 1.1.1i

- .github/ISSUE_TEMPLATE/Question.md
- README.md
> Doc: Fix incorrect Slack urls

- plugins/config/parsers/views.cpp
This gives a 10x execution speed boost to the config fuzzer.
> Avoid running queries for views when fuzzing

- CONTRIBUTING.md
- README.md
We spoke about this process in the office hours but I think it is helpful for folks to have it some place more discoverable.
> Update README to include release process comment

- docs/wiki/development/creating-tables.md
Easy navigation and easy reading for others
> Fix broken url in docs

- libraries/cmake/source/thrift/patches/src/0002-THRIFT-5078-Handle-named-pipe-clients-quickly-discon.patch
Fixes #4280
@mike-myers-tob do you have a way to test this?
Generated from `apache/thrift` using:
```
git checkout e56f717b7f62ba5b1ace7382d728ac7f0fda940f
git format-patch -1 HEAD
```
> Add patch for apache/thrift #5078

- osquery/dispatcher/scheduler.cpp
https://github.com/osquery/osquery/issues/6923
> Update the scheduler to log the query name at info level

- osquery/events/linux/bpf/bpfeventpublisher.cpp
This PR upgrades the ebpfpub library and changes the execve/execveat function tracers from tracepoint to kprobes to work around a (linux kernel?) bug (https://github.com/osquery/osquery/pull/6802#issuecomment-744650811) so that process creation detection is more reliable.
The patch also makes the build work on AArch64 without having to disable BPF. The publisher will however not work correctly, due to another bug related to bpf_probe_read_str. This prevents osquery from capturing strings (like the filename in execve) and buffers (i.e.: sockaddr structures).
EDIT:
Here is the publisher output on AArch64. It seems like the logic to capture strings and buffers fail really often, but I am not sure there's anything we can do about it. I was able to reproduce the same problem using execsnoop …
> bpf: Improve execve/execveat tracing, add AArch64 build support

- osquery/tables/system/tests/linux/extended_attributes_tests.cpp
Do not expect that the extended attributes list of a test file
contains only the attributes that have been set by the test.
Check that the extended attributes set by the test are all present
instead.
Fixes #6867
> Fix ExtendedAttributesTableTests failing due to an unexpected attribute

- plugins/logger/tls_logger.cpp
> Initialize TLSLogForwarder before enrollment check

- docs/wiki/development/building.md
- docs/wiki/installation/install-linux.md
The install paths for Linux have changed since the last time the docs were accurate, so I've tried to remedy that.
> Update the Linux install steps and package listing

- osquery/tables/system/posix/augeas.cpp
> augeas: Clear aug pointer on error

- docs/wiki/deployment/debugging.md
- osquery/devtools/shell.cpp
This adds a helpful debugging feature to the shell, the ability to run queries against other osquery processes.
> shell: Add .connect meta command

- docs/wiki/development/building.md
> Update docs to describe how to build for aarch64/arm64 (#6285)

- osquery/sql/sqlite_util.h
Users may use transactions to manage temp tables. Add to the authorizer
Fixes: #7013
> Add transactions to the pragma/actions authorizer allow list

- specs/windows/windows_events.table
> Correct the example in the windows_events table spec

- .github/FUNDING.yml
> Add funding link on GitHub generated page

- docs/wiki/deployment/configuration.md
> config: Add docs for the events top-level-key

- osquery/remote/enroll/enroll.cpp
Ensure the appropriate locking exists around access/modification of the
node key so that the duplicate enrollment issue described in #6993 does
not occur.
Fixes #6993
> Guard node key to prevent duplicate enrollments

- osquery/events/eventsubscriberplugin.cpp
- osquery/events/eventsubscriberplugin.h
- osquery/events/tests/eventsubscriberplugin.cpp
This is a small refactor of some internal events subscriber code to facilitate more testing. I was reviewing the `--events_optimize` features and found them to work as intended (as far as I can tell). But I wanted to extend test coverage slightly.
> Small events subscriber refactor to increase test coverage

- CHANGELOG.md
> 4.8.0 changelog

- osquery/events/linux/auditdnetlink.cpp
When inspecting the syscalls via the linux audit framework, it's
recommended to have as trimmed down rules as possible. osquery
originally installed individual syscall watches without any custom
filters for each syscall. That can lead to a lot of implicit filtering
within kauditd since it needs to match an event through upto 35 syscalls
individually.
Libaudit allows adding multiple syscalls to be added in the same audit
rule data. This can lead to matching all of the syscalls in a single
match within the kernel. For the record, an audit rule contains an array
that contains information about what syscalls it needs to match within a
bitmap. Which means, multiple syscalls can be matches efficiently using
bitmasks. In practice this leads to much better cpu consumption.
For the audit rules of …
> Consolidate syscalls to a single audit rule

- plugins/database/rocksdb.cpp
This addresses #7079 but makes logs more susceptible to data loss if a process crashes.
> rocksdb: Do not fsync WAL writes

- osquery/process/windows/process_ops.cpp
- osquery/tables/yara/yara.cpp
- osquery/tables/yara/yara_events.cpp
> Minor cleanup of unused variables

- osquery/extensions/interface.cpp
Fix for https://github.com/osquery/osquery/issues/7118
> 7118: Make generaing an extension uuid thread safe

- libraries/cmake/source/librdkafka/CMakeLists.txt
- libraries/cmake/source/librdkafka/config/aarch64/linux/config.h
- libraries/cmake/source/librdkafka/config/x86_64/linux/config.h
- libraries/cmake/source/librdkafka/config/x86_64/macos/config.h
Fixes https://github.com/osquery/osquery/issues/7097
> libs: Update librdkafka to version 1.7.0

- libraries/cmake/source/yara/CMakeLists.txt
- libraries/cmake/source/yara/patches/src/yara-strutils.patch
Fixes https://github.com/osquery/osquery/issues/7123
> libs: Update libyara to version 4.1.1

- osquery/config/packs.cpp
Do not merge until 5.0
Fixes: #6491
> Remove deprecated `blacklist` key (BreakingChange)

- CHANGELOG.md
- docs/wiki/installation/cli-flags.md
- osquery/config/tests/packs.cpp
- osquery/sql/tests/sqlite_util_tests.cpp
- osquery/tables/system/linux/pci_devices.cpp
- osquery/tables/system/posix/sudoers.cpp
- osquery/tables/system/windows/shimcache.cpp
- osquery/tables/system/windows/userassist.cpp
- osquery/utils/schemer/json/schemer_json.h
- osquery/utils/windows/shellitem.cpp
- tools/tests/test_osqueryd.py
Fix spelling. The result of an occasional run of a spellchecker.
> Spelling fixes

- .github/workflows/build_aarch64.yml
- .github/workflows/build_x86.yml
For when osquery/osquery-packaging#9 lands
> [macOS][packaging] Update the packaging repo commit for #7236 related fixes

- osquery/events/linux/auditdnetlink.cpp
The audit rules were not getting removed when osquery exits as part of
the cleanup process. This was due to not adding the audit rule to the
cleanup list unless osquery was run with `--audit_force_unconfigure`. The
force unconfigure option is to remove the rules irrespective of the their
install exit code which was not followed in the #7063.
The current fix is going to install the rule for cleanup either the error
code is non-negative or osquery is asked to force reconfigure. This would
also fix the double adding of the audit rules as mentioned in #7205.
> Fix audit rule removal upon osquery exit

- osquery/sql/sqlite_util.h
Add a couple more pragmas. One requested, and one that looks reasonable to add. See https://www.sqlite.org/pragma.html
Fixes: #7266
> Add case sensitive pragma to the pragma/actions authorizer allow list

- .github/workflows/build_aarch64.yml
- .github/workflows/build_x86.yml
- CMakeLists.txt
Create an app bundle structure along side the other `package_data`
> [macOS][packaging] Create an app bundle along with other package_data

- .github/workflows/build_aarch64.yml
- .github/workflows/build_x86.yml
- CMakeLists.txt
Fixes: #7237
Other changes upcoming in the packaging repo
> [linux][packaging] Update packaging paths

- libraries/cmake/formula/openssl/CMakeLists.txt
> libs: Update OpenSSL to version 1.1.1l

- docs/wiki/deployment/process-auditing.md
- docs/wiki/installation/cli-flags.md
Addresses #7277 
Minor update to macOS docs for ESF. I have tested this sample config.
> docs: update macOS ESF documentation

- docs/wiki/introduction/sql.md
Spotted this tiny typo reading the docs.
> Fix typo in SQL docs

- .github/workflows/build_aarch64.yml
- .github/workflows/build_x86.yml
- cmake/install_directives.cmake
Fixes #7327
Depends on osquery/osquery-packaging#19 getting merged first.
> Restore query packs in Windows packaging

- .github/ISSUE_TEMPLATE/Question.md
> Update github issue template to link to slack

- CHANGELOG.md
> CHANGELOG 5.1.0

- osquery/main/harnesses/fuzz_utils.cpp
The detach operation uses the DROP TABLE sql query to remove a table,
but this doesn't work with eponymous tables.
Use the "disable_tables" flag instead,
which prevents the initialization of the specified tables.
> Fix how we disable tables in the fuzzer init method

- libraries/cmake/source/boost/CMakeLists.txt
This define got lost with the library update
> Add BOOST_USE_ASAN define when enabling Asan

- osquery/tables/system/darwin/processes.cpp
Use the time base conversion coming from mach_timebase_info
also for the cpu time values coming from the libproc API.
The user_time and system_time columns values are taken
from the proc_pid_rusage API values of ri_user_time and
ri_system_time.
The unit of those two values was incorrectly considered
to always be nanoseconds, but they are mach ticks,
much like the start_time that is later calculated
via mach_absolute_time.
While on x86_64 the time base info used to convert ticks to nanoseconds
returns a numerator and denominator that are both 1,
on M1 they are not (125 and 3 is one example).
Fixes #7459
> Fix user_time and system_time unit in processes table on M1

- libraries/cmake/source/expat/CMakeLists.txt
- libraries/cmake/source/expat/README.md
- libraries/cmake/source/expat/config/linux/expat_config.h
> libs: Update expat from version 2.2.10 to 2.4.7

- CONTRIBUTING.md
Relates to: https://github.com/osquery/foundation/issues/82 https://github.com/osquery/foundation/issues/81
> Update the TSC members

- tools/tests/test_release.py
Correct the list of expected linked libraries
depending on the architecture.
> Fix release tests for Linux aarch64

- docs/wiki/installation/cli-flags.md
Related to https://github.com/osquery/osquery/pull/7516
> Correct the section where the users and groups service flags are described

- osquery/logger/logger.cpp
- tools/deployment/osquery.example.conf
Related to https://github.com/osquery/osquery/issues/6533
> Remove CLI flags settings from osquery.example.conf

- osquery/tables/utility/time.cpp
**Timezone configuration**
```
Z:\osquery>tzutil /g
GMT Standard Time
```
**Without the TZ environment variable**
```
Z:\osquery> osqueryd.exe -S "SELECT timestamp, datetime, timezone, local_timezone FROM time;"
+------------------------------+----------------------+----------+----------------+
| timestamp                    | datetime             | timezone | local_timezone |
+------------------------------+----------------------+----------+----------------+
| Mon Jun 27 13:33:45 2022 UTC | 2022-06-27T13:33:45Z | UTC      | UTC            |
+------------------------------+----------------------+----------+----------------+
```
**With the TZ environment variable**
The environment variable is applying but osquery is not able to parse it correctly
```
Z:\osquery>set TZ=IST-5:30
```
``` …
```
> time: Fix the Windows local_timezone column value

- libraries/cmake/source/libarchive/config/linux/aarch64/config.h
- libraries/cmake/source/libarchive/config/linux/x86_64/config.h
- libraries/cmake/source/libarchive/config/macos/aarch64/config.h
- libraries/cmake/source/libarchive/config/macos/x86_64/config.h
- libraries/cmake/source/libarchive/config/windows/x86_64/config.h
> libs: Update libarchive to version 3.6.1

- osquery/tables/system/windows/tpm_info.cpp
Fixes https://github.com/osquery/osquery/issues/7687
> tpm_info: Refactor, ensure boolean values are always up to date

- ASSURANCE.md
- docs/wiki/deployment/dependency-security.md
- docs/wiki/index.md
> Add documentation about 3rd-party dependency security

- osquery/tables/system/darwin/smbios_tables.cpp
Add port for the `platform_info` for M1 Macs, where the information is in different locations in the IODeviceTree registry.
The following columns appear to not have a equivalent data on M1 Macs:
- `vendor`
- `volume_size`
- `size`
- `date`
- `version`
> Port platform_info table to M1 Macs

- tests/integration/tables/mdfind.cpp
Instead of searching for a hardcoded file name,
which might not be indexed yet, sample what is indexed,
then choose one of those to further test the API.
Also remove the Spotlight running test since it's incorrect.
The process that's doing the indexing is mdworker,
but we cannot check if it's actively indexing or not.
Assume actively indexing is the correct state and so
we shouldn't accept an empty result for the initial wide query.
Fixes #7531
> test: Fix Mdfind.test_sanity flakyness

- osquery/tables/system/darwin/unified_log.mm
The `@available` check cannot be negated; the compiler won't recognize it
and it will warn about non compatible APIs used if this runs
on macOS < 10.15.
Fix a tautological comparison on the constraints operators
used for timestamp.
Correct spelling of sentinel.
> Correct macOS version support check for unified_log.mm

- tests/integration/tables/memory_devices.cpp
Adds validation integration test for the `memory_devices` table.
> Add validation integration test for memory_devices

- CHANGELOG.md
Changelog for 5.5!
And some bonus commits that got missed in the 5.3.0 changelog
> CHANGELOG 5.5.1

- osquery/tables/applications/posix/docker.cpp
Brings the macOS code up to parity with the Linux code. Previously, it
seems like we were intentionally providing arguments that were ignored
by the Docker API on
macOS (https://github.com/osquery/osquery/pull/4163#discussion_r171316517),
but at some point those were no longer ignored and that started causing
issues (Docker API returning 500 error due to unknown arguments,
specifically `wq`). As of today, the Docker API on macOS seems to
support the same arguments as on Linux.
This also has the effect of returning all of the same data (more
complete) on macOS as is provided on Linux.
Tested on macOS 12.5.1, Docker Desktop 4.11.1 and 4.0.0 (1 year old
version).
> Fix `docker_container_processes` on macOS

- docs/wiki/deployment/yara.md
- osquery/tables/yara/yara_utils.cpp
Took a stab at correcting the documentation for Yara signatures retrieved from urls.
Fixes: https://github.com/osquery/osquery/issues/7308
> docs: Correct the description on how to configure and use Yara signature urls

- osquery/tables/system/windows/wmi_bios_info.cpp
```bash
alessandro@win11-annie MINGW64 /z/osquery (alessandro/feature/improve-wmi_bios_info-windows-table)
$ ../build/osquery/osqueryd -S 'SELECT * FROM wmi_bios_info;'
+--------------------------------+-------------------------------+
| name                           | value                         |
+--------------------------------+-------------------------------+
| BIOSVersion                    |                               |
| BuildNumber                    |                               |
| Caption                        | 0.0.0                         |
| CodeSet                        |                               |
| CurrentLanguage                |                               |
| Description                    | 0.0.0                         |
| IdentificationCode …
```
> `wmi_bios_info`: Include Win32_BIOS attributes for all systems

- specs/yara/yara.table
- specs/yara/yara_events.table
I've been learning about YARA and found that the descriptions in the table were not very informative. I think this is my best understanding of what the two YARA tables do. I think it might be more informative/clear for newcomers?
> Document difference between `yara` and `yara_events`

- specs/darwin/keychain_items.table
> Fixing typo in keychain_items

- docs/wiki/deployment/yara.md
Added a brief explanation of YARA and a link to the documentation.
> Add link to YARA docs

- tools/tests/test_base.py
A little helper option to more easily exercise selected python testcases in a test suite.
> test: Add an option to run only selected python testcases

- libraries/cmake/source/zlib/README.md
- libraries/third_party_libraries_manifest.json
This also resolves CVE-2022-37434
Fixes #7862
> libs: Update zlib to 1.2.13

- osquery/main/windows/main.cpp
Thank you @dreisel  for the bug report 
Closes #7604
> Propagate windows errors to the exit code

- libraries/third_party_libraries_manifest.json
> cve: Ignore sqlite CVE-2022-46908

- osquery/tables/system/windows/scheduled_tasks.cpp
Addresses leaks in scheduled_tasks table (https://github.com/osquery/osquery/issues/7903)
> Fix leaks in scheduled_tasks (#7903)

- CODE_OF_CONDUCT.md
> Fixes broken link

- osquery/filesystem/windows/fileops.cpp
This fixes a bug where osqueryd.exe cannot be executed from some privileged directories because when the binary is copied to a directory with write permissions to either of these (such as a subdirectory in "C:\\Program Files") it will have invalid permissions. 
Tested and confirmed it solves this bug.
> Relax osquery safe permissions check

- osquery/core/windows/wmi.cpp
This fixes #7962 by setting the COM security per interface level using IClientSecurity interface.
> Fix COM security initialization  by setting COM security per interface level

- osquery/process/windows/process.cpp
Hi!
The main goal of this PR is to remove redundant memory copying of process arguments into `std::vector<WCHAR>`.
This is possible since C++17 that I believe is the version of C++ standard used by the osquery project.
I also changed a bit two other functions and I can remove these changes if it looks unrelated to the PR.
This is my first PR in this project, so please correct me if I did something wrong.
I have only a Mac machine at the moment and I hope that CI build can check compilation and run tests for this part of the code.
> Do not copy process arguments into vector for CreateProcess call

- osquery/tables/cloud/aws/ec2_instance_metadata.cpp
For instance when an EC2 instance doesn't have a configured ssh key,
the openssh metadata endpoint is not present.
Log the 404 as verbose instead.
> Do not consider a 404 as an error in ec2-instance-metadata

- .github/workflows/self_hosted_runners.yml
Update the workflow to point to the action in the osquery repo.
Also update which version of the action we are using.
Fixes #8034
> Fix the aarch64 workflow

- .github/workflows/hosted_runners.yml
- docs/wiki/development/building.md
- docs/wiki/installation/install-macos.md
> [build] update macos hosted github runner to macos-12 monterey

- libraries/third_party_libraries_manifest.json
> cve: Ignore dbus CVE-2023-34969

- libraries/third_party_libraries_manifest.json
> cve: Ignore libcap CVE-2023-2603

- osquery/tables/system/linux/block_devices.cpp
- specs/posix/block_devices.table
> Revert "Add some indexing to `block_devices`"

- CHANGELOG.md
Update the 5.10.1 changelog to be for 5.10.2, and include new commits.
> Changelog 5.10.2

- CHANGELOG.md
> docs: Correct link to a PR in the 4.7.0 changelog

- libraries/cmake/source/zlib/CMakeLists.txt
- libraries/cmake/source/zlib/README.md
- libraries/third_party_libraries_manifest.json
Ignore the Minizip CVE-2023-45853
Fixes #8167
> cve: Update zlib to 1.3 and ignore a CVE

- osquery/tables/networking/posix/dns_resolvers.cpp
Fix https://github.com/osquery/osquery/issues/8328
> Fix dns_resolvers dns-search bug with multiple search domains

- osquery/remote/utility.h
#8322
Currently, if distributed TLS requests to `--distributed_tls_read_endpoint` and `--distributed_tls_write_endpoint` fail on the TCP/IP or TLS layer, or if the JSON in the response could not be parsed, osquery shows nothing and retries.
E.g. if osquery is configured with `--distributed_tls_max_attempts=3` and the server is down or not returning a JSON response you just get:
```
265887 I0430 11:55:03.687932 29520 tls.cpp:263] TLS/HTTPS POST request to URI: https://example.com/api/v1/osquery/distributed/write
265891 I0430 11:55:05.651844 29520 tls.cpp:263] TLS/HTTPS POST request to URI: https://example.com/api/v1/osquery/distributed/write
265892 I0430 11:55:10.595957 29520 tls.cpp:263] TLS/HTTPS POST request to URI: https://example.com/api/v1/osquery/distributed/write
```
Which does not …
> Add verbose logging when distributed requests fail and retry

- osquery/sql/sqlite_encoding.cpp
> Make fallthrough explicit in sqlite_encoding.cpp

- libraries/cmake/source/librpm/README.md
- libraries/cmake/source/librpm/build-patches/build-remove-lua.patch
- libraries/cmake/source/librpm/config/aarch64/config.h
- libraries/cmake/source/librpm/config/x86_64/config.h
- libraries/cmake/source/librpm/patches/src/remove-lua.patch
- libraries/third_party_libraries_manifest.json
> libs: Update rpm to 4.18.2

- specs/darwin/alf_explicit_auths.table
> Update description for alf_explicit_auths.

- docs/wiki/development/building.md
Derived from instructions provided by @sharvilshah.
> Add documentation for testing macOS EndpointSecurity

- osquery/config/packs.cpp
closes #8480 
Added chrono header file to avoid regression issues due to microsoft MSVC STL
> Added chrono header file

- osquery/tables/networking/darwin/wifi_status.mm
Fixes https://github.com/osquery/osquery/issues/8220
From Fleet: https://github.com/fleetdm/fleet/issues/22195
This PR updates the source of the `network_name` column value in the `wifi_status` table. This value was previously copied from the ssid property of the interface retrieved via CWWiFiClient, but this is no longer available in MacOS 14.x (Sonoma). Instead, we'll now retrieve it from the system profiler, which still returns the current WiFi network name on newer OS X versions.
I'm open to ideas on what a good test addition would be here.  Mocking the system profiler and `CWWiFiClient` responses would make a pretty watered-down test IMO.  I could pull the code that maps MAC addresses to network names into a separate method and unit test that if that sounds worthwhile.  
I did test …
> Fix `wifi_status` to correctly gather `network_name` on MacOS 14+

- osquery/tables/system/python_packages.cpp
For https://github.com/fleetdm/fleet/issues/22236
Added two missed paths for python packages.
Added support for scanning simple paths in user directories. The code
now checks to see if the path can be expanded using `traverseVersions`
otherwise just uses the regular `resolveFilePattern` method to expand
any `%` in the specified path.
> Added RHEL paths for `python_packages` table

- osquery/utils/system/windows/users_groups_helpers.cpp
- Fix a memory leak in getGroupSidFromUsername (leaked the allocated Sid buffer)
- Improve Unicode support in psidToString by moving to ConvertSidToStringW
> Fixes in windows helpers

- osquery/tables/system/posix/shell_history.cpp
Update shell_history.cpp to account for .ash_history files
> Update `shell_history` table to include ash

- osquery/tables/system/windows/prefetch.cpp
- tests/integration/tables/prefetch.cpp
> Fix Prefetch table for Windows 11

- .github/workflows/hosted_runners.yml
- docs/wiki/development/building.md
Attempt to fix one of the many issues in https://github.com/osquery/osquery/issues/8593#issuecomment-3041428870.
Remaining fix for SDK 16.4 is an issue with Boost.
> Fix build for XCode SDK 16.4

- docs/wiki/development/building.md
We discussed this issue in office hours.
Adding the workaround to the docs until we can fix https://github.com/osquery/osquery/issues/8593.
> Update build instructions for workaround for XCode SDK > 16.3

- tools/ci/scripts/cve/third_party_libraries_cves_scanner.py
Small PR to add a disclaimer to the automatically opened CVE issues
> Enhance issue description with automation note
