osquery/carver/CMakeLists.txt
osquery/carver/carver.cpp
osquery/carver/carver.h
osquery/carver/carver_utils.cpp
osquery/carver/carver_utils.h
osquery/carver/tests/carver_tests.cpp
osquery/dispatcher/CMakeLists.txt
osquery/dispatcher/scheduler.cpp
osquery/dispatcher/scheduler.h
osquery/sql/sqlite_operations.cpp
osquery/tables/forensic/carves.cpp

This change refactors the carver code and functionality.
From a functionality perspective, carving is now implemented using a request and handler model. Carving can be requested via the SQLite `carve` function or using the predicate `WHERE carve=1` on the `osquery_carves` table. Previously when a carve was requested, the carving and posting to a remote endpoint would occur during query execution. Now carve requests are buffered and the scheduler thread periodically "wakes up" a carving thread that handles the requests. Additionally, carving is now unique to `osqueryd` and the metadata from successful carve requests will be removed from osquery's internal database after 24hours.
From a code point of view the implementation is split into a "carver utilities" set that can be widely …

carver: Refactor carver to use the Scheduler

---

osquery/tables/system/windows/certificates.cpp
osquery/tables/system/windows/registry.cpp
osquery/tables/system/windows/users.cpp

Free up memory allocated by ConvertStringSidToSid with calls to LocalFree (as described under Sid parameter in [here](https://docs.microsoft.com/en-us/windows/win32/api/sddl/nf-sddl-convertstringsidtosida)) as per bug ticket #6560.

bugfix-6560: free memory allocated by ConvertStringSidToSid

---

specs/linux/kernel_modules.table

This fixes https://github.com/osquery/osquery/issues/6711
this makes size consistent with other size fields in the schema like deb_packages.

type of size field in kernel_modules table should be BIGINT

---

osquery/tables/networking/linux/iptables.cpp
osquery/tables/networking/linux/iptc_proxy.h
osquery/tables/networking/tests/linux/iptables_tests.cpp

This isn't a formatted or tested PR, just wanted to throw this up so I could highlight the issues and how I'm thinking about fixing them to get feedback.
Our QA team identified two issues with the iptables table:
1. The chain default row is being stomped on by the last rule row being output, so it's outputting a duplicate row instead of the default policy for the chain. The fix is to create a copy of the chain row, update it with the rule data, and then move it into the result set. That leaves the chain rule alone.
2. There's a bitfield that specifies which match fields in the rule are logical negations. That information was not being included in the output. In this PR I prefix any negated fields with !.

Fix missing negations, duplicate rows in iptables table

---

osquery/tables/networking/darwin/wifi.mm
osquery/tables/networking/tests/darwin/wifi_tests.mm

I've added a macOS version check, and if the version is 10.15 or above, it references a changed key name for the field in the plist that fills the `last_connected` column, restoring the functionality of that column.
Related to #6235

Fix last_connected column in wifi_networks on Catalina

---

libraries/cmake/source/thrift/CMakeLists.txt

Windows build was broken on newer MSVC:
It couldn't find the random_shuffle identifier:
```
TSocketPool.cpp(191): error C3861: 'random_shuffle': identifier not found 
```
Supersedes #6725

build: Fix windows build on newer MSVC

---

docs/wiki/deployment/process-auditing.md

This PR updates the tracing logic for the fork/vfork/clone system calls, allowing osquery to retrieve PIDs in the host namespace even when using containers

BPF: Add container support to fork/vfork/clone

---

packs/unwanted-chrome-extensions.conf

Updating the unwanted-chrome-extensions query pack with three new extensions that were recently compromised and made tech news sites. Extensions have been removed by Google from Chrome Web Store. Since removal from the Chrome Web Store does not remove already installed extensions, this query will allow users of osquery to monitor their endpoints for these malicious extensions.
References:
https://chris.partridge.tech/2020/extensions-the-next-generation-of-malware/help-for-users/
https://arstechnica.com/information-technology/2020/10/popular-chromium-ad-blockers-caught-stealing-user-data-and-accessing-accounts/

Updated unwanted-chrome-extensions

---

packs/it-compliance.conf

The usb_devices table and respective query in the packs/it-compliance.conf pack is posix only.

Make the usb_devices pack query available only on posix

---

osquery/tables/applications/browser_chrome.cpp

Yandex Browser (https://browser.yandex.com/) is a popular Chromium-based browser on Windows, macOS and Linux. However, chrome_extensions table doesn't check its extensions.
This PR adds default paths for Yandex Browser extensions.
For Linux systems the default path `/.config/yandex-browser%/%/Extensions/` has the first `%`-sign because currently it's `yandex-browser-beta`. Thus, in case of future changes we don't need to fix the code one more time.
The PR was successfully tested on Ubuntu 18.04 x64 (5.3.0-28-generic) and Windows 10 1809 17763.1217.  Unfortunately, I experience difficulties building osquery for macOS Catalina (10.15.7) which aren't connected with the PR.

Add Yandex Browser support for chrome_extensions

---

osquery/utils/aws/aws_util.cpp

Enables use of AWS Instance profile as a credential provider on Windows 
Depends on: #6749

Enable AWS Instance profile as credential provider on Windows

---

osquery/remote/http_client.cpp

This PR switches the OpenSSL call used to load the client cert file into the context to use one which allows specifying a PEM cert **chain** rather than just a single-cert PEM file.  This allows use of client certs that are issued from intermediate CAs (as are widely deployed in our infrastructure).  The existing code assumes that the client cert will chain directly up to the server's trusted root CA, which is incorrect as TLS allows for either peer to supply a cert chain and the root CA should be all that is necessary to verify the supplied chain.
This PR changes from calling `use_certificate_file` to `use_certificate_chain_file`, which is compatible with `use_certificate_file` **with the exception** that `use_certificate_file` allows the caller to specify that the file is in ASN.1 …

Fixes #6752 - support TLS client cert chains

---

osquery/sql/virtual_table.cpp

Reported by cppcheck:
[osquery/sql/virtual_table.cpp:557]: (error) Using 'memset' on struct that contains a 'std::shared_ptr'

Do not use memset on VirtualTable, a non-POD type

---

docs/wiki/deployment/process-auditing.md
docs/wiki/installation/install-linux.md

This PR adds additional notices to the osquery documentation to warn users about the impact on journald audit logs and how to mask those logs from entering the systemd journald if needed.
This problem has been discussed on the following thread in the Osquery[ slack channel](https://osquery.slack.com/archives/C08V7KTJB/p1603126388324400) and @theopolis has recommended to add this to the documentation.
Idea is, by default, systemd journald will collect the audit logs generated by the kernel auditing (something that osquery enables). On busy boxes, we saw that the lack of mask on those logs can greatly affect the performance on the box - for example considerably increasing the disk write operations that can reach limits like the burst allowance ones enforced on AWS so it is really …

Journald Audit Logs Masking Documentation

---

CMakeLists.txt
cmake/options.cmake
libraries/cmake/source/modules/Findebpfpub.cmake
osquery/events/CMakeLists.txt
osquery/events/tests/CMakeLists.txt
osquery/tables/events/CMakeLists.txt
osquery/tables/events/tests/CMakeLists.txt
specs/CMakeLists.txt

CMake: Disable BPF support if the LLVM libs are not compatible

---

osquery/tables/system/darwin/packages.mm

When parsing `/Library/Receipts/InstallHistory.plist` not all entries have a PackageIdentifiers. Allow them to remain unset.
This opts to leave them unset, preserving the underlying data, and does not make assumptions about it
Fixes: #6766

PackageIdentifiers are optional in InstallHistory.plist

---

libraries/cmake/source/rocksdb/CMakeLists.txt
libraries/cmake/source/rocksdb/patches/env_win.h

This PR updates the Windows 7 compatibility patch for RocksDB so that it works with both the Ninja and MSBuild generators

libs: Port the RocksDB Win7 compatibility patch to the MSBuild generator

---

.gitmodules

The gpg-error and libgcrypt repositories often fail cloning.
We use our mirrored version on Github instead.
libcap repository does not support shallow cloning,
change the url to another official mirror which supports it.

Change urls for submodules gpg-error, libgcrypt, libcap

---

osquery/remote/http_client.h
osquery/sql/sqlite_hashing.cpp
osquery/tables/applications/posix/docker.cpp
tests/integration/tables/helper.cpp

All the platforms now build correctly,
even with boost 1.70.

Remove boost workaround introduced in #5591 for string_view

---

azure-pipelines.yml

Since the CI already selects the newest installation of Python,
to then install some additional packages, lets pass the root folder to CMake,
so it doesn't have to detect Python again and possibly select the wrong version.
Remove the need to use Python3 32bit, since it's not necessary
and the Windows installation used is a 64bit one anyway.
Fix pip complaining about the Scripts folder not being in the PATH,
by prepending the PATH with the selected Python installation
root folder and Scripts folder.
Split and reorder the various prerequisite install steps
so that they are closer to each other
and slightly better categorized.

CI: Python installation improvements on Windows

---

azure-pipelines.yml

Small change: runs `brew update` before `brew upgrade`. This fixes things, even though `upgrade` is expected to run `update` automatically it apparently doesn't.

CI: Update brew scripts

---

azure-pipelines.yml
cmake/packaging.cmake

Also add TGZ as a supported package format on macOS,
since it's already used on the CI.
NOTE, to download them:
1. You need to open the CI page which points to a specific build; you can reach that for instance from a PR build results in the `Checks` tab or on the bottom of the `Conversation` tab where all the checks results are shown.
2. You want to follow the `Details` link of the `osquery` check, then `View more details on Azure Pipelines`.
3. On the Azure Pipelines website, you should see the summary of the PR CI build, with all the platforms. On the top right you want to find the following area:
Instead of a `0 artifacts` there's should be written something like `6 published`, click on it.
4. A list of packages grouped by platform and build type should be shown now. You can download …

CI: Make the built packages available to be downloaded

---

docs/wiki/deployment/file-integrity-monitoring.md
osquery/events/CMakeLists.txt
osquery/events/darwin/fsevents.cpp
osquery/events/file_events_flags.cpp
osquery/events/linux/inotify.cpp
osquery/events/tests/darwin/fsevents_tests.cpp
osquery/events/tests/linux/inotify_tests.cpp

This allows Linux users to configure the **process_file_events** table without enabling **file_events** by mistake. Solves issue #5584

file_events: Add configuration flag

---

osquery/tables/system/windows/users.cpp
specs/users.table

Fixes #6411 by advertising and implementing an index on the `uuid` column of the `users` table on Windows, allowing for `JOIN` operations with linear performance instead of exponential.
Although `uid` is the indexed column on POSIX systems, I went with the `uuid` column since it holds SIDs, the preferred (?) unique identifier for Windows users.
The following output shows that the table only generates the required rows in a `JOIN`, rather than all of them.
```
PS C:\Projects\osquery\build> .\osquery\RelWithDebInfo\osqueryi.exe --verbose --planner
I1130 21:31:01.193373  3708 init.cpp:340] osquery initialized [version=4.5.1-50-gc75fd9e3]
I1130 21:31:01.196367  3708 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \Program Files\osquery\extensions.load
I1130 …
```

Add indexed column support to Windows users table

---

CMakeLists.txt
cmake/options.cmake

Due to a bug present in CPack provided with CMake
version 3.18.0 and higher on RPM packages generation,
add a check which fails the configuration
if a version with the bug is found.
Provide a way to ignore the check by setting
OSQUERY_IGNORE_CMAKE_MAX_VERSION_CHECK=TRUE.
This should prevent issue #6755 until a solution has been found on upstream.
NOTE: This shouldn't be merged immediately. When and if we are ok with the PR, we need to do one on the oss-fuzz project first, so that it doesn't fail configuring.

CMake: add max version limit to 3.18.0 on Linux

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/dbus/methods/dbusmethod.h
osquery/tables/system/linux/dbus/methods/getstringproperty.cpp
osquery/tables/system/linux/dbus/methods/getstringproperty.h
osquery/tables/system/linux/startup_items.cpp
osquery/tables/system/linux/systemd_units.cpp
specs/CMakeLists.txt
specs/linux/systemd_units.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/systemd_units.cpp

This PR implements a new Linux table named systemd_units that lists the loaded systemd units.
```
+-------------------------------+-----------------------------------------+------------+--------------+-----------+-----------+----------------------------------------------------------------------+--------+----------+----------+---------------------------------------------------+------+----------------------+
| id                            | description                             | load_state | active_state | sub_state | following | object_path                                                          | job_id | job_type | job_path | fragment_path                                     | user | source_path          |
+-------------------------------+-----------------------------------------+--- …
```

Implement new Linux table systemd_units, listing systemd units

---

docs/wiki/deployment/extensions.md

The `.tables` and `.schema` shell builtins are useful, but in my use-case I need to retrieve the same data via SQL over the Thrift API.

Document retrieval of available tables/columns via SQL

---

osquery/tables/networking/tests/darwin/wifi_tests.mm
tools/tests/configs/test_airport.plist
tools/tests/configs/test_airport_pre_macOS_10.15.plist

- Updates the test input plist file for the `wifi_networks` test, to reflect what the plist looks like on macOS 10.15
- Also removes the test and test input file for macOS 10.9, a way older version of macOS that is not supported by Apple or osquery anymore.
Closes #6722

Fix wifi_tests on macOS 10.15 and above

---

osquery/tables/system/darwin/user_groups.mm

Fixes #6320
Tested on macOS 10.14, 10.15 and 11.0.

macOS: Fix OpenDirectory attribute mismatch

---

azure-pipelines.yml

Even if the macOS image have Python homebrew already installed,
there's the symlink /usr/local/bin/2to3 which points to the
system installed Python.
Normally that file is placed by homebrew Python,
but since it's not, upgrading the homebrew Python version
makes it soft fail because it cannot overwrite such symlink.
Later the CMake step fails to detect the correct Python version on the
system and the CI fails.
Since we are not interested in the Python 2 to 3 conversion,
delete the link and let homebrew place its own.

CI: Remove incorrect 2to3 symlink breaking Python brew upgrade

---

cmake/flags.cmake

CMake doesn't add the /MD flag in the CMAKE_\<LANG\>\_FLAGS\_\<CONFIG\>
anymore, to be then replaced with /MT by us.
Without it, the build still defaults to using /MD, which is wrong.

Explicitly set the MSVC runtime library

---

osquery/tables/system/darwin/disk_encryption.mm
specs/posix/disk_encryption.table

This PR adds a new darwin-only column to the `disk_encryption` table called `filevault_status` which on Macs will return either `on`, `off`, or `unknown`.
Some Mac Admins often believe the terms "Filevault On" and "Encryption Enabled" are equivalent. While historically this is true, the introduction of the T2 Secure Enclave has made these terms diverge in meaning in very important ways.
On T2 Macs, even when Filevault is off, the Secure Enclave by default will encrypt the contents of the drive at line speed. This means, at rest, the drive is encrypted. In these cases the `disk_encryption` table in osquery correctly indicates the volume is encrypted.
**However, this does not mean the data of the drive is inaccessible to someone with physical access to the Mac**. In fact, in Kolide's …

Add `filevault_status` to disk_encryption table

---

cmake/flags.cmake
cmake/options.cmake
osquery/main/CMakeLists.txt
osquery/main/harnesses/CMakeLists.txt

The flag to build the fuzzers is now OSQUERY_BUILD_FUZZERS
and it is independent from OSQUERY_BUILD_TESTS.
Now it's possible to build with the address sanitizer
but without any feature required by the fuzzers.
The fuzzers and the sanitizer flags are presented only on Linux.
NOTE: This is also eventually needed to fix the current oss-fuzz build failure, since we connected the build of the fuzzers with the build of the tests, without changing the oss-fuzz build script.

CMake: Refactor and rename fuzzers build flag

---

cmake/flags.cmake
osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/location_services.mm
specs/CMakeLists.txt
specs/darwin/location_services.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/location_services.cpp

This table consists of only one column that reports the enabled/disabled status of the Location Services feature of macOS. See screenshots below.
There are many people for compliance and privacy reasons who need to understand the current state of Location Services.
1. I added a new framework to get this data (Corelocation), the framework has been around since 10.6 so we should be safe, but we might want to verify older macOS compatibility just to be sure the API hasn't changed.
1. I kept the table simple as I imagine this would be something we could extend to Windows.
1. This API does not pass any errors by reference so I just threw it in a Try/Catch block just in case we have issues, not sure if that is an acceptable pattern for such a simple class method API.

Add new table location_services for darwin

---

tools/codegen/CMakeLists.txt

The list of spec files, dependency of the amalgamated table generation,
was incorrectly specified.
When a list is used in a DEPENDS argument, all the components of
the argument should be a list.
Using double quotes breaks that.

CMake: Fix amalgamated tables generation on change

---

cmake/flags.cmake

When possible try to avoid generating debug symbols
for third party libraries, when compiling in Debug or
RelWithDebInfo mode, like for POSIX platforms.
This might not always possible because there's no way
to explicitly disable symbol generation on Windows,
but this should be an improvement.

CMake: Do not compile Windows libraries with debug symbols

---

libraries/cmake/formula/openssl/CMakeLists.txt

I believe this is the recommended way to pass `make` flags into external projects. This allows OpenSSL to use `-jN` and results in a much faster build on slower machines.

Use make jobserver for OpenSSL on Linux and macOS

---

cmake/flags.cmake
cmake/options.cmake
libraries/cmake/source/boost/CMakeLists.txt
osquery/main/harnesses/CMakeLists.txt

Add OSQUERY_ENABLE_VALGRIND_SUPPORT so that it's possible
to run osquery under Valgrind.
This is specifically required by the boost library
that needs to be compiled with a special define
and it also requires the valgrind.h header.
Also move the defines for the ASAN usage to the boost
library CMakeLists.txt instead of being in flags.cmake.
This way we reduce the unnecessary recompilation of code that
doesn't depend on boost, when switching options.

CMake: Add Valgrind support

---

CMakeLists.txt
azure-pipelines.yml
cmake/options.cmake
cmake/utilities.cmake
tools/formatting/format-check.py

Also find the clang-format binary using find_program and
permit to give a path if it doesn't find it,
unless the Linux osquery toolchain is used.
Although caching the submodules has made the formatting checks come considerably sooner, this makes it slightly faster and a bit more consistent.

Permit running formatting earlier in the CI

---

azure-pipelines.yml
docs/wiki/development/building.md
tests/integration/tables/browser_plugins.cpp

Updating the Azure Pipelines agent to use 10.15 Catalina image. This will also help with the EndpointSecurity work.
Here is the agent info: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md
Closes #6707

[CI] Update macOS agent to 10.15 Catalina

---

azure-pipelines.yml

The job will output packages that will be used for the release.
We skip formatting checks and building tests,
so that more disk space is left for debug symbols.

CI: Add a RelWithDebInfo Linux job to generate packages

---

osquery/events/events.cpp

We are confusing people when we report unconfigured subscribers as "errors".

Do not call unconfigured subscribers errors

---

CMakeLists.txt
cmake/options.cmake
osquery/tables/system/CMakeLists.txt
specs/CMakeLists.txt
tests/integration/tables/CMakeLists.txt

The goal is to support distros (and their maintainers!) like Arch, which do not usually package support for deb/apt/etc. See: https://archlinux.org/packages/community/x86_64/osquery/ and the impact supporting has on downstream dependency management.

CMake: Add an option to disable building libdpkg tables and library

---

osquery/devtools/shell.cpp

Reported by ASAN when querying a non existing table:
```
=================================================================
==18372==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 72 byte(s) in 1 object(s) allocated from:
#0 0x559d9969a93d in operator new(unsigned long) /opt/toolchain/llvm/compiler-rt/lib/asan/asan_new_delete.cpp:99:3
#1 0x559d99b0e4d6 in main_init(callback_data*) /home/smjert/Development/osquery/src/osquery/devtools/shell.cpp:1648:23
#2 0x559d99b0e4d6 in osquery::launchIntoShell(int, char**) /home/smjert/Development/osquery/src/osquery/devtools/shell.cpp:1725:3
#3 0x559d99b0846e in osquery::startShell(osquery::Initializer&, int, char**) /home/smjert/Development/osquery/src/osquery/main/main.cpp:140:17
#4 0x559d99b08d36 in osquery::startOsquery(int, char**) …
```

Fix leaks when a query fails from the shell

---

cmake/flags.cmake
osquery/logger/logger.cpp
plugins/config/parsers/decorators.cpp
plugins/config/parsers/file_paths.cpp

Add a special define when osquery is built for fuzzing.
With that is possible to enable code that ignores
changing log levels.
With the config fuzzer, even if the fuzzer code was settings
the minloglevel to 4, that was immediately changed by the osquery logic.
Do not run queries parsed from the config to improve
the config fuzzer performance and avoid oom issues.
When built for fuzzing, compile osquery and libraries
without optimizing the frame pointer away.
This in some cases improves the accuracy of the stack trace
presented when a bug is found.
\
The config fuzzer was getting stuck on queries that would take all the time available to run, or would consume more than 2.5GB of memory, which is the limit oss-fuzz uses.
With Valgrind in front, instead of ASAN, a simple one line query with a …

Improve fuzzing speed and stack trace accuracy

---

osquery/worker/ipc/CMakeLists.txt

The public header is only present on non Linux platforms.

CMake: Fix platformtablecontaineripc include namespace generation

---

azure-pipelines.yml

Since cppcheck is a non-blocking check,
prefer running the tests first to have a quicker result
if something is wrong.

CI: Move cppcheck step after the tests

---

libraries/cmake/source/thrift/CMakeLists.txt

The THRIFT_STATIC_DEFINE define should be publicly used,
because it's used in a header that will be included by osquery.

CMake: Do not attempt to dllimport Thrift symbols

---

cmake/utilities.cmake
osquery/tables/system/CMakeLists.txt

When a header specified to be added in a generated include namespace
does not exists because its path is wrong or it shoudn't be added,
issue a fatal error, so that it gets noticed and fixed.
Remove windows/userassist.h as a header to be added in an include
namespace, since it doesn't exists.

CMake: Detect missing headers during include namespace generation

---

tools/codegen/CMakeLists.txt

The previous PR (osquery/osquery#6832) was not enough to cover all type of changes
to the inputs of the generation of the amalgamation file.
The previous PR was only fixing the case where a spec file would change
(it's mtime would be newer than the output, to be specific),
but not if the dependency list itself would change.
So if a new spec file was added or one was removed, it would not rerun.
Moreover, with build systems that are not Ninja,
any generated artifact that due to a config change is not generated anymore,
will remain in the build folder, affecting the amalgamation file
generation.
Specifically if a table is disabled and its .cpp is not generated
anymore, but previously it was generated, the amalgamate script
will still pick it up because it doesn't receive a list of files
to …

CMake: Further fix amalgamation file gen on change

---

libraries/cmake/source/sleuthkit/CMakeLists.txt

To completely remove sqlite3 as a dependency of sleuthkit,
case_db.cpp and auto_db.cpp should not be compiled,
because both depend on the header tsk_case_db.h,
which in turn include tsk_db_sqlite.h
which then depends on the sqlite3.h header.
NOTE: The library was using the sqlite3.h header embedded in sleuthkit instead of the one provided by our version of sqlite, not only because we were not linking sleuthkit against sqlite anymore, but because we had not defined the `HAVE_LIBSQLITE3` define, that would change header inclusion type from `""` to `<>`.
Nonetheless this should not be necessary anymore, since we're removing all the sqlite3 uses.

Remove the last usage of sqlite3 from sleuthkit

---

tools/harnesses/osqueryfuzz_config_dict.sh

Avoid grepping in the libraries folder,
since the script will get stuck on symlink loops.
Add config flags as dictionary values.

Improve config fuzzer dictionary creation script

---

libraries/cmake/source/thrift/patches/src/0001-Make-named-pipe-security-configurable-by-security-de.patch

This adds a patch for https://github.com/apache/thrift/pull/2083 to our v0.13.0 checkout of apache/thrift. We intend to use these changes to set proper security descriptors for named pipes on Windows.
Heads up @mike-myers-tob

Add patch for apache/thrift#2083

---

osquery/tables/system/linux/selinux_settings.cpp
specs/linux/selinux_settings.table

There's no logic to implement such constraints,
moreover the columns values are not unique,
so they shouldn't be exclusively part of the primary key.
Use a slightly more meaningful error message
when reading SELinux classes fails.

Don't mark scope and key columns as index in selinux_settings table

---

osquery/filesystem/linux/mounts.cpp
osquery/filesystem/linux/mounts.h
osquery/tables/system/linux/mounts.cpp
osquery/tables/system/linux/selinux_settings.cpp

Use a vector instead of an unordered_map keyed on the mount path,
since we can have multiple mount points on the same mount path
and since all the other use cases do not need such data layout.
Although multiple mount points on the same mount path will override
each other, we still want to be faithful to the information
that /proc/mounts gives us.
Moreover with autofs mounted filesystems, we will always have two
mount lines when the target filesystem is mounted, one for autofs
and one for the target filesytem.
Fixes #6865

Do not ignore mountpoints that have the same mount path

---

osquery/config/config.cpp
osquery/config/tests/config_tests.cpp

This fixes a pathological case where the validation algorithm
is unable to verify if there's a deeply nested tree,
and it can end up into an oom situation.
Added a regression test to verify this case.
This has been found by oss-fuzz.

Fix config validation oom with duplicated keys

---

osquery/events/eventfactory.cpp

Do not take a reference to a shared_ptr to be accessed
after being removed from the last persistent place
that was possibly keeping it alive.
This was only used by tests. Found with Asan.

Fix heap-use-after-free in deregisterEventSubscriber

---

osquery/events/eventfactory.cpp
osquery/events/eventfactory.h
osquery/events/eventpublisherplugin.h
osquery/events/eventsubscriber.h
osquery/events/eventsubscriberplugin.cpp
osquery/events/eventsubscriberplugin.h
osquery/events/types.h

- Downcasting a shared_ptr to a type T2 that's not a derived class or a base class of T1,
even if they share the same base class B, it's undefined behaviour.
For instance BPFEventPublisher inherits from EventPublisher<BPFEventSC,BPFEventEC>,
which is a template that inherits from EventPublisherPlugin, which
further inherits from Plugin.
The register function was called passing an instance of std::shared_ptr<BPFEventPublisher>
which was implicitly upcasted to std::shared_ptr<Plugin> as the
function parameter.
Then such parameter was downcasted to std::shared_ptr<EventPublisherPlugin>
(which was fine), then further downcasted to std::shared_ptr<BaseEventPlugin>
which actually was std::shared_ptr<EventPublisher<SubscriptionContext, EventContext>>.
Although the two EventPublisher template …

Fix UB and dangerous casting in the pubsub framework

---

docs/wiki/installation/cli-flags.md

Add missing documentation for `--tls_enroll_max_attempts` flag. Also updates docs for `--config_tls_max_attempts` flag.

Add docs for tls enroll max attempts

---

libraries/cmake/source/libdpkg/CMakeLists.txt
libraries/cmake/source/libdpkg/patches/src/fix-memory-leak.patch
libraries/cmake/source/modules/Findlibdpkg.cmake

libdpkg is leaking memory on every initialization.
Initialization happens everytime deb_packages gets queried.
The memory leaked is allocated for the "triggersdir"
global variable by "dpkg_db_get_path" called in "trigdef_update_start".
"trigdef_update_start" is called by "trig_incorporate" just after
the memory for "triggersdir" has been allocated.
In some occasions "trigdef_update_start" is also called two times in a
row. In all these cases the memory do not get deallocated in between calls,
so the old memory is lost.
Since the result of "dpkg_db_get_path" depends on the database dir that
has been set, and in the "trigdef_update_start" function it's not possible
to know if it has changed from the previous allocation or not,
it's necessary to always deallocate vs just avoid to call …

Fix a leak in libdpkg when querying the deb_packages table

---

osquery/tables/applications/posix/docker.cpp
specs/CMakeLists.txt
specs/posix/docker_image_history.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/docker_image_history.cpp

This table provides output similar to "docker history" command.
See: https://docs.docker.com/engine/reference/commandline/history/
created_by column has useful information related to the command history
Sample output:
```
osquery> select * from docker_image_history where id = '9499db781771';
+--------------+------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

docker_image_history table

---

osquery/tables/yara/yara_utils.cpp

Make the relative filepath check cross-platform.
Fixes #6788

Fix loading of YARA rules on Windows

---

cmake/flags.cmake

A previous PR removed the unused /LTCG linker flag,
which was also disabling incremental linking,
permitting the build to stay under a certain size.
Now that the incremental linking is enabled again,
the size of a full build with RelWithDebInfo increased by 29GB,
for a total of almost 50GB.
This is too big, so disable incremental linking to reduce build size.

Disable incremental linking to reduce build size on Windows

---

README.md
docs/wiki/deployment/extensions.md
docs/wiki/deployment/log-aggregation.md
docs/wiki/deployment/performance-safety.md
docs/wiki/deployment/process-auditing.md
docs/wiki/deployment/syslog.md
docs/wiki/development/creating-tables.md
docs/wiki/development/osquery-sdk.md
docs/wiki/development/pubsub-framework.md
docs/wiki/development/unit-tests.md
docs/wiki/installation/cli-flags.md
docs/wiki/installation/install-linux.md
docs/wiki/introduction/using-osqueryi.md

Just a routine spellchecking and Markdown pass on our docs.
We gotta stop misspelling `osquery` 👀

Spellcheck and Markdown nits

---

.github/workflows/build.yml
README.md
osquery/empty.cpp
osquery/filesystem/tests/filesystem.cpp
osquery/tables/system/darwin/ibridge.cpp
osquery/utils/tests/rot13.cpp
tests/integration/tables/ibridge.cpp
tools/ci/scripts/check_copyright_headers.py

The original intent was to just add Linux support, but I ended up adding all platforms (sadly, I wasn't able to keep one file per OS because jobs can only depend on other jobs defined on the same files).
I think it looks decent for an initial version, as it's at least in feature parity compared to Azure; I would like to start looking into the signing options with @directionless's guidance once this is merged
The workflow should always attach the following artifacts:
1. Windows packages (nupkg, msi)
2. Linux packages (deb, ddeb, release rpm, debuginfo rpm, tar.gz)
3. macOS packages (pkg, tar.gz)
4. cppcheck logs (release and debug, Linux only)
An additional difference compared to Azure is that no build jobs are started if the code fails the format check

CI: Add support for GitHub Actions

---

osquery/tables/yara/yara.cpp

This is a follow-up to #6893 fixing an additional cross-platform
compatibility issue with the relative path check in Yara.

Fix additional relative path check in Yara for Windows

---

cmake/flags.cmake

osquery was already linking with -pthread and so linking
to libpthread on Linux, but it wasn't always defining
the _REENTRANT macro which is done by the -pthread option
given at compile time.
Although in the third party libraries that need it,
it should've been defined in other ways (directly or via a config.h),
always add -pthread for correctness and consistency.
Note: macOS doesn't need -pthread at link time because
pthreads are already implemented inside the libc library.

CMake: Add -pthread compile option on posix platforms

---

.gitmodules

The upstream repository was failing to do shallow clones.
Also oss-fuzz keeps failing to build due to that.

Change libdpkg submodule url to our own github mirror

---

README.md

The status badge was incorrectly specified and it was "merged"
with the Azure one.
Add a link that sends to the Github Actions builds on the master branch
when the status badge is clicked.

Fix Github Actions status badge in the README

---

osquery/remote/transports/tls.cpp

> The PCI Council suggested that organizations migrate from TLS 1.0 to TLS 1.1 or higher before June 30, 2018. In October 2018, Apple, Google, Microsoft, and Mozilla jointly announced they would deprecate TLS 1.0 and 1.1 in March 2020.
https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.0
TLS 1.2 is the recommended minimum version of the TLS protocol to allow. Support in OpenSSL was introduced in 2012, from OpenSSL version 1.0.1. TLS 1.0 and 1.1 have been deprecated throughout the web, and osquery should drop its use of them too.
According to Zach, Fleet has supported TLS 1.2 and 1.3 for a long time (years).

Disable deprecated TLS versions 1.0, 1.1

---

azure-pipelines.yml
docs/wiki/development/building.md
docs/wiki/installation/install-macos.md

This updates:
* `CMAKE_OSX_DEPLOYMENT_TARGET` to 10.12. This in turn sets `mmacosx-version-min` CFLAG to 10.12
* Updates to the latest XCode. CMake uses the XCode path to build against the latest 11.1 SDK (Note: this CI image is still on 10.15 Catalina)
The benefit of this is, that we still support older macOS versions, while incorporating newer changes.
```
➜  vtool -show ./osqueryi
./osqueryi:
Load command 9
cmd LC_VERSION_MIN_MACOSX
cmdsize 16
version 10.12
sdk 11.1
Load command 10
cmd LC_SOURCE_VERSION
cmdsize 16
version 0.0
➜  ./osqueryi -A os_version;
+-------+---------+-------+-------+-------+-------+----------+---------------+----------+--------+
| name  | version | major | minor | patch | build | platform | platform_like | codename | arch   | …
```

[macOS][CI] Update XCode to 12.3 and Update min macOS version to 10.12

---

.github/workflows/build.yml

This PR updates GitHub Actions to match Azure Pipelines: https://github.com/osquery/osquery/pull/6896

GitHub Actions: Use Xcode 12.3, SDK 10.12

---

libraries/cmake/source/modules/Findyara.cmake
libraries/cmake/source/yara/CMakeLists.txt
libraries/cmake/source/yara/patches/src/yara-strutils.patch

Yara publicly exposes the definition of various str functions like
strlcpy, strlcat and so on if they are not present on the system
it is compiled on.
This is not ideal because other libraries use custom implementations
of those functions and those symbols would collide with
the public ones from yara, therefore we rename them
to avoid the collision.

Rename yara str functions to avoid symbol collisions

---

docs/wiki/deployment/configuration.md

Attempts to clear up a common misconception about the functionality of
the `denylist` key.

Update documentation about denylist schedule key

---

tests/integration/tables/system_controls.cpp

Fix SystemControlsTest adding sunrpc as an expected subsystem

---

osquery/tables/applications/windows/office_mru.cpp
osquery/tables/system/windows/certificates.cpp
osquery/tables/system/windows/logged_in_users.cpp
osquery/tables/system/windows/scheduled_tasks.cpp
specs/logged_in_users.table
specs/windows/office_mru.table
specs/windows/scheduled_tasks.table

Closes #6890 
As described in the issue, sometimes 64-bit (`long long`) variables used for timestamps were being put through the `INTEGER()` macro which would fail in the `tryto()` routine. This PR changes the fields that need to hold these timestamps to be `BIGINT`.

Fix data type macro used for 64-bit timestamp variables

---

docs/wiki/installation/install-windows.md

When trying to help someone in Slack today, I noticed the docs reference an old file name, but only once.

Docs: fix reference to a Powershell script on Windows

---

osquery/filesystem/linux/proc.h

As described in #5709, some permissions schemes do not have full
permission on /proc. Move the try/catch block into the loop, and allow
iteration despite errors.
Track whether we've had any success and base the failure off of it.
fixes: #5709
I'm not convinced this is quite right, but it seems worth review

Move try/catch to all partial failure during /proc iteration

---

docs/wiki/deployment/configuration.md

After reading [some code](https://github.com/osquery/osquery/blob/1699adc38741c05bd9cf02fe6995a9aca9de9504/osquery/config/packs.cpp#L319-L344), it is my understanding that packs queries are scheduled only if all the discovery queries return rows.

Fix packs discovery queries documentation

---

osquery/filesystem/tests/posix/xattrs.cpp

The extended attributes present on a test file
might not be only the ones set by the test itself.
If SELinux is installed for instance, an additional extended attribute
is present.
Therefore instead of requiring that the list of attribute names
is exactly the one set by the test, verify that the attribute names
we expect are present in the list.
Fixes #6870

Fix XattrTests failing due to unexpected attribute name

---

tests/integration/tables/startup_items.cpp

The "path" column for a systemd unit row can be empty.
Added missing possible values for the "status" column,
when the "type" column value is "systemd unit".
Removed "Login Item" as a possible value for the "type" column,
since now "Startup Item" is used.
Removed "disabled" as a possible value for the "status" column,
since it's not returned anymore and due to the type "Startup Item"
being either a script or a .desktop file, which do not have a disabled state;
if they need to be they'll just be removed
and they won't appear in the table anymore.
Separately check for the "status" column possible values
since they differ based on the "type" column value.
Fixes #6869

Fix StartupItemTest failing due to unexpected values

---

tests/integration/tables/startup_items.cpp

This is something I missed when running the test locally.

Fix an incorrect check in StartupItems test

---

docs/wiki/installation/cli-flags.md
osquery/extensions/impl_thrift.cpp

I've found using there's a log of noise around the extension code with verbose on:
```
I0214 19:32:04.267999  4932 impl_thrift.cpp:346] Thrift: TPipe ::GetOverlappedResult errored GLE=: errno = 109
I0214 19:32:04.268999  4932 impl_thrift.cpp:346] Thrift: TConnectedClient died: TPipe: GetOverlappedResult failed
I0214 19:32:04.526999  5004 impl_thrift.cpp:346] Thrift: TPipe ::GetOverlappedResult errored GLE=: errno = 109
I0214 19:32:04.582000  5004 impl_thrift.cpp:346] Thrift: TConnectedClient died: TPipe: GetOverlappedResult failed
I0214 19:32:07.620999  5596 impl_thrift.cpp:346] Thrift: TPipe ::GetOverlappedResult errored GLE=: errno = 109
I0214 19:32:07.620999  5596 impl_thrift.cpp:346] Thrift: TConnectedClient died: TPipe: GetOverlappedResult failed
I0214 19:32:07.734999  5608 …
```

Put noisy thrift logs behind a flag

---

docs/wiki/installation/cli-flags.md

Users trying to simply turn on evented tables on Windows are often confused that `--disable_events=false` is not enough. Afterwards, they are confused when they query an evented table twice and some or all of the data from the first query is still there. They are confused again when they get warnings about evented tables' events overfilling and losing events. So the docs could be better. This is my attempt.
Addresses @muffins [comment on recent changes to the flags that control evented tables](https://github.com/osquery/osquery/pull/6280).
Closes #6763

Improve explanations of event control flags

---

osquery/main/main.cpp

This brings the daemon's start logic to mimic the shell.
In some rare instances where you are using `--config_check`, and where the daemon cannot start it's backing storage, osquery may crash. This removes the crashing potential.

Do not start scheduler when shutting down

---

osquery/carver/CMakeLists.txt
osquery/carver/carver.cpp
osquery/carver/carver_utils.cpp
osquery/carver/carver_utils.h
osquery/carver/tests/carver_tests.cpp
osquery/sql/sqlite_operations.cpp
osquery/tables/forensic/carves.cpp
specs/carves.table

This is half of the solution for #6727. We do not want to use the last-most-recent distributed request ID for all carve requests. Carve requests can be initiated multiple ways, through a scheduled query, distributed query, shell query, etc.
This also improve the UX of the `carves` table. It will report the single row requested when `carve = 1` is used.
A follow up change should explore storing metadata with queries such that the virtual table can retrieve and use this data.

Use a distinct carver request_id

---

docs/wiki/deployment/remote.md

This documentation edit is to align the docs for 4.7.0 following the change made in PR #6910

Update the info about osquery's TLS version support

---

osquery/tables/applications/posix/docker.cpp

Was missing a string conversion so it ended up empty.

Fix pids column in docker_container_stats table

---

osquery/tables/CMakeLists.txt
osquery/tables/cloud/CMakeLists.txt
osquery/tables/cloud/ycloud/ycloud_instance_metadata.cpp
osquery/utils/CMakeLists.txt
osquery/utils/ycloud/CMakeLists.txt
osquery/utils/ycloud/tests/CMakeLists.txt
osquery/utils/ycloud/tests/ycloud.cpp
osquery/utils/ycloud/ycloud_util.cpp
osquery/utils/ycloud/ycloud_util.h
specs/CMakeLists.txt
specs/ycloud_instance_metadata.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/ycloud_instance_metadata.cpp

This PR introduces a new table `ycloud_instance_metadata` which allows to fetch virtual machine metadata in [Yandex.Cloud](https://cloud.yandex.com). The table is similar to `azure_instance_metadata` or `ec2_instance_metadata`.
The API for Yandex.Cloud metadata can be found at the [official documentation](https://cloud.yandex.com/docs/compute/concepts/vm-metadata).
I also added a way to override a metadata endpoint via constraints which is useful for tests.

VM metadata table for Yandex.Cloud

---

CODEOWNERS

The intention is to allow `osquery/osquery-committers` or `osquery/technical-steering-committee`

Fix CODEOWNERS syntax to allow committers and TSC

---

plugins/config/parsers/auto_constructed_tables.cpp
plugins/config/parsers/decorators.cpp
plugins/config/parsers/events_parser.cpp
plugins/config/parsers/feature_vectors.cpp
plugins/config/parsers/file_paths.cpp
plugins/config/parsers/kafka_topics.cpp
plugins/config/parsers/logger.cpp
plugins/config/parsers/options.cpp
plugins/config/parsers/prometheus_targets.cpp
plugins/config/parsers/views.cpp

This is an alternative to https://github.com/osquery/osquery/pull/6945.
In this PR, the persistent copies of JSON documents within config parsers are replaced with new objects on each config update.

Copy JSON objects to avoid MemoryPool buildup

---

osquery/tables/system/posix/augeas.cpp

Fix output bug where the augeas table incorrectly calculated path from
node.
Augeas stores it's data in a tree. Internal information is preseted in
`/augeas` and files are in `/files`. Osquery usually works with data by
path. The augeas table _assumed_ that all data was file data, and
indiscriminately tried to coerce a file object. This would result in
output like:
```
osquery> select * from augeas where node = "/augeas/load";
+--------------+-------+-------+--------+
| node         | value | label | path   |
+--------------+-------+-------+--------+
| /augeas/load |       | load  | s/load |
+--------------+-------+-------+--------+
```
Path should be null here. This is not a real file

Augeas Table: Fix output bug

---

osquery/tables/system/posix/augeas.cpp

While playing with augeas, I noticed it loaded the lenses that were
already on my machine (at /usr/local/share/augeas/lenses). This was an
unwelcome surprise.
I'm not sure if this was previously intended or not. I assume not, since
there is some versioning with the lenses, and we ship our own.
This adds the load flags to ignore anything on the existing system path.
And disable saving while I'm here.
Note that this is, potentially, an API change. Though I think it's
adding consistency
Fixes: #6974

Augeas Table: Don't autoload system lenses

---

osquery/main/harnesses/fuzz_utils.cpp

This should speed up our harnesses. We want to avoid searching the filesystem while fuzzing.

Remove hash and yara table from fuzz harnesses

---

osquery/tables/system/linux/process_open_pipes.cpp

Inode is a uint32, not an int.
Fixes: #6977
Co-authored-by: Stefano Bonicatti <stefano.bonicatti@gmail.com>

Fix error in process_open_files around stoi vs stoul

---

osquery/tables/system/windows/logon_sessions.cpp
osquery/tables/system/windows/users.cpp

Closes #6979 fixing a small regression introduced in #6782 that undid part of #6714 
It's easy to forget to free memory with "Caller must free this parameter" APIs like `ConvertStringSidToSidA`, fixed before in https://github.com/osquery/osquery/pull/6714 (we even forgot to do it in the wrapper we created for `ConvertSidToSidStringA`, see https://github.com/osquery/osquery/pull/6548 that fixed that).
Because a wrapper for `ConvertSidToSidStringA`, I found one place that I changed to use that, instead of the raw API, saving a few lines of code. But in the future, to avoid similar problems with `ConvertStringSidToSidA`, we'd have to make our own wrapper class for `sid` that implemented RAII as noted by @Breakwell.

Fix mem leak regression with Windows' sids API

---

osquery/process/windows/process_ops.cpp
osquery/tables/system/windows/users.cpp

Closes #4264 by changing the behavior of `users` and `processes` to retrieve Group IDs the same way that `groups` does. See the issue for a longer explanation.
With the corrected behavior, observe that the `gid` values are of Local Groups and are consistent across tables, making it possible to `JOIN` on this column:
```
osquery> select * from users;
+------+-----+------------+------------+--------------------+-------------------------------------------------------------------------------------------------+---------------------------------------------+-----------------------------+-----------------------------------------------+---------+
| uid  | gid | uid_signed | gid_signed | username           | description …
```

Make Group ID columns consistent across Windows tables

---

docs/wiki/installation/install-macos.md

Small change here, to coincide with the switchover in our CI systems. It's the only instance where our CI systems were mentioned in any of our docs, actually. 🤷🏻‍♂️

Docs: change reference about Azure Pipelines to GitHub Actions

---

cmake/packaging.cmake

Created a package of this branch and inspected it with `pkgutil` and `lsbom`
```
➜  build git:(augeas_lenses_path) ✗ man lsbom
➜  build git:(augeas_lenses_path) ✗ lsbom -s  $(pkgutil --bom osquery-4.6.0-71-g3d2d2ba0-dirty.pkg) | grep lenses
./private/var/osquery/lenses
./private/var/osquery/lenses/access.aug
./private/var/osquery/lenses/activemq_conf.aug
./private/var/osquery/lenses/activemq_xml.aug
./private/var/osquery/lenses/afs_cellalias.aug
./private/var/osquery/lenses/aliases.aug
./private/var/osquery/lenses/anacron.aug
./private/var/osquery/lenses/approx.aug
./private/var/osquery/lenses/apt_update_manager.aug
./private/var/osquery/lenses/aptcacherngsecurity.aug
./private/var/osquery/lenses/aptconf.aug
./private/var/osquery/lenses/aptpreferences.aug …
```

[packaging] Remove extraneous lenses directory for augues on macOS

---

osquery/tables/system/windows/background_activities_moderator.cpp
osquery/tables/system/windows/shellbags.cpp
osquery/tables/system/windows/userassist.cpp
specs/windows/background_activities_moderator.table
specs/windows/shellbags.table
specs/windows/userassist.table

Following up on #6897 this is basically the same deal: always use the `BIGINT` macro rather than the `INTEGER` macro when dealing with `long long` values, or they might generate warnings and not report data, the same as explained in the last PR.

Always use BIGINT macro for 'long long' data

---

osquery/sql/sqlite_util.h

From what I can tell we have to enable the journal mode pragma in order for the getSqliteJournalMode() function to work as advertised. As it stands it fails to retrieve the journal mode which has probably rebroken the issue in https://github.com/osquery/osquery/issues/5225. I'm in the midst of investigating another ATC issue at the moment, but this stood out as something we should probably fix.

ATC fails because journal_mode pragma is blocked by sqlite authorizer

---

osquery/events/CMakeLists.txt

With OSQUERY_BUILD_BPF=false, the `osquery_events_tests_bpftests-test` test is still added, which ends up failing since it was never built:
> Start 65: osquery_events_tests_bpftests-test
>        Could not find executable osquery_events_tests_bpftests-test
>        Looked in the following places:
>        osquery_events_tests_bpftests-test
>        osquery_events_tests_bpftests-test
>        Release/osquery_events_tests_bpftests-test
>        Release/osquery_events_tests_bpftests-test
>        Debug/osquery_events_tests_bpftests-test
>        Debug/osquery_events_tests_bpftests-test
>        MinSizeRel/osquery_events_tests_bpftests-test
>        MinSizeRel/osquery_events_tests_bpftests-test
>        RelWithDebInfo/osquery_events_tests_bpftests-test
> …

Disable BPF events tests if OSQUERY_BUILD_BPF is false

---

tests/integration/tables/deb_packages.cpp

`section` and `priority` fields are optional in the Debian spec, so valid packages can cause this test to fail.
Debian docs: https://www.debian.org/doc/debian-policy/ch-controlfields.html#binary-package-control-files-debian-control
This is a failure caused by a legitimate package that installs just fine, but has no `section`:
>        96: [----------] 1 test from DebPackages
>        96: [ RUN      ] DebPackages.test_sanity
>        96: /opt/build/osquery/tests/integration/tables/helper.cpp:167: Failure
>        96: Value of: validate_value_using_flags(value, flags)
>        96:   Actual: false
>        96: Expected: true
>        96: Standard validator of the column "section" with value "" failed
>        96: Row: {arch: "amd64", maintainer: "Maintainer", name: "package name", priority: …

Setting non-required deb_packages fields as optional in test

---

.github/workflows/build.yml

I think this fixes a bug, where we do not use `v*` but rather the exact semantic version number in tags.

Run GH Actions workflows on all tags

---

.github/workflows/build.yml

This moves the CI to using `osquery/builder18.04` Which comes from https://github.com/osquery/osquery/pull/7011
the `0aa3775ce` tag is from a recent main branch build

Move CI to using docker from osquery

---

osquery/dispatcher/scheduler.cpp

Fixes https://github.com/osquery/osquery/issues/6902.

Fix scheduler to print the correct number of elapsed seconds

---

packs/osx-attacks.conf

This query is subject to quite a few false positives and does no filtering in the query itself. As an example, `/usr/libexec/gamecontrollerd` is a native MacOS utility that regularly hooks into taps and will cause false positives on every Mac that this pack runs on. 
As an example of how much whitelisting can be necessary to reduce FPs, please see https://github.com/palantir/osquery-configuration/blob/master/Classic/Endpoints/MacOS/osquery.conf#L79
TL;DR - My opinion is that we shouldn't put queries that are likely to generate many FPs in this pack.

Removing Keyboard Event Taps from osx-attacks pack

---

osquery/tables/system/windows/processes.cpp
osquery/tables/system/windows/windows_crashes.cpp

These  messages seem very noisy. Given the frequency of them, I suspect
they represent assumptions that don't always hold, and not outright
errors.
If any of the windows folks feel otherwise I'd love to know...
Fixes: #7022

Change windows messages to verbose

---

osquery/utils/conversions/windows/strings.cpp

Release variable in `cimDatetimeToUnixtime`
i think I got all the returns. It passes CI. I can download and run the resultant `osqueryd`. Not sure if there's much else to manually test here
Fixes: #7018

Release variable in windows data conversation

---

.github/workflows/build.yml
.github/workflows/build_aarch64.yml

This adds a new GitHub Actions workflow called `build_aarch64`. This workflow does not run on Pull Requests because non-collaborators do not have access to the `secrets` context, meaning the builds will always fail. This is acceptable for now since we are looking to go from not knowing if aarch64 is working to knowing if it works on `master`. This gives us confidence when tagging new releases that aarch64 tests are passing, and we will have testable packages.
In the future we want to have tests run on PRs and https://github.com/osquery/infrastructure/pull/7/files is exploring the solution.
This uses the approach here: https://github.com/machulav/ec2-github-runner but using my fork `theopolis/ec2-github-runner@main` for a little extra safety from breaking changes (and because I added …

Add build_aarch64 workflow for push

---

docs/wiki/deployment/remote.md

As confirmed recently with @Smjert on Slack, the docs needed to be changed to be consistent with the fact that osquery no longer uses a system-provided library for anything and that includes OpenSSL.
Separately, the docs were making the implication that TLS protocol support on Windows was different than the rest, but I don't believe that's the case either, so I changed that line.

Correct docs about OpenSSL and TLS behavior

---

osquery/tables/networking/curl_certificate.cpp
osquery/tables/system/darwin/certificates.mm
osquery/tables/system/darwin/keychain_utils.cpp
osquery/tables/system/tests/darwin/certificates_tests.cpp

Follow-up to PR #6361 and #6799

Remove Buck leftovers that supported building with old versions of OpenSSL

---

osquery/tables/system/windows/logged_in_users.cpp

Fix for #7019. As documented by @Breakwell , WTSEnumerateSessionsExW needs to be freed with a call to WTSFreeMemoryEx.

bugfix-7019: Free using WTSFreeMemoryEx for WTSEnumerateSessionsExW

---

osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/events/linux/auditeventpublisher.h
osquery/tables/events/CMakeLists.txt
osquery/tables/events/linux/seccomp_events.cpp
osquery/tables/events/linux/seccomp_events.h
osquery/tables/events/tests/CMakeLists.txt
osquery/tables/events/tests/linux/seccomp_events_tests.cpp
specs/CMakeLists.txt
specs/linux/seccomp_events.table

**Changes description**:
This PR adds a new `seccomp_events` table that contains events from [Seccomp](https://www.kernel.org/doc/html/v4.14/userspace-api/seccomp_filter.html). Seccomp is a Linux kernel security feature which allows to restrict the set of system calls application can make. Seccomp is one of the main components of any sandbox. Also, `seccomp_events` table makes Seccomp logs human readable for x86_64 systems.
**Motivation for the PR**:
Creating Seccomp security profile with exact whitelist of system calls is complicated for complex applications. Therefore, using Seccomp in terminating mode (`SECCOMP_RET_KILL`) can lead to huge production risks. Since Linux 4.14 Seccomp allows to log use of unauthorized system calls without application terminating (`SECCOMP_RET_LOG`). This …

seccomp_events table in osquery

---

cmake/flags.cmake
cmake/options.cmake

Add OSQUERY_ENABLE_INCREMENTAL_LINKING which adds
/INCREMENTAL if it's enabled, to improve linking speed
when relinking executables.
This greatly increases the amount of disk space used
(around 50GB now, with tests), so default is off
and /INCREMENTAL:NO is used.

Add an option to enable incremental linking on Windows

---

osquery/tables/system/windows/system_info.cpp

On windows, physical memory is more correctly reported through the
`Win32_PhysicalMemory` wmi class.
The prior `Win32_ComputerSystem` mechanism reported the amount available
to the OS, which did not include anything held by the bios.
From https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystem
> Total size of physical memory. Be aware that, under some circumstances, this property may not return an accurate value for the physical memory. For example, it is not accurate if the BIOS is using some of the physical memory. For an accurate value, use the Capacity property in Win32_PhysicalMemory instead.
(Thanks @terracatta and Kolide)

Change windows calculation for `physical_memory`

---

docs/wiki/deployment/file-integrity-monitoring.md

The FIM docs needed some attention. They're out of date and didn't mention Audit-based FIM or NTFS Journal Events -based FIM. Users often have trouble setting it up.

Improve docs on FIM, mention NTFS and Audit, etc.

---

osquery/core/query.cpp
osquery/core/query.h
osquery/core/tests/query_tests.cpp
osquery/dispatcher/scheduler.cpp

I noticed that "event based" queries do not include `epoch` or `counter` tracking in their logging. These are queries in the schedule against an events table like `SELECT * FROM file_events;`.
I tracked this down to some optimization path in the scheduler. I think our expectation is to include these.

Use epoch and counter for events-based queries

---

osquery/events/eventfactory.cpp
osquery/events/eventpublisherplugin.cpp
osquery/events/eventpublisherplugin.h
osquery/events/eventsubscriberplugin.cpp
osquery/events/eventsubscriberplugin.h
osquery/events/tests/eventsubscriberplugin.cpp
osquery/events/tests/mockedosquerydatabase.cpp
osquery/events/tests/mockedosquerydatabase.h

This fixes a bug introduced in 4.7.0 where a schedule with multiple queries using the same event subscriber (and an event expiration lower than the maximum interval) would lose events.
Here is an example configuration:
```
{
"schedule": {
"query_1": { "query": "select eid from process_events", "interval": 5 },
"query_2": { "query": "select count(1), '2' from process_events", "interval": 20 },
"query_3": { "query": "select count(1), '3' from process_events", "interval": 40 }
}
}
```
And an example invocation of osquery:
```
sudo ./osquery/osqueryd \
--config_path ./config.json --logger_plugin=stdout \
--ephemeral --disable_database  --allow_unsafe \
--nodisable_audit --audit_allow_config --events_expiry=1
```

Fix optimization for multiple queries using the same subscriber

---

osquery/core/init.cpp
osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp
osquery/core/watcher.h
osquery/main/main.cpp

My eventual goal is to add an IPC to the Watcher. Before I do this I would like to simplify the code. I noticed that `Watcher` does not need to be a singleton.

Refactor watcher out of singleton pattern

---

osquery/events/eventsubscriberplugin.cpp
osquery/events/eventsubscriberplugin.h
osquery/events/tests/eventsubscriberplugin.cpp

This is "part 2" of #7055.
The previous fix improved the optimization handling but did not handle an edge case where events would be produced in the same second the last query ended. This had been handled by tracking the "last visited" EventID within a time window.
This PR implements the same "visited" tracking as before.

Handle events optimization edge cases

---

plugins/database/rocksdb.cpp

The integer values of the error code and subcode
were interpreted as characters instead of numbers.

Correct RocksDB error code and subcode printing on open failure

---

tools/tests/test_base.py
tools/tests/test_example_queries.py
tools/tests/test_extensions.py
tools/tests/test_osqueryd.py
tools/tests/test_release.py
tools/tests/test_windows_service.py

We should try to remove the flakiness from tests instead of marking them as flaky and attempting to retry.

Remove flaky test decorators for python tests

---

osquery/events/eventfactory.cpp
osquery/events/eventsubscriberplugin.cpp
osquery/events/eventsubscriberplugin.h
osquery/events/tests/eventsubscriberplugin.cpp

This adds more tests for event subscribers. Specifically, this tests when a "minimum expiration" is needed. In these cases there are multiple queries in the schedule with different intervals. The minimum expiration assures that all queries have run before any event is expired.

Add more tests for events expiration

---

osquery/tables/system/darwin/system_extensions.mm
osquery/tables/system/tests/darwin/system_extensions_test.cpp
specs/darwin/system_extensions.table
tests/integration/tables/system_extensions.cpp

System extensions deployed on a managed environment can be configured through a device management profile.  The changes add a new column (`is_managed`) having information if the extension is managed by a payload policy. It scans through the extension payload policies and checks the allowed team identifiers & allowed extensions dictionary.
It will be great to get feedback from the community both on the changes and uses of having the information in the table. 
Refs: [com.apple.system-extension-policy](https://developer.apple.com/documentation/devicemanagement/systemextensions?language=objc)

Add column for system extensions managed by configuration policy (system_extensions table)

---

osquery/extensions/extensions.cpp
osquery/extensions/impl_thrift.cpp
osquery/extensions/interface.h

We used to apply a timeout of 5minutes to thrift requests (and 10s for pings). This was unintentionally disabled when we added nearly infinite retries. The retry was added to mitigate what we handle with our patches to thrift to prevent erroring when an interrupt occurs.

Restore thrift socket 5min timeout

---

osquery/utils/azure/CMakeLists.txt

The test osquery_utils_aws_tests-test has been incorrectly duplicated
into the osquery_utils_azure context.

Remove duplicated osquery_utils_aws_tests-test

---

docs/wiki/development/osquery-sdk.md
external/examples/config_plugin/main.cpp
external/examples/read_only_table/main.cpp
external/examples/writable_table/main.cpp
tools/codegen/templates/osquery_extension_group_main.cpp.in

The crash was happening due to the ExtensionWatcher thread still running
and attempting to call the watch() function,
while the extension was exiting.
Use the Initializer::shutdown() function so that all threads/services are stopped before
exiting.
Also update the documentation with the example extension.

Fix extensions crash on shutdown

---

osquery/core/shutdown.cpp
osquery/core/shutdown.h
osquery/dispatcher/scheduler.cpp
osquery/dispatcher/scheduler.h
osquery/remote/utility.h
plugins/config/tests/tls_config_tests.cpp
plugins/remote/enroll/tls_enroll.cpp

Make the quadratic backoff sleep during the enrollment retry procedure
interruptible by the shutdown.
Same for TLS requests retries.
Avoid any subsequent attempt to enroll during the shutdown procedure.
This partially addresses #7068

Improve speed of osquery shutdown procedure

---

.github/workflows/build_x86.yml

Add the compiler version to the sccache key so that if the version
changes, the key won't match and a new cache key is generated.
Without this all the first runs of PRs after the compiler version
changes, provided they succeed, or until a commit lands on master and
it's built before the PR,
will have sccache miss everything and the build will take double the time.
With this, if a commit lands on master and its build or the scheduled build
run before a new opened PR, then that PR will find the new cache key
and it won't take double the time.

CI: Regenerate sccache cache when compiler version changes

---

osquery/core/init.cpp
osquery/core/system.cpp
osquery/core/watcher.cpp
osquery/distributed/CMakeLists.txt
osquery/process/process.h
osquery/worker/ipc/linux/linux_table_container_ipc.cpp

- Wait for the worker to shutdown
- Increase the default alarm timeout to 15 seconds, but limit the minimum to 10
- Stop extensions and the worker in parallel, so that the time it takes
to stop them doesn't always fully add up.
Fixes https://github.com/osquery/osquery/issues/7073
The alarm timeout has been increased to a default of 15 seconds which is ample time and should be below the most common services timeout for each platform (last time I checked 20 seconds are the timeout for macOS, other platforms have more).
The minimum limit of 10 seconds is to give some breathing space for the processes to close, especially the worker if it's processing some query. With that limit the worker would actually have 6 seconds to close gracefully and 2 to close brutally/via SIGKILL.
I think that in …

Watchdog should wait for the worker to shutdown

---

osquery/tables/system/darwin/homebrew_packages.cpp
specs/darwin/homebrew_packages.table

Update the `homebrew_packages` to search in both of homebrew's default locations. As well as to allow the caller to specify the `prefix` to search.
There's a lot of `fs::path` and back to strings and back again here. But a lot of that seems to pre-exist. 
Fixes: #7108

Update `homebrew_packages` to include new prefix and allows specifying alternate prefixes

---

osquery/tables/system/windows/processes.cpp
specs/processes.table
tests/integration/tables/processes.cpp

Find processes that are secured (IUM), protected or virtual on Windows #7120

Secured protected virtual processes

---

osquery/tables/applications/chrome/chrome_extensions.cpp
osquery/tables/applications/chrome/tests/utils.cpp
osquery/tables/applications/chrome/utils.cpp
osquery/tables/applications/chrome/utils.h
specs/chrome_extensions.table
tests/integration/tables/chrome_extensions.cpp

- The `identifier` column now contains the identifier built from the `key` property of the extension manifest.
- The identifier used in the **Preferences**/**Secure Preferences** profile to reference extensions is now stored in the `referenced_identifier` column.
Fixes: #7093

chrome_extensions: Compute the identifier from the 'key' property

---

osquery/tables/system/windows/ntfs_acl_permissions.cpp

This is in response to the Bug :  #7113 
ntfs_acl_permissions table uses GetExplicitEntriesFromAcl() API which enumerates only explicit Aceess Conrol Entries (ACE) and not inherited ones. Most Windows files are protected by  inherited ACEs which will not get listed when running this table against those files. 
The PR intends to use GetACE() function to enum ACEs in a dacl which will get all ACEs regardless of whether they are explicit or not. The information returned by GetAce is slightly different than what GetExplicitEntriesFromAcl() might return
As a result, code to enumerate and populate column values needed to change though all efforts have beenn made to stick to existing column values. 
I have tested this on Windows 10. for both success and failure scenarios mentioned in #7113 …

Bugfix/ntfs_acl_permissions: Use GetAce() to enlist all ACE entries in dacl

---

docs/wiki/installation/cli-flags.md
plugins/remote/enroll/tls_enroll.cpp

Setting the flag tls_enroll_max_attempts to 0 enables infinite
enrollment retries.
The interval between retries is limited by a new flag,
tls_enroll_max_interval, which defaults to 5 minutes,
so that it doesn't indefinitely increase.
The interval limit works also with limited retries.
Also increased the default attempts number to 12,
to come up to around 10 minutes of retries, at each enrollment round.
Partially implements https://github.com/osquery/osquery/issues/7082

Implement infinite enrollment retries

---

osquery/dispatcher/scheduler.cpp
osquery/logger/data_logger.h
osquery/logger/logger.cpp
osquery/logger/tests/logger.cpp
plugins/logger/tests/filesystem_logger_tests.cpp

The code has been slightly refactored to remove an incorrect usage
of std::futures in a queue, where it was possible to try to wait on the
same std::future twice, which would lead to a crash.
Even after fixing the crash, it was possible that threads dealing
with recursive logging would change order and wait on a std::future
of another thread, causing a deadlock.
Finally the deferred log relaying wasn't always used when it should've,
due to a confusion between boolean values.
A enum class has been used instead to be more expressive about
the relaying mode asked.
Fixes #6928

Fix crash and deadlocks in the support for recursive logging

---

tools/codegen/genwebsitejson.py

Update the website generation tooling to reflect that the yara table
supports windows.
Relates to: #6564
Closes: https://github.com/osquery/osquery-site/issues/212

Website: Note windows support for yara

---

osquery/tables/system/darwin/packages.mm

I am confused as to why this sometimes throws an exception of type `boost::wrapexcept<boost::property_tree::ptree_bad_path>: No such node (packageIdentifiers)` with the `get_child_optional` API. I am trying an alternative.

Alternate check for packageIdentifiers key

---

osquery/worker/ipc/posix/pipe_channel.cpp

When reading data from a table using `generateInNamespace`, the pipe channel implementation would only try one `read` syscall to read the message from the osquery process running in the namespace.  Under certain circumstances, this single read call would be insufficient to read all the data in the message and the query would fail.
Example:
```
E0604 23:00:14.790307 256479 linux_table_container_ipc.cpp:446] Table deb_packages failed to retrieve QueryData from the container: Failed to read the entire message from the pipe of table deb_packages, read only 64436/113588 bytes
```
This PR fixes this problem by putting the `read` syscall in a loop that continues to read until all data has been returned.
cc @Smjert related to this thread: …

pipe_channel not reading all data in a message

---

osquery/events/eventsubscriberplugin.cpp

This is applying the suggestion from Slack here: https://osquery.slack.com/archives/C08V7KTJB/p1622484876086800
In the current code, an event cleanup is triggered sort of randomly when we have counted `% 256 == 0` events. I think the intention is to try to cleanup every checkpoint, meaning each time we collect another batch of 256 events.

Trigger event cleanup checks every 256 events

---

osquery/tables/system/darwin/xprotect.cpp

This commit:
- updates the `xprotect_entries` and `xprotect_meta` tables so that
they use the updated xprotect paths on macOS Big Sur (11.0 or 10.16)
and later, while still using the existing paths for 10.15 and lower.
Why?
- In macOS Big Sur, the location of the XProtect.plist and
XProtect.meta.plist changed.
Closes #7137

Add detection/handling for updated XProtect path in macOS Big Sur

---

osquery/tables/applications/posix/docker.cpp

docker containers without traditional network config fail to report cpu, memory and storage stats because the code attempts to query net_rx and tx.  This results in a ptree error for the "networks" node not being found:
`Error getting docker container stats 5e27b6a92a3fb7f4988993da46522655ce42242b7930471fc4aa9e437a3bd246: No such node (networks)`
This patch returns an empty ptree as default for the network calls if the node is not found.  This allows you to collect container stats (excluding networking info) on docker containers that don't have traditional network setups.
Thanks for the help @solarkennedy

enable container stats on docker containers that don't have traditional networks

---

osquery/tables/networking/curl_certificate.cpp

because of a bug in my implementation, custom timeouts in curl_certificate would never be honored.  This is because of too fine of scope for the timeout variable parsed from the constraint.  This PR, re-uses the outer scope timeout variable so that it is actually used by the rest of the table implementation.
Symptoms of this bug: if you set a custom timeout for curl_certificate, the table would no longer work.  This is because the SQL engine would filter out all of the results because the timeout specified in the constraint and what came back from the table implementation would always be different.  Unless of course, you set the timeout = 4 which was the default value that was always used.
That's a couple of hours of my life I can't back.  I'm mad at my last year self now.

custom curl_certificate timeouts would never be used

---

osquery/tables/system/darwin/apps.mm
osquery/tables/system/darwin/launchd.cpp
osquery/tables/system/darwin/packages.mm

While digging around some system services, we noticed that they were
missing from osquery. This looks akin to #7138, the paths changed
I did a quick review of the other paths, and I didn't see anything else
missing. I'm sure they'll turn up...

Add additional paths to `apps` and `launchd`

---

CMakeLists.txt
tools/deployment/make_windows_package.ps1
tools/deployment/windows_packaging/chocolatey/tools/chocolateyinstall.ps1

This updates the artifacts produced for Windows packaging to make the osquery icon file placed in a more generic location for the `nupkg`, as well as brings along the query packs. The  [`nuspec` documentation](https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon) specifies that the icon element of the nuspec should now just point to a file on disk. The CMake options don't seem to reflect this change yet, but we are making the move in order to have compliance with the chocolatey validation when we release our packages.
* Generate the osquery project with cmake, as per the usual
* Run the `install` target to place the package artifacts in the appropriate locations:
```
-- Install configuration: "Release"
-- Installing: C:/Program Files/osquery/osqueryd/osqueryd.exe
-- Installing: …
```

packaging: update windows icon reference and include query packs

---

tools/deployment/windows_packaging/osquery_utils.ps1

Instead of applying the safe permissions ACLs in two phases,
one that removes all ACLs present on the target,
the other that puts the wanted ACLs, we create an ACL from
scratch that already contains the final state and apply that.
Fixes #7165

Fix issues applying ACLs during chocolatey deployment

---

osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp

See #6537, ~~we should at least be using `PrivateBytes` for our definition of `resident_size`.~~
Update: based on discussion here, we are choosing to address the issue by using `total_size` within the watchdog logic.

Use total_size within watchdog on Windows

---

osquery/filesystem/windows/fileops.cpp

This PR fixes a memory issue in the Windows fileops `platformStat` function (missing call to LocalFree API).

Fix memory issue in Windows fileops

---

libraries/cmake/source/yara/CMakeLists.txt

We don't have libyara's macho module compiled and enabled currently, this causes `yara: compilation error` for signature files including the macho module
```yara
import "macho"
rule macho
{
condition:
uint32(0) == 0xfeedface or uint32(0) == 0xfeedfacf
}
```
```
osquery> select * from yara where path like '/tmp/%' and sigfile = '/tmp/macho_test.sig' and count > 0;
+---------------+---------+-------+-----------+---------------------+---------+------+
| path          | matches | count | sig_group | sigfile             | strings | tags |
+---------------+---------+-------+-----------+---------------------+---------+------+
| /tmp/osqueryd | macho   | 1     |           | /tmp/macho_test.sig |         |      |
+---------------+---------+-------+-----------+---------------------+---------+------+ …
```

[libs][yara] enable and compile the macho module on macOS

---

osquery/tables/applications/chrome/utils.cpp

This commit:
- adds the necessary path for microsoft edge on macos so that
installed for that browser included in the chrome_extensions table
Why?
- Edge for macOS extensions aren't currently picked up by the chrome
extensions table
Note that some of the properties (install_time, for one) may not be populated 
for extensions not installed from the Chrome Web Store, but I think that is 
existing behavior on windows as well.
To test this, I: 
- installed Microsoft Edge for Mac and Edge Beta for Mac 
- for each, installed an extension from the chrome web store and the edge web store
- ran `select name from users cross join chrome extensions ce on users.uid = ce.uid where name like '<EXTENSION_NAME>';`
prior to this patch, the query returned nothing. after this patch, the expected extensions …

Add Edge & EdgeBeta to `chrome_extensions` on macOS

---

tools/deployment/windows_packaging/chocolatey/tools/chocolateyinstall.ps1

The powershell script used for installation and upgrade
do not stop when an error occurs in some command.
This causes chocolatey to proceed the installation/upgrade,
leading to a corrupted/incomplete installation.
Tell powershell to interrupt as soon as an error is hit.
Fixes #7181

Fix choco not failing when an error occurs during install or upgrade

---

osquery/core/watcher.cpp

This PR initializes `parent` and `footprint` of variable `change` right after it is declared, in case they are not initialized when an exception is thrown. (When control reaches line 422)

Always initialize variable `change`

---

osquery/core/tables.h

canoical -> canonical
if not move the committed files to the stage area,
build the `format` target to format, then re-commit.
More information is available on the wiki.

refactor: Fix comment typo in tables.h

---

osquery/logger/logger.cpp

It is sometimes possible that multiple threads trying to serialize and
broadcast logs are enqueued. Each thread will broadcast all the logs
and if between two threads runs there's no new log to broadcast,
then the thread coming after a broadcast will find no logs,
broadcasting an empty log response instead of doing nothing.
Prevent this by checking that there are actually logs to be serialized
before broadcasting a response.
Fixes #7180

Fix broadcasting empty logs to logger plugins

---

osquery/extensions/thrift/osquery.thrift

This adds an option to namespace ruby generated code, exactly like the other languages

Add ruby namespace to the thrift definition

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/posix/ssh_keys.h
osquery/tables/system/ssh_keys.cpp
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/posix/ssh_keys_tests.cpp
specs/user_ssh_keys.table

Revived PR [#5526](https://github.com/osquery/osquery/pull/5526): Rebased onto latest master and tests fixed. 
========
Comments: 
Newer versions of OpenSSH use ed25519 keys, which don't include the text "ENCRYPTED" in their body. This patch tries to parse the keys using openssl and falls back to custom logic to support arbitrary key types.
Fixes [#4826](https://github.com/osquery/osquery/issues/4826)
Fixes [#5253](https://github.com/osquery/osquery/issues/5253)
Fixes [#4886](https://github.com/osquery/osquery/issues/4886)
Added a bunch of tests for the user_ssh_keys table. 
==========
Thanks to [Robbie Ostrow](https://github.com/ostrowr) for doing the heavy lifting.

detect encryption of ed25519 ssh keys

---

docs/wiki/deployment/yara.md

Resolves #7110 
- Removes outdated column `pattern` and explains the `WHERE path LIKE` syntax with examples
- Documents new flags and functionality added in the last year or so
- Clarifies some of the usage, and forms an initial version of a troubleshooting section
- Points to YARA rule-writing documentation
- Updates the examples with the current table schema
- I've tested all the examples myself (on Windows 10)

Docs: bring the YARA wiki page up to date

---

osquery/core/watcher.cpp

Related issue: https://github.com/osquery/osquery/issues/7171
With the existing behavior, osquery can launch multiple extensions if the running extension uses
a lot of CPU & RAM.
With the new behavior, osquery will never launch multiple extensions.
- if the extension watchdog is enabled, it will kill the old extension then relaunch a new one
- if the extension watchdog is not enabled, it will do nothing
osquery was ignoring the return of `extension.second->checkStatus` and instead looking at
`extension.second->isValid`. `isValid` is just "did the extension ever launch". With the change in
behavior this means that if the extension had been launched once, it would never be relaunched

Do not let osquery create multiple copies of the extension running at once

---

osquery/tables/system/posix/sudoers.cpp
osquery/tables/system/tests/posix/sudoers_tests.cpp

In sudo 1.9.1, sudo changed the include directives from `#include` to
`@include` (See https://github.com/sudo-project/sudo/commit/741c6f274e65f852b7026b10a21dff519b2fd6c2)
Support parsing them.
Along the way, add more tests and update the parsing

Update `sudoers` table to support newer include syntax

---

osquery/core/watcher.cpp
osquery/core/watcher.h

Due to a race condition between the shutdown procedure part
handled by the WatcherRunner::stop and the execution of a new worker
or extension, it's possible that a worker or extension is left running
after the watcher process has exited.
This happens because when requested to shutdown
the WatcherRunner::stop function might not find any extensions or workers
to stop, but they are about to be launched.
This means that the stop function will return not having stopped any
process and the watcher will still start a worker or an extension,
and then finally realize that it has to interrupt and exit,
leaving the child processes running.
This is especially problematic with workers because if starting and
stopping osquery quickly, due to the issue above sometimes at the next
osquery service start, …

Prevent race condition between shutdown and worker or extension launch

---

osquery/tables/yara/yara_events.cpp

When you enable the yara_events table and you map certain rulesets to directories, the rules will only check files if they have the action **CREATED** or **UPDATED**. Because of this, Osquery will eventually miss some files being moved around by bad actors. The `mv` command is a command that is often used to move files around, so if a bad actor moves a file around it is important that those get scanned with corresponding yara rules as well. 
The specific action that should be tracked, included in this PR, is **MOVED_TO**. 
This action corresponds to the following file event on Darwin-based systems: **kFSEventStreamEventFlagItemRenamed**
And to the following file event on linux-based systems: **IN_MOVED_TO**
This fix will make sure that this action is also being tracked.
PS: Maybe it is a …

Make sure that the file action "MOVED_TO" is tracked with yara events.

---

osquery/tables/system/posix/last.cpp
specs/posix/last.table
tests/integration/tables/last.cpp

The utmp numeric values can be impenetrable without referring to the
source code. Includde a column with a little more info.
I don't love the column name here. Suggestions welcome.
Closes: #7092

Add utmp type name column to `last` table

---

osquery/filesystem/fileops.h
osquery/filesystem/windows/fileops.cpp
osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/secureboot.cpp
osquery/tables/system/secureboot.hpp
osquery/tables/system/windows/secureboot.cpp
osquery/utils/conversions/windows/strings.cpp
osquery/utils/conversions/windows/strings.h
specs/CMakeLists.txt
specs/linwin/secureboot.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/secureboot.cpp

Add a `secureboot` table for windows and linux. It works by reading the efivars.
Currently returns `0`, `1`, `NULL`, or `-1`.  (For false, true, unknown, error). I'm not sure I love the `-1`. I don't think we have consistency around those. 
Also extracted the `lastErrorMessage` helper function from it's unused location in `fileops` and moved it to a util class. (Amusingly I did this after I'd already written another version of it. But :shrug: may future me find it helpful)

Add a `secureboot` table for linux and windows

---

.github/workflows/build_aarch64.yml
.github/workflows/build_x86.yml

This allows us to make changes to the packaging repo without interrupting open osquery PRs. We can then make a testable changes to osquery when ready.

Pin the packaging repo within GitHub workflows

---

osquery/tables/system/darwin/process_open_descriptors.cpp

On darwin, `soi_so` is an unsigned 64bit number. sqlite, however, is
signed. Current behavior is to emit a warning, and drop the column.
It's not clear we have a good fix for the type mismatch, so comment and
drop it in the virtual table instead.
Relates to: #6319

Fix process_open_sockets type error on darwin

---

osquery/tables/system/posix/augeas.cpp
osquery/tables/system/tests/posix/augeas_tests.cpp

Add querying by LIKE to the augeas table. This fixes querying the
`/augeas` part of the tree, and should additionally improve the behavior
around file paths.
Prior, there is implicit magic that makes the path part work -- we
append `//*` the augeas recursive wildcard. This combined with sqlite
filtering made it appear to work for simple trailing wildcards. But, it
would fail for leading or infix wildcards.
This replaces that with some additional routines to allow wildcard
conversion. The UX is a bit weird, in that `path` should _not_ have a
trailing wildcard, and the behavior of `%` vs `%%` is different. But
this feels like the simplest bridge between osquery and augeas.
The current problem is mostly clearly visible with `select * from augeas where node like "/augeas/load/%";` returning …

Update `augeas` table to use native pattern matching (BREAKING)

---

osquery/remote/http_client.cpp
osquery/utils/aws/aws_util.cpp

This PR:
* adds a `aws_enable_debugging` FLAG option, to enable AWS-SDK debug logging
* restrics header size for `content-type` in PUT requests to a reasonable length 
This fixes the `ec2_instance_tags` table, and other timeout issues with AWS PUT requests that we been seeing on an IMDSv2 enforced instance

[AWS] Optionally enable debug option and restrict content-type header size for PUT req

---

CMakeLists.txt
docs/wiki/deployment/configuration.md
docs/wiki/deployment/debugging.md
docs/wiki/installation/custom-packages.md
docs/wiki/installation/install-macos.md
tools/windows_resources.rc.in

Changes to update the various facebook names to the osquery ones.
I tried to get the paths as well. I might have missed a couple
Closes: #7159

Update paths, and remove deprecated Facebook names

---

cmake/flags.cmake
osquery/tables/utility/osquery.cpp
osquery/utils/info/platform_type.h

The value of build_platform in the osquery_info table
is currently controlled by the value of the preprocessor macro
OSQUERY_BUILD_PLATFORM, which is hardcoded to `linux` as a macro
passed via CLI.
That macro is then stringified, but the issue is that the `linux`
keyword is also a macro, which gets expanded to 1.
To avoid this collisions, we can set the preprocessor macro value
as a string already from CLI and remove the stringification,
which will prevent further problematic expansions.
We do the same also for the other string macro OSQUERY_BUILD_DISTRO.
NOTE: This is a quick fix for the described issue specifically; the values presented in those columns have additional issues described here: https://github.com/osquery/osquery/issues/7253

Fix osquery_info build_platform column value on Linux

---

specs/uptime.table

https://github.com/osquery/osquery/issues/6395 has an excellent writeup about the different meanings up `uptime`. Seems worth a small note here.

Update `uptime` table descrption

---

docs/wiki/installation/cli-flags.md
plugins/logger/CMakeLists.txt
plugins/logger/filesystem_logger.cpp
tools/tests/test_osqueryd.py

The logger_mode flag was actually interpreted as decimal format number,
not octal.
Now the flag is actually a string and is expected to represent an octal
number.
A validation function has been added to prevent invalid permission modes and
the flag itself is expected to be given at osquery startup only,
not changed during the execution.
This supersedes #7193

Change logger_mode flag to be actually interpreted as an octal

---

docs/wiki/deployment/process-auditing.md
osquery/events/CMakeLists.txt
osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/auditeventpublisher.cpp
osquery/events/linux/auditeventpublisher.h
osquery/events/linux/socket_events.cpp
osquery/events/linux/socket_events.h
osquery/events/tests/CMakeLists.txt
osquery/events/tests/linux/audit_tests.cpp
osquery/events/tests/linux/process_file_events_tests.cpp
osquery/events/tests/linux/socket_events.cpp
osquery/tables/events/linux/process_events.cpp
osquery/tables/events/linux/process_file_events.cpp
osquery/tables/events/linux/socket_events.cpp
osquery/tables/events/linux/socket_events.h
osquery/tables/events/tests/linux/process_events_tests.cpp
specs/posix/socket_events.table

This PR adds support for non-blocking sockets to the Audit-based socket_events table for Linux.
Changes:
* The `success` column has been deprecated (hidden). This was always reporting `1` since the audit event publisher was originally filtering out all the syscall events that had the `success=no` field in the AUDIT_SYSCALL record
* A new `status` column has been added, supporting four values: **failed**, **succeeded**, **in_progress** (`connect` on a non-blocking socket) or **no_client** (`accept` on a non-blocking socket with no incoming connection ready)
* The `--audit_allow_failed_socket_events` boolean flag has been added and can be used to include failed events in the table (default is to **false**)
* The `--audit_allow_null_accept_socket_events` boolean can be used to include …

audit: socket_events improvements

---

docs/wiki/installation/cli-flags.md
osquery/config/config.cpp
osquery/dispatcher/scheduler.cpp
osquery/events/eventfactory.cpp
osquery/events/eventfactory.h
osquery/events/events.cpp
osquery/events/events.h
osquery/sql/sqlite_operations.cpp

While debugging https://github.com/osquery/osquery/issues/7112 we found adverse unintentional effects when queries for event-based tables are denylisted. This can lead to event loss and buffers thrashing at max.
~~This approach is not perfect, it uses a heuristic to check if a query applies to an event-based table by looking for the "_events" suffix. This pattern is enforced by our schema auditing, meaning there will be no false negatives. There can be false positives, for example "osquery_events".~~
I've also added a helper SQLite function `sleep` to be used for testing purposes only. Using this, I can simulate killing the worker and exercising the logic.

Add feature to skip denylist for event-based queries

---

osquery/tables/system/darwin/disk_encryption.mm
osquery/tables/system/linux/disk_encryption.cpp
specs/posix/block_devices.table
specs/posix/disk_encryption.table

While trying to understand some LVM things (which I incorrectly thought was a bug, see #7207) I noticed that these tables were very slow to work with.  Some updates to allow working with QueryContext

Change to the `disk_encryption` table to support QueryContext

---

.github/workflows/build_aarch64.yml
.github/workflows/build_x86.yml

This pins the SHA to the packaging repo which has fixes for linux symlinks

Update packaging SHA

---

osquery/filesystem/CMakeLists.txt
osquery/filesystem/linux/proc.cpp
osquery/filesystem/linux/proc.h
osquery/filesystem/tests/linux/proc_tests.cpp
osquery/tables/networking/linux/process_open_sockets.cpp

AF_PACKET sockets will now be listed along inet, inet6, unix families.
This will allow listing sockets opened by popular software such as tcpdump.

Linux: Support AF_PACKET sockets.

---

osquery/core/system.cpp

We also avoid doing any query to the running processes
if we know that the pid in the pidfile corresponds
to our own process.
Partially addresses https://github.com/osquery/osquery/issues/5233

Prevent osquery from killing itself when the --force flag is used

---

tools/deployment/linux_packaging/deb/osqueryd.service
tools/deployment/linux_packaging/rpm/osqueryd.service

Set value to 5 seconds for consistency with the logic in the init
scripts.
It's not entirely clear to me that the default behavior of systemd would not be adequate, but we have noticed some race conditions in our deployments. We disable osqueryd before upgrading certain files when new versions are pushed and then re-enable it, and sometimes we get alerts from osqueryd for things that happen in the first few seconds. We are hoping this change addresses the issue. However, I believe this is an appropriate fix either way because it makes the systemd service file consistent with the logic in the init script.

Add TimeoutStopSec to systemd service files

---

docs/wiki/installation/install-macos.md

Updates the wiki installation guide page since it was still referencing older install paths on macOS.

Update installation guide to use newer macOS paths

---

docs/wiki/deployment/aws-logging.md
osquery/utils/aws/aws_util.cpp
osquery/utils/aws/aws_util.h
osquery/utils/aws/tests/aws_util_tests.cpp
plugins/logger/aws_firehose.cpp
plugins/logger/aws_firehose.h
plugins/logger/aws_kinesis.cpp
plugins/logger/aws_kinesis.h
plugins/logger/aws_log_forwarder.h
plugins/logger/tests/aws_kinesis_logger_tests.cpp

Added `--aws_firehose_endpoint` and `--aws_kinesis_endpoint` flags to support non-AWS Kinesis and Firehose implementations. Setting the flag disables AWS region validation.

[AWS] Support custom endpoints for Kinesis and Firehose.

---

osquery/tables/system/posix/authorized_keys.cpp

This table implementation produces a lot of unneeded error messages for files that don't exist when cross joining against all users on a system:
```
$ osqueryi "select * from authorized_keys cross join users"
W0922 13:52:54.039000 354004480 glog_logger.cpp:34] Cannot open file for reading: /Users/nabil/.ssh/authorized_keys2
```
This PR introduces a check to see if the file exists before attempting to open it.  If there's no file, it will continue silently.

Reduce excessive log messages from authorized_keys table implementation

---

osquery/tables/system/posix/crontab.cpp

Fixes a long ignored warning:
```
/Users/smjert/Development/osquery/src/osquery/tables/system/posix/crontab.cpp:112:19: warning: loop variable 'cron_dir' of type 'const std::__1::basic_string<char>' creates a copy from type 'const std::__1::basic_string<char>' [-Wrange-loop-analysis]
for (const auto cron_dir : kCronSearchDirs) {
^
/Users/smjert/Development/osquery/src/osquery/tables/system/posix/crontab.cpp:112:8: note: use reference type 'const std::__1::basic_string<char> &' to prevent copying
for (const auto cron_dir : kCronSearchDirs) {
^~~~~~~~~~~~~~~~~~~~~
&
```

Avoid string copies when looping through cron search dirs

---

osquery/process/windows/process.cpp

Detect when a Windows extension has not started, which mirror how the Posix `PlatformProcess` operates. The problem was that `GetExitCodeProcess()` was being called with an invalid handle, which returns a value indicating that the process is still active. So, extensions were never executed.
The fix is to check if the handle is valid prior to checking if the process is alive.
fixes #7324

Windows: Detect when an extension has not started

---

osquery/tables/networking/curl_certificate.cpp

If you use the `curl_certificate` table against a service that requires a client certificate, osquery will not return a certificate even though it is provided as part of the failed handshake.   The following commands reproduce this problem:
```
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes
openssl s_server -key key.pem -cert cert.pem -accept 5000 -www -Verify 1
osqueryi "select * from curl_certificate where hostname='localhost:5000';"
```
The expected output should be the certificate created in the line above.  But instead, no certificate is returned.
This change does not return from the `getTLSCertificate` function until it checks to see if there is a peer certificate in the SSL context.  If there is, it will proceed parsing it.  Otherwise, it will …

`curl` table now returns peer certificates even if the TLS handshake does not complete

---

osquery/tables/system/hash.cpp

**Current Behaviour:** all the columns of `hash` table respect the `read_max` parameter, except `ssdeep` one:
```
$ dd if=/dev/urandom of=/tmp/temp100m bs=1m count=100
osquery> select * from file where path = '/tmp/temp100m';
path = /tmp/temp100m
directory = /tmp
filename = temp100m
inode = 23579345
uid = 501
gid = 0
mode = 0644
device = 0
size = 104857600
block_size = 4096
atime = 1635514968
mtime = 1635514957
ctime = 1635514957
btime = 1635514957
hard_links = 1
symlink = 0
type = regular
bsd_flags =
osquery> select * from hash where path = '/tmp/temp100m';
W1029 19:13:48.575589 319819264 filesystem.cpp:140] Cannot read /tmp/temp100m size exceeds limit: 104857600 > 52428800
path = /tmp/temp100m
directory = /tmp
md5 =
sha1 =
sha256 =
ssdeep = …
```

Respect `read_max` flag when hashing using ssdeep

---

docs/wiki/installation/cli-flags.md
osquery/core/watcher.cpp

[WIP] - Took a stab at implementing #7212. This functionality had some inconsistencies in the docs (around percentages, times, etc.), so I'm still not incredibly confident that this is correct.
I'd like to get some early feedback / corrections to make from maintainers.
Fixes: #7212

Allow custom cpu limit duration for the watchdog

---

docs/wiki/installation/cli-flags.md
osquery/distributed/distributed.cpp

This lowers the default log level of `Executing distributed query` and implements similar functionality to what's described in #6923

Lower log level of `executing distributed query`

---

osquery/events/CMakeLists.txt
osquery/events/linux/bpf/bpferrorstate.cpp
osquery/events/linux/bpf/bpferrorstate.h
osquery/events/linux/bpf/bpfeventpublisher.cpp
osquery/events/linux/bpf/filesystem.cpp
osquery/events/linux/bpf/filesystem.h
osquery/events/linux/bpf/ifilesystem.h
osquery/events/linux/bpf/isystemstatetracker.h
osquery/events/linux/bpf/serializers.cpp
osquery/events/linux/bpf/serializers.h
osquery/events/linux/bpf/systemstatetracker.cpp
osquery/events/linux/bpf/systemstatetracker.h
osquery/events/tests/linux/bpf/bpfeventpublisher.cpp
osquery/events/tests/linux/bpf/mockedfilesystem.cpp
osquery/events/tests/linux/bpf/mockedfilesystem.h
osquery/events/tests/linux/bpf/systemstatetracker.cpp

When capturing syscall events that emit strings (i.e.: chdir()) or buffers (i.e.: connect()), there's a chance the memory we need to access has not been mapped yet (page fault), causing events to lack some of the syscall parameters we need for tracking system state.
This PR improves the BPF publisher reliability by capturing strings on syscall exit (as opposed to using the on enter program), increasing chances that the buffers we need are accessible when our probes run.

bpf: Improve publisher reliability

---

osquery/dispatcher/dispatcher.h

This allows external code/tests such as extensions to call `Dispatcher::resetStopping`. This is helpful when testing end to end osquery state.
Extensions might start osqueryd and then call `startExtension` and want to manage state where osqueryd restarts.

Allow tests and SDK to reset dispatcher state

---

osquery/core/shutdown.cpp
osquery/core/shutdown.h

See https://github.com/osquery/osquery/pull/7372 as this is a companion.
This changes the capability of the shutdown APIs so that they can be called multiple times. And that code can "reset" the request to shutdown.
This is helpful when using the SDK and within an extension that both wants to test this state machine and make decisions based on osqueryd's shutdown thrift API.

Allow tests to reset the restarting state

---

osquery/events/eventsubscriberplugin.cpp
osquery/tables/events/linux/apparmor_events.cpp
osquery/tables/events/linux/seccomp_events.cpp
osquery/tables/events/linux/selinux_events.cpp

Fixes: #7394
- Fixed the expression so the cleanup is triggered correctly.
- Replaced `add()` with `addBatch()` for `selinux_events`, `apparmor_events`, `seccomp_events`

fix for #7394 where cleanup of some event tables never occures

---

osquery/tables/system/windows/windows_security_products.cpp

Prevent a crash happening due to an incorrect displaying of an error code,
which was interpreted as a pointer.
Also transform the error code in hex, so that it's easier to recognize.
Querying this table just after boot might fail the initialization
of the IWSCProductList, which was causing the table to take the error
branch and crash while printing the error.
Thanks to @defensivedepth for reporting the issue and @puffyCid for narrowing it down to the error printing lines.

Fix crash when windows_security_products errors out

---

docs/wiki/development/building.md

Remove an extra 'the' in 'Preparing to build the osquery-packaging repository'

fix: remove typo

---

specs/windows/windows_security_center.table

related to #7399 
code is still fetching the spyware engine status. I guess it should be deleted at the same time with first Windows version that doesn't support this column.

Hide the deprecate `antispyware` column in `windows_security_center`

---

osquery/config/config.cpp

Do not run discovery queries for packs when fuzzing,
since they easily get oss-fuzz to timeout or go oom.

Prevent running discovery queries when fuzzing

---

libraries/cmake/source/sleuthkit/CMakeLists.txt

The thirdparty_sleuthkit_fs_cpp object library actually depends
on thirdparty_sleuthkit_auto but we are not explicitly specifying
that depedency.
Sometimes it works, sometimes it doesn't (like on oss-fuzz).
Add the correct dependency and also change thirdparty_sleuthkit_fs_cpp
to be a STATIC library, because linking to thirdparty_sleuthkit_auto
causes a circular dependency (which is also present upstream),
and CMake can only deal with that if every library involved is STATIC.

Fix linking of thirdparty_sleuthkit

---

osquery/sql/sqlite_util.cpp

Also fix the parsing of the "EXPLAIN QUERY PLAN" output,
since the detail column has changed format for the SCAN operation,
from "SCAN TABLE \<uppercase tablename\>" to just "SCAN \<provided tablename\>".

Update sqlite to version 3.37.0

---

libraries/cmake/source/yara/patches/strutils.cpp
osquery/tables/yara/tests/yara_tests.cpp

Define real wrapper functions instead of function pointers
to the various strutils functions.
Yara was incorrectly attempting to call some internal functions
as normal functions instead of function pointers,
causing the execution to jump to data instead of an instruction.
This would in turn cause a crash.
The reason is that to avoid collisions of functions like strlcpy,
which Yara needs and provides its own definition,
in all the caller contexts we rename the calls to those to yara_strutils_\<funcname\>.
We then define a global variable with the same name
and type of a function pointer.
The problem is that the various callers still include headers
with the definition of strlcpy (renamed to the new name)
which is not a function pointer, but a function.
The compiler therefore doesn't …

Fix a crash when Yara uses its own strutils functions

---

osquery/sql/virtual_sqlite_table.cpp
plugins/config/parsers/auto_constructed_tables.cpp

In sqlite, column names are case insensitive. But, in #6278 I added logic to _add_ the `path` column to ATC configs. Unfortunately, this logic was not case sensitive, and sometimes try to create a table with sql akin to:
```sql
CREATE TABLE atc_downcase(`path` TEXT, `Anum` TEXT, `Path` TEXT)
```
The double `path` and `Path` are a fatal sql error
Refine the `path` checks to be case insensitive.
Fixes #7441

Update the ATC table `path` column check to be case insensitive

---

tools/deployment/osquery.example.conf

Remove `utc` flag in example config file, leftover from #7276

[docs] remove utc flag from example config file

---

cmake/utilities.cmake
tools/deployment/macos_packaging/Info.plist
tools/deployment/macos_packaging/Info.plist.in

My attempt at adding a version to the app bundle.
Fixes #7312 and takes [#7383](https://github.com/osquery/osquery/pull/7383#discussion_r750714364) into consideration.
Uses the existing `getCleanedOsqueryVersion` [function](https://github.com/osquery/osquery/blob/9ecb3f0a77566e7cbc9683b1277a78b25efe1483/cmake/utilities.cmake#L396-L405) that results in a semver-like version string, which conforms to the required format of three period-separated integers, such as 3.2.9.
References
[CFBundleVersion](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion)
[CFBundleShortVersionString](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring)

Add osquery version to macOS app bundle Info.plist

---

osquery/core/system.cpp

In #7276 we removed the functionality of the `--utc` flag. Unfortunately, we also removed the flag. This causes osquery to break on older configurations.
While I'm generally game for some breaking changes, this presents something of a coupling issue. If one wanted utc timestamps, but needed an osquery config to work across multiple versions, there's no way to do it. So, this adds the flag back as a `HIDDEN_FLAG`. (Not sure we have a better pattern for this)

Add `utc` flag back for compatibility

---

osquery/tables/system/darwin/signature.mm

Resolves #7321
Due to [this commit](https://github.com/osquery/osquery/commit/e1676c9ef584b426ca402f41d1ceadfede79b1d9#diff-73482bd04aaa0be86cca133932cedb490d2cfa1ade51dc2269b289b6aecf24b2R54-R55), the `kSecCSCheckNestedCode` flag is always included, therefore, there is no longer a need to check OS version to optionally include this flag.

Removing unnecessary macOS version check

---

CHANGELOG.md

Combined changelog for 5.2.0 and 5.2.1. I _think_ it's reasonable to not ship the 5.2.0 changes?

CHANGELOG 5.2.2

---

osquery/tables/system/tests/windows/registry_tests.cpp
osquery/tables/system/windows/registry.cpp
osquery/tables/system/windows/registry.h

This PR fixes the bug reported at #7350.  It adds  a check whether 'queryKey' returns major error(e.g. access denied) or path not found.
The "path not found" error should be handled when writing registry globs like "HKEY_USERS\\%\SOFTWARE\Python\PythonCore\\%\InstallPath" The first glob wildcard is trivial to be found, but the other once depends on whether user installs any Python software within its registry tree.   
I tested the fix with installing latest Python version for local-user only. My Python installation is stored under "C:\Users\Amir\AppData\Local\Programs\Python\Python310\python.exe" it's not a system location( e.g. c:\program files) .
After my fix the python packages populate to the table.
any feedback is more than welcome, Thanks!

Fix for gathering python packages from any user Python installations

---

osquery/core/windows/wmi.cpp

Previously osquery ceasing to respond indefinitely on connection if the server is broken.
Now the `ConnectServer` call returns in 2 minutes or less to prevent program from ceasing to respond indefinitely.

Improved connection time for broken servers. (#7424)

---

CMakeLists.txt

We don't want to run clang-tidy on third party libraries,
so we set that variable after having declared the third party library
targets. This skips setting the relative target property,
and CMake will build normally.
Setting the CMAKE_CXX_CLANG_TIDY variable in a global scope
is not needed, since all the targets we are interested in
are created in the topmost main() function scope.
Finally, only set the CXX variant of the variable,
since the osquery code doesn't contain C.

Do not run clang-tidy on third party libraries

---

osquery/core/query.cpp

If a scheduled query is against an evented table,
has run at least once and if this query later changes
and it's against a non evented table,
after that query has run, osquery will exit with the error
"Error adding new results to database for query
\<queryname\> JSON object was not an array"
This is because if the query is against an evented table,
osquery always stores an empty JSON object.
When the query changes and is against a non evented table,
there has been a previous run and if the differential is active,
at the next query run, it will take the previous results of the query
deserializing the JSON document and expecting an array,
which is the type used to serialize non evented results.

Change the JSON of the results from an event scheduled query to an array

---

osquery/tables/system/posix/sudoers.cpp
osquery/tables/system/tests/posix/sudoers_tests.cpp

This PR fixes the bug reported at #7421. I handle the case that a line contains a backslash as last character.
The code aggregates multiple lines within  a "rule_details" column. The aggregation logic starts when a line ends with backslash and end when EOF or the next line doesn't end with a backlash.
The code deletes the backslash character in favor of clearness. 
Any feedback is more than welcome, Thanks!

Fix parsing issue when a backslash as the last character on sudoers file line

---

CMakeLists.txt
cmake/utilities.cmake

Add a helper target which can be used to compile all the third party
libraries.
This can be useful if you need to run a tool that instruments the build,
but you're only interested on the osquery portion of the code.
An example for this is the creation of a database for CodeQL.

Add third party libraries target

---

osquery/tables/system/posix/yum_sources.cpp
osquery/tables/system/tests/posix/yum_sources_tests.cpp
specs/posix/yum_sources.table

This PR adds a new mirrorlist column to the yum_sources table.

yum_sources: Include the mirrorlist URL in the table output

---

libraries/cmake/source/dbus/CMakeLists.txt
libraries/cmake/source/expat/CMakeLists.txt
libraries/cmake/source/rocksdb/CMakeLists.txt

RocksDB was incorrectly linking to the thirdparty_cxx_settings target
publicly, leaking its flags (and specifically the one disabling warnings)
to some osquery targets.
Also remove redudant linking of c_settings and cxx_settings in
dbus/expat

Fix third party libraries flags leaking to osquery targets

---

osquery/tables/system/tests/windows/windows_eventlog_tests.cpp

The backslash path separator has to be escaped too in a string,
otherwise it gets decoded with the next character as a special
character.
The warnings:
```
windows_eventlog_tests.cpp(41): warning C4129: 'A': unrecognized character escape sequence
windows_eventlog_tests.cpp(41): warning C4129: 'D': unrecognized character escape sequence
windows_eventlog_tests.cpp(41): warning C4129: 'w': unrecognized character escape sequence
windows_eventlog_tests.cpp(41): warning C4129: 'o': unrecognized character escape sequence
windows_eventlog_tests.cpp(42): warning C4129: 'o': unrecognized character escape sequence
windows_eventlog_tests.cpp(42): warning C4129: 'D': unrecognized character escape sequence
windows_eventlog_tests.cpp(43): warning C4129: 'W': unrecognized character escape sequence …
```

Fix some warnings about unrecognized special characters

---

tests/integration/tables/cpu_info.cpp

This change allows the test to pass on systems with more than one cpu socket present so it fixes #7488.

Change cpu_info test to ensure *at least* one socket is present

---

osquery/extensions/impl_thrift.cpp

Add flag for configuring the thrift protocol factory string size limit to avoid crash reported in #7482

Set string size limit on thrift protocol factory

---

.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml
tests/cppcheck/CMakeLists.txt
tests/cppcheck/suppressions_list.txt
tools/ci/osquery-ubuntu18.04-toolchain.dockerfile

Also improve the analysis performance by skipping analysis
on all third party code.
In practice the `check_source_code` job has gone from ~30m to ~5m.

Update cppcheck to version 2.6.3 and skip analysis for third party code

---

docs/wiki/installation/cli-flags.md
osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp
osquery/core/watcher.h

Add a new flag "watchdog_forced_shutdown_delay" set to a default of 4 seconds,
which separates the timeouts for a forced shutdown due to a resource
limit being hit by a worker or extension, from the timeouts for a normal shutdown.
This flag can also be set to 0, which skips sending a gracefull kill
and directly goes for a SIGKILL.
This has currently no effect on Windows, since the normal
shutdown would issue a TerminateProcess anyway, which kills a process immediately.
The fix was necessary since the watchdog was using the normal shutdown timeouts to kill
a misbehaving worker or extension; this was not ideal,
especially since the lowest amount of time we could wait for a forced kill was 6 seconds.

Fix watchdog not killing unhealthy worker/extension fast enough

---

tools/tests/test_http_server.py

After receiving a request the server would reset/restart
the timeout timer even if the --persist option was present,
which should've blocked any timeout timer to start.
Insert the option check in the reset_timeout helper function.

Fix the test_http_server.py --persist option

---

osquery/tables/system/python_packages.cpp

Somewhat recently, the homebrew project changed the default installation path for its packages on Macs with Apple Silicon (see https://github.com/osquery/osquery/pull/7117).
This PR updates the `python_packages` to look for packages in this new folder (it was already looking in the intel-based homebrew directory).

Ensure `python_packages` checks new homebrew paths

---

tools/analysis/profile.py

This PR fixes two issues I encountered when I recently `./tools/analysis/profile.py --leaks` in my `osquery` development folder.
The most pressing issue is that when this Python script runs the `leaks` binary under the hood, it attempts to do string manipulation on `stdout`. This is allowed in Python2, but in Python3, stdout is now a `bytes` object. This PR updates the calls so they are compatible.
When executing the tool without arguments, the script was looking for an osqueryi binary in `./build/<platform>/osquery/osqueryi` but in practice, builds seem to actually now be located at `./build/osquery/osqueryi`. I've updated the default accordingly.
After making these two changes, I get the expected output from the tool:
```
☁  osquery [jem_fix_leaks] ⚡  ./tools/analysis/profile.py --leaks …
```

Fix regressions in `profile.py --leaks`

---

libraries/cmake/source/ebpfpub/CMakeLists.txt

Update the ebpfpub version so that's possible to specify
to link against the osquery compiled zlib static library,
instead of linking against the system one.
Fixes #7553

Prevent ebpfpub linking against the system zlib

---

.github/workflows/hosted_runners.yml
tools/tests/CMakeLists.txt
tools/tests/test_base.py
tools/tests/test_query_packs.py
tools/tests/test_release.py

- Permit to better control which arguments are passed
to python tests
- Verify that there's no dynamic link
outside standard system libraries folders
on Linux and Darwin
- Verify that there's no unwanted linked library
on Linux and Windows
- Split the query pack test in it's own test script,
since it depends on osquery test framework,
and still requires some work
Related to #5795
Depends on #7557

 Restore some release checks

---

cmake/install_directives.cmake
cmake/utilities.cmake

Generated files should not end up in the source folder,
but the build folder.
Change the generation destination and the install logic accordingly.
To test, configure as usual (I'm using `Ninja` here, with `Make` would be the same), the file will end up in
```
<build folder>/tools/deployment/macos_packaging
```
Then build:
```
DESTDIR=/tmp/osquery ninja install
```
Result:
```
[617/618] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /tmp/osquery/control/osquery.entitlements
-- Installing: /tmp/osquery/control/embedded.provisionprofile
-- Installing: /tmp/osquery/control/Info.plist <----
[...]
-- Installing: /tmp/osquery/opt/osquery/osquery.app/Contents/MacOS/osqueryd
-- Installing: /tmp/osquery/opt/osquery/osquery.app/Contents/embedded.provisionprofile
-- …
```

Change where the macOS Info.plist is generated

---

tests/integration/tables/deb_packages.cpp

The size column of the deb_packages table can be empty
if the Installed-Size field of the package is unknown.
Fixes #7568

Fix DebPackages.test_sanity test

---

.github/workflows/hosted_runners.yml

Managing the required checks is a github UI action, that feels a bit fragile. When I was recently changing the required status checks I found it very hard to tell if the ones I wanted were configured. 
Create a job to gate what's required. The pro is that it makes a single thing to require in the branch protections. The con, is that it might be easier to accidentally change the requirements. But, that would be in the PR. 
Curious what y'all think

Create github workflow target to gate mergeability

---

specs/linux/deb_packages.table

Although both index and additional add the column to the primary key,
index is meant to mark columns that make the row unique.
So the column values should contain unique values.
additional instead marks a column that when provided in a where clause
changes the table behvior, which is more correct in this case,
since the packages will be parsed from a different path than the default.

Use additional instead of index for admindir in deb_packages

---

osquery/tables/system/darwin/processes.cpp
specs/processes.table
tests/integration/tables/processes.cpp

Implements a `kind` column to `processes` table on macOS. This checks if the process is translated (running under rosetta) on apple silicon macs.
(Not sold on the `kind` column name, happy to hear any suggestions)
```
osquery> select * from processes where kind = 'apple' limit 1;
pid = 1
name = launchd
path = /sbin/launchd
cmdline = /sbin/launchd
state = R
cwd = /
...
cpu_type = 16777228
cpu_subtype = -2147483646
kind = apple
```
```
osquery> select * from processes where kind = 'intel' limit 1;
pid = 2710
name = CarbonComponentScannerXPC
path = /System/Library/Frameworks/AudioToolbox.framework/XPCServices/CarbonComponentScannerXPC.xpc/Contents/MacOS/CarbonComponentScannerXPC
cmdline = /System/Library/Frameworks/AudioToolbox.framework/XPCServices/CarbonComponentScannerXPC.xpc/Contents/MacO …
```

macOS: add `translated` column to `processes` table to indicate whether the process is running under rosetta

---

osquery/core/system.cpp
osquery/core/tests/windows/wmi_tests.cpp
osquery/core/windows/wmi.cpp
osquery/core/windows/wmi.h
osquery/tables/networking/windows/arp_cache.cpp
osquery/tables/networking/windows/interfaces.cpp
osquery/tables/system/windows/bitlocker_info.cpp
osquery/tables/system/windows/chassis_info.cpp
osquery/tables/system/windows/cpu_info.cpp
osquery/tables/system/windows/disk_info.cpp
osquery/tables/system/windows/drivers.cpp
osquery/tables/system/windows/hvci_status.cpp
osquery/tables/system/windows/logical_drives.cpp
osquery/tables/system/windows/ntdomains.cpp
osquery/tables/system/windows/os_version.cpp
osquery/tables/system/windows/patches.cpp
osquery/tables/system/windows/physical_disk_performance.cpp
osquery/tables/system/windows/shared_resources.cpp
osquery/tables/system/windows/smbios_tables.cpp
osquery/tables/system/windows/system_info.cpp
osquery/tables/system/windows/tpm_info.cpp
osquery/tables/system/windows/video_info.cpp
osquery/tables/system/windows/windows_optional_features.cpp
osquery/tables/system/windows/wmi_bios_info.cpp
osquery/tables/system/windows/wmi_cli_event_consumers.cpp
osquery/tables/system/windows/wmi_event_filters.cpp
osquery/tables/system/windows/wmi_filter_consumer_binding.cpp
osquery/tables/system/windows/wmi_script_event_consumers.cpp

Also change all the relevant calling sites to check for errors and do something sensible in that case.
Fixes #7448.

Replace WmiRequest constructor with static factory method

---

cmake/flags.cmake
cmake/options.cmake

Adds `OSQUERY_ENABLE_THREAD_SANITIZER` CMake flag to optionally build with ThreadSanitizer enabled on POSIX platforms

Support optionally building with ThreadSanitizer (TSan)

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/tests/filesystem.cpp

Currently, when opening or reading a named pipe (or fifo), osquery will block. This is a potential avenue for a denial of service attack.
After some investigation, I believe the comment [here](https://github.com/osquery/osquery/blob/master/osquery/filesystem/filesystem.cpp#L97) is incorrect.
>  // A special file cannot be read in non-blocking mode, reopen in blocking
>       // mode
According to [The Linux Programming Interface](https://www.oreilly.com/library/view/the-linux-programming/9781593272203/) Section 5.9
> Nonblocking mode can be used with devices (e.g., terminals and pseudoterminals), pipes, FIFOs, and sockets. (Because file descriptors for pipes and sockets are not obtained using open(), we must enable this flag using the fcntl() F_SETFL operation described in Section 5.3.)
> …

Eliminate removal of nonblocking flag for "special" files

---

CHANGELOG.md

~NOTE: this also contains the changelog for 5.2.2 which was pushed after the 5.2.2 tag, so it wasn't contained in the 5.2.3 branch.~

CHANGELOG 5.2.3

---

osquery/database/database.cpp
osquery/database/database.h
osquery/dispatcher/distributed_runner.cpp
osquery/distributed/distributed.cpp
osquery/distributed/distributed.h
osquery/distributed/tests/distributed_tests.cpp

Move the distributed plugin RocksDB metadata to a different domain
which is not used or touched by the config plugin.
Also do not acquire the pending queries multiple times just to count
them. Acquire them once, use the obtained vector to count them
and then use them to proceed executing the queries.

Fix crash due to interaction between distributed and config plugin

---

libraries/cmake/formula/openssl/CMakeLists.txt

Add the OSQUERY_OPENSSL_ARCHIVE_PATH option to be able to specify
a path to a local archive of the openssl source code.
This permits to have a better UX when attempting offline builds,
since CMake won't attempt to download it anymore.
Related to #5598

Add an option to specify a path to the openssl archive

---

plugins/logger/tls_logger.cpp

The TLS logger plugin sends two types of logs, results log and status log. If `--verbose` option specified the logger will frequently send status logs to remote server, which may cause undesirable bandwidth usage.  Currently the logger plugin dose not provide an option to opt out the status logs sending.
This PR adds a flag option `--tls_disable_status_log` that will prevent status log being sent to the remote server. The default value of this option is false, so no impact to the previous behavior.
Here are the test results from my local
Test query
```json
{
"schedule": {
"test_query": {
"query": "select year from time",
"interval": 10,
"snapshot": true
}
}
}
```
Without `--tls_disable_status_log`
```shell
./osqueryd --verbose --ephemeral --disable_database \
--tls_hostname localhost:8088 …
```

Make TLS status logging configurable

---

packs/osx-attacks.conf

Hi,
I would like to make a minor improvement to avoid false positives for `Behavioral_Reverse_Shell` query in osx-attacks pack. Certain build processes are spawned by IDEs such as Xcode which do not have any open files, but have an open socket that is not a network socket which results in remote_port being 0 and remote_address empty. 
In this PR, I basically add a check for `process_open_sockets.remote_port > 0` to avoid all possible false positives which do not indicate a reverse shell. We can confirm it's safe considering port `0` is [reserved](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) and cannot be used for network sockets.

packs: Update reverse shell query pack to check for a valid remote_port

---

tools/tests/test_osqueryd.py

The osquery logic for SIGHUP has long been removed
and actually that signal does close osquery.
The test was flaky because it wasn't waiting enough time
for the process to receive the signal and close,
so most of the times it seemed that nothing was happening
to the daemon.
Fixes #7192

Remove the test_daemon_sighup test

---

osquery/core/flags.cpp
osquery/core/flags.h
osquery/sql/sqlite_util.cpp
plugins/config/parsers/options.cpp

CLI_FLAG should not be set/updated in a config file,
but set once via a flagfile or passed at the process startup.
In the next release the ability to do so will be completely removed.
Also change the disable_tables and enable_tables flags
to CLI_FLAG since changes to them won't be reflected at runtime,
but it's also not desirable to have them change at runtime
for security reasons.
Partially Addresses #6533

Warn about setting CLI_FLAGs in the config

---

osquery/tables/system/darwin/disk_encryption.mm

There's a constant `kHardcodedDiskUUIDs` that contains UUIDs of disks in macOS. One of them was clearly intended to be `EBC6C064-0000-11AA-AA11-00306543ECAC` indicating `Type: Personal Recovery User` but the last character of the string was truncated in a copy/paste long ago.
We haven't documented the provenance of these UUIDs, but, if you have enabled FileVault, run the command `diskutil apfs listusers /` and it outputs a list of `Cryptographic users` for that volume, which corresponds to the cryptographic keys. Each is identified by a UUID, and one of them is `EBC6C064-0000-11AA-AA11-00306543ECAC`.
Credit to @elopez for the discovery.

Fix a UUID typo in the `disk_encryption` table

---

.github/ISSUE_TEMPLATE/Blueprint.md
.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/Feature_Request.md
.github/ISSUE_TEMPLATE/Free_Form.md
.github/ISSUE_TEMPLATE/New_Release.md
.github/ISSUE_TEMPLATE/Question.md

This PR just updates the "New Release" issue template, specifically because we no longer post new tagged release binaries to Slack. They become available on the Releases page as build artifacts.
That change was mine. Then GitHub has updated the other templates with some additional hidden fields.

Update the "new release" issue template

---

osquery/config/config.cpp
osquery/core/CMakeLists.txt
osquery/core/init.cpp
osquery/core/system.h
osquery/core/tests/CMakeLists.txt
osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp
osquery/core/watcher.h
osquery/process/posix/process.cpp
osquery/process/process.h
osquery/process/windows/process.cpp

- Add support for handling a SIGUSR1 signal which will be used on posix
platforms by the watcher to immediately signal the worker that a
resource limit has been hit. Logic in the worker will prevent to
remove trace of the fact that a query was running when the limit was
hit, by avoiding clearing up the name of the executing query from the database.
- Improve on the scheduler shutdown logic; even after receiving
a shutdown request, the scheduler was first executing
all the queries in the schedule and only then it was exiting.
This was potentially causing unnecessary forced kills by the watchdog,
which would result in denylisting queries that were not causing
any resource limit to be hit, due to them not finishing in time.
Check for the need to exit after each query execution instead.
- …

Improve scheduled query denylisting and scheduler shutdown

---

osquery/dispatcher/tests/scheduler.cpp

The test was not resetting the shutdown status,
which gets set everytime the scheduler does all the steps
it was requested to do.
Due to a recent change the scheduler was correctly
not executing queries anymore if the shutdown was requested.
This often caused very low execution time
and the test expecting at least 1ms drift was failing.
Fixes #7612

Fix SchedulerTests.test_scheduler_drift_accumulation flakyness

---

.github/workflows/hosted_runners.yml
cmake/flags.cmake
docs/wiki/development/building.md

- The check was never done when using a system toolchain
due to an incorrect test on the toolchain sysroot variable.
- Correct a typo in the names of the variables that the PIE check sets
when PIE is supported.
NOTE: This wasn't negatively affecting the official builds on any platform, or any build done with our toolchain. It was already building correctly with PIE. Builds using a system compiler though (like with oss-fuzz), were not PIE.
EDIT: Changed the description to reflect the status after the latest changes.

Fix check for PIE support

---

osquery/filesystem/fileops.h
osquery/filesystem/posix/fileops.cpp
osquery/filesystem/windows/fileops.cpp
osquery/tables/yara/tests/yara_tests.cpp
osquery/tables/yara/yara.cpp
osquery/tables/yara/yara_events.cpp
osquery/tables/yara/yara_utils.cpp
osquery/tables/yara/yara_utils.h

- Use RAII structures to fix leaks around the management
of the rules cache and the rule compiler.
- Fix a leak in the Yara library caused by passing
a file descriptor as the rule file that actually points
to a directory instead of a file.
- Minor improvements to avoid recalculating the hash
of the rule files, used as a key into the rules cache.
Fixes #7610 
Fixes #7475

Fix multiple Yara leaks

---

specs/windows/tpm_info.table

This is a small non-code change that corrects the spelling of the word `owned` in the documentation associated with the `tpm_info` table.

Fix spelling of the word "owned"

---

osquery/core/system.cpp

This is a regression from last time we updated Thrift
and seems to affect only Linux.
Thrift had a patch to ignore the EINTR error
when waiting for connections.
This is because on Linux when dropping privileges
we call libc APIs to change user and groups
that require all threads to change credentials too.
The mechanism uses signals,
which interrupt other syscalls (like a poll) with EINTR.
Thrift has some limited retries for the EINTR case,
but it's pretty easy to hit.
Instead of patching Thrift it's possible to call
the underlying syscalls to change user and group
for a single thread, because the signaling mechanism
is implemented by the libc library only.
This was already partially done but missing
on a couple more function calls.
Fixes #7586
Fixes #7602

Fix thrift server shutting down when dropping privileges

---

osquery/remote/transports/tls.cpp
osquery/utils/aws/aws_util.cpp

Revert "Fixes osquery tls connections to aws kinesis when tls_server_certs is set (#7450)"
This reverts commit 97815bd68c36df4c997dbeff3a9c113f5a8d24ba.
This doesn't actually fix the issue the PR was set to fix.
The certificates are always needed to be set,
the difference though is that it might be desirable to have
a set of configurations for internal use,
to have osquery connect to a fleet manager,
and another set for other services, like AWS, Azure etc.
Fixes #7632

Fix AWS certificate verification failing on all services 

---

osquery/tables/system/darwin/pci_devices.cpp
osquery/utils/conversions/darwin/iokit.cpp

Sometimes querying `pci_devices` on Apple Silicon macs would result in `std::bad_alloc`. 
The way to trigger this would be `select * from pci_devices` in quick succession (about 10ish times). This was because we were not doing bounds check on a vector

fix std::bad_alloc on pci_devices on Apple Silicon macs

---

osquery/tables/system/darwin/system_info.cpp

Use IOKit IODeviceTree `model` instead of `product-model`

Fix hardware_model for Apple Silicon

---

specs/darwin/browser_plugins.table

The naming of the table `browser_plugins` is pretty expansive. As a newbie, I thought I could just query it for everything! Turns out there are browser-specific tables and this table, despite it's name, references tech that is no longer supported across major browsers (https://en.wikipedia.org/wiki/NPAPI#Support). 
This PR adds some language around that to try alleviate the potential confusion and also communicate to the user that the CNPAPI is widely no longer supported. 
Maybe this is a first step towards getting rid of this table?

clarify browser_plugins table is referencing basically unsupported CNPAPI tech

---

osquery/config/config.h
osquery/config/tests/config_tests.cpp
plugins/config/parsers/options.cpp

Also change the `disable_tables` and `enable_tables` flags
to CLI_FLAG since changes to them won't be reflected at runtime,
but it's also not desirable to have them change at runtime
for security reasons.
Fixes #6533 
NOTE: This has a slight spin to the original fix; I didn't want to touch the `Flag::updateValue` API because I think that should be still usable as-is internally and especially for tests, since the real issue comes from the "options" config parser.

Prevent CLI_FLAGs to be set via config

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/filesystem.h
osquery/filesystem/mock_file_structure.cpp
osquery/filesystem/mock_file_structure.h
osquery/filesystem/tests/fileops.cpp
osquery/filesystem/tests/filesystem.cpp
osquery/main/windows/main.cpp
tests/integration/tables/file.cpp

This PR adds a new function that sets the default locale to utf-8, fixing std::wstring -> std::string conversion issues in boost::filesystem::path and std::filesystem::path.
I have verified that this change should at least fix the following tables: chrome_extensions, hash, file.

Fix MBCS support on Windows

---

osquery/core/windows/global_users_groups_cache.h
osquery/tables/system/tests/system_tables_tests.cpp
tests/integration/tables/CMakeLists.txt
tests/integration/tables/certificates.cpp
tests/integration/tables/chrome_extensions.cpp
tests/integration/tables/firefox_addons.cpp
tests/integration/tables/groups.cpp
tests/integration/tables/ssh_configs.cpp
tests/integration/tables/user_groups.cpp
tests/integration/tables/user_ssh_keys.cpp
tests/integration/tables/users.cpp
tests/test_util.cpp
tests/test_util.h

Some of the tests making queries on tables that were
indirectly making use of the users and groups cached information
were sometimes failing because the needed services were not started.
This starts the appropriate services and makes sure to reset
the futures needed to access the cache, so that all the tests
that do not initialize the services on their own will fail,
instead of relying on a previous initialization.

Initialize users and groups services on all tests that need them

---

osquery/core/system.cpp
osquery/core/system.h
osquery/utils/system/CMakeLists.txt
osquery/utils/system/posix/system.cpp
osquery/utils/system/posix/system.h
osquery/utils/system/system.h
osquery/utils/system/windows/system.cpp

- The computer_name and local_hostname columns where incorrectly
truncating Unicode characters when the computer name contained them.
Use the WinAPI to get the computer name instead of the POSIX one,
which correctly supports Unicode.
- Minor cleanup on the getHostname implementation of Linux and macOS too,
since POSIX guarantees the same max size.
On Windows this can be tested by:
1. Opening a Windows Powershell terminal (not Powershell core)
2. Run the following commands:
```
$computerName = Get-WmiObject Win32_ComputerSystem
$computerName.Rename("TEST-ƒ")
```
3. Reboot, then query `system_info` with osquery pre and post this patch

Fix system-info support for Unicode characters on Windows

---

osquery/utils/linux/dpkg/dpkgquery.cpp

This PR fixes a regression in the dpkg helpers, removing the package arch field from the package name.
Fixes: #7637

deb_packages: Do not display arch info in the package name

---

osquery/tables/system/linux/memory_info.cpp
specs/linux/memory_info.table
tests/integration/tables/memory_info.cpp

This PR adds support for `memory_available` (`MemAvailable` in `/proc/meminfo`) for Linux.
Memory Available is the proper way to identify how much RAM is available to run new process without swapping in Linux according to [this kernel commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773)

Add support for Memory Available in Linux

---

osquery/config/config.cpp
osquery/config/config.h
osquery/core/flags.cpp
osquery/core/flags.h
osquery/main/harnesses/fuzz_config.cpp

- Speed up config parsing in stripConfigComments by using string_view
to avoid unnecessary and slow string copies
- Speed up osqueryfuzz-config by periodically resetting
the custom flags map
- Lower the chances of an OOM by periodically resetting
the options config parser state, since it grows incrementally
each time it parses new options. Also call malloc_trim.
Related to #7634

Improve config parsing and osqueryfuzz-config performance

---

CMakeLists.txt
cmake/ccache.cmake
cmake/globals.cmake
cmake/options.cmake

Add OSQUERY_ENABLE_CCACHE CMake option, default to ON,
to enable or disable using ccache during the build.

cmake: Add an option to enable or disable using ccache

---

docs/wiki/deployment/file-integrity-monitoring.md

The correct flag is `--enable_ntfs_event_publisher` as output by the `.features` command in osqueryi.

Fix typo in FIM docs for Windows

---

osquery/tables/system/windows/windows_crashes.cpp

The `windows_crashes` table locates the directory containing the crash dumps by reading a path string from a registry key. If this path contains environment variables, handling this string as the path may fail to find the directory. This change passes the path string through the (existing) osquery utility function, [expandEnvString](https://github.com/osquery/osquery/blob/d2be385d71f401c85872f00d479df8f499164c5a/osquery/utils/system/env.h#L37) before handling it. E.g., it would change `%TMP%` to `C:\Windows\Temp`.
The added code appears similar to what is in the `services` table: https://github.com/osquery/osquery/blob/d2be385d71f401c85872f00d479df8f499164c5a/osquery/tables/system/windows/services.cpp#L141
(description added by @mike-myers-tob)

Expand env vars for the windows_crashes table

---

osquery/tables/system/darwin/kernel_panics.cpp

Fixes #7215 by unwrapping a light layer of undocumented obfuscation (JSON) that Apple added to their semi-structured plaintext kernel panic log files up through macOS 10.15. Some columns don't appear to exist anymore, or might just be missing from my crash dump: `dependencies`, `last_unloaded`, etc.
Example of table working to parse a crash dump:
```
mmyers@mmyerss-Mac build % ./osquery/osqueryi
osquery> select * from kernel_panics;
path = /Library/Logs/DiagnosticReports/Kernel-2022-05-05-173858.panic
time = 2022-05-05 17:38:58.00 -0700
registers = 
frame_backtrace = 0xffffffe0735e3210 : 0xffffff8019c83e2d
module_backtrace = 
dependencies = 
name = dtrace
os_version = 21E258
kernel_version = Darwin Kernel Version …
```

Restore macOS `kernel_panics` table on modern macOS

---

docs/wiki/development/building.md

This PR updates the Windows test section under [building osquery](https://osquery.readthedocs.io/en/stable/development/building/) to explain how to use GTEST_FILTER on PowerShell.
Just documentation. It doesn't contain any code changes.

Adds info on how to use GTEST_FILTER on windows

---

osquery/tables/system/darwin/password_policy.cpp
specs/darwin/password_policy.table

`uid` is now `-1` for global password policies.
Addresses #7688

macos: `password_policy` table, use `-1` as sentinel value for `uid` column

---

.github/workflows/hosted_runners.yml

CI jobs that need a Catalina machine are getting canceled due to a scheduled brownout, see:
https://github.com/actions/virtual-environments/issues/5583
and for example the checks in https://github.com/osquery/osquery/pull/7699
The PR prepares the test job to run on Big Sur, but disables it because it really only make sense if we are building on Monterey.
Since we are currently building on Big Sur and in the same job running the tests, having another job that does the same thing doesn't make sense.
So this unblocks the CI, letting us update to building on Monterey later.

ci: Update and temporarily disable the macOS Catalina test job

---

osquery/core/sql/column.h
osquery/core/tables.cpp
tools/codegen/gentable.py

Some of the data osquery conveys is case insensitive. Correctly working with this data requires either updating column definitions to set the collating sequence, or updating all sql queries to use case insensitive operations. I think it's reasonable for us to handle this correctly under the hood. (This is required background work for #7673)
This adds a column option of the form `collate_nocase=True`. To be honest, I'd prefer `collate="NOCASE"` -- it reads cleaner and has better future proofing. But that looks it would require deeper changes to how the autogeneration stuff works.
I'd love feedback
* `collate_nocase=True` or the larger work for `collate="NOCASE"` ?
* Other thoughts?

Add table spec support for `COLLATE NOCASE`

---

osquery/filesystem/filesystem.cpp

The function did not check whether the `user` had a `directory` so for
systems that have a NULL directory for a single user, this function
throws and exception. This checks that the directory exists before
accessing it.

Fix bug in GetHomeDirectories filesystem function

---

osquery/tables/system/windows/smbios_tables.cpp

Uses the [`std::wcstoull`](https://en.cppreference.com/w/cpp/string/wide/wcstoul) functionality of detecting the base automatically.

Fix `GetMemorySize` for Windows `memory_devices` table

---

specs/darwin/screenlock.table

Since Apple locked down the screenlock data, Kollide and osquery implemented a workaround (https://www.kolide.com/blog/how-kolide-built-its-macos-screenlock-check). The screenlock table is only for the current user context, but the table spec did not add the user_data=True attribute to reflect it. This PR adds that attribute.

Describe user-context-related caveat for screenlock table

---

docs/wiki/deployment/process-auditing.md
osquery/events/linux/auditdnetlink.cpp
osquery/events/linux/auditdnetlink.h

- Reduced the amount of audit records read as a batch
from 4096 to 1024, to reduce the average number of them
that has to be kept in memory.
- Introduced a throttling mechanism between the netlink reader
and the records processing, and then between the records processing
and the audit publisher, which generates events.
This is to ensure that it's not possible to have a backlog that's
always increasing and that's bigger of a certain amount.
- Prevent some unnecessary work happening in the processing thread,
by always sleeping for 1 second if there's no records to be processed.
We noticed that in environments where:
1. Audit is used and a continuous amount of audit records is captured
2. There's a limited CPU availability due to few cores and high CPU load, or the osquery worker process CPU …

Prevent the audit event system from using too much memory

---

osquery/carver/carver.cpp
osquery/filesystem/file_compression.cpp

Fixes #7679 
Archives will now use full path names:
```
➜  scratch tar -tf helloworld.tar
/tmp/osquery_carve_f5613894-26e9-4c03-b171-411d5240e5b8/tmp/hello world.txt
➜  scratch tar -tf foo.tar
/tmp/osquery_carve_56c6dfe1-72f8-424e-99b5-8c6ff2395ed3/tmp/foo/foo 1/foo_random.data
/tmp/osquery_carve_56c6dfe1-72f8-424e-99b5-8c6ff2395ed3/tmp/foo/foo 2/foo_random.data
/tmp/osquery_carve_56c6dfe1-72f8-424e-99b5-8c6ff2395ed3/tmp/foo/foo 3/foo_random.data
```

carves: use full pathnames while creating an archive

---

tests/integration/tables/memory_devices.cpp

This will fix CI for linux aarch64. The test must be changed to perform
proper validation, rather than a naive assumption that a memory device
row will always be present. The validation will require more updates
to the table code, so this is the temporary fix.

Temporarily disable memory_devices integration test

---

docs/wiki/deployment/configuration.md
docs/wiki/deployment/debugging.md
osquery/database/database.cpp
osquery/database/database.h
osquery/dispatcher/distributed_runner.cpp
osquery/dispatcher/tests/scheduler.cpp
osquery/distributed/distributed.cpp
osquery/distributed/distributed.h
osquery/distributed/tests/distributed_tests.cpp

Implements proposal #7658.
Am not sure about the default value for denylisting expiration, my guess is we could start with a default value of `1h`.
Apart from the added unit tests I manually tested this with Fleet, by running an expensive live query twice (first time to cause the watcher to kill the worker, second time to verify denylisting):

Add denylist mechanism to distributed queries

---

osquery/tables/system/darwin/battery.mm

Apple's x86 laptops report battery status in mAh but its ARM laptops use percent.
This commit uses an undocumented raw capacity field which reports mAh on both x86 and ARM laptops. I've tested on a 2022 M2 MacBook Pro and a 2012 i5 MacBook Pro, both running macOS 12. However, this needs more testing on more systems.
This will partially fix #6800 but will not fix the incorrect health column. I've spent a while trying to figure out how the Battery.prefPane and coconutBattery get correct results but so far I've only found that Battery.prefPane uses `IOPSCopyPowerSourcesByType(1)` then gets the `Battery Service State` field from the first battery, which does not exist for me

Get raw battery max and current capacity on macOS

---

specs/windows/registry.table

According to https://docs.microsoft.com/en-us/windows/win32/sysinfo/structure-of-the-registry the `key` on the windows registry is case insensitive. This sets the default collation
Fixes: #7673

Update the `registry` table to be case insensitive for `key`

---

osquery/tables/system/darwin/mdfind.mm

The default of 5 seconds is quite low in general,
beyond making the mdfind test flaky.
Fixes #7531

Increase mdfind query timeout to 30 seconds

---

osquery/tables/system/windows/smbios_tables.cpp
specs/platform_info.table

Tested on Windows 11 and Windows 7 VM's. Adds a column with the value for the firmware type of the system, with possible output values of:
- `Uefi`
- `Bios`
- `Unknown`

Add `firmware_type` column to `platform_info` table on Windows.

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/processes.cpp
osquery/tables/system/linux/processes.h
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/linux/processes_tests.cpp
specs/processes.table
tests/integration/tables/processes.cpp

This will read the full cgroup path out of /proc for each process in the process table. I've tested this with cgroup v2 (unified hierarchies) but have not yet tested it with cgroup v1 (where each group type has a separate hierarchy). On cgroup v1 it should report the first cgroup it's in but that may not be consistently the same type. Proper cgroup v1 support would require a different schema as each process can be in 13 different hierarchies.
This does involve several string copies but I couldn't find a clean way of doing it with fewer.

processes: add `cgroup_path` column on Linux

---

osquery/tables/applications/browser_firefox.cpp
specs/firefox_addons.table

This functionality seems to have been [removed from Firefox since 2015](https://blog.mozilla.org/addons/2015/05/04/dropping-support-for-binary-components/). In our testing we never saw this have a nonzero value.

Remove `binary` column from `firefox_addons` table

---

osquery/tables/system/darwin/smbios_tables.cpp
specs/platform_info.table
tests/integration/tables/platform_info.cpp

This PR adds macOS support for the firmware_type column introduced in https://github.com/osquery/osquery/pull/7710

platform_info: Add `firmware_type` to macOS

---

osquery/tables/system/darwin/mdfind.mm

- Run the RunLoop for 1 second each time instead of a single pass
to then check the spotlight queries status,
since this means that we are checking the queries status and re-running
the loop thousands of times per second.
This causes the osquery worker to use a full core for the duration of
the query and the watchdog to kill it.
- Support quick interruption of a mdfind query if a shutdown is requested

mdfind: Reduce table overhead and support quick interruption

---

docs/wiki/deployment/debugging.md
osquery/remote/transports/tls.cpp

This change now matches the documentation:
https://github.com/osquery/osquery/blob/3da346d218115556aa5640226f6ee6e000bf0e07/docs/wiki/deployment/debugging.md?plain=1#L199-L201

Have `--tls_dump` output body to `stderr`

---

tests/integration/tables/platform_info.cpp

The address, size, and volume_size columns
have been recently become hidden on Windows, because they don't contain data,
don't test them.
This went through because a PR that was making those columns hidden has been merged just before the PR that was activating the test, and since we don't force that PRs are in sync with master, the PR activating the test was successful (because the columns were still available).

test: Fix platform-info.test_sanity on Windows

---

osquery/system/usersgroups/windows/groups_service.cpp
osquery/system/usersgroups/windows/users_service.cpp
osquery/tables/system/windows/user_groups.cpp
osquery/utils/system/windows/users_groups_helpers.cpp
osquery/utils/system/windows/users_groups_helpers.h

Ideally in the future we create factory functions/wrappers for each Windows API that allocates, so that's possible to create a smart pointer without giving access to the smart pointer internals (like with `get_new_ptr()`).
Fixes #7754

Fix a leak and improve users and groups APIs on Windows

---

specs/platform_info.table
tools/codegen/gentable.py
tools/codegen/genwebsitejson.py

At Fleet we would like to be able to include platforms on extended schema updates in our web interface (see fleetdm/fleet#7236). This PR changes how the platforms field works in extended_schema and includes them in the output of `genwebsitejson.py`

codegen: Include extended schema platforms in website json

---

osquery/tables/events/linux/process_file_events.cpp
osquery/tables/events/linux/process_file_events.h

The process_file_events subscriber was not finding its data
in the database, so no event was shown.
The setUp() function shouldn't be overridden
by the implementation of the subscriber,
otherwise vital information about the subscriber
and where it should search its data in the database is not setup.
Only init() should be used.

Fix `process_file_events` subscriber being incorrectly initialized

---

osquery/tables/system/darwin/running_apps.mm
specs/darwin/running_apps.table
tests/integration/tables/running_apps.cpp

This column will only return accurate data when on query in `osqueryi`. This means that whenever this table is queried via distributed or scheduled queries, it will return false and inaccurate data.
This is a quirk of the NSWorkspace API on macOS, which needs to be run from the main thread only. I tried looking at the slightly higher cocoa API to replace this, but couldn’t find any.
I am also unaware of very many users of this column, and I think it should be okay to deprecate it.

Remove deprecate `is_running` column from macOS `running_apps` table

---

tests/integration/tables/running_apps.cpp

fix sanity test for `running_apps` table

macOS: fix sanity test for `running_apps` table

---

docs/wiki/installation/cli-flags.md
osquery/tables/cloud/aws/ec2_instance_metadata.cpp
osquery/tables/cloud/aws/ec2_instance_tags.cpp
osquery/utils/aws/aws_util.cpp
osquery/utils/aws/aws_util.h

- Introduce the flag aws_imdsv2_request_attempts
to specify how many attempts should be done
to retrieve an IMDSv2 token to do a secure request.
- Introduce the flag aws_imdsv2_request_interval
to specify the base seconds to wait between attempts,
which scales quadratically with the number of attempts.
- Introduce the flag aws_disable_imdsv1_fallback
which disables IMDSv1 as a fallback if the IMDSv2 token
fails to be retrieved.
- Remove the automatic check to see if osquery
is running on an EC2 instance.
- Improve the retrieval of instance id and region.
If the retrieval keeps failing, don't cache empty values,
keep retrying on next requests until it has success,
then cache the values.
- Improve error message when STS credentials fail to be retrieved.
The hardcoded error was hiding the …

Improvements to osquery AWS logic

---

packs/incident-response.conf

This PR updates the `process_memory_map` query from `linux` to `posix`, so that it will execute on macOS machines where it is also beneficial.

packs/incident_response: process_memory_map is also applicable to Darwin

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/processes.cpp
osquery/tables/system/linux/processes.cpp
osquery/utils/system/CMakeLists.txt
osquery/utils/system/boottime.h
osquery/utils/system/linux/boottime.cpp

- Linux: instead of using the uptime and having to extrapolate the boot time and then calculate the start time, which causes multiple clock reads and therefore an inherent imprecision in the final result, we read directly the boot time from procfs once and keep it in memory for the whole process duration.
- macOS: instead of extrapolating the process age and then use that to calculate the start time, which is again done through two different clock reads, read the already correct start time from another API. This also fixes a bug with system sleep, since the start time retrieved by the previous APIs was a relative value that didn't include system sleep.
Fixes #7556, #6911

`processes`: Stabilize the `start_time` column value on macOS and Linux

---

osquery/tables/applications/posix/docker.cpp

Fixes fleetdm/fleet#8007
This patch is quite simple and seems to work on my macOS 12.6 system, though I don't have a macOS 13 system to test.
Reporting any finished_at time makes no sense when a container is running, even if that time isn't 1 CE like it is on macOS 13. Therefore I decided to leave the column empty when the container is running, instead of checking if the date makes sense.

docker_containers: Don't report finished_at for a container which is still running

---

osquery/tables/system/windows/logged_in_users.cpp

Fixes empty "host" column from logged_in_users table

Fix the empty `host` column from `logged_in_users` table

---

.github/workflows/hosted_runners.yml
tools/ci/scripts/macos/package_tests.sh

Use the same version of python when installing the modules via pip and when configuring osquery, otherwise the tests
will not find the modules.
Fixes #7812

ci: Fix python version when installing modules and testing on macos

---

osquery/tables/system/windows/pipes.cpp

This is in response to the #7809 
Fixing the sharing mode parameter of CreateFileW API in genPipes() to open pipes in sharing mode, so that other processes can have read/write/delete access to the pipes when osquery's handles to those pipes are still open.

Fix permissions on opening pipes for reading in `pipes` table

---

osquery/utils/aws/aws_util.cpp
plugins/logger/aws_log_forwarder.h
plugins/logger/buffered.cpp

- Fixes the retry mechanism of some AWS HTTP requests in some cases, like STS. The osquery MakeRequest implementation for the AWS SDK was incorrectly setting a 200 response code when the osquery http client would throw an exception, due to some internal error or simply due to reaching the timeout for sending the request. Not only this hides some of the logging that could happen when this is reported as an error, but it also prevents the AWS SDK logic to retry again.
- Improve again the STS credentials retrieval failure message, since in some cases the error message was empty. Now print the error message when present, the STS error type, and the HTTP response code, when present.
- Improve support on shutting down quickly when the AWS logger plugin is retrying sending logs.
Some more …

Fix handling of some errors during an AWS HTTP request

---

osquery/core/watcher.cpp
osquery/dispatcher/scheduler.cpp
osquery/logger/data_logger.h
osquery/logger/logger.cpp

A deadlock could happen if a log relay thread
was trying to serialize logs into the database
when a database reset was being attempted.
Since the log relay thread is started by the same thread that executes the database reset, the scheduler thread, ensure that the log relay thread has finished its work before doing a database reset on the next scheduler loop.
Also ensure that when the scheduler is finishing its work, to permit osquery to exit, we wait on the log relaying thread if it's still running to prevent race conditions
and possible crashes on shutdown.
Finally remove the relayStatusLog call from the watcher process, it's a no-op since there's no logger plugin active.
Since the database reset doesn't happen at every scheduler step, but every `schedule_reload` seconds, and by default …

Fix deadlock when logging happens during a database reset

---

.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml

The set-output command is being deprecated,
use the special $GITHUB_OUTPUT environment file instead.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: Update how we set github workflow step outputs

---

osquery/tables/system/windows/shimcache.cpp

Per Slack discussion, change shimcache table to only pull from `CurrentControlSet`. This will fix the duplicates.
Closes: https://github.com/osquery/osquery/issues/7831

Shimcache: Only check CurrentControlSet

---

osquery/events/darwin/endpointsecurity.h
osquery/events/darwin/es_utils.cpp
osquery/tables/events/darwin/es_process_events.cpp
specs/darwin/es_process_events.table

Adds column to the macOS es_process_events table to indicate information about codesigning flags for the process. This is useful data to include to detect processes that may be tampered with or more vulnerable to it.
This data is available in the es_process_t struct codesigning_flags field [here](https://developer.apple.com/documentation/endpointsecurity/es_process_t/3334987-codesigning_flags), through the flags in the kernel headers [here](https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/osfmk/kern/cs_blobs.h).
Only a few flags that are understood and relevant for monitoring are supported - more can be added later if use cases arise. These are:
* `NOT_VALID`: Process is running or exited with [invalid code …

Add column to `es_process_events` for process codesigning flags

---

docs/wiki/deployment/dependency-security.md
mkdocs.yml

- Add the pages about the CVEs scan and dependency security
- Update the dependency security page to refer to the new system of tracking CVEs and scanning them.

docs: Update the list of pages

---

osquery/tables/networking/posix/dns_resolvers.cpp

Was [using this file as reference point](https://github.com/osquery/osquery/issues/7808) and observed apparent typo

dns_resolvers: fix typo in the name when spawning in namespace

---

ASSURANCE.md

This is a follow-up to https://github.com/osquery/osquery/pull/7787 with more documentation changes describing how the project now handles third-party library security.

Docs: mention the recent adoption of automatic CVE scanning

---

libraries/third_party_libraries_manifest.json

Ignoring CVE-2016-4484 and CVE-2021-4122,
since they do not affect osquery.
Fixes #7842
Fixes #7843

cve: Ignore libcryptsetup cves

---

libraries/cmake/source/libarchive/CMakeLists.txt
libraries/cmake/source/libarchive/README.md
libraries/cmake/source/libarchive/config/linux/aarch64/config.h
libraries/cmake/source/libarchive/config/linux/x86_64/config.h
libraries/cmake/source/libarchive/config/macos/aarch64/config.h
libraries/cmake/source/libarchive/config/macos/x86_64/config.h
libraries/cmake/source/libarchive/config/windows/x86_64/config.h
libraries/third_party_libraries_manifest.json

This also resolves CVE-2022-36227
Fixes #7841

libs: Update libarchive to 3.6.2

---

.gitignore

The compile_commands.json file is normally generated in the build folder, but there are tools like `vim` with plugins which automatically picks it up to give completion/intellisense if it's in the source folder.
The pyrightconfig.json is used to configure one of the components of the Python extension in Visual Studio Code; one useful thing to do is to tell it to ignore the libraries folder:
```
{
"exclude": ["**/libraries/**"]
}
```
otherwise it easily breaks due to the amount of code and different projects causing type checking, completion etc to not work for python files in osquery.

git: Ignore compile_commands.json and pyrightconfig.json

---

.github/workflows/hosted_runners.yml

Set the concurrency group for the workflow to either the PR number or the run id so that in the first case, if there are multiple updates to a PR that start multiple build jobs, only the last job will run and the previous ones will be canceled, to avoid starving the CI.
The fallback is for a build job not started from a PR, the run id is unique, so no canceling will happen.

ci: Automatically cancel old PR jobs

---

tools/tests/test_osqueryd.py

The test is supposed to verify the correct and clean shutdown when osquery receives a SIGINT.
The clean shutdown though, is only possible when the signal handler is installed, which might not happen immediately,
so there might be a window where if the test sends a SIGINT it will immediately interrupt the osquery process with exit code -2, due to the signal, making the test fail.
Originally the test was waiting for the pidfile to be created by the process, because at that point the signal handler was installed. But a regression was introduced and the pidfile path was created by the test itself before starting osquery,
causing the wait to not work properly.
This restores that logic by removing the creation of that path in the test.
We also ensure that there's no pidfile created by another …

test: Fix flaky test_daemon_sigint

---

osquery/core/init.cpp
osquery/registry/registry_factory.cpp
osquery/sql/tests/virtual_table.cpp
osquery/sql/virtual_table.cpp
osquery/tables/events/tests/file_events_tests.cpp
tools/tests/test_base.py

Change the table_exceptions and registry_exceptions flags
to ignore_table_exceptions and ignore_registry_exceptions,
also changing their default to false.
This way all the tests on tables will fail if an exception
is thrown during the querying of a table.
They will be set to true though, when the Initializer
is used to start an osquery or extension instance.
To further expand the reason for the change, catching those exceptions has hidden the issue fixed in PR https://github.com/osquery/osquery/pull/7620 because the tests were not actually failing, although in the CI log one could see that some of the tables were throwing the exceptions.
Changing them to true makes them enabled by default and impossible to forget to enable in a test; for production (osqueryd instance or extensions), we …

Do not catch table or registry exceptions when running tests

---

libraries/third_party_libraries_manifest.json

Ignore CVE-2018-0495, CVE-2018-6829, CVE-2021-33560, and CVE-2021-40528, since they do not affect osquery.
Fixes #7845
Fixes #7846 
Fixes #7847 
Fixes #7848

cve: Ignore libgcrypt cves

---

.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml

- actions/cache@v2 is getting deprecated, update to v3
- Drop again the deprecated usage of set-output in favor of the environment variable GITHUB_OUTPUT.
- Update the aws-actions/configure-aws-credentials@v1 to v1-node16, to resolve the deprecations warnings of node 12.
Here the notice for the `configure-aws-credential` action: https://github.com/aws-actions/configure-aws-credentials#notice-node12-deprecation-warning

ci: Update some actions to remove deprecation warnings

---

osquery/tables/applications/posix/docker.cpp
specs/posix/docker_container_stats.table
tests/integration/tables/docker_container_stats.cpp

The docker container memory usage isn't in sync with docker cli which subtracts the cached memory from the used memory. I added a new column to docker_container_stats to get the cached container memory to get more detailed information about container memory usage.

Update `docker_container_stats` table to include `cached_memory` column

---

libraries/cmake/README.md
libraries/cmake/source/libdpkg/README.md
libraries/cmake/source/thrift/README.md
libraries/cmake/source/thrift/config/linux/x86_64/thrift/config.h
libraries/cmake/source/thrift/config/macos/aarch64/thrift/config.h
libraries/cmake/source/thrift/config/macos/x86_64/thrift/config.h
libraries/cmake/source/thrift/config/windows/x86_64/thrift/config.h
libraries/third_party_libraries_manifest.json

Updates the git submodule for the Thrift third-party dependency, currently at 0.15.0, to version 0.17.0.
It also updates the CMake config for each relevant platform:
This is related to #7104 and although we are not responding to any known vulnerabilities in _Apache_ Thrift 0.15.0, it may includes fixes to vulnerabilities known to be in _Facebook_ Thrift, if any.

libs: update Thrift to 0.17

---

.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml
.gitmodules
CMakeLists.txt
libraries/cmake/source/popt/CMakeLists.txt
libraries/cmake/source/popt/README.md
libraries/cmake/source/popt/config/linux/aarch64/config.h
libraries/cmake/source/popt/config/linux/x86_64/config.h
libraries/third_party_libraries_manifest.json
osquery/tables/system/CMakeLists.txt

- Change the submodule url to the same used for rpm
- Update popt to the same date as the release of the latest version of rpm/librpm
- Remove macOS configs and unnecessary references
- Correctly generate config for both Linux archs and correct the README
This is mostly needed to properly update librpm later.

libs: Update popt to 1.19

---

osquery/tables/system/linux/systemd_units.cpp
specs/linux/systemd_units.table

This adds a new column to the `systemd_units` table to determine if a systemd service is in one of several enabled states, such as `enabled` or `masked`. There is currently no way of determining service is enabled.
This change may be slower than a more complicated change that makes only 2 dbus requests then joins them in osquery, but that would substantially increase code complexity.
Fleet has tracked this in [fleetdm/fleet#8976](https://github.com/fleetdm/fleet/issues/8976)

systemd_units: Add new unit_file_state column

---

osquery/distributed/CMakeLists.txt
osquery/distributed/distributed.cpp
osquery/distributed/distributed.h
plugins/distributed/CMakeLists.txt

This creates a new top-level `stats` key when writing a distributed query response. This includes the data included in `QueryPerformance` class, indexed by the query ID included in the read endpoint from the server.
This issue is tracked in #7867

Record and send statistics for distributed queries

---

osquery/sql/sqlite_util.cpp
osquery/sql/virtual_table.cpp

Fixes #7400 - When we call xBestIndex set the Affected tables and clear the cached data when using the QueryPlanner class.

Clear cached constraints and columns in xBestIndex

---

docs/wiki/deployment/aws-logging.md

👋  Hello!
Just a quick docs update to the example for AWS logging plugins. I've removed the `logger_plugin` from config and added clarifications that it must be set via a CLI flag (with a link to those docs).

docs: clarify that logger_plugin is set from CLI

---

osquery/tables/system/darwin/xprotect.cpp

This makes the `min_version` column consistent across the various types of entries in the `XProtect.meta.plist` file. Returning `any` was misleading as these values are actually empty in the file.
See discussion in https://github.com/fleetdm/fleet/issues/9545#issuecomment-1411214980.

Leave min_version empty in xprotect_meta when not specified

---

osquery/tables/yara/CMakeLists.txt
osquery/tables/yara/yara.cpp
specs/yara/yara.table

Resolves https://github.com/osquery/osquery/issues/7808
[This is almost blindly based on this previous PR.](https://github.com/osquery/osquery/pull/7132/files#diff-e175bdb0223c28709c16e04c1534b0c85c5ebeba1f5dc1ba9dafc9f9d81d3c07)
I don't see a good way to add automated testing for this, but am happy to implement inline with any pattern that can be pointed to. [I did test this code manually and demonstrate that here](https://www.youtube.com/watch?app=desktop&v=RpUf5LtHsvM). I expect the artifact built on the pipeline could be pulled down and substituted in my [test script which is available here.](https://github.com/NickBorgersOnLowSecurityNode/inspect-container-dependencies/blob/main/osquery_on_host.new_version.sh)

Add `pid_with_namespace` for `yara` table

---

libraries/cmake/source/libmagic/CMakeLists.txt

Only rename strlcat and strlcpy on Linux,
otherwise the library will try to use the renamed functions which are not provided by the library anymore.
The compilation did not fail on the CI due to linker magic that drops functions that call those strlcat and strlcpy functions. When compiling with ASAN enabled though the callers are not dropped anymore, causing a linking error.

libs: Fix libmagic build on macOS

---

libraries/cmake/source/dbus/README.md
libraries/cmake/source/dbus/config/aarch64/config.h
libraries/cmake/source/dbus/config/x86_64/config.h

dbus needs to access some paths on the system
to be able to communicate with systemd.
The config file was incorrectly configured.

libs: Fix system paths used by dbus

---

tools/analysis/profile.py
tools/tests/utils.py

This adds some diagnostic log and error messages to profile.py so that people can debug why profile.py is quietly exiting. In my case, it was because I was passing an osquery pack file to `--config`. 
Invalid config:
```
$ ./profile.py --shell /usr/bin/osqueryi --config pack.conf
```
Notice the lack of any output or error code.
Valid config:
```
$ ./profile.py --shell /usr/bin/osqueryi --config osquery.conf
Profiling query: SELECT hostname, cpu_brand, physical_memory FROM system_info;
```
Invalid config:
```
$ ./profile.py --shell /usr/bin/osqueryi --config pack.conf                       pack.conf parsed as JSON, but does not contain a 'schedule' or 'packs' stanza. Is it really an osquery configuration file?
```
Valid config:
```
$ ./profile.py --shell /usr/bin/osqueryi --config …
```

profile.py: Log # of queries loaded and raise an error if 0 are loaded

---

tools/analysis/profile.py
tools/tests/utils.py

This adds a `--pack` flag so that `analysis.py` can pull queries from an osquery pack file.
For example:
```shell
./profile.py --shell /usr/bin/osqueryi --pack pack.conf
Profiling query: SELECT file.path, file.type, file.size, file.mtime, file.uid, file.ctime, file.gid, hash.sha256, magic.data FROM file LEFT JOIN hash ON file.path = hash.path LEFT JOIN users u ON file.uid = u.uid LEFT JOIN magic ON file.path = magic.path WHERE ( file.directory LIKE '/Users/%/Downloads/%' OR file.directory LIKE '/home/%/%' OR file.directory LIKE '/home/%/' OR file.directory LIKE '/home/%/.%' OR file.directory LIKE '/home/%/Downloads/%' OR file.directory LIKE '/tmp/%' OR file.directory LIKE '/tmp/' OR file.directory LIKE '/Users/%/%' OR file.directory LIKE '/Users/%/' OR file.directory LIKE '/Users/%/.%' OR …
```

analysis.py: Add --pack flag to load queries from a pack file

---

osquery/tables/applications/chrome/utils.cpp

Adds additional Chrome and Brave extensions to list of builtin extensions, which seem to occasionally generate warnings that the manifest.json can't be read:
* [identity_scope_approval_dialog](https://github.com/chromium/chromium/blob/main/chrome/browser/resources/identity_scope_approval_dialog/manifest.json)
* [brave_extension](https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/manifest.json)
* brave_rewards (removed in this [Brave PR](https://github.com/brave/brave-core/pull/15342), but still nice to exclude for older versions)
* [brave_webtorrent](https://github.com/brave/brave-core/blob/master/components/brave_webtorrent/extension/manifest.json)
Not sure how to reliably trigger the error to do testing, but it looks like a safe change …

Silence warnings for more builtin Chrome and Brave extensions

---

.gitignore
.gitmodules
cmake/options.cmake
libraries/cmake/source/boost/CMakeLists.txt
libraries/cmake/source/modules/Findboost.cmake
libraries/third_party_libraries_manifest.json
osquery/core/CMakeLists.txt
osquery/core/init.cpp
osquery/events/linux/bpf/bpfeventpublisher.cpp
osquery/experimental/experiments/CMakeLists.txt
osquery/experimental/experiments/linuxevents/CMakeLists.txt
osquery/experimental/experiments/linuxevents/README.md
osquery/experimental/experiments/linuxevents/include/osquery/experiments/linuxevents.h
osquery/experimental/experiments/linuxevents/libraries/CMakeLists.txt
osquery/experimental/experiments/linuxevents/libraries/linuxevents/CMakeLists.txt
osquery/experimental/experiments/linuxevents/src/bpfprocesseventstable.cpp
osquery/experimental/experiments/linuxevents/src/bpfprocesseventstable.h
osquery/experimental/experiments/linuxevents/src/linuxevents.cpp
osquery/experimental/experiments/linuxevents/src/linuxeventsservice.cpp
osquery/experimental/experiments/linuxevents/src/linuxeventsservice.h
osquery/experimental/experiments/loader/CMakeLists.txt
osquery/experimental/experiments/loader/include/osquery/experiments/loader.h
osquery/experimental/experiments/loader/src/loader.cpp
tools/ci/scripts/cve/osquery/manifest_api.py
tools/tests/CMakeLists.txt

This PR adds support for extra features named `experiments` that are off by default but can be enabled using the `--experiment_list=experiment1,experiment2` flag. The idea is that enabling one or more experiments will void your warranty, causing that specific instance to no longer be officially supported.
An initial experiment has been included, called `linuxevents`. This adds a new `bpf_process_events_v2` table which is a better, container-aware version of the built-in `bpf_process_events`.
Key features:
1. The table now traces internal kernel structures (i.e. task_struct) to capture all the data. We no longer need to trace system calls and keep track of file descriptors
2. Significantly lower memory and CPU usage
3. Container aware: contains both the container ID and container backend …

experiments: Implement a new bpf_process_events_v2 table

---

osquery/tables/system/windows/system_info.cpp

In debug mode an **osquery::Expected** class object will asserted in destructor, if it's not checked for results.
When we check multiple **osquery::Expected** objects in single **if**, in case of first one has error, the second one will not be checked and **osquery::Expected** object destructor will assert.
So, every **osquery::Expected** must be checked explicitly

Fix assert fail for unverified WMI request result

---

osquery/core/query.cpp
osquery/core/query.h
osquery/dispatcher/scheduler.cpp
osquery/logger/tests/logger.cpp
osquery/sql/tests/sql_test_utils.cpp
plugins/config/parsers/tests/decorators_tests.cpp
plugins/logger/tests/filesystem_logger_tests.cpp

This change adds logging of an empty result set in batch format for an initial run (or new epoch) if there are no results. Previously the no results case was ignored and not logged even on an initial run / new epoch.
This makes the initial run / new epoch for differential queries more consistent with the snapshot query behavior, and it ensures there is always a "counter=0" log entry for each epoch in batch format. It makes it possible for users to differentiate between a query not running and the query not producing any results.
More context is in https://github.com/osquery/osquery/issues/7799
This should not lead to significantly more log events than before, as it is adding at most one log per epoch change.
There's a risk that implementations won't handle having both "added" and …

Support logging empty result set in batch format for initial runs

---

.github/workflows/hosted_runners.yml

Windows 32bit is not sold on new PCs since 2020, and also its support ended the same year too.
osquery never released official builds of Windows 32bit, its support was always best effort.
Since its support is causing some delays with updating openssl, and there might be other similar issues in the future, we want to reduce our maintenance burden.

ci: Remove Windows 32bit build

---

libraries/cmake/formula/openssl/CMakeLists.txt
libraries/third_party_libraries_manifest.json

Resolves CVE-2023-0286, CVE-2022-4304,
CVE-2023-0215, CVE-2022-4450
Fixes #7936

cve: Update openssl to 1.1.1t

---

.github/workflows/self_hosted_runners.yml

Due to some new libraries being added to the build, we hit the disk space limit on the aarch64 runner; this adds a workaround to cleanup some build artifacts that are not needed after a certain point, which helps give some breathing space.
You can see a job failing here: https://github.com/osquery/osquery/actions/runs/4183644659/jobs/7248309929
And a build where I was testing this workaround: https://github.com/osquery/osquery/actions/runs/4185682265
Adding 30MB of a single static library caused ~4GB of additional disk space taken by tests.
See this comment for further explanation: https://github.com/osquery/osquery/issues/6397#issuecomment-1431724082

ci: Workaround in the aarch64 runner to avoid out of space

---

cmake/flags.cmake
libraries/cmake/source/libmagic/CMakeLists.txt
osquery/events/darwin/iokit.cpp
osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/cpu_info.cpp
osquery/tables/system/darwin/smbios_tables.cpp
osquery/tables/system/darwin/smbios_utils.h
osquery/tables/system/linux/cpu_info.cpp
osquery/tables/system/posix/smbios_utils.cpp
osquery/tables/system/smbios_utils.h
osquery/utils/CMakeLists.txt
osquery/utils/conversions/darwin/iokit.cpp
osquery/utils/conversions/darwin/iokit.h
osquery/utils/darwin/iokit_helpers.h
specs/CMakeLists.txt
specs/cpu_info.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/cpu_info.cpp

- Add two new columns "number_of_efficiency_cores",
and "number_of_performance_cores".
This is Apple Silicon only for now,
but in the future it could be extracted for Linux x86
and Windows x86 with newer Intel CPUs.
- Do some minor cleanups to reuse common SMBIOS utils.
- Enable the cpu_info integration test for Linux and macOS

`cpu_info`: Port the table to macOS x86 and Apple Silicon

---

docs/wiki/deployment/remote.md
docs/wiki/development/unit-tests.md
osquery/distributed/distributed.cpp
osquery/distributed/distributed.h
osquery/distributed/tests/distributed_tests.cpp

This PR fixes and attempts to document the discovery queries behavior in distributed queries.
The main change:
If a distributed query does not have its corresponding discovery query, then it will always be executed.
(Currently on `master` this is not the case, if there's at least one discovery query then all those distributed queries that do not have one defined are not executed at all.)
This PR also fixes #5260 and #7793 and adds some tests to `Distributed.acceptWork`.

Fix and document discovery queries behavior on distributed queries and add tests

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/linux/kernel_keys.cpp
specs/CMakeLists.txt
specs/linux/kernel_keys.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/kernel_keys.cpp

This PR adds a new table called kernel_keys for Linux. This table exposes the content of the file /proc/keys,
this file exposes a list of the keys for which the reading thread has view permission, providing various information about each key. 
Fixes #7765

Add a new table `kernel keys` to the Linux platform

---

docs/wiki/deployment/logging.md
osquery/core/query.cpp
osquery/core/query.h
osquery/core/tests/query_tests.cpp

This change sets the counter to zero only when all records are being logged as part of an initial run or new epoch. 
Previously in some cases, the counter would be zero for a differential log (specifically events tables or if the query changed). For these cases, the counter is now reset to 1 instead. This change also does a small refactor to ensure the epoch in the database is updated for events tables, so that it will be set accurately if the same query is later changed to run over a non-evented table.
More context and motivation for this change is in https://github.com/osquery/osquery/issues/7799

Set counter consistently so zero always indicates all records

---

.github/workflows/self_hosted_runners.yml
osquery/core/CMakeLists.txt
osquery/core/tests/CMakeLists.txt
osquery/events/CMakeLists.txt
osquery/events/tests/CMakeLists.txt

#6397 has been more and more of an issue, and is now blocking the 5.8 release. Talking in office hours today, we decided to try collapsing some of the test binaries. It's imperfect, but we think it's the quickest way to get 5.8 out. This is a first pass. This may be reverted later.
This branch is on the main osquery repo, because we need to hit the self hosted runner.

Try to free some disk space on the arm64 runners

---

osquery/tables/system/darwin/managed_policies.cpp
tests/integration/tables/managed_policies.cpp

Currently the username field in managed_policy table is always set to "." for a user policy. This changes the field to instead be the actual username (or empty if it is a system policy), which is the expected behavior. 
The issue is that directory paths from `listDirectoriesInDirectory` end in "/"  (see [here](https://github.com/osquery/osquery/blob/cb65b6e9d6b2ca15278da8782fcad8507a16246d/osquery/filesystem/filesystem.cpp#L364)), which causes their filename and stem to be "." due to the Boost behavior described [here](https://www.boost.org/doc/libs/1_68_0/libs/filesystem/doc/reference.html#path-filename)
Tested manually with a managed machine using osqueryi. Also uncommented the table test, though it doesn't actually test anything on a non-managed machine (ie in CI) because the plist …

Fix username field in managed_policy table

---

osquery/dispatcher/scheduler.cpp

The PR https://github.com/osquery/osquery/pull/7803 intended to add logging of an empty result set in batch format for an initial run (or new epoch) if there are no results. However, it instead lead to logging an empty result set every time the query executes without results (not just on a new epoch) -- see report in [Slack](https://osquery.slack.com/archives/C08VA3XQU/p1678855376559829). 
This is because the `item.counter` field is only set to its correct value when there are results to report and otherwise defaults to zero in the scheduler. The easiest fix seems like making the default `item.counter` field a non-zero value instead. An alternative idea would be to always set `item.counter` correctly in the query code (or else to go back to the old behavior of ignoring all empty runs). …

Fix empty batch result set reporting

---

tests/integration/tables/CMakeLists.txt

cpu_info, secureboot and memory_devices are tables that on Linux require root to work.
root tests are only built if OSQUERY_BUILD_ROOT_TESTS is enabled, those table tests should be no exception.

tests: Do not always build root tests on Linux

---

osquery/core/tests/CMakeLists.txt

The osquery_main target should never be linked by tests.
Not sure why the CI is happily working, but when executing the `osquery_core_tests_mergedtests_test` it starts an osquery shell, not the test.
The issue in the other test cannot be seen locally, but it's equally incorrect.

tests: Fix some tests becoming osquery shells

---

tests/integration/tables/secureboot.cpp

For instance if the machine is not using UEFI,
or there is any error, the table won't return a row.

test: Do not always expect a row from the secureboot table

---

osquery/hashing/CMakeLists.txt
osquery/hashing/tests/hashing.cpp

Hi!
While walking across the osquery project I tried to change some code in the hashing component.
But I believe that it would be better to land some tests first to be sure that I don't broke anything later.
So this PR contains only a few basic tests for hashing classes and functions.
PTAL.

Add few unit tests for the hashing component

---

.gitmodules
CMakeLists.txt
libraries/cmake/source/librdkafka/CMakeLists.txt
libraries/cmake/source/lz4/CMakeLists.txt
libraries/cmake/source/lz4/README.md
libraries/cmake/source/modules/Findlz4.cmake
libraries/third_party_libraries_manifest.json

This helps to better track CVEs, since rdkafka embeds LZ4 and doesn't have any CPE.

libs: Bring out LZ4 from rdkafka and update it to v1.9.4

---

osquery/core/windows/wmi.cpp

It seems to me that the COM objects and strings from PR #7963 should be released.
@marcosd4h PTAL

Release objects and free memory obtained from COM

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/tests/filesystem.cpp
osquery/tables/system/python_packages.cpp

This relates to #[6679 ](https://github.com/osquery/osquery/issues/6679) and Fleet PR #[8243](https://github.com/fleetdm/fleet/issues/8243)
There was a 10x performance increase when using this logic (see osqueryi_custom.exe results below)
```
PS C:\tools\osquery> Measure-Command { .\osqueryi_5.8.2.exe "select COUNT(*) from python_packages;" | Out-Default }
+----------+
| COUNT(*) |
+----------+
| 228      |
+----------+
TotalSeconds      : 19.1131021
TotalMilliseconds : 19113.1021
PS C:\tools\osquery> Measure-Command { .\osqueryi_custom.exe "select COUNT(*) from python_packages;" | Out-Default }
+----------+
| COUNT(*) |
+----------+
| 228      |
+----------+
TotalSeconds      : 1.907992
TotalMilliseconds : 1907.992
```

Improving `listDirectoriesInDirectory` by using `std::fs`

---

osquery/tables/system/linux/system_info.cpp
osquery/tables/system/windows/system_info.cpp
specs/system_info.table
tests/integration/tables/system_info.cpp

Add number of sockets to `system_info`

---

.github/workflows/self_hosted_runners.yml

Update the workflow to point to the action in the osquery repo.
Also update which version of the action we are using.
Fixes #8034
Second tentative, since I messed up the merge target.

Fix the aarch64 workflow

---

specs/darwin/disk_events.table
specs/darwin/es_process_events.table
specs/darwin/es_process_file_events.table
specs/darwin/user_interaction_events.table
specs/linux/apparmor_events.table
specs/linux/bpf_process_events.table
specs/linux/bpf_socket_events.table
specs/linux/process_file_events.table
specs/linux/seccomp_events.table
specs/linux/selinux_events.table
specs/linux/syslog_events.table
specs/posix/file_events.table
specs/posix/hardware_events.table
specs/posix/process_events.table
specs/posix/socket_events.table
specs/posix/user_events.table
specs/windows/ntfs_journal_events.table
specs/windows/powershell_events.table
specs/windows/process_etw_events.table
specs/windows/windows_events.table

Osquery optimizes event tables in scheduled queries to only return data since the last time the scheduled query was run (unless `--events_optimize=false` is set). Sometimes this behavior is not desirable if the query is for a specifically set time range, so there is [code](https://github.com/osquery/osquery/blob/90648c36aa74e18be02dc4ad5ffb8ea7598c013c/osquery/events/eventsubscriberplugin.cpp#L297) to turn off the optimization if a constraint on the `time` column is present. However this does not work today because the constraint is not available to the table implementation unless it is marked "additional" in the schema.
This change adds `additional=True` to `time` columns in event tables, disabling event optimization when a time constraint is present in a scheduled query.
If the old …

Mark time column as "additional" for event tables

---

external/CMakeLists.txt
external/examples/string_batch/CMakeLists.txt
external/examples/string_batch/main.cpp
osquery/core/plugins/logger.cpp
osquery/core/plugins/logger.h

This PR adds support for a batched version of the `string` logger plugin request

logger: Add new `string_batch` request type to compliment existing `string` type

---

.github/ISSUE_TEMPLATE/Question.md
CONTRIBUTING.md
README.md
SUPPORT.md
docs/wiki/index.md
tools/deployment/make_windows_package.ps1

The website was updated, we miss links here in the osquery repo.
Fixes #8047

Update expired Slack invite

---

osquery/tables/system/darwin/crashes.cpp

Closes #6776 by checking the `Retired` subdirectories, which is where crash reports now get moved soon after creation, but before deletion. More importantly, this PR adds parsing for the JSON-based `.ips` format that Apple switched to for crash logs in macOS 12. Actually parsing the registers and thread stack fields is now a bit complex, but shouldn't be any more fragile than the regex-based parsing of the legacy (unstructured log) format. I have searched for any API for accessing `.ips` crash logs and couldn't find one from Apple, although there is a BSD licensed CLI tool here (I didn't study it). https://github.com/packagesdev/ips2crash
Questions for reviewers:
1. what is `fuzz_paths` in the table spec? Should it be updated to include the two new subdirectories that are enumerated by …

Restore functionality of `crashes` table on macOS 12 and newer

---

osquery/filesystem/posix/xattrs.cpp
osquery/filesystem/posix/xattrs.h
osquery/filesystem/tests/posix/xattrs.cpp
osquery/tables/system/darwin/extended_attributes.cpp
osquery/tables/system/linux/extended_attributes.cpp
osquery/tables/system/tests/darwin/extended_attributes_tests.cpp
osquery/utils/base64.cpp
osquery/utils/base64.h
osquery/utils/chars.cpp
osquery/utils/chars.h

- Fix a bug in the macOS implementation where a race condition could cause a read out of bound when the read file is deleted. Use the xattr variant of APIs which uses a fd, so that the file remains valid even if deleted, and also check error codes.
- Improve error reporting for the extended_attributes implementation on Linux and macOS
- Minor improvements to prevent unnecessary string copies by using string_view

Improve extended_attributes implementation for Linux and macOS

---

osquery/tables/applications/darwin/browser_plugins.cpp
specs/darwin/safari_extensions.table

This relates to #6498  and Fleet's #[6950](https://github.com/fleetdm/fleet/issues/6950)
Fixes: #6498

Update `safari_extensions` to handle the current app extensions pattern

---

osquery/tables/system/darwin/homebrew_packages.cpp

Fixes a bug introduced in osquery 5.9.0 where the version column in `homebrew_packages` was the name of the package instead of its version. 
Tested manually:
```
osquery> select * from homebrew_packages order by name;
+--------------------------+-----------------------------------------------+----------------+
| name                     | path                                          | version        |
+--------------------------+-----------------------------------------------+----------------+
| aom                      | /opt/homebrew/Cellar/aom                      | 3.6.0          |
| aribb24                  | /opt/homebrew/Cellar/aribb24                  | 1.0.4          |
| autoconf                 | /opt/homebrew/Cellar/autoconf                 | 2.71           |
| awscli …
```

Fix version column in homebrew_packages

---

libraries/third_party_libraries_manifest.json

Fixes: #8049
As discussed in offices today (2023-06-20) we do not think osquery is vulnerable to this. From the description:
> Libarchive through 3.6.2 can cause directories to have world-writable permissions. The umask() call inside archive_write_disk_posix.c changes the umask of the whole process for a very short period of time; a race condition with another thread can lead to a permanent umask 0 setting. Such a race condition could lead to implicit directory creation with permissions 0777 (without the sticky bit), which means that any low-privileged local user can delete and rename files inside those directories.
Osquery does not unpack files, so we do not believe this effects us.
Furthermore, there is not yet an upstream fix, and this appears limited to multithreaded environments.
See …

Ignore CVE-2023-30571

---

docs/wiki/installation/cli-flags.md
osquery/core/tests/watcher_tests.cpp
osquery/core/watcher.cpp
osquery/sql/virtual_table.cpp

See #8069.
With the changes in this PR, the following is logged every check interval (3s) for every process being watched:
```
[...]
I0623 17:54:02.500684 81305600 watcher.cpp:537] pid: 93084, cpu: 97ms/1200ms, memory: 0.00MB/200MB
I0623 17:54:02.500970 81305600 watcher.cpp:537] pid: 93083, cpu: 0ms/1200ms, memory: 0.03MB/200MB
I0623 17:54:05.503715 81305600 watcher.cpp:537] pid: 93084, cpu: 1ms/1200ms, memory: 0.02MB/200MB
I0623 17:54:05.504016 81305600 watcher.cpp:537] pid: 93083, cpu: 2ms/1200ms, memory: 0.04MB/200MB
[...]
```
---
The following is a log from `master` when the CPU limit is exceeded:
```
2668:W0623 15:27:06.032490 221732864 watcher.cpp:415] osqueryd worker (72457) stopping:
Maximum sustainable CPU utilization limit: 12
```
The following is a log with this PR when the CPU …

Add `--enable_watchdog_logging` flag and improve error messages

---

osquery/events/tests/linux/inotify_tests.cpp
plugins/database/tests/rocksdb.cpp

inotify:
```
62: =================================================================
62: ==440195==ERROR: LeakSanitizer: detected memory leaks
62: 
62: Direct leak of 139264 byte(s) in 1 object(s) allocated from:
62:     #0 0x55efb459af1d in malloc /opt/osquery-toolchain/llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:145:3
62:     #1 0x55efb46bfccd in osquery::INotifyEventPublisher::setUp() /home/smjert/Development/osquery/src/osquery/events/linux/inotify.cpp:70:21
62:     #2 0x55efb4758727 in osquery::EventFactory::registerEventPublisher(std::__1::shared_ptr<osquery::Plugin> const&) /home/smjert/Development/osquery/src/osquery/events/eventfactory.cpp:152:29
62:     #3 0x55efb497bb0d in osquery::INotifyTests_test_inotify_embedded_wildcards_Test::TestBody() …
```

test: Fix leaks in inotify and rocksdb tests

---

osquery/events/windows/ntfs_event_publisher.cpp
osquery/filesystem/windows/fileops.cpp
osquery/utils/conversions/windows/tests/strings.cpp

The UTF16 and UTF8 conversion APIs already accept `std::string` and `std::wstring` correctly, without the need to convert them to a wchar_t or char pointer, which is then converted back to the original type, but with potentially allocating other memory.

improvement: Avoid unnecessary string conversions

---

osquery/filesystem/posix/fileops.cpp

Checking if a file exists before opening it is a pessimization and susceptible to race conditions.
On posix it's enough to open without O_CREAT and if the file doesn't exists the open will return -1.

core: Avoid checking if a file exists before opening

---

docs/wiki/deployment/configuration.md

Documentation update - Updated the example config and output values in  the ` Automatic Table Construction` section of the configuration documentation to reflect the current TCC database schema in macOS  Ventura.

Update Automatic Table Construction example

---

osquery/core/tables.h
osquery/tables/events/linux/bpf_process_events.cpp
osquery/tables/events/linux/bpf_socket_events.cpp
osquery/tables/networking/linux/iptables.cpp
osquery/tables/system/darwin/authorizations.mm
osquery/tables/system/darwin/battery.mm
osquery/tables/system/darwin/connected_displays.mm
osquery/tables/system/darwin/cpu_info.cpp
osquery/tables/system/darwin/disk_encryption.mm
osquery/tables/system/darwin/kernel_extensions.cpp
osquery/tables/system/darwin/mounts.cpp
osquery/tables/system/darwin/os_version.mm
osquery/tables/system/darwin/user_groups.mm
osquery/tables/system/linux/extended_attributes.cpp
osquery/tables/system/linux/groups.cpp
osquery/tables/system/linux/os_version.cpp
osquery/tables/system/linux/rpm_packages.cpp
osquery/tables/system/linux/shadow.cpp
osquery/tables/system/linux/systemd_units.cpp
osquery/tables/system/linux/users.cpp
osquery/tables/system/posix/last.cpp
osquery/tables/system/posix/logged_in_users.cpp

Don't keep a macro which on Windows cannot be used due to collisions.
Use only one version for clarity.

cleanup: Substitute the TEXT macro with SQL_TEXT in table code

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/filesystem.h
osquery/tables/applications/browser_firefox.cpp
osquery/utils/json/json.cpp
osquery/utils/json/json.h

- Remove usages of boost::ptree to parse JSON, use rapidjson instead
- Don't block when attempting to read a file

firefox_addons: Use rapidjson to parse and don't block on read

---

osquery/filesystem/fileops.h
osquery/filesystem/filesystem.cpp
osquery/filesystem/filesystem.h
osquery/filesystem/posix/fileops.cpp
osquery/filesystem/windows/fileops.cpp
osquery/hashing/hashing.cpp
osquery/tables/applications/posix/carbon_black.cpp
osquery/tables/networking/etc_hosts.cpp
osquery/tables/system/darwin/packages.mm
osquery/tables/system/linux/apt_sources.cpp
osquery/tables/system/linux/memory_info.cpp
osquery/tables/system/posix/authorized_keys.cpp
osquery/tables/system/posix/crontab.cpp
osquery/tables/system/posix/known_hosts.cpp
osquery/tables/system/posix/shell_history.cpp
osquery/tables/system/posix/sudoers.cpp
osquery/tables/system/ssh_configs.cpp
osquery/tables/system/ssh_keys.cpp

The function doesn't do much especially due to relatime or noatime on Linux.
Furthermore even if it did something, it tampers with times and does not prevent an application to read the updated atime.

cleanup: Remove forensicReadFile

---

docs/wiki/installation/cli-flags.md
osquery/tables/cloud/aws/ec2_instance_tags.cpp
osquery/utils/aws/CMakeLists.txt
osquery/utils/aws/aws_util.cpp
osquery/utils/aws/aws_util.h

Add the "aws_enforce_fips" to force that all current services using AWS (Kinesis, Firehose, EC2, STS),
must use FIPS endpoints, or fail to.

aws: Add an option to enforce FIPS endpoints

---

osquery/tables/system/darwin/sip_config.cpp

Add the following config flags to the darwin `sip_config` table:
* `allow_any_recovery_os`
* `allow_unapproved_kexts`
* `allow_executable_policy_override`
* `allow_unauthenticated_root`

Add newest SIP config flags

---

specs/darwin/connected_displays.table

This PR is related to an already-closed issue: #8106.
Following @directionless's advice, this is a small change to make the `serial_number` column in the darwin `connected_displays` table indicate in the description that a serial number may not be unique.
More details as to how/why this can happen in #8106.

Update the description of `serial_number` in `connected_displays`

---

docs/wiki/installation/cli-flags.md
osquery/core/watcher.cpp

Before this the CPU utilization limit, when on a physical host with virtual cores, was actually half of what was configured through the watchdog_utilization_limit flag,
because the code was counting only the physical cores, which normally are half of the virtual ones.
On VMs this could've been worse; now we use all the cores to calculate the limit.
Thanks to @lucasmrod for bringing this forward.
I've tested the change on:
1. macOS Apple Silicon host
2. macOS Apple Silicon virtualized with UTM
3. macOS x86 virtualized with VMware Fusion
4. Linux host
5. Linux x86 virtualized with KVM
6. Linux aarch64 virtualized with UTM
7. Windows virtualized with KVM
And the count of cores was always correct.

watchdog: Use virtual cores to calculate CPU utilization limit

---

osquery/events/darwin/endpointsecurity.h
osquery/events/darwin/endpointsecurity_fim.cpp
osquery/events/darwin/es_utils.cpp
osquery/tables/events/darwin/es_process_file_events.cpp

Tested on: 
* macOS 11 (Big Sur)
* macOS 12 (Monterey)
* macOS 13 (Ventura)
Test `osquery.conf`:
```json
{
"options": {
"disable_events": "false",
"verbose": "true",
"disable_events": "false",
"ephemeral": "true",
"disable_endpointsecurity": "false",
"disable_endpointsecurity_fim": "false",
"es_fim_enable_open_events": "true"
},
"schedule": {
"es_file_events": {
"query": "SELECT * FROM es_process_file_events;",
"interval": 20
}
},
"file_paths": {
"monitor": [
"/Users/*/.aws/*",
"/Users/*/.ssh/*",
"/Users/*/.config/gcloud/*",
"/Library/Keychains/*.keychain"
]
},
"exclude_paths": {
"monitor": [
"/Users/*/.ssh/id_ed25519.pub"
]
}
}
```

macos: `es_process_file_events` -- add support for open events, and for only triggering on `file_paths`

---

osquery/events/darwin/endpointsecurity_fim.cpp

A minor improvement I missed in the review, to avoid repetition and rescanning the JSON member we've already found.

Use JSON member iterator instead of rescanning

---

docs/wiki/deployment/file-carving.md
mkdocs.yml

Adds a new wiki page with minimum information about osquery's file carving tool.
Addresses the empty void of file carving documentation i.e. #7677 but not even close to enough detail to satisfy #3797.

docs: add very basic file carving documentation

---

docs/wiki/deployment/configuration.md
docs/wiki/installation/cli-flags.md
osquery/config/config.h
plugins/config/parsers/decorators.cpp
plugins/logger/buffered.cpp
plugins/logger/tests/buffered_tests.cpp

- Adds support to put the decorations at the root level of the status log JSON.
- Remove use of boost ptree to write status logs JSON and use rapidjson, making it consistent with results log. The "line", "unixTime" and "severity" will not be written as strings anymore, since they are numbers.
- Add tests to verify standard decorations and custom ones for status logs.

logs: Implement decorations_top_level flag for status logs

---

libraries/cmake/formula/openssl/CMakeLists.txt
libraries/third_party_libraries_manifest.json

Resolves CVE-2023-3817, CVE-2023-3446
and CVE-2023-2975
Fixes #8095 
Fixes #8097 
Fixes #8111

libs: Update openssl to 3.1.2

---

osquery/events/linux/auditdnetlink.cpp

Fixed the return value check from `<` to `<=` in places the documentation says:

Check audit return values with <=

---

.github/workflows/self_hosted_runners.yml

- Add a Release mode build which builds everything, runs tests, but does not create packages.
- Change the RelWithDebInfo build to not build and run tests, but create packages.
- Update the aws-actions/configure-aws-credentials version from v2 to v3, since v2 is being deprecated.
This makes the setup similar to what we do for x86_64, and since we are not building tests with debug symbols, it saves us quite some space.
You can see a build with this commit here: https://github.com/osquery/osquery/actions/runs/6089670131

ci: Increase aarch64 available space by splitting the build

---

libraries/cmake/formula/openssl/CMakeLists.txt

The build we do now still creates an ARM64 static library (otherwise the build would've broken), but how openssl was configured was wrong.
I could at least see a difference in the RC4_INT definition, which shouldn't affect correctness, just performance, but I haven't deeply checked what other issues were present with the incorrect configuration.

Fix openssl build arch for Windows ARM64

---

libraries/cmake/formula/openssl/CMakeLists.txt
libraries/third_party_libraries_manifest.json

Resolves CVE-2023-4807.
Fixes #8140

cve: Update openssl to 3.1.3

---

osquery/tables/system/windows/services.cpp

Fixes #6852
Windows "Services" can be created as drivers too. 
Currently osquery has no way to query info about File System Drivers or Kernel Drivers that are registered as "Services".
As the "drivers" table, rightly only includes Device Drivers. 
Local testing done:
```
C:\Source\osquery\build\osquery\RelWithDebInfo>osqueryi.exe "SELECT * FROM services WHERE name LIKE 'wof';"
+------+--------------------+-------------------------------------------+---------+-----+------------+-----------------+-------------------+------+-------------+-------------+--------------+
| name | service_type       | display_name                              | status  | pid | start_type | win32_exit_code | service_exit_code | path | module_path | description | user_account | …
```

Allow querying of kernel and filesystem drivers

---

osquery/events/eventsubscriberplugin.cpp
osquery/events/eventsubscriberplugin.h
osquery/events/tests/eventsubscriberplugin.cpp

Concurrent iteration and modification can cause crashes so ensure proper locking for all operations with event_index. 
#8076 
To reduce scope of locking EventSubscriberPlugin::generateRows() was slightly refactored to separate index operations from DB access.

Always lock event_index_mutex when accessing event_index map

---

libraries/cmake/source/libmagic/CMakeLists.txt
libraries/cmake/source/libmagic/README.md
libraries/cmake/source/libmagic/config/linux/aarch64/config.h
libraries/cmake/source/libmagic/config/linux/x86_64/config.h
libraries/cmake/source/libmagic/config/macos/aarch64/config.h
libraries/cmake/source/libmagic/config/macos/x86_64/config.h
libraries/cmake/source/libmagic/include/magic.h
libraries/third_party_libraries_manifest.json

Resolves CVE-2022-48554.
Fixes #8121

cve: Update libmagic to 5.45

---

osquery/tables/system/linux/block_devices.cpp
specs/posix/block_devices.table

This extends the work originally done in #7209 to the `block_devices` table. And relates to #8033
With it, I hope to fix an o(n^2) bug.
As the underlying code doesn't support this on darwin, I opted to flag the spec as `additional=True` and not `index=True`
(Thanks @uptycs-rmack for talking through this with me)

Add some indexing to `block_devices`

---

.github/workflows/hosted_runners.yml

Sometimes apt decides to fail the removal of the packages if one of them is missing.
Lets get a list of only the packages that are installed, and match on those, so that we only delete what we know it's present.
For instance here: https://github.com/osquery/osquery/actions/runs/6308677593/job/17127241840

ci: Remove flakyness when removing unused packages on Linux

---

osquery/sql/benchmarks/sql_benchmarks.cpp
osquery/sql/sqlite_util.cpp
osquery/sql/tests/virtual_table.cpp
osquery/sql/virtual_table.cpp
osquery/sql/virtual_table.h

Fixes: #7000 
Fixes: #5714
I noticed some of the named virtual tables don’t appear in the osquery instance. This can be seen by querying `sqlite_temp_master`.
Digging a lot, this is because we add `WITHOUT ROWID` to the column definitions when a table contains a column with either an index or additional flag set. This breaks parsing on the named virtual table create statements.
```
osquery> CREATE VIRTUAL TABLE test USING users() WITHOUT ROWID;
Error: near "WITHOUT": syntax error
osquery> CREATE VIRTUAL TABLE test USING users();
osquery> SELECT uid FROM test LIMIT 1;
+-----+
| uid |
+-----+
| 278 |
+-----+
```
This has been true since we added support for [sqlite 3.14.0](https://github.com/osquery/osquery/commit/763f4e94372c768e3c8f9f235ac5ce7370d2a2c6#diff-496b07a6ace3d0702ddd348f9b0b4fc3 …

Fix named virtual table create statement

---

osquery/tables/cloud/ycloud/ycloud_instance_metadata.cpp
osquery/utils/ycloud/tests/ycloud.cpp
osquery/utils/ycloud/ycloud_util.cpp
osquery/utils/ycloud/ycloud_util.h
specs/ycloud_instance_metadata.table

Added `cloud_id` column for `ycloud_instance_metadata` table. 
`cloud_id` is a container for resources in Yandex Cloud which is similar to a "project" in Google Cloud Platform. This change will allow people that use osquery in Yandex Cloud to get more information about the resource path of their virtual machines.

Added cloud_id to ycloud_instance_metadata - the vm metadata table for Yandex Cloud

---

README.md

Following on from a quick discussion on Slack. I've added a table to show case the available fleet managers for Osquery.

Add a list of Osquery fleet managers

---

osquery/tables/system/linux/disk_encryption.cpp
specs/posix/disk_encryption.table

This change will rely on #8037
Functionally this should minimize getting encryption status from parent devices, but without the constraint being added in block_devices this will not perform well.
Below is the process of acquiring crypt status and overall what is different. 
1. Query block devices all or by name constraint
2. Generate encryption row for each queried block device
- If current block device has encryption
- Set the encryption row with those values
- If current block device does not have valid encryption
- If we have a parent block device defined
- If we need to create the parent's encryption status
- If we need to query the parent block device
- Query the parent block device
- Generate parent encryption status
- If we have already generated an encryption status for the parent …

Update linux `disk_encryption` to recursively query parent crypt status

---

osquery/tables/networking/darwin/wifi_survey.mm

This is on Sonoma by the way; all the retrieved networks/ssids are empty. This is just a hotfix.

wifi_survey: Do not crash if the ssid cannot be retrieved

---

osquery/distributed/tests/distributed_tests.cpp

The constraint was compared in lexicographic order, so `5.10.0` is less than `5.3.0`.
The version doesn't have any specific meaning, so just check the first number.

ci: Fix DistributedTests.test_run_queries_with_denylisted_query test

---

libraries/third_party_libraries_manifest.json

The correct name is `libexpat`, not `expat`.
This was preventing the CI workflow to pick up CVEs.

cve: Fix the expat product name in the libraries manifest

---

.github/workflows/cleanup_ec2_runners.yml

Every now and again, I've caught an ec2 CI node hanging out. To prevent that, this is an attempt at a cleanup script.
It might be interesting to build this into [`osquery/ec2-github-runner`](https://github.com/osquery/ec2-github-runner), but this was easy.

GitHub Action to cleanup at stale ec2 runners

---

libraries/cmake/source/expat/CMakeLists.txt
libraries/cmake/source/expat/README.md
libraries/cmake/source/expat/config/aarch64/expat_config.h
libraries/cmake/source/expat/config/x86_64/expat_config.h
libraries/third_party_libraries_manifest.json

This also resolves CVE-2022-40674 and
CVE-2022-43680.
Depends on #8158
Fixes #8160 
Fixes #8161

cve: Update expat to version 2.5.0

---

tools/tests/test_http_server.py

Our builds on x86 windows have been failing because of deprecated/removed use of ssl.wrap_socket. Now updated to use the SSLContext class

build/tests: for python test http server use SSLContext.wrap_socket() instead of deprecated ssl.wrap_socket()

---

osquery/events/darwin/endpointsecurity_fim.cpp

Slack conversation: https://osquery.slack.com/archives/C08VA3XQU/p1697483297449949
tl;dr: the bug was that we were inadvertently calling the ES mute inversion APIs on each config refresh, causing us to actually lose the mute inversion for file paths and cause a surge of events. 
The fix is to check the ES mute inversion state, and call those APIs only if we are not currently "mute inverted" ( in ES parlance `ES_MUTE_NOT_INVERTED`). This essentially gates the existing code with:
```c++
if (es_muting_inverted(es_file_client_, ES_MUTE_INVERSION_TYPE_TARGET_PATH) == ES_MUTE_NOT_INVERTED) {
...
}
```

macOS: fix EndpointSecurity FIM mute inversion for file paths

---

CHANGELOG.md

docs: Call out in the CHANGELOG the format changes of the status logs decorations

---

osquery/tables/applications/chrome/utils.cpp
osquery/tables/applications/chrome/utils.h

Adds additional Chrome paths, for Google Chrome Beta and Dev, as well as Vivaldi, which are currently not picked up by the chrome extensions table.

Add additional chrome extensions paths

---

.github/workflows/hosted_runners.yml

The check_source_code job was waiting for the same job 2 times, while it should've also waited for the code style job.
Also add a dependency in the build jobs to the libraries manifest check. The general idea is to have quick checks go first and fail everything immediately if something is wrong.

ci: Correct job order

---

cmake/flags.cmake
libraries/cmake/source/boost/CMakeLists.txt

std::unary_function has been removed from C++17,
but boost still needs it.
Only recently in XCode 15 it has been removed; asks Boost to stop using it.
Fixes #8196

build: Temporary workaround to build with XCode 15

---

.github/workflows/hosted_runners.yml

When removing packages to get more space,
don't cause other packages to be installed;
keep one version of temurin Java sdk.
This is necessary because the apt mirrors that the install tries to access are out of date, and this makes the Linux job fail. To update them we would need to call `apt update`, but we really don't want to.

ci: Fix Linux build

---

.github/workflows/cleanup_ec2_runners.yml
.github/workflows/cve_scan_runner.yml
libraries/third_party_libraries_manifest.json
tools/ci/scripts/cve/requirements.txt
tools/ci/scripts/cve/third_party_libraries_cves_scanner.py

- Update nvdlib to use the latest NVD APIs
- Use isVulnerable in the request to only get CVEs for the CPE we are searching for, where the CPE is vulnerable, not all the CVEs that are connected to the CPE.
- Put a limit to the CVE scan and EC2 cleanup workflow.
- Change the create_issues option to create-issues, using the same format for the other options.
- Formatting
The `isVulnerable` parameter fixes the issue where for instance `openldap` has a CVE that reference `openssl`, because the CVE is due to an incorrect usage of `openssl`, but it's **not** a bug/CVE of `openssl`, and the API returns that when searching CVEs for `openssl`.
We then had to ignore those in the manifest. Now they will not be returned instead.
A run can be seen on my repo: …

ci: Update nvdlib to use the latest NVD APIs

---

libraries/cmake/formula/openssl/CMakeLists.txt
libraries/third_party_libraries_manifest.json

This also resolves CVE-2023-5363,
CVE-2023-5678.
Fixes #8187
Fixes #8193

cve: Update openssl to 3.2.0

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/secureboot.mm
specs/secureboot.table

Add the additional columns "description", "allow_kernel_extensions", and "allow_mdm_operations". These correspond to the options presented in the Startup Security Utility.
This has been tested across all the possible configurations on a M2 MacBook Pro with Manual MDM enrollment.
Closes #8195

Add support for Apple Silicon in secureboot table

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/certificates.mm
osquery/tables/system/darwin/keychain.h
osquery/tables/system/darwin/keychain_acl.cpp
osquery/tables/system/darwin/keychain_items.cpp
osquery/tables/system/darwin/keychain_utils.cpp
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/darwin/keychain_test.cpp
specs/certificates.table
specs/darwin/keychain_acls.table
specs/darwin/keychain_items.table

Fixes #7780 
Related issue: https://github.com/fleetdm/fleet/issues/13065
Adding a cache for macOS keychain file accesses.
The cache checks whether a keychain file has been modified by comparing the file's SHA256 hash. If the file has been modified, the cache also checks whether the file has been accessed recently. If it has been accessed within the configured interval, the old cached results are returned.
The cache works independently for each table. This means that multiple tables can access the keychain files within the interval, but each one of them can only do so once.
The following feature flags have been added:
```
--keychain_access_cache                          Use a cache for keychain accesses (default true)
--keychain_access_interval VALUE                 Minimum minutes …
```

Added cache and throttling for `certificates`, `keychain_acls`, and `keychain_items` tables.

---

docs/wiki/deployment/aws-logging.md
docs/wiki/installation/cli-flags.md
osquery/tables/cloud/aws/ec2_instance_tags.cpp
osquery/utils/aws/aws_util.cpp
osquery/utils/aws/aws_util.h
osquery/utils/aws/tests/aws_util_tests.cpp
plugins/logger/aws_firehose.cpp
plugins/logger/aws_firehose.h
plugins/logger/aws_kinesis.cpp
plugins/logger/aws_kinesis.h
plugins/logger/aws_log_forwarder.h
plugins/logger/tests/aws_kinesis_logger_tests.cpp

The `aws_sts_region` flag was controlling the region used by services using STS, like Kinesis and Firehose,
instead of controlling which region to generate the STS credential from. This changes the behavior of the flag so it controls the STS credentials region, and it also adds two new flags, `aws_kinesis_region` and `aws_firehose_region` to control the relative services regions.

fix: Correct the aws_sts_region behavior

---

tools/tests/CMakeLists.txt

This was disabled in the past due to a bug in the build, where on Linux with BPF we would link zlib.so.
This has since been solved, so re-enable the test.

test: re-enable tools_tests_testrelease

---

osquery/tables/applications/browser_firefox.cpp

Add a return when the "addons" member in the extensions JSON is present but it's not an array, to avoid accessing uninitialized memory.
Also check that the "addons" member elements are all objects when trying to access its nested members.
Should fix #8226

fix: Fix a crash in firefox_addons

---

osquery/events/windows/windowseventlogpublisher.cpp

This fixes #8224 
cosine similarity calculation in powershell_events could rollover to using negative indices with special chars in script (#8224)
Converting `auto` type to `unsigned char` will force compiler to treat `chr` as unsigned value which is more in accordance with `size_t` type used for indices in `buffer_freqs` . 
This also provides an accurate value of cosine-similarity of scripts with special characters.

Fix signed/unsigned mismatch in powershell_events

---

osquery/worker/ipc/include/table_ipc_base.h
plugins/config/tls_config.cpp
plugins/logger/kafka_producer.cpp

I went through or uses of `fromString` and checked where we weren't making sure that the correct root node of the JSON tree was of the correct type.
We should also go through all uses of rapidjson and see if all the proper checks when accessing the rest of the JSON nodes are correct (checking that something IsString before doing GetString and so on).

fix: Add stricter checks to JSON parsing

---

osquery/config/config.cpp
osquery/config/config.h
osquery/config/tests/config_tests.cpp

Fixes #8209 
When updating scheduled/pack queries dynamically, the performance stats will be cleared for deleted queries and for queries with updated SQL.
This is done by creating a map of pack/query/SQL of old queries and comparing it to the map for new/updated queries.
I'd like to merge this fix before starting work on a related issue https://github.com/osquery/osquery/issues/7694

Clear performance stats when modifying scheduled/pack query

---

tests/integration/tables/vscode_extensions.cpp

The test was out of sync with the table spec.

test: Fix vscodeExtensions.test_sanity test

---

libraries/cmake/source/googletest/CMakeLists.txt

Although googletest uses python only for its own tests, it still searches for it and the search cannot be removed.
In some configuration, like when using pyenv, CMake requires a shell to be able to find Python; this might not be present if run via the VsCode CMake extension.
While we can pass the Python3_EXECUTABLE path to osquery, googletest will still attempt to search Python in the system, slowing down the configuration phase.

cmake: Pass the osquery python path to googletest

---

.github/workflows/hosted_runners.yml

Github has recently deployed more powerful runners: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
Lets use all the cores and print more stats.

ci: Use all available cores and print more stats

---

libraries/cmake/formula/openssl/CMakeLists.txt
libraries/third_party_libraries_manifest.json

Also fix CVE-2023-6129
Fixes #8255

cve: Update openssl to 3.2.1

---

osquery/tables/applications/CMakeLists.txt
osquery/tables/system/CMakeLists.txt
osquery/tables/system/darwin/connected_displays.mm
osquery/tables/system/darwin/secureboot.mm
osquery/tables/system/tests/CMakeLists.txt
osquery/utils/CMakeLists.txt
osquery/utils/darwin/system_profiler.h
osquery/utils/darwin/system_profiler.mm
osquery/utils/tests/darwin/system_profiler.mm

Move the report retrieval into a utility file and then refactor the two current tables that use it (`connected_displays` and `secureboot`) to use the new helper.
Tested that the tables continue to work on both Intel and ARM64.

Refactor macOS system profile report retrieval

---

libraries/third_party_libraries_manifest.json

Also resolves CVE-2023-7104 and CVE-2024-0232
Fixes #8238 
Fixes #8256

cve: Update sqlite to 3.45.0

---

osquery/config/config.cpp
osquery/config/config.h
osquery/core/sql/query_performance.cpp
osquery/core/sql/query_performance.h
osquery/core/tests/CMakeLists.txt
osquery/core/tests/query_performance_tests.cpp
osquery/database/database.cpp
osquery/database/database.h

Fixes #7694 
This implementation has the following limitation: if user modifies pack_delimiter, then all pack-related data is reset.
Specifically, the old data will still be in DB, and can be viewed with --database_dump, but osquery will now use the new pack_delimiter to save/retrieve the data. To fix this, a larger chunk of code needs to change to track the name of the query without the pack delimiter. I believe it is reasonable not to change pack_delimiter once set.
Also, persistence will only apply to scheduled queries, and not distributed queries.

Persist query performance stats

---

libraries/cmake/source/expat/config/aarch64/expat_config.h
libraries/cmake/source/expat/config/x86_64/expat_config.h
libraries/third_party_libraries_manifest.json

Also resolves CVE-2023-52425 and
CVE-2023-52426
Fixes #8268 
Fixes #8269

cve: Update libexpat to 2.6.0

---

docs/wiki/installation/cli-flags.md
plugins/logger/buffered.cpp
plugins/logger/buffered.h
plugins/logger/tests/buffered_tests.cpp
plugins/logger/tls_logger.cpp
plugins/logger/tls_logger.h

Fixes #8219 
Added exponential backoff for tls_logger when results and/or status logs are unsuccessfully sent. The results and status logs have separate independent backoff timers, but their maximum backoff time config is the same.
The following tls_logger config values can now be updated dynamically via config_tls_endpoint without restarting osquery:
- logger_tls_endpoint
- logger_tls_period
- logger_tls_max_lines
- logger_tls_backoff_max (new)
QA Instructions:
1. Configure logger_tls_endpoint and start osquery.
2. Kill the server that was servicing the endpoint, and watch log requests start to back off.

tls_logger backoff

---

osquery/dispatcher/dispatcher.cpp

`worker_threads` was removed in https://github.com/osquery/osquery/pull/1924. This moves the flag to hidden

Deprecate `worker_threads` flag

---

plugins/config/parsers/auto_constructed_tables.cpp

Fixes #8232
I'm not sure if there are nuances I'm missing or if there is a good way to test this section of code, but this fixes a bug where the _first_ ATC table specified in a conf file is attached twice and the second attempt fails.

Don't add ATC table name to registry until after sqlite DB initialization

---

osquery/tables/system/darwin/unified_log.mm

Relates to #7914 
I narrowed down the/a memory leak in `unified_log` caused from the `OSLogEnumerator`. Unless all objects are enumerated, they are held in memory.
Example:
```
Pre PR:
On startup memory consumption looks like this:
Micah@Macbook-Pro ~/osquery/build (master) $ ps x -p 63022 -o rss,vsz,%mem,pid,command,args | sort -nr | grep -i osquery | grep -v 'grep'
25936 409002864  0.1 63022 /Users/micahsore /Users/micahsorenson/osquery/build/osquery/osqueryd -S
After running a very heavy unified_log query such as:
select count(*) from unified_log where timestamp >= (select unix_time-100000 from time);
The memory jumps and doesn't release after the query is finished:
Micah@Macbook-Pro ~/osquery/build (master) $ ps x -p 63022 -o rss,vsz,%mem,pid,command,args | sort -nr | grep -i osquery …
```

Fix a memory leak in `unified_log`

---

osquery/sql/sqlite_version.cpp
osquery/sql/tests/sql.cpp

There's a small bug in the version collations where the difference in length of the versions is returned when the next character of the longer version is a delimiter, which it should return any segment value difference before length difference.

Fix version collate returning incorrect value when last character is a delimiter

---

osquery/tables/system/windows/os_version.cpp
specs/os_version.table
tests/integration/tables/os_version.cpp

Fixes #7908 and #7663 
The purpose of this PR is to include the build revision to the build number on windows.
**Rationale for this change:**
On executing the query `“select build from os_version;”` the build does not display the full build number including what is called the updated build revision (UBR) , the implementation of os_version uses the Win32_OperatingSystem WMI class to get all the build information, but it does not have any property that returns the UBR.
**How is this fixed:**
Get this information from windows registry and concatenate it to the build value.
Below screen shot shows, how this would look post fix

Add windows UBR to `os_version` table

---

osquery/tables/applications/darwin/browser_plugins.cpp

Fixes #8210 
Simple one line change to correct the file path(s) `genSafariSandboxedExtensions` iterates over. I'm unsure if `listDirectoriesInDirectory` previously returned the path with the ending separator, but it currently does not seem to do so. Since `kSafariAppExtensionsPlistPath` is isolated I decided to just add the path separator instead of digging further.
Example:
```
Pre PR:
/Applications/AdBlock.appContents/PlugIns/%.appex/Contents/Info.plist
Post PR:
/Applications/AdBlock.app/Contents/PlugIns/%.appex/Contents/Info.plist
```

Add missing path separator in Safari Extensions table generator

---

osquery/tables/system/windows/cpu_info.cpp
specs/cpu_info.table
tests/integration/tables/cpu_info.cpp

It looks like windows tracks this, and there was an old PR (#5307) for the update. As the code was simple enough I've ported it forward. 
Co-authored-by: Cameron Haupt <chaupt2013@my.fit.edu>

Update `cpu_info` to include `load_percentage` on windows

---

osquery/tables/system/darwin/homebrew_packages.cpp
specs/darwin/homebrew_packages.table

Resolves https://github.com/osquery/osquery/issues/5327
PR adds the dir `/Caskroom` to the `homebrew_packages` table so it includes any [casks](https://formulae.brew.sh/cask/) installed by the user.
It also adds a new column `type` to distinguish between formulae and casks.
This is important since some binaries will end up in `/usr/local/bin` thus not being reported by any Osquery table.
```
$ which ngrok
/usr/local/bin/ngrok
```
Example query:
```
$ osqueryi "select * from homebrew_packages order by type limit 5;"
+---------------+-----------------------------------+---------------------+----------+
| name          | path                              | version             | type     |
+---------------+-----------------------------------+---------------------+----------+
| ngrok         | …
```

Extend `homebrew_packages` table to include Casks

---

tools/tests/utils.py

* Issue
* profile.py hangs on macOS with following packs enabled
* it-compliance
* vuln-management
```
sudo -E python3  ./tools/analysis/profile.py --config /var/osquery/osquery.conf --shell /usr/local/bin/osqueryi 
...
U:3  C:2  M:3  F:0  D:2  pack_keychain_items (1/1): utilization: 58.14 cpu_time: 1.464740256 memory: 33173504 fds: 4 duration: 2.030775785446167 
Profiling query: select * from deb_packages;
U:3  C:3  M:3  F:3  D:3  pack_deb_packages (1/1): utilization: -1 cpu_time: -1 memory: -1 fds: -1 duration: -1 
Profiling query: select * from apt_sources;
```
* reason being these queries are for ```"platform":"linux"``` and not meant for ```"darwin"```
* Propose fix
* for profiling with packs
* check for platform matching 
* if not matching, skip the query

Fix packs to check for platform before including queries

---

osquery/tables/system/linux/deb_packages.cpp

Fixes #8055 and _partly_ fixes #8286.
By "partly" I mean that with this change running `SELECT * FROM deb_packages;` doesn't generate an INFO error log because `/var/lib/dpkg` doesn't exist, #8286 has some other changes necessary to log errors properly.

`deb_packages` to ignore non existent admindirs

---

osquery/tables/applications/vscode_extensions.cpp

The following was being logged as INFO every time `vscode_extensions` was being queried.
Adding the usual pathExists check to avoid spamming status logs.
Linux host:
```
54038 I0305 15:05:32.666677 210071552 vscode_extensions.cpp:31] Could not read vscode extensions.json from /Users/luk/.vscode-server/extensions/extensions.json
54039 I0305 15:05:32.669131 210071552 vscode_extensions.cpp:31] Could not read vscode extensions.json from /var/root/.vscode/extensions/extensions.json
54040 I0305 15:05:32.669243 210071552 vscode_extensions.cpp:31] Could not read vscode extensions.json from /var/root/.vscode-server/extensions/extensions.json
```
Windows host:
```
I0223 17:08:25.617586  9348 vscode_extensions.cpp:31] Could not read vscode extensions.json from .vscode\extensions\extensions.json …
```

Check path exists first in `vscode_extensions`

---

libraries/cmake/source/sqlite/CMakeLists.txt
libraries/third_party_libraries_manifest.json

See https://github.com/osquery/osquery/issues/8291
This also moves the logic to build in osquery, so that's future proof if we ever want to patch sqlite.
CVE-2023-7104 is fully resolved by not compiling in the session extension, which was anyway unused.
Note that CVE-2024-0232 is not yet present in this version, since the json code is different, given that it didn't yet receive the rework to make it more performant.
I'm not closing the issue since this is a hotfix, we should be properly fixing this issue on our side.

Downgrade sqlite to 3.42 to prevent a regression with required columns

---

.github/workflows/hosted_runners.yml
osquery/process/posix/process.cpp
tools/ci/scripts/macos/package_tests.sh

Don't use the OS python to install dependencies,
but use the one that's installed for the runner itself. Select it with the python action.

CI: Fix macOS python dependencies install step

---

osquery/tables/system/posix/authorized_keys.cpp

Add missing SSH key types that support FIDO2 authentication

---

specs/darwin/time_machine_backups.table
specs/darwin/time_machine_destinations.table

Updated Time Machine table documentation to require FDA, which is needed to read `/Library/Preferences/com.apple.TimeMachine.plist`

Updated Time Machine table documentation to require FDA.

---

osquery/carver/carver.cpp
osquery/carver/carver_utils.cpp
osquery/carver/carver_utils.h
osquery/tables/forensic/carves.cpp

In some instances, it was observed that the size is stored as a JSON string rather than number, resulting in an exception if GetInt was called. Check for the type for backwards compatibility.
Fixes #7756.

Fix crash when carve size is stored as string

---

plugins/config/parsers/auto_constructed_tables.cpp

Reverting #8233 as it made ATC tables unable to attach properly which revealed a race condition between extensions and ATC tables #8323. A fix is in the works with #8324.

Revert #8233

---

CHANGELOG.md

I ran https://github.com/osquery/tools:
```
go run ./cmd/release-notes -changelog ../path/to/CHANGELOG.md -last 5.11.0 -new 5.12.1
go run ./cmd/release-notes -changelog ../path/to/CHANGELOG.md -last 5.12.1 -new 5.12.2
```
[as advised by](https://osquery.slack.com/archives/C08VA3XQU/p1715624555614839) @directionless, and then edited manually.

Add entries for 5.12.1 and 5.12.2 to CHANGELOG.md

---

osquery/distributed/tests/distributed_tests.cpp
osquery/tables/system/windows/windows_security_center.cpp
osquery/tables/system/windows/wmi_bios_info.cpp
osquery/utils/windows/shellitem.cpp

chore: remove repetitive words

---

specs/darwin/package_receipts.table

The query example that is on this page references the pacakge_bom table NOT the package_receipts table.

Update `package_receipts` table example

---

osquery/utils/conversions/castvariant.h

Fixes https://github.com/osquery/osquery/issues/8301
boost::lexical_cast was not using the right precision for double-to-string conversion.
Switched to using std::ostringstream.

Using std::setprecision to get the right precision for double to string conversion.

---

CHANGELOG.md

The tool used picks up the incorrect range of commits.
These are the commits that have been added since 5.12.1: https://github.com/osquery/osquery/compare/5.12.1...5.12.2
Fixes #8346

docs: Correct 5.12.2 changelog

---

osquery/tables/system/ssh_keys.cpp
osquery/tables/system/tests/posix/ssh_keys_tests.cpp
specs/user_ssh_keys.table
tests/integration/tables/user_ssh_keys.cpp

This PR introduces additional columns which use OpenSSL macros to get additional details about PEM keys in user .ssh/ directories. 
- "key_length" uses OpenSSL's EVP_PKEY_bits to get the cryptographic length of the cryptosystem to which the private key belongs, in bits. Definition of cryptographic length is specific to cryptosystem.
- "key_security_bits" uses OpenSSL's EVP_PKEY_security_bits to get the number of security bits of the given key (bits of security as defined in NIST SP800-57).
- "key_group_name" uses OpenSSL's EVP_PKEY_get_group_name to get the group of the private key. Supported for a subset of key_types implemented by OpenSSL.

add additional details for OpenSSL-style keys

---

osquery/tables/system/darwin/process_open_descriptors.cpp

Fix `process_open_sockets` to correctly displays `family` and `protocol` on macOS

---

osquery/tables/networking/curl_certificate.cpp

While running valgrind on osquery it reported an invalid memory access in the curl_certificates table. There is a read and potential write 1 byte past the end of a memory buffer when stripping trailing newline from the end of the formatted X509 extension name. In this PR I remove the spurious check past the end of the buffer and also fix an issue where, if a newline had been found at the end of the buffer, the output included a NIL byte at the end instead of actually shrinking the string as intended.

Fix invalid memory access in `curl_certificates` table

---

osquery/tables/system/python_packages.cpp

Fixes #8257
We should avoid attempting to open metadata files such as METADATA or PKG-INFO if they are not located within the specified paths.

The Python manifest directories, .egg-info and .dist-info, contain flat file hierarchies

---

osquery/tables/system/darwin/firewall.cpp
osquery/tables/system/darwin/firewall.h
osquery/tables/system/tests/darwin/firewall_tests.cpp

Fixes #8349 
In macOS 15 the alf plist has moved to the `/usr/libexec/ApplicationFirewall/` directory.
To fix this I've added the path into a plist path array, then enumerate it for the plist parser.
```
osquery> SELECT os_version.version AS os_version, alf.* FROM os_version, alf;
os_version = 15.0
allow_signed_enabled = 1
firewall_unload = 0
global_state = 0
logging_enabled = 1
logging_option = 0
stealth_enabled = 0
version = 1.7
```

Add new file path for alf plist

---

osquery/tables/system/linux/users.cpp
specs/users.table
tests/integration/tables/users.cpp

#8337
For manual testing I used [this](https://www.analogous.dev/blog/sssd-without-tls/) guide to setup a local OpenLDAP directory server and a Ubuntu VM that uses such server for authentication.
The Ubuntu VM has 51 local users and 2 "remote" users (joe,uid:1005 and julie,uid:1006) in an LDAP directory.
```sqlite
SELECT uid,username FROM users; // returns 51 local users as expected
+-------+---------------------+
| uid   | username            |
+-------+---------------------+
| 0     | root                |
| 1     | daemon              |
| 2     | bin                 |
| 3     | sys                 |
| 4     | sync                |
| 5     | games               |
| 6     | man                 |
| 7     | lp                  |
| 8     | mail                |
| 9     | news …
```

Table `users` on linux by default to return only users in `/etc/passwd`

---

osquery/utils/conversions/castvariant.h

Fixes #8301 
The previous fix was incomplete -- there were still some numbers that were being improperly converted into string.
This fix limits double-to-string conversion to significant digits only, without an extra non-significant digit.

Fixing real precision by limiting precision to 15 digits.

---

osquery/sql/virtual_table.cpp

Previous message: `constraint failed`
New message (example with `SELECT * FROM hash`): `Table hash was queried without a required column in the WHERE clause`

Improve error message when required constraint missing.

---

.github/workflows/hosted_runners.yml
osquery/dispatcher/tests/scheduler.cpp
osquery/tables/system/tests/darwin/firewall_tests.cpp

macOS 11 runners have been deprecated, the oldest image available to test is macOS 12.
Also update the builder to macOS 14, which is now using arm64.
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal

CI: Update macos builder to 14 and tester to 12

---

docs/wiki/introduction/sql.md

Closes https://github.com/osquery/osquery/issues/7392 by updating the explanation in the docs. The website had already been fixed to correctly have an icon indicating which columns are required for certain tables, but the docs still referred to a different icon.
If there is anything technically inaccurate about my explanation in the changed text, please let me know.

Docs: improve explanation of required columns

---

specs/sleuthkit/device_partitions.table

This is a small documentation-only PR because I noticed there was a table, `device_partitions`, with undocumented columns. There is no associated GitHub issue for this, it's just a small update.

Fill in missing column descriptions to spec for `device_partitions`

---

.gitmodules

This PR fixes `util-linux` submodule url. Fixes the following error:
```
stderr: fatal: unable to access 'https://git.kernel.org/pub/scm/utils/util-linux/util-linux/': The requested URL returned error: 502
```

Fix util-linux submodule url

---

osquery/tables/system/linux/apparmor_profiles.cpp
specs/linux/apparmor_profiles.table

AppArmor changed the `SECURITY_APPARMOR_HASH` from sha1 to sha256 on the Linux kernel 6.8, thus breaking the `apparmor_profiles` table (#8344):
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=237c31cb5d83b3f77715f6d6a185f46a5ee4ec88
This adds a new `sha256` column to the `apparmor_profiles` table to address this change.

Add `sha256` hash to `apparmor_profiles` table

---

.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml
tools/ci/Makefile
tools/ci/osquery-ubuntu20.04-toolchain.dockerfile

You can see a successful run on aarch64 here: https://github.com/osquery/osquery/actions/runs/9812533295
This fixes a problem with some actions that started using Node.js 20, which is not compatible with the Linux Docker images we are using.
It's also a base for a soon to be happening update of all our actions to the latest version, to use Node.js 20+, since the previous versions will be deprecated.

ci: Update Linux Docker image to Ubuntu 20.04 

---

osquery/tables/system/darwin/firewall.cpp
osquery/tables/system/darwin/firewall.h
osquery/tables/system/tests/darwin/firewall_tests.cpp

With Beta 3 of macOS 15 there's been confirmation in Apples release notes that "Application Firewall settings are no longer contained in a property list.".
Instead, Apple says to use the command line tool `socketfilterfw`. The previous PR for the alf plist path change will not work and may result in false data being returned.
While this PR doesn't solve the issue, it'll revert the possibility of false data from the `libexec` plist. I'm responsible for not catching this in #8352, as my `libexec` plist mirrored my settings at the time and I didn't validate the solution enough.

Revert #8352 (darwin alf plist path change)

---

.gitmodules
libraries/cmake/formula/openssl/CMakeLists.txt

- Upstream xz has disabled cloning from their own repo.
Go back to the Github repository instead,
they have been reinstated a while ago.
- Openssl has updated their website and their downloads moved
totally on Github too. Update the url.
Fixes #8382

build: Correct xz submodule url and openssl download url

---

osquery/filesystem/filesystem.cpp
osquery/filesystem/tests/filesystem.cpp

Fixes https://github.com/osquery/osquery/issues/8354: inotify treats symlinks to individual files as directories.
Demo video of the fix: https://www.loom.com/share/c7044edec1ff47158fd93f49a1b0af63

`listDirectoriesInDirectory` fix -- check if symlinks point to directories

---

osquery/filesystem/filesystem.cpp
osquery/tables/system/posix/suid_bin.cpp

Fixes #8391
Modifies the `recursive_directory_iterator` to the non throwing form
~Looking at our code, I notice that we call `fs::recursive_directory_iterator` in two places. One has a try/catch, one does not. The internet suggests some versions of boost have a bug that causes is_symlink to raise if there's no permissions. They reference https://svn.boost.org/trac/boost/ticket/4494 which doesn't exist any more~

Use non-throw version of `fs::recursive_directory_iterator`

---

osquery/filesystem/fileops.h
osquery/hashing/hashing.cpp
osquery/hashing/hashing.h
osquery/hashing/tests/hashing.cpp

- Don't unnecessarily allocate memory
- Slightly expand the tests to potentially trigger some corner cases in reading and hashing a file
- Add a warning when hashing fails

Minor improvements to the hashing logic

---

osquery/core/core.h
osquery/core/shutdown.cpp
osquery/core/sql/query_data.cpp
osquery/core/sql/scheduled_query.h
osquery/core/tests/process_tests.cpp
osquery/core/watcher.cpp
osquery/logger/logger.cpp
osquery/remote/uri.h
osquery/tables/system/posix/openssl_utils.cpp
osquery/tables/system/tests/system_tables_tests.cpp
osquery/utils/pidfile/tests/pidfile.cpp
osquery/utils/system/posix/time.cpp
osquery/utils/system/time.h
osquery/utils/tests/scope_guard.cpp
tests/integration/tables/process_open_files.cpp

Hey :wave:
These are some includes I had to add to make the project buildable on Arch Linux using Clang 18.1.8.
For context I'm currently in the process of updating the [Arch Linux package for osquery](https://archlinux.org/packages/extra/x86_64/osquery/) and will attempt to upstream as many of the required patches as possible. The complete WIP patchset can be found in this branch: https://github.com/carlsmedstad/osquery/tree/build-on-archlinux
Cheers!

Add missing includes causing compilation error with Clang 18.1.8

---

.github/workflows/hosted_runners.yml

The older v1 action will be deprecated; this also fixes the current CI failure with downloading pre-built macOS tests, since the download-artifact action has been updated making it incompatible.

ci: Update the upload-artifact action to v4.4.0

---

CHANGELOG.md

Ran the following to generate the changes:
```
go run ./cmd/release-notes -changelog /path/to/osquery/CHANGELOG.md -last 5.12.2 -new 5.13.0 > NEW.txt
```
And then edited manually by looking at https://github.com/osquery/osquery/compare/5.12.2...5.13.0.
EDIT: After 5.13.1 was released I manually added the notes for the few commits that were added since then.

Add `CHANGELOG.md` entry for 5.13.1

---

osquery/filesystem/linux/proc.h
osquery/filesystem/tests/filesystem.cpp
osquery/tables/applications/chrome/tests/utils.cpp
osquery/tables/applications/posix/docker.cpp
osquery/tables/events/linux/process_file_events.cpp
osquery/tables/events/windows/powershell_events.cpp
osquery/tables/sleuthkit/sleuthkit.cpp
osquery/utils/aws/aws_util.cpp
tests/integration/tables/mdfind.cpp

Hey again,
This PR contains changes required for compatibility with [Boost 1.86.0](https://www.boost.org/users/history/version_1_86_0.html).
For context, the complete WIP patchset for the [Arch Linux package for osquery](https://archlinux.org/packages/extra/x86_64/osquery/) is maintained in this branch: https://github.com/carlsmedstad/osquery/tree/build-on-archlinux

Boost 1.86 compatibility

---

osquery/tables/system/windows/windows_crashes.cpp

Fixes #8381 
**Issue:** 
Fix for an issue in the 'windows_crashes' table that prevents displaying information related to user mode memory dumps.
**Root Cause:**
1. To display information related to user mode crash dumps, the user has to configure the following on the system, if not done, then no crash dumps are created for user mode application crashes.  The below link has the detailed information, so it could be possible the user has not configured this on end user systems and hence no data related to crash dumps are displayed.
https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
2. The default location for user mode crash dumps if the user has not configured the step (1) as mentioned above is 
**C:\Users\<username>\AppData\Local\CrashDumps** , which can be …

Fix for `windows_crashes` missing information on user mode memory dumps

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/windows/deviceguard_status.cpp
specs/CMakeLists.txt
specs/windows/deviceguard_status.table
tests/integration/tables/CMakeLists.txt
tests/integration/tables/deviceguard_status.cpp

Also fix incorrect comparison causing status data to always return `UNKNOWN`.

Rename `hvci_status` to `deviceguard_status` to better reflect the data collected.

---

osquery/tables/networking/windows/process_open_sockets.cpp

The socket tables are allocated in the constructor for WinSockets, but any failure to allocate is not subsequently checked before using the tables in the parsing routine. This was causing a crash in (possibly temporary) low-memory scenarios.
The fix is to simply check the tables are not null before using them. The fix is to the only location in the code where the tables are referenced.

Fix crash in socket table parsing

---

osquery/tables/applications/darwin/browser_plugins.cpp

We want to have the extension identifier be present in the Extensions.plist, not the opposite.
With a couple of test extensions:
```
osquery> select * from safari_extensions;
uid = 501
name = Safari Extension
identifier = com.1password.safari.extension
version = 8.10.46
sdk = 6.0
update_url =
author =
developer_id =
description =
path = /Applications/1Password for Safari.app/Contents/PlugIns/%.appex/Contents/Info.plist
bundle_version = 81046034
copyright =
extension_type = WebOrAppExtension
uid = 501
name = Ghostery Privacy Ad Blocker Extension
identifier = com.ghostery.extension.safari
version = 10.4.6
sdk = 6.0
update_url =
author =
developer_id =
description =
path = /Applications/Ghostery Privacy Ad Blocker.app/Contents/PlugIns/%.appex/Contents/Info.plist
bundle_version = 29
copyright …
```

Fix: `safari_extensions` not returning results

---

osquery/tables/applications/darwin/browser_plugins.cpp
specs/darwin/safari_extensions.table

Also removes columns which will not have data anymore,
like "author", "update_url", "developer_id" and
"extension_type" since there's no more differentiation necessary.
Updated "path" to reflect its current meaning.
We target macOS 10.15 and updated Safari there is version 15.x.
Since Safari version 13 there's no more support for legacy extensions (.safariextz): https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes#Removed-Features

table: Remove support for deprecated Safari Legacy Extensions

---

osquery/tables/applications/browser_firefox.cpp

`osquery` doesn't list my Firefox addons and I suspect that's because Ubuntu installs it via snap. This PR should add support for Firefox installations installed via snap.

Add support for Firefox addons for snap installations

---

osquery/tables/system/windows/certificates.cpp

There are 2 bugs in the findUserPersonalCertsOnDisk method:-
- The return from CertCreateCertificateContext is not checked, which leads to a subsequent crash in addCertRow etc. should the call fail
- The certificate context, if created, is not freed after use

Fix: Check and free cert context creation in windows certificates table

---

osquery/filesystem/CMakeLists.txt
osquery/filesystem/filesystem.cpp
osquery/filesystem/filesystem.h
osquery/filesystem/tests/filesystem.cpp
osquery/filesystem/tests/linux/proc_tests.cpp
osquery/filesystem/tests/posix/filesystem_tests.cpp
osquery/filesystem/tests/windows/filesystem_tests.cpp
osquery/filesystem/windows/fileops.cpp
osquery/hashing/hashing.cpp
osquery/tables/networking/darwin/wifi.mm
osquery/tables/networking/etc_hosts.cpp
osquery/tables/system/linux/apt_sources.cpp
osquery/tables/system/posix/authorized_keys.cpp
osquery/tables/system/posix/crontab.cpp
osquery/tables/system/posix/shell_history.cpp
osquery/tables/system/python_packages.cpp
osquery/tables/system/ssh_keys.cpp
osquery/utils/status/status.h

- Simplify readFile interface to only support reading full files
- Remove the choice of reading in a blocking way, since we want to prevent hanging
- Remove the dry run read, since it was not useful
- Split the implementation between two overloads, where one supports returning the whole file contents in one go, while the other calls back a predicate everytime some data is read, up to a fixed block size (as with the previous implementation)

improvement: refactor readFile

---

osquery/tables/system/darwin/firewall.h
osquery/tables/system/darwin/firewall.mm
specs/darwin/alf_exceptions.table

#8432
```
osquery> SELECT * FROM alf_exceptions;
+------------------------------------------+-------+
| path                                     | state |
+------------------------------------------+-------+
| io.tailscale.ipn.macos.network-extension | 0     |
| com.apple.sharingd                       | 0     |
| com.allowthistraffic.cmd                 | 0     |
| com.apple.rpcbind                        | 0     |
| com.spotify.client                       | 0     |
| com.apple.cupsd                          | 0     |
| <REDACTED>.com.docker.docker             | 0     |
| com.blockthistraffic.cmd                 | 2     |
| <REDACTED>.com.vmware.fusion             | 0     |
| com.docker.docker                        | 0     |
| com.apple.dt.xcode_select.tool-shim      | 0     |
| …
```

Add support for `alf_exceptions`to macOS 15

---

osquery/tables/system/darwin/firewall.mm
specs/darwin/alf_explicit_auths.table
tests/integration/tables/alf_explicit_auths.cpp

#8433
Looks like there's no "explict auths" in macOS 15 (yet). So let's document it as not supported.

Update table `alf_explicit_auths` as not supported on macOS 15

---

osquery/tables/system/linux/groups.cpp

This PR 
- sets initial buffer size as 16KB
- bumps buffer size when exceeded
Fixes https://github.com/osquery/osquery/issues/8356

Fix linux `groups` table to handle larger group sets by increasing buffer size

---

.github/workflows/hosted_runners.yml

macOS 15 (Sequoia) was released on September 16, 2024.
PS: Alternative is to replace `macos-14` with `macos-15` (to prevent so many jobs).

Run tests on macos-15

---

docs/wiki/deployment/yara.md
osquery/tables/yara/yara.cpp

This allows osquery users to host their yara rules behind an authenticated endpoint.
Allow authentication for yara sigurl requests by enabling this flag. When enabled, osquery will send a POST request with a body containing the node key as in other osquery TLS requests. Server response is expected to be the same as unauthenticated requests: a plaintext yara signature file.

Add --yara_sigurl_authenticate flag

---

osquery/tables/system/windows/registry.cpp

A crash occurs when a string registry value is not null-terminated and this value is the longest in a given key.
This PR substitutes the use of RegQueryValueEx API to RegGetValue which correctly handles non null-terminated string values in the registry.
RegQueryInfoKey API will return the maximum length of a value in a specified key as it exists in the registry, so any string value (REG_SZ etc.) which has been written without a null terminator will result in a cbMaxValueData value for the data only which is incorrect. So, if the non-terminated string value also happens to be the longest value in the given key, the current allocation is not sufficient. 
This change allocates a buffer per-value rather than one buffer based on the size of the largest reported value, which would be wrong.
On …

Fixes crash with non-null-terminated values in registry enumeration

---

tools/tests/test_http_server.py

In some CI runs (eg. https://github.com/osquery/osquery/actions/runs/11383780628/job/31670155405?pr=8421#step:19:2925) the server seems to shut down before the test completes. This is intended to improve reliability by increasing the timeout.

Extend timeout for test HTTP server

---

osquery/tables/system/windows/deviceguard_status.cpp
specs/windows/deviceguard_status.table
tests/integration/tables/deviceguard_status.cpp

This change imports the remaining useful fields presented by the `Win32_DeviceGuard` WMI table.

Add additional WMI data to `deviceguard_status` table

---

osquery/tables/system/darwin/unified_log.mm
specs/darwin/unified_log.table
tests/integration/tables/unified_log.cpp

The log entries timestamp is a double, we need to ensure that it's cast to an integer when returning it as a result to sqlite and using a timestamp constraint, otherwise sqlite will filter out all the entries that have the decimal part in them.

Fix `unified_log` handling of timestamp formats

---

osquery/tables/system/darwin/unified_log.mm
tests/integration/tables/unified_log.cpp

To fix a memory leak,  https://github.com/osquery/osquery/pull/8274 added a lot of excess enumeration work. This, unfortunately, is a horrific performance regression for all `unified_log` usage without a timestamp constraint. 
This adds a somewhat cumbersome additional `WHERE` clause to most of the tests. It's not ideal, but it should cut down on the run time significantly.

Update tests for `unified_log` table to work around slowness

---

CHANGELOG.md

Generated the following way:
```
go run ./cmd/release-notes -github-token ... -changelog ../forks/osquery/CHANGELOG.md -last 5.13.1 -new 5.14.1 > NEW.txt
```
And then edited manually.

Add CHANGELOG.md entry for 5.14.1

---

.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml

As discussed during office hours we want to reduce the amount of scheduled builds to once a day, during a low activity time.

ci: Reduce scheduled builds amount

---

.github/workflows/cleanup_ec2_runners.yml
.github/workflows/cve_scan_runner.yml
.github/workflows/hosted_runners.yml
.github/workflows/self_hosted_runners.yml

All actions using NodeJs < 20 are being deprecated soon.

ci: Update all Github actions to a version using NodeJs 20

---

.github/workflows/hosted_runners.yml

The packaging logic expects to enter into a specific folder to create Windows packages inside.
This folder was not being created and the workflow was not complaining for its absence, using the root of the workspace.
Add the folder as it exists for the other jobs.

CI: Add a specific package build folder on Windows jobs

---

libraries/third_party_libraries_manifest.json

Closes #8415
Closes #8414
Closes #8413
These bugs are about handling untrusted input, but osquery uses expat only to communicate with DBUS, a trusted system level service.
Closes #8442
Closes #8441
Closes #8376
These bugs are about decompressing untrusted archives. However, osquery does not use libarchive for this.
Closes #8403
Closes #8264
We believe this is an NVD error -- NVD lists this as effecting 4.2.0, but we believe it was patched in 4.2.0-rc1. See #8264

Add CVEs to the ignored lists

---

docs/wiki/introduction/sql.md

As discussed in #8443, the docs are misleading. This function is restricted to ascii printable, not just ascii

Update docs to correctly define `conditional_to_base64`

---

.github/workflows/hosted_runners.yml

Also add support to eventually test on multiple versions.
https://github.com/actions/runner-images/issues/10721
Eventually we should move macOS 14 there, and start using its build artifacts too, but I would wait at least until 5.14.x is fully out and when they have caught up with the OS patches.

ci: Update macOS test runner from 12 to 13

---

.github/workflows/hosted_runners.yml
tools/ci/scripts/macos/package_tests.sh

- Change the installed version to 3.13.x
- Don't restrict to a single version on macOS, but let newer minor versions be installed
- Don't use x64 python on macOS arm runners
- Fix python binary substitution in the test files when builder architecture
doesn't correspond with tester architecture.
- Use a sed separator that doesn't create problems with BSD sed, and isn't a regex operator
- Correct the in place option usage if the package_tests.sh is ever used with BSD sed,
since it doesn't work the same as GNU sed

ci: Restrict python versions differently

---

.github/workflows/hosted_runners.yml

The older version has been removed on arm64 runners.
Builds are currently failing: https://github.com/osquery/osquery/actions/runs/11725838783/job/32663117635
Just updating should not be a problem since the deployment target is what drives the compatibility.

ci: Update xcode version for macos-14 from 14.3.1 to 15.4

---

specs/darwin/apps.table
specs/darwin/keychain_items.table
specs/darwin/mdls.table
specs/darwin/package_bom.table
specs/darwin/plist.table
specs/darwin/signature.table

This PR extends the optimized columns for the Darwin platform. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the `IN` optimization.
I've confirmed that the columns can support these changes by querying the tables with an `IN` constraint on the optimized columns. I validated the expected results by comparing returned values from osquery 5.13.1 (before `IN` optimization existed), 5.14.1, and 5.14.1 containing these spec file changes.
With each query I included a `NULL`, `''` (empty string), and some non-existent values in my `IN` constraint.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)`.

Add Darwin platform optimized path columns

---

specs/darwin/authorization_mechanisms.table
specs/darwin/authorizations.table
specs/darwin/power_sensors.table
specs/darwin/smc_keys.table
specs/darwin/temperature_sensors.table

This PR extends the optimized columns for the Darwin platform. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the `IN` optimization.
I've confirmed that the columns can support these changes by querying the tables with an `IN` constraint on the optimized columns. I validated the expected results by comparing returned values from osquery 5.13.1 (before `IN` optimization existed), 5.14.1, and 5.14.1 containing these spec file changes.
With each query I included a `NULL`, `''` (empty string), and some non-existent values in my `IN` constraint.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)`.

Add Darwin platform optimized system-related columns

---

osquery/events/darwin/iokit.cpp

Experiencing random crashes in iokit thread on USB unplug. 
```
Crashed Thread:        22  iokit
Exception Type:        EXC_GUARD (SIGKILL)
Exception Codes:       GUARD_TYPE_MACH_PORT
Exception Codes:       0x0000000000005c03, 0x0000000000000000
...
Thread 22 Crashed:: iokit
0   libsystem_kernel.dylib        	       0x18da69ce4 _kernelrpc_mach_port_deallocate_trap + 8
1   libsystem_kernel.dylib        	       0x18da6b11c mach_port_deallocate + 28
2   IOKit                         	       0x191536678 IODispatchCalloutFromCFMessage + 396
3   CoreFoundation                	       0x18dbbf1d0 __CFMachPortPerform + 296
4   CoreFoundation                	       0x18db922c8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
5   CoreFoundation                	       0x18db921e8 …
```

fix IO objects refcounting

---

specs/curl.table
specs/process_memory_map.table
specs/processes.table

This PR extends the optimized columns for all platforms. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the IN optimization.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)`, Linux Ubuntu: `6.8.0-1018-gcp (Ubuntu …

Add all platform process based and curl optimized columns

---

specs/linux/deb_packages.table
specs/linux/process_namespaces.table
specs/linux/shadow.table

This PR extends the optimized columns for Linux platforms. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the IN optimization.
Tests were ran on Linux Ubuntu: `6.8.0-1018-gcp (Ubuntu 12.3.0-1ubuntu1~22.04)`.

Add Linux platform optimized columns

---

specs/posix/extended_attributes.table
specs/posix/known_hosts.table
specs/posix/process_envs.table
specs/posix/shell_history.table

This PR extends the optimized columns for POSIX platforms. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the IN optimization.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)` and Linux Ubuntu: `6.8.0-1018-gcp (Ubuntu …

Add POSIX platforms optimized columns

---

osquery/tables/applications/vscode_extensions.cpp
specs/vscode_extensions.table
tests/integration/tables/vscode_extensions.cpp

As per this issue -> https://github.com/osquery/osquery/issues/8350 <- this PR introduces VSCode insiders extensions in the `vscode_extensions` table.
This changes:
- `osquery/tables/applications/vscode_extensions.cpp` - Add path for `.vscode-server-insiders` and `.vscode-insiders` `/extensions/extensions.json` files, and also adds a new column named `version_type` to differentiate between `vscode` or `vscode_insiders`.
- Also updates `specs/vscode_extensions.table` and `tests/integration/tables/vscode_extensions.cpp` to include the new column.

Include VSCode Insiders extensions in vscode_extensions table

---

specs/windows/authenticode.table
specs/windows/ntfs_acl_permissions.table
specs/windows/prefetch.table
specs/windows/registry.table

This PR extends the optimized columns for the Windows platform. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the IN optimization.
Tests were ran on Windows 11 Pro: `10.0.22631`.

Add Windows platform optimized columns

---

osquery/utils/status/status.cpp
osquery/utils/status/status.h

Watching `perf` tool shows large amount of `strlen` calls. The reason is in often default message construction that requires calculation of the constant string "OK" length.
Here we move this calculation on program start stage.

utils: Optimize default status message constructor

---

specs/posix/socket_events.table

Per @sharvilshah (and the code) this is not supported on macOS.
Fixes #8073

Move status column to extended_schema for linux socket_events

---

osquery/events/linux/bpf/processcontextfactory.cpp
osquery/events/tests/linux/bpf/processcontextfactory.cpp

Fixes eBPF's parent process pid parsing. The unit test https://github.com/osquery/osquery/blob/6ac7ffb1941703cd1317822c89357fe823b353d2/osquery/events/tests/linux/bpf/processcontextfactory.cpp#L33 should be `33616`, accordingly to the mock data
https://github.com/osquery/osquery/blob/6ac7ffb1941703cd1317822c89357fe823b353d2/osquery/events/tests/linux/bpf/mockedfilesystem.cpp#L20

Fixed eBPF's parsing of parent pid

---

specs/certificates.table
specs/hash.table
specs/npm_packages.table
specs/python_packages.table
specs/utility/file.table

This PR extends the optimized columns for all platforms. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the IN optimization.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)`, Linux Ubuntu: `6.8.0-1018-gcp (Ubuntu …

Add all-platform path-based optimized columns

---

specs/darwin/homebrew_packages.table
specs/darwin/mdfind.table
specs/darwin/nvram.table
specs/darwin/password_policy.table
specs/darwin/preferences.table
specs/darwin/safari_extensions.table

This PR extends the optimized columns for the Darwin platform. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the `IN` optimization.
I've confirmed that the columns can support these changes by querying the tables with an `IN` constraint on the optimized columns. I validated the expected results by comparing returned values from osquery 5.13.1 (before `IN` optimization existed), 5.14.1, and 5.14.1 containing these spec file changes.
With each query I included a `NULL`, `''` (empty string), and some non-existent values in my `IN` constraint.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)`.

Add Darwin platform optimized miscellaneous columns

---

docs/wiki/installation/install-windows.md

solves #7368 
the issue is that installation-windows.md misses double quotes in the path which results in unexpected behavior during installation on Windows.

Add double quotes in Windows installation documentation

---

specs/chrome_extension_content_scripts.table
specs/chrome_extensions.table
specs/firefox_addons.table
specs/ssh_configs.table
specs/user_groups.table
specs/user_ssh_keys.table
specs/vscode_extensions.table

This PR extends the optimized columns for all platforms. I've split up the optimized changes into multiple PRs to make it easier to validate the table generation methods. I've only added tables where I believe and tested the generate methods support the IN optimization.
Tests were ran on macOS Sequoia: `Version 15.2 Beta (24C5079e)`, Linux Ubuntu: `6.8.0-1018-gcp (Ubuntu …

Add all-platform user-based optimized columns

---

osquery/tables/events/darwin/socket_events.cpp
specs/posix/socket_events.table

This is useful for seeing when a new incoming connection is accepted on a listening socket. Includes the remote IP.
Closes #8379.

Add support for accept to macOS table `socket_events`

---

osquery/tables/events/darwin/socket_events.cpp
osquery/tables/events/linux/socket_events.cpp

I think it is easier to understand the results when the values that are not relevant are set to empty/null rather than explicitly set to zero. I think that explicitly setting to zero might be a leftover from the time when osquery couldn't handle empty column values.

Use empty columns instead of zeroes when undefined in socket_events

---

osquery/tables/system/windows/windows_eventlog.cpp

Fixes [#8477](https://github.com/osquery/osquery/issues/8477)
Handles were leaked when querying events using `limit`  constraint.

Fix leak in `windows_events` by using scope_guard

---

osquery/tables/applications/chrome/utils.cpp
osquery/tables/applications/chrome/utils.h

Adds additional chrome_extensions path for Arc on Mac, closing #8377.
This does not add Windows, as I can't test that, and I'm not to sure I find the correct path for it, closest is `%LOCALAPPDATA%\Packages\TheBrowserCompany.Arc_ttt1ap7aakyb4` from https://resources.arc.net/hc/en-us/articles/22353769256471-How-To-Set-Arc-Group-Policies, which _looks_ random.
You may notice the trailing `User Data` on the path, that as far as I can tell is just a quirk of Arcs chromium use, but correct. (The link above mentions plist use on Windows too, so I guess it leaks in both directions (?))

Add arc path to `chrome_extensions` on macOS

---

osquery/events/windows/windowseventlogparser.cpp
osquery/tables/system/tests/windows/windows_eventlog_tests.cpp

Fixes [#7340](https://github.com/osquery/osquery/issues/7340)
For the time being we are only catching the exception to avoid crashing the process.
The schema description is explained on this page [EventType Schema](https://learn.microsoft.com/en-us/windows/win32/wes/eventschema-eventtype-complextype)
The downside of this solution is that we are going to miss the event. In order to get those events, it should be as easy as adding the parsing of xml elements: `DebugData`, `BinaryEventData` and `ProcessingErrorData`. The content of those elements will be flattened out and stored into `row["data"]`. 
E.g.
```
getDataFromPtree("Event.EventData");
getDataFromPtree("Event.UserData");
getDataFromPtree("Event.DebugData");
getDataFromPtree("Event.BinaryEventData"); …
```

Catching generic exception in order to avoid crashing when parsing windows events logs

---

osquery/tables/applications/browser_firefox.cpp

My osquery with debug logs is logging:
> Failed to read the extensions file at: /home/XYZ/.mozilla/firefox/Crash Reports/extensions.json, error: Cannot open file for reading: /home/XYZ/.mozilla/firefox/Crash Reports/extensions.json
> Failed to read the extensions file at: /home/andrea/.mozilla/firefox/Pending Pings/extensions.json, error: Cannot open file for reading: /home/andrea/.mozilla/firefox/Pending Pings/extensions.json
I think we should just exclude those folders from the profiles list.

Update the `browser_firefox` table to exclude "Crash Reports" and "Pending Pings" folders

---

CHANGELOG.md

Generated the following way:
```
go run ./cmd/release-notes -github-token ... -changelog ../forks/osquery/CHANGELOG.md -last 5.14.1 -new 5.15.0 > NEW.txt
```
And then edited the generated notes manually.

Add CHANGELOG.md entry for 5.15.0

---

osquery/tables/system/linux/rpm_packages.cpp
specs/linux/rpm_package_files.table
specs/linux/rpm_packages.table

Currently the RPM table is being generated by initializing the RPM db with all packages, or a single package by name with query context. I've changed this table to start using `rpmdbSetIteratorRE` with string compare, by iterating through all values given in query context, and adding those regex patterns to the RPM iterator selector.
RPM API `rpmdbSetIteratorRE`: https://ftp.osuosl.org/pub/rpm/api/4.4.2.2/group__rpmdb.html#g9f84dbc47d1d432f4ffe83b713fb47c9
This allows the table to generate results with all values from query context at once.
I've confirmed that the columns can support these changes by querying the tables with an IN constraint on the optimized columns. I validated the expected results by comparing returned values from osquery 5.13.1 (before IN optimization existed), 5.14.1, …

Optimize `rpm_packages` and `rpm_package_files` use of query context

---

osquery/tables/system/linux/deb_packages.cpp

For #8286
Fleet: https://github.com/fleetdm/fleet/issues/24877
This PR addresses an issue on CentOS and Fedora (and possibly other) distributions where errors are encountered when attempting to log to a file while generating the `deb_packages` table.  This occurs because we drop permissions while generating this table, which means we don't have access to create the logfile.
The solution in this PR as suggested by @lucasmrod is to buffer the logs while permissions are dropped, and output them after perms are restored.  The number of error logs directly produced by this table is limited by the number of admin dirs specified in the query, so the buffer size isn't a big concern there.  
To test this I set up a Fedora 41 VM.  Running the main branch of osquery with a scheduled query of the …

Buffer error logs in deb_packages table

---

osquery/tables/system/python_packages.cpp
specs/python_packages.table
tests/integration/tables/python_packages.cpp

Added `uid` column to `python_packages`. This makes it easy to scan for packages in user directories. 
Fixes https://github.com/osquery/osquery/issues/8500
From Fleet: https://github.com/fleetdm/fleet/issues/24805
I included some user directories that were missing in the initial scan. `.pyenv` places its python packages in the user directory as well as doing a pip install with the `--user` [flag](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-user) with the homebrew installed python. Here are two example paths from my mac:
`/Users/ksykulev/.pyenv/versions/3.13.1/lib/python3.13/site-packages`
`/Users/ksykulev/Library/Python/3.13/lib/python/site-packages`

Added python packages in user directories

---

osquery/config/config.cpp

We've been seeing some scheduled queries getting unexpectedly deny-listed when osquery is not running with watchdog enabled ([example_denied_query_with_disabled_watchdog.txt](https://github.com/user-attachments/files/18624364/example_denied_query_with_disabled_watchdog.txt)), or when watchdog itself did not stop osquery. Based on the scheduled query definition of the deny-list field, I would expect that it would be deny-listed only by watchdog.
> `denylist`: a boolean to determine if this query may be denylisted (when stopped by the Watchdog for excessive resource consumption), default true
However, there appears to be a bug in `config.cpp` as it does not differentiate between a `failed_query` by the watchdog or osquery dying by another means. Various signals sent to the osquery process …

Fix to only deny-list scheduled queries when watchdog is enabled

---

cmake/flags.cmake
osquery/CMakeLists.txt
osquery/main/windows/main.cpp

Fixes https://github.com/osquery/osquery/issues/7923
From this https://github.com/osquery/osquery/issues/7923#issuecomment-1654679368 I implemented solution 1, switching from main to wmain, as the quickest and cleanest to implement.

[Windows] Switched to wmain to accept non-ascii characters from command line

---

osquery/tables/system/python_packages.cpp

`where directory = '....'` was added in https://github.com/osquery/osquery/pull/4407
When specifying a directory to filter by, the query still executes all the code paths unnecessarily.
```
osquery> select name, version, path from users cross join python_packages using(uid) where python_packages.directory = "/opt/homebrew/lib";
+-----------+---------+----------------------------------------------------------------------+
| name      | version | path                                                                 |
+-----------+---------+----------------------------------------------------------------------+
| packaging | 24.2    | /opt/homebrew/lib/python3.12/site-packages/packaging-24.2.dist-info  |
| numpy     | 2.2.2   | /opt/homebrew/lib/python3.12/site-packages/numpy-2.2.2.dist-info …
```

Fix the `python_paths` table to skip unnecessary code paths when filtering by `directory`

---

CHANGELOG.md

Generated the following way:
```
go run ./cmd/release-notes -github-token ... \
-changelog ../forks/osquery/CHANGELOG.md \
-last 5.15.0 -new 5.16.0 > NEW.txt
```
And then edited the generated notes manually.

Add `CHANGELOG.md` entry for 5.16.0

---

osquery/tables/utility/file.cpp
specs/utility/file.table
tests/integration/tables/file.cpp

Add an empty by default column `symlink_target` that will show the target in case of a symlink.
This is one of many small patches that should help drive #8476  ahead.

Add `symlink_target_path` to `files` tables

---

osquery/events/darwin/endpointsecurity_fim.cpp

Per the docs `es_mute_path_literal `and `es_mute_path_prefix` are deprecated since MacOS 12.0
And  `es_mute_path `is available since 12.0.
So Code needs to align with docs. 
[es_mute_path_literal](https://developer.apple.com/documentation/endpointsecurity/3366122-es_mute_path_literal?language=objc)
[es_mute_path_prefix](https://developer.apple.com/documentation/endpointsecurity/3366123-es_mute_path_prefix?language=objc)
[es_mute_path](https://developer.apple.com/documentation/endpointsecurity/3763102-es_mute_path?language=objc)

Align ES functions with documented macOS versions

---

osquery/events/eventsubscriberplugin.cpp
osquery/events/tests/eventsubscriberplugin.cpp

Fixes https://github.com/osquery/osquery/issues/8524 by ensuring the last events are never expired from a table. Without this change, new event IDs could be unintentionally generated starting from 1, while optimizations tell the generate function to look at a higher ID. All of those newer events would then never be logged.

Fix event expiration to prevent losing events

---

osquery/tables/applications/posix/docker.cpp

At the 27.4.0 docker engine version, there was a change with the "blkio_stats. io_service_bytes_recursive.op" in the container stats API response. The value of the "op" became lowercase, and it caused a mismatch in the getIOBytes function which is called with Capitalised op. 
Example:
getIOBytes(container.get_child("blkio_stats.io_service_bytes_recursive"),"Write");

Fix dicker container table disk/write metrics, compares "op" values with ignore case

---

osquery/remote/http_client.cpp
osquery/remote/http_client.h

I'm currently rebuilding osquery for Boost 1.87 on Arch Linux and have produced this compatibility patch.
These changes are not backwards compatible with Boost 1.86, but that could be fixed with some `#if BOOST_VERSION` checks if needed. Let me know if that's the case.
Thanks!

Boost 1.87 compatibility

---

.github/workflows/hosted_runners.yml

Changes:
- Pin a specific Python version (3.13.1) when installing python on the macos builder and the test_older_macos runner
Motivation:
- Fix the test_older_macos CI tests
- Failures are of the form "Could not start process at /Users/runner/hostedtoolcache/Python/3.13.1/x64/bin/python3" (e.g. [this run](https://github.com/osquery/osquery/actions/runs/13625228685/job/38083016971))
- The macos-13 runner image was [recently updated to have Python 3.13.2](https://github.com/actions/runner-images/commit/1366aad0aa64d0c3c50ec054feba9b8eceb69ccd#diff-49d5008075920b3466eff9e2bb3f4a933cca7733524c0153fd761cf9b6fc4fd4R30) but the other macos runners are still on Python 3.13.1
- Notably, the "Setup python" step in the test_older_macos run shows "Successfully set up CPython (3.13.2)", which …

Pin macos python versions in CI to fix mismatch between builder and test runner

---

osquery/tables/system/darwin/smc_keys.cpp
osquery/tables/system/tests/darwin/smc_tests.cpp

Fixes #7627
Fixes #5896
Fixes https://github.com/fleetdm/fleet/issues/26583
Fixes issues with SMC key readings used by the `temperature_sensors`, `power_sensors` and `fan_speed_sensors` tables.
SMC keys are already mysterious (there is no known definitive reference on the keys) and each new Apple product that comes out seems to have its own opinions about what data type keys should use.  At some point the temperature keys started using the `flt` and `ioft` types which we were not handling.  
Big shout out to @directionless for doing some digging on a previous ticket and leading me to https://github.com/dkorunic/iSMC which at least has a good listing of known types and clues as to how to convert them.  I've updated the code to handle `flt` and `ioft` as well all of the known `fp*`, `sp*`, …

Fix SMC reading values

---

osquery/tables/applications/posix/docker.cpp

I noticed the network metrics from the docker_container_stats table are missing, it started with the 5.14 osquery version. I saw the logic was changed in how to get the cumulative values for the network rx/tx, I changed back to the original solution.

Fixes network metrics

---

tests/integration/tables/mdfind.cpp

- Skip most of the test when spotlight indexing is disabled
- Skip for the specific older macOS job because this fails even when indexing is enabled

Fix flaky mdfind test in CI

---

libraries/cmake/formula/openssl/CMakeLists.txt
libraries/third_party_libraries_manifest.json

Fixes CVE-2024-4741, CVE-2024-4603, CVE-2024-2511, CVE-2024-5535 and CVE-2024-6119.

libs: openssl: 3.2.1 -> 3.4.1

---

osquery/tables/system/linux/apt_sources.cpp
osquery/tables/system/linux/apt_sources.h
osquery/tables/system/tests/linux/apt_sources_tests.cpp

Adds support for the new [DEB822 source format](https://repolib.readthedocs.io/en/latest/deb822-format.html) on the `apt_sources` table. DEB822 is a new format used by Debian-based distributions to describe the sources apt will use when fetching packages.

Add support for DEB822-style apt sources

---

osquery/tables/system/windows/programs.cpp
specs/windows/programs.table
tests/integration/tables/programs.cpp

https://github.com/fleetdm/fleet/issues/27199
This code scans the new registry location for MSIX packages and adds them to the `programs` osquery table. MSIX is the new an improved format designed to replace older formats like MSI, AppX, EXE installers. The Windows App Store uses it.  To learn more about it https://learn.microsoft.com/en-us/windows/msix/overview
The important bits to know about them is that they are scoped by user (see comment below). And a lot of the meta data around the application is contained in a file called `appxmanifest.xml`.
This code walks through the registry and grabs the installed applications. It also parses bits of the appxmanifest.xml file to get relevant data out.

Add support for msix packages

---

osquery/tables/system/CMakeLists.txt
osquery/tables/system/tests/CMakeLists.txt
osquery/tables/system/tests/windows/programs_tests.cpp
osquery/tables/system/windows/programs.cpp
osquery/tables/system/windows/programs.h
specs/windows/programs.table
tests/integration/tables/programs.cpp

For issue https://github.com/fleetdm/fleet/issues/27759
Related to PR https://github.com/osquery/osquery/pull/8585
There are a few identifiers for windows programs. `UpgradeCode` is the unique identifier for MSI applications that is stable between version upgrades. It is different than the `identifying_number` column (which is typically `ProductCode`), as this changes between versions.
https://learn.microsoft.com/en-us/windows/win32/msi/productcode
https://learn.microsoft.com/en-us/windows/win32/msi/upgradecode

Added UpgradeCode to programs table

---

libraries/third_party_libraries_manifest.json

Was #8571.
Fixes #8557 
Fixes CVE-2024-50602, CVE-2024-28757 and CVE-2024-8176.

libs: expat bump from 2.6.0 to 2.7.1

---

osquery/tables/system/windows/system_info.cpp

Querying Win32_Processor for all fields has a performance penalty of 1.1s per CPU core - this is mostly unnoticable on small boxes, but on larger boxes can actualloy have a significant impact on startup performance.  Even on an 8 core system, this takes the startup time for osqueryi from 8.5s to 0.2s

Filter the Win32_Processor query to only required fields

---

tools/tests/utils.py

This pull request adds a print of `stderr` if it exists during performance analysis. This improves the readability of the performance analysis output. 
For example, without printing `stderr`, the output will look like this:
```bash
$ sudo -E python ./tools/analysis/profile.py --query 'SELECT * FROM system_info;'
Profiling query: SELECT * FROM system_info;
U:3  C:3  M:3  F:3  D:3  manual (1/1): utilization: -1 cpu_time: -1 memory: -1 fds: -1 duration: -1 
```
With `stderr` printing:
```bash
Profiling query: SELECT * FROM system_info;
Error: E0417 14:42:06.650187 3823731 virtual_table.cpp:1052] Exception while executing table system_info: Cannot get database value: host_uuid_v3
Query failed (1): Cannot get database value: host_uuid_v3
U:3  C:3  M:3  F:3  D:3  manual (1/1): utilization: -1 …
```

[Performance Analysis] print stderr if exists

---

.github/workflows/hosted_runners.yml

The windows-2019 runner is [being deprecated](https://github.com/actions/runner-images/issues/12045).

Update Windows runner version in hosted_runners.yml

---

libraries/cmake/source/libarchive/config/linux/aarch64/config.h
libraries/cmake/source/libarchive/config/linux/x86_64/config.h
libraries/cmake/source/libarchive/config/macos/aarch64/config.h
libraries/cmake/source/libarchive/config/macos/x86_64/config.h
libraries/cmake/source/libarchive/config/windows/aarch64/config.h
libraries/cmake/source/libarchive/config/windows/x86_64/config.h
libraries/third_party_libraries_manifest.json

Fixes:
* CVE-2023-30571
* CVE-2024-37407
* CVE-2024-48957
* CVE-2024-48958
* CVE-2024-57970
* CVE-2025-1632
* CVE-2025-25724
* CVE-2024-20696
* CVE-2024-26256
* CVE-2024-26256
Fixes #8581
Fixes #8597
Changes:
https://github.com/libarchive/libarchive/releases/tag/v3.7.0 https://github.com/libarchive/libarchive/releases/tag/v3.7.1 https://github.com/libarchive/libarchive/releases/tag/v3.7.2 https://github.com/libarchive/libarchive/releases/tag/v3.7.3 https://github.com/libarchive/libarchive/releases/tag/v3.7.4 https://github.com/libarchive/libarchive/releases/tag/v3.7.5 https://github.com/libarchive/libarchive/releases/tag/v3.7.6 https://github.com/libarchive/libarchive/releases/tag/v3.7.7 https://github.com/libarchive/libarchive/releases/tag/v3.7.8 …

libs: libarchive: 3.6.2 -> 3.7.9

---

osquery/hashing/hashing.cpp

Fixes https://github.com/fleetdm/fleet/issues/28577.
TL;DR: When `hash` table is used as scheduled query, the generated `WARNING` logs fill up the disk space.
Sample:
Without `--verbose`:
```
sudo ./osquery/osqueryi
osquery> SELECT * FROM hash WHERE path = '/Users/lucas/Downloads/Win11_24H2_English_Arm64.iso';
+-----------------------------------------------------+------------------------+-----+------+--------+
| path                                                | directory              | md5 | sha1 | sha256 |
+-----------------------------------------------------+------------------------+-----+------+--------+
| /Users/lucas/Downloads/Win11_24H2_English_Arm64.iso | /Users/lucas/Downloads |     |      |        |
+-----------------------------------------------------+--------------------- …
```

Reduce log noise for `hash` table

---

docs/wiki/introduction/sql.md

This update cleans up a few SQL examples in the docs.

Fix SQL example syntax in SQL introduction docs

---

osquery/sql/virtual_sqlite_table.cpp
plugins/config/parsers/auto_constructed_tables.cpp

Fixes #8630 
When the ATC query fails, attempt to reopen with `immutable=1` option. This works in the case of Firefox databases.

Fix ATC for open Firefox databases

---

.github/workflows/hosted_runners.yml

Reverts osquery/osquery#8633
Originally we needed to do this to get 5.18.1 working on Windows ARM. Now we are bringing back the newer runners so that Windows unit and integration tests will run successfully.
We will still need to figure out why those Windows builds are not actually running on ARM with this runner.

Revert "Revert "Update Windows runner version in hosted_runners.yml (#8618)""

---

specs/os_version.table

This is a small PR to add the version collation to the os_version's `version` column. This will allow easier comparison for queries checking if the os version is below or above a certain release.

Add version collate to os_version table's version column

---

osquery/tables/system/darwin/signature.mm
specs/darwin/signature.table
tests/integration/tables/signature.cpp

Entitlements are returned as JSON, or an empty string if no entitlements are set.
Also added some integration testing to the table.
https://github.com/fleetdm/fleet/issues/25679

Add `entitlements` column to macOS `signature` table

---

osquery/config/config.cpp
osquery/config/config.h
osquery/config/packs.cpp
osquery/config/tests/config_tests.cpp
osquery/database/database.cpp
osquery/database/database.h
osquery/dispatcher/tests/scheduler.cpp
osquery/utils/CMakeLists.txt
osquery/utils/affixes.cpp
osquery/utils/affixes.h
osquery/utils/tests/affixes.cpp

Fixes https://github.com/osquery/osquery/issues/8611
As described in the above issue, Osquery stores the state of the scheduled queries in the `kQueries` domain in RocksDB. The `Config::purge()` function is invoked on every config refresh. It is responsible for purging the stored state of queries that are no longer in the schedule and haven't been executed in the last 7 days. Whenever a query is scheduled, the timestamp for it is updated as `timestamp.<name>` in the `kPersistentSettings` domain. The `Config::purge()` function however, sets the timestamps for all metadata keys in the `kQueries` domain such as `<name>counter`, `<name>epoch`, `query.<name>` as well if not already present. The Osquery scheduler never updates the timestamp for these metadata keys. Every 7 days, …

Fix inconsistent counter resets due to `Config::purge()`

---

CHANGELOG.md

This PR simply adds a reference to the Releases change tracker in the legacy CHANGELOG.md file for consistency.

Update CHANGELOG to point to Releases page.

---

osquery/tables/system/linux/certificates.cpp

This PR fixes an issue where the `certificates` table in osquery returned no results on openSUSE systems.  
The root cause was that osquery did not search in openSUSE's default CA bundle location.
- Added `/var/lib/ca-certificates/ca-bundle.pem` (the canonical openSUSE CA bundle path) to `kDefaultBundlePathList`
- Added a check to only include bundle paths that actually exist on the system.
Fixes: #8649

Add default path for CA certificate bundle on openSUSE

---

osquery/database/database.cpp

This PR makes it so views from osquery configuration files will be skipped in the database migration. This is because the `Conversion from ptree to RapidJSON` fails for config views. Our company has started to use the views within the osquery config, but quickly noticed that a lot of instances of osquery were not creating the views.
After diagnosing, it appears to be when osquery is unable to obtain the current `db_version`, and has to assume version `0`. This then causes osquery to migrate, but the config views are not proper JSON, so it fails to convert them every time. Similar to queries, I added a check to skip keys that start with `config_views.`.
I also added error logging for when the database version value is not obtained as I believe this is useful to know.

Exclude config views from db migration

---

osquery/tables/applications/vscode_extensions.cpp
tests/integration/tables/vscode_extensions.cpp

Observations indicated that the identifier.uuid field was not always populated, while the metadata.id field was always populated with the same data (if it existed in the former).

Make `vscode_extensions` more consistently report UUID

---

osquery/tables/system/windows/system_info.cpp

When the previous changes to lenovo systems were made, hardware_version was used to store the old value. The problem is  we overwrote that everytime so hardware_version, regardless of value would be reset to "-1".
Only set hardware_version when its not previously set.

Don't overwrite hardware_version if it has a value

---

osquery/tables/system/npm_packages.cpp

Adds support for global node packages installed using a version of `node` managed by `nvm`.
A relatively simple change, just adds a couple of directories to search for `npm` packages. Should cover the default locations for `nvm` on macOS and Linux, as well as `nvm-windows` (a similar program for windows).
Related to https://github.com/fleetdm/fleet/issues/32268

Support `nvm` on `npm_packages` table
